// packages/react/src/Select/Select.tsx
'use client';

import {
  DropdownLoadingPosition,
  DropdownOption,
  DropdownStatus as DropdownStatusType,
  DropdownType,
} from '@mezzanine-ui/core/dropdown/dropdown';
import {
  selectClasses as classes,
  SelectInputSize,
} from '@mezzanine-ui/core/select';
import isArray from 'lodash/isArray';
import {
  forwardRef,
  KeyboardEvent,
  MouseEvent,
  useCallback,
  useContext,
  useMemo,
  useRef,
  useState,
} from 'react';
import Dropdown from '../Dropdown';
import { FormControlContext, FormElementFocusHandlers } from '../Form';
import {
  SelectMultipleValueControl,
  UseSelectMultipleValueControl,
  UseSelectSingleValueControl,
  useSelectValueControl,
} from '../Form/useSelectValueControl';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { cx } from '../utils/cx';
import { SelectControlContext } from './SelectControlContext';
import SelectTrigger from './SelectTrigger';
import {
  SelectTriggerInputProps,
  SelectTriggerProps,
  SelectValue,
} from './typings';

export interface SelectBaseProps
  extends Omit<
      SelectTriggerProps,
      | 'active'
      | 'inputProps'
      | 'mode'
      | 'onBlur'
      | 'onChange'
      | 'onClick'
      | 'onFocus'
      | 'onKeyDown'
      | 'onScroll'
      | 'type'
      | 'renderValue'
      | 'value'
    >,
    FormElementFocusHandlers {
  /**
   * Direct options array for dropdown (supports tree structure).
   * If provided, `type` will be automatically set.
   */
  options?: DropdownOption[];
  /**
   * The type of dropdown.
   * @default 'default'
   */
  type?: DropdownType;
  /**
   * The other native props for input element.
   */
  inputProps?: Omit<
    SelectTriggerInputProps,
    | 'onBlur'
    | 'onChange'
    | 'onFocus'
    | 'placeholder'
    | 'role'
    | 'value'
    | `aria-${'controls' | 'expanded' | 'owns'}`
  >;
  /**
   * The max height of the dropdown list.
   */
  menuMaxHeight?: number | string;
  /**
   * Popup menu scroll listener
   */
  onScroll?: (
    computed: { scrollTop: number; maxScrollTop: number },
    target: HTMLDivElement,
  ) => void;
  /**
   * select input placeholder
   */
  placeholder?: string;
  /**
   * Whether the input is readonly.
   * @default false
   */
  readOnly?: boolean;
  /**
   * To customize rendering select input value
   */
  renderValue?(values: SelectValue[] | SelectValue | null): string;
  /**
   * Whether the selection is required.
   * @default false
   */
  required?: boolean;
  /**
   * The size of input.
   */
  size?: SelectInputSize;
  /**
   * The z-index of the dropdown.
   */
  dropdownZIndex?: number | string;
  /**
   * Whether to enable floating-ui `flip` middleware for the dropdown menu.
   * When `true`, the menu flips from below to above the input (and back) along
   * the main axis if it would overflow the viewport, keeping its width and
   * horizontal alignment with the input. Forwarded to the underlying `Dropdown`.
   * @default false
   */
  flip?: boolean;
  /**
   * Whether to enable portal for the dropdown.
   * @default true
   */
  globalPortal?: boolean;
  /**
   * Whether the dropdown is in a loading state.
   * @default false
   */
  loading?: boolean;
  /**
   * The position of the loading indicator.
   * @default 'bottom'
   */
  loadingPosition?: DropdownLoadingPosition;
  /**
   * The text displayed while loading.
   */
  loadingText?: string;
  /**
   * Callback fired when the dropdown list leaves the bottom.
   */
  onLeaveBottom?: () => void;
  /**
   * Callback fired when the dropdown list reaches the bottom.
   */
  onReachBottom?: () => void;
}

export type SelectMultipleProps = SelectBaseProps & {
  /**
   * The default selection
   */
  defaultValue?: SelectValue[];
  /**
   * Controls the layout of trigger.
   */
  mode: 'multiple';
  /**
   * The change event handler of input element.
   */
  onChange?(newOptions: SelectValue[]): void;
  /**
   * To customize rendering select input value
   */
  renderValue?(values: SelectValue[]): string;
  /**
   * The value of selection.
   * @default undefined
   */
  value?: SelectValue[];
};

export type SelectSingleProps = SelectBaseProps & {
  /**
   * The default selection
   */
  defaultValue?: SelectValue;
  /**
   * Controls the layout of trigger.
   */
  mode?: 'single';
  /**
   * The change event handler of input element.
   */
  onChange?(newOptions: SelectValue | null): void;
  /**
   * To customize rendering select input value
   */
  renderValue?(values: SelectValue | null): string;
  /**
   * The value of selection.
   * @default undefined
   */
  value?: SelectValue | null;
};

export type SelectProps = SelectMultipleProps | SelectSingleProps;

/**
 * 下拉選擇元件，支援單選與多選兩種模式。
 *
 * 透過 `mode` 切換 `single`（單選，預設）或 `multiple`（多選，以標籤呈現已選項目）。
 * 傳入 `options` 陣列即可自動建立下拉選單；多選模式下若 options 含有 `children` 巢狀結構，
 * 會自動切換為樹狀選取（`type: 'tree'`）並為所有選項加上勾選框。
 * 支援 `clearable`、`readOnly`、`loading` 狀態，以及透過 `renderValue` 自訂顯示文字。
 *
 * @example
 * ```tsx
 * import Select from '@mezzanine-ui/react/Select';
 *
 * const options = [
 *   { id: '1', name: '選項一' },
 *   { id: '2', name: '選項二' },
 *   { id: '3', name: '選項三' },
 * ];
 *
 * // 單選
 * <Select options={options} placeholder="請選擇" onChange={(val) => console.log(val)} />
 *
 * // 多選
 * <Select mode="multiple" options={options} placeholder="可多選" onChange={(vals) => console.log(vals)} />
 *
 * // 帶搜尋功能（搭配 AutoComplete）
 * <Select options={options} clearable placeholder="選擇或搜尋" />
 * ```
 *
 * @see {@link AutoComplete} 支援自由輸入文字的搜尋下拉元件
 * @see {@link Dropdown} Select 底層使用的下拉清單容器元件
 * @see {@link useSelectValueControl} 用於在受控模式下管理選取值的 Hook
 */
const Select = forwardRef<HTMLDivElement, SelectProps>(
  function Select(props, ref) {
    const {
      disabled: disabledFromFormControl,
      fullWidth: fullWidthFromFormControl,
      required: requiredFromFormControl,
      severity,
    } = useContext(FormControlContext) || {};
    const {
      className,
      clearable = false,
      defaultValue,
      disabled = disabledFromFormControl || false,
      error = severity === 'error' || false,
      fullWidth = fullWidthFromFormControl || false,
      inputProps,
      inputRef,
      loading = false,
      loadingPosition = 'bottom',
      loadingText,
      menuMaxHeight,
      mode = 'single',
      onBlur,
      onChange: onChangeProp,
      onClear: onClearProp,
      onFocus,
      onLeaveBottom,
      onReachBottom,
      onScroll,
      options: optionsProp,
      placeholder = '',
      prefix,
      readOnly = false,
      renderValue,
      required = requiredFromFormControl || false,
      overflowStrategy,
      size,
      suffixActionIcon,
      type = 'default',
      value: valueProp,
      dropdownZIndex,
      flip = false,
      globalPortal = true,
    } = props;

    const dropdownStatus: DropdownStatusType | undefined = loading
      ? 'loading'
      : undefined;

    const [open, toggleOpen] = useState(false);
    const onOpen = useCallback(() => {
      // Prevent opening when readOnly is true
      if (readOnly) {
        return;
      }

      onFocus?.();
      toggleOpen(true);
    }, [onFocus, readOnly]);

    const onClose = useCallback(() => {
      onBlur?.();
      toggleOpen(false);
    }, [onBlur]);

    const {
      onChange,
      onClear: onClearFromControl,
      value,
    } = useSelectValueControl({
      defaultValue,
      mode,
      onChange: onChangeProp,
      onClear: onClearProp,
      onClose,
      value: valueProp,
    } as UseSelectMultipleValueControl | UseSelectSingleValueControl);

    // Wrap onClear and delegate to control hook
    const onClear = useCallback(
      (e: MouseEvent<Element>) => {
        onClearFromControl(e);
      },
      [onClearFromControl],
    );

    const nodeRef = useRef<HTMLDivElement>(null);
    const composedRef = useComposeRefs([ref, nodeRef]);

    // Helper function to recursively add checkbox to all options in tree structure
    const addCheckboxToTreeOptions = useCallback(
      (opts: DropdownOption[]): DropdownOption[] => {
        return opts.map((opt) => ({
          ...opt,
          showCheckbox: true,
          checkSite: 'prefix' as const,
          children: opt.children
            ? addCheckboxToTreeOptions(opt.children)
            : undefined,
        }));
      },
      [],
    );

    const getLeafDescendantIds = useCallback(
      (option: DropdownOption): string[] => {
        const ids = new Set<string>();

        const collect = (opt: DropdownOption) => {
          if (!opt.children || opt.children.length === 0) {
            ids.add(String(opt.id));
          } else {
            opt.children.forEach(collect);
          }
        };

        collect(option);

        return Array.from(ids);
      },
      [],
    );

    const findOptionById = useCallback(
      (id: string, opts: DropdownOption[]): DropdownOption | null => {
        for (const opt of opts) {
          if (String(opt.id) === id) {
            return opt;
          }
          if (opt.children) {
            const found = findOptionById(id, opt.children);
            if (found) {
              return found;
            }
          }
        }
        return null;
      },
      [],
    );

    // Use provided options directly
    const options = useMemo<DropdownOption[]>(() => {
      if (!optionsProp) return [];

      // In tree mode (multiple mode with tree structure), ensure all options have checkbox
      if (mode === 'multiple') {
        const hasTreeStructure = optionsProp.some(
          (opt) => opt.children && opt.children.length > 0,
        );
        if (hasTreeStructure) {
          return addCheckboxToTreeOptions(optionsProp);
        }
      }
      return optionsProp;
    }, [mode, optionsProp, addCheckboxToTreeOptions]);

    // Determine dropdown type based on options structure and mode
    // Tree mode is only available in multiple mode
    const dropdownType = useMemo<DropdownType>(() => {
      if (optionsProp && mode === 'multiple') {
        // If options prop is provided and mode is multiple, check if it has tree structure
        const hasTreeStructure = optionsProp.some(
          (opt) => opt.children && opt.children.length > 0,
        );
        return hasTreeStructure ? 'tree' : type;
      }
      return type;
    }, [optionsProp, type, mode]);

    const dropdownValue = useMemo<string | string[] | undefined>(() => {
      if (!value) return undefined;

      if (Array.isArray(value)) {
        return value.map((v) => String(v.id));
      }

      return String(value.id);
    }, [value]);

    function getPlaceholder() {
      if (typeof renderValue === 'function') {
        return renderValue(value);
      }

      if (value && !isArray(value)) {
        return (value as SelectValue).name;
      }

      return placeholder;
    }

    /**
     * keyboard events for a11y
     * (@todo keyboard event map into option selection when menu is opened)
     */
    const onKeyDownTextField = (evt: KeyboardEvent<Element>) => {
      // Prevent keyboard events from opening when readOnly is true
      if (readOnly) {
        return;
      }

      /** for a11y to open menu via keyboard */
      switch (evt.code) {
        case 'Enter':
          onClose();

          break;
        case 'ArrowUp':
        case 'ArrowRight':
        case 'ArrowLeft':
        case 'ArrowDown': {
          if (!open) {
            onOpen();
          }

          break;
        }
        case 'Tab': {
          if (open) {
            onClose();
          }

          break;
        }

        default:
          break;
      }
    };

    const handleDropdownSelect = useCallback(
      (option: DropdownOption) => {
        if (mode === 'multiple' && dropdownType === 'tree') {
          const onChangeMultiple =
            onChange as SelectMultipleValueControl['onChange'];
          const currentValues = Array.isArray(value) ? value : [];
          const leafDescendantIds = getLeafDescendantIds(option);
          const leafDescendantValues: SelectValue[] = leafDescendantIds.map(
            (id) => {
              const foundOption = findOptionById(id, options);

              return {
                id,
                name: foundOption?.name || id,
              };
            },
          );

          const selectedLeafIds = leafDescendantIds.filter((id) =>
            currentValues.some((v) => String(v.id) === id),
          );
          const allSelected =
            selectedLeafIds.length === leafDescendantIds.length;

          if (allSelected) {
            // Deselect all leaf descendants in a single update
            const leafIdSet = new Set(
              leafDescendantIds.map((id) => String(id)),
            );
            const nextValues = currentValues.filter(
              (v) => !leafIdSet.has(String(v.id)),
            );
            onChangeMultiple(nextValues);
          } else {
            // Select all leaf descendants that are not yet selected in a single update
            const existingIdSet = new Set(
              currentValues.map((v) => String(v.id)),
            );
            const valuesToAdd = leafDescendantValues.filter(
              (descValue) => !existingIdSet.has(String(descValue.id)),
            );
            const nextValues = [...currentValues, ...valuesToAdd];
            onChangeMultiple(nextValues);
          }
        } else {
          // Normal selection logic for non-tree mode
          const selectValue: SelectValue = {
            id: String(option.id),
            name: String(option.name),
          };

          if (mode === 'multiple') {
            onChange(selectValue);
          } else {
            onChange(selectValue);
            onClose();
          }
        }
      },
      [
        mode,
        onChange,
        onClose,
        value,
        dropdownType,
        getLeafDescendantIds,
        findOptionById,
        options,
      ],
    );

    const handleVisibilityChange = useCallback(
      (isOpen: boolean) => {
        if (isOpen && readOnly) {
          return;
        }

        if (isOpen) {
          onOpen();
        } else {
          onClose();
        }
      },
      [onOpen, onClose, readOnly],
    );

    const resolvedInputProps: SelectTriggerInputProps = {
      ...inputProps,
      role: 'combobox',
    };

    const context = useMemo(
      () => ({
        onChange,
        value,
      }),
      [onChange, value],
    );

    return (
      <SelectControlContext.Provider value={context}>
        <div
          ref={nodeRef}
          className={cx(
            classes.host,
            fullWidth && classes.hostFullWidth,
            mode && classes.hostMode(mode),
          )}
        >
          <Dropdown
            disabled={readOnly || disabled}
            flip={flip}
            globalPortal={globalPortal}
            loadingPosition={loadingPosition}
            loadingText={loadingText}
            maxHeight={menuMaxHeight}
            mode={mode}
            onLeaveBottom={onLeaveBottom}
            onReachBottom={onReachBottom}
            onScroll={onScroll}
            onSelect={handleDropdownSelect}
            onVisibilityChange={handleVisibilityChange}
            open={readOnly ? false : open}
            options={options}
            sameWidth
            status={dropdownStatus}
            type={dropdownType}
            value={dropdownValue}
            zIndex={dropdownZIndex}
          >
            <SelectTrigger
              ref={composedRef}
              active={!readOnly && open}
              className={className}
              clearable={clearable}
              disabled={disabled}
              error={error}
              fullWidth={fullWidth}
              inputRef={inputRef}
              mode={mode}
              onTagClose={onChange}
              onClear={onClear}
              onKeyDown={onKeyDownTextField}
              prefix={prefix}
              readOnly={readOnly}
              {...(mode === 'single' && renderValue ? { renderValue } : {})}
              required={required}
              inputProps={resolvedInputProps}
              overflowStrategy={overflowStrategy}
              size={size}
              suffixActionIcon={suffixActionIcon}
              value={value === null ? undefined : value}
              placeholder={getPlaceholder()}
            />
          </Dropdown>
        </div>
      </SelectControlContext.Provider>
    );
  },
);

export default Select;

// packages/vue/select/select.vue
<script setup lang="ts">
import { computed, inject, provide, ref } from 'vue';
import type {
  DropdownOption,
  DropdownStatus,
  DropdownType,
} from '@mezzanine-ui/core/dropdown/dropdown';
import { selectClasses as classes } from '@mezzanine-ui/core/select';
import clsx from 'clsx';
import isArray from 'lodash/isArray';
import { formControlKey } from '../_internal/form-control';
import { useSelectValueControl } from '../_internal/use-select-value-control';
import MznDropdown from '../dropdown/dropdown.vue';
import type { DropdownTriggerProps } from '../dropdown/dropdown.types';
import type { SelectControl, SelectProps, SelectValue } from './select.types';
import { selectControlKey } from './select-control-context';
import MznSelectTrigger from './select-trigger.vue';
import type {
  SelectTriggerInputProps,
  SelectTriggerProps,
} from './select-trigger.types';

/**
 * 下拉選擇元件，支援單選與多選兩種模式。
 *
 * 透過 `mode` 切換 `single`（單選，預設）或 `multiple`（多選，以標籤呈現已選項目）。
 * 傳入 `options` 陣列即可自動建立下拉選單；多選模式下若 options 含有 `children` 巢狀結構，
 * 會自動切換為樹狀選取（`type: 'tree'`）並為所有選項加上勾選框。
 * 支援 `clearable`、`readOnly`、`loading` 狀態，以及透過 `renderValue` 自訂顯示文字。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznSelect } from '@mezzanine-ui/vue/select';
 * <\/script>
 *
 * <template>
 *   <MznSelect :options="options" placeholder="請選擇" @change="onChange" />
 *   <MznSelect mode="multiple" :options="options" placeholder="可多選" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznDropdown Select 底層使用的下拉清單容器元件
 * @see useSelectValueControl 用於在受控模式下管理選取值的 composable
 */
const props = withDefaults(defineProps<SelectProps>(), {
  clearable: false,
  defaultValue: undefined,
  disabled: undefined,
  dropdownZIndex: undefined,
  error: undefined,
  flip: false,
  forceHideSuffixActionIcon: undefined,
  forceShowClearable: undefined,
  fullWidth: undefined,
  globalPortal: true,
  hideSuffixWhenClearable: undefined,
  inputProps: undefined,
  isForceClearable: undefined,
  loading: false,
  loadingPosition: 'bottom',
  loadingText: undefined,
  menuMaxHeight: undefined,
  mode: 'single',
  options: undefined,
  overflowStrategy: undefined,
  placeholder: '',
  readOnly: false,
  renderValue: undefined,
  required: undefined,
  searchText: undefined,
  showTextInputAfterTags: undefined,
  size: undefined,
  suffixAction: undefined,
  suffixActionIcon: undefined,
  type: 'default',
  value: undefined,
  warning: undefined,
});

const emit = defineEmits<{
  /** Fired when the trigger loses focus, which also closes the menu. */
  blur: [];
  /** The change event handler of input element. */
  change: [newOptions: SelectValue[] | SelectValue | null];
  /** Fired when the clear button emptied the selection. */
  clear: [event: MouseEvent];
  /** Fired when the trigger takes focus, which also opens the menu. */
  focus: [];
  /** Callback fired when the dropdown list leaves the bottom. */
  leaveBottom: [];
  /** Callback fired when the dropdown list reaches the bottom. */
  reachBottom: [];
  /** Popup menu scroll listener. */
  scroll: [
    computed: { maxScrollTop: number; scrollTop: number },
    target: HTMLDivElement,
  ];
  /** The click handler for the cross icon on tags. */
  tagClose: [target: SelectValue];
}>();

const slots = defineSlots<{
  /** The trigger's prefix, forwarded to the text field. */
  prefix?: () => unknown;
}>();

const formControl = inject(formControlKey, undefined);

const disabled = computed(
  (): boolean => props.disabled ?? formControl?.value.disabled ?? false,
);
const error = computed(
  (): boolean => props.error ?? formControl?.value.severity === 'error',
);
const fullWidth = computed(
  (): boolean => props.fullWidth ?? formControl?.value.fullWidth ?? false,
);
const required = computed(
  (): boolean => props.required ?? formControl?.value.required ?? false,
);

const dropdownStatus = computed((): DropdownStatus | undefined =>
  props.loading ? 'loading' : undefined,
);

const open = ref(false);

function onOpen(): void {
  // Prevent opening when readOnly is true
  if (props.readOnly) return;

  emit('focus');
  open.value = true;
}

function onClose(): void {
  emit('blur');
  open.value = false;
}

const {
  onChange,
  onClear: onClearFromControl,
  value,
} = useSelectValueControl({
  defaultValue: () => props.defaultValue,
  mode: () => props.mode ?? 'single',
  onChange: (next) => emit('change', next),
  onClear: (event) => emit('clear', event),
  onClose,
  value: () => props.value,
});

// Helper function to recursively add checkbox to all options in tree structure
function addCheckboxToTreeOptions(opts: DropdownOption[]): DropdownOption[] {
  return opts.map((opt) => ({
    ...opt,
    showCheckbox: true,
    checkSite: 'prefix' as const,
    children: opt.children ? addCheckboxToTreeOptions(opt.children) : undefined,
  }));
}

function getLeafDescendantIds(option: DropdownOption): string[] {
  const ids = new Set<string>();

  const collect = (opt: DropdownOption): void => {
    if (!opt.children || opt.children.length === 0) {
      ids.add(String(opt.id));
    } else {
      opt.children.forEach(collect);
    }
  };

  collect(option);

  return Array.from(ids);
}

function findOptionById(
  id: string,
  opts: DropdownOption[],
): DropdownOption | null {
  for (const opt of opts) {
    if (String(opt.id) === id) return opt;

    if (opt.children) {
      const found = findOptionById(id, opt.children);

      if (found) return found;
    }
  }

  return null;
}

const hasTreeStructure = computed((): boolean =>
  Boolean(
    props.options?.some((opt) => opt.children && opt.children.length > 0),
  ),
);

// Use provided options directly
const options = computed((): DropdownOption[] => {
  if (!props.options) return [];

  // In tree mode (multiple mode with tree structure), ensure all options have checkbox
  if (props.mode === 'multiple' && hasTreeStructure.value) {
    return addCheckboxToTreeOptions(props.options);
  }

  return props.options;
});

// Determine dropdown type based on options structure and mode
// Tree mode is only available in multiple mode
const dropdownType = computed((): DropdownType => {
  if (props.options && props.mode === 'multiple') {
    return hasTreeStructure.value ? 'tree' : props.type;
  }

  return props.type;
});

const dropdownValue = computed((): string | string[] | undefined => {
  if (!value.value) return undefined;

  if (Array.isArray(value.value)) {
    return value.value.map((v) => String(v.id));
  }

  return String(value.value.id);
});

const resolvedPlaceholder = computed((): string => {
  if (typeof props.renderValue === 'function') {
    return props.renderValue(value.value);
  }

  if (value.value && !isArray(value.value)) {
    return (value.value as SelectValue).name;
  }

  return props.placeholder;
});

/**
 * keyboard events for a11y
 * (@todo keyboard event map into option selection when menu is opened)
 */
function onKeyDownTextField(event: KeyboardEvent): void {
  // Prevent keyboard events from opening when readOnly is true
  if (props.readOnly) return;

  /** for a11y to open menu via keyboard */
  switch (event.code) {
    case 'Enter':
      onClose();

      break;
    case 'ArrowUp':
    case 'ArrowRight':
    case 'ArrowLeft':
    case 'ArrowDown': {
      if (!open.value) onOpen();

      break;
    }
    case 'Tab': {
      if (open.value) onClose();

      break;
    }

    default:
      break;
  }
}

function handleDropdownSelect(option: DropdownOption): void {
  if (props.mode === 'multiple' && dropdownType.value === 'tree') {
    const currentValues = Array.isArray(value.value) ? value.value : [];
    const leafDescendantIds = getLeafDescendantIds(option);
    const leafDescendantValues: SelectValue[] = leafDescendantIds.map((id) => {
      const foundOption = findOptionById(id, options.value);

      return { id, name: foundOption?.name || id };
    });

    const selectedLeafIds = leafDescendantIds.filter((id) =>
      currentValues.some((v) => String(v.id) === id),
    );
    const allSelected = selectedLeafIds.length === leafDescendantIds.length;

    if (allSelected) {
      // Deselect all leaf descendants in a single update
      const leafIdSet = new Set(leafDescendantIds.map((id) => String(id)));

      onChange(currentValues.filter((v) => !leafIdSet.has(String(v.id))));
    } else {
      // Select all leaf descendants that are not yet selected in a single update
      const existingIdSet = new Set(currentValues.map((v) => String(v.id)));

      onChange([
        ...currentValues,
        ...leafDescendantValues.filter(
          (descValue) => !existingIdSet.has(String(descValue.id)),
        ),
      ]);
    }

    return;
  }

  // Normal selection logic for non-tree mode
  const selectValue: SelectValue = {
    id: String(option.id),
    name: String(option.name),
  };

  onChange(selectValue);

  if (props.mode !== 'multiple') onClose();
}

function handleVisibilityChange(isOpen: boolean): void {
  if (isOpen && props.readOnly) return;

  if (isOpen) onOpen();
  else onClose();
}

const resolvedInputProps = computed(
  (): SelectTriggerInputProps => ({ ...props.inputProps, role: 'combobox' }),
);

provide(
  selectControlKey,
  computed(
    (): SelectControl => ({
      onChange: (v) => onChange(v),
      value: value.value,
    }),
  ),
);

const hostClasses = computed((): string =>
  clsx(classes.host, {
    [classes.hostFullWidth]: fullWidth.value,
    [classes.hostMode(props.mode)]: props.mode,
  }),
);

/**
 * React only forwards `renderValue` to the trigger in single mode, where the
 * trigger's own signature narrows the value to a single one.
 */
const triggerRenderValue = computed((): SelectTriggerProps['renderValue'] =>
  props.mode === 'single' && props.renderValue
    ? (value?: SelectValue | null) => props.renderValue!(value ?? null)
    : undefined,
);
</script>

<template>
  <div :class="hostClasses">
    <MznDropdown
      :disabled="readOnly || disabled"
      :flip="flip"
      :global-portal="globalPortal"
      :loading-position="loadingPosition"
      :loading-text="loadingText"
      :max-height="menuMaxHeight"
      :mode="mode"
      :open="readOnly ? false : open"
      :options="options"
      same-width
      :status="dropdownStatus"
      :type="dropdownType"
      :value="dropdownValue"
      :z-index="dropdownZIndex"
      @leave-bottom="emit('leaveBottom')"
      @reach-bottom="emit('reachBottom')"
      @scroll="
        (computedScroll, target) => emit('scroll', computedScroll, target)
      "
      @select="handleDropdownSelect"
      @visibility-change="handleVisibilityChange"
    >
      <template #default="triggerProps: DropdownTriggerProps">
        <MznSelectTrigger
          v-bind="triggerProps"
          :active="!readOnly && open"
          :clearable="clearable"
          :disabled="disabled"
          :error="error"
          :full-width="fullWidth"
          :input-props="resolvedInputProps"
          :mode="mode"
          :placeholder="resolvedPlaceholder"
          :overflow-strategy="overflowStrategy"
          :read-only="readOnly"
          :render-value="triggerRenderValue"
          :required="required"
          :size="size"
          :suffix-action-icon="suffixActionIcon"
          :value="value === null ? undefined : value"
          @clear="onClearFromControl"
          @keydown="onKeyDownTextField"
          @tag-close="onChange"
        >
          <template v-if="slots.prefix" #prefix
            ><slot name="prefix"
          /></template>
        </MznSelectTrigger>
      </template>
    </MznDropdown>
  </div>
</template>
