// packages/vue/inline-message/inline-message.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  inlineMessageClasses as classes,
  inlineMessageIcons,
} from '@mezzanine-ui/core/inline-message';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznFade from '../transition/fade.vue';
import type { InlineMessageProps } from './inline-message.types';

/**
 * 行內提示訊息。
 *
 * 直接放進版面中呈現情境回饋，需要在關閉時反應請監聽 `close`。
 *
 * 根元素預設帶 `role="status"` 與 `aria-live="polite"`，其餘屬性會原樣轉發；
 * 兩個預設值都可覆寫 — 失敗訊息需要插播時請傳 `aria-live="assertive"`。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInlineMessage } from '@mezzanine-ui/vue/inline-message';
 * <\/script>
 *
 * <template>
 *   <MznInlineMessage content="已儲存草稿" severity="info" />
 *
 *   <MznInlineMessage
 *     aria-live="assertive"
 *     content="送出失敗"
 *     id="submit-error"
 *     severity="error"
 *   />
 * </template>
 * ```
 */
const props = defineProps<InlineMessageProps>();

const emit = defineEmits<{
  close: [];
}>();

/**
 * React spreads the rest props onto the inner div, after `role` and
 * `aria-live` so the consumer can override them. The root here is the fade
 * wrapper, so attributes are forwarded explicitly and in that same order.
 */
defineOptions({ inheritAttrs: false });

const visible = ref(true);

const fadeDuration = {
  enter: MOTION_DURATION.fast,
  exit: MOTION_DURATION.fast,
};
const fadeEasing = {
  enter: MOTION_EASING.standard,
  exit: MOTION_EASING.standard,
};

const icon = computed(() => props.icon ?? inlineMessageIcons[props.severity]);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.severity(props.severity)),
);

function handleClose(): void {
  visible.value = false;
  emit('close');
}

const iconClass = classes.icon;
const contentContainerClass = classes.contentContainer;
const contentClass = classes.content;
</script>

<template>
  <MznFade :duration="fadeDuration" :easing="fadeEasing" :in="visible">
    <div aria-live="polite" role="status" v-bind="$attrs" :class="hostClasses">
      <div :class="contentContainerClass">
        <MznIcon :class="iconClass" :icon="icon" />
        <span :class="contentClass">{{ content }}</span>
      </div>
      <MznClearActions
        v-if="severity === 'info'"
        type="standard"
        variant="base"
        @click="handleClose"
      />
    </div>
  </MznFade>
</template>

// packages/react/src/InlineMessage/InlineMessage.tsx
'use client';

import { forwardRef, useCallback, useMemo, useState } from 'react';

import {
  inlineMessageClasses as classes,
  inlineMessageIcons,
  InlineMessageSeverity,
} from '@mezzanine-ui/core/inline-message';
import { IconDefinition } from '@mezzanine-ui/icons';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';

import ClearActions from '../ClearActions';
import Icon from '../Icon';
import Fade from '../Transition/Fade';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

export interface InlineMessageProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * The content of the inline message value(only string is supported).
   */
  content: string;
  /**
   * The class name of the inline message element.
   */
  className?: string;
  /**
   * The icon of the inline message.
   */
  icon?: IconDefinition;
  /**
   * Called when user clicks the close button.
   */
  onClose?: () => void;
  /**
   * The inline message severity (`'info' | 'warning' | 'error'`).
   */
  severity: InlineMessageSeverity;
}

/**
 * The react component for `mezzanine` inline message.
 *
 * Use `InlineMessage` directly in your layout to display contextual feedback,
 * and provide `onClose` callback when you need to react to dismiss events.
 *
 * The root element defaults to `role="status"` with `aria-live="polite"` and
 * spreads any other DOM prop you pass. Both defaults are overridable — pass
 * `aria-live="assertive"` when a failure needs to interrupt rather than queue.
 *
 * @example
 * ```tsx
 * import InlineMessage from '@mezzanine-ui/react/InlineMessage';
 *
 * // 一般提示（排隊播報）
 * <InlineMessage content="已儲存草稿" severity="info" />
 *
 * // 破壞性操作失敗，需要插播
 * <InlineMessage
 *   aria-live="assertive"
 *   content="送出失敗"
 *   id="submit-error"
 *   severity="error"
 * />
 * ```
 */
const InlineMessage = forwardRef<HTMLDivElement, InlineMessageProps>(
  function InlineMessage(props, ref) {
    const { content, className, icon, onClose, severity, ...rest } = props;
    const [visible, setVisible] = useState(true);

    const handleClose = useCallback(() => {
      setVisible(false);

      if (onClose) {
        onClose();
      }
    }, [onClose]);

    const iconNode = useMemo(() => {
      if (icon) {
        return <Icon className={classes.icon} icon={icon} />;
      }

      const severityIcon = inlineMessageIcons[severity];

      return <Icon className={classes.icon} icon={severityIcon} />;
    }, [icon, severity]);

    return (
      <Fade
        ref={ref}
        duration={{
          enter: MOTION_DURATION.fast,
          exit: MOTION_DURATION.fast,
        }}
        easing={{
          enter: MOTION_EASING.standard,
          exit: MOTION_EASING.standard,
        }}
        in={visible}
      >
        <div
          aria-live="polite"
          role="status"
          {...rest}
          className={cx(classes.host, classes.severity(severity), className)}
        >
          <div className={classes.contentContainer}>
            {iconNode}
            <span className={classes.content}>{content}</span>
          </div>
          {severity === 'info' ? (
            <ClearActions
              onClick={handleClose}
              type="standard"
              variant="base"
            />
          ) : null}
        </div>
      </Fade>
    );
  },
);

export default InlineMessage;
