// packages/react/src/Table/components/TableSelectionCell.tsx
'use client';

import { forwardRef, memo } from 'react';
import {
  tableClasses as classes,
  type TableSelectionMode,
} from '@mezzanine-ui/core/table';
import { cx } from '../../utils/cx';
import Checkbox from '../../Checkbox';
import Radio from '../../Radio';
import Skeleton from '../../Skeleton';
import { useTableContext } from '../TableContext';

export interface TableSelectionCellProps {
  className?: string;
  disabled?: boolean;
  fixed?: boolean;
  fixedOffset?: number;
  hidden?: boolean;
  indeterminate?: boolean;
  isHeader?: boolean;
  /** Selection mode */
  mode?: TableSelectionMode;
  onChange: () => void;
  selected: boolean;
  showShadow?: boolean;
  /** Explicit width for dragging state */
  width?: number;
}

const TableSelectionCellInner = forwardRef<
  HTMLTableCellElement,
  TableSelectionCellProps
>(function TableSelectionCell(props, ref) {
  const { loading } = useTableContext();
  const {
    className,
    disabled = false,
    fixed = false,
    fixedOffset = 0,
    hidden = false,
    indeterminate = false,
    isHeader = false,
    mode = 'checkbox',
    onChange,
    selected,
    showShadow = false,
    width,
  } = props;

  const CellComponent = isHeader ? 'th' : 'td';

  const cellStyle: React.CSSProperties = {};

  // Apply explicit width for dragging state
  if (width !== undefined) {
    cellStyle.width = width;
    cellStyle.minWidth = width;
    cellStyle.maxWidth = width;
    cellStyle.flexShrink = 0;
  }

  if (fixed) {
    (cellStyle as Record<string, string>)['--fixed-start-offset'] =
      `${fixedOffset}px`;
  }

  const renderChild = () => {
    if (hidden) return null;

    if (loading) {
      return <Skeleton width="100%" variant="body-highlight" />;
    }

    if (mode === 'radio') {
      return (
        <Radio checked={selected} disabled={disabled} onChange={onChange} />
      );
    }

    return (
      <Checkbox
        checked={selected}
        disabled={disabled}
        indeterminate={indeterminate}
        onChange={onChange}
      />
    );
  };

  return (
    <CellComponent
      className={cx(
        isHeader ? classes.headerCell : classes.cell,
        classes.selectionCell,
        {
          [classes.cellFixed]: fixed,
          [classes.cellFixedStart]: fixed,
          [classes.cellFixedShadow]: showShadow,
        },
        className,
      )}
      ref={ref}
      scope={isHeader ? 'col' : undefined}
      style={cellStyle}
    >
      <div className={classes.selectionCheckbox}>{renderChild()}</div>
    </CellComponent>
  );
});

export const TableSelectionCell = memo(TableSelectionCellInner);

// packages/vue/table/table-selection-cell.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { CSSProperties } from 'vue';
import { tableClasses as classes } from '@mezzanine-ui/core/table';
import clsx from 'clsx';
import MznCheckbox from '../checkbox/checkbox.vue';
import MznRadio from '../radio/radio.vue';
import MznSkeleton from '../skeleton/skeleton.vue';
import { useTableContext } from './table-context';
import type { TableSelectionCellProps } from './table-selection-cell.types';

/**
 * 表格的選取欄儲存格，表頭是全選、資料列是單列選取。
 *
 * `mode` 為 radio 時渲染單選鈕、表頭不給全選；`hidden` 會讓儲存格保留位置但不放控制項。
 *
 * @example
 * ```vue
 * <template>
 *   <MznTableSelectionCell :selected="isSelected" @change="toggle" />
 * </template>
 * ```
 *
 * @see MznTable 使用它的元件
 */
const props = withDefaults(defineProps<TableSelectionCellProps>(), {
  disabled: false,
  fixed: false,
  fixedOffset: 0,
  hidden: false,
  indeterminate: false,
  isHeader: false,
  mode: 'checkbox',
  showShadow: false,
  width: undefined,
});

const emit = defineEmits<{
  /** Fired when the row's selection is toggled. */
  change: [];
}>();

const table = useTableContext();

const cellComponent = computed((): string => (props.isHeader ? 'th' : 'td'));

const cellStyle = computed((): CSSProperties => {
  const style: CSSProperties = {};

  // Apply explicit width for dragging state
  if (props.width !== undefined) {
    style.width = `${props.width}px`;
    style.minWidth = `${props.width}px`;
    style.maxWidth = `${props.width}px`;
    style.flexShrink = 0;
  }

  if (props.fixed) {
    (style as Record<string, string>)['--fixed-start-offset'] =
      `${props.fixedOffset}px`;
  }

  return style;
});

const cellClasses = computed((): string =>
  clsx(
    props.isHeader ? classes.headerCell : classes.cell,
    classes.selectionCell,
    {
      [classes.cellFixed]: props.fixed,
      [classes.cellFixedStart]: props.fixed,
      [classes.cellFixedShadow]: props.showShadow,
    },
  ),
);
</script>

<template>
  <component
    :is="cellComponent"
    :class="cellClasses"
    :scope="isHeader ? 'col' : undefined"
    :style="cellStyle"
  >
    <div :class="classes.selectionCheckbox">
      <template v-if="!hidden">
        <MznSkeleton
          v-if="table.loading"
          variant="body-highlight"
          width="100%"
        />
        <MznRadio
          v-else-if="mode === 'radio'"
          :checked="selected"
          :disabled="disabled"
          @change="emit('change')"
        />
        <MznCheckbox
          v-else
          :checked="selected"
          :disabled="disabled"
          :indeterminate="indeterminate"
          @change="emit('change')"
        />
      </template>
    </div>
  </component>
</template>
