// packages/vue/dropdown/dropdown-item-card.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue';
import { dropdownClasses as classes } from '@mezzanine-ui/core/dropdown/dropdown';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useHasListener } from '../_internal/use-has-listener';
import MznCheckbox from '../checkbox/checkbox.vue';
import MznIcon from '../icon/icon.vue';
import type { IconColor } from '@mezzanine-ui/core/icon';
import MznSeparator from '../separator/separator.vue';
import MznTypography from '../typography/typography.vue';
import { highlightText, type HighlightSegment } from './highlight-text';
import type { DropdownItemCardProps } from './dropdown-item-card.types';

/**
 * 下拉選單的單一選項列。
 *
 * `checkSite` 決定勾選標記在前綴、後綴或不顯示；`multiple` 模式的前綴是核取方塊，
 * `single` 模式則是勾。`followText` 會把符合的片段標成高亮。
 * `showUnderline` 會在下方再補一條分隔線（第二個 `li`）。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDropdownItemCard } from '@mezzanine-ui/vue/dropdown';
 * <\/script>
 *
 * <template>
 *   <MznDropdownItemCard label="選項一" mode="single" @click="onSelect" />
 * </template>
 * ```
 *
 * @see MznDropdownItem 排出整份清單的元件
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DropdownItemCardProps>(), {
  active: false,
  appendContent: undefined,
  appendIcon: undefined,
  checked: undefined,
  checkSite: undefined,
  defaultChecked: undefined,
  disabled: undefined,
  followText: undefined,
  id: undefined,
  indeterminate: false,
  label: undefined,
  level: undefined,
  name: undefined,
  prependIcon: undefined,
  showUnderline: undefined,
  subTitle: undefined,
  toggleCheckedOnClick: true,
  validate: undefined,
});

const emit = defineEmits<{
  checkedChange: [checked: boolean];
  click: [];
  /**
   * Named the way React spells its prop (`onMouseEnter`): a component emit is
   * camelized, so this is `@mouse-enter` for consumers — not the DOM's own
   * `mouseenter`, which the row still listens to natively below.
   */
  mouseEnter: [];
}>();

const attrs = useAttrs();
const hasListener = useHasListener();

const cardLabel = computed((): string => props.label || '');
const cardName = computed((): string => props.name || cardLabel.value);
const level = computed(() => props.level || 0);

// Generate ID for the label element to use with aria-labelledby
// If no id is provided, we'll rely on the visible text content for accessibility
const labelId = computed((): string | undefined =>
  props.id ? `${props.id}-label` : undefined,
);

// If name is different from label, we need to use aria-label as fallback
const ariaLabel = computed((): string | undefined =>
  cardName.value !== cardLabel.value ? cardName.value : undefined,
);

// Controlled/uncontrolled mode for checked/selected state
const internalChecked = ref(props.defaultChecked ?? false);
const isControlled = computed((): boolean => props.checked !== undefined);
const isChecked = computed((): boolean =>
  isControlled.value ? Boolean(props.checked) : internalChecked.value,
);

const appendIconColor = computed((): IconColor => {
  if (props.disabled) return 'neutral-light';

  if (props.validate === 'danger') return 'error';

  return 'brand';
});

const iconColor = computed((): IconColor => {
  if (props.disabled) return 'neutral-light';

  return props.validate === 'danger' ? 'error' : 'neutral';
});

const labelParts = computed((): HighlightSegment[] =>
  props.followText
    ? highlightText(cardLabel.value, props.followText)
    : [{ text: cardLabel.value, highlight: false }],
);

const subTitleParts = computed((): HighlightSegment[] => {
  if (props.followText && props.subTitle) {
    return highlightText(props.subTitle, props.followText);
  }

  return props.subTitle ? [{ text: props.subTitle, highlight: false }] : [];
});

const showPrependContent = computed((): boolean =>
  Boolean(
    props.prependIcon ||
      (props.checkSite === 'prefix' && props.mode === 'multiple') ||
      (props.checkSite === 'prefix' &&
        props.mode === 'single' &&
        isChecked.value),
  ),
);

const showAppendContent = computed((): boolean =>
  Boolean(
    props.appendContent ||
      props.appendIcon ||
      (props.checkSite === 'suffix' && isChecked.value),
  ),
);

const highlightClass = (part: HighlightSegment): string =>
  part.highlight && props.validate !== 'danger'
    ? classes.cardHighlightedText
    : '';

function toggleChecked(): void {
  if (props.disabled) return;

  const newChecked = !isChecked.value;

  if (!isControlled.value) {
    internalChecked.value = newChecked;
  }

  emit('checkedChange', newChecked);
}

function handleClick(): void {
  if (props.disabled) return;

  if (props.mode === 'multiple' && props.toggleCheckedOnClick) {
    toggleChecked();
  }

  emit('click');
}

function handleCheckboxChange(event: Event): void {
  event.stopPropagation();
  toggleChecked();
}

function handleKeyDown(event: KeyboardEvent): void {
  if (props.disabled) return;

  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    handleClick();
  }
}

/**
 * React only stops propagation on the checkbox when a `onCheckedChange`
 * handler was given; the same condition is read from the listener here.
 */
function checkboxGuards(): Record<string, (event: Event) => void> {
  if (!hasListener('checkedChange')) return {};

  return {
    click: (event: Event) => event.stopPropagation(),
    mousedown: (event: Event) => event.stopPropagation(),
  };
}

const hostClasses = computed((): string =>
  clsx(
    classes.card,
    classes.cardLevel(level.value),
    {
      [classes.cardActive]: props.active || isChecked.value,
      [classes.cardKeyboardActive]: props.active,
      [classes.cardDisabled]: props.disabled,
      [classes.cardDanger]: props.validate === 'danger',
    },
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const cardAppendContentClass = classes.cardAppendContent;
const cardBodyClass = classes.cardBody;
const cardContainerClass = classes.cardContainer;
const cardDescriptionClass = classes.cardDescription;
const cardPrependContentClass = classes.cardPrependContent;
const cardTitleClass = classes.cardTitle;
const cardUnderlineClass = classes.cardUnderline;
</script>

<template>
  <li
    v-bind="forwardedAttrs"
    :aria-label="ariaLabel"
    :aria-labelledby="labelId"
    :aria-selected="isChecked"
    :class="hostClasses"
    :id="id"
    role="option"
    :tabindex="-1"
    @click="handleClick"
    @keydown="handleKeyDown"
    @mouseenter="emit('mouseEnter')"
  >
    <div :class="cardContainerClass">
      <div v-if="showPrependContent" :class="cardPrependContentClass">
        <MznIcon v-if="prependIcon" :color="iconColor" :icon="prependIcon" />
        <MznCheckbox
          v-if="checkSite === 'prefix' && mode === 'multiple'"
          :checked="isChecked"
          :disabled="disabled"
          :indeterminate="indeterminate"
          v-on="checkboxGuards()"
          @change="handleCheckboxChange"
        />
        <MznIcon
          v-if="checkSite === 'prefix' && mode === 'single' && isChecked"
          :color="appendIconColor"
          :icon="CheckedIcon"
          :size="16"
        />
      </div>
      <div :class="cardBodyClass">
        <MznTypography v-if="cardLabel" :class="cardTitleClass" :id="labelId"
          ><span
            v-for="(part, index) in labelParts"
            :key="index"
            :class="highlightClass(part)"
            >{{ part.text }}</span
          ></MznTypography
        >
        <MznTypography
          v-if="subTitleParts.length > 0"
          :class="cardDescriptionClass"
          ><span
            v-for="(part, index) in subTitleParts"
            :key="index"
            :class="highlightClass(part)"
            >{{ part.text }}</span
          ></MznTypography
        >
      </div>
      <div v-if="showAppendContent" :class="cardAppendContentClass">
        <MznTypography v-if="appendContent" color="text-neutral-light">
          {{ appendContent }}
        </MznTypography>
        <MznIcon v-if="appendIcon" :color="iconColor" :icon="appendIcon" />
        <MznIcon
          v-if="checkSite === 'suffix' && isChecked"
          :color="appendIconColor"
          :icon="CheckedIcon"
          :size="16"
        />
      </div>
    </div>
  </li>
  <li v-if="showUnderline" aria-hidden="true" role="presentation">
    <MznSeparator :class="cardUnderlineClass" orientation="horizontal" />
  </li>
</template>

// packages/ng/dropdown/dropdown-item-card.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import {
  dropdownClasses as classes,
  DropdownCheckPosition,
  DropdownItemLevel,
  DropdownItemValidate,
  DropdownMode,
} from '@mezzanine-ui/core/dropdown';
import { CheckedIcon, IconDefinition } from '@mezzanine-ui/icons';
import { MznCheckbox } from '@mezzanine-ui/ng/checkbox';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznSeparator } from '@mezzanine-ui/ng/separator';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import { HighlightSegment, highlightText } from '@mezzanine-ui/ng/utils';
import clsx from 'clsx';

/**
 * Dropdown 選項卡片元件，渲染單一選項列表項目。
 *
 * 支援單選/多選模式的勾選圖示、前置/後置圖示、副標題、
 * 層級縮排與危險驗證樣式。多選模式下 `checkSite='prefix'` 會顯示 Checkbox。
 *
 * @example
 * ```html
 * import { MznDropdownItemCard } from '@mezzanine-ui/ng/dropdown';
 *
 * <div mznDropdownItemCard
 *   label="Option A"
 *   mode="single"
 *   [checked]="isSelected"
 *   (clicked)="onSelect()"
 * ></div>
 * ```
 *
 * @see MznDropdown
 */
@Component({
  selector: '[mznDropdownItemCard]',
  host: {
    '[attr.active]': 'null',
    '[attr.appendContent]': 'null',
    '[attr.appendIcon]': 'null',
    '[attr.checked]': 'null',
    '[attr.checkSite]': 'null',
    '[attr.disabled]': 'null',
    '[attr.followText]': 'null',
    '[attr.id]': 'null',
    '[attr.indeterminate]': 'null',
    '[attr.label]': 'null',
    '[attr.level]': 'null',
    '[attr.mode]': 'null',
    '[attr.prependIcon]': 'null',
    '[attr.showUnderline]': 'null',
    '[attr.subTitle]': 'null',
    '[attr.validate]': 'null',
  },
  standalone: true,
  imports: [MznCheckbox, MznIcon, MznSeparator, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <li
      role="option"
      [attr.id]="id() || null"
      [attr.aria-labelledby]="labelId()"
      [class]="hostClasses()"
      [attr.aria-selected]="checked()"
      [attr.aria-disabled]="disabled() || null"
      [tabIndex]="-1"
      (click)="onClick()"
    >
      <div [class]="containerClass">
        @if (showPrependContent()) {
          <div [class]="prependClass">
            @if (prependIcon()) {
              <i mznIcon [icon]="prependIcon()!"></i>
            }
            @if (checkSite() === 'prefix' && mode() === 'multiple') {
              <div
                mznCheckbox
                [checked]="checked()"
                [disabled]="disabled()"
                [indeterminate]="indeterminate()"
                (click)="$event.stopPropagation()"
                (mousedown)="$event.stopPropagation()"
                (change)="onCheckedChange()"
              ></div>
            }
            @if (checkSite() === 'prefix' && mode() === 'single' && checked()) {
              <i
                mznIcon
                [icon]="checkedIcon"
                [color]="checkIconColor()"
                [size]="16"
              ></i>
            }
          </div>
        }
        <div [class]="bodyClass">
          @if (label()) {
            <p
              mznTypography
              variant="body"
              [class]="titleClass"
              [attr.id]="labelId()"
            >
              @for (part of labelParts(); track $index) {
                <span [class]="part.highlight ? highlightedClass() : ''">{{
                  part.text
                }}</span>
              }
            </p>
          }
          @if (subTitle()) {
            <p mznTypography variant="caption" [class]="descriptionClass">
              @for (part of subTitleParts(); track $index) {
                <span [class]="part.highlight ? highlightedClass() : ''">{{
                  part.text
                }}</span>
              }
            </p>
          }
        </div>
        @if (showAppendContent()) {
          <div [class]="appendClass">
            @if (appendContent()) {
              <span mznTypography color="text-neutral-light">{{
                appendContent()
              }}</span>
            }
            @if (appendIcon()) {
              <i mznIcon [icon]="appendIcon()!" [size]="16"></i>
            }
            @if (checkSite() === 'suffix' && checked()) {
              <i
                mznIcon
                [icon]="checkedIcon"
                [color]="checkIconColor()"
                [size]="16"
              ></i>
            }
          </div>
        }
      </div>
    </li>
    @if (showUnderline()) {
      <li role="presentation" aria-hidden="true">
        <hr mznSeparator orientation="horizontal" [class]="underlineClass" />
      </li>
    }
  `,
})
export class MznDropdownItemCard {
  /** 是否為鍵盤導航高亮狀態。 @default false */
  readonly active = input(false);

  /** 後置文字內容。 */
  readonly appendContent = input<string>();

  /** 後置圖示。 */
  readonly appendIcon = input<IconDefinition>();

  /** 是否被選取。 @default false */
  readonly checked = input(false);

  /** 勾選圖示顯示位置。 @default 'suffix' */
  readonly checkSite = input<DropdownCheckPosition>('suffix');

  /** 是否禁用。 @default false */
  readonly disabled = input(false);

  /**
   * 高亮關鍵字;若提供,會將 `label` / `subTitle` 中(大小寫不敏感)符合的
   * 子字串以 `.mzn-dropdown-item-card-highlighted-text` 包裹。
   * 對應 React 的 `followText` prop(`DropdownItemCard.tsx:68`)。
   */
  readonly followText = input<string>();

  /** DOM id，用於 aria-activedescendant。 */
  readonly id = input<string>();

  /** 是否為不確定狀態（部分子項目被選取）。 @default false */
  readonly indeterminate = input(false);

  /** 選項文字標籤。 */
  readonly label = input<string>();

  /** 層級深度（影響縮排）。 @default 0 */
  readonly level = input<DropdownItemLevel>(0);

  /** 選取模式。 */
  readonly mode = input.required<DropdownMode>();

  /** 前置圖示。 */
  readonly prependIcon = input<IconDefinition>();

  /** 是否在選項下方顯示分隔線。 @default false */
  readonly showUnderline = input(false);

  /** 副標題文字。 */
  readonly subTitle = input<string>();

  /** 驗證樣式。 @default 'default' */
  readonly validate = input<DropdownItemValidate>('default');

  /** 點擊事件。 */
  readonly clicked = output<void>();

  /** 勾選狀態變更事件（多選 prefix 模式）。 */
  readonly checkedChange = output<void>();

  protected readonly checkedIcon = CheckedIcon;
  protected readonly containerClass = classes.cardContainer;
  protected readonly bodyClass = classes.cardBody;
  protected readonly titleClass = classes.cardTitle;
  protected readonly descriptionClass = classes.cardDescription;
  protected readonly prependClass = classes.cardPrependContent;
  protected readonly appendClass = classes.cardAppendContent;
  protected readonly underlineClass = classes.cardUnderline;

  /**
   * 高亮 span 套用的 class。`validate === 'danger'` 時清空,對齊 React
   * `DropdownItemCard.tsx:242`(danger 狀態下不顯示高亮底色)。
   */
  protected readonly highlightedClass = computed((): string =>
    this.validate() === 'danger' ? '' : classes.cardHighlightedText,
  );

  /**
   * 將 `label` 按 `followText` 切成 `{ text, highlight }` 片段陣列,
   * 無 followText 時整段回傳 `highlight: false`。
   * 對應 React `DropdownItemCard.tsx:195-204` 的 `labelParts`。
   */
  protected readonly labelParts = computed(
    (): ReadonlyArray<HighlightSegment> => {
      const label = this.label();

      if (!label) return [];

      const keyword = this.followText();

      return keyword
        ? highlightText(label, keyword)
        : [{ text: label, highlight: false }];
    },
  );

  /**
   * 將 `subTitle` 按 `followText` 切片。無 subTitle 時回傳空陣列。
   * 對應 React `DropdownItemCard.tsx:218-229`。
   */
  protected readonly subTitleParts = computed(
    (): ReadonlyArray<HighlightSegment> => {
      const subTitle = this.subTitle();

      if (!subTitle) return [];

      const keyword = this.followText();

      return keyword
        ? highlightText(subTitle, keyword)
        : [{ text: subTitle, highlight: false }];
    },
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.card, classes.cardLevel(this.level()), {
      [classes.cardActive]: this.active() || this.checked(),
      [classes.cardKeyboardActive]: this.active(),
      [classes.cardDisabled]: this.disabled(),
      [classes.cardDanger]: this.validate() === 'danger',
    }),
  );

  protected readonly showPrependContent = computed((): boolean => {
    const prependIcon = this.prependIcon();
    const checkSite = this.checkSite();
    const mode = this.mode();
    const checked = this.checked();

    return (
      !!prependIcon ||
      (checkSite === 'prefix' && mode === 'multiple') ||
      (checkSite === 'prefix' && mode === 'single' && checked)
    );
  });

  protected readonly showAppendContent = computed((): boolean => {
    const appendContent = this.appendContent();
    const appendIcon = this.appendIcon();
    const checkSite = this.checkSite();
    const checked = this.checked();

    return (
      !!appendContent || !!appendIcon || (checkSite === 'suffix' && checked)
    );
  });

  // Mirror React's appendIconColor: disabled → neutral-light,
  // validate 'danger' → error, otherwise brand.
  protected readonly checkIconColor = computed(
    (): 'neutral-light' | 'error' | 'brand' => {
      if (this.disabled()) return 'neutral-light';
      if (this.validate() === 'danger') return 'error';

      return 'brand';
    },
  );

  /** DOM id for label, used for aria-labelledby. Mirrors React's `${id}-label`. */
  protected readonly labelId = computed((): string | null => {
    const id = this.id();

    return id ? `${id}-label` : null;
  });

  protected onClick(): void {
    if (this.disabled()) return;

    this.clicked.emit();
  }

  protected onCheckedChange(): void {
    if (this.disabled()) return;

    this.checkedChange.emit();
  }
}
