// packages/vue/dropdown/dropdown-status.vue
<script setup lang="ts">
import { computed } from 'vue';
import { dropdownClasses as classes } from '@mezzanine-ui/core/dropdown/dropdown';
import { FolderOpenIcon } from '@mezzanine-ui/icons';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTypography from '../typography/typography.vue';
import type { DropdownStatusProps } from './dropdown-status.types';

/**
 * 下拉選單的載入中／無資料狀態。
 *
 * `loading` 顯示轉圈，其餘顯示資料夾圖示；兩者的文字都可覆寫。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDropdownStatus } from '@mezzanine-ui/vue/dropdown';
 * <\/script>
 *
 * <template>
 *   <MznDropdownStatus status="empty" empty-text="沒有符合的選項" />
 * </template>
 * ```
 *
 * @see MznDropdown 顯示這個狀態的元件
 */
const props = withDefaults(defineProps<DropdownStatusProps>(), {
  emptyIcon: undefined,
  emptyText: undefined,
  loadingText: undefined,
});

const defaultStatusText = computed((): string => {
  if (props.status === 'loading') {
    return props.loadingText ?? 'Loading...';
  }

  if (props.status === 'empty') {
    return props.emptyText ?? 'No matching options.';
  }

  return '';
});

const icon = computed(() => props.emptyIcon ?? FolderOpenIcon);

const statusClass = classes.status;
const statusTextClass = classes.statusText;
</script>

<template>
  <div :class="statusClass">
    <MznSpin v-if="status === 'loading'" loading size="minor" />
    <MznIcon v-else :icon="icon" :size="16" />
    <MznTypography :class="statusTextClass">
      {{ defaultStatusText }}
    </MznTypography>
  </div>
</template>

// packages/ng/dropdown/dropdown-status.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import {
  dropdownClasses as classes,
  DropdownStatus as DropdownStatusType,
} from '@mezzanine-ui/core/dropdown';
import { FolderOpenIcon, IconDefinition } from '@mezzanine-ui/icons';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznSpin } from '@mezzanine-ui/ng/spin';
import { MznTypography } from '@mezzanine-ui/ng/typography';

/**
 * Dropdown 狀態元件，用於顯示載入中或空狀態。
 *
 * 當 `status` 為 `'loading'` 時顯示旋轉指示器，
 * 為 `'empty'` 時顯示空狀態圖示與文字。
 *
 * @example
 * ```html
 * import { MznDropdownStatus } from '@mezzanine-ui/ng/dropdown';
 *
 * <div mznDropdownStatus status="loading" ></div>
 * <div mznDropdownStatus status="empty" emptyText="找不到任何選項。" ></div>
 * ```
 *
 * @see MznDropdown
 */
@Component({
  selector: '[mznDropdownStatus]',
  host: {
    '[class]': 'statusClass',
    '[attr.emptyIcon]': 'null',
    '[attr.emptyText]': 'null',
    '[attr.loadingText]': 'null',
    '[attr.status]': 'null',
  },
  standalone: true,
  imports: [MznIcon, MznSpin, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (status() === 'loading') {
      <div mznSpin [loading]="true" size="minor"></div>
    } @else {
      <i mznIcon [icon]="resolvedEmptyIcon()" [size]="16"></i>
    }
    <span mznTypography variant="body" [class]="statusTextClass">{{
      displayText()
    }}</span>
  `,
})
export class MznDropdownStatus {
  /** 空狀態圖示。 @default FolderOpenIcon */
  readonly emptyIcon = input<IconDefinition>();

  /** 空狀態顯示文字。 @default 'No matching options.' */
  readonly emptyText = input('No matching options.');

  /** 載入中顯示文字。 @default 'Loading...' */
  readonly loadingText = input('Loading...');

  /** 狀態類型。 */
  readonly status = input.required<DropdownStatusType>();

  protected readonly statusClass = classes.status;
  protected readonly statusTextClass = classes.statusText;

  protected readonly resolvedEmptyIcon = computed(
    (): IconDefinition => this.emptyIcon() ?? FolderOpenIcon,
  );

  protected readonly displayText = computed((): string => {
    if (this.status() === 'loading') {
      return this.loadingText();
    }

    return this.emptyText();
  });
}
