// packages/vue/accordion/accordion-title.vue
<script setup lang="ts">
import { computed, h, inject, useSlots } from 'vue';
import type { FunctionalComponent, VNode } from 'vue';
import { accordionClasses as classes } from '@mezzanine-ui/core/accordion';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import MznIcon from '../icon/icon.vue';
import MznRotate from '../transition/rotate.vue';
import MznAccordionActions from './accordion-actions.vue';
import { ACCORDION_CONTROL_CONTEXT } from './accordion-control-context';
import type { AccordionTitleProps } from './accordion-title.types';

/**
 * 手風琴的標題列，點一下切換展開狀態。
 *
 * 標題文字與右側操作是分開的：預設 slot 裡的 MznAccordionActions 會被挑出來放
 * 到右側，其餘內容留在可點擊的按鈕裡。也可以改用 `actions` 設定物件描述右側。
 * 所在的 MznAccordion 為 disabled 時，按鈕跟著停用。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznAccordion, MznAccordionContent, MznAccordionTitle } from '@mezzanine-ui/vue/accordion';
 * <\/script>
 *
 * <template>
 *   <MznAccordion>
 *     <MznAccordionTitle id="faq-1">運送政策</MznAccordionTitle>
 *     <MznAccordionContent>訂單成立後 1-3 個工作天內出貨。</MznAccordionContent>
 *   </MznAccordion>
 * </template>
 * ```
 *
 * @see MznAccordionActions 右側的操作按鈕區
 */
const props = defineProps<AccordionTitleProps>();

defineSlots<{
  /** The title text, and optionally an actions area. */
  default?: () => unknown;
}>();

const slots = useSlots();

const control = inject(ACCORDION_CONTROL_CONTEXT, undefined);

const disabled = computed((): boolean | undefined => control?.value.disabled);
const expanded = computed((): boolean | undefined => control?.value.expanded);

function onToggle(event: MouseEvent | KeyboardEvent): void {
  event.stopPropagation();

  if (control && !disabled.value) {
    control.value.toggleExpanded(!expanded.value);
  }
}

const ariaProps = computed((): Record<string, unknown> => {
  const result: Record<string, unknown> = { 'aria-expanded': expanded.value };
  const contentId = control?.value.contentId;

  if (contentId) {
    result['aria-controls'] = contentId;
  }

  return result;
});

/** The actions written as a child are pulled out of the clickable part. */
const resolved = computed((): { actions: VNode[]; mainPart: VNode[] } => {
  const actions: VNode[] = [];
  const mainPart: VNode[] = [];

  flattenChildren(slots.default?.(), { keepText: true }).forEach((child) => {
    if (child.type === MznAccordionActions) actions.push(child);
    else mainPart.push(child);
  });

  return { actions, mainPart };
});

const hostClasses = computed((): string =>
  clsx(classes.title, {
    [classes.titleExpanded]: expanded.value,
    [classes.titleDisabled]: disabled.value,
  }),
);

const iconClasses = computed((): string =>
  clsx(
    classes.titleIcon,
    { [classes.titleIconDisabled]: disabled.value },
    props.iconClassName,
  ),
);

const MainPart: FunctionalComponent = () => resolved.value.mainPart;
const ChildActions: FunctionalComponent = () => resolved.value.actions;

/**
 * Built with `h` so the config object reaches the actions area as props, the
 * way React spreads it.
 */
const SuffixActions: FunctionalComponent = () =>
  h(MznAccordionActions, props.actions);
</script>

<template>
  <div :class="hostClasses">
    <button
      v-bind="ariaProps"
      :class="classes.titleMainPart"
      :disabled="disabled"
      type="button"
      @click="onToggle"
    >
      <MznRotate :degrees="-90" :in="expanded">
        <MznIcon :class="iconClasses" :icon="ChevronRightIcon" :size="16" />
      </MznRotate>

      <MainPart />
    </button>
    <SuffixActions v-if="actions" />
    <ChildActions v-else />
  </div>
</template>

// packages/ng/accordion/accordion-title.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  OnInit,
} from '@angular/core';
import { accordionClasses as classes } from '@mezzanine-ui/core/accordion';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznRotate } from '@mezzanine-ui/ng/transition';
import { AccordionControl, MZN_ACCORDION_CONTROL } from './accordion-control';

/**
 * 手風琴標題元件，點擊可展開/收合對應的 AccordionContent。
 *
 * 自動從 `MZN_ACCORDION_CONTROL` 讀取展開與禁用狀態，並在 init 時將
 * host 的 `id` 屬性註冊到 control，讓兄弟 AccordionContent 能透過
 * `${id}-content` 形成 a11y 連動（aria-controls / aria-labelledby）。
 *
 * 右側可透過 `<ng-content select="[actions]">` 投射操作按鈕。
 *
 * @example
 * ```html
 * <div mznAccordionTitle id="faq-1">
 *   標題文字
 *   <div actions>
 *     <button>操作</button>
 *   </div>
 * </div>
 * ```
 */
@Component({
  selector: '[mznAccordionTitle]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon, MznRotate],
  host: {
    '[class]': 'hostClasses()',
  },
  template: `
    <button
      [class]="mainPartClass"
      [disabled]="control?.disabled"
      [attr.aria-expanded]="control?.expanded"
      [attr.aria-controls]="control?.contentId"
      type="button"
      (click)="onToggle($event)"
    >
      <i
        mznIcon
        mznRotate
        [class]="iconClasses()"
        [icon]="chevronIcon"
        [size]="16"
        [in]="!!control?.expanded"
        [degrees]="-90"
      ></i>
      <ng-content />
    </button>
    <ng-content select="[actions]" />
  `,
})
export class MznAccordionTitle implements OnInit {
  protected readonly control = inject<AccordionControl>(MZN_ACCORDION_CONTROL, {
    optional: true,
  });
  private readonly elementRef = inject(ElementRef<HTMLElement>);
  protected readonly chevronIcon = ChevronRightIcon;
  protected readonly mainPartClass = classes.titleMainPart;

  protected readonly hostClasses = computed((): string =>
    clsx(classes.title, {
      [classes.titleExpanded]: this.control?.expanded,
      [classes.titleDisabled]: this.control?.disabled,
    }),
  );

  protected readonly iconClasses = computed((): string =>
    clsx(classes.titleIcon, {
      [classes.titleIconDisabled]: this.control?.disabled,
    }),
  );

  ngOnInit(): void {
    const hostId = this.elementRef.nativeElement.getAttribute('id');

    this.control?.setTitleId(hostId);
  }

  protected onToggle(event: MouseEvent): void {
    event.stopPropagation();

    if (this.control && !this.control.disabled) {
      this.control.toggleExpanded(!this.control.expanded);
    }
  }
}
