// packages/vue/text-field/text-field.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, useAttrs, useSlots, watch } from 'vue';
import { textFieldClasses as classes } from '@mezzanine-ui/core/text-field';
import clsx from 'clsx';
import MznClearActions from '../clear-actions/clear-actions.vue';
import type { TextFieldPaddingInfo, TextFieldProps } from './text-field.types';

/**
 * 輸入類元件的視覺外框，包住原生 input 或 textarea。
 *
 * 外框會自動推導 `role`（有 click 監聽時為 `button`，否則 `textbox`）。若內部放的是
 * 真正的 `input` / `textarea`，且命名屬性（例如 `aria-label`）是掛在該原生控制項上，
 * 請傳入 `role="presentation"`，讓 ARIA 語意留在原生控制項。
 *
 * 預設 slot 會收到 `paddingClassName`；一旦取用，外框就不再自行套用內距，
 * 改由使用端決定 — 這對需要 resize handle 貼齊邊界的 textarea 特別有用。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznTextField } from '@mezzanine-ui/vue/text-field';
 * <\/script>
 *
 * <template>
 *   <MznTextField clearable @clear="value = ''">
 *     <input v-model="value" type="text" placeholder="Enter text..." />
 *   </MznTextField>
 *
 *   <MznTextField v-slot="{ paddingClassName }">
 *     <textarea v-model="text" :class="paddingClassName" rows="4" />
 *   </MznTextField>
 * </template>
 * ```
 */
/**
 * Defaults must go through `withDefaults`, not `?? fallback` in a computed:
 * Vue casts an absent Boolean prop to `false` rather than leaving it
 * `undefined`, so `props.fullWidth ?? true` would always resolve to `false`.
 *
 * The three interactive-state props are given an explicit `undefined` default
 * for the same reason in reverse — the auto-detect path depends on being able
 * to tell "not supplied" from "supplied as false", which the Boolean cast
 * would erase.
 */
const props = withDefaults(defineProps<TextFieldProps>(), {
  active: false,
  clearable: false,
  disabled: undefined,
  error: false,
  forceShowClearable: false,
  fullWidth: true,
  hideSuffixWhenClearable: false,
  readonly: undefined,
  size: 'main',
  typing: undefined,
  warning: undefined,
});

const emit = defineEmits<{
  clear: [event: MouseEvent];
}>();

defineSlots<{
  default?: (info: TextFieldPaddingInfo) => unknown;
  prefix?: () => unknown;
  suffix?: () => unknown;
}>();

const attrs = useAttrs();
const slots = useSlots();

const container = ref<HTMLDivElement | null>(null);
const isTyping = ref(false);
const isHovered = ref(false);
const isFocused = ref(false);
const hasValue = ref(false);

const typing = computed((): boolean => {
  if (props.disabled || props.readonly) return false;

  return props.typing ?? isTyping.value;
});

let detach: (() => void) | null = null;
let checkValue: (() => void) | null = null;

/**
 * The value/typing/hover state is read straight off the nested native control,
 * exactly as React does: the field frames a control it does not own, so there
 * is no prop to observe.
 */
function attachToControl(): void {
  detach?.();
  detach = null;
  checkValue = null;

  const element = container.value;

  if (!element) return;

  const input = element.querySelector('input, textarea') as
    | HTMLInputElement
    | HTMLTextAreaElement
    | null;

  if (!input) return;

  const check = (): void => {
    hasValue.value = (input.value || '').trim().length > 0;
  };

  checkValue = check;

  const handleInput = (): void => {
    isTyping.value = true;
    check();
  };
  const handleFocus = (): void => {
    isFocused.value = true;
    check();
  };
  const handleBlur = (): void => {
    isTyping.value = false;
    isFocused.value = false;
    check();
  };
  const handleMouseEnter = (): void => {
    check();
    isHovered.value = true;
  };
  const handleMouseLeave = (): void => {
    isHovered.value = false;
  };

  check();

  const trackTyping =
    props.typing === undefined && !props.disabled && !props.readonly;

  if (trackTyping) {
    input.addEventListener('input', handleInput, false);
    input.addEventListener('mousedown', handleInput, false);
  }

  input.addEventListener('focus', handleFocus, false);
  input.addEventListener('blur', handleBlur, false);
  element.addEventListener('mouseenter', handleMouseEnter, false);
  element.addEventListener('mouseleave', handleMouseLeave, false);
  input.addEventListener('input', check, false);
  input.addEventListener('change', check, false);

  detach = () => {
    if (trackTyping) {
      input.removeEventListener('input', handleInput, false);
      input.removeEventListener('mousedown', handleInput, false);
    }

    input.removeEventListener('focus', handleFocus, false);
    input.removeEventListener('blur', handleBlur, false);
    element.removeEventListener('mouseenter', handleMouseEnter, false);
    element.removeEventListener('mouseleave', handleMouseLeave, false);
    input.removeEventListener('input', check, false);
    input.removeEventListener('change', check, false);
  };
}

watch(
  [container, () => props.typing, () => props.disabled, () => props.readonly],
  attachToControl,
  { flush: 'post', immediate: true },
);

onBeforeUnmount(() => detach?.());

const paddingClassName = computed((): string =>
  clsx(
    classes.inputPadding,
    props.size === 'main' ? classes.inputPaddingMain : classes.inputPaddingSub,
  ),
);

/**
 * React branches on `typeof children === 'function'` to know the consumer took
 * over padding. A Vue scoped slot is always a function, so that test does not
 * exist — but reading the payload does: the slot is invoked once with a getter
 * that records whether `paddingClassName` was destructured. The probe result is
 * discarded, so this costs one extra pass of vnode creation and nothing else.
 */
function consumesPadding(): boolean {
  const slot = slots.default;

  if (!slot) return false;

  let consumed = false;

  slot({
    get paddingClassName() {
      consumed = true;

      return paddingClassName.value;
    },
  });

  return consumed;
}

const hasPrefix = computed(() => !!slots.prefix);
const hasSuffix = computed(() => !!slots.suffix);

const shouldShowClearable = computed(
  () =>
    props.clearable &&
    (props.forceShowClearable || hasValue.value) &&
    (isHovered.value || typing.value || isFocused.value),
);

const fallbackRole = computed((): string =>
  attrs.onClick ? 'button' : 'textbox',
);

function hostClasses(): string {
  return clsx(classes.host, {
    [classes.slimGap]: (hasPrefix.value && hasSuffix.value) || props.clearable,
    [classes.main]: props.size === 'main',
    [classes.sub]: props.size === 'sub',
    [classes.clearable]: props.clearable,
    [classes.disabled]: props.disabled,
    [classes.error]: props.error,
    [classes.fullWidth]: props.fullWidth,
    [classes.noPadding]: consumesPadding(),
    [classes.readonly]: props.readonly,
    [classes.typing]: typing.value,
    [classes.active]: props.active,
    [classes.clearing]: shouldShowClearable.value,
    [classes.warning]: props.warning,
  });
}

function handleClick(event: MouseEvent): void {
  event.stopPropagation();
}

function handleClear(event: MouseEvent): void {
  if (props.disabled || props.readonly) return;

  emit('clear', event);
  requestAnimationFrame(() => checkValue?.());
}

const prefixClass = classes.prefix;
const clearIconClass = classes.clearIcon;
const suffixContentClass = classes.suffixContent;

const suffixClasses = computed((): string =>
  clsx(classes.suffix, {
    [classes.suffixOverlay]: props.hideSuffixWhenClearable,
  }),
);
</script>

<template>
  <div
    ref="container"
    :class="hostClasses()"
    :role="fallbackRole"
    @click="handleClick"
  >
    <div v-if="hasPrefix" :class="prefixClass">
      <slot name="prefix" />
    </div>

    <slot :padding-class-name="paddingClassName" />

    <MznClearActions
      v-if="clearable && !hideSuffixWhenClearable"
      :class="clearIconClass"
      :tabindex="-1"
      type="clearable"
      @click="handleClear"
      @mousedown.prevent
    />

    <div v-if="hasSuffix" :class="suffixClasses">
      <template v-if="hideSuffixWhenClearable">
        <div :class="suffixContentClass">
          <slot name="suffix" />
        </div>
        <MznClearActions
          v-if="clearable"
          :class="clearIconClass"
          :tabindex="-1"
          type="clearable"
          @click="handleClear"
          @mousedown.prevent
        />
      </template>
      <slot v-else name="suffix" />
    </div>
  </div>
</template>

// packages/react/src/TextField/TextField.tsx
'use client';

import {
  textFieldClasses as classes,
  TextFieldSize,
} from '@mezzanine-ui/core/text-field';
import {
  forwardRef,
  MouseEventHandler,
  ReactNode,
  useEffect,
  useRef,
  useState,
} from 'react';
import ClearActions from '../ClearActions';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { useTextFieldControl } from './useTextFieldControl';

/**
 * Padding info provided to children function
 */
export interface TextFieldPaddingInfo {
  /**
   * ClassName that applies the same padding as TextField's current size.
   * Use this when you want to move padding from TextField to input/textarea.
   */
  paddingClassName: string;
}

/**
 * Base props shared by all TextField variants
 */
export interface TextFieldBaseProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'div'>,
    'children' | 'defaultValue' | 'onChange' | 'prefix'
  > {
  /**
   * Whether the field is active (focused/opened/expanded).
   * @default false
   */
  active?: boolean;
  /**
   * The input/textarea element, or a function that receives padding info.
   * When using function form, TextField will not apply padding (you control it).
   */
  children: ReactNode | ((paddingInfo: TextFieldPaddingInfo) => ReactNode);
  /**
   * Additional class name to apply to the root element.
   */
  className?: string;
  /**
   * Whether to show the clear button.
   * @default false
   */
  clearable?: boolean;
  /**
   * Force clear button visibility logic to ignore input value check.
   * @default false
   */
  forceShowClearable?: boolean;
  /**
   * Whether the field is in error state.
   * @default false
   */
  error?: boolean;
  /**
   * Whether the field should take the full width of its container.
   * @default true
   */
  fullWidth?: boolean;
  /**
   * The callback will be fired after clear icon clicked.
   */
  onClear?: MouseEventHandler;
  /**
   * The size of field.
   * @default 'main'
   */
  size?: TextFieldSize;
  /**
   * Whether the field is in warning state.
   * @default false
   */
  warning?: boolean;
}

/**
 * Affix props - prefix and suffix
 */
export type TextFieldAffixProps = {
  /**
   * The prefix addon of the field.
   */
  prefix?: ReactNode;
  /**
   * The suffix addon of the field.
   */
  suffix?: ReactNode;
};

/**
 * Interactive state - typing, disabled, and readonly are mutually exclusive
 */
export type TextFieldInteractiveStateProps =
  | {
    /**
     * Whether the user is currently typing.
     * If not provided, will be auto-detected.
     */
    typing?: boolean;
    disabled?: never;
    readonly?: never;
  }
  | {
    typing?: never;
    /**
     * Whether the field is disabled.
     * @default false
     */
    disabled: true;
    readonly?: never;
  }
  | {
    typing?: never;
    disabled?: never;
    /**
     * Whether the field is readonly.
     * @default false
     */
    readonly: true;
  }
  | {
    typing?: never;
    disabled?: never;
    readonly?: never;
  };

export type TextFieldProps = TextFieldBaseProps &
  TextFieldAffixProps &
  TextFieldInteractiveStateProps;

/**
 * The react component for `mezzanine` text field.
 */
const TextField = forwardRef<HTMLDivElement, TextFieldProps>(
  function TextField(props, ref) {
    const {
      active = false,
      children,
      className,
      clearable = false,
      disabled,
      error = false,
      forceShowClearable = false,
      fullWidth = true,
      onClear,
      onClick: onClickProps,
      onKeyDown: onKeyDownProps,
      prefix,
      readonly,
      role: roleProp,
      size = 'main',
      suffix,
      typing: typingProp,
      warning,
      ...rest
    } = props;

    const [isTyping, setIsTyping] = useState(false);
    const [isHovered, setIsHovered] = useState(false);
    const [isFocused, setIsFocused] = useState(false);
    const [hasValue, setHasValue] = useState(false);
    const containerRef = useRef<HTMLDivElement>(null);
    const checkValueRef = useRef<(() => void) | null>(null);
    const hostRef = useComposeRefs([ref, containerRef]);

    const typing =
      disabled || readonly
        ? false
        : typeof typingProp !== 'undefined'
          ? typingProp
          : isTyping;

    useEffect(() => {
      const container = containerRef.current;
      if (!container) return;

      const input = container.querySelector('input, textarea') as
        | HTMLInputElement
        | HTMLTextAreaElement
        | null;
      if (!input) return;

      const checkValue = () => {
        // 檢查值是否為空（包括空字符串和只有空白字符）
        const value = (input.value || '').trim();
        setHasValue(value.length > 0);
      };

      // 保存 checkValue 函數到 ref，以便在 onClear 後可以立即調用
      checkValueRef.current = checkValue;

      const handleInput = () => {
        setIsTyping(true);
        checkValue();
      };

      const handleFocus = () => {
        setIsFocused(true);
        checkValue();
      };

      const handleBlur = () => {
        setIsTyping(false);
        setIsFocused(false);
        checkValue();
      };

      const handleMouseEnter = () => {
        checkValue(); // 在 hover 時也檢查值，確保狀態正確
        setIsHovered(true);
      };

      const handleMouseLeave = () => {
        setIsHovered(false);
      };

      // 初始化檢查值
      checkValue();

      // 監聽輸入框事件（用於 typing 狀態）
      if (typingProp === undefined && !disabled && !readonly) {
        input.addEventListener('input', handleInput, false);
        input.addEventListener('mousedown', handleInput, false);
      }

      // 監聽 focus/blur 事件
      input.addEventListener('focus', handleFocus, false);
      input.addEventListener('blur', handleBlur, false);

      // 監聽 hover 事件（在容器上）
      container.addEventListener('mouseenter', handleMouseEnter, false);
      container.addEventListener('mouseleave', handleMouseLeave, false);

      // 監聽值變化（適用於受控組件）
      input.addEventListener('input', checkValue, false);
      input.addEventListener('change', checkValue, false);

      return () => {
        if (typingProp === undefined && !disabled && !readonly) {
          input.removeEventListener('input', handleInput, false);
          input.removeEventListener('mousedown', handleInput, false);
        }
        input.removeEventListener('focus', handleFocus, false);
        input.removeEventListener('blur', handleBlur, false);
        container.removeEventListener('mouseenter', handleMouseEnter, false);
        container.removeEventListener('mouseleave', handleMouseLeave, false);
        input.removeEventListener('input', checkValue, false);
        input.removeEventListener('change', checkValue, false);
        checkValueRef.current = null;
      };
    }, [typingProp, disabled, readonly]);

    const { role, onClick, onKeyDown } = useTextFieldControl({
      onClick: onClickProps,
      onKeyDown: onKeyDownProps,
    });

    const isChildrenFunction = typeof children === 'function';
    const shouldShowClearable =
      clearable &&
      (forceShowClearable || hasValue) &&
      (isHovered || typing || isFocused);

    const paddingInfo: TextFieldPaddingInfo = {
      paddingClassName: cx(
        classes.inputPadding,
        size === 'main' ? classes.inputPaddingMain : classes.inputPaddingSub,
      ),
    };

    const renderedChildren = isChildrenFunction
      ? children(paddingInfo)
      : children;

    return (
      <div
        {...rest}
        ref={hostRef}
        role={roleProp || role}
        onClick={(evt) => {
          evt.stopPropagation();

          onClick?.(evt);
        }}
        onKeyDown={onKeyDown}
        className={cx(
          classes.host,
          {
            [classes.slimGap]: (prefix && suffix) || clearable,
            [classes.main]: size === 'main',
            [classes.sub]: size === 'sub',
            [classes.clearable]: clearable,
            [classes.disabled]: disabled,
            [classes.error]: error,
            [classes.fullWidth]: fullWidth,
            [classes.noPadding]: isChildrenFunction,
            [classes.readonly]: readonly,
            [classes.typing]: typing,
            [classes.active]: active,
            [classes.warning]: warning,
          },
          className,
        )}
      >
        {prefix && <div className={classes.prefix}>{prefix}</div>}
        {renderedChildren}
        {clearable && (
          <ClearActions
            type="clearable"
            className={classes.clearIcon}
            style={{
              opacity: shouldShowClearable ? 1 : 0,
              pointerEvents: shouldShowClearable ? 'auto' : 'none',
            }}
            onClick={(event) => {
              if (!disabled && !readonly && onClear) {
                onClear(event);
                requestAnimationFrame(() => {
                  checkValueRef.current?.();
                });
              }
            }}
            onMouseDown={(event) => event.preventDefault()}
            tabIndex={-1}
          />
        )}
        {suffix && <div className={classes.suffix}>{suffix}</div>}
      </div>
    );
  },
);

export default TextField;
