// packages/vue/message/message.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { messageClasses as classes } from '@mezzanine-ui/core/message';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTranslate from '../transition/translate.vue';
import { messageTimerController } from './message-timer-controller';
import { message } from './message';
import type { MessageData } from './message.types';

/**
 * 單則訊息的呈現，由 Message 工廠負責建立，一般不直接使用。
 *
 * 停留時間到就自動關閉；滑鼠移入或取得焦點時**整疊訊息**一起暫停計時，
 * 移出後再一起恢復 —— 指標只蓋住一則，但被擋住的閱讀時間是所有人的。
 * `duration: false`（loading 用）則完全不計時。
 *
 * @see createNotifier 建立訊息佇列的工廠
 */
const props = withDefaults(defineProps<MessageData>(), {
  children: undefined,
  duration: undefined,
  easing: undefined,
  from: 'bottom',
  icon: undefined,
  onEnter: undefined,
  onEntered: undefined,
  onEntering: undefined,
  onExit: undefined,
  onExited: undefined,
  onExiting: undefined,
  reference: undefined,
  severity: undefined,
});

const open = ref(true);

let timer: number | null = null;
let remainingTime = props.duration || 0;
let startTime = 0;

// 清理計時器
function clearTimer(): void {
  if (timer) {
    window.clearTimeout(timer);
    timer = null;
  }
}

// 開始計時器
function startTimer(time: number): void {
  clearTimer();

  if (time > 0) {
    startTime = Date.now();
    remainingTime = time;
    timer = window.setTimeout(() => {
      open.value = false;
    }, time);
  }
}

// 暫停計時器
function pauseTimer(): void {
  if (timer) {
    clearTimer();

    const elapsed = Date.now() - startTime;

    remainingTime = Math.max(0, remainingTime - elapsed);
  }
}

// 恢復計時器
function resumeTimer(): void {
  if (remainingTime > 0) startTimer(remainingTime);
}

// 初始設定計時器
watch(
  [open, (): MessageData['duration'] => props.duration],
  ([isOpen, duration]) => {
    if (isOpen && duration) startTimer(duration);
    // duration 為 false 時，清除計時器（不自動關閉）
    else if (isOpen && duration === false) clearTimer();
  },
  { immediate: true },
);

// 註冊到全域控制器
watch(
  [
    (): MessageData['reference'] => props.reference,
    (): MessageData['duration'] => props.duration,
  ],
  ([reference, duration], _previous, onCleanup) => {
    if (!reference || !duration) return;

    messageTimerController.register(reference, {
      pause: pauseTimer,
      resume: resumeTimer,
    });

    onCleanup(() => messageTimerController.unregister(reference));
  },
  { immediate: true },
);

// 清理計時器（元件卸載時）
onBeforeUnmount(clearTimer);

function onExited(node: HTMLElement): void {
  props.onExited?.(node);

  if (props.reference) message.remove(props.reference);
}

function pauseAll(): void {
  messageTimerController.pause();
}

function resumeAll(): void {
  messageTimerController.resume();
}

const hostClasses = computed((): string =>
  clsx(classes.host, props.severity ? classes.severity(props.severity) : ''),
);

const iconClass = classes.icon;
const contentClass = classes.content;
</script>

<template>
  <MznTranslate
    appear
    :easing="easing"
    :from="from"
    :in="open"
    @enter="onEnter"
    @entered="onEntered"
    @entering="onEntering"
    @exit="onExit"
    @exited="onExited"
    @exiting="onExiting"
  >
    <div
      :class="hostClasses"
      role="status"
      @blur="resumeAll"
      @focus="pauseAll"
      @mouseenter="pauseAll"
      @mouseleave="resumeAll"
    >
      <span v-if="severity === 'loading'" :class="iconClass">
        <MznSpin loading size="minor" />
      </span>
      <MznIcon v-else-if="icon" :class="iconClass" :icon="icon" />
      <span :class="contentClass">{{ children }}</span>
    </div>
  </MznTranslate>
</template>

// packages/react/src/Message/Message.tsx
'use client';

import {
  messageClasses as classes,
  messageIcons,
  MessageSeverity,
} from '@mezzanine-ui/core/message';
import { IconDefinition } from '@mezzanine-ui/icons';
import type { FC, Key } from 'react';
import { useEffect, useState, useRef, useCallback } from 'react';
import { cx } from '../utils/cx';
import Icon from '../Icon';
import {
  createNotifier,
  Notifier,
  NotifierData,
  NotifierConfig,
} from '../Notifier';
import { Translate, TranslateProps } from '../Transition';
import { messageTimerController } from './MessageTimerController';

export interface MessageConfigProps
  extends Pick<NotifierConfig, 'duration'>,
    Pick<
      TranslateProps,
      | 'onEnter'
      | 'onEntering'
      | 'onEntered'
      | 'onExit'
      | 'onExiting'
      | 'onExited'
      | 'easing'
      | 'from'
    > {}

export interface MessageData
  extends Omit<NotifierData, 'onClose'>,
    MessageConfigProps {
  /**
   * If given, the message will be closed after the amount of time.
   * You can use `Message.config` to overwrite.
   * @default 3000
   */
  duration?: NotifierData['duration'];
  /**
   * message icon prefix
   */
  icon?: IconDefinition;
  /**
   * The key of message.
   */
  reference?: Key;
  /**
   * The severity of the message.
   */
  severity?: MessageSeverity;
}

export type MessageType = FC<MessageData> &
  Notifier<MessageData, MessageConfigProps> &
  Record<
    string,
    (
      message: MessageData['children'],
      props?: Omit<MessageData, 'children' | 'severity' | 'icon'> & {
        key?: Key;
      },
    ) => Key
  >;

/**
 * The react component for `mezzanine` message.
 *
 * Use the API from the Message instance such as `Message.add` and `Message.success`
 * to display a notification message globally.
 */
const Message: MessageType = ((props) => {
  const {
    children,
    duration,
    icon,
    reference,
    severity,
    onExited: onExitedProp,
    ...restTransitionProps
  } = props;

  const [open, setOpen] = useState(true);
  const timerRef = useRef<number | null>(null);
  const remainingTimeRef = useRef<number>(duration || 0);
  const startTimeRef = useRef<number>(Date.now());

  // 清理計時器
  const clearTimer = useCallback(() => {
    if (timerRef.current) {
      window.clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  }, []);

  // 開始計時器
  const startTimer = useCallback(
    (time: number) => {
      clearTimer();

      if (time > 0) {
        startTimeRef.current = Date.now();
        remainingTimeRef.current = time;
        timerRef.current = window.setTimeout(() => {
          setOpen(false);
        }, time);
      }
    },
    [clearTimer],
  );

  // 暫停計時器
  const pauseTimer = useCallback(() => {
    if (timerRef.current) {
      clearTimer();

      const elapsed = Date.now() - startTimeRef.current;

      remainingTimeRef.current = Math.max(
        0,
        remainingTimeRef.current - elapsed,
      );
    }
  }, [clearTimer]);

  // 恢復計時器
  const resumeTimer = useCallback(() => {
    if (remainingTimeRef.current > 0) {
      startTimer(remainingTimeRef.current);
    }
  }, [startTimer]);

  // 初始設定計時器
  useEffect(() => {
    if (open && duration) {
      startTimer(duration);
    } else if (open && duration === false) {
      // duration 為 false 時，清除計時器（不自動關閉）
      clearTimer();
    }

    return () => {
      clearTimer();
    };
  }, [open, duration, clearTimer, startTimer]);

  // 註冊到全域控制器
  useEffect(() => {
    if (reference && duration) {
      messageTimerController.register(reference, {
        pause: pauseTimer,
        resume: resumeTimer,
      });

      return () => {
        messageTimerController.unregister(reference);
      };
    }
  }, [reference, duration, pauseTimer, resumeTimer]);

  // 清理計時器（組件卸載時）
  useEffect(() => {
    return () => {
      clearTimer();
    };
  }, [clearTimer]);

  const onExited: TranslateProps['onExited'] = (node) => {
    if (onExitedProp) {
      onExitedProp(node);
    }

    if (reference) Message.remove(reference);
  };

  const handleMouseEnter = () => {
    messageTimerController.pause();
  };

  const handleMouseLeave = () => {
    messageTimerController.resume();
  };

  const handleFocus = () => {
    messageTimerController.pause();
  };

  const handleBlur = () => {
    messageTimerController.resume();
  };

  return (
    <Translate
      in={open}
      appear
      onExited={onExited}
      from="bottom"
      {...restTransitionProps}
    >
      <div
        className={cx(classes.host, severity ? classes.severity(severity) : '')}
        onBlur={handleBlur}
        onFocus={handleFocus}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        role="status"
      >
        {icon ? (
          <Icon
            className={classes.icon}
            icon={icon}
            spin={severity === 'loading'}
          />
        ) : null}
        <span className={classes.content}>{children}</span>
      </div>
    </Translate>
  );
}) as MessageType;

const { add, config, destroy, remove } = createNotifier<
  MessageData,
  MessageConfigProps
>({
  duration: 3000,
  maxCount: 4,
  render: (message) => (
    <Message {...message} reference={message.key} key={undefined} />
  ),
  setRoot: (root) => {
    root?.setAttribute('class', classes.root);
  },
});

Message.add = add;
Message.config = config;
Message.destroy = destroy;
Message.remove = remove;

const severities = [
  {
    key: 'success',
    icon: messageIcons.success,
  },
  {
    key: 'warning',
    icon: messageIcons.warning,
  },
  {
    key: 'error',
    icon: messageIcons.error,
  },
  {
    key: 'info',
    icon: messageIcons.info,
  },
  {
    key: 'loading',
    icon: messageIcons.loading,
  },
];

const validSeverities: MessageSeverity[] = [
  'success',
  'warning',
  'error',
  'info',
  'loading',
];

severities.forEach((severity) => {
  Message[severity.key] = (message, props) =>
    Message.add({
      ...props,
      children: message,
      severity: validSeverities.includes(severity.key as MessageSeverity)
        ? (severity.key as MessageSeverity)
        : undefined,
      icon: severity.icon,
      duration: severity.key === 'loading' ? false : props?.duration,
    });
});

export default Message;
