// packages/react/src/ContentHeader/ContentHeader.tsx
import { forwardRef, ReactElement } from 'react';
import { contentHeaderClasses as classes } from '@mezzanine-ui/core/content-header';
import Button, { ButtonGroup, ButtonProps } from '../Button';
import { SearchInputProps } from '../Input';
import { SelectProps } from '../Select';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { ChevronLeftIcon, IconDefinition } from '@mezzanine-ui/icons';
import {
  renderActionsProp,
  renderFilterProp,
  renderIconButtonsProp,
  resolveContentHeaderChild,
} from './utils';
import Typography from '../Typography';
import { DropdownProps } from '../Dropdown';

// TODO: Replace with actual SegmentedControlProps when SegmentedControl component is complete
type SegmentedControlProps = {
  mock: 'SegmentedControlProps';
};

type ContentHeaderChild =
  | ReactElement<SearchInputProps>
  | ReactElement<SelectProps>
  | ReactElement<SegmentedControlProps>
  | ReactElement<ButtonProps>
  | ReactElement<DropdownProps>
  | ReactElement<{ href: string }>
  | null
  | false
  | undefined;

/**
 * Props for the ContentHeader component.
 *
 * Defines a flexible header with title, description, filter, action buttons, and utility icons.
 * Commonly used in page headers for primary user actions.
 */
export type ContentHeaderProps = Omit<
  NativeElementPropsWithoutKeyAndRef<'header'>,
  'children'
> & {
  /**
   * Button configuration for actions. <br />
   * Automatically applies proper styling and order. <br />
   * When conflicting with other props, props take priority over children. <br />
   * Buttons with variants other than primary, secondary, and destructive will not be rendered. <br />
   */
  actions?: ButtonProps[];
  /**
   * Children elements: <br />
   * - Back button which Component with href prop.
   *     - example 1: `<a href="..." />` <br />
   *     - example 2: `<Link href="..." />` <br />
   *     - conflicting prop: `onBackClick` <br />
   * - Filter component (SearchInput, Select, or SegmentedControl) <br />
   * - Action buttons `<Button />` <br />
   * - Icon-only utility buttons `<Button icon="..." />` <br />
   * - Overflow icon utility dropdown `<Dropdown> <Button icon="..." /> </Dropdown>` <br />
   * <br />
   * Can mix and match the above children. <br />
   * The order of children does not matter as they will be arranged properly. <br />
   * When conflicting with other props, props take priority over children. <br />
   */
  children?: ContentHeaderChild[] | ContentHeaderChild;
  /** Optional description text displayed below the title */
  description?: string;
  /** Filter component (SearchInput, Select, or SegmentedControl) */
  filter?: { variant: 'search' | 'select' | 'segmentedControl' } & (
    | SearchInputProps
    | SelectProps
    | SegmentedControlProps
  );
  /**
   * Optional back button properties. <br />
   * When provided, a back button will be rendered on the left side of the title. <br />
   * href prop from children will be ignored if onBackClick is provided. <br />
   * */
  onBackClick?: () => void;
  /**
   * Size variant of the toolbar. <br />
   * Affects the size of buttons and filter component. <br />
   */
  size?: 'main' | 'sub';
  /** Main title text for the content header */
  title: string;
  /**
   * HTML element type for the title (defaults to 'h1' for main size and 'h2' for sub size)
   */
  titleComponent?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p';
  /**
   * Icon-only utility buttons `<Button icon="..." />`. <br />
   * They usually appear as smaller buttons with only an icon and no text.
   */
  utilities?: (
    | (ButtonProps & {
        icon: IconDefinition;
      })
    | DropdownProps
  )[];
};

/**
 * ContentHeader component. <br />
 * A flexible header with title, description, filter, action buttons, and utility icons. <br />
 * Commonly used in page headers for primary user actions. <br />
 *
 * @example
 * ```tsx
 *  <ContentHeader
 *    size="main"
 *    title={'ContentHeader Title'}
 *    description="description."
 *  >
 *    <a href="" title="back" />  <-- Back button
 *
 *    <Input variant="search" placeholder="Search..." />  <-- Filter component
 *    <Button variant="base-secondary">Secondary</Button>  <-- Action buttons
 *    <Button>Primary</Button>
 *
 *    <Button icon={PlusIcon} />  <-- Utility icon button
 *    <Dropdown
 *      options={[
 *        { id: '1', name: 'Option 1' },
 *        { id: '2', name: 'Option 2' },
 *      ]}
 *    >
 *      <Button icon={DotHorizontalIcon} />
 *    </Dropdown>  <-- Utility dropdown
 *  </ContentHeader>
 * ```
 */
const ContentHeader = forwardRef<HTMLElement, ContentHeaderProps>(
  function ContentHeader(props, ref) {
    const {
      actions,
      children,
      className,
      description,
      filter,
      onBackClick,
      size = 'main',
      title,
      titleComponent = size === 'main' ? 'h1' : 'h2',
      utilities,
      ...rest
    } = props;

    const renderFilter = renderFilterProp(filter, size);
    const renderActions = actions ? renderActionsProp(actions, size) : null;
    const renderUtilities = utilities
      ? renderIconButtonsProp(utilities, size)
      : null;

    const {
      backButton,
      filter: filterFromChildren,
      actions: actionsFromChildren,
      utilities: utilitiesFromChildren,
    } = resolveContentHeaderChild(children, size);

    // prop onBack takes precedence over backButtonOrLink
    const renderBackButton = onBackClick ? (
      <Button
        iconType="icon-only"
        icon={ChevronLeftIcon}
        onClick={onBackClick}
        aria-label="Back"
        type="button"
        size="sub"
        variant="base-tertiary"
      />
    ) : (
      backButton
    );

    return (
      <header
        {...rest}
        className={cx(classes.host, classes.size(size), className)}
        ref={ref}
      >
        <span className={classes.titleArea}>
          {/* title area */}
          {renderBackButton && (
            <span className={classes.backButton}>{renderBackButton}</span>
          )}

          <span className={classes.textGroup}>
            <Typography
              component={titleComponent}
              align="left"
              color="text-neutral-solid"
              variant={size === 'main' ? 'h2' : 'h3'}
            >
              {title}
            </Typography>
            {description && (
              <Typography align="left" color="text-neutral" variant="caption">
                {description}
              </Typography>
            )}
          </span>
        </span>

        {/* actions area */}
        <span className={classes.actionArea}>
          {renderFilter || filterFromChildren}
          {(renderActions || actionsFromChildren.length > 0) && (
            <ButtonGroup>{renderActions || actionsFromChildren}</ButtonGroup>
          )}
          {(renderUtilities || utilitiesFromChildren.length > 0) && (
            <span className={classes.utilities}>
              {renderUtilities || utilitiesFromChildren}
            </span>
          )}
        </span>
      </header>
    );
  },
);

export default ContentHeader;

// packages/vue/content-header/content-header.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { VNodeArrayChildren, VNodeChild } from 'vue';
import { contentHeaderClasses as classes } from '@mezzanine-ui/core/content-header';
import { ChevronLeftIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useHasListener } from '../_internal/use-has-listener';
import MznButton from '../button/button.vue';
import MznButtonGroup from '../button/button-group.vue';
import MznTypography from '../typography/typography.vue';
import {
  renderActionsProp,
  renderFilterProp,
  renderIconButtonsProp,
  resolveContentHeaderChild,
} from './content-header-utils';
import type { ContentHeaderProps } from './content-header.types';

/**
 * 內容區塊的標題列：標題、說明、篩選器、動作按鈕與工具圖示。
 *
 * 內容可以用 props 給（`filter`、`actions`、`utilities`），也可以直接把元件放進
 * 預設 slot —— 放進去的順序不重要，會依元件種類分派到對應的位置，而 props 優先
 * 於 slot。`size` 會強制蓋掉子項自己的尺寸。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznContentHeader } from '@mezzanine-ui/vue/content-header';
 * <\/script>
 *
 * <template>
 *   <MznContentHeader description="說明文字" size="main" title="標題">
 *     <a href="/back" title="back" />
 *     <MznInput placeholder="搜尋..." variant="search" />
 *     <MznButton variant="base-secondary">儲存草稿</MznButton>
 *     <MznButton>發布</MznButton>
 *   </MznContentHeader>
 * </template>
 * ```
 *
 * @see MznContentHeaderResponsive 只在某個斷點顯示的子項
 * @see MznPageFooter 對應的頁尾操作列
 */
const props = withDefaults(defineProps<ContentHeaderProps>(), {
  actions: undefined,
  backButtonLabel: 'Back',
  description: undefined,
  filter: undefined,
  size: 'main',
  titleComponent: undefined,
  utilities: undefined,
});

const emit = defineEmits<{
  backClick: [];
}>();

const slots = defineSlots<{
  /**
   * The back link, the filter, the action buttons and the utility icons, in
   * any order.
   */
  default?: () => unknown;
}>();

const hasListener = useHasListener();

const titleComponent = computed(
  (): NonNullable<ContentHeaderProps['titleComponent']> =>
    props.titleComponent ?? (props.size === 'main' ? 'h1' : 'h2'),
);

const renderFilter = computed(
  (): VNodeChild => renderFilterProp(props.filter, props.size),
);

const renderActions = computed((): VNodeChild[] | null =>
  props.actions ? renderActionsProp(props.actions, props.size) : null,
);

const renderUtilities = computed((): VNodeChild[] | null =>
  props.utilities ? renderIconButtonsProp(props.utilities, props.size) : null,
);

const resolved = computed(() =>
  resolveContentHeaderChild(
    slots.default?.() as VNodeArrayChildren | undefined,
    props.size,
    props.backButtonLabel,
  ),
);

/** The `back-click` listener takes precedence over a back link in the slot. */
const renderBackButton = computed(
  (): VNodeChild =>
    hasListener('backClick') ? null : resolved.value.backButton,
);

const hasBackClickListener = (): boolean => hasListener('backClick');

const hostClasses = computed((): string =>
  clsx(classes.host, classes.size(props.size)),
);

const actionAreaClass = classes.actionArea;
const backButtonClass = classes.backButton;
const textGroupClass = classes.textGroup;
const titleAreaClass = classes.titleArea;
const utilitiesClass = classes.utilities;
</script>

<template>
  <header :class="hostClasses">
    <span :class="titleAreaClass">
      <!-- title area -->
      <span
        v-if="(hasBackClickListener() || renderBackButton) && size !== 'sub'"
        :class="backButtonClass"
      >
        <MznButton
          v-if="hasBackClickListener()"
          :aria-label="backButtonLabel"
          :icon="ChevronLeftIcon"
          icon-type="icon-only"
          size="sub"
          type="button"
          variant="base-tertiary"
          @click="emit('backClick')"
        />
        <component :is="() => renderBackButton" v-else />
      </span>

      <span :class="textGroupClass">
        <MznTypography
          align="left"
          color="text-neutral-solid"
          :component="titleComponent"
          :variant="size === 'main' ? 'h2' : 'h3'"
        >
          {{ title }}
        </MznTypography>
        <MznTypography
          v-if="description"
          align="left"
          color="text-neutral"
          variant="caption"
        >
          {{ description }}
        </MznTypography>
      </span>
    </span>

    <!-- actions area -->
    <span :class="actionAreaClass">
      <component :is="() => renderFilter ?? resolved.filter" />
      <MznButtonGroup v-if="renderActions || resolved.actions.length > 0">
        <component :is="() => renderActions ?? resolved.actions" />
      </MznButtonGroup>
      <span
        v-if="renderUtilities || resolved.utilities.length > 0"
        :class="utilitiesClass"
      >
        <component :is="() => renderUtilities ?? resolved.utilities" />
      </span>
    </span>
  </header>
</template>
