// packages/vue/card/four-thumbnail-card.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { VNode, VNodeArrayChildren } from 'vue';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import MznIcon from '../icon/icon.vue';
import MznThumbnail from './thumbnail.vue';
import MznThumbnailCardInfo from './thumbnail-card-info.vue';
import type {
  FourThumbnailCardComponent,
  FourThumbnailCardProps,
} from './four-thumbnail-card.types';

/**
 * 四張縮圖排成 2x2 的卡片，可加標籤與收藏按鈕，下方是資訊列。
 *
 * 子項必須是 MznThumbnail：不足四個會補上空格子，超過四個只取前四個並在開發
 * 模式下提醒。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznFourThumbnailCard, MznThumbnail } from '@mezzanine-ui/vue/card';
 * <\/script>
 *
 * <template>
 *   <MznFourThumbnailCard subtitle="4 items" title="相簿">
 *     <MznThumbnail v-for="photo in photos" :key="photo.id" :title="photo.name">
 *       <img :alt="photo.name" :src="photo.src" />
 *     </MznThumbnail>
 *   </MznFourThumbnailCard>
 * </template>
 * ```
 *
 * @see MznThumbnail 每一格縮圖
 * @see MznSingleThumbnailCard 單張縮圖的版本
 */
/**
 * React takes `component` out of the spread; Vue's fallthrough would leave it
 * on the element as an attribute.
 */
defineOptions({ inheritAttrs: false });

const MAX_THUMBNAILS = 4;

const props = withDefaults(defineProps<FourThumbnailCardProps>(), {
  actionName: undefined,
  filetype: undefined,
  options: undefined,
  personalActionActive: false,
  personalActionActiveIcon: undefined,
  personalActionIcon: undefined,
  personalActionOnClick: undefined,
  subtitle: undefined,
  tag: undefined,
  type: 'default',
});

const emit = defineEmits<{
  actionClick: [event: MouseEvent];
  optionSelect: [option: DropdownOption];
}>();

const slots = defineSlots<{
  /** One to four thumbnails. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const component = computed(
  (): FourThumbnailCardComponent =>
    (attrs.component as FourThumbnailCardComponent) ?? 'div',
);

const forwardedAttrs = computed(() => {
  const { class: _class, component: _component, ...rest } = attrs;

  return rest;
});

const thumbnails = computed((): VNode[] => {
  const children = flattenChildren(
    slots.default?.() as VNodeArrayChildren | undefined,
  );

  const valid = children.filter((child) => {
    const isThumbnail = child.type === MznThumbnail;

    if (!isThumbnail && process.env.NODE_ENV !== 'production') {
      const type = child.type as { displayName?: string; name?: string };
      const displayName =
        typeof child.type === 'string'
          ? child.type
          : (type.displayName ?? type.name ?? 'Unknown');

      console.warn(
        `[FourThumbnailCard] Invalid child type: <${displayName}>. ` +
          'FourThumbnailCard only accepts Thumbnail components as children.',
      );
    }

    return isThumbnail;
  });

  if (valid.length > MAX_THUMBNAILS && process.env.NODE_ENV !== 'production') {
    console.warn(
      `[FourThumbnailCard] Received ${valid.length} Thumbnail children, ` +
        `but only the first ${MAX_THUMBNAILS} will be rendered.`,
    );
  }

  return valid.slice(0, MAX_THUMBNAILS);
});

const emptySlots = computed((): number[] =>
  Array.from(
    { length: MAX_THUMBNAILS - thumbnails.value.length },
    (_, index) => index,
  ),
);

const hasPersonalAction = computed((): boolean =>
  Boolean(props.personalActionIcon),
);

const currentPersonalActionIcon = computed((): IconDefinition | undefined =>
  props.personalActionActive
    ? (props.personalActionActiveIcon ?? props.personalActionIcon)
    : props.personalActionIcon,
);

function handlePersonalActionClick(event: MouseEvent): void {
  event.stopPropagation();
  props.personalActionOnClick?.(event, props.personalActionActive);
}

const hostClasses = computed((): string =>
  clsx(classes.thumbnail, attrs.class as string),
);

const emptyClasses = clsx(
  classes.fourThumbnailThumbnail,
  classes.fourThumbnailThumbnailEmpty,
);

const gridClass = classes.fourThumbnail;
const personalActionClass = classes.thumbnailPersonalAction;
const tagClass = classes.thumbnailTag;
</script>

<template>
  <component :is="component" v-bind="forwardedAttrs" :class="hostClasses">
    <div :class="gridClass">
      <div v-if="tag" :class="tagClass">{{ tag }}</div>
      <button
        v-if="hasPersonalAction && currentPersonalActionIcon"
        aria-label="Personal Action"
        :class="personalActionClass"
        type="button"
        @click="handlePersonalActionClick"
      >
        <MznIcon :icon="currentPersonalActionIcon" :size="16" />
      </button>
      <component :is="() => thumbnails" />
      <div
        v-for="index in emptySlots"
        :key="`empty-${index}`"
        :class="emptyClasses"
      />
    </div>
    <MznThumbnailCardInfo
      :action-name="type === 'action' ? actionName : undefined"
      :filetype="filetype"
      :options="type === 'overflow' ? options : undefined"
      :subtitle="subtitle"
      :title="title"
      :type="type"
      @action-click="emit('actionClick', $event)"
      @option-select="emit('optionSelect', $event)"
    />
  </component>
</template>

// packages/react/src/Card/FourThumbnailCard.tsx
'use client';

import { Children, forwardRef, isValidElement, MouseEvent } from 'react';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import { cx } from '../utils/cx';
import { ComponentOverridableForwardRefComponentPropsFactory } from '../utils/jsx-types';
import Icon from '../Icon';
import Thumbnail from './Thumbnail';
import ThumbnailCardInfo from './ThumbnailCardInfo';
import {
  FourThumbnailCardActionProps,
  FourThumbnailCardComponent,
  FourThumbnailCardOverflowProps,
  FourThumbnailCardProps,
} from './typings';

export type FourThumbnailCardComponentProps<
  C extends FourThumbnailCardComponent = 'div',
> = ComponentOverridableForwardRefComponentPropsFactory<
  FourThumbnailCardComponent,
  C,
  FourThumbnailCardProps
>;

const MAX_THUMBNAILS = 4;

/**
 * FourThumbnailCard displays a 2x2 grid of image thumbnails with optional tag, personal action,
 * and info section. Supports three action types: default, action, and overflow.
 *
 * Children must be Thumbnail components. If less than 4 are provided, empty slots will be rendered.
 * If more than 4 are provided, only the first 4 will be used (with a console warning in development).
 */
const FourThumbnailCard = forwardRef<
  HTMLDivElement,
  FourThumbnailCardComponentProps
>(function FourThumbnailCard(props, ref) {
  const {
    children,
    className,
    component: Component = 'div',
    filetype,
    personalActionActive = false,
    personalActionActiveIcon,
    personalActionIcon,
    personalActionOnClick,
    subtitle,
    tag,
    title,
    type = 'default',
    ...rest
  } = props;

  // Process children: filter valid Thumbnail elements and limit to MAX_THUMBNAILS
  const childArray = Children.toArray(children).filter((child) => {
    if (!isValidElement(child)) return false;

    // Check if the child is a Thumbnail component
    const isThumbnail = child.type === Thumbnail;

    if (!isThumbnail && process.env.NODE_ENV !== 'production') {
      const displayName =
        typeof child.type === 'string'
          ? child.type
          : (child.type as { displayName?: string }).displayName ||
            (child.type as { name?: string }).name ||
            'Unknown';

      console.warn(
        `[FourThumbnailCard] Invalid child type: <${displayName}>. ` +
          'FourThumbnailCard only accepts Thumbnail components as children.',
      );
    }

    return isThumbnail;
  });

  // Warn if more than MAX_THUMBNAILS children are provided
  if (
    childArray.length > MAX_THUMBNAILS &&
    process.env.NODE_ENV !== 'production'
  ) {
    console.warn(
      `[FourThumbnailCard] Received ${childArray.length} Thumbnail children, ` +
        `but only the first ${MAX_THUMBNAILS} will be rendered.`,
    );
  }

  // Take only the first MAX_THUMBNAILS
  const thumbnails = childArray.slice(0, MAX_THUMBNAILS);

  // Fill remaining slots with empty placeholders
  const emptySlots = MAX_THUMBNAILS - thumbnails.length;
  const emptyPlaceholders = Array.from({ length: emptySlots }, (_, index) => (
    <div
      key={`empty-${index}`}
      className={cx(
        classes.fourThumbnailThumbnail,
        classes.fourThumbnailThumbnailEmpty,
      )}
    />
  ));

  const hasPersonalAction = Boolean(personalActionIcon);
  const currentPersonalActionIcon = personalActionActive
    ? (personalActionActiveIcon ?? personalActionIcon)
    : personalActionIcon;

  const handlePersonalActionClick = (event: MouseEvent<HTMLButtonElement>) => {
    event.stopPropagation();
    personalActionOnClick?.(event, personalActionActive);
  };

  const getInfoProps = () => {
    if (type === 'action') {
      const { actionName, onActionClick } =
        props as FourThumbnailCardActionProps;

      return { actionName, onActionClick };
    }

    if (type === 'overflow') {
      const { onOptionSelect, options } =
        props as FourThumbnailCardOverflowProps;

      return { onOptionSelect, options };
    }

    return {};
  };

  // Filter out type-specific props before spreading
  const {
    actionName: _actionName,
    onActionClick: _onActionClick,
    onOptionSelect: _onOptionSelect,
    options: _options,
    type: _type,
    ...componentProps
  } = rest as Record<string, unknown>;

  return (
    <Component
      {...componentProps}
      ref={ref}
      className={cx(classes.thumbnail, className)}
    >
      <div className={classes.fourThumbnail}>
        {tag && <div className={classes.thumbnailTag}>{tag}</div>}
        {hasPersonalAction && currentPersonalActionIcon && (
          <button
            aria-label="Personal Action"
            className={classes.thumbnailPersonalAction}
            onClick={handlePersonalActionClick}
            type="button"
          >
            <Icon icon={currentPersonalActionIcon} size={24} />
          </button>
        )}
        {thumbnails}
        {emptyPlaceholders}
      </div>
      <ThumbnailCardInfo
        filetype={filetype}
        subtitle={subtitle}
        title={title}
        type={type}
        {...getInfoProps()}
      />
    </Component>
  );
});

FourThumbnailCard.displayName = 'FourThumbnailCard';

export default FourThumbnailCard;
