// packages/ng/card/quick-action-card-skeleton.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import clsx from 'clsx';
import { MznSkeleton } from '@mezzanine-ui/ng/skeleton';

/**
 * Skeleton placeholder for QuickActionCard component.
 * Renders a skeleton that mimics the QuickActionCard layout
 * with a circle icon skeleton and two text skeletons.
 *
 * @example
 * ```html
 * import { MznQuickActionCardSkeleton } from '@mezzanine-ui/ng/card';
 *
 * <div mznQuickActionCardSkeleton ></div>
 * <div mznQuickActionCardSkeleton mode="vertical" ></div>
 * ```
 *
 * @see MznQuickActionCard
 */
@Component({
  selector: '[mznQuickActionCardSkeleton]',
  standalone: true,
  imports: [MznSkeleton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.mode]': 'null',
  },
  template: `
    <div mznSkeleton [circle]="true" [height]="24" [width]="24"></div>
    <div [class]="contentClass">
      <div mznSkeleton [height]="20" width="70%"></div>
      <div mznSkeleton [height]="16" width="50%"></div>
    </div>
  `,
})
export class MznQuickActionCardSkeleton {
  /**
   * Layout mode matching QuickActionCard.
   * @default 'horizontal'
   */
  readonly mode = input<'horizontal' | 'vertical'>('horizontal');

  protected readonly contentClass = classes.quickActionContent;

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.quickAction,
      classes.quickActionReadOnly,
      this.mode() === 'vertical' && classes.quickActionVertical,
    ),
  );
}

// packages/react/src/Card/QuickActionCardSkeleton.tsx
'use client';

import { forwardRef } from 'react';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Skeleton from '../Skeleton';

export interface QuickActionCardSkeletonProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'> {
  /**
   * Layout mode matching QuickActionCard
   * @default 'horizontal'
   */
  mode?: 'horizontal' | 'vertical';
}

/**
 * Skeleton placeholder for QuickActionCard component.
 * Renders a skeleton that mimics the QuickActionCard layout.
 */
const QuickActionCardSkeleton = forwardRef<
  HTMLDivElement,
  QuickActionCardSkeletonProps
>(function QuickActionCardSkeleton(props, ref) {
  const { className, mode = 'horizontal', ...rest } = props;

  return (
    <div
      {...rest}
      ref={ref}
      className={cx(
        classes.quickAction,
        classes.quickActionReadOnly,
        mode === 'vertical' && classes.quickActionVertical,
        className,
      )}
    >
      <Skeleton circle height={24} width={24} />
      <div className={classes.quickActionContent}>
        <Skeleton height={20} width="70%" />
        <Skeleton height={16} width="50%" />
      </div>
    </div>
  );
});

QuickActionCardSkeleton.displayName = 'QuickActionCardSkeleton';

export default QuickActionCardSkeleton;
