// packages/vue/radio/radio.vue
<script setup lang="ts">
import { computed, h, inject, ref, useAttrs } from 'vue';
import type { VNode, VNodeChild } from 'vue';
import type { InputCheckSize } from '@mezzanine-ui/core/_internal/input-check';
import { radioClasses as classes } from '@mezzanine-ui/core/radio';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import MznInputCheck from '../_internal/input-check.vue';
import { useRadioControlValue } from '../_internal/use-radio-control-value';
import MznIcon from '../icon/icon.vue';
import MznInput from '../input/input.vue';
import { radioGroupKey } from './radio-group-context';
import type { RadioProps } from './radio.types';

/**
 * 單選按鈕元件，支援標準（radio）與區段（segment）兩種類型。
 *
 * 在 MznRadioGroup 內使用時會自動繼承群組的 `name`、`size` 與 `type`；
 * 也可獨立使用，透過 `checked` / `defaultChecked` 進行受控或非受控操作。
 * `segment` 類型可搭配 `icon` 顯示圖示；`withInputConfig` 會在右側附一個輸入框，
 * 選中時自動聚焦到它。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznRadio } from '@mezzanine-ui/vue/radio';
 * <\/script>
 *
 * <template>
 *   <MznRadio value="male" :input-props="{ name: 'gender' }">男性</MznRadio>
 *   <MznRadio type="segment" :icon="ListIcon" value="list">列表</MznRadio>
 * </template>
 * ```
 *
 * @see MznRadioGroup 管理多個單選按鈕的群組元件
 * @see useRadioControlValue 單選按鈕受控值的 composable
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<RadioProps>(), {
  checked: undefined,
  defaultChecked: undefined,
  disabled: undefined,
  error: false,
  focused: undefined,
  hint: undefined,
  icon: undefined,
  inputProps: undefined,
  segmentedStyle: undefined,
  size: undefined,
  type: undefined,
  value: undefined,
  withInputConfig: undefined,
});

const emit = defineEmits<{
  /** The change event handler of input in radio. */
  change: [event: Event];
}>();

const slots = defineSlots<{
  /** The label of the radio. */
  default?: () => VNode[];
}>();

const attrs = useAttrs();
const radioGroup = inject(radioGroupKey, undefined);

const disabled = computed(
  (): boolean => props.disabled ?? radioGroup?.value.disabled ?? false,
);
const type = computed(
  (): 'radio' | 'segment' => props.type ?? radioGroup?.value.type ?? 'radio',
);
const size = computed(
  (): InputCheckSize =>
    (props.size ?? radioGroup?.value.size ?? 'main') as InputCheckSize,
);

const inputId = computed((): string | undefined => props.inputProps?.id);
const name = computed(
  (): string | undefined => props.inputProps?.name ?? radioGroup?.value.name,
);

const restInputProps = computed(() => {
  const { id: _id, name: _name, ...rest } = props.inputProps ?? {};

  return rest;
});

const { checked, onChange } = useRadioControlValue({
  checked: () => props.checked,
  defaultChecked: () => props.defaultChecked,
  onChange: (event) => emit('change', event),
  radioGroup: () => radioGroup?.value,
  value: () => props.value,
});

const radioInput = ref<HTMLInputElement | null>(null);
const textInput = ref<InstanceType<typeof MznInput> | null>(null);

function handleRadioChange(event: Event): void {
  onChange(event);

  if (props.withInputConfig && !props.withInputConfig.disabled) {
    textInput.value?.input?.focus();
  }
}

const controlClasses = computed((): string =>
  clsx(classes.host, classes.size(size.value), {
    [classes.segmented]: type.value === 'segment',
    [classes.checked]: checked.value,
    [classes.error]: props.error,
  }),
);

const segmentedContainerClasses = computed((): string =>
  clsx(classes.segmentedContainer, {
    [classes.segmentedContainerWithIconText]:
      Boolean(flattenChildren(slots.default?.()).length) && Boolean(props.icon),
  }),
);

/**
 * React hands the control in as a node, so it is built here rather than in a
 * slot: the input has to keep the ref that focuses the paired text input.
 */
const control = computed(
  (): VNodeChild =>
    h('span', { class: controlClasses.value }, [
      type.value === 'segment'
        ? h('span', { class: segmentedContainerClasses.value }, [
            props.icon ? h(MznIcon, { icon: props.icon, size: 16 }) : null,
            slots.default?.(),
          ])
        : null,
      h('input', {
        ...restInputProps.value,
        'aria-checked': checked.value,
        'aria-disabled': disabled.value,
        checked: checked.value,
        disabled: disabled.value,
        id: inputId.value,
        name: name.value,
        onChange: handleRadioChange,
        ref: radioInput,
        type: 'radio',
        value: props.value,
      }),
    ]),
);

const withInputStyle = computed(() => ({
  width: `${props.withInputConfig?.width ?? 120}px`,
}));

const withInputProps = computed(() => {
  const { width: _width, ...rest } = props.withInputConfig ?? {};

  return rest;
});

const textInputProps = { onClick: () => radioInput.value?.click() };

const wrapperClasses = computed((): unknown[] => [
  classes.wrapper,
  attrs.class,
]);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});
</script>

<template>
  <div :class="wrapperClasses">
    <MznInputCheck
      v-bind="forwardedAttrs"
      :control="control"
      :disabled="disabled"
      :error="error"
      :focused="focused"
      :for="inputId"
      :hint="hint"
      :segmented-style="type === 'segment'"
      :size="size"
    >
      <slot v-if="type === 'radio'" />
    </MznInputCheck>
    <div v-if="type === 'radio' && withInputConfig" :style="withInputStyle">
      <MznInput
        ref="textInput"
        v-bind="withInputProps"
        :input-props="textInputProps"
        :placeholder="withInputConfig.placeholder ?? 'Placeholder'"
        variant="base"
      />
    </div>
  </div>
</template>

// packages/react/src/Radio/Radio.tsx
'use client';

import { ChangeEventHandler, forwardRef, useContext, useState } from 'react';
import { radioClasses as classes, RadioSize } from '@mezzanine-ui/core/radio';
import { IconDefinition } from '@mezzanine-ui/icons';
import InputCheck, {
  InputCheckProps,
} from '../_internal/InputCheck/InputCheck';
import { cx } from '../utils/cx';
import { useRadioControlValue } from '../Form/useRadioControlValue';
import { RadioGroupContext } from './RadioGroupContext';
import Input, { BaseInputProps } from '../Input';
import Icon from '../Icon';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

export interface RadioBaseProps
  extends Omit<InputCheckProps, 'control' | 'htmlFor'> {
  /**
   * Whether the radio is checked.
   */
  checked?: boolean;
  /**
   * Whether the radio is checked by default.
   * @default false
   */
  defaultChecked?: boolean;
  /**
   * Since at Mezzanine we use a host element to wrap our input, most derived props will be passed to the host element.
   *  If you need direct control to the input element, use this prop to provide to it.
   *
   * Noticed that if you pass an id within this prop,
   *  the rendered label element will have `htmlFor` sync with passed in id.
   */
  inputProps?: Omit<
    NativeElementPropsWithoutKeyAndRef<'input'>,
    | 'checked'
    | 'defaultChecked'
    | 'disabled'
    | 'onChange'
    | 'placeholder'
    | 'readOnly'
    | 'required'
    | 'type'
    | 'value'
    | `aria-${'disabled' | 'checked'}`
  >;
  /**
   * The change event handler of input in radio.
   */
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * The size of radio.
   * @default 'main'
   */
  size?: RadioSize;
  /**
   * The value of input in radio.
   */
  value?: string;
}

export interface RadioNormalProps extends RadioBaseProps {
  icon?: never;
  hint?: string;
  /**
   * The type of radio.
   * @default 'radio'
   */
  type?: 'radio';
  /**
   * When `withInputConfig` is provided, an `Input` component is rendered alongside the
   * radio using the passed props. By default, this input has a width of 120px unless you
   * override it via the `width` property below.
   */
  withInputConfig?: Pick<
    BaseInputProps,
    'aria-disabled' | 'disabled' | 'onChange' | 'placeholder' | 'value'
  > & {
    width?: number;
  };
}

export interface RadioSegmentProps extends RadioBaseProps {
  /**
   * The icon in radio prefix.
   */
  icon?: IconDefinition;
  hint?: never;
  /**
   * The type of radio.
   * @default 'radio'
   */
  type: 'segment';
  withInputConfig?: never;
}

export type RadioProps = RadioNormalProps | RadioSegmentProps;

/**
 * The react component for `mezzanine` radio.
 */
const Radio = forwardRef<HTMLDivElement, RadioProps>(
  function Radio(props, ref) {
    const radioGroup = useContext(RadioGroupContext);
    const {
      disabled: disabledFromGroup,
      name: nameFromGroup,
      size: sizeFromGroup,
      type: typeFromGroup,
    } = radioGroup || {};
    const {
      checked: checkedProp,
      className,
      children,
      defaultChecked,
      disabled = disabledFromGroup || false,
      error = false,
      icon,
      hint,
      inputProps,
      onChange: onChangeProp,
      size = sizeFromGroup || 'main',
      type = typeFromGroup || 'radio',
      value,
      withInputConfig,
      ...rest
    } = props;
    const {
      id: inputId,
      name = nameFromGroup,
      ...restInputProps
    } = inputProps || {};
    const [checked, onChange] = useRadioControlValue({
      checked: checkedProp,
      defaultChecked,
      onChange: onChangeProp,
      radioGroup,
      value,
    });
    const [focused, setFocused] = useState<boolean>(false);

    return (
      <div ref={ref} className={cx(classes.wrapper, className)}>
        <InputCheck
          {...rest}
          control={
            <span
              className={cx(classes.host, classes.size(size), {
                [classes.segmented]: type === 'segment',
                [classes.checked]: checked,
                [classes.focused]: focused,
                [classes.error]: error,
              })}
            >
              {type === 'segment' && (
                <span className={cx(classes.segmentedContainer)}>
                  {icon && <Icon icon={icon} size={16} />}
                  {children}
                </span>
              )}
              <input
                {...restInputProps}
                aria-checked={checked}
                aria-disabled={disabled}
                checked={checked}
                disabled={disabled}
                id={inputId}
                onChange={onChange}
                onFocus={() => {
                  setFocused(true);
                }}
                onBlur={() => {
                  setFocused(false);
                }}
                name={name}
                type="radio"
                value={value}
              />
            </span>
          }
          disabled={disabled}
          error={error}
          focused={focused}
          hint={hint}
          htmlFor={inputId}
          segmentedStyle={type === 'segment'}
          size={size}
        >
          {type === 'radio' && children}
        </InputCheck>
        {type === 'radio' && withInputConfig && (
          <div style={{ width: withInputConfig.width ?? 120 }}>
            <Input
              {...withInputConfig}
              variant="base"
              placeholder={withInputConfig.placeholder ?? 'Placeholder'}
            />
          </div>
        )}
      </div>
    );
  },
);

export default Radio;
