// packages/react/src/PageHeader/PageHeader.tsx
import { cloneElement, forwardRef, isValidElement, ReactElement } from 'react';
import { pageHeaderClasses as classes } from '@mezzanine-ui/core/page-header';
import Breadcrumb, { BreadcrumbProps } from '../Breadcrumb';
import ContentHeader, { ContentHeaderProps } from '../ContentHeader';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { flattenChildren } from '../utils/flatten-children';

type PageHeaderChild =
  | ReactElement<BreadcrumbProps>
  | ReactElement<ContentHeaderProps>
  | null
  | undefined
  | false;

/**
 * Props for the PageHeader component.
 * Extends native HTML header element props.
 */
export type PageHeaderProps = NativeElementPropsWithoutKeyAndRef<'header'> & {
  /**
   * Child components: Breadcrumb or ContentHeader
   * */
  children?: PageHeaderChild | PageHeaderChild[];
};

const getBreadcrumbAndToolbar = (
  children: PageHeaderProps['children'],
): {
  breadcrumb?: ReactElement<BreadcrumbProps>;
  contentHeader?: ReactElement<ContentHeaderProps>;
} => {
  let breadcrumb: ReactElement<BreadcrumbProps> | undefined;
  let contentHeader: ReactElement<ContentHeaderProps> | undefined;

  const childrenArray = flattenChildren(children);

  if (children) {
    childrenArray.forEach((child) => {
      if (!isValidElement(child)) return;

      if (child.type === Breadcrumb) {
        if (breadcrumb) {
          console.warn(
            '[Mezzanine][PageHeader] only accepts one Breadcrumb as its child.',
          );
        }

        breadcrumb = child as ReactElement<BreadcrumbProps>;
      } else if (child.type === ContentHeader) {
        if (contentHeader) {
          console.warn(
            '[Mezzanine][PageHeader] only accepts one ContentHeader as its child.',
          );
        }

        const sizeProp = (child as ReactElement<ContentHeaderProps>).props.size;

        if (sizeProp !== undefined && sizeProp !== 'main') {
          console.warn(
            '[Mezzanine][PageHeader] ContentHeader size prop will be overridden to "main".',
          );
        }

        contentHeader = cloneElement(
          child as ReactElement<ContentHeaderProps>,
          {
            size: 'main',
          },
        ) as ReactElement<ContentHeaderProps>;
      } else {
        console.warn(
          '[Mezzanine][PageHeader] only accepts Breadcrumb or ContentHeader as its children.',
        );
      }
    });
  }

  if (!contentHeader) {
    console.error(
      '[Mezzanine][PageHeader] requires a ContentHeader as its child.',
    );
  }

  return { breadcrumb, contentHeader };
};

/**
 * PageHeader component
 *
 * Used to display the page header, typically containing a `<Breadcrumb />` and a `<ContentHeader />`.
 *
 * @example
 * ```tsx
 * <PageHeader>
 *   <Breadcrumb
 *     links={[
 *       { id: '1', children: 'Home', href: '/' },
 *       { id: '2', children: 'Page Header' },
 *     ]}
 *   />
 *
 *   <ContentHeader
 *     title="Page Title"
 *     description="This is the page description."
 *   >
 *     <Button variant="base-secondary">Secondary</Button>
 *     <Button>Primary</Button>
 *   </ContentHeader>
 * </PageHeader>
 * ```
 */
const PageHeader = forwardRef<HTMLElement, PageHeaderProps>(
  function PageHeader(props, ref) {
    const { children, className, ...rest } = props;

    const { breadcrumb, contentHeader } = getBreadcrumbAndToolbar(children);

    return (
      <header {...rest} className={cx(classes.host, className)} ref={ref}>
        {breadcrumb}
        {contentHeader}
      </header>
    );
  },
);

export default PageHeader;

// packages/vue/page-header/page-header.vue
<script setup lang="ts">
import { cloneVNode, computed, useSlots } from 'vue';
import type { FunctionalComponent, VNode } from 'vue';
import { pageHeaderClasses as classes } from '@mezzanine-ui/core/page-header';
import { flattenChildren } from '../_internal/flatten-children';
import MznBreadcrumb from '../breadcrumb/breadcrumb.vue';
import MznContentHeader from '../content-header/content-header.vue';
import type { PageHeaderProps } from './page-header.types';

/**
 * 頁面標頭：一組麵包屑加上一個內容標題列。
 *
 * slot 只收 MznBreadcrumb 與 MznContentHeader，各一個；內容標題列的 `size` 一律
 * 被改成 `main`。少了內容標題列會在 console 報錯。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznPageHeader } from '@mezzanine-ui/vue/page-header';
 * <\/script>
 *
 * <template>
 *   <MznPageHeader>
 *     <MznBreadcrumb>...</MznBreadcrumb>
 *     <MznContentHeader title="Page Title" />
 *   </MznPageHeader>
 * </template>
 * ```
 *
 * @see MznContentHeader 頁面標頭裡的內容標題列
 */
defineProps<PageHeaderProps>();

defineSlots<{
  /** One MznBreadcrumb and one MznContentHeader. */
  default?: () => unknown;
}>();

const slots = useSlots();

const resolved = computed(
  (): { breadcrumb: VNode | null; contentHeader: VNode | null } => {
    let breadcrumb: VNode | null = null;
    let contentHeader: VNode | null = null;

    flattenChildren(slots.default?.()).forEach((child) => {
      if (child.type === MznBreadcrumb) {
        if (breadcrumb) {
          console.warn(
            '[Mezzanine][PageHeader] only accepts one Breadcrumb as its child.',
          );
        }

        breadcrumb = child;
      } else if (child.type === MznContentHeader) {
        if (contentHeader) {
          console.warn(
            '[Mezzanine][PageHeader] only accepts one ContentHeader as its child.',
          );
        }

        const sizeProp = (child.props as { size?: string } | null)?.size;

        if (sizeProp !== undefined && sizeProp !== 'main') {
          console.warn(
            '[Mezzanine][PageHeader] ContentHeader size prop will be overridden to "main".',
          );
        }

        contentHeader = cloneVNode(child, { size: 'main' });
      } else {
        console.warn(
          '[Mezzanine][PageHeader] only accepts Breadcrumb or ContentHeader as its children.',
        );
      }
    });

    if (!contentHeader) {
      console.error(
        '[Mezzanine][PageHeader] requires a ContentHeader as its child.',
      );
    }

    return { breadcrumb, contentHeader };
  },
);

const Breadcrumb: FunctionalComponent = () => resolved.value.breadcrumb;
const ContentHeader: FunctionalComponent = () => resolved.value.contentHeader;
</script>

<template>
  <header :class="classes.host">
    <Breadcrumb />
    <ContentHeader />
  </header>
</template>
