// packages/vue/tag/tag.vue
<script setup lang="ts">
import { computed } from 'vue';
import { tagClasses as classes } from '@mezzanine-ui/core/tag';
import { CloseIcon, PlusIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznBadge from '../badge/badge.vue';
import MznIcon from '../icon/icon.vue';
import type { TagProps } from './tag.types';

/**
 * 標籤元件，用於分類、篩選或標記內容，支援靜態、計數、可關閉及可新增四種模式。
 *
 * 透過 `type` prop 切換顯示模式：`static` 純標籤（預設）、`counter` 帶數字的標籤、
 * `dismissable` 含關閉按鈕、`addable` 含新增按鈕。`overflow-counter` 適用於收合多餘標籤並顯示剩餘數量。
 * `dismissable` 與 `addable` 模式支援 `active` 和 `disabled` 狀態；
 * `overflow-counter` 與 `addable` 渲染為 `button`，其餘為 `span`。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznTag } from '@mezzanine-ui/vue/tag';
 * <\/script>
 *
 * <template>
 *   <MznTag label="設計" type="static" />
 *   <MznTag :count="3" label="待處理" type="counter" />
 *   <MznTag label="React" type="dismissable" @close="removeTag('React')" />
 *   <MznTag label="新增標籤" type="addable" @click="handleAdd" />
 *   <MznTag :count="5" type="overflow-counter" @click="handleExpand" />
 * </template>
 * ```
 *
 * @see MznTagGroup 以群組方式管理多個標籤
 */
const props = withDefaults(defineProps<TagProps>(), {
  active: undefined,
  count: undefined,
  disabled: undefined,
  label: undefined,
  readOnly: undefined,
  size: 'main',
  type: 'static',
});

const emit = defineEmits<{
  /** Handler fired when button-based tag clicked. */
  click: [event: MouseEvent];
  /** Handler fired when the close button in dismissable tag is clicked. */
  close: [event: MouseEvent];
}>();

const hostClasses = computed((): string =>
  clsx(classes.host, classes.size(props.size), classes.type(props.type), {
    [classes.disabled]: props.disabled,
    [classes.active]: props.active,
    [classes.readOnly]: props.readOnly,
  }),
);

const isButtonHost = computed(
  (): boolean => props.type === 'overflow-counter' || props.type === 'addable',
);

const iconClass = classes.icon;
const labelClass = classes.label;
const closeButtonClass = classes.closeButton;
</script>

<template>
  <button
    v-if="isButtonHost"
    :class="hostClasses"
    :disabled="disabled"
    type="button"
    @click="emit('click', $event)"
  >
    <MznIcon :class="iconClass" :icon="PlusIcon" :size="16" />
    <span :class="labelClass">{{
      type === 'overflow-counter' ? count : label
    }}</span>
  </button>
  <span v-else :aria-disabled="disabled" :class="hostClasses">
    <span v-if="type === 'static'" :class="labelClass">{{ label }}</span>
    <template v-if="type === 'counter'">
      <span :class="labelClass">{{ label }}</span>
      <MznBadge :count="count ?? 0" variant="count-info" />
    </template>
    <template v-if="type === 'dismissable'">
      <span :class="labelClass">{{ label }}</span>
      <button
        :class="closeButtonClass"
        :disabled="disabled"
        type="button"
        @click="emit('close', $event)"
      >
        <MznIcon :class="iconClass" :icon="CloseIcon" :size="16" />
      </button>
    </template>
  </span>
</template>

// packages/ng/tag/tag.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import {
  TagSize,
  TagType,
  tagClasses as classes,
} from '@mezzanine-ui/core/tag';
import { PlusIcon, CloseIcon, IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznBadge } from '@mezzanine-ui/ng/badge';

/**
 * 標籤元件，用於分類、篩選或標記內容。
 *
 * 支援五種模式：`static`（純標籤）、`counter`（帶數字）、`dismissable`（可關閉）、
 * `addable`（可新增）及 `overflow-counter`（溢出計數）。
 *
 * @example
 * ```html
 * import { MznTag } from '@mezzanine-ui/ng/tag';
 *
 * <span mznTag type="static" label="設計" ></span>
 * <span mznTag type="counter" label="待處理" [count]="3" ></span>
 * <span mznTag type="dismissable" label="React" (close)="removeTag('React')" ></span>
 * <span mznTag type="addable" label="新增標籤" (click)="handleAdd()" ></span>
 * ```
 */
@Component({
  selector: '[mznTag]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon, MznBadge],
  host: {
    '[class]': 'hostClasses()',
    '[attr.aria-disabled]': 'disabled() || null',
    '[attr.type]': 'null',
    '[attr.label]': 'null',
    '[attr.size]': 'null',
    '[attr.count]': 'null',
    '[attr.disabled]': 'null',
    '[attr.active]': 'null',
    '[attr.readOnly]': 'null',
  },
  template: `
    @switch (type()) {
      @case ('overflow-counter') {
        <button
          type="button"
          style="display: inline-flex; align-items: center; gap: inherit; padding: 0; border: none; background: none; color: inherit; font: inherit; cursor: pointer;"
          [disabled]="disabled()"
          (click)="tagClick.emit($event)"
        >
          <i mznIcon [class]="classes.icon" [icon]="plusIcon" [size]="16"></i>
          <span [class]="classes.label">{{ count() }}</span>
        </button>
      }
      @case ('addable') {
        <button
          type="button"
          style="display: inline-flex; align-items: center; gap: inherit; padding: 0; border: none; background: none; color: inherit; font: inherit; cursor: pointer;"
          [disabled]="disabled()"
          (click)="tagClick.emit($event)"
        >
          <i mznIcon [class]="classes.icon" [icon]="plusIcon" [size]="16"></i>
          <span [class]="classes.label">{{ label() }}</span>
        </button>
      }
      @default {
        <span [class]="classes.label">{{ label() }}</span>
        @if (type() === 'counter') {
          <div mznBadge variant="count-info" [count]="count() ?? 0"></div>
        }
        @if (type() === 'dismissable') {
          <button
            [class]="classes.closeButton"
            type="button"
            [disabled]="disabled()"
            (click)="close.emit($event)"
          >
            <i
              mznIcon
              [class]="classes.icon"
              [icon]="closeIcon"
              [size]="16"
            ></i>
          </button>
        }
      }
    }
  `,
})
export class MznTag {
  protected readonly classes = classes;
  protected readonly plusIcon: IconDefinition = PlusIcon;
  protected readonly closeIcon: IconDefinition = CloseIcon;

  /**
   * 標籤類型。
   * @default 'static'
   */
  readonly type = input<TagType>('static');

  /** 標籤顯示的文字。 */
  readonly label = input<string>();

  /**
   * 標籤尺寸。
   * @default 'main'
   */
  readonly size = input<TagSize>('main');

  /** 計數器/溢出計數器的數字。 */
  readonly count = input<number>();

  /**
   * 是否禁用。
   * @default false
   */
  readonly disabled = input(false);

  /**
   * 是否啟用中。
   * @default false
   */
  readonly active = input(false);

  /**
   * 是否唯讀。
   * @default false
   */
  readonly readOnly = input(false);

  /** 可關閉標籤的關閉事件。 */
  readonly close = output<MouseEvent>();

  /** 可點擊標籤（addable/overflow-counter）的點擊事件。 */
  readonly tagClick = output<MouseEvent>();

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.size(this.size()), classes.type(this.type()), {
      [classes.disabled]: this.disabled(),
      [classes.active]: this.active(),
      [classes.readOnly]: this.readOnly(),
    }),
  );
}
