// packages/react/src/Button/Button.tsx
'use client';

import { forwardRef, MouseEvent, useCallback, useRef } from 'react';
import { buttonClasses as classes } from '@mezzanine-ui/core/button';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { cx } from '../utils/cx';
import { ComponentOverridableForwardRefComponentPropsFactory } from '../utils/jsx-types';
import Icon from '../Icon';
import Spin from '../Spin';
import Tooltip from '../Tooltip';
import { ButtonComponent, ButtonPropsBase } from './typings';

export type ButtonProps<C extends ButtonComponent = 'button'> =
  ComponentOverridableForwardRefComponentPropsFactory<
    ButtonComponent,
    C,
    ButtonPropsBase
  >;

/**
 * 通用按鈕元件，支援多種外觀變體與尺寸。
 *
 * 可透過 `variant` 控制外觀（如 `base-primary`、`outlined-primary`、`text-primary` 等），
 * 透過 `iconType` 決定圖示的位置（`leading`、`trailing` 或 `icon-only`）。
 * 當 `iconType` 為 `icon-only` 時，`children` 會作為 Tooltip 的提示文字顯示。
 * 支援 `loading` 狀態，以及透過 `component` prop 將根元素替換為任意元件（例如 `<a>`）。
 *
 * @example
 * ```tsx
 * import Button from '@mezzanine-ui/react/Button';
 * import { PlusIcon, ArrowRightIcon } from '@mezzanine-ui/icons';
 *
 * // 基本用法
 * <Button variant="base-primary">送出</Button>
 *
 * // 帶有前置圖示
 * <Button icon={PlusIcon} iconType="leading" variant="outlined-primary">新增項目</Button>
 *
 * // 僅圖示（hover 時顯示 Tooltip）
 * <Button icon={PlusIcon} iconType="icon-only">新增</Button>
 *
 * // 以 <a> 標籤渲染（多型態用法）
 * <Button component="a" href="/dashboard" icon={ArrowRightIcon} iconType="trailing">前往儀表板</Button>
 * ```
 *
 * @see {@link ButtonGroup} 用於將多個 Button 水平排列為群組
 */
const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(props, ref) {
    const {
      'aria-describedby': ariaDescribedBy,
      children,
      className,
      component: Component = 'button',
      disabled = false,
      disabledTooltip = false,
      icon,
      iconType,
      loading = false,
      onBlur,
      onClick,
      onFocus,
      size = 'main',
      tooltipPosition = 'bottom',
      variant = 'base-primary',
      ...rest
    } = props;

    const isIconOnly = iconType === 'icon-only';
    const showTooltip = isIconOnly && !disabledTooltip && Boolean(children);

    /**
     * Tooltip 分支會提供自己的 ref，必須與呼叫端的 ref 合成而非取代，
     * 否則像 Dropdown 這種以 anchorRef 定位的消費端會拿不到 DOM 節點。
     * 這裡用 holder + 穩定的 callback ref，避免每次 render 產生新的
     * ref 函式導致 Tooltip 的 target state 反覆 detach/attach。
     */
    const tooltipTargetRef = useRef<React.RefCallback<HTMLElement> | null>(
      null,
    );
    const attachTooltipTarget = useCallback(
      (element: HTMLButtonElement | null) => {
        tooltipTargetRef.current?.(element);
      },
      [],
    );
    const composedRef = useComposeRefs<HTMLButtonElement>([
      ref,
      attachTooltipTarget,
    ]);

    // Loading 狀態下的 icon
    const loadingIcon = <Spin loading size="minor" />;

    // 渲染 icon 內容
    const renderIcon = () => {
      if (loading) {
        return loadingIcon;
      }
      if (icon) {
        return <Icon icon={icon} size={16} />;
      }
      return null;
    };

    const buttonElement = (tooltipProps?: {
      'aria-describedby': string | undefined;
      onBlur: React.FocusEventHandler;
      onFocus: React.FocusEventHandler;
      onMouseEnter: React.MouseEventHandler;
      onMouseLeave: React.MouseEventHandler;
      ref: React.RefCallback<HTMLElement>;
    }) => {
      tooltipTargetRef.current = tooltipProps?.ref ?? null;

      return (
        <Component
          {...rest}
          ref={composedRef}
          aria-describedby={
            [ariaDescribedBy, tooltipProps?.['aria-describedby']]
              .filter(Boolean)
              .join(' ') || undefined
          }
          aria-disabled={disabled}
          className={cx(
            classes.host,
            classes.variant(variant),
            classes.size(size),
            {
              [classes.disabled]: disabled,
              [classes.loading]: loading,
              [classes.iconLeading]: iconType === 'leading',
              [classes.iconTrailing]: iconType === 'trailing',
              [classes.iconOnly]: isIconOnly,
            },
            className,
          )}
          disabled={disabled}
          onClick={(event: MouseEvent<HTMLButtonElement>) => {
            if (!disabled && !loading && onClick) {
              onClick(event);
            }
          }}
          onBlur={(event: React.FocusEvent<HTMLButtonElement>) => {
            onBlur?.(event);
            tooltipProps?.onBlur(event);
          }}
          onFocus={(event: React.FocusEvent<HTMLButtonElement>) => {
            onFocus?.(event);
            tooltipProps?.onFocus(event);
          }}
          {...(tooltipProps && {
            onMouseEnter: tooltipProps.onMouseEnter,
            onMouseLeave: tooltipProps.onMouseLeave,
          })}
        >
          {loading ? (
            renderIcon()
          ) : (
            <>
              {(iconType === 'leading' || isIconOnly) && renderIcon()}
              {!isIconOnly && children}
              {iconType === 'trailing' && renderIcon()}
            </>
          )}
        </Component>
      );
    };

    if (showTooltip) {
      return (
        <Tooltip options={{ placement: tooltipPosition }} title={children}>
          {(tooltipProps) => buttonElement(tooltipProps)}
        </Tooltip>
      );
    }

    return buttonElement();
  },
);

export default Button;

// packages/vue/button/button.vue
<script setup lang="ts">
import { computed, h, useAttrs, useSlots } from 'vue';
import type { FunctionalComponent, VNode } from 'vue';
import { buttonClasses as classes } from '@mezzanine-ui/core/button';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTooltip from '../tooltip/tooltip.vue';
import type { PopperOptions } from '../popper/popper.types';
import type { TooltipTriggerProps } from '../tooltip/tooltip.types';
import type { ButtonProps } from './button.types';

/**
 * 通用按鈕元件，支援多種外觀變體與尺寸。
 *
 * `variant` 控制外觀，`iconType` 決定圖示的位置（`leading`、`trailing` 或
 * `icon-only`）。當 `iconType` 為 `icon-only` 時，預設 slot 的內容會作為
 * tooltip 的提示文字而不是按鈕文字。`loading` 會以轉圈取代圖示，並擋下點擊。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznButton } from '@mezzanine-ui/vue/button';
 * import { PlusIcon } from '@mezzanine-ui/icons';
 * <\/script>
 *
 * <template>
 *   <MznButton variant="base-primary">送出</MznButton>
 *   <MznButton :icon="PlusIcon" icon-type="leading" variant="outlined-primary">
 *     新增項目
 *   </MznButton>
 *   <MznButton :icon="PlusIcon" icon-type="icon-only">新增</MznButton>
 * </template>
 * ```
 *
 * @see MznButtonGroup 將多個按鈕水平或垂直排列為群組
 */
/**
 * React composes the consumer's `onClick`, `onFocus` and `onBlur` with its own
 * — click is swallowed while disabled or loading, focus and blur are shared
 * with the tooltip — so the listeners are read from `$attrs` and re-bound
 * rather than left to fall through.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ButtonProps>(), {
  disabled: false,
  disabledTooltip: false,
  icon: undefined,
  iconType: undefined,
  loading: false,
  size: 'main',
  tooltipPosition: 'bottom',
  variant: 'base-primary',
});

defineSlots<{
  /**
   * The button text content. With `iconType="icon-only"` it becomes the
   * tooltip's content instead.
   */
  default?: () => unknown;
}>();

const attrs = useAttrs();
const slots = useSlots();

type AttrHandler =
  | ((event: never) => void)
  | ((event: never) => void)[]
  | undefined;

/** `$attrs` holds either one listener or an array of them. */
function call(handler: AttrHandler, event: Event): void {
  const listeners = Array.isArray(handler) ? handler : [handler];

  listeners.forEach((listener) =>
    (listener as ((event: Event) => void) | undefined)?.(event),
  );
}

const isIconOnly = computed((): boolean => props.iconType === 'icon-only');

const showTooltip = computed(
  (): boolean =>
    isIconOnly.value && !props.disabledTooltip && Boolean(slots.default),
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.variant(props.variant),
    classes.size(props.size),
    {
      [classes.disabled]: props.disabled,
      [classes.loading]: props.loading,
      [classes.iconLeading]: props.iconType === 'leading',
      [classes.iconTrailing]: props.iconType === 'trailing',
      [classes.iconOnly]: isIconOnly.value,
    },
    attrs.class as string,
  ),
);

const tooltipOptions = computed(
  (): PopperOptions => ({ placement: props.tooltipPosition }),
);

const forwardedAttrs = computed(() => {
  const {
    'aria-describedby': _describedBy,
    class: _class,
    onBlur: _onBlur,
    onClick: _onClick,
    onFocus: _onFocus,
    ...rest
  } = attrs;

  return rest;
});

/**
 * Everything the root element takes, in one place: React writes it once and
 * calls it from both the plain and the tooltip-wrapped branch, and so does the
 * template below.
 */
function rootBindings(tooltipProps?: TooltipTriggerProps) {
  return {
    ...forwardedAttrs.value,
    'aria-describedby':
      [attrs['aria-describedby'], tooltipProps?.['aria-describedby']]
        .filter(Boolean)
        .join(' ') || undefined,
    'aria-disabled': props.disabled,
    class: hostClasses.value,
    disabled: props.disabled,
    onBlur: (event: FocusEvent): void => {
      call(attrs.onBlur as AttrHandler, event);
      tooltipProps?.onBlur();
    },
    onClick: (event: MouseEvent): void => {
      if (!props.disabled && !props.loading) {
        call(attrs.onClick as AttrHandler, event);
      }
    },
    onFocus: (event: FocusEvent): void => {
      call(attrs.onFocus as AttrHandler, event);
      tooltipProps?.onFocus(event);
    },
    ...(tooltipProps && {
      onMouseenter: tooltipProps.onMouseenter,
      onMouseleave: tooltipProps.onMouseleave,
      ref: tooltipProps.ref,
    }),
  };
}

/**
 * The icon slot of the button: the spinner while loading, the icon otherwise,
 * and nothing when neither applies.
 */
const ButtonIcon: FunctionalComponent = () => {
  if (props.loading) return h(MznSpin, { loading: true, size: 'minor' });
  if (props.icon) return h(MznIcon, { icon: props.icon, size: 16 });

  return null;
};

/** Content arrangement, shared by both branches. */
const ButtonContent: FunctionalComponent = () => {
  if (props.loading) return h(ButtonIcon);

  const children: (VNode | unknown)[] = [];

  if (props.iconType === 'leading' || isIconOnly.value) {
    children.push(h(ButtonIcon));
  }

  if (!isIconOnly.value) children.push(slots.default?.());
  if (props.iconType === 'trailing') children.push(h(ButtonIcon));

  return children as VNode[];
};
</script>

<template>
  <MznTooltip v-if="showTooltip" :options="tooltipOptions">
    <template #title>
      <slot />
    </template>
    <template #default="tooltipProps">
      <button v-bind="rootBindings(tooltipProps)">
        <ButtonContent />
      </button>
    </template>
  </MznTooltip>

  <button v-else v-bind="rootBindings()">
    <ButtonContent />
  </button>
</template>
