// packages/react/src/Modal/ModalBodyForVerification.tsx
'use client';

import {
  forwardRef,
  useRef,
  useState,
  useEffect,
  KeyboardEvent,
  ClipboardEvent,
  ChangeEvent,
} from 'react';
import { modalClasses } from '@mezzanine-ui/core/modal';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Typography from '../Typography';

export interface ModalBodyForVerificationProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'onChange'> {
  /**
   * Whether to auto focus the first input when mounted.
   * @default true
   */
  autoFocus?: boolean;
  /**
   * Whether the inputs are disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Whether the inputs are in error state.
   * @default false
   */
  error?: boolean;
  /**
   * Number of verification code digits.
   * @default 4
   */
  length?: number;
  /**
   * Called when verification code changes.
   */
  onChange?: (value: string) => void;
  /**
   * Called when all digits are filled.
   */
  onComplete?: (value: string) => void;
  /**
   * Called when resend link is clicked.
   */
  onResend?: () => void;
  /**
   * Whether the inputs are readonly.
   * @default false
   */
  readOnly?: boolean;
  /**
   * Prompt text before resend link.
   * @default "收不到驗證碼？"
   */
  resendPrompt?: string;
  /**
   * Resend link text.
   * @default "點此重新寄送"
   */
  resendText?: string;
  /**
   * Current verification code value.
   */
  value?: string;
}

/**
 * The react component for verification code input in modal.
 */
const ModalBodyForVerification = forwardRef<
  HTMLDivElement,
  ModalBodyForVerificationProps
>(function ModalBodyForVerification(props, ref) {
  const {
    autoFocus = true,
    className,
    disabled = false,
    error = false,
    length = 4,
    onChange,
    onComplete,
    onResend,
    readOnly = false,
    resendPrompt = '收不到驗證碼？',
    resendText = '點此重新寄送',
    value = '',
    ...rest
  } = props;

  const [codes, setCodes] = useState<string[]>(
    value
      .split('')
      .slice(0, length)
      .concat(Array(length - value.length).fill('')),
  );
  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  // Auto focus first input when mounted
  useEffect(() => {
    if (autoFocus && !disabled && !readOnly) {
      inputRefs.current[0]?.focus();
    }
  }, [autoFocus, disabled, readOnly]);

  const handleChange = (index: number, newValue: string) => {
    if (disabled || readOnly) return;

    // Only allow single digit/letter
    const sanitized = newValue.slice(-1);

    const newCodes = [...codes];
    newCodes[index] = sanitized;
    setCodes(newCodes);

    const fullValue = newCodes.join('');
    onChange?.(fullValue);

    // Auto focus next input
    if (sanitized && index < length - 1) {
      inputRefs.current[index + 1]?.focus();
    }

    // Call onComplete when all filled
    if (fullValue.length === length) {
      onComplete?.(fullValue);
    }
  };

  const handleKeyDown = (index: number, e: KeyboardEvent<HTMLInputElement>) => {
    // Handle backspace
    if (e.key === 'Backspace') {
      if (disabled || readOnly) return;

      if (!codes[index] && index > 0) {
        // If current is empty, focus previous
        inputRefs.current[index - 1]?.focus();
      } else {
        // Clear current
        const newCodes = [...codes];
        newCodes[index] = '';
        setCodes(newCodes);
        onChange?.(newCodes.join(''));
      }
    }
    // Handle arrow keys
    else if (e.key === 'ArrowLeft' && index > 0) {
      inputRefs.current[index - 1]?.focus();
    } else if (e.key === 'ArrowRight' && index < length - 1) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handlePaste = (e: ClipboardEvent<HTMLInputElement>) => {
    if (disabled || readOnly) return;

    e.preventDefault();
    const pastedData = e.clipboardData.getData('text').slice(0, length);
    const newCodes = pastedData
      .split('')
      .concat(Array(length - pastedData.length).fill(''));

    setCodes(newCodes);
    onChange?.(pastedData);

    // Focus the next empty input or the last input
    const nextEmptyIndex = Math.min(pastedData.length, length - 1);
    inputRefs.current[nextEmptyIndex]?.focus();

    if (pastedData.length === length) {
      onComplete?.(pastedData);
    }
  };

  const handleInputChange = (
    index: number,
    e: ChangeEvent<HTMLInputElement>,
  ) => {
    handleChange(index, e.target.value);
  };

  return (
    <div
      {...rest}
      ref={ref}
      className={cx(modalClasses.modalBodyVerification, className)}
    >
      <div
        className={cx(modalClasses.modalBodyVerificationInputs, {
          [modalClasses.modalBodyVerificationInputsExtended]: length > 4,
        })}
      >
        {Array.from({ length }).map((_, index) => (
          <input
            key={index}
            ref={(el) => {
              inputRefs.current[index] = el;
            }}
            type="text"
            inputMode="numeric"
            maxLength={1}
            value={codes[index] || ''}
            onChange={(e) => handleInputChange(index, e)}
            onKeyDown={(e) => handleKeyDown(index, e)}
            onPaste={handlePaste}
            className={cx(modalClasses.modalBodyVerificationInput, {
              [modalClasses.modalBodyVerificationInputError]: error,
            })}
            autoComplete="off"
            disabled={disabled}
            readOnly={readOnly}
          />
        ))}
      </div>
      {onResend && (
        <div className={modalClasses.modalBodyVerificationResend}>
          <Typography variant="caption" color="text-neutral">
            {resendPrompt}
          </Typography>
          <Typography
            variant="caption"
            color="text-neutral"
            className={modalClasses.modalBodyVerificationResendLink}
            onClick={onResend}
            component="span"
            style={{ cursor: 'pointer', textDecoration: 'underline' }}
          >
            {resendText}
          </Typography>
        </div>
      )}
    </div>
  );
});

export default ModalBodyForVerification;

// packages/ng/modal/modal-body-for-verification.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  afterNextRender,
  computed,
  effect,
  input,
  output,
  signal,
  viewChildren,
  ElementRef,
} from '@angular/core';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import { MznTypography } from '@mezzanine-ui/ng/typography';

/**
 * Modal 驗證碼輸入元件，用於 OTP / 驗證碼輸入場景。
 *
 * 提供多個單字元輸入欄位，支援自動前進、Backspace 退格、方向鍵導覽、貼上分配，
 * 以及全部填滿時的 `completed` 事件。可選配重新傳送連結。
 *
 * @example
 * ```html
 * import { MznModalBodyForVerification } from '@mezzanine-ui/ng/modal';
 *
 * <div mznModalBodyForVerification
 *   [length]="6"
 *   [autoFocus]="true"
 *   resendText="點此重新寄送"
 *   (valueChange)="onCodeChange($event)"
 *   (completed)="onComplete($event)"
 *   (resent)="onResend()"
 * ></div>
 * ```
 *
 * @see MznModal
 * @see MznModalFooter
 */
@Component({
  selector: '[mznModalBodyForVerification]',
  host: {
    '[class]': 'verificationClass',
    '[attr.autoFocus]': 'null',
    '[attr.disabled]': 'null',
    '[attr.error]': 'null',
    '[attr.length]': 'null',
    '[attr.readOnly]': 'null',
    '[attr.resendPrompt]': 'null',
    '[attr.resendText]': 'null',
    '[attr.value]': 'null',
  },
  standalone: true,
  imports: [MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="inputsClass()">
      @for (code of codes(); track $index) {
        <input
          #codeInput
          [class]="inputClass()"
          type="text"
          inputMode="numeric"
          maxlength="1"
          autocomplete="off"
          [value]="code"
          [disabled]="disabled()"
          [readOnly]="readOnly()"
          (input)="onInput($index, $event)"
          (keydown)="onKeyDown($index, $event)"
          (paste)="onPaste($index, $event)"
        />
      }
    </div>
    @if (resendText()) {
      <div [class]="resendClass">
        <span mznTypography variant="caption" color="text-neutral">{{
          resendPrompt()
        }}</span>
        <span
          mznTypography
          variant="caption"
          color="text-neutral"
          [class]="resendLinkClass"
          style="cursor: pointer; text-decoration: underline;"
          (click)="onResendClick()"
          >{{ resendText() }}</span
        >
      </div>
    }
  `,
})
export class MznModalBodyForVerification {
  /** 是否在掛載後自動聚焦第一個輸入框。 @default true */
  readonly autoFocus = input(true);

  /** 是否禁用所有輸入框。 @default false */
  readonly disabled = input(false);

  /** 是否顯示錯誤樣式。 @default false */
  readonly error = input(false);

  /** 驗證碼欄位數量。 @default 4 */
  readonly length = input(4);

  /** 是否為唯讀模式。 @default false */
  readonly readOnly = input(false);

  /** 重新傳送連結前的提示文字。 @default '收不到驗證碼？' */
  readonly resendPrompt = input('收不到驗證碼？');

  /** 可點擊的重新傳送連結文字，有值時才顯示重新傳送區塊。 */
  readonly resendText = input<string>();

  /** 初始值，依序填入各欄位。 @default '' */
  readonly value = input('');

  /** 任一欄位變更時發出，值為所有欄位串接後的字串。 */
  readonly valueChange = output<string>();

  /** 所有欄位填滿時發出，值為完整驗證碼字串。 */
  readonly completed = output<string>();

  /** 點擊重新傳送連結時發出。 */
  readonly resent = output<void>();

  /** 各欄位的單字元陣列。 */
  readonly codes = signal<string[]>([]);

  private readonly inputRefs =
    viewChildren<ElementRef<HTMLInputElement>>('codeInput');

  protected readonly verificationClass = classes.modalBodyVerification;
  protected readonly resendClass = classes.modalBodyVerificationResend;
  protected readonly resendLinkClass = classes.modalBodyVerificationResendLink;

  protected readonly inputsClass = computed((): string =>
    clsx(classes.modalBodyVerificationInputs, {
      [classes.modalBodyVerificationInputsExtended]: this.length() > 4,
    }),
  );

  protected readonly inputClass = computed((): string =>
    clsx(classes.modalBodyVerificationInput, {
      [classes.modalBodyVerificationInputError]: this.error(),
    }),
  );

  constructor() {
    // Seed codes array from value input
    effect(() => {
      const val = this.value();
      const len = this.length();
      const chars = val.split('').slice(0, len);
      const padded = chars.concat(Array<string>(len - chars.length).fill(''));

      this.codes.set(padded);
    });

    // Auto-focus first input after initial render
    afterNextRender(() => {
      if (this.autoFocus() && !this.disabled() && !this.readOnly()) {
        const refs = this.inputRefs();

        if (refs.length > 0) {
          refs[0].nativeElement.focus();
        }
      }
    });
  }

  protected onInput(index: number, event: Event): void {
    if (this.disabled() || this.readOnly()) return;

    const input = event.target as HTMLInputElement;
    const sanitized = input.value.slice(-1);

    const newCodes = [...this.codes()];

    newCodes[index] = sanitized;
    this.codes.set(newCodes);

    const fullValue = newCodes.join('');

    this.valueChange.emit(fullValue);

    // Auto-advance to next input
    if (sanitized && index < this.length() - 1) {
      const refs = this.inputRefs();

      refs[index + 1]?.nativeElement.focus();
    }

    // Check completion
    if (newCodes.every((c) => c !== '')) {
      this.completed.emit(fullValue);
    }
  }

  protected onKeyDown(index: number, event: KeyboardEvent): void {
    if (event.key === 'Backspace') {
      if (this.disabled() || this.readOnly()) return;

      const currentCodes = this.codes();

      if (!currentCodes[index] && index > 0) {
        // Current empty — focus previous
        const refs = this.inputRefs();

        refs[index - 1]?.nativeElement.focus();
      } else {
        // Clear current
        const newCodes = [...currentCodes];

        newCodes[index] = '';
        this.codes.set(newCodes);
        this.valueChange.emit(newCodes.join(''));
      }
    } else if (event.key === 'ArrowLeft' && index > 0) {
      const refs = this.inputRefs();

      refs[index - 1]?.nativeElement.focus();
    } else if (event.key === 'ArrowRight' && index < this.length() - 1) {
      const refs = this.inputRefs();

      refs[index + 1]?.nativeElement.focus();
    }
  }

  protected onPaste(index: number, event: ClipboardEvent): void {
    if (this.disabled() || this.readOnly()) return;

    event.preventDefault();

    const pastedData = event.clipboardData?.getData('text') ?? '';
    const len = this.length();
    const sliced = pastedData.slice(0, len - index);
    const chars = sliced.split('');
    const newCodes = [...this.codes()];

    chars.forEach((char, i) => {
      newCodes[index + i] = char;
    });

    this.codes.set(newCodes);

    const fullValue = newCodes.join('');

    this.valueChange.emit(fullValue);

    // Focus the next empty input or the last filled position
    const nextFocusIndex = Math.min(index + chars.length, len - 1);
    const refs = this.inputRefs();

    refs[nextFocusIndex]?.nativeElement.focus();

    if (newCodes.every((c) => c !== '')) {
      this.completed.emit(fullValue);
    }
  }

  protected onResendClick(): void {
    this.resent.emit();
  }
}
