// packages/vue/modal/modal-footer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import MznButtonGroup from '../button/button-group.vue';
import type { ButtonProps } from '../button/button.types';
import MznCheckbox from '../checkbox/checkbox.vue';
import MznToggle from '../toggle/toggle.vue';
import MznTypography from '../typography/typography.vue';
import type { ModalFooterProps } from './modal-footer.types';

/**
 * Modal 的操作列：右側是取消與確認按鈕，左側可放一份輔助內容。
 *
 * `auxiliaryContentType` 決定左側放什麼 —— 註記文字、文字按鈕、核取方塊、
 * 切換開關，或密碼情境（記住我＋忘記密碼）。`loading` 會讓確認鈕轉圈、
 * 取消鈕停用。沒有輔助內容時，`actionsButtonLayout="fill"` 可讓兩顆按鈕等分寬度。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznModalFooter } from '@mezzanine-ui/vue/modal';
 * <\/script>
 *
 * <template>
 *   <MznModalFooter
 *     cancel-text="取消"
 *     confirm-text="確認"
 *     @cancel="close"
 *     @confirm="submit"
 *   />
 *
 *   <MznModalFooter
 *     annotation="這個動作無法復原"
 *     auxiliary-content-type="annotation"
 *     confirm-text="刪除"
 *     :show-cancel-button="false"
 *     @confirm="remove"
 *   />
 * </template>
 * ```
 *
 * @see MznModal 以 showModalFooter 渲染這個操作列
 */
const props = withDefaults(defineProps<ModalFooterProps>(), {
  actionsButtonLayout: 'fixed',
  annotation: undefined,
  auxiliaryContentButtonProps: undefined,
  auxiliaryContentButtonText: undefined,
  auxiliaryContentChecked: undefined,
  auxiliaryContentLabel: undefined,
  auxiliaryContentOnChange: undefined,
  auxiliaryContentOnClick: undefined,
  auxiliaryContentType: undefined,
  cancelButtonProps: undefined,
  cancelText: undefined,
  confirmButtonProps: undefined,
  confirmText: undefined,
  loading: undefined,
  passwordButtonProps: undefined,
  passwordButtonText: undefined,
  passwordChecked: undefined,
  passwordCheckedLabel: undefined,
  passwordCheckedOnChange: undefined,
  passwordOnClick: undefined,
  showCancelButton: true,
});

const emit = defineEmits<{
  cancel: [event: MouseEvent];
  confirm: [event: MouseEvent];
}>();

defineSlots<{
  /** Extra content, rendered after the action buttons. */
  default?: () => unknown;
}>();

/**
 * React spreads the button props and then writes `onClick` after them, so the
 * later one wins. A `v-bind` object does the same; two separate bindings would
 * instead *chain* the handlers, running both.
 */
type ButtonBindings = ButtonProps & {
  class?: string;
  onClick?: (event: MouseEvent) => void;
};

const cancelButtonDisabled = computed(
  (): boolean | undefined => props.cancelButtonProps?.disabled ?? props.loading,
);

const isActionsButtonFillLayout = computed(
  (): boolean =>
    props.actionsButtonLayout === 'fill' && !props.auxiliaryContentType,
);

const hostClasses = computed((): string =>
  clsx(classes.modalFooter, {
    [`${classes.modalFooter}--password-mode`]:
      props.auxiliaryContentType === 'password',
    [`${classes.modalFooter}--with-auxiliary-content`]:
      !!props.auxiliaryContentType && props.auxiliaryContentType !== 'password',
  }),
);

const actionsButtonContainerClasses = computed((): string =>
  clsx(classes.modalFooterActionsButtonContainer, {
    [`${classes.modalFooterActionsButtonContainer}--fill-layout`]:
      isActionsButtonFillLayout.value,
  }),
);

const passwordButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-text-link',
    ...props.passwordButtonProps,
    onClick: props.passwordOnClick,
  }),
);

const auxiliaryContentButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-text-link',
    ...props.auxiliaryContentButtonProps,
    onClick: props.auxiliaryContentOnClick,
  }),
);

const cancelButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-secondary',
    ...props.cancelButtonProps,
    class: classes.modalFooterActionsButton,
    disabled: cancelButtonDisabled.value,
    onClick: (event: MouseEvent) => emit('cancel', event),
  }),
);

const confirmButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-primary',
    ...props.confirmButtonProps,
    class: classes.modalFooterActionsButton,
    loading: props.loading,
    onClick: (event: MouseEvent) => emit('confirm', event),
  }),
);

function onPasswordCheckedChange(event: Event): void {
  props.passwordCheckedOnChange?.((event.target as HTMLInputElement).checked);
}

function onAuxiliaryContentChange(event: Event): void {
  props.auxiliaryContentOnChange?.((event.target as HTMLInputElement).checked);
}

const passwordContainerClass = classes.modalFooterPasswordContainer;
const auxiliaryContentContainerClass =
  classes.modalFooterAuxiliaryContentContainer;
</script>

<template>
  <div :class="hostClasses">
    <div
      v-if="auxiliaryContentType === 'password'"
      :class="passwordContainerClass"
    >
      <MznCheckbox
        :checked="passwordChecked"
        :label="passwordCheckedLabel"
        @change="onPasswordCheckedChange"
      />
      <MznButton v-bind="passwordButtonBindings">
        <component :is="() => passwordButtonText" />
      </MznButton>
    </div>
    <div
      v-if="auxiliaryContentType && auxiliaryContentType !== 'password'"
      :class="auxiliaryContentContainerClass"
    >
      <MznTypography
        v-if="auxiliaryContentType === 'annotation'"
        color="text-neutral"
        variant="caption"
      >
        <component :is="() => annotation" />
      </MznTypography>
      <MznButton
        v-if="auxiliaryContentType === 'button'"
        v-bind="auxiliaryContentButtonBindings"
      >
        <component :is="() => auxiliaryContentButtonText" />
      </MznButton>
      <MznCheckbox
        v-if="auxiliaryContentType === 'checkbox'"
        :checked="auxiliaryContentChecked"
        :label="auxiliaryContentLabel"
        @change="onAuxiliaryContentChange"
      />
      <MznToggle
        v-if="auxiliaryContentType === 'toggle'"
        :checked="auxiliaryContentChecked"
        :label="auxiliaryContentLabel"
        @change="onAuxiliaryContentChange"
      />
    </div>
    <MznButtonGroup :class="actionsButtonContainerClasses">
      <MznButton v-if="showCancelButton" v-bind="cancelButtonBindings">
        <component :is="() => cancelText" />
      </MznButton>
      <MznButton v-bind="confirmButtonBindings">
        <component :is="() => confirmText" />
      </MznButton>
    </MznButtonGroup>
    <slot />
  </div>
</template>

// packages/ng/modal/modal-footer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import { MznButton, MznButtonGroup } from '@mezzanine-ui/ng/button';
import { MznCheckbox } from '@mezzanine-ui/ng/checkbox';
import { MznToggle } from '@mezzanine-ui/ng/toggle';
import { ButtonVariant } from '@mezzanine-ui/core/button';
import { MZN_MODAL_CONTEXT, ModalContextValue } from './modal-context';

/**
 * Modal 底部操作列元件。
 *
 * 搭配 `MznModal` 使用，自動從父 Modal 的 context 取得 `loading` 狀態。
 * 支援確認/取消按鈕、annotation、checkbox/toggle/button/password 輔助內容。
 *
 * @example
 * ```html
 * import { MznModalFooter } from '@mezzanine-ui/ng/modal';
 *
 * <mzn-modal-footer
 *   confirmText="確認"
 *   cancelText="取消"
 *   (confirmed)="onConfirm()"
 *   (cancelled)="onCancel()"
 * />
 * ```
 *
 * @see MznModal
 */
@Component({
  selector: 'mzn-modal-footer',
  standalone: true,
  imports: [FormsModule, MznButton, MznButtonGroup, MznCheckbox, MznToggle],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
  },
  template: `
    @if (auxiliaryContentType() === 'password') {
      <div [class]="passwordContainerClass">
        <div
          mznCheckbox
          [checked]="passwordChecked()"
          [label]="passwordCheckedLabel()"
          (ngModelChange)="passwordCheckedChanged.emit($event)"
          [ngModel]="passwordChecked()"
        ></div>
        <button
          mznButton
          variant="base-text-link"
          (click)="passwordClicked.emit()"
          >{{ passwordButtonText() }}</button
        >
      </div>
    }

    @if (auxiliaryContentType() && auxiliaryContentType() !== 'password') {
      <div [class]="auxiliaryContentContainerClass">
        @if (auxiliaryContentType() === 'annotation') {
          <span class="mzn-typography--caption mzn-typography--text-neutral">{{
            annotation()
          }}</span>
        }
        @if (auxiliaryContentType() === 'button') {
          <button
            mznButton
            variant="base-text-link"
            (click)="auxiliaryContentClicked.emit()"
            >{{ auxiliaryContentButtonText() }}</button
          >
        }
        @if (auxiliaryContentType() === 'checkbox') {
          <div
            mznCheckbox
            [checked]="auxiliaryContentChecked()"
            [label]="auxiliaryContentLabel()"
            (ngModelChange)="auxiliaryContentChanged.emit($event)"
            [ngModel]="auxiliaryContentChecked()"
          ></div>
        }
        @if (auxiliaryContentType() === 'toggle') {
          <mzn-toggle
            [checked]="auxiliaryContentChecked()"
            [label]="auxiliaryContentLabel()"
            (ngModelChange)="auxiliaryContentChanged.emit($event)"
            [ngModel]="auxiliaryContentChecked()"
          />
        }
      </div>
    }

    <mzn-button-group [class]="actionsButtonContainerClasses()">
      @if (showCancelButton()) {
        <button
          mznButton
          variant="base-secondary"
          [disabled]="resolvedLoading()"
          [class]="actionsButtonClass"
          (click)="cancelled.emit()"
          >{{ cancelText() }}</button
        >
      }
      <button
        mznButton
        [variant]="confirmButtonVariant()"
        [loading]="resolvedLoading()"
        [class]="actionsButtonClass"
        (click)="confirmed.emit()"
        >{{ confirmText() }}</button
      >
    </mzn-button-group>

    <ng-content />
  `,
})
export class MznModalFooter {
  private readonly modalContext = inject<ModalContextValue>(MZN_MODAL_CONTEXT, {
    optional: true,
  });

  /** 操作按鈕排版方式。 */
  readonly actionsButtonLayout = input<'fill' | 'fixed'>('fixed');

  /** 顯示在 footer 左側的 annotation 文字。僅在 auxiliaryContentType 為 'annotation' 時生效。 */
  readonly annotation = input<string>();

  /** 輔助內容按鈕文字。僅在 auxiliaryContentType 為 'button' 時生效。 */
  readonly auxiliaryContentButtonText = input<string>();

  /** 輔助內容 checkbox/toggle 是否勾選。 */
  readonly auxiliaryContentChecked = input(false);

  /** 輔助內容 checkbox/toggle 標籤文字。 */
  readonly auxiliaryContentLabel = input<string>();

  /** 輔助內容類型。 */
  readonly auxiliaryContentType = input<
    'annotation' | 'button' | 'checkbox' | 'password' | 'toggle'
  >();

  /** 取消按鈕文字。 */
  readonly cancelText = input('取消');

  /** 確認按鈕的 variant。 @default 'base-primary' */
  readonly confirmButtonVariant = input<ButtonVariant>('base-primary');

  /** 確認按鈕文字。 */
  readonly confirmText = input('確認');

  /** password 模式的按鈕文字（如「Forgot password?」）。 */
  readonly passwordButtonText = input<string>();

  /** password 模式的 checkbox 是否勾選（如「Remember me」）。 */
  readonly passwordChecked = input(false);

  /** password 模式的 checkbox 標籤文字。 */
  readonly passwordCheckedLabel = input<string>();

  /** 是否顯示取消按鈕。 */
  readonly showCancelButton = input(true);

  /** 輔助內容 checkbox/toggle 變更事件。 */
  readonly auxiliaryContentChanged = output<boolean>();

  /** 輔助內容按鈕點擊事件。 */
  readonly auxiliaryContentClicked = output<void>();

  /** 取消事件。 */
  readonly cancelled = output<void>();

  /** 確認事件。 */
  readonly confirmed = output<void>();

  /** password 模式的按鈕點擊事件。 */
  readonly passwordClicked = output<void>();

  /** password 模式的 checkbox 變更事件。 */
  readonly passwordCheckedChanged = output<boolean>();

  /** 從父 Modal context 取得 loading 狀態。 */
  readonly resolvedLoading = computed(
    (): boolean => this.modalContext?.loading() ?? false,
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.modalFooter, {
      [`${classes.modalFooter}--password-mode`]:
        this.auxiliaryContentType() === 'password',
      [`${classes.modalFooter}--with-auxiliary-content`]:
        !!this.auxiliaryContentType() &&
        this.auxiliaryContentType() !== 'password',
    }),
  );

  protected readonly actionsButtonContainerClasses = computed((): string =>
    clsx(classes.modalFooterActionsButtonContainer, {
      [`${classes.modalFooterActionsButtonContainer}--fill-layout`]:
        this.actionsButtonLayout() === 'fill' && !this.auxiliaryContentType(),
    }),
  );

  protected readonly auxiliaryContentContainerClass =
    classes.modalFooterAuxiliaryContentContainer;
  protected readonly actionsButtonClass = classes.modalFooterActionsButton;
  protected readonly passwordContainerClass =
    classes.modalFooterPasswordContainer;
}
