// packages/vue/modal/modal-header.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  modalClasses as classes,
  modalStatusTypeIcons,
} from '@mezzanine-ui/core/modal';
import type { ModalStatusType } from '@mezzanine-ui/core/modal';
import type { IconColor } from '@mezzanine-ui/core/icon';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznTypography from '../typography/typography.vue';
import { useModalControl } from './modal-control';
import type { ModalHeaderProps } from './modal-header.types';

/**
 * Modal 的標題列，顯示標題、輔助說明與狀態圖示。
 *
 * 狀態圖示取自 Modal 提供的 `modalStatusType`，圖示與顏色一一對應；
 * `statusTypeIconLayout` 決定圖示在標題左邊還是上方，`titleAlign` 與
 * `supportingTextAlign` 決定文字對齊。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznModalHeader } from '@mezzanine-ui/vue/modal';
 * <\/script>
 *
 * <template>
 *   <MznModalHeader show-status-type-icon title="確認刪除" />
 *   <MznModalHeader
 *     supporting-text="這個動作無法復原"
 *     title="確認刪除"
 *     title-align="center"
 *   />
 * </template>
 * ```
 *
 * @see MznModal 以 showModalHeader 渲染這個標題列
 */
const props = withDefaults(defineProps<ModalHeaderProps>(), {
  showStatusTypeIcon: false,
  statusTypeIconLayout: 'vertical',
  supportingText: undefined,
  supportingTextAlign: 'left',
  titleAlign: 'left',
});

const modalControl = useModalControl();

const iconColor = (type: ModalStatusType): IconColor => {
  switch (type) {
    case 'success':
      return 'success-strong';
    case 'warning':
      return 'warning';
    case 'error':
      return 'error-solid';
    case 'info':
      return 'info-strong';
    case 'email':
      return 'info-strong';
    case 'delete':
      return 'error-solid';
    default:
      return 'neutral';
  }
};

const statusTypeIcon = computed(
  (): IconDefinition =>
    modalStatusTypeIcons[modalControl.value.modalStatusType],
);

const statusTypeIconColor = computed(
  (): IconColor => iconColor(modalControl.value.modalStatusType),
);

const hostClasses = computed((): string =>
  clsx(classes.modalHeader, {
    [`${classes.modalHeader}--horizontal`]:
      props.statusTypeIconLayout === 'horizontal',
    [`${classes.modalHeader}--vertical`]:
      props.statusTypeIconLayout === 'vertical',
    [`${classes.modalHeader}--title-align-left`]: props.titleAlign === 'left',
    [`${classes.modalHeader}--title-align-center`]:
      props.titleAlign === 'center',
    [`${classes.modalHeader}--show-modal-status-type-icon`]:
      props.showStatusTypeIcon,
  }),
);

const supportingTextClasses = computed((): string =>
  clsx(classes.modalHeaderSupportingText, {
    [`${classes.modalHeaderSupportingText}--align-left`]:
      props.supportingTextAlign === 'left',
    [`${classes.modalHeaderSupportingText}--align-center`]:
      props.supportingTextAlign === 'center',
  }),
);

const statusTypeIconClass = classes.modalHeaderStatusTypeIcon;
const titleAndSupportingTextContainerClass =
  classes.modalHeaderTitleAndSupportingTextContainer;
const titleClass = classes.modalHeaderTitle;
</script>

<template>
  <div :class="hostClasses">
    <div v-if="showStatusTypeIcon" :class="statusTypeIconClass">
      <MznIcon :color="statusTypeIconColor" :icon="statusTypeIcon" :size="20" />
    </div>
    <div :class="titleAndSupportingTextContainerClass">
      <MznTypography
        :class="titleClass"
        color="text-neutral-solid"
        :title="title"
        variant="h2"
      >
        {{ title }}
      </MznTypography>
      <MznTypography
        :class="supportingTextClasses"
        color="text-neutral-strong"
        variant="body"
      >
        {{ supportingText }}
      </MznTypography>
    </div>
  </div>
</template>

// packages/ng/modal/modal-header.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import {
  modalClasses as classes,
  ModalStatusType,
  modalStatusTypeIcons,
} from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import { IconColor } from '@mezzanine-ui/core/icon';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import { MZN_MODAL_CONTEXT, ModalContextValue } from './modal-context';

/**
 * Modal 標題列元件。
 *
 * 搭配 `MznModal` 使用，自動從父 Modal 的 context 取得 `modalStatusType`
 * 以決定狀態圖示的顏色與種類。
 *
 * @example
 * ```html
 * import { MznModalHeader } from '@mezzanine-ui/ng/modal';
 *
 * <div mznModalHeader
 *   title="確認刪除"
 *   supportingText="此操作無法復原"
 *   [showStatusTypeIcon]="true"
 * ></div>
 * ```
 *
 * @see MznModal
 */
@Component({
  selector: '[mznModalHeader]',
  standalone: true,
  imports: [MznIcon, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.title]': 'null',
    '[attr.showStatusTypeIcon]': 'null',
    '[attr.statusTypeIconLayout]': 'null',
    '[attr.supportingText]': 'null',
    '[attr.supportingTextAlign]': 'null',
    '[attr.titleAlign]': 'null',
  },
  template: `
    @if (showStatusTypeIcon()) {
      <div [class]="statusTypeIconClass">
        <i
          mznIcon
          [icon]="statusIcon()"
          [color]="statusIconColor()"
          [size]="20"
        ></i>
      </div>
    }
    <div [class]="titleContainerClass">
      <h2
        mznTypography
        variant="h2"
        color="text-neutral-solid"
        [class]="titleClasses()"
        [title]="title()"
        >{{ title() }}</h2
      >
      @if (supportingText()) {
        <p
          mznTypography
          variant="body"
          color="text-neutral-strong"
          [class]="supportingTextClasses()"
          >{{ supportingText() }}</p
        >
      }
    </div>
  `,
})
export class MznModalHeader {
  private readonly modalContext = inject<ModalContextValue>(MZN_MODAL_CONTEXT, {
    optional: true,
  });

  /** 標題文字。 */
  readonly title = input.required<string>();

  /** 是否顯示狀態類型圖示。 */
  readonly showStatusTypeIcon = input(false);

  /** 圖示排版方向。 */
  readonly statusTypeIconLayout = input<'horizontal' | 'vertical'>('vertical');

  /** 輔助說明文字。 */
  readonly supportingText = input<string>();

  /** 輔助說明文字對齊。 */
  readonly supportingTextAlign = input<'center' | 'left'>('left');

  /** 標題文字對齊。 */
  readonly titleAlign = input<'center' | 'left'>('left');

  private readonly resolvedStatusType = computed(
    (): ModalStatusType => this.modalContext?.modalStatusType() ?? 'info',
  );

  protected readonly statusIcon = computed(
    () => modalStatusTypeIcons[this.resolvedStatusType()],
  );

  protected readonly statusIconColor = computed((): IconColor => {
    const t = this.resolvedStatusType();

    switch (t) {
      case 'success':
        return 'success-strong';
      case 'warning':
        return 'warning';
      case 'error':
      case 'delete':
        return 'error-solid';
      case 'info':
      case 'email':
      default:
        return 'info-strong';
    }
  });

  protected readonly hostClasses = computed((): string =>
    clsx(classes.modalHeader, {
      [`${classes.modalHeader}--horizontal`]:
        this.statusTypeIconLayout() === 'horizontal',
      [`${classes.modalHeader}--vertical`]:
        this.statusTypeIconLayout() === 'vertical',
      [`${classes.modalHeader}--title-align-left`]:
        this.titleAlign() === 'left',
      [`${classes.modalHeader}--title-align-center`]:
        this.titleAlign() === 'center',
      [`${classes.modalHeader}--show-modal-status-type-icon`]:
        this.showStatusTypeIcon(),
    }),
  );

  protected readonly titleClasses = computed((): string =>
    clsx(classes.modalHeaderTitle),
  );

  protected readonly supportingTextClasses = computed((): string =>
    clsx(classes.modalHeaderSupportingText, {
      [`${classes.modalHeaderSupportingText}--align-left`]:
        this.supportingTextAlign() === 'left',
      [`${classes.modalHeaderSupportingText}--align-center`]:
        this.supportingTextAlign() === 'center',
    }),
  );

  protected readonly statusTypeIconClass = classes.modalHeaderStatusTypeIcon;
  protected readonly titleContainerClass =
    classes.modalHeaderTitleAndSupportingTextContainer;
}
