// packages/ng/calendar/calendar-cell.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import {
  CalendarMode,
  calendarClasses as classes,
} from '@mezzanine-ui/core/calendar';
import clsx from 'clsx';

/**
 * 日曆單元格元件，呈現單一日期/月份/年份的格子。
 *
 * @example
 * ```html
 * <mzn-calendar-cell [active]="true" [today]="true" mode="day">
 *   <button>15</button>
 * </mzn-calendar-cell>
 * ```
 */
@Component({
  selector: 'mzn-calendar-cell',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
  },
  template: `<span [class]="innerClass"><ng-content /></span>`,
})
export class MznCalendarCell {
  /** 是否為選取中狀態。 */
  readonly active = input(false);

  /** 是否為禁用狀態。 */
  readonly disabled = input(false);

  /** 日曆模式。 */
  readonly mode = input<CalendarMode>('day');

  /** 是否為今天。 */
  readonly today = input(false);

  /** 是否為區間起始。 */
  readonly isRangeStart = input(false);

  /** 是否為區間結束。 */
  readonly isRangeEnd = input(false);

  /** 是否為週末。 */
  readonly isWeekend = input(false);

  /** 是否帶有註解。 */
  readonly withAnnotation = input(false);

  /** 元素 role。 */
  readonly role = input<string | undefined>(undefined);

  protected readonly innerClass = classes.cellInner;

  protected hostClasses(): string {
    return clsx(classes.cell, classes.cellMode(this.mode()), {
      [classes.cellToday]: this.today(),
      [classes.cellActive]: this.active(),
      [classes.cellDisabled]: this.disabled(),
      [classes.cellWithAnnotation]: this.withAnnotation(),
      [classes.cellWeekend]: this.isWeekend(),
      [classes.cellRangeStart]: this.isRangeStart(),
      [classes.cellRangeEnd]: this.isRangeEnd(),
    });
  }
}

// packages/vue/calendar/calendar-cell.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import clsx from 'clsx';
import type { CalendarCellProps } from './calendar-cell.types';

/**
 * 日曆格子，日／週／月／季／半年／年各面板共用的最小單位。
 *
 * 只負責格子本身的狀態樣式（今天、選取、停用、區間起訖、週末、含註記），
 * 內容一律包在 `.mzn-calendar-cell__inner` 裡。可用來組裝自訂日曆。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarCell } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarCell active today>15</MznCalendarCell>
 * </template>
 * ```
 *
 * @see MznCalendarDays 使用格子排出月曆
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarCellProps>(), {
  mode: 'day',
  role: undefined,
});

defineSlots<{
  /** The cell's content. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const hostClasses = computed((): string =>
  clsx(
    classes.cell,
    classes.cellMode(props.mode),
    {
      [classes.cellToday]: props.today,
      [classes.cellActive]: props.active,
      [classes.cellDisabled]: props.disabled,
      [classes.cellWithAnnotation]: props.withAnnotation,
      [classes.cellWeekend]: props.isWeekend,
      [classes.cellRangeStart]: props.isRangeStart,
      [classes.cellRangeEnd]: props.isRangeEnd,
    },
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const innerClass = classes.cellInner;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses" :role="role">
    <span :class="innerClass"><slot /></span>
  </div>
</template>
