// packages/react/src/Calendar/CalendarCell.tsx
import {
  CalendarMode,
  calendarClasses as classes,
} from '@mezzanine-ui/core/calendar';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

export interface CalendarCellProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * Apply active styles if true.
   */
  active?: boolean;
  /**
   * Apply disabled styles if true.
   */
  disabled?: boolean;
  /**
   * Calendar mode for applying mode specific styles.
   * @default 'day'
   */
  mode?: CalendarMode;
  /**
   * Apply today styles if true.
   */
  today?: boolean;
  /**
   * The role attribute for accessibility
   */
  role?: string;
  /**
   * Apply range start styles if true.
   */
  isRangeStart?: boolean;
  /**
   * Apply range end styles if true.
   */
  isRangeEnd?: boolean;
  /**
   * Apply weekend styles if true.
   */
  isWeekend?: boolean;
  /**
   * Apply annotation styles if true.
   */
  withAnnotation?: boolean;
}

/**
 * The react component for `mezzanine` calendar cell.
 * You may use it to compose your own calendar.
 */
function CalendarCell(props: CalendarCellProps) {
  const {
    active,
    children,
    className,
    disabled,
    mode = 'day',
    today,
    role,
    isRangeStart,
    isRangeEnd,
    isWeekend,
    withAnnotation,
    ...restCalendarCellProps
  } = props;

  return (
    <div
      role={role}
      className={cx(
        classes.cell,
        classes.cellMode(mode),
        {
          [classes.cellToday]: today,
          [classes.cellActive]: active,
          [classes.cellDisabled]: disabled,
          [classes.cellWithAnnotation]: withAnnotation,
          [classes.cellWeekend]: isWeekend,
          [classes.cellRangeStart]: isRangeStart,
          [classes.cellRangeEnd]: isRangeEnd,
        },
        className,
      )}
      {...restCalendarCellProps}
    >
      <span className={classes.cellInner}>{children}</span>
    </div>
  );
}

export default CalendarCell;

// packages/vue/calendar/calendar-cell.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import clsx from 'clsx';
import type { CalendarCellProps } from './calendar-cell.types';

/**
 * 日曆格子，日／週／月／季／半年／年各面板共用的最小單位。
 *
 * 只負責格子本身的狀態樣式（今天、選取、停用、區間起訖、週末、含註記），
 * 內容一律包在 `.mzn-calendar-cell__inner` 裡。可用來組裝自訂日曆。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarCell } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarCell active today>15</MznCalendarCell>
 * </template>
 * ```
 *
 * @see MznCalendarDays 使用格子排出月曆
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarCellProps>(), {
  mode: 'day',
  role: undefined,
});

defineSlots<{
  /** The cell's content. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const hostClasses = computed((): string =>
  clsx(
    classes.cell,
    classes.cellMode(props.mode),
    {
      [classes.cellToday]: props.today,
      [classes.cellActive]: props.active,
      [classes.cellDisabled]: props.disabled,
      [classes.cellWithAnnotation]: props.withAnnotation,
      [classes.cellWeekend]: props.isWeekend,
      [classes.cellRangeStart]: props.isRangeStart,
      [classes.cellRangeEnd]: props.isRangeEnd,
    },
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const innerClass = classes.cellInner;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses" :role="role">
    <span :class="innerClass"><slot /></span>
  </div>
</template>
