// packages/react/src/Calendar/CalendarHalfYears.tsx
'use client';

import {
  calendarClasses as classes,
  DateType,
  calendarHalfYears,
  calendarHalfYearYearsCount,
  getYearRange,
} from '@mezzanine-ui/core/calendar';
import { useMemo } from 'react';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { useCalendarContext } from './CalendarContext';
import CalendarCell from './CalendarCell';

export interface CalendarHalfYearsProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'div'>,
    'onClick' | 'children'
  > {
  /**
   * Provide if you have a custom disabling logic.
   * The method takes the date object as its parameter.
   */
  isHalfYearDisabled?: (date: DateType) => boolean;
  /**
   * Provide if you have a custom logic for checking if the half-year is in range.
   * The method takes the date object as its parameter.
   */
  isHalfYearInRange?: (date: DateType) => boolean;
  /**
   * Click handler for the button of each half-year.
   * The method takes the date object as its parameter.
   */
  onClick?: (target: DateType) => void;
  /**
   * Mouse enter handler for the button of each half-year.
   * The method takes the date object as its parameter.
   */
  onHalfYearHover?: (target: DateType) => void;
  /**
   * The reference date for getting the half-years range and computing the date object.
   */
  referenceDate: DateType;
  /**
   * The half-year will be marked as active if it matches the same half-year of any value in the array.
   */
  value?: DateType[];
}

/**
 * The react component for `mezzanine` calendar half-years.
 * This component displays half-years for 5 years.
 * You may use it to compose your own calendar.
 */
function CalendarHalfYears(props: CalendarHalfYearsProps) {
  const {
    getNow,
    getYear,
    getCurrentHalfYearFirstDate,
    isHalfYearIncluded,
    setYear,
    setMonth,
  } = useCalendarContext();

  const {
    className,
    isHalfYearDisabled,
    isHalfYearInRange,
    onClick: onClickProp,
    onHalfYearHover,
    referenceDate,
    value,
    ...rest
  } = props;

  const currentYear = getYear(referenceDate);

  const [start] = useMemo(
    () => getYearRange(currentYear, calendarHalfYearYearsCount),
    [currentYear],
  );

  const years = useMemo(() => {
    return Array.from(
      { length: calendarHalfYearYearsCount },
      (_, i) => start + i,
    );
  }, [start]);

  return (
    <div className={cx(classes.board, className)} {...rest}>
      {years.map((year, yearIndex) => {
        return (
          <div
            key={year}
            className={cx(classes.row, {
              [classes.rowWithBorder]: yearIndex > 0,
            })}
          >
            <CalendarCell disabled mode="half-year">
              {year}
            </CalendarCell>
            {calendarHalfYears.map((halfYear) => {
              const halfYearStartMonth = (halfYear - 1) * 6;
              const halfYearDate = setMonth(
                setYear(getCurrentHalfYearFirstDate(referenceDate), year),
                halfYearStartMonth,
              );

              const disabled =
                isHalfYearDisabled && isHalfYearDisabled(halfYearDate);
              const inRange =
                !disabled &&
                isHalfYearInRange &&
                isHalfYearInRange(halfYearDate);
              const active =
                !disabled && value && isHalfYearIncluded(halfYearDate, value);
              const isRangeStart =
                value && value.length > 0
                  ? isHalfYearIncluded(halfYearDate, [value[0]])
                  : false;
              const isRangeEnd =
                value && value.length > 0
                  ? isHalfYearIncluded(halfYearDate, [value[value.length - 1]])
                  : false;

              const onClick = () => {
                if (disabled) return;
                onClickProp?.(halfYearDate);
              };

              const onMouseEnter = () => {
                if (disabled) return;
                onHalfYearHover?.(halfYearDate);
              };

              // Accessible half-year label for screen readers
              const halfYearMonths =
                halfYear === 1 ? 'January to June' : 'July to December';

              const ariaLabel = [
                `Half ${halfYear}, ${year}`,
                halfYearMonths,
                active && 'Selected',
                disabled && 'Not available',
              ]
                .filter(Boolean)
                .join(', ');

              return (
                <CalendarCell
                  key={halfYear}
                  mode="half-year"
                  today={isHalfYearIncluded(halfYearDate, [getNow()])}
                  active={active}
                  isRangeStart={isRangeStart}
                  isRangeEnd={isRangeEnd}
                >
                  <button
                    key={halfYear}
                    type="button"
                    disabled={disabled}
                    aria-disabled={disabled}
                    aria-label={ariaLabel}
                    aria-pressed={active}
                    className={cx(classes.button, {
                      [classes.buttonDisabled]: disabled,
                      [classes.buttonInRange]: inRange,
                      [classes.buttonActive]: active,
                    })}
                    onClick={onClick}
                    onMouseEnter={onMouseEnter}
                  >
                    H{halfYear}
                  </button>
                </CalendarCell>
              );
            })}
          </div>
        );
      })}
    </div>
  );
}

export default CalendarHalfYears;

// packages/vue/calendar/calendar-half-years.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import {
  calendarClasses as classes,
  calendarHalfYears,
  calendarHalfYearYearsCount,
  getYearRange,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import clsx from 'clsx';
import MznCalendarCell from './calendar-cell.vue';
import { useCalendarContext } from './calendar-context';
import type { CalendarHalfYearsProps } from './calendar-half-years.types';

/**
 * 半年面板，每一列是一個年份、上下兩個半年。
 *
 * 一次顯示五年，範圍由 `referenceDate` 所在的區間決定；被停用的半年不會送出事件。
 * 可用來組裝自訂日曆。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarHalfYears } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarHalfYears reference-date="2026-01-01" @click="onChange" />
 * </template>
 * ```
 *
 * @see MznCalendar 依 `mode` 切換各面板
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarHalfYearsProps>(), {
  isHalfYearDisabled: undefined,
  isHalfYearInRange: undefined,
  value: undefined,
});

const emit = defineEmits<{
  click: [target: DateType];
  halfYearHover: [target: DateType];
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const start = computed(
  (): number =>
    getYearRange(
      calendar.value.getYear(props.referenceDate),
      calendarHalfYearYearsCount,
    )[0],
);

const rows = computed(() =>
  Array.from({ length: calendarHalfYearYearsCount }, (_, i) => {
    const year = start.value + i;
    const {
      getNow,
      getCurrentHalfYearFirstDate,
      isHalfYearIncluded,
      setYear,
      setMonth,
    } = calendar.value;

    return {
      halfYears: calendarHalfYears.map((halfYear) => {
        const halfYearStartMonth = (halfYear - 1) * 6;
        const halfYearDate = setMonth(
          setYear(getCurrentHalfYearFirstDate(props.referenceDate), year),
          halfYearStartMonth,
        );

        const disabled =
          props.isHalfYearDisabled && props.isHalfYearDisabled(halfYearDate);
        const inRange =
          !disabled &&
          props.isHalfYearInRange &&
          props.isHalfYearInRange(halfYearDate);
        const active =
          !disabled &&
          props.value &&
          isHalfYearIncluded(halfYearDate, props.value);
        const isRangeStart =
          props.value && props.value.length > 0
            ? isHalfYearIncluded(halfYearDate, [props.value[0]])
            : false;
        const isRangeEnd =
          props.value && props.value.length > 0
            ? isHalfYearIncluded(halfYearDate, [
                props.value[props.value.length - 1],
              ])
            : false;

        // Accessible half-year label for screen readers
        const halfYearMonths =
          halfYear === 1 ? 'January to June' : 'July to December';

        const ariaLabel = [
          `Half ${halfYear}, ${year}`,
          halfYearMonths,
          active && 'Selected',
          disabled && 'Not available',
        ]
          .filter(Boolean)
          .join(', ');

        return {
          active,
          ariaLabel,
          buttonClasses: clsx(classes.button, {
            [classes.buttonDisabled]: disabled,
            [classes.buttonInRange]: inRange,
            [classes.buttonActive]: active,
          }),
          disabled,
          halfYear,
          halfYearDate,
          isRangeEnd,
          isRangeStart,
          today: isHalfYearIncluded(halfYearDate, [getNow()]),
        };
      }),
      year,
    };
  }),
);

const hostClasses = computed((): string =>
  clsx(classes.board, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const rowClasses = (index: number): string =>
  clsx(classes.row, { [classes.rowWithBorder]: index > 0 });

function handleClick(disabled: boolean | undefined, target: DateType): void {
  if (disabled) return;

  emit('click', target);
}

function handleMouseEnter(
  disabled: boolean | undefined,
  target: DateType,
): void {
  if (disabled) return;

  emit('halfYearHover', target);
}
</script>

<template>
  <div :class="hostClasses" v-bind="forwardedAttrs">
    <div
      v-for="(row, rowIndex) in rows"
      :key="row.year"
      :class="rowClasses(rowIndex)"
    >
      <MznCalendarCell disabled mode="half-year">
        {{ row.year }}
      </MznCalendarCell>
      <MznCalendarCell
        v-for="halfYear in row.halfYears"
        :key="halfYear.halfYear"
        :active="halfYear.active"
        :is-range-end="halfYear.isRangeEnd"
        :is-range-start="halfYear.isRangeStart"
        mode="half-year"
        :today="halfYear.today"
      >
        <button
          :aria-disabled="halfYear.disabled"
          :aria-label="halfYear.ariaLabel"
          :aria-pressed="halfYear.active"
          :class="halfYear.buttonClasses"
          :disabled="halfYear.disabled"
          type="button"
          @click="handleClick(halfYear.disabled, halfYear.halfYearDate)"
          @mouseenter="
            handleMouseEnter(halfYear.disabled, halfYear.halfYearDate)
          "
        >
          H{{ halfYear.halfYear }}
        </button>
      </MznCalendarCell>
    </div>
  </div>
</template>
