// packages/ng/media-preview-modal/media-preview-modal.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { ChevronLeftIcon, ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznBackdrop } from '@mezzanine-ui/ng/backdrop';
import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznScale, MznFade } from '@mezzanine-ui/ng/transition';
import { EscapeKeyService } from '@mezzanine-ui/ng/services';
import { TopStackService } from '@mezzanine-ui/ng/services';
import { ScrollLockService } from '@mezzanine-ui/ng/services';

/**
 * MediaPreviewModal displays a gallery of images with navigation controls and circular browsing.
 *
 * Supports both controlled mode (`currentIndex` + `onNext`/`onPrev`) and uncontrolled mode (`defaultIndex`).
 * Automatically preloads adjacent images for better performance, and shows a pagination indicator when there are multiple items.
 *
 * @example
 * ```html
 * import { MznMediaPreviewModal } from '@mezzanine-ui/ng/media-preview-modal';
 *
 * <div mznMediaPreviewModal
 *   [open]="isOpen"
 *   [mediaItems]="['url1.jpg', 'url2.jpg', 'url3.jpg']"
 *   [defaultIndex]="0"
 *   [showPaginationIndicator]="true"
 *   (closed)="isOpen = false"
 *   (indexChange)="onIndexChange($event)"
 * ></div>
 * ```
 *
 * Controlled mode:
 * ```html
 * <div mznMediaPreviewModal
 *   [open]="isOpen"
 *   [mediaItems]="images"
 *   [currentIndex]="currentIndex"
 *   (closed)="isOpen = false"
 *   (next)="onNext()"
 *   (prev)="onPrev()"
 * ></div>
 * ```
 */
@Component({
  selector: '[mznMediaPreviewModal]',
  standalone: true,
  imports: [MznBackdrop, MznClearActions, MznIcon, MznScale, MznFade],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.open]': 'null',
    '[attr.mediaItems]': 'null',
    '[attr.defaultIndex]': 'null',
    '[attr.currentIndex]': 'null',
    '[attr.disableNext]': 'null',
    '[attr.disablePrev]': 'null',
    '[attr.enableCircularNavigation]': 'null',
    '[attr.showPaginationIndicator]': 'null',
    '[attr.disableCloseOnBackdropClick]': 'null',
    '[attr.disableCloseOnEscapeKeyDown]': 'null',
    '[attr.disablePortal]': 'null',
  },
  template: `
    <div
      mznBackdrop
      [open]="open()"
      [disableCloseOnBackdropClick]="disableCloseOnBackdropClick()"
      [disablePortal]="disablePortal()"
      (closed)="onBackdropClose()"
    >
      <div mznScale [in]="open()">
        <div class="mzn-modal__content-wrapper">
          <div class="mzn-modal__media-preview-content">
            <div class="mzn-modal__media-preview-media-container">
              @for (idx of displayedIndices(); track idx) {
                @if (isStringItem(mediaItems()[idx])) {
                  <img
                    mznFade
                    [in]="idx === activeIndex()"
                    [duration]="fadeDuration"
                    [easing]="fadeEasing"
                    class="mzn-modal__media-preview-image"
                    [src]="asString(mediaItems()[idx])"
                    [alt]="'Media ' + (idx + 1)"
                  />
                }
              }
            </div>
          </div>
        </div>
      </div>
      @if (open()) {
        <button
          mznClearActions
          class="mzn-modal__media-preview-close-button"
          type="embedded"
          variant="contrast"
          ariaLabel="Close"
          (clicked)="closed.emit()"
        ></button>

        @if (hasMultipleItems()) {
          <button
            type="button"
            class="mzn-modal__media-preview-nav-button mzn-modal__media-preview-nav-button--prev"
            [attr.aria-disabled]="isPrevDisabled()"
            aria-label="Previous media"
            [disabled]="isPrevDisabled()"
            (click)="onPrev()"
          >
            <i
              mznIcon
              [icon]="chevronLeftIcon"
              [size]="16"
              color="fixed-light"
            ></i>
          </button>

          <button
            type="button"
            class="mzn-modal__media-preview-nav-button mzn-modal__media-preview-nav-button--next"
            [attr.aria-disabled]="isNextDisabled()"
            aria-label="Next media"
            [disabled]="isNextDisabled()"
            (click)="onNext()"
          >
            <i
              mznIcon
              [icon]="chevronRightIcon"
              [size]="16"
              color="fixed-light"
            ></i>
          </button>
        }

        @if (showPaginationIndicator() && hasMultipleItems()) {
          <div
            class="mzn-modal__media-preview-pagination-indicator"
            [attr.aria-label]="
              'Page ' + (resolvedIndex() + 1) + ' of ' + mediaItems().length
            "
          >
            {{ resolvedIndex() + 1 }}/{{ mediaItems().length }}
          </div>
        }
      }
    </div>
  `,
})
export class MznMediaPreviewModal {
  private readonly escapeKey = inject(EscapeKeyService);
  private readonly topStack = inject(TopStackService);
  private readonly scrollLock = inject(ScrollLockService);

  protected readonly chevronLeftIcon = ChevronLeftIcon;
  protected readonly chevronRightIcon = ChevronRightIcon;

  /** Fade duration / easing for image crossfade (mirrors React). */
  protected readonly fadeDuration = {
    enter: MOTION_DURATION.fast,
    exit: MOTION_DURATION.fast,
  } as const;
  protected readonly fadeEasing = {
    enter: MOTION_EASING.standard,
    exit: MOTION_EASING.standard,
  } as const;

  // ─── Inputs ───────────────────────────────────────────────────

  /** Whether the modal is open. @default false */
  readonly open = input(false);

  /** Array of media items (image URLs). */
  readonly mediaItems = input<string[]>([]);

  /** Default index when opened (uncontrolled mode). @default 0 */
  readonly defaultIndex = input(0);

  /** Current index (controlled mode). */
  readonly currentIndex = input<number>();

  /** Whether to disable the next button. @default false */
  readonly disableNext = input(false);

  /** Whether to disable the previous button. @default false */
  readonly disablePrev = input(false);

  /** Enable circular navigation (wrap around at boundaries). @default false */
  readonly enableCircularNavigation = input(false);

  /** Whether to show the pagination indicator. @default true */
  readonly showPaginationIndicator = input(true);

  /** Whether to disable closing on backdrop click. @default false */
  readonly disableCloseOnBackdropClick = input(false);

  /** Whether to disable closing on Escape key. @default false */
  readonly disableCloseOnEscapeKeyDown = input(false);

  /** Whether to disable portal rendering. @default false */
  readonly disablePortal = input(false);

  // ─── Outputs ─────────────────────────────────────────────────

  /** Emitted when the modal is closed. */
  readonly closed = output<void>();

  /** Emitted when the index changes (uncontrolled mode). */
  readonly indexChange = output<number>();

  /** Emitted when the next button is clicked (controlled mode). */
  readonly next = output<void>();

  /** Emitted when the previous button is clicked (controlled mode). */
  readonly prev = output<void>();

  // ─── Internal state ─────────────────────────────────────────────

  private readonly _internalIndex = signal(0);
  private readonly _displayedIndices = signal<number[]>([]);
  /** Currently visible image index (template consumes via `activeIndex()`). */
  protected readonly activeIndex = signal(0);

  // ─── Computed ──────────────────────────────────────────────────

  protected readonly isControlled = computed(
    (): boolean => this.currentIndex() !== undefined,
  );

  protected readonly resolvedIndex = computed((): number =>
    this.isControlled() ? (this.currentIndex() ?? 0) : this._internalIndex(),
  );

  protected readonly hasMultipleItems = computed(
    (): boolean => this.mediaItems().length > 1,
  );

  protected readonly isNextDisabled = computed((): boolean => {
    if (this.enableCircularNavigation()) return false;
    return (
      this.disableNext() || this.resolvedIndex() >= this.mediaItems().length - 1
    );
  });

  protected readonly isPrevDisabled = computed((): boolean => {
    if (this.enableCircularNavigation()) return false;
    return this.disablePrev() || this.resolvedIndex() <= 0;
  });

  protected readonly displayedIndices = this._displayedIndices;

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.mediaPreview),
  );

  // ─── Lifecycle ─────────────────────────────────────────────────

  constructor() {
    // Manage top stack and escape key
    effect((onCleanup) => {
      const isOpen = this.open();

      if (isOpen) {
        this.scrollLock.lock();

        const entry = this.topStack.register();

        const escapeCleanup = this.escapeKey.listen(() => {
          if (!this.disableCloseOnEscapeKeyDown() && entry.isTop()) {
            this.closed.emit();
          }
        });

        onCleanup(() => {
          escapeCleanup();
          entry.unregister();
          this.scrollLock.unlock();
        });
      }
    });

    // Reset internal index when modal opens
    effect(() => {
      const isOpen = this.open();
      const isCtrl = this.isControlled();

      if (isOpen && !isCtrl) {
        this._internalIndex.set(this.defaultIndex());
        this._displayedIndices.set([this.defaultIndex()]);
        this.activeIndex.set(this.defaultIndex());
      }
    });

    // Handle index changes
    effect((onCleanup) => {
      const idx = this.resolvedIndex();
      const active = this.activeIndex();

      if (idx !== active) {
        // Add new index to displayed indices
        this._displayedIndices.update((prev) =>
          prev.includes(idx) ? prev : [...prev, idx],
        );

        // Use RAF to trigger animation
        let rafId1 = 0;
        let rafId2 = 0;

        rafId1 = requestAnimationFrame(() => {
          rafId2 = requestAnimationFrame(() => {
            this.activeIndex.set(idx);
          });
        });

        // Cleanup old images after transition
        const cleanupTimer = setTimeout(() => {
          this._displayedIndices.set([idx]);
        }, MOTION_DURATION.fast + 100);

        onCleanup(() => {
          clearTimeout(cleanupTimer);
          cancelAnimationFrame(rafId1);
          cancelAnimationFrame(rafId2);
        });
      }
    });

    // Image preloading
    effect((onCleanup) => {
      const isOpen = this.open();
      const idx = this.resolvedIndex();
      const items = this.mediaItems();

      if (!isOpen || items.length === 0) return;

      const priorityIndices = [idx - 1, idx, idx + 1].filter(
        (i): i is number => i >= 0 && i < items.length,
      );

      // Preload priority images
      priorityIndices.forEach((i) => {
        const item = items[i];
        if (item !== undefined) {
          const img = new Image();
          img.src = item;
        }
      });

      // Preload remaining images after delay
      const timer = setTimeout(() => {
        items.forEach((item, i) => {
          if (item !== undefined && !priorityIndices.includes(i)) {
            const img = new Image();
            img.src = item;
          }
        });
      }, 500);

      onCleanup(() => clearTimeout(timer));
    });
  }

  // ─── Methods ──────────────────────────────────────────────────

  protected onBackdropClose(): void {
    if (!this.disableCloseOnBackdropClick()) {
      this.closed.emit();
    }
  }

  protected onNext(): void {
    if (this.isControlled()) {
      this.next.emit();
    } else {
      const items = this.mediaItems();
      const idx = this._internalIndex();
      const nextIdx = this.enableCircularNavigation()
        ? (idx + 1) % items.length
        : Math.min(idx + 1, items.length - 1);

      this._internalIndex.set(nextIdx);
      this.indexChange.emit(nextIdx);
    }
  }

  protected onPrev(): void {
    if (this.isControlled()) {
      this.prev.emit();
    } else {
      const items = this.mediaItems();
      const idx = this._internalIndex();
      const prevIdx = this.enableCircularNavigation()
        ? (idx - 1 + items.length) % items.length
        : Math.max(idx - 1, 0);

      this._internalIndex.set(prevIdx);
      this.indexChange.emit(prevIdx);
    }
  }

  protected isStringItem(item: string | undefined): boolean {
    return typeof item === 'string';
  }

  protected asString(item: string | undefined): string {
    return item ?? '';
  }
}

// packages/react/src/Modal/MediaPreviewModal.tsx
'use client';

import { forwardRef, useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeftIcon, ChevronRightIcon } from '@mezzanine-ui/icons';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import useModalContainer, { ModalContainerProps } from './useModalContainer';
import Icon from '../Icon';
import ClearActions from '../ClearActions';
import { Fade } from '../Transition';

export interface MediaPreviewModalProps
  extends Omit<ModalContainerProps, 'children'>,
    NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * The current index of the media being displayed (controlled mode).
   * If provided along with onNext/onPrev, the component operates in controlled mode.
   */
  currentIndex?: number;
  /**
   * The default index when the modal opens (uncontrolled mode).
   * @default 0
   */
  defaultIndex?: number;
  /**
   * Whether to disable the next navigation button.
   * @default false
   */
  disableNext?: boolean;
  /**
   * Whether to disable the previous navigation button.
   * @default false
   */
  disablePrev?: boolean;
  /**
   * Enable circular navigation (wrap around at boundaries).
   * When enabled, navigating past the last item goes to the first,
   * and navigating before the first item goes to the last.
   * @default false
   */
  enableCircularNavigation?: boolean;
  /**
   * Array of media items to display.
   * Each item should be a valid image URL or React node.
   */
  mediaItems: (string | React.ReactNode)[];
  /**
   * Callback fired when the index changes (uncontrolled mode).
   */
  onIndexChange?: (index: number) => void;
  /**
   * Callback fired when the next navigation button is clicked (controlled mode).
   * If provided, the component operates in controlled mode.
   */
  onNext?: () => void;
  /**
   * Callback fired when the previous navigation button is clicked (controlled mode).
   * If provided, the component operates in controlled mode.
   */
  onPrev?: () => void;
  /**
   * Whether to show the pagination indicator.
   * @default true
   */
  showPaginationIndicator?: boolean;
}

/**
 * The react component for `mezzanine` media preview modal.
 * Displays media items with navigation controls and a close button.
 */
const MediaPreviewModal = forwardRef<HTMLDivElement, MediaPreviewModalProps>(
  function MediaPreviewModal(props, ref) {
    const {
      className,
      container,
      currentIndex: controlledIndex,
      defaultIndex = 0,
      disableCloseOnBackdropClick = false,
      disableCloseOnEscapeKeyDown = false,
      disableNext = false,
      disablePortal = false,
      disablePrev = false,
      enableCircularNavigation = false,
      mediaItems,
      onBackdropClick,
      onClose,
      onIndexChange,
      onNext,
      onPrev,
      open,
      showPaginationIndicator = true,
      ...rest
    } = props;

    const { Container: ModalContainer } = useModalContainer();

    // Determine if component is in controlled mode
    const isControlled = controlledIndex !== undefined;

    // Internal state for uncontrolled mode
    const [internalIndex, setInternalIndex] = useState(defaultIndex);

    // Use controlled index if provided, otherwise use internal state
    const currentIndex = isControlled ? controlledIndex : internalIndex;

    // Reset internal index when modal opens in uncontrolled mode
    useEffect(() => {
      if (open && !isControlled) {
        setInternalIndex(defaultIndex);
      }
    }, [open, isControlled, defaultIndex]);

    // Built-in navigation handlers for uncontrolled mode
    const handleNext = () => {
      if (onNext) {
        // Controlled mode: use provided callback
        onNext();
      } else {
        // Uncontrolled mode: update internal state
        let nextIndex: number;
        if (enableCircularNavigation) {
          nextIndex = (currentIndex + 1) % mediaItems.length;
        } else {
          nextIndex = Math.min(currentIndex + 1, mediaItems.length - 1);
        }
        setInternalIndex(nextIndex);
        onIndexChange?.(nextIndex);
      }
    };

    const handlePrev = () => {
      if (onPrev) {
        // Controlled mode: use provided callback
        onPrev();
      } else {
        // Uncontrolled mode: update internal state
        let prevIndex: number;
        if (enableCircularNavigation) {
          prevIndex =
            (currentIndex - 1 + mediaItems.length) % mediaItems.length;
        } else {
          prevIndex = Math.max(currentIndex - 1, 0);
        }
        setInternalIndex(prevIndex);
        onIndexChange?.(prevIndex);
      }
    };

    // Auto-calculate disable states for uncontrolled mode
    const isNextDisabled = enableCircularNavigation
      ? false
      : disableNext || currentIndex >= mediaItems.length - 1;
    const isPrevDisabled = enableCircularNavigation
      ? false
      : disablePrev || currentIndex <= 0;

    const [displayedIndices, setDisplayedIndices] = useState<number[]>([
      currentIndex,
    ]);
    const [activeIndex, setActiveIndex] = useState<number>(currentIndex);
    const preloadedUrls = useRef<Set<string>>(new Set());

    // Helper function to preload a single image
    const preloadImage = (url: string) => {
      if (preloadedUrls.current.has(url)) return;

      const img = new Image();
      img.src = url;
      preloadedUrls.current.add(url);
    };

    // Preload images: prioritize current and adjacent, then load others
    useEffect(() => {
      if (!open) return;

      // Priority 1: Current and adjacent images
      const priorityIndices = [
        currentIndex - 1,
        currentIndex,
        currentIndex + 1,
      ].filter((idx) => idx >= 0 && idx < mediaItems.length);

      priorityIndices.forEach((idx) => {
        const media = mediaItems[idx];

        if (typeof media === 'string') {
          preloadImage(media);
        }
      });

      // Priority 2: All other images (load after a short delay)
      const loadRemainingTimer = setTimeout(() => {
        mediaItems.forEach((media, idx) => {
          if (typeof media === 'string' && !priorityIndices.includes(idx)) {
            preloadImage(media);
          }
        });
      }, 500);

      return () => clearTimeout(loadRemainingTimer);
    }, [open, currentIndex, mediaItems]);

    useEffect(() => {
      if (currentIndex !== activeIndex) {
        // First, add new index to displayedIndices (will render with in=false)
        setDisplayedIndices((prev) =>
          prev.includes(currentIndex) ? prev : [...prev, currentIndex],
        );

        // Use requestAnimationFrame to ensure DOM is updated before triggering animation
        let rafId1: number | null = null;
        let rafId2: number | null = null;

        rafId1 = requestAnimationFrame(() => {
          rafId2 = requestAnimationFrame(() => {
            setActiveIndex(currentIndex);
          });
        });

        // Clean up old images after transition completes
        const cleanupTimer = setTimeout(() => {
          setDisplayedIndices([currentIndex]);
        }, MOTION_DURATION.fast + 100);

        return () => {
          clearTimeout(cleanupTimer);
          if (rafId1 !== null) {
            cancelAnimationFrame(rafId1);
          }
          if (rafId2 !== null) {
            cancelAnimationFrame(rafId2);
          }
        };
      }

      return undefined;
    }, [currentIndex, activeIndex]);

    // Memoize media elements to prevent unnecessary re-renders
    const mediaElements = useMemo(() => {
      return mediaItems.map((media, index) => {
        if (typeof media === 'string') {
          return {
            index,
            element: (
              <img
                alt={`Media ${index + 1}`}
                className={classes.mediaPreviewImage}
                src={media}
              />
            ),
          };
        }

        return {
          index,
          element: <div className={classes.mediaPreviewImage}>{media}</div>,
        };
      });
    }, [mediaItems]);

    const renderMedia = (index: number) => {
      const mediaElement = mediaElements.find((item) => item.index === index);

      if (!mediaElement) return null;

      const isCurrent = index === activeIndex;

      return (
        <Fade
          duration={{
            enter: MOTION_DURATION.fast,
            exit: MOTION_DURATION.fast,
          }}
          easing={{
            enter: MOTION_EASING.standard,
            exit: MOTION_EASING.standard,
          }}
          in={isCurrent}
          key={index}
        >
          {mediaElement.element}
        </Fade>
      );
    };

    return (
      <ModalContainer
        className={classes.overlay}
        container={container}
        disableCloseOnBackdropClick={disableCloseOnBackdropClick}
        disableCloseOnEscapeKeyDown={disableCloseOnEscapeKeyDown}
        disablePortal={disablePortal}
        onBackdropClick={onBackdropClick}
        onClose={onClose}
        open={open}
        ref={ref}
      >
        <div
          {...rest}
          className={cx(classes.host, classes.mediaPreview, className)}
          role="dialog"
        >
          <div className={classes.mediaPreviewContent}>
            <div className={classes.mediaPreviewMediaContainer}>
              {displayedIndices.map((index) => renderMedia(index))}
            </div>
          </div>
        </div>
        <ClearActions
          className={classes.mediaPreviewCloseButton}
          onClick={onClose}
          type="embedded"
          variant="contrast"
        />
        {mediaItems.length > 1 && (
          <button
            aria-disabled={isPrevDisabled}
            aria-label="Previous media"
            className={cx(
              classes.mediaPreviewNavButton,
              classes.mediaPreviewNavButtonPrev,
            )}
            disabled={isPrevDisabled}
            onClick={handlePrev}
            title="Previous"
            type="button"
          >
            <Icon icon={ChevronLeftIcon} size={16} color="fixed-light" />
          </button>
        )}
        {mediaItems.length > 1 && (
          <button
            aria-disabled={isNextDisabled}
            aria-label="Next media"
            className={cx(
              classes.mediaPreviewNavButton,
              classes.mediaPreviewNavButtonNext,
            )}
            disabled={isNextDisabled}
            onClick={handleNext}
            title="Next"
            type="button"
          >
            <Icon icon={ChevronRightIcon} size={16} color="fixed-light" />
          </button>
        )}
        {showPaginationIndicator && mediaItems.length > 1 && (
          <div
            aria-label={`Page ${currentIndex + 1} of ${mediaItems.length}`}
            className={classes.mediaPreviewPaginationIndicator}
          >
            {currentIndex + 1}/{mediaItems.length}
          </div>
        )}
      </ModalContainer>
    );
  },
);

export default MediaPreviewModal;
