// packages/vue/modal/media-preview-modal.vue
<script setup lang="ts">
import { computed, ref, watch, watchEffect } from 'vue';
import { ChevronLeftIcon, ChevronRightIcon } from '@mezzanine-ui/icons';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import { useHasListener } from '../_internal/use-has-listener';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznFade from '../transition/fade.vue';
import { useModalContainer } from './use-modal-container';
import type { MediaPreviewModalProps } from './media-preview-modal.types';

/**
 * 媒體預覽對話框，把一組圖片或節點鋪滿畫面並提供前後切換。
 *
 * 給 `currentIndex` 並監聽 `next` / `prev` 就是受控模式，索引完全由外部決定；
 * 否則元件自己記住索引，`enableCircularNavigation` 可讓頭尾相接，索引變動時
 * 發出 `index-change`。切換時新舊圖片交叉淡入淡出，並會預先載入相鄰的圖片。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznMediaPreviewModal } from '@mezzanine-ui/vue/modal';
 * <\/script>
 *
 * <template>
 *   <MznMediaPreviewModal
 *     :media-items="urls"
 *     :open="open"
 *     @close="open = false"
 *   />
 * </template>
 * ```
 *
 * @see MznModal 一般用途的對話框
 */
/**
 * React spreads its rest props onto the dialog element inside the container,
 * and `backdropClassName` onto the container itself.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<MediaPreviewModalProps>(), {
  backdropClassName: undefined,
  container: undefined,
  currentIndex: undefined,
  defaultIndex: 0,
  disableCloseOnBackdropClick: false,
  disableCloseOnEscapeKeyDown: false,
  disableNext: false,
  disablePortal: false,
  disablePrev: false,
  enableCircularNavigation: false,
  open: undefined,
  showPaginationIndicator: true,
});

const emit = defineEmits<{
  backdropClick: [event: MouseEvent];
  close: [];
  indexChange: [index: number];
  next: [];
  prev: [];
}>();

const hasListener = useHasListener();

const { Container: MznModalContainer } = useModalContainer();

// Determine if component is in controlled mode
const isControlled = computed((): boolean => props.currentIndex !== undefined);

// Internal state for uncontrolled mode
const internalIndex = ref(props.defaultIndex);

// Use controlled index if provided, otherwise use internal state
const currentIndex = computed((): number =>
  isControlled.value ? (props.currentIndex as number) : internalIndex.value,
);

// Reset internal index when modal opens in uncontrolled mode
watch(
  [() => props.open, isControlled, () => props.defaultIndex],
  () => {
    if (props.open && !isControlled.value) {
      internalIndex.value = props.defaultIndex;
    }
  },
  { immediate: true },
);

// Built-in navigation handlers for uncontrolled mode
function handleNext(): void {
  if (hasListener('next')) {
    // Controlled mode: hand it to the consumer
    emit('next');

    return;
  }

  // Uncontrolled mode: update internal state
  const nextIndex = props.enableCircularNavigation
    ? (currentIndex.value + 1) % props.mediaItems.length
    : Math.min(currentIndex.value + 1, props.mediaItems.length - 1);

  internalIndex.value = nextIndex;
  emit('indexChange', nextIndex);
}

function handlePrev(): void {
  if (hasListener('prev')) {
    // Controlled mode: hand it to the consumer
    emit('prev');

    return;
  }

  // Uncontrolled mode: update internal state
  const prevIndex = props.enableCircularNavigation
    ? (currentIndex.value - 1 + props.mediaItems.length) %
      props.mediaItems.length
    : Math.max(currentIndex.value - 1, 0);

  internalIndex.value = prevIndex;
  emit('indexChange', prevIndex);
}

// Auto-calculate disable states for uncontrolled mode
const isNextDisabled = computed((): boolean =>
  props.enableCircularNavigation
    ? false
    : props.disableNext || currentIndex.value >= props.mediaItems.length - 1,
);

const isPrevDisabled = computed((): boolean =>
  props.enableCircularNavigation
    ? false
    : props.disablePrev || currentIndex.value <= 0,
);

const displayedIndices = ref<number[]>([currentIndex.value]);
const activeIndex = ref<number>(currentIndex.value);
const preloadedUrls = new Set<string>();

// Helper function to preload a single image
function preloadImage(url: string): void {
  if (preloadedUrls.has(url)) return;

  const img = new Image();

  img.src = url;
  preloadedUrls.add(url);
}

// Preload images: prioritize current and adjacent, then load others
watchEffect((onCleanup) => {
  if (!props.open) return;

  const items = props.mediaItems;
  const index = currentIndex.value;

  // Priority 1: Current and adjacent images
  const priorityIndices = [index - 1, index, index + 1].filter(
    (idx) => idx >= 0 && idx < items.length,
  );

  priorityIndices.forEach((idx) => {
    const media = items[idx];

    if (typeof media === 'string') {
      preloadImage(media);
    }
  });

  // Priority 2: All other images (load after a short delay)
  const loadRemainingTimer = setTimeout(() => {
    items.forEach((media, idx) => {
      if (typeof media === 'string' && !priorityIndices.includes(idx)) {
        preloadImage(media);
      }
    });
  }, 500);

  onCleanup(() => clearTimeout(loadRemainingTimer));
});

/**
 * The outgoing image has to stay mounted while the incoming one fades in, and
 * the incoming one has to render once with `in="false"` before it can animate
 * — hence the two frames before `activeIndex` moves.
 */
watch(
  [currentIndex, activeIndex],
  (_value, _previous, onCleanup) => {
    if (currentIndex.value === activeIndex.value) return;

    // First, add new index to displayedIndices (will render with in=false)
    if (!displayedIndices.value.includes(currentIndex.value)) {
      displayedIndices.value = [...displayedIndices.value, currentIndex.value];
    }

    // Use requestAnimationFrame to ensure DOM is updated before triggering animation
    let rafId1: number | null = null;
    let rafId2: number | null = null;

    rafId1 = requestAnimationFrame(() => {
      rafId2 = requestAnimationFrame(() => {
        activeIndex.value = currentIndex.value;
      });
    });

    // Clean up old images after transition completes
    const cleanupTimer = setTimeout(() => {
      displayedIndices.value = [currentIndex.value];
    }, MOTION_DURATION.fast + 100);

    onCleanup(() => {
      clearTimeout(cleanupTimer);

      if (rafId1 !== null) {
        cancelAnimationFrame(rafId1);
      }

      if (rafId2 !== null) {
        cancelAnimationFrame(rafId2);
      }
    });
  },
  { immediate: true },
);

const FADE_DURATION = {
  enter: MOTION_DURATION.fast,
  exit: MOTION_DURATION.fast,
};

const FADE_EASING = {
  enter: MOTION_EASING.standard,
  exit: MOTION_EASING.standard,
};

const hostClasses = computed((): string =>
  clsx(classes.host, classes.mediaPreview),
);

const prevButtonClasses = clsx(
  classes.mediaPreviewNavButton,
  classes.mediaPreviewNavButtonPrev,
);

const nextButtonClasses = clsx(
  classes.mediaPreviewNavButton,
  classes.mediaPreviewNavButtonNext,
);

const closeButtonClass = classes.mediaPreviewCloseButton;
const contentClass = classes.mediaPreviewContent;
const imageClass = classes.mediaPreviewImage;
const mediaContainerClass = classes.mediaPreviewMediaContainer;
const paginationIndicatorClass = classes.mediaPreviewPaginationIndicator;
</script>

<template>
  <MznModalContainer
    :class="backdropClassName"
    :container="container"
    :disable-close-on-backdrop-click="disableCloseOnBackdropClick"
    :disable-close-on-escape-key-down="disableCloseOnEscapeKeyDown"
    :disable-portal="disablePortal"
    :open="open"
    @backdrop-click="emit('backdropClick', $event)"
    @close="emit('close')"
  >
    <div v-bind="$attrs" :class="hostClasses" role="dialog">
      <div :class="contentClass">
        <div :class="mediaContainerClass">
          <template v-for="index in displayedIndices" :key="index">
            <MznFade
              v-if="index >= 0 && index < mediaItems.length"
              :duration="FADE_DURATION"
              :easing="FADE_EASING"
              :in="index === activeIndex"
            >
              <img
                v-if="typeof mediaItems[index] === 'string'"
                :alt="`Media ${index + 1}`"
                :class="imageClass"
                :src="mediaItems[index] as string"
              />
              <div v-else :class="imageClass">
                <component :is="() => mediaItems[index]" />
              </div>
            </MznFade>
          </template>
        </div>
      </div>
    </div>
    <MznClearActions
      :class="closeButtonClass"
      type="embedded"
      variant="contrast"
      @click="emit('close')"
    />
    <button
      v-if="mediaItems.length > 1"
      :aria-disabled="isPrevDisabled"
      aria-label="Previous media"
      :class="prevButtonClasses"
      :disabled="isPrevDisabled"
      title="Previous"
      type="button"
      @click="handlePrev"
    >
      <MznIcon color="fixed-light" :icon="ChevronLeftIcon" :size="16" />
    </button>
    <button
      v-if="mediaItems.length > 1"
      :aria-disabled="isNextDisabled"
      aria-label="Next media"
      :class="nextButtonClasses"
      :disabled="isNextDisabled"
      title="Next"
      type="button"
      @click="handleNext"
    >
      <MznIcon color="fixed-light" :icon="ChevronRightIcon" :size="16" />
    </button>
    <div
      v-if="showPaginationIndicator && mediaItems.length > 1"
      :aria-label="`Page ${currentIndex + 1} of ${mediaItems.length}`"
      :class="paginationIndicatorClass"
    >
      <component
        :is="() => [String(currentIndex + 1), '/', String(mediaItems.length)]"
      />
    </div>
  </MznModalContainer>
</template>

// packages/react/src/Modal/MediaPreviewModal.tsx
'use client';

import { forwardRef, useEffect, useMemo, useRef, useState } from 'react';
import { ChevronLeftIcon, ChevronRightIcon } from '@mezzanine-ui/icons';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import useModalContainer, { ModalContainerProps } from './useModalContainer';
import Icon from '../Icon';
import ClearActions from '../ClearActions';
import { Fade } from '../Transition';

export interface MediaPreviewModalProps
  extends Omit<ModalContainerProps, 'children'>,
    NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * The current index of the media being displayed (controlled mode).
   * If provided along with onNext/onPrev, the component operates in controlled mode.
   */
  currentIndex?: number;
  /**
   * The default index when the modal opens (uncontrolled mode).
   * @default 0
   */
  defaultIndex?: number;
  /**
   * Whether to disable the next navigation button.
   * @default false
   */
  disableNext?: boolean;
  /**
   * Whether to disable the previous navigation button.
   * @default false
   */
  disablePrev?: boolean;
  /**
   * Array of media items to display.
   * Each item should be a valid image URL or React node.
   */
  mediaItems: (string | React.ReactNode)[];
  /**
   * Callback fired when the index changes (uncontrolled mode).
   */
  onIndexChange?: (index: number) => void;
  /**
   * Callback fired when the next navigation button is clicked (controlled mode).
   * If provided, the component operates in controlled mode.
   */
  onNext?: () => void;
  /**
   * Callback fired when the previous navigation button is clicked (controlled mode).
   * If provided, the component operates in controlled mode.
   */
  onPrev?: () => void;
  /**
   * Whether to show the pagination indicator.
   * @default true
   */
  showPaginationIndicator?: boolean;
}

/**
 * The react component for `mezzanine` media preview modal.
 * Displays media items with navigation controls and a close button.
 */
const MediaPreviewModal = forwardRef<HTMLDivElement, MediaPreviewModalProps>(
  function MediaPreviewModal(props, ref) {
    const {
      className,
      container,
      currentIndex: controlledIndex,
      defaultIndex = 0,
      disableCloseOnBackdropClick = false,
      disableCloseOnEscapeKeyDown = false,
      disableNext = false,
      disablePortal = false,
      disablePrev = false,
      mediaItems,
      onBackdropClick,
      onClose,
      onIndexChange,
      onNext,
      onPrev,
      open,
      showPaginationIndicator = true,
      ...rest
    } = props;

    const { Container: ModalContainer } = useModalContainer();

    // Determine if component is in controlled mode
    const isControlled = controlledIndex !== undefined;

    // Internal state for uncontrolled mode
    const [internalIndex, setInternalIndex] = useState(defaultIndex);

    // Use controlled index if provided, otherwise use internal state
    const currentIndex = isControlled ? controlledIndex : internalIndex;

    // Reset internal index when modal opens in uncontrolled mode
    useEffect(() => {
      if (open && !isControlled) {
        setInternalIndex(defaultIndex);
      }
    }, [open, isControlled, defaultIndex]);

    // Built-in navigation handlers for uncontrolled mode
    const handleNext = () => {
      if (onNext) {
        // Controlled mode: use provided callback
        onNext();
      } else {
        // Uncontrolled mode: update internal state
        const nextIndex = Math.min(currentIndex + 1, mediaItems.length - 1);
        setInternalIndex(nextIndex);
        onIndexChange?.(nextIndex);
      }
    };

    const handlePrev = () => {
      if (onPrev) {
        // Controlled mode: use provided callback
        onPrev();
      } else {
        // Uncontrolled mode: update internal state
        const prevIndex = Math.max(currentIndex - 1, 0);
        setInternalIndex(prevIndex);
        onIndexChange?.(prevIndex);
      }
    };

    // Auto-calculate disable states for uncontrolled mode
    const isNextDisabled = disableNext || currentIndex >= mediaItems.length - 1;
    const isPrevDisabled = disablePrev || currentIndex <= 0;

    const [displayedIndices, setDisplayedIndices] = useState<number[]>([
      currentIndex,
    ]);
    const [activeIndex, setActiveIndex] = useState<number>(currentIndex);
    const preloadedUrls = useRef<Set<string>>(new Set());

    // Helper function to preload a single image
    const preloadImage = (url: string) => {
      if (preloadedUrls.current.has(url)) return;

      const img = new Image();
      img.src = url;
      preloadedUrls.current.add(url);
    };

    // Preload images: prioritize current and adjacent, then load others
    useEffect(() => {
      if (!open) return;

      // Priority 1: Current and adjacent images
      const priorityIndices = [
        currentIndex - 1,
        currentIndex,
        currentIndex + 1,
      ].filter((idx) => idx >= 0 && idx < mediaItems.length);

      priorityIndices.forEach((idx) => {
        const media = mediaItems[idx];

        if (typeof media === 'string') {
          preloadImage(media);
        }
      });

      // Priority 2: All other images (load after a short delay)
      const loadRemainingTimer = setTimeout(() => {
        mediaItems.forEach((media, idx) => {
          if (typeof media === 'string' && !priorityIndices.includes(idx)) {
            preloadImage(media);
          }
        });
      }, 500);

      return () => clearTimeout(loadRemainingTimer);
    }, [open, currentIndex, mediaItems]);

    useEffect(() => {
      if (currentIndex !== activeIndex) {
        // First, add new index to displayedIndices (will render with in=false)
        setDisplayedIndices((prev) =>
          prev.includes(currentIndex) ? prev : [...prev, currentIndex],
        );

        // Use requestAnimationFrame to ensure DOM is updated before triggering animation
        let rafId1: number | null = null;
        let rafId2: number | null = null;

        rafId1 = requestAnimationFrame(() => {
          rafId2 = requestAnimationFrame(() => {
            setActiveIndex(currentIndex);
          });
        });

        // Clean up old images after transition completes
        const cleanupTimer = setTimeout(() => {
          setDisplayedIndices([currentIndex]);
        }, MOTION_DURATION.fast + 100);

        return () => {
          clearTimeout(cleanupTimer);
          if (rafId1 !== null) {
            cancelAnimationFrame(rafId1);
          }
          if (rafId2 !== null) {
            cancelAnimationFrame(rafId2);
          }
        };
      }

      return undefined;
    }, [currentIndex, activeIndex]);

    // Memoize media elements to prevent unnecessary re-renders
    const mediaElements = useMemo(() => {
      return mediaItems.map((media, index) => {
        if (typeof media === 'string') {
          return {
            index,
            element: (
              <img
                alt={`Media ${index + 1}`}
                className={classes.mediaPreviewImage}
                src={media}
              />
            ),
          };
        }

        return {
          index,
          element: <div className={classes.mediaPreviewImage}>{media}</div>,
        };
      });
    }, [mediaItems]);

    const renderMedia = (index: number) => {
      const mediaElement = mediaElements.find((item) => item.index === index);

      if (!mediaElement) return null;

      const isCurrent = index === activeIndex;

      return (
        <Fade
          duration={{
            enter: MOTION_DURATION.fast,
            exit: MOTION_DURATION.fast,
          }}
          easing={{
            enter: MOTION_EASING.entrance,
            exit: MOTION_EASING.exit,
          }}
          in={isCurrent}
          key={index}
        >
          {mediaElement.element}
        </Fade>
      );
    };

    return (
      <ModalContainer
        className={classes.overlay}
        container={container}
        disableCloseOnBackdropClick={disableCloseOnBackdropClick}
        disableCloseOnEscapeKeyDown={disableCloseOnEscapeKeyDown}
        disablePortal={disablePortal}
        onBackdropClick={onBackdropClick}
        onClose={onClose}
        open={open}
        ref={ref}
      >
        <div
          {...rest}
          className={cx(classes.host, classes.mediaPreview, className)}
          role="dialog"
        >
          <div className={classes.mediaPreviewContent}>
            <div className={classes.mediaPreviewMediaContainer}>
              {displayedIndices.map((index) => renderMedia(index))}
            </div>
          </div>
        </div>
        <ClearActions
          className={classes.mediaPreviewCloseButton}
          onClick={onClose}
          type="embedded"
          variant="contrast"
        />
        {mediaItems.length > 1 && (
          <button
            aria-disabled={isPrevDisabled}
            aria-label="Previous media"
            className={cx(
              classes.mediaPreviewNavButton,
              classes.mediaPreviewNavButtonPrev,
            )}
            disabled={isPrevDisabled}
            onClick={handlePrev}
            title="Previous"
            type="button"
          >
            <Icon icon={ChevronLeftIcon} size={16} color="fixed-light" />
          </button>
        )}
        {mediaItems.length > 1 && (
          <button
            aria-disabled={isNextDisabled}
            aria-label="Next media"
            className={cx(
              classes.mediaPreviewNavButton,
              classes.mediaPreviewNavButtonNext,
            )}
            disabled={isNextDisabled}
            onClick={handleNext}
            title="Next"
            type="button"
          >
            <Icon icon={ChevronRightIcon} size={16} color="fixed-light" />
          </button>
        )}
        {showPaginationIndicator && mediaItems.length > 1 && (
          <div
            aria-label={`Page ${currentIndex + 1} of ${mediaItems.length}`}
            className={classes.mediaPreviewPaginationIndicator}
          >
            {currentIndex + 1}/{mediaItems.length}
          </div>
        )}
      </ModalContainer>
    );
  },
);

export default MediaPreviewModal;
