// packages/vue/modal/modal-footer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import MznButtonGroup from '../button/button-group.vue';
import type { ButtonProps } from '../button/button.types';
import MznCheckbox from '../checkbox/checkbox.vue';
import MznToggle from '../toggle/toggle.vue';
import MznTypography from '../typography/typography.vue';
import type { ModalFooterProps } from './modal-footer.types';

/**
 * Modal 的操作列：右側是取消與確認按鈕，左側可放一份輔助內容。
 *
 * `auxiliaryContentType` 決定左側放什麼 —— 註記文字、文字按鈕、核取方塊、
 * 切換開關，或密碼情境（記住我＋忘記密碼）。`loading` 會讓確認鈕轉圈、
 * 取消鈕停用。沒有輔助內容時，`actionsButtonLayout="fill"` 可讓兩顆按鈕等分寬度。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznModalFooter } from '@mezzanine-ui/vue/modal';
 * <\/script>
 *
 * <template>
 *   <MznModalFooter
 *     cancel-text="取消"
 *     confirm-text="確認"
 *     @cancel="close"
 *     @confirm="submit"
 *   />
 *
 *   <MznModalFooter
 *     annotation="這個動作無法復原"
 *     auxiliary-content-type="annotation"
 *     confirm-text="刪除"
 *     :show-cancel-button="false"
 *     @confirm="remove"
 *   />
 * </template>
 * ```
 *
 * @see MznModal 以 showModalFooter 渲染這個操作列
 */
const props = withDefaults(defineProps<ModalFooterProps>(), {
  actionsButtonLayout: 'fixed',
  annotation: undefined,
  auxiliaryContentButtonProps: undefined,
  auxiliaryContentButtonText: undefined,
  auxiliaryContentChecked: undefined,
  auxiliaryContentLabel: undefined,
  auxiliaryContentOnChange: undefined,
  auxiliaryContentOnClick: undefined,
  auxiliaryContentType: undefined,
  cancelButtonProps: undefined,
  cancelText: undefined,
  confirmButtonProps: undefined,
  confirmText: undefined,
  loading: undefined,
  passwordButtonProps: undefined,
  passwordButtonText: undefined,
  passwordChecked: undefined,
  passwordCheckedLabel: undefined,
  passwordCheckedOnChange: undefined,
  passwordOnClick: undefined,
  showCancelButton: true,
});

const emit = defineEmits<{
  cancel: [event: MouseEvent];
  confirm: [event: MouseEvent];
}>();

defineSlots<{
  /** Extra content, rendered after the action buttons. */
  default?: () => unknown;
}>();

/**
 * React spreads the button props and then writes `onClick` after them, so the
 * later one wins. A `v-bind` object does the same; two separate bindings would
 * instead *chain* the handlers, running both.
 */
type ButtonBindings = ButtonProps & {
  class?: string;
  onClick?: (event: MouseEvent) => void;
};

const cancelButtonDisabled = computed(
  (): boolean | undefined => props.cancelButtonProps?.disabled ?? props.loading,
);

const isActionsButtonFillLayout = computed(
  (): boolean =>
    props.actionsButtonLayout === 'fill' && !props.auxiliaryContentType,
);

const hostClasses = computed((): string =>
  clsx(classes.modalFooter, {
    [`${classes.modalFooter}--password-mode`]:
      props.auxiliaryContentType === 'password',
    [`${classes.modalFooter}--with-auxiliary-content`]:
      !!props.auxiliaryContentType && props.auxiliaryContentType !== 'password',
  }),
);

const actionsButtonContainerClasses = computed((): string =>
  clsx(classes.modalFooterActionsButtonContainer, {
    [`${classes.modalFooterActionsButtonContainer}--fill-layout`]:
      isActionsButtonFillLayout.value,
  }),
);

const passwordButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-text-link',
    ...props.passwordButtonProps,
    onClick: props.passwordOnClick,
  }),
);

const auxiliaryContentButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-text-link',
    ...props.auxiliaryContentButtonProps,
    onClick: props.auxiliaryContentOnClick,
  }),
);

const cancelButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-secondary',
    ...props.cancelButtonProps,
    class: classes.modalFooterActionsButton,
    disabled: cancelButtonDisabled.value,
    onClick: (event: MouseEvent) => emit('cancel', event),
  }),
);

const confirmButtonBindings = computed(
  (): ButtonBindings => ({
    variant: 'base-primary',
    ...props.confirmButtonProps,
    class: classes.modalFooterActionsButton,
    loading: props.loading,
    onClick: (event: MouseEvent) => emit('confirm', event),
  }),
);

function onPasswordCheckedChange(event: Event): void {
  props.passwordCheckedOnChange?.((event.target as HTMLInputElement).checked);
}

function onAuxiliaryContentChange(event: Event): void {
  props.auxiliaryContentOnChange?.((event.target as HTMLInputElement).checked);
}

const passwordContainerClass = classes.modalFooterPasswordContainer;
const auxiliaryContentContainerClass =
  classes.modalFooterAuxiliaryContentContainer;
</script>

<template>
  <div :class="hostClasses">
    <div
      v-if="auxiliaryContentType === 'password'"
      :class="passwordContainerClass"
    >
      <MznCheckbox
        :checked="passwordChecked"
        :label="passwordCheckedLabel"
        @change="onPasswordCheckedChange"
      />
      <MznButton v-bind="passwordButtonBindings">
        <component :is="() => passwordButtonText" />
      </MznButton>
    </div>
    <div
      v-if="auxiliaryContentType && auxiliaryContentType !== 'password'"
      :class="auxiliaryContentContainerClass"
    >
      <MznTypography
        v-if="auxiliaryContentType === 'annotation'"
        color="text-neutral"
        variant="caption"
      >
        <component :is="() => annotation" />
      </MznTypography>
      <MznButton
        v-if="auxiliaryContentType === 'button'"
        v-bind="auxiliaryContentButtonBindings"
      >
        <component :is="() => auxiliaryContentButtonText" />
      </MznButton>
      <MznCheckbox
        v-if="auxiliaryContentType === 'checkbox'"
        :checked="auxiliaryContentChecked"
        :label="auxiliaryContentLabel"
        @change="onAuxiliaryContentChange"
      />
      <MznToggle
        v-if="auxiliaryContentType === 'toggle'"
        :checked="auxiliaryContentChecked"
        :label="auxiliaryContentLabel"
        @change="onAuxiliaryContentChange"
      />
    </div>
    <MznButtonGroup :class="actionsButtonContainerClasses">
      <MznButton v-if="showCancelButton" v-bind="cancelButtonBindings">
        <component :is="() => cancelText" />
      </MznButton>
      <MznButton v-bind="confirmButtonBindings">
        <component :is="() => confirmText" />
      </MznButton>
    </MznButtonGroup>
    <slot />
  </div>
</template>

// packages/react/src/Modal/ModalFooter.tsx
import { forwardRef, ReactNode } from 'react';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Button, { ButtonProps } from '../Button/Button';
import ButtonGroup from '../Button/ButtonGroup';
import Checkbox from '../Checkbox/Checkbox';
import Toggle from '../Toggle/Toggle';
import Typography from '../Typography';

export interface ModalFooterProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * Layout of action buttons.
   * - 'fixed': Buttons maintain fixed width
   * - 'fill': Buttons expand to fill available space equally
   * @default 'fixed'
   */
  actionsButtonLayout?: 'fill' | 'fixed';
  /**
   * Text to display as annotation on the left side.
   * Only used when auxiliaryContentType is 'annotation'.
   */
  annotation?: ReactNode;
  /**
   * Props for the auxiliary content button.
   * Only used when auxiliaryContentType is 'button'.
   */
  auxiliaryContentButtonProps?: ButtonProps;
  /**
   * Text for the auxiliary content button.
   * Only used when auxiliaryContentType is 'button'.
   */
  auxiliaryContentButtonText?: ReactNode;
  /**
   * Whether the auxiliary content control (checkbox/toggle) is checked.
   * Only used when auxiliaryContentType is 'checkbox' or 'toggle'.
   */
  auxiliaryContentChecked?: boolean;
  /**
   * Label text for the auxiliary content control (checkbox/toggle).
   * Only used when auxiliaryContentType is 'checkbox' or 'toggle'.
   */
  auxiliaryContentLabel?: string;
  /**
   * Change handler for auxiliary content control (checkbox/toggle).
   * Only used when auxiliaryContentType is 'checkbox' or 'toggle'.
   */
  auxiliaryContentOnChange?: (checked: boolean) => void;
  /**
   * Click handler for the auxiliary content button.
   * Only used when auxiliaryContentType is 'button'.
   */
  auxiliaryContentOnClick?: ButtonProps['onClick'];
  /**
   * Type of auxiliary content to show on the left side of the footer.
   * - 'annotation': Display text annotation
   * - 'button': Display a button
   * - 'checkbox': Display a checkbox control
   * - 'toggle': Display a toggle control
   * - 'password': Display password-specific controls (remember me + forgot password)
   * @default undefined (no auxiliary content)
   */
  auxiliaryContentType?:
    | 'annotation'
    | 'button'
    | 'checkbox'
    | 'toggle'
    | 'password';
  /**
   * Additional props for the cancel button.
   */
  cancelButtonProps?: ButtonProps;
  /**
   * Text content of the cancel button.
   */
  cancelText?: ReactNode;
  /**
   * Additional props for the confirm button.
   */
  confirmButtonProps?: ButtonProps;
  /**
   * Text content of the confirm button.
   */
  confirmText?: ReactNode;
  /**
   * Whether confirm button is loading and cancel button is disabled.
   */
  loading?: boolean;
  /**
   * Click handler for the cancel button.
   */
  onCancel?: ButtonProps['onClick'];
  /**
   * Click handler for the confirm button.
   */
  onConfirm?: ButtonProps['onClick'];
  /**
   * Props for the password auxiliary button.
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordButtonProps?: ButtonProps;
  /**
   * Text for the password auxiliary button (e.g., "Forgot password?").
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordButtonText?: ReactNode;
  /**
   * Whether the password checkbox is checked (e.g., "Remember me").
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordChecked?: boolean;
  /**
   * Label for the password checkbox (e.g., "Remember me").
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordCheckedLabel?: string;
  /**
   * Change handler for the password checkbox.
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordCheckedOnChange?: (checked: boolean) => void;
  /**
   * Click handler for the password auxiliary button.
   * Only used when auxiliaryContentType is 'password'.
   */
  passwordOnClick?: ButtonProps['onClick'];
  /**
   * Whether to show the cancel button.
   * @default true
   */
  showCancelButton?: boolean;
}

/**
 * The react component for `mezzanine` modal footer.
 */
const ModalFooter = forwardRef<HTMLDivElement, ModalFooterProps>(
  function ModalFooter(props, ref) {
    const {
      children,
      className,
      actionsButtonLayout = 'fixed',
      annotation,
      auxiliaryContentButtonProps,
      auxiliaryContentButtonText,
      auxiliaryContentChecked,
      auxiliaryContentLabel,
      auxiliaryContentOnChange,
      auxiliaryContentOnClick,
      auxiliaryContentType,
      cancelButtonProps,
      cancelText,
      confirmButtonProps,
      confirmText,
      loading,
      onCancel,
      onConfirm,
      passwordButtonProps,
      passwordButtonText,
      passwordChecked,
      passwordCheckedLabel,
      passwordCheckedOnChange,
      passwordOnClick,
      showCancelButton = true,
      ...rest
    } = props;

    const { disabled: cancelButtonDisabled = loading } =
      cancelButtonProps || {};

    const isActionsButtonFillLayout =
      actionsButtonLayout === 'fill' && !auxiliaryContentType;

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(
          classes.modalFooter,
          {
            [classes.modalFooter + '--password-mode']:
              auxiliaryContentType === 'password',
            [classes.modalFooter + '--with-auxiliary-content']:
              !!auxiliaryContentType && auxiliaryContentType !== 'password',
          },
          className,
        )}
      >
        {auxiliaryContentType === 'password' && (
          <div className={classes.modalFooterPasswordContainer}>
            <Checkbox
              checked={passwordChecked}
              label={passwordCheckedLabel}
              onChange={(e) => passwordCheckedOnChange?.(e.target.checked)}
            />
            <Button
              variant="base-text-link"
              {...passwordButtonProps}
              onClick={passwordOnClick}
            >
              {passwordButtonText}
            </Button>
          </div>
        )}
        {auxiliaryContentType && auxiliaryContentType !== 'password' && (
          <div className={classes.modalFooterAuxiliaryContentContainer}>
            {auxiliaryContentType === 'annotation' && (
              <Typography variant="caption" color="text-neutral">
                {annotation}
              </Typography>
            )}
            {auxiliaryContentType === 'button' && (
              <Button
                variant="base-text-link"
                {...auxiliaryContentButtonProps}
                onClick={auxiliaryContentOnClick}
              >
                {auxiliaryContentButtonText}
              </Button>
            )}
            {auxiliaryContentType === 'checkbox' && (
              <Checkbox
                checked={auxiliaryContentChecked}
                label={auxiliaryContentLabel}
                onChange={(e) => auxiliaryContentOnChange?.(e.target.checked)}
              />
            )}
            {auxiliaryContentType === 'toggle' && (
              <Toggle
                checked={auxiliaryContentChecked}
                label={auxiliaryContentLabel}
                onChange={(e) => auxiliaryContentOnChange?.(e.target.checked)}
              />
            )}
          </div>
        )}
        <ButtonGroup
          className={cx(classes.modalFooterActionsButtonContainer, {
            [classes.modalFooterActionsButtonContainer + '--fill-layout']:
              isActionsButtonFillLayout,
          })}
        >
          {showCancelButton && (
            <Button
              variant="base-secondary"
              {...cancelButtonProps}
              disabled={cancelButtonDisabled}
              onClick={onCancel}
              className={classes.modalFooterActionsButton}
            >
              {cancelText}
            </Button>
          )}
          <Button
            variant="base-primary"
            {...confirmButtonProps}
            loading={loading}
            onClick={onConfirm}
            className={classes.modalFooterActionsButton}
          >
            {confirmText}
          </Button>
        </ButtonGroup>
        {children}
      </div>
    );
  },
);

export default ModalFooter;
