// packages/react/src/Navigation/NavigationOverflowMenuOption.tsx
'use client';

import {
  Children,
  forwardRef,
  isValidElement,
  ReactElement,
  use,
  useEffect,
  useId,
  useMemo,
  useState,
} from 'react';
import { navigationOverflowMenuOptionClasses as classes } from '@mezzanine-ui/core/navigation';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import { cx } from '../utils/cx';
import Icon from '../Icon';
import {
  NavigationActivatedContext,
  NavigationOptionLevelContext,
} from './context';
import { flattenChildren } from '../utils/flatten-children';
import Badge, { BadgeProps } from '../Badge';
import NavigationOption, {
  NavigationOptionChildren,
  NavigationOptionProps,
} from './NavigationOption';

export interface NavigationOverflowMenuOptionProps
  extends NavigationOptionProps {
  onTriggerClick?: (
    path: string[],
    currentKey: string,
    href?: string,
    items?: ReactElement<NavigationOptionProps>[],
  ) => void;
}

const NavigationOverflowMenuOption = forwardRef<
  HTMLLIElement,
  NavigationOverflowMenuOptionProps
>((props, ref) => {
  const {
    active,
    children,
    className,
    anchorComponent,
    defaultOpen = false,
    href,
    icon,
    id,
    onTriggerClick,
    title,
    ...rest
  } = props;

  const [open, setOpen] = useState<boolean>(defaultOpen);

  const { level, path: parentPath } = use(NavigationOptionLevelContext);
  const currentLevel = level + 1; // start as 1

  const uuid = useId();
  const currentKey = id || title || href || uuid;
  const currentPath = useMemo(
    () => [...parentPath, currentKey],
    [parentPath, currentKey],
  );
  const currentPathKey = currentPath.join('::');

  const {
    activatedPath,
    activatedPathKey,
    setActivatedPath,
    optionsAnchorComponent,
  } = use(NavigationActivatedContext);

  // Default open if current path is activated
  useEffect(() => {
    if (
      activatedPathKey === currentPathKey ||
      activatedPathKey.startsWith(`${currentPathKey}::`)
    ) {
      setOpen(true);
    }
  }, [activatedPathKey, currentLevel, currentPathKey]);

  const Component = href
    ? (anchorComponent ?? optionsAnchorComponent ?? 'a')
    : 'div';

  const flattenedChildren = useMemo(
    () => flattenChildren(children) as NavigationOptionChildren,
    [children],
  );

  const { badge, items } = useMemo(() => {
    let badgeComponent: ReactElement<BadgeProps> | null = null;

    const items: ReactElement<NavigationOptionProps>[] = [];

    Children.forEach(flattenedChildren, (child: NavigationOptionChildren) => {
      if (child && isValidElement(child)) {
        switch (child.type) {
          case Badge: {
            badgeComponent = child as ReactElement<BadgeProps>;
            break;
          }
          case NavigationOption: {
            items.push(child as ReactElement<NavigationOptionProps>);
            break;
          }
          default:
            console.warn(
              '[Mezzanine][NavigationOption]: NavigationOption only accepts NavigationOption or Badge as children.',
            );
        }
      }
    });

    return { badge: badgeComponent, items };
  }, [flattenedChildren]);

  return (
    <li
      {...rest}
      ref={ref}
      className={cx(
        classes.host,
        open && classes.open,
        !children && classes.basic,
        (active ?? activatedPath?.[currentLevel - 1] === currentKey) &&
          classes.active,
        className,
      )}
      data-id={currentKey}
    >
      <Component
        /**
         * The div form is a disclosure for its sub-options, so tell assistive
         * technology whether that group is currently open.
         */
        aria-expanded={children ? open : undefined}
        className={cx(classes.content)}
        href={href}
        onClick={() => {
          setOpen(!open);
          onTriggerClick?.(currentPath, currentKey, href, items);

          if (!children) setActivatedPath(currentPath);
        }}
        onKeyDown={(
          e: React.KeyboardEvent<HTMLAnchorElement | HTMLDivElement>,
        ) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            setOpen(!open);

            if (!children) setActivatedPath(currentPath);
          }
        }}
        /**
         * Same reasoning as NavigationOption: the overflow list is a set of
         * links inside a plain `<ul>`, so `menuitem` is both unsupported by its
         * ancestors and a promise of a keyboard model this component does not
         * implement.
         */
        role={Component === 'div' ? 'button' : undefined}
        tabIndex={0}
      >
        {icon && <Icon className={classes.icon} icon={icon} />}
        <span className={classes.title}>{title}</span>
        {badge}
        {children && (
          <Icon className={classes.toggleIcon} icon={ChevronRightIcon} />
        )}
      </Component>
    </li>
  );
});

export default NavigationOverflowMenuOption;

// packages/vue/navigation/navigation-overflow-menu-option.vue
<script setup lang="ts">
import { computed, inject, ref, useId, useSlots, watch } from 'vue';
import type { Component, FunctionalComponent, VNode } from 'vue';
import { navigationOverflowMenuOptionClasses as classes } from '@mezzanine-ui/core/navigation';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import MznBadge from '../badge/badge.vue';
import MznIcon from '../icon/icon.vue';
import MznNavigationOption from './navigation-option.vue';
import {
  NAVIGATION_ACTIVATED_CONTEXT,
  NAVIGATION_OPTION_LEVEL_CONTEXT,
  navigationOptionLevelContextDefaultValues,
} from './navigation-context';
import type { NavigationOverflowMenuOptionProps } from './navigation-overflow-menu-option.types';

/**
 * 收合側邊欄「更多」浮層裡的一列。
 *
 * 有子項時右邊是往右的箭頭，點一下由浮層負責再開一欄；沒有子項時就是一條連結。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznNavigationOverflowMenuOption } from '@mezzanine-ui/vue/navigation';
 * <\/script>
 *
 * <template>
 *   <MznNavigationOverflowMenuOption title="專案 1" />
 * </template>
 * ```
 *
 * @see MznNavigationOverflowMenu 承載這些列的浮層
 */
const props = withDefaults(defineProps<NavigationOverflowMenuOptionProps>(), {
  active: undefined,
  anchorComponent: undefined,
  defaultOpen: false,
  href: undefined,
  icon: undefined,
  id: undefined,
});

const emit = defineEmits<{
  /** Fired when the row is clicked, with its path, key, href and sub-options. */
  triggerClick: [
    path: string[],
    currentKey: string,
    href?: string,
    items?: VNode[],
  ];
}>();

defineSlots<{
  /** The sub-options, and at most one badge. */
  default?: () => unknown;
}>();

const slots = useSlots();

const open = ref(props.defaultOpen);

const levelContext = inject(NAVIGATION_OPTION_LEVEL_CONTEXT, undefined);
const context = inject(NAVIGATION_ACTIVATED_CONTEXT, undefined);

const level = computed(
  (): number =>
    levelContext?.value.level ??
    navigationOptionLevelContextDefaultValues.level,
);
const parentPath = computed(
  (): string[] =>
    levelContext?.value.path ?? navigationOptionLevelContextDefaultValues.path,
);

/** Levels start at 1. */
const currentLevel = computed((): number => level.value + 1);

const uuid = useId();
const currentKey = computed(
  (): string => props.id || props.title || props.href || uuid,
);
const currentPath = computed((): string[] => [
  ...parentPath.value,
  currentKey.value,
]);
const currentPathKey = computed((): string => currentPath.value.join('::'));

watch(
  [() => context?.value.activatedPathKey, currentPathKey],
  ([activatedPathKey, pathKey]) => {
    if (
      activatedPathKey === pathKey ||
      activatedPathKey?.startsWith(`${pathKey}::`)
    ) {
      open.value = true;
    }
  },
  { immediate: true },
);

const OptionComponent = computed((): Component | string =>
  props.href
    ? (props.anchorComponent ?? context?.value.optionsAnchorComponent ?? 'a')
    : 'div',
);

const isDiv = computed((): boolean => OptionComponent.value === 'div');

const resolved = computed((): { badge: VNode | null; items: VNode[] } => {
  let badge: VNode | null = null;
  const items: VNode[] = [];

  flattenChildren(slots.default?.()).forEach((child) => {
    if (child.type === MznBadge) {
      badge = child;
    } else if (child.type === MznNavigationOption) {
      items.push(child);
    } else {
      console.warn(
        '[Mezzanine][NavigationOption]: NavigationOption only accepts NavigationOption or Badge as children.',
      );
    }
  });

  return { badge, items };
});

/**
 * React branches on raw `children`, not on real sub-options, so a row carrying
 * only a badge still reads as a group here.
 */
const hasChildren = computed((): boolean => Boolean(slots.default));

const isActive = computed(
  (): boolean =>
    props.active ??
    context?.value.activatedPath?.[currentLevel.value - 1] === currentKey.value,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    open.value && classes.open,
    !hasChildren.value && classes.basic,
    isActive.value && classes.active,
  ),
);

function onTrigger(): void {
  open.value = !open.value;
  emit(
    'triggerClick',
    currentPath.value,
    currentKey.value,
    props.href,
    resolved.value.items,
  );

  if (!hasChildren.value) {
    context?.value.setActivatedPath(currentPath.value);
  }
}

function onKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    open.value = !open.value;

    if (!hasChildren.value) {
      context?.value.setActivatedPath(currentPath.value);
    }
  }
}

const OptionBadge: FunctionalComponent = () => resolved.value.badge;
</script>

<template>
  <li :class="hostClasses" :data-id="currentKey">
    <component
      :is="OptionComponent"
      :aria-expanded="hasChildren ? open : undefined"
      :class="classes.content"
      :href="href"
      :role="isDiv ? 'button' : undefined"
      :tabindex="0"
      @click="onTrigger"
      @keydown="onKeydown"
    >
      <MznIcon v-if="icon" :class="classes.icon" :icon="icon" />
      <span :class="classes.title">{{ title }}</span>
      <OptionBadge />
      <MznIcon
        v-if="hasChildren"
        :class="classes.toggleIcon"
        :icon="ChevronRightIcon"
      />
    </component>
  </li>
</template>
