// packages/ng/navigation/navigation-header.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { navigationHeaderClasses as classes } from '@mezzanine-ui/core/navigation';
import { SiderIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import {
  MZN_NAVIGATION_ACTIVATED,
  NavigationActivatedState,
} from './navigation-context';

/**
 * 導覽列標頭元件，含收合/展開切換按鈕與品牌區域。
 *
 * 透過 `title` 顯示導覽列名稱（收合時僅顯示第一個字元）。
 * 子內容（如 logo 圖示）透過 `<ng-content>` 插入品牌圖示區域。
 * `brandClick` 輸出可讓品牌區域具備點擊互動。
 *
 * @example
 * ```html
 * <header mznNavigationHeader title="My App">
 *   <img src="logo.svg" alt="Logo" />
 * </header>
 * ```
 *
 * @see MznNavigation
 */
@Component({
  selector: '[mznNavigationHeader]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon],
  host: {
    '[class]': 'hostClasses()',
    '[attr.title]': 'null',
  },
  template: `
    <button
      type="button"
      [class]="iconButtonClass"
      [attr.aria-label]="collapseToggleLabel()"
      [attr.aria-expanded]="!isCollapsed()"
      (click)="onToggleCollapse()"
    >
      <i mznIcon [icon]="siderIcon" [size]="16"></i>
    </button>
    <span [class]="contentClass" (click)="brandClick.emit()">
      <span [class]="childrenWrapperClass">
        <ng-content />
      </span>
      <span [class]="titleClass">{{ displayTitle() }}</span>
    </span>
  `,
})
export class MznNavigationHeader {
  private readonly navState = inject<NavigationActivatedState>(
    MZN_NAVIGATION_ACTIVATED,
    { optional: true },
  );

  protected readonly siderIcon = SiderIcon;
  protected readonly contentClass = classes.content;
  protected readonly childrenWrapperClass = classes.childrenWrapper;
  protected readonly titleClass = classes.title;
  protected readonly iconButtonClass = 'mzn-navigation-icon-button';

  /**
   * 導覽列標題文字。收合時僅顯示第一個字元。
   */
  readonly title = input<string>();

  /**
   * 收合／展開切換鍵的可及名稱。該鍵只畫一個圖示，這是螢幕閱讀器唯一唸得到的
   * 內容，請與介面其餘文案一起翻譯。
   * 對齊 React `NavigationHeader` 的 `collapseToggleLabel` prop。
   * @default 'Toggle navigation'
   */
  readonly collapseToggleLabel = input('Toggle navigation');

  /** 品牌區點擊事件。 */
  readonly brandClick = output<void>();

  protected readonly isCollapsed = computed(
    (): boolean => this.navState?.collapsed ?? false,
  );

  protected readonly displayTitle = computed((): string => {
    const t = this.title() ?? '';
    return this.isCollapsed() ? (t[0] ?? '') : t;
  });

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, {
      [classes.collapsed]: this.isCollapsed(),
      [classes.hasChildren]: true,
    }),
  );

  protected onToggleCollapse(): void {
    if (this.navState) {
      this.navState.handleCollapseChange(!this.navState.collapsed);
    }
  }
}

// packages/vue/navigation/navigation-header.vue
<script setup lang="ts">
import { computed, inject, useSlots } from 'vue';
import { navigationHeaderClasses as classes } from '@mezzanine-ui/core/navigation';
import { SiderIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import { useHasListener } from '../_internal/use-has-listener';
import MznFade from '../transition/fade.vue';
import MznNavigationIconButton from './navigation-icon-button.vue';
import { NAVIGATION_ACTIVATED_CONTEXT } from './navigation-context';
import type { NavigationHeaderProps } from './navigation-header.types';

/**
 * 側邊欄的頂部：收合切換鈕，加上品牌區塊。
 *
 * 收合時標題只留第一個字，slot 給的 logo 仍然留著。有人監聽 `brandClick` 時品牌
 * 區塊會變成按鈕，否則是純文字。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznNavigationHeader } from '@mezzanine-ui/vue/navigation';
 * <\/script>
 *
 * <template>
 *   <MznNavigationHeader title="Mezzanine"><span aria-label="logo" /></MznNavigationHeader>
 * </template>
 * ```
 *
 * @see MznNavigation 承載這個頂部的側邊欄
 */
const props = withDefaults(defineProps<NavigationHeaderProps>(), {
  collapseToggleLabel: 'Toggle navigation',
});

const emit = defineEmits<{
  /** Fired when the brand area is clicked. */
  brandClick: [];
}>();

defineSlots<{
  /** The logo shown next to the title. */
  default?: () => unknown;
}>();

const slots = useSlots();
const hasListener = useHasListener();

const context = inject(NAVIGATION_ACTIVATED_CONTEXT, undefined);

const collapsed = computed((): boolean => Boolean(context?.value.collapsed));

/**
 * A slot that renders only a `v-if` placeholder is React's `{false}`: written,
 * but not content.
 */
const hasChildren = computed(
  (): boolean => flattenChildren(slots.default?.()).length > 0,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    collapsed.value && classes.collapsed,
    hasChildren.value && classes.hasChildren,
  ),
);

const brandIsButton = computed((): boolean => hasListener('brandClick'));

const shownTitle = computed((): string | undefined =>
  collapsed.value ? props.title?.[0] : props.title,
);

function onToggle(): void {
  context?.value.handleCollapseChange(!collapsed.value);
}
</script>

<template>
  <header :class="hostClasses">
    <MznNavigationIconButton
      :aria-expanded="!collapsed"
      :aria-label="collapseToggleLabel"
      :icon="SiderIcon"
      @click="onToggle"
    />
    <component
      :is="brandIsButton ? 'button' : 'span'"
      :class="classes.content"
      :type="brandIsButton ? 'button' : undefined"
      @click="brandIsButton ? emit('brandClick') : undefined"
    >
      <span v-if="hasChildren" :class="classes.childrenWrapper">
        <slot />
      </span>

      <MznFade :in="!collapsed || !hasChildren">
        <span :class="classes.title">{{ shownTitle }}</span>
      </MznFade>
    </component>
  </header>
</template>
