// packages/react/src/Navigation/NavigationFooter.tsx
import {
  Children,
  CSSProperties,
  forwardRef,
  isValidElement,
  use,
  useEffect,
  useRef,
  useState,
} from 'react';
import { navigationFooterClasses as classes } from '@mezzanine-ui/core/navigation';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import NavigationUserMenu from './NavigationUserMenu';
import { NavigationActivatedContext } from './context';

export interface NavigationFooterProps
  extends NativeElementPropsWithoutKeyAndRef<'footer'> {
  /**
   * Children of footer, only `NavigationUserMenu` is allowed as direct child,
   * other children will be wrapped in an icons container.
   */
  children?: React.ReactNode;
}

const resolveChildren = (children: React.ReactNode) => {
  let userMenu: React.ReactNode = null;
  const otherChildren: React.ReactNode[] = [];

  Children.map(children, (child) => {
    if (isValidElement(child) && child.type === NavigationUserMenu) {
      userMenu = child;
    } else {
      otherChildren.push(child);
    }
  });

  return { userMenu, otherChildren };
};

const NavigationFooter = forwardRef<HTMLElement, NavigationFooterProps>(
  (props, ref) => {
    const { children, className, ...rest } = props;

    const { collapsed } = use(NavigationActivatedContext);

    const { userMenu, otherChildren } = resolveChildren(children);

    const iconsRef = useRef<HTMLSpanElement>(null);

    const [iconsWidth, setIconsWidth] = useState(0);

    useEffect(() => {
      if (!iconsRef.current) return;

      const resizeObserver = new ResizeObserver(() => {
        if (iconsRef.current) {
          setIconsWidth(iconsRef.current.offsetWidth);
        }
      });

      resizeObserver.observe(iconsRef.current);

      return () => {
        resizeObserver.disconnect();
      };
    }, []);

    return (
      <footer
        {...rest}
        ref={ref}
        className={cx(classes.host, collapsed && classes.collapsed, className)}
        style={
          {
            ['--icons-width']: `${iconsWidth}px`,
          } as CSSProperties
        }
      >
        {userMenu}
        <span ref={iconsRef} className={classes.icons}>
          {otherChildren}
        </span>
      </footer>
    );
  },
);

export default NavigationFooter;

// packages/vue/navigation/navigation-footer.vue
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, ref, useSlots, watch } from 'vue';
import type { CSSProperties, FunctionalComponent, VNode } from 'vue';
import { navigationFooterClasses as classes } from '@mezzanine-ui/core/navigation';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import { NAVIGATION_ACTIVATED_CONTEXT } from './navigation-context';
import MznNavigationUserMenu from './navigation-user-menu.vue';
import type { NavigationFooterProps } from './navigation-footer.types';

/**
 * 側邊欄的底部。
 *
 * 只有 MznNavigationUserMenu 會單獨排在前面，其餘子項一律收進圖示列。圖示列的
 * 寬度會量出來寫進 `--icons-width`，樣式靠它保留使用者名稱的空間。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznNavigationFooter, MznNavigationUserMenu } from '@mezzanine-ui/vue/navigation';
 * <\/script>
 *
 * <template>
 *   <MznNavigationFooter>
 *     <MznNavigationUserMenu :options="options">王小明</MznNavigationUserMenu>
 *   </MznNavigationFooter>
 * </template>
 * ```
 *
 * @see MznNavigation 承載這個底部的側邊欄
 */
defineProps<NavigationFooterProps>();

defineSlots<{
  /** The user menu, and whatever icon buttons go beside it. */
  default?: () => unknown;
}>();

const slots = useSlots();

const context = inject(NAVIGATION_ACTIVATED_CONTEXT, undefined);

const collapsed = computed((): boolean => Boolean(context?.value.collapsed));

const resolved = computed((): { others: VNode[]; userMenu: VNode | null } => {
  let userMenu: VNode | null = null;
  const others: VNode[] = [];

  flattenChildren(slots.default?.()).forEach((child) => {
    if (child.type === MznNavigationUserMenu) userMenu = child;
    else others.push(child);
  });

  return { others, userMenu };
});

const icons = ref<HTMLSpanElement | null>(null);
const iconsWidth = ref(0);

let resizeObserver: ResizeObserver | null = null;

watch(
  icons,
  (element) => {
    resizeObserver?.disconnect();
    resizeObserver = null;

    if (!element) return;

    resizeObserver = new ResizeObserver(() => {
      if (icons.value) iconsWidth.value = icons.value.offsetWidth;
    });

    resizeObserver.observe(element);
  },
  { flush: 'post', immediate: true },
);

onBeforeUnmount(() => resizeObserver?.disconnect());

const hostClasses = computed((): string =>
  clsx(classes.host, collapsed.value && classes.collapsed),
);

const hostStyle = computed(
  (): CSSProperties =>
    ({ '--icons-width': `${iconsWidth.value}px` }) as CSSProperties,
);

const UserMenu: FunctionalComponent = () => resolved.value.userMenu;
const OtherChildren: FunctionalComponent = () => resolved.value.others;
</script>

<template>
  <footer :class="hostClasses" :style="hostStyle">
    <UserMenu />
    <span ref="icons" :class="classes.icons"><OtherChildren /></span>
  </footer>
</template>
