// packages/react/src/PageFooter/PageFooter.tsx
import { forwardRef } from 'react';
import { pageFooterClasses as classes } from '@mezzanine-ui/core/page-footer';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import type { ButtonProps } from '../Button';
import Button, { ButtonGroup } from '../Button';
import Typography from '../Typography';
import Dropdown, { DropdownProps } from '../Dropdown';
import { DotVerticalIcon } from '@mezzanine-ui/icons';

/**
 * Single button configuration - only primary button is allowed
 */
type SingleButtonAction = {
  secondaryButton?: never;
  primaryButton: ButtonProps;
};

/**
 * Two buttons configuration - both secondary and primary buttons
 */
type TwoButtonsAction = {
  secondaryButton: ButtonProps;
  primaryButton: ButtonProps;
};

/**
 * Actions can be either single button or two buttons
 */
export type PageFooterActions = SingleButtonAction | TwoButtonsAction;

export type PageFooterType = 'standard' | 'overflow' | 'information';

type PageFooterBaseProps = NativeElementPropsWithoutKeyAndRef<'footer'> & {
  /**
   * Action buttons configuration for primary and secondary actions.
   * Renders buttons in the order: secondary (left), primary (right).
   */
  actions?: PageFooterActions;
  /**
   * The className of annotation wrapper.
   */
  annotationClassName?: string;
  /**
   * The warning message in the middle.
   */
  warningMessage?: string;
};

type PageFooterStandardProps = PageFooterBaseProps & {
  /**
   * The type of PageFooter annotation.
   * @default 'standard'
   */
  type?: 'standard';
  /**
   * The supporting action name of PageFooter annotation.
   */
  supportingActionName?: ButtonProps['children'];
  /**
   * The supporting action type of PageFooter annotation.
   */
  supportingActionType?: ButtonProps['type'];
  /**
   * The supporting action onClick of PageFooter annotation.
   */
  supportingActionOnClick?: ButtonProps['onClick'];
  /**
   * The supporting action variant of PageFooter annotation.
   * @default 'base-ghost'
   */
  supportingActionVariant?: ButtonProps['variant'];
};

type PageFooterOverflowProps = PageFooterBaseProps & {
  /**
   * The type of PageFooter annotation.
   */
  type: 'overflow';
  /**
   * Overflow type: Icon for the icon-only button.
   * @default DotVerticalIcon
   */
  supportingActionIcon?: ButtonProps['icon'];
  /**
   * Dropdown props for the annotation button.
   */
  dropdownProps: Partial<DropdownProps>;
};

type PageFooterInformationProps = PageFooterBaseProps & {
  /**
   * The type of PageFooter annotation.
   */
  type: 'information';
  /**
   * Information type: Plain text to display.
   */
  annotation?: string;
};

export type PageFooterProps =
  | PageFooterStandardProps
  | PageFooterOverflowProps
  | PageFooterInformationProps;

const PageFooter = forwardRef<HTMLElement, PageFooterProps>(
  function PageFooter(props, ref) {
    const {
      actions,
      annotationClassName,
      className,
      type = 'standard',
      warningMessage,
      ...rest
    } = props;

    // Filter out onAnnotationClick from rest props to avoid React warnings
    if ('onAnnotationClick' in rest) {
      delete rest.onAnnotationClick;
    }

    const { children: primaryButtonText, ...restPrimaryButtonProps } =
      actions?.primaryButton ?? {};

    // Render annotation based on type
    const renderAnnotation = () => {
      switch (type) {
        case 'standard': {
          const {
            supportingActionName,
            supportingActionType,
            supportingActionOnClick,
            supportingActionVariant = 'base-ghost',
          } = props as PageFooterStandardProps;

          return (
            <Button
              size="main"
              type={supportingActionType}
              onClick={supportingActionOnClick}
              variant={supportingActionVariant}
            >
              {supportingActionName}
            </Button>
          );
        }

        case 'overflow': {
          const { supportingActionIcon, dropdownProps } =
            props as PageFooterOverflowProps;

          return (
            <Dropdown
              {...dropdownProps}
              maxHeight={dropdownProps.maxHeight}
              onSelect={dropdownProps.onSelect}
              options={dropdownProps.options || []}
              placement={dropdownProps.placement || 'top'}
            >
              <Button
                type="button"
                iconType="icon-only"
                icon={supportingActionIcon || DotVerticalIcon}
                size="main"
                variant="base-ghost"
              />
            </Dropdown>
          );
        }

        case 'information': {
          const { annotation } = props as PageFooterInformationProps;
          if (!annotation) return null;

          return (
            <Typography color="text-neutral" variant="caption">
              {annotation as string}
            </Typography>
          );
        }

        default:
          return null;
      }
    };

    return (
      <footer ref={ref} {...rest} className={cx(classes.host, className)}>
        <div className={cx(classes.annotation, annotationClassName)}>
          {renderAnnotation()}
        </div>
        <div className={classes.message}>
          {warningMessage ? (
            <Typography variant="caption" color="text-warning" align="right">
              {warningMessage}
            </Typography>
          ) : null}
        </div>
        <ButtonGroup>
          {actions?.secondaryButton && (
            <Button
              size="main"
              variant="base-secondary"
              {...actions.secondaryButton}
            />
          )}
          <Button
            size="main"
            variant="base-primary"
            {...restPrimaryButtonProps}
          >
            {primaryButtonText || 'Button'}
          </Button>
        </ButtonGroup>
      </footer>
    );
  },
);

export default PageFooter;

// packages/vue/page-footer/page-footer.vue
<script setup lang="ts">
import { computed } from 'vue';
import { pageFooterClasses as classes } from '@mezzanine-ui/core/page-footer';
import { DotHorizontalIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import MznButtonGroup from '../button/button-group.vue';
import MznDropdown from '../dropdown/dropdown.vue';
import MznTypography from '../typography/typography.vue';
import type { PageFooterProps } from './page-footer.types';

/**
 * 頁面底部的操作列，右側放主要與次要按鈕，左側放一份補充內容。
 *
 * `type` 決定左側放什麼 —— `standard` 是一顆文字按鈕、`overflow` 是一顆開啟
 * 下拉選單的圖示按鈕、`information` 是一段說明文字。中間可放一句警告訊息，
 * 右側的按鈕由 `actions` 以資料形式給定。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznPageFooter } from '@mezzanine-ui/vue/page-footer';
 * <\/script>
 *
 * <template>
 *   <MznPageFooter
 *     :actions="{ primaryButton: { children: '發佈' }, secondaryButton: { children: '儲存草稿' } }"
 *     supporting-action-name="查看發佈紀錄"
 *   />
 *
 *   <MznPageFooter
 *     annotation="發佈後將無法編輯"
 *     :actions="{ primaryButton: { children: '發佈' } }"
 *     type="information"
 *   />
 * </template>
 * ```
 *
 * @see MznPageHeader 對應的頁首
 */
const props = withDefaults(defineProps<PageFooterProps>(), {
  actions: undefined,
  annotation: undefined,
  annotationClassName: undefined,
  dropdownProps: undefined,
  supportingActionIcon: undefined,
  supportingActionName: undefined,
  supportingActionOnClick: undefined,
  supportingActionType: undefined,
  supportingActionVariant: 'base-ghost',
  type: 'standard',
  warningMessage: undefined,
});

const annotationClasses = computed((): string =>
  clsx(classes.annotation, props.annotationClassName),
);

const dropdownBindings = computed(() => ({
  ...props.dropdownProps,
  options: props.dropdownProps?.options || [],
  placement: props.dropdownProps?.placement || 'top',
}));

/**
 * `children` is pulled out of the spread and rendered as the slot: React's
 * `children` becomes the button's content, while a Vue `v-bind` would leave it
 * on the element as an attribute nobody asked for.
 */
const secondaryButtonBindings = computed(() => {
  const { children: _children, ...rest } = props.actions?.secondaryButton ?? {};

  return { size: 'main' as const, variant: 'base-secondary' as const, ...rest };
});

const primaryButtonBindings = computed(() => {
  const { children: _children, ...rest } = props.actions?.primaryButton ?? {};

  return { size: 'main' as const, variant: 'base-primary' as const, ...rest };
});

const hostClass = classes.host;
const messageClass = classes.message;
</script>

<template>
  <footer :class="hostClass">
    <div :class="annotationClasses">
      <MznButton
        v-if="type === 'standard' && supportingActionName"
        size="main"
        :type="supportingActionType"
        :variant="supportingActionVariant"
        @click="supportingActionOnClick"
      >
        <component :is="() => supportingActionName" />
      </MznButton>
      <MznDropdown
        v-else-if="type === 'overflow' && dropdownProps"
        v-bind="dropdownBindings"
      >
        <template #default="triggerProps">
          <MznButton
            v-bind="triggerProps"
            type="button"
            icon-type="icon-only"
            :icon="supportingActionIcon || DotHorizontalIcon"
            size="main"
            variant="base-ghost"
          />
        </template>
      </MznDropdown>
      <MznTypography
        v-else-if="type === 'information' && annotation"
        color="text-neutral"
        variant="caption"
      >
        {{ annotation }}
      </MznTypography>
    </div>
    <div :class="messageClass">
      <MznTypography
        v-if="warningMessage"
        align="right"
        color="text-warning"
        variant="caption"
      >
        {{ warningMessage }}
      </MznTypography>
    </div>
    <MznButtonGroup>
      <MznButton
        v-if="actions?.secondaryButton"
        v-bind="secondaryButtonBindings"
      >
        <component :is="() => actions?.secondaryButton?.children" />
      </MznButton>
      <MznButton v-if="actions?.primaryButton" v-bind="primaryButtonBindings">
        <component :is="() => actions?.primaryButton?.children" />
      </MznButton>
    </MznButtonGroup>
  </footer>
</template>
