// packages/vue/breadcrumb/breadcrumb-overflow-menu-item.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { Component } from 'vue';
import { breadcrumbOverflowMenuItemClasses as classes } from '@mezzanine-ui/core/breadcrumb';
import clsx from 'clsx';
import MznTypography from '../typography/typography.vue';
import MznBreadcrumbOverflowMenuDropdown from './breadcrumb-overflow-menu-dropdown.vue';
import type { BreadcrumbItemProps } from './breadcrumb-item.types';

/**
 * 收合選單裡的一列。與 MznBreadcrumbItem 同樣依 `options`、`href` 與是否有
 * click 監聽決定渲染成下拉、連結還是純文字，但文字一律用 label 樣式。
 *
 * @see MznBreadcrumbOverflowMenu 收納它們的選單
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<BreadcrumbItemProps>(), {
  component: undefined,
  current: undefined,
  href: undefined,
  target: undefined,
});

const attrs = useAttrs();

const isDropdown = computed((): boolean => props.options !== undefined);

const triggerComponent = computed((): Component | string => {
  if (props.component) return props.component;

  if (
    (!props.current && typeof props.href === 'string') ||
    attrs.onClick !== undefined
  ) {
    return 'a';
  }

  return 'span';
});

const isAnchor = computed((): boolean => triggerComponent.value === 'a');

const hostClasses = computed((): string =>
  clsx(classes.host, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, onClick: _onClick, rel: _rel, ...rest } = attrs;

  return rest;
});

const triggerBindings = computed(() => ({
  class: classes.trigger,
  href: isAnchor.value ? props.href : undefined,
  onClick: isAnchor.value
    ? (attrs.onClick as (() => void) | undefined)
    : undefined,
  rel: isAnchor.value ? (attrs.rel as string | undefined) : undefined,
  target: isAnchor.value ? props.target : undefined,
}));
</script>

<template>
  <MznBreadcrumbOverflowMenuDropdown
    v-if="isDropdown"
    v-bind="{ ...props, ...attrs }"
  />
  <span v-else v-bind="forwardedAttrs" :class="hostClasses" :id="id">
    <component :is="triggerComponent" v-bind="triggerBindings">
      <MznTypography variant="label-primary">{{ name }}</MznTypography>
    </component>
  </span>
</template>

// packages/react/src/Breadcrumb/BreadcrumbOverflowMenuItem.tsx
import { forwardRef } from 'react';
import { breadcrumbOverflowMenuItemClasses as classes } from '@mezzanine-ui/core/breadcrumb';
import { cx } from '../utils/cx';
import Typography from '../Typography';
import type { BreadcrumbItemProps } from './typings';
import BreadcrumbOverflowMenuDropdown from './BreadcrumbOverflowMenuDropdown';

const BreadcrumbOverflowMenuItem = forwardRef<
  HTMLSpanElement,
  BreadcrumbItemProps
>(function BreadcrumbOverflowMenuItem(props, ref) {
  if ('options' in props) return <BreadcrumbOverflowMenuDropdown {...props} />;

  const {
    className,
    component,
    current,
    href,
    name,
    onClick,
    rel,
    target,
    ...rest
  } = props;

  const TriggerComponent = (() => {
    if (component) return component;

    if (
      (!current && 'href' in props && typeof props.href === 'string') ||
      'onClick' in props
    ) {
      return 'a';
    }

    return 'span';
  })();

  const handleClick = () => {
    onClick?.();
  };

  return (
    <span {...rest} className={cx(classes.host, className)} ref={ref}>
      <TriggerComponent
        className={cx(classes.trigger)}
        href={TriggerComponent === 'a' ? href : undefined}
        onClick={TriggerComponent === 'a' ? handleClick : undefined}
        rel={TriggerComponent === 'a' ? rel : undefined}
        target={TriggerComponent === 'a' ? target : undefined}
      >
        <Typography variant={'label-primary'}>{name}</Typography>
      </TriggerComponent>
    </span>
  );
});

export default BreadcrumbOverflowMenuItem;
