// packages/react/src/FilterArea/FilterLine.tsx
'use client';

import { forwardRef, ReactElement, useMemo } from 'react';

import { filterAreaClasses as classes } from '@mezzanine-ui/core/filter-area';

import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

import { FilterProps } from './Filter';

export interface FilterLineProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'> {
  /**
   * The content of the filter line, must be Filter component(s).
   */
  children: ReactElement<FilterProps> | ReactElement<FilterProps>[];
}

/**
 * 篩選器中的單行條件列，包含一或多個 Filter 欄位。
 *
 * 透過 Grid 排版將 Filter 子元件橫向排列；
 * 需作為 FilterArea 的直接子元件使用。
 *
 * @example
 * ```tsx
 * import { Filter, FilterLine } from '@mezzanine-ui/react';
 *
 * <FilterLine>
 *   <Filter span={2}>...</Filter>
 *   <Filter span={3}>...</Filter>
 * </FilterLine>
 * ```
 *
 * @see {@link FilterArea} 管理多個 FilterLine 的容器元件
 * @see {@link Filter} 包裝單一篩選欄位的元件
 */
const FilterLine = forwardRef<HTMLDivElement, FilterLineProps>(
  function FilterLine(props, ref) {
    const { className, children, ...rest } = props;

    const lineClassName = useMemo(
      () => cx(classes.line, className),
      [className],
    );

    return (
      <div {...rest} ref={ref} className={lineClassName}>
        {children}
      </div>
    );
  },
);

export default FilterLine;

// packages/ng/filter-area/filter-line.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
} from '@angular/core';
import { filterAreaClasses as classes } from '@mezzanine-ui/core/filter-area';
import { MZN_FILTER_AREA_CONTEXT } from './filter-area-context';

/**
 * 篩選器中的單行條件列，包含一或多個 MznFilter 欄位。
 *
 * 透過 Grid 排版將 MznFilter 子元件橫向排列；
 * 需作為 MznFilterArea 的直接子元件使用。
 * 非第一行的 FilterLine 在 FilterArea 收合時會自動隱藏。
 *
 * @example
 * ```html
 * import { MznFilterLine, MznFilter } from '@mezzanine-ui/ng/filter-area';
 *
 * <mzn-filter-line>
 *   <mzn-filter [span]="2">...</mzn-filter>
 *   <mzn-filter [span]="3">...</mzn-filter>
 * </mzn-filter-line>
 * ```
 *
 * @see {@link MznFilterArea} 管理多個 MznFilterLine 的容器元件
 * @see {@link MznFilter} 包裝單一篩選欄位的元件
 */
@Component({
  selector: 'mzn-filter-line',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
    '[style.display]': 'hostDisplay()',
  },
  template: '<ng-content />',
})
export class MznFilterLine {
  private readonly context = inject(MZN_FILTER_AREA_CONTEXT, {
    optional: true,
  });

  private readonly elRef = inject(ElementRef<HTMLElement>);

  protected readonly hostClass = classes.line;

  /**
   * 判斷是否為第一個 mzn-filter-line 子元件。
   * 透過檢查前方是否有同名兄弟元素來判斷，避免依賴 contentChildren signal。
   */
  private isFirstLine(): boolean {
    const el = this.elRef.nativeElement;
    let sibling = el.previousElementSibling;

    while (sibling) {
      if (sibling.tagName.toLowerCase() === 'mzn-filter-line') {
        return false;
      }

      sibling = sibling.previousElementSibling;
    }

    return true;
  }

  protected readonly hostDisplay = computed((): string | null => {
    const ctx = this.context;

    if (!ctx) return null;

    const isFirst = this.isFirstLine();
    const expanded = ctx.expanded();

    return !isFirst && !expanded ? 'none' : null;
  });
}
