// packages/react/src/Input/Input.tsx
'use client';

import { DropdownOption } from '@mezzanine-ui/core/dropdown';
import { inputClasses as classes } from '@mezzanine-ui/core/input';
import { textFieldClasses } from '@mezzanine-ui/core/text-field';
import { EyeIcon, EyeInvisibleIcon, SearchIcon } from '@mezzanine-ui/icons';
import {
  ChangeEventHandler,
  forwardRef,
  KeyboardEventHandler,
  MouseEventHandler,
  ReactNode,
  Ref,
  useCallback,
  useMemo,
  useRef,
  useState,
} from 'react';
import { useInputWithClearControlValue } from '../Form/useInputWithClearControlValue';
import { useComposeRefs } from '../hooks/useComposeRefs';
import Icon from '../Icon';
import { PopperPlacement } from '../Popper';
import TextField, {
  TextFieldAffixProps,
  TextFieldInteractiveStateProps,
  TextFieldProps,
} from '../TextField';
import { cx } from '../utils/cx';
import { formatNumberWithCommas } from '../utils/format-number-with-commas';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { parseNumberWithCommas } from '../utils/parse-number-with-commas';
import ActionButton, { ActionButtonProps } from './ActionButton';
import PasswordStrengthIndicator, {
  PasswordStrengthIndicatorProps,
} from './PasswordStrengthIndicator';
import SelectButton, { SelectButtonProps } from './SelectButton';
import SpinnerButton from './SpinnerButton';

/**
 * Base props shared by all Input variants
 */
export interface InputBaseProps
  extends Omit<
    TextFieldProps,
    'children' | 'clearable' | 'onClear' | 'prefix' | 'suffix'
  > {
  /**
   * The default value of input.
   */
  defaultValue?: string;
  /**
   * Formatter function to transform the value for display.
   * Common use cases: measure formatting (1000 → "1,000"), phone numbers, etc.
   * Default to formatting number with commas for "measure" variant.
   * @example
   * formatter={(value) => value.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
   */
  formatter?: (value: string) => string;
  /**
   * The id of input element.
   */
  id?: string;
  /**
   * The react ref passed to input element.
   */
  inputRef?: Ref<HTMLInputElement>;
  /**
   * The other native props for input element.
   */
  inputProps?: Omit<
    NativeElementPropsWithoutKeyAndRef<'input'>,
    | 'defaultValue'
    | 'disabled'
    | 'onChange'
    | 'placeholder'
    | 'readOnly'
    | 'value'
    | 'type'
    | 'id'
    | 'name'
    | `aria-${'disabled' | 'multiline' | 'readonly'}`
  >;
  /**
   * The input type of input element.
   * @default 'text'
   */
  inputType?: NativeElementPropsWithoutKeyAndRef<'input'>['type'];
  /**
   * The name of input element.
   */
  name?: string;
  /**
   * The change event handler of input element.
   */
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * Parser function to extract the raw value from formatted display value.
   * Should reverse the formatter transformation.
   * Default to removing commas for "measure" formatting.
   * @example
   * parser={(value) => value.replace(/,/g, '')}
   */
  parser?: (value: string) => string;
  /**
   * The placeholder of input.
   */
  placeholder?: string;
  /**
   * The value of input.
   */
  value?: string;
}

/**
 * Clearable props
 */
export type ClearableInput = Pick<TextFieldProps, 'clearable' | 'onClear'>;

/**
 * Number input
 */
export type NumberInput = {
  /**
   * The minimum value.
   */
  min?: number;
  /**
   * The maximum value.
   */
  max?: number;
  /**
   * The step value.
   * @default 1
   */
  step?: number;
};

/**
 * 1. Base Input - Basic input field
 */
export type BaseInputProps = InputBaseProps &
  ClearableInput & {
    /**
     * The type of input.
     * @default 'base'
     */
    variant?: 'base';
  };

/**
 * 2. With Affix Input - Input with prefix/suffix decorations
 */
export type WithAffixInputProps = InputBaseProps &
  TextFieldAffixProps &
  ClearableInput & {
    variant: 'affix';
  };

/**
 * 3. Search Input - Input with search icon prefix
 */
export type SearchInputProps = InputBaseProps &
  ClearableInput & {
    variant: 'search';
  };

/**
 * 4. Number Input - Small numeric input (36x36)
 */
export type NumberInputProps = InputBaseProps &
  NumberInput & {
    variant: 'number';
  };

/**
 * 5. Measure Input - Input with unit text and spinner buttons
 */
export type MeasureInputProps = InputBaseProps &
  NumberInput &
  TextFieldAffixProps & {
    variant: 'measure';
    /**
     * Whether to show spinner buttons.
     * @default false
     */
    showSpinner?: boolean;
    /**
     * Callback when spinner up button is clicked.
     */
    onSpinUp?: VoidFunction;
    /**
     * Callback when spinner down button is clicked.
     */
    onSpinDown?: VoidFunction;
  };

/**
 * 6. Action Input - Input with action button (button is adjacent to TextField, not inside)
 */
export type ActionInputProps = InputBaseProps & {
  variant: 'action';
  /**
   * The action button props.
   */
  actionButton: ActionButtonProps & {
    position: 'prefix' | 'suffix';
  };
};

/**
 * 7. Select Input - Input with select button (button is adjacent to TextField, not inside)
 */
export type SelectInputProps = InputBaseProps & {
  variant: 'select';
  /**
   * The select button props.
   */
  selectButton: SelectButtonProps & {
    position: 'prefix' | 'suffix' | 'both';
  };
  /**
   * The options of the dropdown.
   */
  options?: DropdownOption[];
  /**
   * The selected value of the dropdown.
   */
  selectedValue?: string;
  /**
   * The onChange event handler of the dropdown.
   */
  onSelect?: (value: string) => void;
  /**
   * The width of the dropdown.
   */
  dropdownWidth?: number | string;
  /**
   * The max height of the dropdown.
   */
  dropdownMaxHeight?: number | string;
  /**
   * The placement of the dropdown.
   */
  dropdownPlacement?: PopperPlacement;
};

/**
 * 8. Password Input - Password input with visibility toggle
 */
export type WithPasswordStrengthIndicator =
  | {
      /**
       * Whether to show password strength indicator.
       */
      showPasswordStrengthIndicator?: false;
      passwordStrengthIndicator?: never;
    }
  | {
      /**
       * Whether to show password strength indicator.
       */
      showPasswordStrengthIndicator: true;
      /**
       * The props for password strength indicator.
       */
      passwordStrengthIndicator: PasswordStrengthIndicatorProps;
    };

export type PasswordInputProps = InputBaseProps &
  ClearableInput &
  WithPasswordStrengthIndicator & {
    variant: 'password';
  };

export type InputProps =
  | BaseInputProps
  | WithAffixInputProps
  | SearchInputProps
  | NumberInputProps
  | MeasureInputProps
  | ActionInputProps
  | SelectInputProps
  | PasswordInputProps;

/**
 * 多功能輸入框元件，透過 `variant` 支援多種輸入類型。
 *
 * 支援以下八種 variant：`base`（基本輸入）、`affix`（帶前後綴裝飾）、`search`（搜尋，預設帶清除鍵）、
 * `number`（原生數字輸入）、`measure`（格式化數字，可選轉盤按鈕）、`action`（帶操作按鈕）、
 * `select`（帶下拉選單按鈕）、`password`（密碼，可切換可見性並顯示強度指示器）。
 * `measure` variant 會自動以千分位格式化顯示值，並在 `onChange` 時回傳原始數值。
 *
 * @example
 * ```tsx
 * import Input from '@mezzanine-ui/react/Input';
 *
 * // 基本輸入（可清除）
 * <Input variant="base" clearable placeholder="請輸入文字" />
 *
 * // 搜尋輸入
 * <Input variant="search" placeholder="搜尋關鍵字" />
 *
 * // 密碼輸入（含強度指示器）
 * <Input
 *   variant="password"
 *   placeholder="請輸入密碼"
 *   showPasswordStrengthIndicator
 *   passwordStrengthIndicator={{ strength: 2 }}
 * />
 *
 * // 數字計量輸入（含轉盤按鈕）
 * <Input variant="measure" suffix="px" showSpinner min={0} max={100} />
 * ```
 *
 * @see {@link FormField} 用於包裹 Input 並提供標籤與錯誤訊息
 * @see {@link TextField} Input 底層使用的文字框容器元件
 */
const Input = forwardRef<HTMLDivElement, InputProps>(
  function Input(props, ref) {
    const {
      active,
      className,
      defaultValue,
      disabled = false,
      error = false,
      formatter: formatterProp,
      fullWidth = true,
      id,
      inputProps,
      inputType,
      inputRef: inputRefProp,
      name,
      onChange: onChangeProp,
      parser: parserProp,
      placeholder,
      readonly,
      size = 'main',
      typing,
      variant = 'base',
      value: valueProp,
    } = props;

    const inputRef = useRef<HTMLInputElement>(null);
    const [showPassword, setShowPassword] = useState(false);

    const [value, onChange, onClearFromHook] = useInputWithClearControlValue({
      defaultValue,
      onChange: onChangeProp,
      ref: inputRef,
      value: valueProp,
    });

    // Handle formatter/parser logic
    const formatter = useMemo(() => {
      if (formatterProp) return formatterProp;

      if (variant === 'measure') {
        return (value: string) => formatNumberWithCommas(value);
      }

      return undefined;
    }, [formatterProp, variant]);

    const parser = useMemo(() => {
      if (parserProp) return parserProp;

      if (variant === 'measure') {
        return (value: string) =>
          parseNumberWithCommas(value)?.toString() ?? '';
      }

      return undefined;
    }, [parserProp, variant]);

    const handleChange: ChangeEventHandler<HTMLInputElement> = useCallback(
      (event) => {
        let newValue = event.target.value;

        // Parse the formatted value back to raw value if parser is provided
        if (parser) {
          newValue = parser(newValue);
        }

        // Create a new event with parsed value for onChange callback
        const syntheticEvent = {
          ...event,
          target: {
            ...event.target,
            value: newValue,
          },
        } as React.ChangeEvent<HTMLInputElement>;

        onChange(syntheticEvent);
      },
      [parser, onChange],
    );

    // Format the display value
    const displayValue = formatter ? formatter(value) : value;

    const composedInputRef = useComposeRefs([inputRefProp, inputRef]);

    // Determine input type and props based on variant
    let defaultInputType: string = 'text';
    let prefix: ReactNode = undefined;
    let suffix: ReactNode = undefined;
    let clearable = false;
    let onClear: MouseEventHandler | undefined = undefined;
    let inputStyle: React.CSSProperties = {};
    let defaultInputProps: Omit<
      React.InputHTMLAttributes<HTMLInputElement>,
      | 'type'
      | 'style'
      | 'onChange'
      | 'value'
      | 'placeholder'
      | 'disabled'
      | 'readOnly'
    > = {};
    let prefixExternalButton: ReactNode = undefined;
    let suffixExternalButton: ReactNode = undefined;
    let showPasswordStrengthIndicator: boolean = false;
    let passwordStrengthIndicatorProps:
      | PasswordStrengthIndicatorProps
      | undefined = undefined;
    let hasSpinner: boolean = false;

    // Handle different input types with type narrowing
    switch (variant) {
      case 'base': {
        const baseProps = props as BaseInputProps;

        if (baseProps.clearable) {
          clearable = baseProps.clearable;
          onClear = baseProps.onClear || onClearFromHook;
        }

        break;
      }
      case 'affix': {
        const affixProps = props as WithAffixInputProps;

        if (affixProps.clearable) {
          clearable = affixProps.clearable;
          onClear = affixProps.onClear || onClearFromHook;
        }

        prefix = affixProps.prefix;
        suffix = affixProps.suffix;

        break;
      }
      case 'search': {
        const searchProps = props as SearchInputProps;

        // 預設為可清除
        clearable =
          typeof searchProps.clearable !== 'undefined'
            ? searchProps.clearable
            : true;

        if (clearable) {
          onClear = searchProps.onClear || onClearFromHook;
        }

        // 預設有 search icon 在前綴
        prefix = <Icon icon={SearchIcon} />;

        break;
      }
      case 'number': {
        const numberProps = props as NumberInputProps;
        const { step = 1, max, min } = numberProps;

        // Input type 應是 number
        defaultInputType = 'number';
        // 額外的屬性
        defaultInputProps = {
          min: min,
          max: max,
          step: step,
        };

        break;
      }
      case 'measure': {
        // 需注意 input type 不應是 number，因為要允許輸入格式化後的字串（例如 1,000）
        const measureProps = props as MeasureInputProps;
        const { step = 1, max, min, onSpinUp, onSpinDown } = measureProps;

        // 預設置右對齊
        inputStyle = { textAlign: 'right' };
        // 允許填入 prefix/suffix
        prefix = measureProps.prefix;
        suffix = measureProps.suffix;

        defaultInputProps = {
          min: min,
          max: max,
          step: step,
        };

        if (measureProps.showSpinner) {
          hasSpinner = true;

          const handleSpinUp = () => {
            const currentValue = parseFloat(value || '0');
            const newValue = currentValue + step;

            if (typeof max === 'undefined' || newValue <= max) {
              onChange({
                target: { value: String(newValue) },
              } as React.ChangeEvent<HTMLInputElement>);
            }

            onSpinUp?.();
          };

          const handleSpinDown = () => {
            const currentValue = parseFloat(value || '0');
            const newValue = currentValue - step;

            if (typeof min === 'undefined' || newValue >= min) {
              onChange({
                target: { value: String(newValue) },
              } as React.ChangeEvent<HTMLInputElement>);
            }

            onSpinDown?.();
          };

          suffix = (
            <>
              {measureProps.suffix}
              <div className={classes.spinners}>
                <SpinnerButton
                  type="up"
                  size={size}
                  disabled={disabled}
                  onClick={handleSpinUp}
                />
                <SpinnerButton
                  type="down"
                  size={size}
                  disabled={disabled}
                  onClick={handleSpinDown}
                />
              </div>
            </>
          );
        } else {
          hasSpinner = false;
        }

        break;
      }
      case 'action': {
        const actionProps = props as ActionInputProps;
        const { actionButton } = actionProps;

        if (actionButton.position === 'prefix') {
          const { ...restActionButtonProps } = actionButton;

          const actionDisabled =
            typeof restActionButtonProps.disabled === 'boolean'
              ? restActionButtonProps.disabled
              : disabled || readonly;

          prefixExternalButton = (
            <ActionButton
              {...restActionButtonProps}
              disabled={actionDisabled}
              size={size}
            />
          );
        }

        if (actionButton.position === 'suffix') {
          const { ...restActionButtonProps } = actionButton;

          const actionDisabled =
            typeof restActionButtonProps.disabled === 'boolean'
              ? restActionButtonProps.disabled
              : disabled || readonly;

          suffixExternalButton = (
            <ActionButton
              {...restActionButtonProps}
              disabled={actionDisabled}
              size={size}
            />
          );
        }

        break;
      }
      case 'select': {
        const selectProps = props as SelectInputProps;
        const {
          selectButton,
          options,
          dropdownWidth = 120,
          dropdownMaxHeight = 114,
          dropdownPlacement = 'bottom-start',
        } = selectProps;

        if (
          selectButton.position === 'both' ||
          selectButton.position === 'prefix'
        ) {
          const { ...restSelectButtonProps } = selectButton;

          prefixExternalButton = (
            <SelectButton
              {...restSelectButtonProps}
              disabled={restSelectButtonProps.disabled || disabled}
              dropdownMaxHeight={dropdownMaxHeight}
              dropdownPlacement={dropdownPlacement}
              dropdownWidth={dropdownWidth}
              onSelect={selectProps.onSelect}
              options={options}
              size={size}
            />
          );
        }

        if (
          selectButton.position === 'both' ||
          selectButton.position === 'suffix'
        ) {
          const { ...restSelectButtonProps } = selectButton;

          suffixExternalButton = (
            <SelectButton
              {...restSelectButtonProps}
              disabled={restSelectButtonProps.disabled || disabled}
              dropdownMaxHeight={dropdownMaxHeight}
              dropdownPlacement={dropdownPlacement}
              dropdownWidth={dropdownWidth}
              onSelect={selectProps.onSelect}
              options={options}
              size={size}
            />
          );
        }

        break;
      }
      case 'password': {
        const passwordProps = props as PasswordInputProps;
        defaultInputType = showPassword ? 'text' : 'password';

        if (passwordProps.clearable) {
          onClear = passwordProps.onClear || onClearFromHook;
        }

        const handlePasswordToggle: KeyboardEventHandler<HTMLElement> = (
          event,
        ) => {
          if (event.key === 'Enter' || event.key === ' ') {
            event.preventDefault();
            setShowPassword((prev) => !prev);
          }
        };

        suffix = (
          <Icon
            icon={showPassword ? EyeIcon : EyeInvisibleIcon}
            onClick={() => setShowPassword((prev) => !prev)}
            role="button"
            tabIndex={0}
            aria-label={showPassword ? 'Hide password' : 'Show password'}
            onKeyDown={handlePasswordToggle}
          />
        );

        if (passwordProps.showPasswordStrengthIndicator) {
          showPasswordStrengthIndicator = true;
          passwordStrengthIndicatorProps =
            passwordProps.passwordStrengthIndicator;
        }

        break;
      }

      default:
        break;
    }

    const interactiveProps: TextFieldInteractiveStateProps = (() => {
      if (disabled) {
        return { disabled: true };
      }
      if (readonly) {
        return { readonly: true };
      }
      if (typing) {
        return { typing: true };
      }
      return {};
    })();

    return (
      <div ref={ref} className={cx(classes.container, className)}>
        <div
          className={cx(classes.host, {
            [classes.number]: variant === 'number',
            [classes.passwordInput]: variant === 'password',
            [classes.withPrefixExternalAction]:
              prefixExternalButton !== undefined,
            [classes.withSuffixExternalAction]:
              suffixExternalButton !== undefined,
            [classes.searchInput]: variant === 'search',
            [classes.measureWithSpinner]: variant === 'measure' && hasSpinner,
            [classes.measureWithoutSpinner]:
              variant === 'measure' && !hasSpinner,
          })}
        >
          {prefixExternalButton}
          <TextField
            active={active}
            className={cx(
              classes.field,
              {
                [classes.number]: variant === 'number',
                [textFieldClasses.monoInput]: variant === 'measure',
                [textFieldClasses.tinyGap]: variant === 'measure' && hasSpinner,
              },
              classes.size(size),
            )}
            clearable={clearable}
            error={error}
            fullWidth={fullWidth}
            onClear={onClear}
            size={size}
            prefix={prefix}
            suffix={suffix}
            {...interactiveProps}
          >
            <input
              {...defaultInputProps}
              {...inputProps}
              id={id}
              name={name}
              aria-disabled={disabled}
              aria-multiline={false}
              aria-readonly={readonly}
              disabled={disabled}
              onChange={formatter || parser ? handleChange : onChange}
              placeholder={placeholder}
              readOnly={readonly}
              ref={composedInputRef}
              style={{ ...inputStyle, ...inputProps?.style }}
              type={inputType ?? defaultInputType}
              value={displayValue}
            />
          </TextField>
          {suffixExternalButton}
        </div>
        {variant === 'password' && showPasswordStrengthIndicator ? (
          <PasswordStrengthIndicator
            {...(passwordStrengthIndicatorProps || {})}
            className={cx(
              classes.indicatorContainer,
              passwordStrengthIndicatorProps?.className,
            )}
          />
        ) : null}
      </div>
    );
  },
);

export default Input;

// packages/vue/input/input.vue
<script setup lang="ts">
import { computed, nextTick, ref, useAttrs } from 'vue';
import type { CSSProperties } from 'vue';
import { inputClasses as classes } from '@mezzanine-ui/core/input';
import { textFieldClasses } from '@mezzanine-ui/core/text-field';
import { EyeIcon, EyeInvisibleIcon, SearchIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { formatNumberWithCommas } from '../_internal/format-number-with-commas';
import { parseNumberWithCommas } from '../_internal/parse-number-with-commas';
import { useInputWithClearControlValue } from '../_internal/use-input-with-clear-control-value';
import MznIcon from '../icon/icon.vue';
import MznTextField from '../text-field/text-field.vue';
import MznInputActionButton from './action-button.vue';
import MznPasswordStrengthIndicator from './password-strength-indicator.vue';
import MznInputSelectButton from './select-button.vue';
import MznInputSpinnerButton from './spinner-button.vue';
import type { InputProps } from './input.types';

/**
 * 多功能輸入框，以 `variant` 決定型態。
 *
 * 八種：`base`、`affix`（前後綴）、`search`（預設可清除、前綴放大鏡）、`number`（原生數字）、
 * `measure`（千分位格式化，可加上下微調）、`action`（旁邊一顆動作按鈕）、
 * `select`（旁邊一顆下拉按鈕）、`password`（可切換顯示，並可加強度指示條）。
 * `measure` 顯示時自動加千分位，`change` 送出的仍是原始數值。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInput } from '@mezzanine-ui/vue/input';
 * <\/script>
 *
 * <template>
 *   <MznInput clearable placeholder="請輸入文字" />
 *   <MznInput variant="search" placeholder="搜尋關鍵字" />
 *   <MznInput variant="measure" suffix="px" show-spinner :min="0" :max="100" />
 * </template>
 * ```
 *
 * @see MznTextField 外框容器
 * @see MznFormField 提供標籤與提示訊息的欄位容器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<InputProps>(), {
  actionButton: undefined,
  active: undefined,
  clearable: undefined,
  defaultValue: undefined,
  disabled: false,
  dropdownMaxHeight: 114,
  dropdownPlacement: 'bottom-start',
  dropdownWidth: 120,
  error: false,
  forceShowClearable: undefined,
  formatter: undefined,
  fullWidth: true,
  hideSuffixWhenClearable: undefined,
  id: undefined,
  inputProps: undefined,
  inputType: undefined,
  max: undefined,
  min: undefined,
  name: undefined,
  options: undefined,
  parser: undefined,
  passwordStrengthIndicator: undefined,
  placeholder: undefined,
  readonly: undefined,
  selectButton: undefined,
  selectedValue: undefined,
  showPasswordStrengthIndicator: undefined,
  showSpinner: undefined,
  size: 'main',
  step: 1,
  typing: undefined,
  value: undefined,
  variant: 'base',
  warning: undefined,
});

const emit = defineEmits<{
  change: [event: Event];
  clear: [event: MouseEvent];
  select: [value: string];
  spinDown: [];
  spinUp: [];
}>();

const slots = defineSlots<{
  /** The field's prefix, for `variant="affix"` and `variant="measure"`. */
  prefix?: () => unknown;
  /** The field's suffix, for `variant="affix"` and `variant="measure"`. */
  suffix?: () => unknown;
}>();

const attrs = useAttrs();

const input = ref<HTMLInputElement | null>(null);
const showPassword = ref(false);

/**
 * React hands the input out through an `inputRef` prop; Vue's equivalent is
 * the parent placing a `ref` on this component, so the element is exposed.
 */
defineExpose({ input });

const {
  onChange,
  onClear: onClearFromHook,
  value,
} = useInputWithClearControlValue({
  defaultValue: () => props.defaultValue,
  elementRef: input,
  onChange: (event) => emit('change', event),
  value: () => props.value,
});

// Handle formatter/parser logic
const formatter = computed((): ((value: string) => string) | undefined => {
  if (props.formatter) return props.formatter;

  if (props.variant === 'measure') {
    return (raw: string) => formatNumberWithCommas(raw);
  }

  return undefined;
});

const parser = computed((): ((value: string) => string) | undefined => {
  if (props.parser) return props.parser;

  if (props.variant === 'measure') {
    return (raw: string) => parseNumberWithCommas(raw)?.toString() ?? '';
  }

  return undefined;
});

function handleChange(event: Event): void {
  restoreControlledValue();

  if (!parser.value) {
    onChange(event);

    return;
  }

  const target = event.target as HTMLInputElement;
  const parsed = parser.value(target.value);
  const originalValue = target.value;

  // Report the parsed value the way React rebuilds the event with it.
  target.value = parsed;
  onChange(event);
  target.value = originalValue;
}

/**
 * React re-renders a controlled input on every change and resets the element's
 * value even when the `value` prop did not move, so text typed into an input
 * whose value is pinned disappears again. Vue skips the patch when the bound
 * value is unchanged, leaving the typed text on screen, so it is put back here.
 */
function restoreControlledValue(): void {
  nextTick(() => {
    if (input.value && input.value.value !== displayValue.value) {
      input.value.value = displayValue.value;
    }
  });
}

// Format the display value
const displayValue = computed((): string =>
  formatter.value ? formatter.value(value.value) : value.value,
);

const isSearch = computed((): boolean => props.variant === 'search');
const isMeasure = computed((): boolean => props.variant === 'measure');
const isPassword = computed((): boolean => props.variant === 'password');

const hasSpinner = computed(
  (): boolean => isMeasure.value && Boolean(props.showSpinner),
);

const clearable = computed((): boolean => {
  if (isSearch.value) {
    // 預設為可清除
    return typeof props.clearable !== 'undefined' ? props.clearable : true;
  }

  if (
    props.variant === 'base' ||
    props.variant === 'affix' ||
    isPassword.value
  ) {
    return Boolean(props.clearable);
  }

  return false;
});

const defaultInputType = computed((): string => {
  if (props.variant === 'number') return 'number';
  if (isPassword.value) return showPassword.value ? 'text' : 'password';

  return 'text';
});

const defaultInputProps = computed((): Record<string, unknown> => {
  if (props.variant === 'number' || isMeasure.value) {
    return { max: props.max, min: props.min, step: props.step };
  }

  return {};
});

// 預設置右對齊
const inputStyle = computed((): CSSProperties | undefined =>
  isMeasure.value ? { textAlign: 'right' } : undefined,
);

function handleSpin(direction: 1 | -1): void {
  const currentValue = parseFloat(value.value || '0');
  const newValue = currentValue + direction * props.step;
  const withinBounds =
    direction === 1
      ? typeof props.max === 'undefined' || newValue <= props.max
      : typeof props.min === 'undefined' || newValue >= props.min;

  if (withinBounds) {
    // React hands the hook a synthetic event carrying only the new value;
    // the rendered value comes from state either way.
    onChange({ target: { value: String(newValue) } } as unknown as Event);
  }

  if (direction === 1) {
    emit('spinUp');
  } else {
    emit('spinDown');
  }
}

const actionButtonProps = computed(() => {
  if (props.variant !== 'action' || !props.actionButton) return undefined;

  const { position: _position, ...rest } = props.actionButton;

  return {
    ...rest,
    disabled:
      typeof rest.disabled === 'boolean'
        ? rest.disabled
        : props.disabled || props.readonly,
    size: props.size,
  };
});

const selectButtonProps = computed(() => {
  if (props.variant !== 'select' || !props.selectButton) return undefined;

  const { position: _position, ...rest } = props.selectButton;

  return {
    ...rest,
    disabled: rest.disabled || props.disabled,
    dropdownMaxHeight: props.dropdownMaxHeight,
    dropdownPlacement: props.dropdownPlacement,
    dropdownWidth: props.dropdownWidth,
    options: props.options,
    size: props.size,
  };
});

const prefixExternalButton = computed((): boolean => {
  if (props.variant === 'action') {
    return props.actionButton?.position === 'prefix';
  }

  if (props.variant === 'select') {
    return (
      props.selectButton?.position === 'both' ||
      props.selectButton?.position === 'prefix'
    );
  }

  return false;
});

const suffixExternalButton = computed((): boolean => {
  if (props.variant === 'action') {
    return props.actionButton?.position === 'suffix';
  }

  if (props.variant === 'select') {
    return (
      props.selectButton?.position === 'both' ||
      props.selectButton?.position === 'suffix'
    );
  }

  return false;
});

const showPasswordStrengthIndicator = computed(
  (): boolean =>
    isPassword.value && Boolean(props.showPasswordStrengthIndicator),
);

function togglePassword(): void {
  showPassword.value = !showPassword.value;
}

function handlePasswordToggleKeyDown(event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    togglePassword();
  }
}

function handleClear(event: MouseEvent): void {
  emit('clear', event);
  onClearFromHook(event);
}

const interactiveProps = computed(() => {
  if (props.disabled) return { disabled: true as const };
  if (props.readonly) return { readonly: true as const };
  if (props.typing) return { typing: true as const };

  return {};
});

const containerClasses = computed((): string =>
  clsx(classes.container, attrs.class as string),
);

const hostClasses = computed((): string =>
  clsx(classes.host, {
    [classes.number]: props.variant === 'number',
    [classes.passwordInput]: isPassword.value,
    [classes.withPrefixExternalAction]: prefixExternalButton.value,
    [classes.withSuffixExternalAction]: suffixExternalButton.value,
    [classes.searchInput]: isSearch.value,
    [classes.measureWithSpinner]: isMeasure.value && hasSpinner.value,
    [classes.measureWithoutSpinner]: isMeasure.value && !hasSpinner.value,
  }),
);

const fieldClasses = computed((): string =>
  clsx(
    classes.field,
    {
      [classes.number]: props.variant === 'number',
      [textFieldClasses.monoInput]: isMeasure.value,
      [textFieldClasses.tinyGap]: isMeasure.value && hasSpinner.value,
    },
    classes.size(props.size),
  ),
);

const indicatorClasses = computed((): string =>
  clsx(classes.indicatorContainer),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const hasPrefixSlot = computed((): boolean =>
  Boolean(slots.prefix && (props.variant === 'affix' || isMeasure.value)),
);

const hasSuffixSlot = computed((): boolean =>
  Boolean(slots.suffix && (props.variant === 'affix' || isMeasure.value)),
);

const spinnersClass = classes.spinners;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="containerClasses">
    <div :class="hostClasses">
      <MznInputActionButton
        v-if="prefixExternalButton && actionButtonProps"
        v-bind="actionButtonProps"
      />
      <MznInputSelectButton
        v-if="prefixExternalButton && selectButtonProps"
        v-bind="selectButtonProps"
        @select="emit('select', $event)"
      />
      <MznTextField
        v-bind="interactiveProps"
        :active="active"
        :class="fieldClasses"
        :clearable="clearable"
        :error="error"
        :force-show-clearable="forceShowClearable"
        :full-width="fullWidth"
        :hide-suffix-when-clearable="hideSuffixWhenClearable"
        role="presentation"
        :size="size"
        :warning="warning"
        @clear="handleClear"
      >
        <template v-if="isSearch || hasPrefixSlot" #prefix>
          <MznIcon v-if="isSearch" :icon="SearchIcon" />
          <slot v-else name="prefix" />
        </template>
        <template
          v-if="hasSuffixSlot || (isMeasure && hasSpinner) || isPassword"
          #suffix
        >
          <slot v-if="hasSuffixSlot" name="suffix" />
          <div v-if="isMeasure && hasSpinner" :class="spinnersClass">
            <MznInputSpinnerButton
              :disabled="disabled"
              :size="size"
              type="up"
              @click="handleSpin(1)"
            />
            <MznInputSpinnerButton
              :disabled="disabled"
              :size="size"
              type="down"
              @click="handleSpin(-1)"
            />
          </div>
          <MznIcon
            v-if="isPassword"
            :aria-label="showPassword ? 'Hide password' : 'Show password'"
            :icon="showPassword ? EyeIcon : EyeInvisibleIcon"
            role="button"
            :tabindex="0"
            @click="togglePassword"
            @keydown="handlePasswordToggleKeyDown"
          />
        </template>
        <input
          ref="input"
          v-bind="{ ...defaultInputProps, ...inputProps }"
          :aria-disabled="disabled"
          :aria-multiline="false"
          :aria-readonly="readonly"
          :disabled="disabled"
          :id="id"
          :name="name"
          :placeholder="placeholder"
          :readonly="readonly"
          :style="[inputStyle, inputProps?.style]"
          :type="inputType ?? defaultInputType"
          :value="displayValue"
          @input="handleChange"
        />
      </MznTextField>
      <MznInputActionButton
        v-if="suffixExternalButton && actionButtonProps"
        v-bind="actionButtonProps"
      />
      <MznInputSelectButton
        v-if="suffixExternalButton && selectButtonProps"
        v-bind="selectButtonProps"
        @select="emit('select', $event)"
      />
    </div>
    <MznPasswordStrengthIndicator
      v-if="showPasswordStrengthIndicator"
      v-bind="passwordStrengthIndicator"
      :class="indicatorClasses"
    />
  </div>
</template>
