// packages/react/src/Input/SelectButton/SelectButton.tsx
'use client';

import {
  inputSelectButtonClasses as classes,
  InputSize,
} from '@mezzanine-ui/core/input';
import { DropdownOption } from '@mezzanine-ui/core/dropdown/dropdown';
import { forwardRef, useCallback, useState } from 'react';
import Icon from '../../Icon';
import Rotate from '../../Transition/Rotate';
import Dropdown from '../../Dropdown';
import { PopperPlacement } from '../../Popper';
import { cx } from '../../utils/cx';
import { ChevronDownIcon } from '@mezzanine-ui/icons';
import { NativeElementPropsWithoutKeyAndRef } from '../../utils/jsx-types';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';

export interface SelectButtonProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'button'>,
    'disabled' | 'onSelect' | 'type' | 'selectedValue'
  > {
  /**
   * Whether clicking an option should automatically close the dropdown.
   * @default true
   */
  closeOnSelect?: boolean;
  /**
   * Whether the select button is disabled.
   */
  disabled?: boolean;
  /**
   * The custom width of the dropdown.
   */
  dropdownWidth?: number | string;
  /**
   * The max height of the dropdown.
   */
  dropdownMaxHeight?: number | string;
  /**
   * The placement of the dropdown.
   */
  dropdownPlacement?: PopperPlacement;
  /**
   * The options of the dropdown.
   */
  options?: DropdownOption[];
  /**
   * Callback when an option is selected.
   */
  onSelect?: (value: string) => void;
  /**
   * The size of select button.
   * @default 'main'
   */
  size?: InputSize;
  /**
   * The value of select button.
   */
  value?: string;
}

const SelectButton = forwardRef<HTMLButtonElement, SelectButtonProps>(
  function SelectButton(props, ref) {
    const {
      className,
      closeOnSelect = true,
      disabled,
      dropdownMaxHeight = 114,
      dropdownPlacement = 'bottom-start',
      dropdownWidth = 120,
      onSelect,
      options = [],
      size = 'main',
      value,
      ...rest
    } = props;

    const [open, setOpen] = useState(false);

    const handleVisibilityChange = useCallback(
      (next: boolean) => {
        if (disabled && next) return;
        setOpen(next);
      },
      [disabled],
    );

    const handleSelect = useCallback(
      (option: DropdownOption) => {
        onSelect?.(option.id);

        if (closeOnSelect) {
          setOpen(false);
        }
      },
      [closeOnSelect, onSelect],
    );

    const dropdownOptions: DropdownOption[] = options.map((option) => ({
      ...option,
      ...(option.id === value ? { checkSite: 'suffix' } : {}),
    }));

    return (
      <Dropdown
        customWidth={dropdownWidth}
        disabled={disabled}
        maxHeight={dropdownMaxHeight}
        onSelect={handleSelect}
        onVisibilityChange={handleVisibilityChange}
        open={open}
        options={dropdownOptions}
        placement={dropdownPlacement}
        value={value}
      >
        <button
          ref={ref}
          type="button"
          disabled={disabled}
          className={cx(
            classes.host,
            disabled && classes.disabled,
            size === 'main' ? classes.main : classes.sub,
            className,
          )}
          title={value}
          {...rest}
        >
          <span className={classes.text}>{value}</span>
          <Rotate
            in={open}
            duration={MOTION_DURATION.fast}
            easing={MOTION_EASING.standard}
          >
            <Icon className={classes.icon} icon={ChevronDownIcon} size={16} />
          </Rotate>
        </button>
      </Dropdown>
    );
  },
);

export default SelectButton;

// packages/vue/input/select-button.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue';
import { inputSelectButtonClasses as classes } from '@mezzanine-ui/core/input';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown/dropdown';
import { ChevronDownIcon } from '@mezzanine-ui/icons';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import MznDropdown from '../dropdown/dropdown.vue';
import MznIcon from '../icon/icon.vue';
import MznRotate from '../transition/rotate.vue';
import type { SelectButtonProps } from './select-button.types';

/**
 * 貼在輸入框旁邊的下拉選擇按鈕。
 *
 * 目前的值會顯示在按鈕上並標記為已選；箭頭在開啟時旋轉。
 * 預設選完就關閉，`closeOnSelect` 設為 false 可留著。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInputSelectButton } from '@mezzanine-ui/vue/input';
 * <\/script>
 *
 * <template>
 *   <MznInputSelectButton :options="options" value="TWD" @select="onSelect" />
 * </template>
 * ```
 *
 * @see MznInput `variant="select"` 會渲染這顆按鈕
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SelectButtonProps>(), {
  closeOnSelect: true,
  disabled: undefined,
  dropdownMaxHeight: 114,
  dropdownPlacement: 'bottom-start',
  dropdownWidth: 120,
  options: () => [],
  size: 'main',
  value: undefined,
});

const emit = defineEmits<{
  select: [value: string];
}>();

const attrs = useAttrs();

const open = ref(false);

function handleVisibilityChange(next: boolean): void {
  if (props.disabled && next) return;

  open.value = next;
}

function handleSelect(option: DropdownOption): void {
  emit('select', option.id);

  if (props.closeOnSelect) {
    open.value = false;
  }
}

const dropdownOptions = computed((): DropdownOption[] =>
  props.options.map((option) => ({
    ...option,
    ...(option.id === props.value ? { checkSite: 'suffix' as const } : {}),
  })),
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    props.disabled && classes.disabled,
    props.size === 'main' ? classes.main : classes.sub,
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const rotateDuration = MOTION_DURATION.fast;
const rotateEasing = MOTION_EASING.standard;
const iconClass = classes.icon;
const textClass = classes.text;
</script>

<template>
  <MznDropdown
    :custom-width="dropdownWidth"
    :disabled="disabled"
    :max-height="dropdownMaxHeight"
    :open="open"
    :options="dropdownOptions"
    :placement="dropdownPlacement"
    :value="value"
    @select="handleSelect"
    @visibility-change="handleVisibilityChange"
  >
    <template #default="triggerProps">
      <button
        v-bind="{ ...forwardedAttrs, ...triggerProps }"
        :class="hostClasses"
        :disabled="disabled"
        :title="value"
        type="button"
      >
        <span :class="textClass">{{ value }}</span>
        <MznRotate :duration="rotateDuration" :easing="rotateEasing" :in="open">
          <MznIcon :class="iconClass" :icon="ChevronDownIcon" :size="16" />
        </MznRotate>
      </button>
    </template>
  </MznDropdown>
</template>
