// packages/react/src/Input/SpinnerButton/SpinnerButton.tsx
'use client';

import {
  inputSpinnerButtonClasses as classes,
  InputSize,
} from '@mezzanine-ui/core/input';
import { forwardRef } from 'react';
import Icon from '../../Icon';
import { cx } from '../../utils/cx';
import { CaretDownFlatIcon, CaretUpFlatIcon } from '@mezzanine-ui/icons';
import { NativeElementPropsWithoutKeyAndRef } from '../../utils/jsx-types';

export interface SpinnerButtonProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'button'>,
    'type' | 'disabled'
  > {
  /**
   * Whether the spinner button is disabled.
   */
  disabled?: boolean;
  /**
   * The size of spinner button.
   * @default 'main'
   */
  size?: InputSize;
  /**
   * The type of spinner button.
   */
  type: 'up' | 'down';
}

const SpinnerButton = forwardRef<HTMLButtonElement, SpinnerButtonProps>(
  function SpinnerButton(props, ref) {
    const { className, disabled, size = 'main', type, ...rest } = props;

    return (
      <button
        ref={ref}
        type="button"
        disabled={disabled}
        className={cx(
          classes.host,
          disabled && classes.disabled,
          size === 'main' ? classes.main : classes.sub,
          className,
        )}
        aria-label={type === 'up' ? 'Increase value' : 'Decrease value'}
        title={type === 'up' ? 'Increase value' : 'Decrease value'}
        {...rest}
      >
        <Icon
          aria-hidden="true"
          icon={type === 'up' ? CaretUpFlatIcon : CaretDownFlatIcon}
        />
      </button>
    );
  },
);

export default SpinnerButton;

// packages/vue/input/spinner-button.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { inputSpinnerButtonClasses as classes } from '@mezzanine-ui/core/input';
import { CaretDownFlatIcon, CaretUpFlatIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { SpinnerButtonProps } from './spinner-button.types';

/**
 * 數值輸入框的上下微調按鈕。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInputSpinnerButton } from '@mezzanine-ui/vue/input';
 * <\/script>
 *
 * <template>
 *   <MznInputSpinnerButton type="up" @click="increase" />
 * </template>
 * ```
 *
 * @see MznInput `variant="measure"` 且 `showSpinner` 時會渲染這兩顆按鈕
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SpinnerButtonProps>(), {
  disabled: undefined,
  size: 'main',
});

const attrs = useAttrs();

const label = computed((): string =>
  props.type === 'up' ? 'Increase value' : 'Decrease value',
);

const icon = computed(() =>
  props.type === 'up' ? CaretUpFlatIcon : CaretDownFlatIcon,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    props.disabled && classes.disabled,
    props.size === 'main' ? classes.main : classes.sub,
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});
</script>

<template>
  <button
    :aria-label="label"
    :class="hostClasses"
    :disabled="disabled"
    :title="label"
    type="button"
    v-bind="forwardedAttrs"
  >
    <MznIcon aria-hidden="true" :icon="icon" />
  </button>
</template>
