// packages/ng/menu/menu-item.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  HostListener,
  Input,
  ViewEncapsulation,
} from '@angular/core';
import {
  menuItemClasses as classes,
} from '@mezzanine-ui/core/menu';
import { CheckIcon } from '@mezzanine-ui/icons';
import {
  BooleanInput,
  HostBindingClass,
  InputBoolean,
} from '@mezzanine-ui/ng/cdk';

@Component({
  selector: 'li[mzn-menu-item]',
  exportAs: 'mznMenuItem',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ng-template #activeIcon>
      <ng-container *ngIf="active">
        <i
          [class]="classes.activeIcon"
          [mzn-icon]="checkIcon"
        ></i>
      </ng-container>
    </ng-template>

    <div [class]="classes.label">
      <ng-content></ng-content>
    </div>
    <ng-template [ngTemplateOutlet]="activeIcon"></ng-template>

  `,
})

/**
 * The ng component for `mezzanine` menu item.
 */
export class MznMenuItemComponent {
  static ngAcceptInputType_active: BooleanInput;

  static ngAcceptInputType_disabled: BooleanInput;

  @HostBindingClass(classes.host)
  readonly bindHostClass = true;

  readonly classes = classes;

  readonly checkIcon = CheckIcon;

  /**
   * Whether the menu item is active.
   * @default false
   */
  @HostBindingClass(classes.active)
  @Input()
  @InputBoolean()
  active?: boolean = false;

  /**
   * Whether the menu item is disabled.
   * @default false
   */
  @HostBindingClass(classes.disabled)
  @HostBinding('attr.aria-disabled')
  @Input()
  @InputBoolean()
  disabled?: boolean = false;

  /**
   * The role of menu item.
   * @default 'menuitem'
   */
  @HostBinding('attr.role')
  @Input()
  role?: string = 'menuitem';

  @HostListener('click', ['$event'])
  onClick(event: MouseEvent) {
    if (this.disabled) {
      if (event.target instanceof HTMLAnchorElement) {
        event.preventDefault();
        event.stopImmediatePropagation();
      }
    }
  }
}

// packages/react/src/Menu/MenuItem.tsx
import { forwardRef } from 'react';
import {
  menuItemClasses as classes,
} from '@mezzanine-ui/core/menu';
import { CheckIcon } from '@mezzanine-ui/icons';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Icon from '../Icon';

export interface MenuItemProps extends NativeElementPropsWithoutKeyAndRef<'li'> {
  /**
   * Whether the menu item is active.
   * @default false
   */
  active?: boolean;
  /**
   * Whether the menu item is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * The role of menu item.
   * @default 'menuitem'
   */
  role?: string;
}

/**
 * The react component for `mezzanine` menu item.
 */
const MenuItem = forwardRef<HTMLLIElement, MenuItemProps>(function MenuItem(props, ref) {
  const {
    active = false,
    children,
    className,
    disabled = false,
    onClick,
    role = 'menuitem',
    ...rest
  } = props;

  return (
    // eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions
    <li
      {...rest}
      ref={ref}
      aria-disabled={disabled}
      className={cx(
        classes.host,
        {
          [classes.active]: active,
          [classes.disabled]: disabled,
        },
        className,
      )}
      onClick={(event) => {
        if (!disabled && onClick) {
          onClick(event);
        }
      }}
      onKeyDown={() => {}}
      role={role}
    >
      <div className={classes.label}>{children}</div>
      {active && <Icon className={classes.activeIcon} icon={CheckIcon} />}
    </li>
  );
});

export default MenuItem;
