// packages/vue/table/table-expand-cell.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { CSSProperties } from 'vue';
import { tableClasses as classes } from '@mezzanine-ui/core/table';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznSkeleton from '../skeleton/skeleton.vue';
import { useTableContext } from './table-context';
import type { TableExpandCellProps } from './table-expand-cell.types';

/**
 * 展開欄的儲存格：資料列放一顆會旋轉的箭頭按鈕，表頭永遠是空的。
 *
 * `can-expand` 為 false 時整顆按鈕都不渲染，點擊也不會冒泡出去。
 *
 * @example
 * ```vue
 * <template>
 *   <MznTableExpandCell :expanded="isExpanded" @click="toggle" />
 * </template>
 * ```
 *
 * @see MznTableExpandedRow 展開後的內容列
 */
const props = withDefaults(defineProps<TableExpandCellProps>(), {
  canExpand: true,
  fixed: false,
  fixedOffset: 0,
  isHeader: false,
  showShadow: false,
  width: undefined,
});

const emit = defineEmits<{
  /** Fired when the expand button is pressed. */
  click: [];
}>();

const table = useTableContext();

const cellComponent = computed((): string => (props.isHeader ? 'th' : 'td'));

const cellStyle = computed((): CSSProperties => {
  const style: CSSProperties = {};

  // Apply explicit width for dragging state
  if (props.width !== undefined) {
    style.width = `${props.width}px`;
    style.minWidth = `${props.width}px`;
    style.maxWidth = `${props.width}px`;
    style.flexShrink = 0;
  }

  if (props.fixed) {
    (style as Record<string, string>)['--fixed-start-offset'] =
      `${props.fixedOffset}px`;
  }

  return style;
});

const cellClasses = computed((): string =>
  clsx(props.isHeader ? classes.headerCell : classes.cell, classes.expandCell, {
    [classes.cellFixed]: props.fixed,
    [classes.cellFixedStart]: props.fixed,
    [classes.cellFixedShadow]: props.showShadow,
  }),
);

const buttonClasses = computed((): string =>
  clsx(classes.expandIcon, {
    [classes.expandIconExpanded]: props.expanded,
  }),
);

function handleClick(event: MouseEvent): void {
  event.stopPropagation();

  if (props.canExpand) {
    emit('click');
  }
}
</script>

<template>
  <component
    :is="cellComponent"
    :class="cellClasses"
    :scope="isHeader ? 'col' : undefined"
    :style="cellStyle"
  >
    <template v-if="!isHeader">
      <MznSkeleton v-if="table.loading" variant="body-highlight" width="100%" />
      <button
        v-else-if="canExpand"
        :class="buttonClasses"
        type="button"
        @click="handleClick"
      >
        <MznIcon :icon="ChevronRightIcon" color="inherit" />
      </button>
    </template>
  </component>
</template>

// packages/react/src/Table/components/TableExpandCell.tsx
'use client';

import { forwardRef, memo, useCallback } from 'react';
import { tableClasses as classes } from '@mezzanine-ui/core/table';
import { ChevronRightIcon } from '@mezzanine-ui/icons';
import { cx } from '../../utils/cx';
import Icon from '../../Icon';
import Skeleton from '../../Skeleton';
import { useTableContext } from '../TableContext';

export interface TableExpandCellProps {
  canExpand?: boolean;
  className?: string;
  expanded: boolean;
  fixed?: boolean;
  fixedOffset?: number;
  isHeader?: boolean;
  onClick?: VoidFunction;
  showShadow?: boolean;
  /** Explicit width for dragging state */
  width?: number;
}

const TableExpandCellInner = forwardRef<
  HTMLTableCellElement,
  TableExpandCellProps
>(function TableExpandCell(props, ref) {
  const { loading } = useTableContext();
  const {
    canExpand = true,
    className,
    expanded,
    fixed = false,
    fixedOffset = 0,
    isHeader = false,
    onClick,
    showShadow = false,
    width,
  } = props;

  const handleClick = useCallback(
    (event: React.MouseEvent) => {
      event.stopPropagation();

      if (canExpand && onClick) {
        onClick();
      }
    },
    [canExpand, onClick],
  );

  const CellComponent = isHeader ? 'th' : 'td';

  const cellStyle: React.CSSProperties = {};

  // Apply explicit width for dragging state
  if (width !== undefined) {
    cellStyle.width = width;
    cellStyle.minWidth = width;
    cellStyle.maxWidth = width;
    cellStyle.flexShrink = 0;
  }

  if (fixed) {
    (cellStyle as Record<string, string>)['--fixed-start-offset'] =
      `${fixedOffset}px`;
  }

  const renderChild = () => {
    if (isHeader) return null;

    if (loading) {
      return <Skeleton width="100%" variant="body-highlight" />;
    }

    return canExpand ? (
      <button
        className={cx(classes.expandIcon, {
          [classes.expandIconExpanded]: expanded,
        })}
        onClick={handleClick}
        type="button"
      >
        <Icon icon={ChevronRightIcon} color="inherit" />
      </button>
    ) : null;
  };

  return (
    <CellComponent
      className={cx(
        isHeader ? classes.headerCell : classes.cell,
        classes.expandCell,
        {
          [classes.cellFixed]: fixed,
          [classes.cellFixedStart]: fixed,
          [classes.cellFixedShadow]: showShadow,
        },
        className,
      )}
      ref={ref}
      scope={isHeader ? 'col' : undefined}
      style={cellStyle}
    >
      {renderChild()}
    </CellComponent>
  );
});

export const TableExpandCell = memo(TableExpandCellInner);
