// packages/vue/table/table-expanded-row.vue
<script setup lang="ts">
import { cloneVNode, computed, isVNode } from 'vue';
import type { VNode, VNodeChild } from 'vue';
import {
  getRowKey,
  tableClasses as classes,
  type TableDataSource,
} from '@mezzanine-ui/core/table';
import clsx from 'clsx';
import { useTableContext } from './table-context';
import { useTableDataContext } from './table-data-context';
import MznTable from './table.vue';
import type { TableExpandedRowProps } from './table-expanded-row.types';

/**
 * 展開後的內容列，橫跨整個表格寬度。
 *
 * 內容由 `expandable.expandedRowRender(record)` 提供；如果回傳的是另一個 MznTable，
 * 會自動補上 `nested` 與 `show-header: false`，讓子表沿用父表的量測結果。
 *
 * @example
 * ```vue
 * <template>
 *   <MznTableExpandedRow :record="record" />
 * </template>
 * ```
 *
 * @see MznTableExpandCell 觸發展開的儲存格
 */
const props = withDefaults(
  defineProps<TableExpandedRowProps<TableDataSource>>(),
  { style: undefined },
);

const table = useTableContext();
const data = useTableDataContext();

// Calculate total column span
const totalColSpan = computed((): number => {
  const { draggable, expansion, selection } = table.value;
  let colSpan = data.value.columns.length;

  // Add 1 for expand column itself
  if (expansion) colSpan += 1;
  if (draggable?.enabled) colSpan += 1;
  if (selection) colSpan += 1;

  return colSpan;
});

const rowKey = computed((): string => getRowKey(props.record));

const isExpanded = computed((): boolean =>
  Boolean(table.value.expansion?.isRowExpanded(rowKey.value)),
);

const expandedRowRender = computed(
  () => table.value.expansion?.config?.expandedRowRender,
);

const rowClasses = computed((): string =>
  clsx(classes.expandedRow, {
    [classes.expandedRowAdding]:
      table.value.transitionState?.addingKeys.has(rowKey.value) ?? false,
    [classes.expandedRowDeleting]:
      table.value.transitionState?.deletingKeys.has(rowKey.value) ?? false,
    [classes.expandedRowFadingOut]:
      table.value.transitionState?.fadingOutKeys.has(rowKey.value) ?? false,
  }),
);

/**
 * React clones the rendered child and, when it is a Table, injects the two
 * props that make it behave as a nested one.
 */
const content = computed((): VNodeChild => {
  const rendered = expandedRowRender.value?.(props.record);

  if (isVNode(rendered) && (rendered as VNode).type === MznTable) {
    return cloneVNode(rendered as VNode, {
      nested: true,
      showHeader: false,
    });
  }

  return rendered;
});
</script>

<template>
  <tr
    v-if="expandedRowRender && isExpanded"
    :class="rowClasses"
    :data-row-key="`${rowKey}-expanded`"
    :style="style"
  >
    <td
      :class="classes.expandedRowCell"
      :colspan="totalColSpan"
      :style="{
        paddingLeft: `${table.expansion?.expansionLeftPadding ?? 0}px`,
      }"
    >
      <div :class="classes.expandedContent">
        <component :is="() => content" />
      </div>
    </td>
  </tr>
</template>

// packages/react/src/Table/components/TableExpandedRow.tsx
'use client';

import { cloneElement, forwardRef, memo, useMemo } from 'react';
import {
  getRowKey,
  tableClasses as classes,
  type TableDataSource,
} from '@mezzanine-ui/core/table';
import { cx } from '../../utils/cx';
import { useTableContext, useTableDataContext } from '../TableContext';
import { Table } from '../Table';

export interface TableExpandedRowProps<
  T extends TableDataSource = TableDataSource,
> {
  className?: string;
  record: T;
  style?: React.CSSProperties;
}

const TableExpandedRowInner = forwardRef<
  HTMLTableRowElement,
  TableExpandedRowProps
>(function TableExpandedRow(props, ref) {
  const { className, record, style } = props;

  const { expansion, draggable, selection, transitionState } =
    useTableContext();
  const { columns } = useTableDataContext();

  // Calculate total column span
  const totalColSpan = useMemo(() => {
    let colSpan = columns.length;

    // Add 1 for expand column itself
    if (expansion) colSpan += 1;
    if (draggable?.enabled) colSpan += 1;
    if (selection) colSpan += 1;

    return colSpan;
  }, [columns.length, expansion, draggable?.enabled, selection]);

  const rowKey = getRowKey(record);
  const isExpanded = expansion?.isRowExpanded(rowKey);

  // Check transition states for the parent row
  const isAdding = transitionState?.addingKeys.has(rowKey) ?? false;
  const isDeleting = transitionState?.deletingKeys.has(rowKey) ?? false;
  const isFadingOut = transitionState?.fadingOutKeys.has(rowKey) ?? false;

  const { config } = expansion || {};
  const { expandedRowRender } = config || {};

  const childNeededProps = useMemo(
    () => ({
      table: {
        nested: true,
        showHeader: false,
      },
    }),
    [],
  );

  if (!expandedRowRender || !isExpanded) return null;

  const children = expandedRowRender(record);
  const clonedChild = cloneElement(children as React.ReactElement);

  return (
    <tr
      className={cx(
        classes.expandedRow,
        {
          [classes.expandedRowAdding]: isAdding,
          [classes.expandedRowDeleting]: isDeleting,
          [classes.expandedRowFadingOut]: isFadingOut,
        },
        className,
      )}
      data-row-key={`${rowKey}-expanded`}
      ref={ref}
      style={style}
    >
      <td
        className={classes.expandedRowCell}
        colSpan={totalColSpan}
        style={{ paddingLeft: expansion?.expansionLeftPadding }}
      >
        <div className={classes.expandedContent}>
          {clonedChild.type === Table
            ? cloneElement(clonedChild, {
                ...childNeededProps.table,
              })
            : clonedChild}
        </div>
      </td>
    </tr>
  );
});

export const TableExpandedRow = memo(
  TableExpandedRowInner,
) as typeof TableExpandedRowInner;
