// packages/vue/upload/upload-picture-card.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import type { CSSProperties } from 'vue';
import { uploadPictureCardClasses as classes } from '@mezzanine-ui/core/upload';
import {
  DownloadIcon,
  FileIcon,
  ImageIcon,
  ResetIcon,
  TrashIcon,
  ZoomInIcon,
} from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useHasListener } from '../_internal/use-has-listener';
import MznButton from '../button/button.vue';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTypography from '../typography/typography.vue';
import { isImageFile } from './upload-utils';
import type {
  UploadPictureCardAriaLabels,
  UploadPictureCardProps,
} from './upload-picture-card.types';

/**
 * 圖片上傳的卡片式預覽。
 *
 * 圖片以 blob 或網址顯示，非圖片顯示檔名。`status` 決定右上角的操作：上傳中是
 * 取消加轉圈、完成是放大／下載／刪除、錯誤是重試加刪除。`readable` 讓卡片變成
 * 純展示；有人監聽 `replace` 且已完成時，整張卡片變成重新選檔的觸發區。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznUploadPictureCard } from '@mezzanine-ui/vue/upload';
 * <\/script>
 *
 * <template>
 *   <MznUploadPictureCard :file="file" status="done" @delete="onDelete" />
 * </template>
 * ```
 *
 * @see MznUpload 管理整組卡片的元件
 */
const props = withDefaults(defineProps<UploadPictureCardProps>(), {
  ariaLabels: undefined,
  disabled: false,
  errorIcon: undefined,
  errorMessage: undefined,
  file: undefined,
  id: undefined,
  imageFit: 'cover',
  readable: false,
  size: 'main',
  status: 'loading',
  url: undefined,
});

const emit = defineEmits<{
  /** Fired when the delete action is used. */
  delete: [event: MouseEvent];
  /** Fired when the download action is used. */
  download: [event: MouseEvent];
  /** Fired when the reload action is used. */
  reload: [event: MouseEvent];
  /** Fired when the card is clicked while it stands for a replacement. */
  replace: [event: MouseEvent];
  /** Fired when the zoom-in action is used. */
  zoomIn: [event: MouseEvent];
}>();

const hasListener = useHasListener();

const DEFAULT_ARIA_LABELS: Required<UploadPictureCardAriaLabels> = {
  cancelUpload: 'Cancel upload',
  clickToReplace: 'Click to Replace',
  delete: 'Delete file',
  download: 'Download file',
  reload: 'Retry upload',
  uploading: 'Uploading',
  zoomIn: 'Zoom in image',
};

const labels = computed(
  (): Required<UploadPictureCardAriaLabels> => ({
    ...DEFAULT_ARIA_LABELS,
    ...props.ariaLabels,
  }),
);

const isImage = computed((): boolean => isImageFile(props.file, props.url));

const fileName = computed((): string => {
  if (props.file?.name && !props.url) return props.file.name;

  if (props.url) {
    try {
      const url = new URL(props.url);

      return url.pathname.split('/').pop() || '';
    } catch {
      const urlWithoutQuery = props.url.split('?')[0].split('#')[0];

      return urlWithoutQuery.split('/').pop() || '';
    }
  }

  return '';
});

const imageUrl = ref('');

let objectUrl: string | null = null;

function revokeObjectUrl(): void {
  if (objectUrl) {
    URL.revokeObjectURL(objectUrl);
    objectUrl = null;
  }
}

watch(
  [
    (): File | undefined => props.file,
    (): string | undefined => props.url,
    isImage,
  ],
  ([file, url, image]) => {
    revokeObjectUrl();

    if (url && image) {
      imageUrl.value = url;

      return;
    }

    if (file && image) {
      try {
        objectUrl = URL.createObjectURL(file);
        imageUrl.value = objectUrl;
      } catch (error) {
        console.error('Failed to create object URL for image:', error);
        imageUrl.value = '';
      }

      return;
    }

    imageUrl.value = '';
  },
  { immediate: true },
);

onBeforeUnmount(revokeObjectUrl);

watch(
  [(): File | undefined => props.file, (): string | undefined => props.url],
  ([file, url]) => {
    if (!file && !url) {
      console.warn(
        'UploadPictureCard: Both `file` and `url` props are missing. At least one should be provided to display the upload picture card.',
      );
    }
  },
  { immediate: true },
);

const errorIconContent = computed((): IconDefinition => {
  if (props.errorIcon) return props.errorIcon;

  return isImage.value ? ImageIcon : FileIcon;
});

const errorMessageContent = computed((): string => {
  if (props.errorMessage) return props.errorMessage;

  return fileName.value ? fileName.value : 'Upload error';
});

const unsupported = computed(
  (): boolean => !isImage.value && props.size === 'minor',
);

watch(
  unsupported,
  (value) => {
    if (value) {
      console.warn(
        'UploadPictureCard: minor size is not supported for non-image files',
      );
    }
  },
  { immediate: true },
);

const canZoomIn = computed((): boolean => hasListener('zoomIn'));
const canDownload = computed((): boolean => hasListener('download'));
const canReplace = computed((): boolean => hasListener('replace'));

const isReplaceTrigger = computed(
  (): boolean => !props.readable && canReplace.value && props.status === 'done',
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.size(props.size),
    props.disabled && classes.disabled,
    props.readable && classes.readable,
    isReplaceTrigger.value && classes.replaceMode,
  ),
);

const imageStyle = computed(
  (): CSSProperties => ({
    objectFit: props.imageFit,
    objectPosition: 'center',
  }),
);

function onHostClick(event: MouseEvent): void {
  if (isReplaceTrigger.value) emit('replace', event);
}

function onHostKeydown(event: KeyboardEvent): void {
  if (!isReplaceTrigger.value) return;

  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    (event.currentTarget as HTMLElement).click();
  }
}

function onDelete(event: MouseEvent): void {
  event.stopPropagation();
  emit('delete', event);
}

function onDownload(event: MouseEvent): void {
  event.stopPropagation();
  emit('download', event);
}

function onZoomIn(event: MouseEvent): void {
  event.stopPropagation();
  emit('zoomIn', event);
}
</script>

<template>
  <div
    v-if="!unsupported"
    :aria-disabled="disabled"
    :class="hostClasses"
    role="group"
    :tabindex="disabled || readable ? -1 : 0"
    @click="onHostClick"
    @keydown="onHostKeydown"
  >
    <div :class="classes.container">
      <img
        v-if="isImage && imageUrl && status !== 'error'"
        :alt="fileName"
        :src="imageUrl"
        :style="imageStyle"
      />
      <div
        v-if="status === 'done' && size !== 'minor' && !isImage"
        :class="classes.content"
      >
        <MznIcon color="brand" :icon="FileIcon" :size="16" />
        <MznTypography :class="classes.name" ellipsis>
          {{ fileName }}
        </MznTypography>
      </div>
      <div
        v-if="status === 'error' && size !== 'minor'"
        aria-live="polite"
        :class="classes.errorMessage"
        role="alert"
      >
        <MznIcon color="error" :icon="errorIconContent" :size="16" />
        <MznTypography :class="classes.errorMessageText">
          {{ errorMessageContent }}
        </MznTypography>
      </div>
      <div :class="[classes.actions, classes.actionsStatus(status)]">
        <template v-if="status === 'loading' && size !== 'minor' && !readable">
          <MznClearActions
            :aria-label="labels.cancelUpload"
            :class="classes.clearActionsIcon"
            type="embedded"
            variant="contrast"
            @click="emit('delete', $event)"
          />
          <div :aria-label="labels.uploading" :class="classes.loadingIcon">
            <MznSpin loading size="sub" />
          </div>
        </template>
        <template v-if="status === 'done' && size !== 'minor' && !readable">
          <div :class="classes.tools">
            <div :class="classes.toolsContent">
              <MznButton
                v-if="canZoomIn"
                :aria-label="labels.zoomIn"
                :icon="ZoomInIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onZoomIn"
              />
              <MznButton
                v-if="canDownload"
                :aria-label="labels.download"
                :icon="DownloadIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onDownload"
              />
              <MznButton
                :aria-label="labels.delete"
                :icon="TrashIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onDelete"
              />
            </div>
          </div>
          <span v-if="canReplace" :class="classes.replaceLabel">
            {{ labels.clickToReplace }}
          </span>
        </template>
        <template v-if="status === 'error' && size !== 'minor' && !readable">
          <div :class="classes.tools">
            <div :class="classes.toolsContent">
              <MznButton
                :aria-label="labels.reload"
                :icon="ResetIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="emit('reload', $event)"
              />
              <MznButton
                :aria-label="labels.delete"
                :icon="TrashIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="emit('delete', $event)"
              />
            </div>
          </div>
        </template>
        <MznIcon
          v-if="size === 'minor' && !readable"
          color="fixed-light"
          :icon="ZoomInIcon"
          :size="24"
        />
      </div>
    </div>
  </div>
</template>

// packages/ng/upload/upload-picture-card.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  output,
  signal,
} from '@angular/core';
import {
  uploadPictureCardClasses as classes,
  UploadItemStatus,
  UploadPictureCardImageFit,
  UploadPictureCardSize,
} from '@mezzanine-ui/core/upload';
import {
  DownloadIcon,
  FileIcon,
  IconDefinition,
  ImageIcon,
  ResetIcon,
  TrashIcon,
  ZoomInIcon,
} from '@mezzanine-ui/icons';
import { MznButton } from '@mezzanine-ui/ng/button';
import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznSpin } from '@mezzanine-ui/ng/spin';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import clsx from 'clsx';
import { extractFileNameFromUrl, isImageFile } from './upload-utils';

/**
 * Aria labels for the upload picture card sub-components.
 */
export interface UploadPictureCardAriaLabels {
  /** Aria label for cancel upload button. @default 'Cancel upload' */
  cancelUpload?: string;
  /** Aria label for the click-to-replace overlay label. @default 'Click to Replace' */
  clickToReplace?: string;
  /** Aria label for delete button. @default 'Delete file' */
  delete?: string;
  /** Aria label for download button. @default 'Download file' */
  download?: string;
  /** Aria label for reload/retry button. @default 'Retry upload' */
  reload?: string;
  /** Aria label for uploading status. @default 'Uploading' */
  uploading?: string;
  /** Aria label for zoom in button. @default 'Zoom in image' */
  zoomIn?: string;
}

/**
 * 以卡片形式呈現的上傳檔案元件，支援圖片與非圖片的預覽與操作。
 *
 * 根據 `status` 切換載入中、完成、錯誤三種外觀，並以 hover/focus 顯示下載、縮放、刪除、
 * 重試等操作。單檔 card 模式可透過 parent 組件觸發 `replaced` 事件進行替換。
 *
 * @example
 * ```html
 * import { MznUploadPictureCard } from '@mezzanine-ui/ng/upload';
 *
 * <div mznUploadPictureCard [file]="file" status="loading"
 *      (deleted)="onDelete($event)"></div>
 *
 * <div mznUploadPictureCard [url]="imageUrl" status="done" imageFit="cover"
 *      (zoomed)="onZoom($event)"
 *      (downloaded)="onDownload($event)"
 *      (deleted)="onDelete($event)"></div>
 * ```
 *
 * @see MznUpload
 */
@Component({
  selector: '[mznUploadPictureCard]',
  exportAs: 'mznUploadPictureCard',
  standalone: true,
  imports: [MznButton, MznIcon, MznSpin, MznClearActions, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.role]': '"group"',
    '[attr.aria-disabled]': 'disabled()',
    '[attr.tabindex]': 'hostTabIndex()',
    '(click)': 'onHostClick($event)',
    '(keydown)': 'onHostKeydown($event)',
  },
  template: `
    <div [class]="containerClass">
      @if (showImage()) {
        <img
          [alt]="resolvedFileName()"
          [src]="imageSrc()"
          [style.object-fit]="imageFit()"
          style="object-position: center;"
        />
      }
      @if (status() === 'done' && size() !== 'minor' && !resolvedIsImage()) {
        <div [class]="contentClass">
          <i mznIcon [icon]="fileIconDef" color="brand" [size]="16"></i>
          <p mznTypography [class]="nameClass" [ellipsis]="true">{{
            resolvedFileName()
          }}</p>
        </div>
      }
      @if (status() === 'error' && size() !== 'minor') {
        <div [class]="errorMessageClass" role="alert" aria-live="polite">
          <i mznIcon [icon]="resolvedErrorIcon()" color="error" [size]="16"></i>
          <p mznTypography [class]="errorMessageTextClass">{{
            resolvedErrorMessage()
          }}</p>
        </div>
      }
      <div [class]="actionsClasses()">
        @if (status() === 'loading' && size() !== 'minor' && !readable()) {
          <button
            mznClearActions
            type="embedded"
            variant="contrast"
            [class]="clearActionsIconClass"
            [attr.aria-label]="resolvedAriaLabels().cancelUpload"
            (clicked)="onDelete($event)"
          ></button>
          <div
            [class]="loadingIconClass"
            [attr.aria-label]="resolvedAriaLabels().uploading"
          >
            <div mznSpin [loading]="true" size="sub"></div>
          </div>
        }
        @if (status() === 'done' && size() !== 'minor' && !readable()) {
          <div [class]="toolsClass">
            <div [class]="toolsContentClass">
              @if (zoomInEnabled()) {
                <button
                  mznButton
                  variant="base-secondary"
                  size="minor"
                  iconType="icon-only"
                  [icon]="zoomInIconDef"
                  type="button"
                  [attr.aria-label]="resolvedAriaLabels().zoomIn"
                  (click)="onZoomIn($event)"
                >
                  <i mznIcon [icon]="zoomInIconDef" [size]="16"></i>
                </button>
              }
              @if (downloadEnabled()) {
                <button
                  mznButton
                  variant="base-secondary"
                  size="minor"
                  iconType="icon-only"
                  [icon]="downloadIconDef"
                  type="button"
                  [attr.aria-label]="resolvedAriaLabels().download"
                  (click)="onDownload($event)"
                >
                  <i mznIcon [icon]="downloadIconDef" [size]="16"></i>
                </button>
              }
              <button
                mznButton
                variant="base-secondary"
                size="minor"
                iconType="icon-only"
                [icon]="trashIconDef"
                type="button"
                [attr.aria-label]="resolvedAriaLabels().delete"
                (click)="onDelete($event)"
              >
                <i mznIcon [icon]="trashIconDef" [size]="16"></i>
              </button>
            </div>
          </div>
          @if (replaceEnabled()) {
            <span [class]="replaceLabelClass">
              {{ resolvedAriaLabels().clickToReplace }}
            </span>
          }
        }
        @if (status() === 'error' && size() !== 'minor' && !readable()) {
          <div [class]="toolsClass">
            <div [class]="toolsContentClass">
              <button
                mznButton
                variant="base-secondary"
                size="minor"
                iconType="icon-only"
                [icon]="resetIconDef"
                type="button"
                [attr.aria-label]="resolvedAriaLabels().reload"
                (click)="onReload($event)"
              >
                <i mznIcon [icon]="resetIconDef" [size]="16"></i>
              </button>
              <button
                mznButton
                variant="base-secondary"
                size="minor"
                iconType="icon-only"
                [icon]="trashIconDef"
                type="button"
                [attr.aria-label]="resolvedAriaLabels().delete"
                (click)="onDelete($event)"
              >
                <i mznIcon [icon]="trashIconDef" [size]="16"></i>
              </button>
            </div>
          </div>
        }
        @if (size() === 'minor' && !readable()) {
          <i mznIcon [icon]="zoomInIconDef" color="fixed-light" [size]="24"></i>
        }
      </div>
    </div>
  `,
})
export class MznUploadPictureCard {
  /** 要顯示的 File 物件。 */
  readonly file = input<File>();

  /** 檔案 URL（用於已上傳檔案顯示）。 */
  readonly url = input<string>();

  /** 檔案識別碼。 */
  readonly id = input<string>();

  /** 卡片狀態。@default 'loading' */
  readonly status = input<UploadItemStatus>('loading');

  /** 卡片尺寸。@default 'main' */
  readonly size = input<UploadPictureCardSize>('main');

  /** 圖片 object-fit。@default 'cover' */
  readonly imageFit = input<UploadPictureCardImageFit>('cover');

  /** 是否禁用。@default false */
  readonly disabled = input(false);

  /** 錯誤訊息（status='error' 時顯示）。 */
  readonly errorMessage = input<string>();

  /** 錯誤圖示。未提供時依是否為圖片回傳 ImageIcon / FileIcon。 */
  readonly errorIcon = input<IconDefinition>();

  /** 是否為唯讀模式（隱藏所有操作）。@default false */
  readonly readable = input(false);

  /** Aria 標籤（無障礙與 i18n）。 */
  readonly ariaLabels = input<UploadPictureCardAriaLabels>();

  /**
   * 是否啟用 Replace 模式。當為 true 且 status='done'、非 readable 時，
   * 點擊卡片會觸發 `replaced` 事件，並顯示 "Click to Replace" 標籤。
   *
   * @default false
   */
  readonly replaceEnabled = input(false);

  /** 是否顯示 Zoom 按鈕（done 狀態）。@default false */
  readonly zoomInEnabled = input(false);

  /** 是否顯示 Download 按鈕（done 狀態）。@default false */
  readonly downloadEnabled = input(false);

  /** 刪除按鈕被點擊。 */
  readonly deleted = output<MouseEvent>();

  /** 下載按鈕被點擊。 */
  readonly downloaded = output<MouseEvent>();

  /** 重試按鈕被點擊。 */
  readonly reloaded = output<MouseEvent>();

  /** Replace 模式下卡片被點擊。 */
  readonly replaced = output<MouseEvent>();

  /** Zoom 按鈕被點擊。 */
  readonly zoomed = output<MouseEvent>();

  // Icon defs
  protected readonly fileIconDef = FileIcon;
  protected readonly zoomInIconDef = ZoomInIcon;
  protected readonly downloadIconDef = DownloadIcon;
  protected readonly trashIconDef = TrashIcon;
  protected readonly resetIconDef = ResetIcon;

  // Class constants
  protected readonly containerClass = classes.container;
  protected readonly contentClass = classes.content;
  protected readonly nameClass = classes.name;
  protected readonly errorMessageClass = classes.errorMessage;
  protected readonly errorMessageTextClass = classes.errorMessageText;
  protected readonly clearActionsIconClass = classes.clearActionsIcon;
  protected readonly loadingIconClass = classes.loadingIcon;
  protected readonly toolsClass = classes.tools;
  protected readonly toolsContentClass = classes.toolsContent;
  protected readonly replaceLabelClass = classes.replaceLabel;

  private readonly _imageUrl = signal('');

  constructor() {
    // Manage blob URL lifecycle. When a File that is an image is provided,
    // create an object URL; clean up when inputs change or component is destroyed.
    effect((onCleanup) => {
      const file = this.file();
      const url = this.url();
      const image = isImageFile(file, url);

      if (url && image) {
        this._imageUrl.set(url);
        return;
      }

      if (file && image) {
        try {
          const blobUrl = URL.createObjectURL(file);

          this._imageUrl.set(blobUrl);
          onCleanup(() => URL.revokeObjectURL(blobUrl));
        } catch {
          this._imageUrl.set('');
        }
      } else {
        this._imageUrl.set('');
      }
    });
  }

  protected readonly resolvedIsImage = computed((): boolean =>
    isImageFile(this.file(), this.url()),
  );

  protected readonly showImage = computed(
    (): boolean =>
      this.resolvedIsImage() && !!this._imageUrl() && this.status() !== 'error',
  );

  protected readonly imageSrc = computed((): string => this._imageUrl());

  protected readonly resolvedFileName = computed((): string => {
    const file = this.file();
    const url = this.url();

    if (file?.name && !url) return file.name;
    if (url) return extractFileNameFromUrl(url);

    return '';
  });

  protected readonly resolvedAriaLabels = computed(
    (): Required<UploadPictureCardAriaLabels> => {
      const labels = this.ariaLabels() ?? {};

      return {
        cancelUpload: labels.cancelUpload ?? 'Cancel upload',
        clickToReplace: labels.clickToReplace ?? 'Click to Replace',
        delete: labels.delete ?? 'Delete file',
        download: labels.download ?? 'Download file',
        reload: labels.reload ?? 'Retry upload',
        uploading: labels.uploading ?? 'Uploading',
        zoomIn: labels.zoomIn ?? 'Zoom in image',
      };
    },
  );

  protected readonly resolvedErrorIcon = computed((): IconDefinition => {
    const custom = this.errorIcon();

    if (custom) return custom;

    return this.resolvedIsImage() ? ImageIcon : FileIcon;
  });

  protected readonly resolvedErrorMessage = computed((): string => {
    const custom = this.errorMessage();

    if (custom) return custom;

    return this.resolvedFileName() || 'Upload error';
  });

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.size(this.size()), {
      [classes.disabled]: this.disabled(),
      [classes.readable]: this.readable(),
      [classes.replaceMode]:
        !this.readable() && this.replaceEnabled() && this.status() === 'done',
    }),
  );

  protected readonly actionsClasses = computed((): string =>
    clsx(classes.actions, classes.actionsStatus(this.status())),
  );

  protected readonly hostTabIndex = computed((): number =>
    this.disabled() || this.readable() ? -1 : 0,
  );

  protected onDelete(event: MouseEvent): void {
    event.stopPropagation();
    this.deleted.emit(event);
  }

  protected onDownload(event: MouseEvent): void {
    event.stopPropagation();
    this.downloaded.emit(event);
  }

  protected onReload(event: MouseEvent): void {
    event.stopPropagation();
    this.reloaded.emit(event);
  }

  protected onZoomIn(event: MouseEvent): void {
    event.stopPropagation();
    this.zoomed.emit(event);
  }

  protected onHostClick(event: MouseEvent): void {
    if (!this.readable() && this.replaceEnabled() && this.status() === 'done') {
      this.replaced.emit(event);
    }
  }

  protected onHostKeydown(event: KeyboardEvent): void {
    if (
      !this.readable() &&
      this.replaceEnabled() &&
      this.status() === 'done' &&
      (event.key === 'Enter' || event.key === ' ')
    ) {
      event.preventDefault();
      (event.currentTarget as HTMLElement).click();
    }
  }
}
