// packages/vue/upload/upload-item.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ComponentPublicInstance } from 'vue';
import { uploadItemClasses as classes } from '@mezzanine-ui/core/upload';
import {
  DangerousFilledIcon,
  DownloadIcon,
  FileIcon,
  ResetIcon,
  TrashIcon,
} from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { resolveElement } from '../_internal/resolve-element';
import { useHasListener } from '../_internal/use-has-listener';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTooltip from '../tooltip/tooltip.vue';
import MznTypography from '../typography/typography.vue';
import MznUploadPictureCard from './upload-picture-card.vue';
import { isImageFile } from './upload-utils';
import type { UploadItemProps } from './upload-item.types';

/**
 * 上傳清單裡的一列。
 *
 * `type` 決定左邊放圖示還是縮圖，`status` 決定右邊放什麼：上傳中是轉圈加取消、
 * 完成是下載、錯誤是重試。完成或錯誤時最右邊還有刪除。檔名過長會截斷並以
 * tooltip 補完。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznUploadItem } from '@mezzanine-ui/vue/upload';
 * <\/script>
 *
 * <template>
 *   <MznUploadItem :file="file" status="done" @delete="onDelete" />
 * </template>
 * ```
 *
 * @see MznUpload 管理整個上傳清單的元件
 */
const props = withDefaults(defineProps<UploadItemProps>(), {
  disabled: false,
  errorIcon: undefined,
  errorMessage: undefined,
  file: undefined,
  fileSize: undefined,
  icon: undefined,
  id: undefined,
  showFileSize: true,
  size: 'main',
  status: 'loading',
  type: 'icon',
  url: undefined,
});

const emit = defineEmits<{
  /** Fired when the cancel icon is clicked. */
  cancel: [event: MouseEvent];
  /** Fired when the delete icon is clicked. */
  delete: [event: MouseEvent];
  /** Fired when the download icon is clicked. */
  download: [event: MouseEvent];
  /** Fired when the reload icon is clicked. */
  reload: [event: MouseEvent];
}>();

/** React spreads the rest onto the inner container, not onto the host. */
defineOptions({ inheritAttrs: false });

const hasListener = useHasListener();

/**
 * Bound as objects rather than with `@click`, because React leaves each handler
 * off entirely when the consumer gave none — and an icon with a click listener
 * draws a pointer cursor.
 */
const cancelBindings = computed(() => ({
  class: classes.closeIcon,
  onClick: hasListener('cancel')
    ? (event: MouseEvent) => emit('cancel', event)
    : undefined,
  role: 'button',
}));

const downloadBindings = computed(() => ({
  class: classes.downloadIcon,
  icon: DownloadIcon,
  onClick: hasListener('download')
    ? (event: MouseEvent) => emit('download', event)
    : undefined,
  size: 16,
}));

const reloadBindings = computed(() => ({
  class: classes.resetIcon,
  icon: ResetIcon,
  onClick: hasListener('reload')
    ? (event: MouseEvent) => emit('reload', event)
    : undefined,
  size: 16,
}));

const deleteBindings = computed(() => ({
  class: classes.deleteIcon,
  color: 'neutral-solid' as const,
  icon: TrashIcon,
  onClick: hasListener('delete')
    ? (event: MouseEvent) => emit('delete', event)
    : undefined,
  size: 16,
}));

const isImage = computed((): boolean => isImageFile(props.file, props.url));

const fileName = computed((): string => {
  if (props.file?.name && !props.url) return props.file.name;

  if (props.url) {
    try {
      const url = new URL(props.url);

      return url.pathname.split('/').pop() || '';
    } catch {
      const urlWithoutQuery = props.url.split('?')[0].split('#')[0];

      return urlWithoutQuery.split('/').pop() || '';
    }
  }

  return '';
});

const fileSize = computed((): string | null => {
  if (!props.file && !props.fileSize) return null;

  const bytes = props.file?.size ?? props.fileSize;

  if (bytes === 0) return '0 B';

  const k = 1024;
  const sizes = ['B', 'KB', 'MB'];
  let index = 0;
  let size = bytes ?? 0;

  while (size >= k && index < sizes.length - 1) {
    size /= k;
    index += 1;
  }

  return `${Math.round(size * 10) / 10} ${sizes[index]}`;
});

const isFinished = computed((): boolean => /done|error/.test(props.status));

const shouldShowFileSize = computed((): boolean =>
  Boolean(props.showFileSize && isFinished.value && fileSize.value),
);

const shouldSingleLineCenter = computed((): boolean =>
  Boolean(
    props.type === 'thumbnail' && fileName.value && !shouldShowFileSize.value,
  ),
);

watch(
  [(): File | undefined => props.file, (): string | undefined => props.url],
  ([file, url]) => {
    if (!file && !url) {
      console.warn(
        'UploadItem: Both `file` and `url` props are missing. At least one should be provided to display the upload item.',
      );
    }
  },
  { immediate: true },
);

const nameElement = ref<HTMLElement | null>(null);
const isTextTruncated = ref(false);

/** Measured once the name is laid out, exactly as React's layout effect does. */
watch(
  [nameElement, fileName, (): string => props.size],
  () => {
    const element = nameElement.value;

    if (!element) {
      isTextTruncated.value = false;

      return;
    }

    isTextTruncated.value = element.scrollWidth > element.clientWidth;
  },
  { flush: 'post', immediate: true },
);

function setName(element: Element | ComponentPublicInstance | null): void {
  nameElement.value = resolveElement(element);
}

const hostClasses = computed((): string =>
  clsx(classes.host, classes.size(props.size), {
    [classes.alignCenter]: props.status !== 'done',
    [classes.disabled]: props.disabled,
    [classes.error]: props.status === 'error',
    [classes.singleLineContent]: shouldSingleLineCenter.value,
  }),
);

const TOOLTIP_OPTIONS = { placement: 'bottom' as const };
</script>

<template>
  <div :class="hostClasses">
    <div
      v-bind="$attrs"
      :aria-disabled="disabled"
      :class="classes.container"
      role="group"
      :tabindex="disabled ? -1 : 0"
    >
      <div :class="classes.contentWrapper">
        <div :class="classes.icon">
          <template v-if="type === 'thumbnail'">
            <MznUploadPictureCard
              v-if="isImage"
              :class="classes.thumbnail"
              :file="file"
              size="minor"
              :url="url"
            />
            <div v-else :class="classes.thumbnail">
              <MznIcon :class="classes.icon" :icon="FileIcon" :size="16" />
            </div>
          </template>
          <MznIcon
            v-else
            :class="classes.icon"
            :icon="icon ?? FileIcon"
            :size="16"
          />
        </div>
        <div :class="classes.content">
          <MznTooltip
            :options="TOOLTIP_OPTIONS"
            :title="isTextTruncated ? fileName : undefined"
          >
            <template #default="tooltip">
              <MznTypography
                :ref="
                  (element) => {
                    setName(element);
                    tooltip.ref(element);
                  }
                "
                :class="classes.name"
                ellipsis
                @mouseenter="tooltip.onMouseenter"
                @mouseleave="tooltip.onMouseleave"
              >
                {{ fileName }}
              </MznTypography>
            </template>
          </MznTooltip>
          <MznTypography v-if="shouldShowFileSize" :class="classes.fontSize">
            {{ fileSize }}
          </MznTypography>
        </div>
      </div>
      <div :class="classes.actions">
        <template v-if="status === 'loading'">
          <div :class="classes.loadingIcon">
            <MznSpin loading size="minor" />
          </div>
          <MznClearActions v-bind="cancelBindings" />
        </template>
        <MznIcon
          v-if="status === 'done' && !disabled"
          v-bind="downloadBindings"
        />
        <MznIcon
          v-if="status === 'error' && !disabled"
          v-bind="reloadBindings"
        />
      </div>
    </div>
    <div v-if="isFinished && !disabled" :class="classes.deleteContent">
      <MznIcon v-bind="deleteBindings" />
    </div>
  </div>
  <div v-if="status === 'error' && errorMessage" :class="classes.errorMessage">
    <MznIcon
      :class="classes.errorIcon"
      color="error"
      :icon="errorIcon ?? DangerousFilledIcon"
      :size="14"
    />
    <MznTypography
      :class="classes.errorMessageText"
      color="text-error"
      variant="caption"
    >
      {{ errorMessage }}
    </MznTypography>
  </div>
</template>

// packages/ng/upload/upload-item.component.ts
import {
  AfterViewChecked,
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import {
  uploadItemClasses as classes,
  UploadItemSize,
  UploadItemStatus,
  UploadItemType,
} from '@mezzanine-ui/core/upload';
import {
  CloseIcon,
  DangerousFilledIcon,
  DownloadIcon,
  FileIcon,
  IconDefinition,
  ResetIcon,
  SpinnerIcon,
  TrashIcon,
} from '@mezzanine-ui/icons';
import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznSpin } from '@mezzanine-ui/ng/spin';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import clsx from 'clsx';
import { extractFileNameFromUrl, isImageFile } from './upload-utils';
import { MznUploadPictureCard } from './upload-picture-card.component';

/**
 * 單一上傳檔案的列表項目元件。
 *
 * 根據 `status` 渲染三種狀態：`loading`（旋轉圖 + 取消）、`done`（下載）、`error`（重試）。
 * 檔案結束（`done` / `error`）時額外顯示刪除按鈕。`type` 為 `'thumbnail'` 時以縮圖呈現，
 * 圖片檔案會內嵌 `MznUploadPictureCard` 作為縮圖。
 *
 * @example
 * ```html
 * import { MznUploadItem } from '@mezzanine-ui/ng/upload';
 *
 * <div mznUploadItem
 *   [file]="file"
 *   status="done"
 *   (delete)="onDelete($event)"
 *   (download)="onDownload($event)"
 * ></div>
 * ```
 *
 * @see MznUpload
 */
@Component({
  selector: '[mznUploadItem]',
  exportAs: 'mznUploadItem',
  standalone: true,
  imports: [
    MznIcon,
    MznTypography,
    MznSpin,
    MznClearActions,
    MznUploadPictureCard,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
  },
  template: `
    <div
      [class]="containerClass"
      role="group"
      [attr.aria-disabled]="disabled()"
      [attr.tabindex]="disabled() ? -1 : 0"
    >
      <div [class]="contentWrapperClass">
        <div [class]="iconWrapperClass">
          @if (type() === 'thumbnail') {
            @if (resolvedIsImage()) {
              <div
                mznUploadPictureCard
                size="minor"
                [file]="file()"
                [url]="url()"
                [class]="thumbnailClass"
              ></div>
            } @else {
              <div [class]="thumbnailClass">
                <i
                  mznIcon
                  [icon]="fileIcon"
                  [class]="iconClass"
                  [size]="16"
                ></i>
              </div>
            }
          } @else {
            <i
              mznIcon
              [icon]="resolvedIcon()"
              [class]="iconClass"
              [size]="16"
            ></i>
          }
        </div>
        <div [class]="contentClass">
          <p #nameEl mznTypography [class]="nameClass" [ellipsis]="true">{{
            resolvedFileName()
          }}</p>
          @if (shouldShowFileSize()) {
            <p mznTypography [class]="fontSizeClass">{{
              formattedFileSize()
            }}</p>
          }
        </div>
      </div>
      <div [class]="actionsClass">
        @if (status() === 'loading') {
          <div [class]="loadingIconClass">
            <div mznSpin [loading]="true" size="minor"></div>
          </div>
          <button
            mznClearActions
            type="standard"
            [class]="closeIconClass"
            (clicked)="onCancel($event)"
          ></button>
        }
        @if (status() === 'done' && !disabled()) {
          <i
            mznIcon
            [icon]="downloadIconDef"
            [class]="downloadIconClass"
            [size]="16"
            (click)="onDownload($event)"
          ></i>
        }
        @if (status() === 'error' && !disabled()) {
          <i
            mznIcon
            [icon]="resetIconDef"
            [class]="resetIconClass"
            [size]="16"
            (click)="onReload($event)"
          ></i>
        }
      </div>
    </div>
    @if (isFinished() && !disabled()) {
      <div [class]="deleteContentClass">
        <i
          mznIcon
          [icon]="trashIconDef"
          [class]="deleteIconClass"
          [size]="16"
          color="neutral-solid"
          (click)="onDelete($event)"
        ></i>
      </div>
    }
    @if (status() === 'error' && errorMessage()) {
      <div [class]="errorMessageClass">
        <i
          mznIcon
          [icon]="resolvedErrorIcon()"
          [class]="errorIconClass"
          [size]="14"
          color="error"
        ></i>
        <p
          mznTypography
          color="text-error"
          variant="caption"
          [class]="errorMessageTextClass"
          >{{ errorMessage() }}</p
        >
      </div>
    }
  `,
})
export class MznUploadItem implements AfterViewChecked {
  /** 要顯示的 File 物件（優先於 url 用於檔名與大小）。 */
  readonly file = input<File>();

  /** 檔案 URL。當 file 未提供時用於顯示與判斷圖片類型。 */
  readonly url = input<string>();

  /** 檔案識別碼。 */
  readonly id = input<string>();

  /**
   * 預覽形式：
   * - `'icon'` 顯示檔案圖示
   * - `'thumbnail'` 顯示縮圖（圖片檔案內嵌 MznUploadPictureCard）
   *
   * @default 'icon'
   */
  readonly type = input<UploadItemType>('icon');

  /** 上傳項目的尺寸。@default 'main' */
  readonly size = input<UploadItemSize>('main');

  /** 上傳項目的狀態。@default 'loading' */
  readonly status = input<UploadItemStatus>('loading');

  /** 明確指定的檔案大小（bytes），優先於 file.size。 */
  readonly fileSize = input<number>();

  /** 是否顯示檔案大小（done/error 狀態且有大小資料時）。@default true */
  readonly showFileSize = input(true);

  /** 是否禁用操作按鈕。@default false */
  readonly disabled = input(false);

  /** 錯誤訊息，僅在 status 為 'error' 時顯示。 */
  readonly errorMessage = input<string>();

  /** 自訂錯誤圖示。未提供時使用 DangerousFilledIcon。 */
  readonly errorIcon = input<IconDefinition>();

  /** 自訂檔案類型圖示。未提供時使用 FileIcon。 */
  readonly icon = input<IconDefinition>();

  /** 覆寫自動解析的檔名。 */
  readonly fileName = input<string>();

  /** 保留兼容舊版的 thumbnail URL（等同 url）。 */
  readonly thumbnailUrl = input<string>();

  /** 使用者點擊取消（loading 狀態）。 */
  readonly cancel = output<MouseEvent>();

  /** 使用者點擊下載（done 狀態）。 */
  readonly download = output<MouseEvent>();

  /** 使用者點擊重新上傳（error 狀態）。 */
  readonly reload = output<MouseEvent>();

  /** 使用者點擊刪除（finished 狀態）。 */
  readonly delete = output<MouseEvent>();

  /** 保留兼容舊版 API 的 remove 輸出（同 delete）。 */
  readonly remove = output<MouseEvent>();

  // Icon defs (constants)
  protected readonly fileIcon = FileIcon;
  protected readonly closeIconDef = CloseIcon;
  protected readonly downloadIconDef = DownloadIcon;
  protected readonly resetIconDef = ResetIcon;
  protected readonly spinnerIconDef = SpinnerIcon;
  protected readonly trashIconDef = TrashIcon;

  // Class constants
  protected readonly containerClass = classes.container;
  protected readonly iconClass = classes.icon;
  protected readonly thumbnailClass = classes.thumbnail;
  protected readonly contentWrapperClass = classes.contentWrapper;
  protected readonly contentClass = classes.content;
  protected readonly nameClass = classes.name;
  protected readonly fontSizeClass = classes.fontSize;
  protected readonly actionsClass = classes.actions;
  protected readonly closeIconClass = classes.closeIcon;
  protected readonly deleteContentClass = classes.deleteContent;
  protected readonly deleteIconClass = classes.deleteIcon;
  protected readonly downloadIconClass = classes.downloadIcon;
  protected readonly errorMessageClass = classes.errorMessage;
  protected readonly errorIconClass = classes.errorIcon;
  protected readonly errorMessageTextClass = classes.errorMessageText;
  protected readonly loadingIconClass = classes.loadingIcon;
  protected readonly resetIconClass = classes.resetIcon;
  protected readonly iconWrapperClass = classes.icon;

  private readonly _nameEl =
    viewChild<ElementRef<HTMLParagraphElement>>('nameEl');

  private readonly _isTruncated = signal(false);

  protected readonly resolvedIsImage = computed((): boolean =>
    isImageFile(this.file(), this.url() ?? this.thumbnailUrl()),
  );

  protected readonly resolvedIcon = computed(
    (): IconDefinition => this.icon() ?? FileIcon,
  );

  protected readonly resolvedErrorIcon = computed(
    (): IconDefinition => this.errorIcon() ?? DangerousFilledIcon,
  );

  protected readonly resolvedFileName = computed((): string => {
    const explicit = this.fileName();

    if (explicit) return explicit;

    const file = this.file();
    const url = this.url() ?? this.thumbnailUrl();

    if (file?.name && !url) return file.name;
    if (url) return extractFileNameFromUrl(url);

    return '';
  });

  protected readonly isFinished = computed((): boolean =>
    /done|error/.test(this.status()),
  );

  protected readonly formattedFileSize = computed((): string => {
    const file = this.file();
    const explicit = this.fileSize();
    const bytes = file?.size ?? explicit;

    if (bytes == null) return '';
    if (bytes === 0) return '0 B';

    const k = 1024;
    const units = ['B', 'KB', 'MB'];
    let size = bytes;
    let i = 0;

    while (size >= k && i < units.length - 1) {
      size /= k;
      i += 1;
    }

    return `${Math.round(size * 10) / 10} ${units[i]}`;
  });

  protected readonly shouldShowFileSize = computed((): boolean => {
    if (!this.showFileSize()) return false;
    if (!this.isFinished()) return false;

    return this.formattedFileSize().length > 0;
  });

  protected readonly shouldSingleLineCenter = computed((): boolean =>
    Boolean(
      this.type() === 'thumbnail' &&
        this.resolvedFileName() &&
        !this.shouldShowFileSize(),
    ),
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.size(this.size()), {
      [classes.alignCenter]: this.status() !== 'done',
      [classes.error]: this.status() === 'error',
      [classes.disabled]: this.disabled(),
      [classes.singleLineContent]: this.shouldSingleLineCenter(),
    }),
  );

  ngAfterViewChecked(): void {
    const el = this._nameEl()?.nativeElement;

    if (!el) {
      if (this._isTruncated()) this._isTruncated.set(false);
      return;
    }

    const isTruncated = el.scrollWidth > el.clientWidth;

    if (isTruncated !== this._isTruncated()) {
      this._isTruncated.set(isTruncated);
    }
  }

  protected onCancel(event: MouseEvent): void {
    event.stopPropagation();
    this.cancel.emit(event);
  }

  protected onDownload(event: MouseEvent): void {
    event.stopPropagation();
    this.download.emit(event);
  }

  protected onReload(event: MouseEvent): void {
    event.stopPropagation();
    this.reload.emit(event);
  }

  protected onDelete(event: MouseEvent): void {
    event.stopPropagation();
    this.delete.emit(event);
    this.remove.emit(event);
  }
}
