// packages/react/src/Tag/Tag.tsx
import {
  DetailedHTMLProps,
  forwardRef,
  HTMLAttributes,
  MouseEventHandler,
} from 'react';
import { tagClasses as classes, TagSize } from '@mezzanine-ui/core/tag';
import { TimesIcon } from '@mezzanine-ui/icons';
import { cx } from '../utils/cx';
import Icon from '../Icon';

export interface TagProps extends DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement> {
  /**
   * Whether the tag can be closed.
   * @default false
   */
  closable?: boolean;
  /**
   * Whether the tag disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Callback executed while tag closed.
   */
  onClose?: MouseEventHandler;
  /**
   * The size of the tag.
   * @default 'medium'
   */
  size?: TagSize;
}

/**
 * The react component for `mezzanine` tag.
 */
const Tag = forwardRef<HTMLSpanElement, TagProps>(function Tag(props, ref) {
  const {
    children,
    className,
    closable = false,
    disabled = false,
    onClose,
    size = 'medium',
    ...rest
  } = props;

  return (
    <span
      {...rest}
      ref={ref}
      aria-disabled={disabled}
      className={cx(
        classes.host,
        classes.size(size),
        {
          [classes.disabled]: disabled,
        },
        className,
      )}
    >
      <span className={classes.label}>{children}</span>
      {closable && (
        <Icon
          className={classes.closeIcon}
          icon={TimesIcon}
          onClick={(event) => {
            if (!disabled && onClose) {
              onClose(event);
            }
          }}
          tabIndex={-1}
        />
      )}
    </span>
  );
});

export default Tag;

// packages/ng/src/tag/tag.component.ts
import { tagClasses as classes, TagSize } from '@mezzanine-ui/core/tag';
import { TimesIcon } from '@mezzanine-ui/icons';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  HostBinding,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { HostBindingEnumClass, InputBoolean } from '../core';

/**
 * The ng component for `mezzanine` tag.
 */
@Component({
  selector: 'mzn-tag',
  exportAs: 'mznTag',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <span [class]="classes.label">
      <ng-content></ng-content>
    </span>
    <i
      *ngIf="closable"
      [mzn-icon]="closeIcon"
      [class]="classes.closeIcon"
      (click)="onClose($event)"
      tabIndex="-1"
    ></i>
  `,
})
export class MznTagComponent {
  @HostBinding(`class.${classes.host}`)
  readonly bindHostClass = true;

  readonly classes = classes;

  readonly closeIcon = TimesIcon;

  /**
   * Whether the tag can be closed.
   * @default false
   */
  @Input()
  @InputBoolean()
  closable = false;

  /**
   * Whether the tag disabled.
   * @default false
   */
  @HostBinding('attr.aria-disabled')
  @HostBinding(`class.${classes.disabled}`)
  @Input()
  @InputBoolean()
  disabled = false;

  /**
   * The size of the tag.
   * @default 'medium'
   */
  @HostBindingEnumClass(classes.size, [
    'small',
    'medium',
    'large',
  ])
  @Input()
  size: TagSize = 'medium';

  // eslint-disable-next-line @angular-eslint/no-output-native
  @Output()
  readonly close = new EventEmitter<MouseEvent>();

  onClose(event: MouseEvent) {
    if (!this.disabled) {
      this.close.emit(event);
    }
  }
}
