// packages/vue/accordion/accordion.vue
<script setup lang="ts">
import { computed, h, provide, ref, useSlots } from 'vue';
import type { FunctionalComponent, VNode } from 'vue';
import { accordionClasses as classes } from '@mezzanine-ui/core/accordion';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import { useHasListener } from '../_internal/use-has-listener';
import MznFade from '../transition/fade.vue';
import MznAccordionContent from './accordion-content.vue';
import MznAccordionTitle from './accordion-title.vue';
import { ACCORDION_CONTROL_CONTEXT } from './accordion-control-context';
import type { AccordionProps } from './accordion.types';

/**
 * 手風琴元件，提供可展開／收合的內容區塊。
 *
 * 標題可以用 `title` 直接給文字，或放一個 MznAccordionTitle 自己排版；內容放在
 * MznAccordionContent 裡，沒有包的子項會自動被收進去。給了 `expanded` 就是受控
 * 模式，內部狀態不再變動，開合都由 `change` 通知。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznAccordion } from '@mezzanine-ui/vue/accordion';
 * <\/script>
 *
 * <template>
 *   <MznAccordion title="常見問題">這裡是問題的詳細說明內容。</MznAccordion>
 * </template>
 * ```
 *
 * @see MznAccordionGroup 管理多個手風琴的群組元件
 */
const props = withDefaults(defineProps<AccordionProps>(), {
  actions: undefined,
  defaultExpanded: false,
  disabled: false,
  expanded: undefined,
  size: 'main',
  title: undefined,
});

const emit = defineEmits<{
  /** Fired when the expand/collapse state is changed. */
  change: [expanded: boolean];
}>();

defineSlots<{
  /**
   * The title and the content. A MznAccordionTitle becomes the title and a
   * MznAccordionContent the content; anything else becomes content too.
   */
  default?: () => unknown;
}>();

const slots = useSlots();
const hasListener = useHasListener();

const internalExpanded = ref(props.defaultExpanded);

/**
 * A consumer that listens takes over the state entirely: React swaps its own
 * setter out for the callback rather than calling both.
 */
function onToggleExpanded(newStatus: boolean): void {
  if (hasListener('change')) emit('change', newStatus);
  else internalExpanded.value = newStatus;
}

const expanded = computed(
  (): boolean => props.expanded ?? internalExpanded.value,
);

/**
 * The title and the content are picked out of the slot by which component they
 * are; whatever is left over is content that was written without a wrapper, so
 * it gets one.
 */
const resolved = computed(
  (): { content: VNode | null; title: VNode | null } => {
    let title: VNode | null = null;
    let content: VNode | null = null;
    const restContentChildren: VNode[] = [];

    flattenChildren(slots.default?.(), { keepText: true }).forEach((child) => {
      if (child.type === MznAccordionTitle) {
        if (title) {
          console.warn(
            '[Mezzanine][Accordion] Only one AccordionTitle is allowed as children of Accordion.',
          );
        }

        title = child;
      } else if (child.type === MznAccordionContent) {
        if (content) {
          console.warn(
            '[Mezzanine][Accordion] Only one AccordionContent is allowed as children of Accordion.',
          );
        }

        content = child;
      } else {
        restContentChildren.push(child);
      }
    });

    if (restContentChildren.length > 0) {
      if (content || title) {
        console.warn(
          '[Mezzanine][Accordion] When AccordionTitle or AccordionContent is used as children. Please wrap other children with AccordionContent.',
        );
      }

      const existing = (content as VNode | null)?.children as
        | { default?: () => unknown }
        | undefined;

      content = h(
        MznAccordionContent,
        (content as VNode | null)?.props ?? null,
        { default: () => [existing?.default?.(), ...restContentChildren] },
      );
    }

    return { content, title };
  },
);

const titleId = computed(
  (): string | undefined =>
    (resolved.value.title?.props?.id as string | undefined) ?? undefined,
);

provide(
  ACCORDION_CONTROL_CONTEXT,
  computed(() => ({
    contentId: titleId.value ? `${titleId.value}-content` : undefined,
    disabled: props.disabled,
    expanded: expanded.value,
    titleId: titleId.value,
    toggleExpanded: onToggleExpanded,
  })),
);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.size(props.size), {
    [classes.hostDisabled]: props.disabled,
  }),
);

const fadeDuration = {
  enter: MOTION_DURATION.moderate,
  exit: MOTION_DURATION.moderate,
};
const fadeEasing = {
  enter: MOTION_EASING.entrance,
  exit: MOTION_EASING.exit,
};

const ResolvedTitle: FunctionalComponent = () => resolved.value.title;
const ResolvedContent: FunctionalComponent = () => resolved.value.content;
</script>

<template>
  <div :class="hostClasses">
    <MznAccordionTitle v-if="title" :actions="actions">
      {{ title }}
    </MznAccordionTitle>
    <ResolvedTitle v-else />

    <MznFade :duration="fadeDuration" :easing="fadeEasing" :in="expanded">
      <div><ResolvedContent /></div>
    </MznFade>
  </div>
</template>

// packages/react/src/Accordion/Accordion.tsx
import React, {
  forwardRef,
  useState,
  useCallback,
  useMemo,
  Children,
  ReactElement,
  cloneElement,
} from 'react';
import { accordionClasses as classes } from '@mezzanine-ui/core/accordion';
import { AccordionControlContext } from './AccordionControlContext';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { cx } from '../utils/cx';
import { Fade } from '../Transition';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import AccordionTitle, { AccordionTitleProps } from './AccordionTitle';
import AccordionActions from './AccordionActions';
import { flattenChildren } from '../utils/flatten-children';
import AccordionContent, { AccordionContentProps } from './AccordionContent';

export interface AccordionProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'onChange'> {
  /**
   * The content of the component. <br />
   * The first child will be treated as the title of the accordion, and the rest will be treated as the content of the accordion.
   * You can also use `title` prop to set the title of the accordion, then all children will be treated as the content of the accordion.
   */
  children: React.ReactNode;
  /**
   * If true, expands the accordion by default.
   * @default false
   */
  defaultExpanded?: boolean;
  /**
   * If true, the accordion will be displayed in a disabled state.
   * @default false
   */
  disabled?: boolean;
  /**
   * If true, expands the accordion, otherwise collapse it. Setting this prop enables control over the accordion.
   */
  expanded?: boolean;
  /**
   * Callback fired when the expand/collapse state is changed.
   */
  onChange?(e: boolean): void;
  /**
   * The size of accordion.
   * @default 'main'
   */
  size?: 'main' | 'sub';
  /**
   * The title of accordion.
   */
  title?: string;
  /**
   * The actions displayed on the right side of the accordion title. <br />
   */
  actions?: AccordionTitleProps['actions'];
}

const resolveChildren = (children: React.ReactNode) => {
  let title: ReactElement<AccordionTitleProps> | null = null;
  let content: ReactElement<AccordionContentProps> | null = null;
  const restContentChildren: React.ReactNode[] = [];

  flattenChildren(children).forEach((child) => {
    if (React.isValidElement(child) && child.type === AccordionTitle) {
      if (title) {
        console.warn(
          '[Mezzanine][Accordion] Only one AccordionTitle is allowed as children of Accordion.',
        );
      }

      title = child as ReactElement<AccordionTitleProps>;
    } else if (React.isValidElement(child) && child.type === AccordionContent) {
      if (content) {
        console.warn(
          '[Mezzanine][Accordion] Only one AccordionContent is allowed as children of Accordion.',
        );
      }

      content = child as ReactElement<AccordionContentProps>;
    } else {
      if (content || title) {
        console.warn(
          '[Mezzanine][Accordion] When <AccordionTitle> or <AccordionContent> is used as children. Please wrap other children with AccordionContent.',
        );
      }

      restContentChildren.push(child);
    }
  });

  if (!content) {
    content = <AccordionContent />;
  }

  if (restContentChildren.length > 0) {
    content = cloneElement(content, {
      children: [content.props.children, ...restContentChildren],
    });
  }

  return {
    title,
    content,
    restContentChildren,
  };
};

const Accordion = forwardRef<HTMLDivElement, AccordionProps>(
  function Accordion(props, ref) {
    const {
      actions,
      children: childrenProp,
      className,
      defaultExpanded = false,
      disabled = false,
      expanded: expandedProp,
      onChange,
      size = 'main',
      title,
      ...rest
    } = props;

    const [expanded, toggleExpanded] = useState<boolean>(
      defaultExpanded || false,
    );

    const onToggleExpanded = useCallback(
      (newStatus: boolean) => {
        if (typeof onChange === 'function') {
          onChange(newStatus);
        } else {
          toggleExpanded(newStatus);
        }
      },
      [onChange],
    );

    const { title: resolvedTitle, content: resolvedContent } = useMemo(
      () => resolveChildren(childrenProp),
      [childrenProp],
    );

    const contextValue = useMemo(
      () => ({
        contentId:
          resolvedTitle && (resolvedTitle as ReactElement<any>)?.props?.id
            ? `${(resolvedTitle as ReactElement<any>).props.id}-content`
            : undefined,
        disabled,
        expanded: expandedProp || expanded,
        titleId:
          (resolvedTitle && (resolvedTitle as ReactElement<any>)?.props?.id) ??
          undefined,
        toggleExpanded: onToggleExpanded,
      }),
      [disabled, expandedProp, expanded, onToggleExpanded, resolvedTitle],
    );

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(classes.host, classes.size(size), className)}
      >
        <AccordionControlContext.Provider value={contextValue}>
          {title ? (
            <AccordionTitle actions={actions}>{title}</AccordionTitle>
          ) : (
            resolvedTitle
          )}

          <Fade
            duration={{
              enter: MOTION_DURATION.moderate,
              exit: MOTION_DURATION.moderate,
            }}
            easing={{
              enter: MOTION_EASING.entrance,
              exit: MOTION_EASING.exit,
            }}
            in={expandedProp || expanded}
          >
            {<div>{resolvedContent}</div>}
          </Fade>
        </AccordionControlContext.Provider>
      </div>
    );
  },
);

export default Accordion;
