// packages/vue/slider/slider.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ComponentPublicInstance, CSSProperties } from 'vue';
import {
  fixRangeSliderValue,
  fixSingleSliderValue,
  isRangeSlider,
  roundToStep,
  sliderClasses as classes,
  sortSliderValue,
} from '@mezzanine-ui/core/slider';
import type { RangeSliderValue } from '@mezzanine-ui/core/slider';
import { spacingPrefix } from '@mezzanine-ui/system/spacing';
import clsx from 'clsx';
import { resolveNumericCSSVariable } from '../_internal/css-variable';
import { useHasListener } from '../_internal/use-has-listener';
import MznIcon from '../icon/icon.vue';
import MznInput from '../input/input.vue';
import type { InputProps } from '../input/input.types';
import MznTooltip from '../tooltip/tooltip.vue';
import type { PopperOptions } from '../popper/popper.types';
import MznTypography from '../typography/typography.vue';
import { useSlider } from './use-slider';
import type { SliderProps } from './slider.types';

/**
 * 滑桿元件，值的型別決定渲染出單一把手還是範圍。
 *
 * 完全受控：`value` 一定要給，並且以 `change` 把新值寫回。給 `withInput` 會在
 * 兩側加上數字輸入框（範圍模式兩個、單值模式一個），給 `prefixIcon` 與
 * `suffixIcon` 則加上可點擊的加減圖示；沒有另外監聽 `prefix-icon-click` /
 * `suffix-icon-click` 時，圖示預設就是以 `step` 增減。`withTick` 可標出刻度，
 * 給數字表示等分、給陣列表示實際的值。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { ref } from 'vue';
 * import { MznSlider } from '@mezzanine-ui/vue/slider';
 * import { MinusIcon, PlusIcon } from '@mezzanine-ui/icons';
 *
 * const value = ref(30);
 * const range = ref<[number, number]>([10, 50]);
 * <\/script>
 *
 * <template>
 *   <MznSlider :value="value" with-input @change="value = $event" />
 *   <MznSlider
 *     :prefix-icon="MinusIcon"
 *     :suffix-icon="PlusIcon"
 *     :value="range"
 *     @change="range = $event"
 *   />
 *   <MznSlider :value="value" :with-tick="3" @change="value = $event" />
 * </template>
 * ```
 *
 * @see useSlider 拖曳與 CSS 變數的 composable
 * @see MznInput withInput 用到的輸入框
 */
const props = withDefaults(defineProps<SliderProps>(), {
  disabled: undefined,
  max: 100,
  min: 0,
  prefixIcon: undefined,
  step: 1,
  suffixIcon: undefined,
  withInput: undefined,
  withTick: undefined,
});

const emit = defineEmits<{
  change: [value: number | RangeSliderValue];
  prefixIconClick: [];
  suffixIconClick: [];
}>();

const hasListener = useHasListener();

const {
  activeHandleIndex,
  cssVars,
  handleClickTrackOrRail,
  handlePress,
  railRef,
} = useSlider({
  max: () => props.max,
  min: () => props.min,
  onChange: (next) => emit('change', next as number | RangeSliderValue),
  step: () => props.step,
  value: () => props.value,
});

const isRange = computed((): boolean => isRangeSlider(props.value));

/**
 * React branches on the handler prop being present; Vue has to ask whether the
 * consumer attached a listener, and has to ask afresh on every render.
 */
function changeable(): boolean {
  return hasListener('change');
}

function iconClickable(): boolean {
  return !props.disabled && changeable();
}

function shouldHaveInputHandlers(): boolean {
  return Boolean(props.withInput) && changeable() && !props.disabled;
}

const startInputValue = ref(
  isRangeSlider(props.value) ? `${props.value[0]}` : '',
);
const endInputValue = ref(
  isRangeSlider(props.value) ? `${props.value[1]}` : `${props.value}`,
);

watch([() => props.min, () => props.max, () => props.value], () => {
  const { max, min, value } = props;

  if (max <= min) return;

  if (isRangeSlider(value)) {
    if (
      (value[0] > max && value[1] > max) ||
      (value[0] < min && value[1] < min) ||
      value[0] < min ||
      value[1] > max
    ) {
      emit('change', fixRangeSliderValue(value, min, max));
    }

    return;
  }

  if (value < min || value > max) {
    emit('change', fixSingleSliderValue(value, min, max));
  }
});

watch([() => props.value, () => props.withInput], () => {
  const { value, withInput } = props;

  if (!withInput) return;

  if (isRangeSlider(value)) {
    startInputValue.value = `${value[0]}`;
    endInputValue.value = `${value[1]}`;

    return;
  }

  endInputValue.value = value.toString();
});

function preventValueOverflow(target: number): number {
  const { max, min, step } = props;

  if (target > max) {
    return max;
  }

  if (target < min) {
    return min;
  }

  return roundToStep(target, step, min, max);
}

function handleIconKeydown(event: KeyboardEvent, handler: () => void): void {
  if (!iconClickable()) return;

  if (event.key === 'Enter') {
    handler();

    return;
  }

  if (event.key === ' ') {
    event.preventDefault();
    handler();
  }
}

function handlePrefixIconClick(): void {
  if (!iconClickable()) return;

  if (hasListener('prefixIconClick')) {
    emit('prefixIconClick');

    return;
  }

  const { step, value } = props;

  if (isRangeSlider(value)) {
    emit('change', [preventValueOverflow(value[0] - step), value[1]]);
  } else {
    emit('change', preventValueOverflow(value - step));
  }
}

function handleSuffixIconClick(): void {
  if (!iconClickable()) return;

  if (hasListener('suffixIconClick')) {
    emit('suffixIconClick');

    return;
  }

  const { step, value } = props;

  if (isRangeSlider(value)) {
    emit('change', [value[0], preventValueOverflow(value[1] + step)]);
  } else {
    emit('change', preventValueOverflow(value + step));
  }
}

function handlePrefixIconKeydown(event: KeyboardEvent): void {
  handleIconKeydown(event, handlePrefixIconClick);
}

function handleSuffixIconKeydown(event: KeyboardEvent): void {
  handleIconKeydown(event, handleSuffixIconClick);
}

function handleTrackOrRailMousedown(event: MouseEvent): void {
  if (!changeable()) return;

  handleClickTrackOrRail?.(event);
}

function onStartInputChange(event: Event): void {
  if (!shouldHaveInputHandlers()) return;

  startInputValue.value = (event.target as HTMLInputElement).value;
}

function onEndInputChange(event: Event): void {
  if (!shouldHaveInputHandlers()) return;

  endInputValue.value = (event.target as HTMLInputElement).value;
}

function onStartInputBlur(): void {
  const { value } = props;

  if (!isRangeSlider(value)) return;

  emit(
    'change',
    sortSliderValue([
      value[1],
      preventValueOverflow(Number(startInputValue.value)),
    ]),
  );
}

function onEndInputBlur(): void {
  const { value } = props;

  if (isRangeSlider(value)) {
    emit(
      'change',
      sortSliderValue([
        value[0],
        preventValueOverflow(Number(endInputValue.value)),
      ]),
    );

    return;
  }

  emit('change', preventValueOverflow(Number(endInputValue.value)));
}

function onStartInputKeydown(event: KeyboardEvent): void {
  const { value } = props;

  if (!isRangeSlider(value)) return;

  switch (event.code) {
    case 'Enter': {
      const result = sortSliderValue([
        value[1],
        preventValueOverflow(Number(startInputValue.value)),
      ]);

      startInputValue.value = result[0].toString();
      endInputValue.value = result[1].toString();
      emit('change', result);

      break;
    }

    case 'Escape': {
      startInputValue.value = value[0].toString();
      endInputValue.value = value[1].toString();

      break;
    }

    default:
      break;
  }
}

function onEndInputKeydown(event: KeyboardEvent): void {
  const { value } = props;

  switch (event.code) {
    case 'Enter': {
      if (isRangeSlider(value)) {
        const result = sortSliderValue([
          value[0],
          preventValueOverflow(Number(endInputValue.value)),
        ]);

        startInputValue.value = result[0].toString();
        endInputValue.value = result[1].toString();
        emit('change', result);

        return;
      }

      const result = preventValueOverflow(Number(endInputValue.value));

      endInputValue.value = result.toString();
      emit('change', result);

      break;
    }

    case 'Escape': {
      if (isRangeSlider(value)) {
        startInputValue.value = value[0].toString();
        endInputValue.value = value[1].toString();

        return;
      }

      endInputValue.value = value.toString();

      break;
    }

    default:
      break;
  }
}

function startInputProps(): InputProps['inputProps'] {
  const enabled = shouldHaveInputHandlers() && isRange.value;

  return {
    max: props.max,
    min: props.min,
    onBlur: enabled ? onStartInputBlur : undefined,
    onKeydown: enabled ? onStartInputKeydown : undefined,
  };
}

function endInputProps(): InputProps['inputProps'] {
  const enabled = shouldHaveInputHandlers();

  return {
    max: props.max,
    min: props.min,
    onBlur: enabled ? onEndInputBlur : undefined,
    onKeydown: enabled ? onEndInputKeydown : undefined,
  };
}

interface SliderTick {
  percent: number;
  text: number;
}

const ticks = computed((): SliderTick[] => {
  const { max, min, withTick } = props;

  if (!withTick) return [];

  const marks: SliderTick[] = [{ percent: 0, text: min }];

  if (Array.isArray(withTick)) {
    withTick.forEach((tick) => {
      if (tick < max && tick > min) {
        marks.push({
          percent: ((tick - min) / (max - min)) * 100,
          text: tick,
        });
      }
    });
  } else {
    Array.from({ length: withTick }, (_, index) => index + 1).forEach(
      (tick) => {
        marks.push({
          percent: (tick / (withTick + 1)) * 100,
          text: (tick / (withTick + 1)) * (max - min) + min,
        });
      },
    );
  }

  marks.push({ percent: 100, text: max });

  return marks;
});

interface SliderHandle {
  index: number;
  value: number;
}

const handles = computed((): SliderHandle[] => {
  const { value } = props;

  return isRangeSlider(value)
    ? [
        { index: 0, value: value[0] },
        { index: 1, value: value[1] },
      ]
    : [{ index: -1, value }];
});

const hostClasses = computed((): string =>
  clsx(classes.host, props.disabled && classes.disabled),
);

/**
 * The track and handle positions are custom properties, which Vue's
 * `CSSProperties` only types under a `--${string}` key. They are written by
 * `toSliderCssVars` and always carry that prefix.
 */
const hostStyle = computed((): CSSProperties => cssVars.value as CSSProperties);

/**
 * A function ref rather than the ref object: a template unwraps a `Ref`, so
 * binding it directly would hand the element's own value back to Vue.
 */
const setRail = (element: Element | ComponentPublicInstance | null): void => {
  railRef.value = element as HTMLDivElement | null;
};

const handlePositionClasses = (index: number): string =>
  clsx(
    classes.handlerPosition,
    index === 0 && classes.handlerStartPosition,
    index === 1 && classes.handlerEndPosition,
  );

const handlerClasses = (index: number): string =>
  clsx(
    classes.handler,
    index === activeHandleIndex.value && classes.handlerActive,
  );

const tickStyle = (percent: number): CSSProperties => ({ left: `${percent}%` });

const CLICKABLE_ICON_STYLE: CSSProperties = { cursor: 'pointer' };

const TOOLTIP_OPTIONS: PopperOptions = { placement: 'top' };

/**
 * Compensate for the handler circle expanding into the outer hit-target div on
 * hover. handler div = size-element-relaxed (24px), circle at rest =
 * size-element-base (16px), so the circle top is (24-16)/2 = 4px inside the div
 * top — add 4px so the visual gap stays at least gap-base.
 */
const handlerTooltipExtraOffset =
  (resolveNumericCSSVariable(`--${spacingPrefix}-size-element-relaxed`) -
    resolveNumericCSSVariable(`--${spacingPrefix}-size-element-base`)) /
  2;

const handlerTooltipOffsetMainAxis =
  resolveNumericCSSVariable(`--${spacingPrefix}-gap-base`) +
  handlerTooltipExtraOffset;

const controlsClass = classes.controls;
const handlerTooltipClass = classes.handlerTooltip;
const iconClass = classes.icon;
const inputClass = classes.input;
const railClass = classes.rail;
const tickClass = classes.tick;
const trackClass = classes.track;
</script>

<template>
  <div :class="hostClasses" :style="hostStyle">
    <MznInput
      v-if="withInput && isRange"
      :class="inputClass"
      :disabled="disabled || undefined"
      :input-props="startInputProps()"
      :value="startInputValue"
      variant="number"
      @change="onStartInputChange"
    />
    <span
      v-if="prefixIcon"
      :aria-label="iconClickable() ? 'Decrease value' : undefined"
      :class="iconClass"
      :role="iconClickable() ? 'button' : undefined"
      :style="iconClickable() ? CLICKABLE_ICON_STYLE : undefined"
      :tabindex="iconClickable() ? 0 : undefined"
      @click="handlePrefixIconClick"
      @keydown="handlePrefixIconKeydown"
    >
      <MznIcon :icon="prefixIcon" />
    </span>
    <div :class="controlsClass">
      <!-- interactive area -->
      <div
        :ref="setRail"
        :class="railClass"
        role="presentation"
        @mousedown="handleTrackOrRailMousedown"
      >
        <!-- line -->
        <span />
      </div>
      <div
        :class="trackClass"
        role="presentation"
        @mousedown="handleTrackOrRailMousedown"
      >
        <!-- line -->
        <span />
      </div>
      <!-- ticks dot and label -->
      <span
        v-for="tick in ticks"
        :key="tick.text"
        aria-hidden="true"
        :class="tickClass"
        :style="tickStyle(tick.percent)"
      >
        <MznTypography variant="caption">{{ tick.text }}</MznTypography>
      </span>
      <!-- handlers -->
      <div
        v-for="handle in handles"
        :key="handle.index"
        :class="handlePositionClasses(handle.index)"
      >
        <MznTooltip
          :class="handlerTooltipClass"
          :offset-main-axis="handlerTooltipOffsetMainAxis"
          :options="TOOLTIP_OPTIONS"
          :title="handle.value.toString()"
        >
          <template #default="tooltipProps">
            <div
              :ref="tooltipProps.ref"
              :aria-disabled="disabled"
              :aria-label="`Slider Handler ${handle.index}`"
              :aria-valuemax="max"
              :aria-valuemin="min"
              :aria-valuenow="handle.value"
              :class="handlerClasses(handle.index)"
              role="slider"
              tabindex="0"
              @mousedown="handlePress($event, handle.index)"
              @mouseenter="tooltipProps.onMouseenter"
              @mouseleave="tooltipProps.onMouseleave"
              @touchstart="handlePress($event, handle.index)"
            >
              <!-- handler circle icon -->
              <span />
            </div>
          </template>
        </MznTooltip>
      </div>
    </div>
    <MznInput
      v-if="withInput"
      :class="inputClass"
      :disabled="disabled || undefined"
      :input-props="endInputProps()"
      :value="endInputValue"
      variant="number"
      @change="onEndInputChange"
    />
    <span
      v-if="suffixIcon"
      :aria-label="iconClickable() ? 'Increase value' : undefined"
      :class="iconClass"
      :role="iconClickable() ? 'button' : undefined"
      :style="iconClickable() ? CLICKABLE_ICON_STYLE : undefined"
      :tabindex="iconClickable() ? 0 : undefined"
      @click="handleSuffixIconClick"
      @keydown="handleSuffixIconKeydown"
    >
      <MznIcon :icon="suffixIcon" />
    </span>
  </div>
</template>

// packages/ng/slider/slider.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  NgZone,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import {
  findClosetValueIndex,
  fixRangeSliderValue,
  fixSingleSliderValue,
  getPercentage,
  getSliderRect,
  getValueFromClientX,
  isRangeSlider,
  RangeSliderValue,
  roundToStep,
  sliderClasses as classes,
  SliderValue,
  sortSliderValue,
  toSliderCssVars,
} from '@mezzanine-ui/core/slider';
import { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznInput } from '@mezzanine-ui/ng/input';
import { MznTooltip } from '@mezzanine-ui/ng/tooltip';
import { provideValueAccessor } from '@mezzanine-ui/ng/utils';

/**
 * 滑桿元件，支援單值與範圍選取模式。
 *
 * 實作 `ControlValueAccessor` 支援 Angular Forms（`ngModel` / `formControlName`）。
 * 可選附加前綴/後綴圖示按鈕，供使用者微調數值。
 * 支援滑鼠拖曳與觸控操作。
 *
 * @example
 * ```html
 * import { MznSlider } from '@mezzanine-ui/ng/slider';
 *
 * <!-- 單值滑桿 -->
 * <div mznSlider [(ngModel)]="volume" [min]="0" [max]="100" [step]="1" ></div>
 *
 * <!-- 範圍滑桿 -->
 * <div mznSlider [value]="[20, 80]" (valueChange)="onRangeChange($event)" ></div>
 *
 * <!-- 附加圖示 -->
 * <div mznSlider [(ngModel)]="volume" [prefixIcon]="MinusIcon" [suffixIcon]="PlusIcon" ></div>
 * ```
 */
@Component({
  selector: '[mznSlider]',
  standalone: true,
  imports: [MznIcon, MznInput, MznTooltip],
  providers: [provideValueAccessor(MznSlider)],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[style]': 'hostStyles()',
    '[attr.disabled]': 'null',
    '[attr.max]': 'null',
    '[attr.min]': 'null',
    '[attr.prefixIcon]': 'null',
    '[attr.step]': 'null',
    '[attr.suffixIcon]': 'null',
    '[attr.withInput]': 'null',
    '[attr.withTick]': 'null',
  },
  template: `
    @if (withInput() && isRange()) {
      <div [class]="inputClass">
        <div
          mznInput
          variant="number"
          [inputType]="'number'"
          [value]="startInputValue()"
          (valueChange)="onStartInputValueChange($event)"
          [disabled]="disabled()"
        ></div>
      </div>
    }
    @if (prefixIcon()) {
      <span
        [class]="iconClass"
        [attr.role]="iconClickable() ? 'button' : null"
        [attr.tabindex]="iconClickable() ? 0 : null"
        [attr.aria-label]="iconClickable() ? 'Decrease value' : null"
        [style.cursor]="iconClickable() ? 'pointer' : null"
        (click)="onPrefixClick()"
        (keydown)="onIconKeyDown($event, 'prefix')"
      >
        <i mznIcon [icon]="prefixIcon()!"></i>
      </span>
    }
    <div [class]="controlsClass">
      <div
        #railEl
        [class]="railClass"
        (mousedown)="onRailMouseDown($event)"
        (touchstart)="onRailTouchStart($event)"
        role="presentation"
      >
        <span></span>
      </div>
      <div
        [class]="trackClass"
        (mousedown)="onRailMouseDown($event)"
        (touchstart)="onRailTouchStart($event)"
        role="presentation"
      >
        <span></span>
      </div>
      @if (isRange()) {
        <div [class]="handlerStartPositionClass">
          <div
            [mznTooltip]="'' + rangeValue()[0]"
            [tooltipOffset]="handlerTooltipOffset"
            tooltipPlacement="top"
            [class]="handlerStartClasses()"
            role="slider"
            tabindex="0"
            [attr.aria-valuemin]="min()"
            [attr.aria-valuemax]="max()"
            [attr.aria-valuenow]="rangeValue()[0]"
            [attr.aria-disabled]="disabled()"
            [attr.aria-label]="'Slider Handler 0'"
            (mousedown)="onHandlerMouseDown($event, 0)"
            (touchstart)="onHandlerTouchStart($event, 0)"
          >
            <span></span>
          </div>
        </div>
        <div [class]="handlerEndPositionClass">
          <div
            [mznTooltip]="'' + rangeValue()[1]"
            [tooltipOffset]="handlerTooltipOffset"
            tooltipPlacement="top"
            [class]="handlerEndClasses()"
            role="slider"
            tabindex="0"
            [attr.aria-valuemin]="min()"
            [attr.aria-valuemax]="max()"
            [attr.aria-valuenow]="rangeValue()[1]"
            [attr.aria-disabled]="disabled()"
            [attr.aria-label]="'Slider Handler 1'"
            (mousedown)="onHandlerMouseDown($event, 1)"
            (touchstart)="onHandlerTouchStart($event, 1)"
          >
            <span></span>
          </div>
        </div>
      } @else {
        <div [class]="handlerPositionClass">
          <div
            [mznTooltip]="'' + singleValue()"
            [tooltipOffset]="handlerTooltipOffset"
            tooltipPlacement="top"
            [class]="handlerClasses()"
            role="slider"
            tabindex="0"
            [attr.aria-valuemin]="min()"
            [attr.aria-valuemax]="max()"
            [attr.aria-valuenow]="singleValue()"
            [attr.aria-disabled]="disabled()"
            [attr.aria-label]="'Slider Handler'"
            (mousedown)="onHandlerMouseDown($event, -1)"
            (touchstart)="onHandlerTouchStart($event, -1)"
          >
            <span></span>
          </div>
        </div>
      }
      @if (ticks().length > 0) {
        @for (tick of ticks(); track tick.percent) {
          <span
            [class]="tickClass"
            aria-hidden="true"
            [style.left.%]="tick.percent"
            >{{ tick.label }}</span
          >
        }
      }
    </div>
    @if (withInput()) {
      <div [class]="inputClass">
        <div
          mznInput
          variant="number"
          [inputType]="'number'"
          [value]="endInputValue()"
          (valueChange)="onEndInputValueChange($event)"
          [disabled]="disabled()"
        ></div>
      </div>
    }
    @if (suffixIcon()) {
      <span
        [class]="iconClass"
        [attr.role]="iconClickable() ? 'button' : null"
        [attr.tabindex]="iconClickable() ? 0 : null"
        [attr.aria-label]="iconClickable() ? 'Increase value' : null"
        [style.cursor]="iconClickable() ? 'pointer' : null"
        (click)="onSuffixClick()"
        (keydown)="onIconKeyDown($event, 'suffix')"
      >
        <i mznIcon [icon]="suffixIcon()!"></i>
      </span>
    }
  `,
})
export class MznSlider implements ControlValueAccessor {
  private readonly ngZone = inject(NgZone);
  private readonly railRef = viewChild<ElementRef<HTMLDivElement>>('railEl');

  /** 是否禁用。 @default false */
  readonly disabled = input(false);

  /** 最大值。 @default 100 */
  readonly max = input(100);

  /** 最小值。 @default 0 */
  readonly min = input(0);

  /** 前綴圖示。 */
  readonly prefixIcon = input<IconDefinition>();

  /** 步進值。 @default 1 */
  readonly step = input(1);

  /** 後綴圖示。 */
  readonly suffixIcon = input<IconDefinition>();

  /**
   * 是否顯示數值輸入框供使用者直接輸入。
   * @default false
   */
  readonly withInput = input(false);

  /**
   * 刻度設定。傳入數字表示刻度數量（均勻分布），傳入數字陣列指定特定刻度值。
   */
  readonly withTick = input<number | readonly number[] | undefined>(undefined);

  /**
   * 自訂前綴圖示點擊處理函式。提供時取代預設遞減行為。
   * 同時也會觸發 `prefixIconClick` output 事件。
   */
  readonly onPrefixIconClick = input<(() => void) | undefined>(undefined);

  /**
   * 自訂後綴圖示點擊處理函式。提供時取代預設遞增行為。
   * 同時也會觸發 `suffixIconClick` output 事件。
   */
  readonly onSuffixIconClick = input<(() => void) | undefined>(undefined);

  /** 前綴圖示點擊事件。 */
  readonly prefixIconClick = output<void>();

  /** 後綴圖示點擊事件。 */
  readonly suffixIconClick = output<void>();

  /** 值變更事件。 */
  readonly valueChange = output<SliderValue>();

  private readonly internalValue = signal<SliderValue>(0);
  private readonly dragging = signal(false);
  private readonly anchorValue = signal<number | undefined>(undefined);

  readonly resolvedValue = computed((): SliderValue => this.internalValue());

  readonly isRange = computed((): boolean =>
    isRangeSlider(this.resolvedValue()),
  );

  readonly singleValue = computed((): number => {
    const val = this.resolvedValue();

    return isRangeSlider(val) ? val[0] : val;
  });

  readonly rangeValue = computed((): RangeSliderValue => {
    const val = this.resolvedValue();

    return isRangeSlider(val) ? val : [val, val];
  });

  protected readonly iconClickable = computed((): boolean => !this.disabled());

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, { [classes.disabled]: this.disabled() }),
  );

  protected readonly hostStyles = computed((): Record<string, string> => {
    const val = this.resolvedValue();
    const minVal = this.min();
    const maxVal = this.max();

    const fixedValue = isRangeSlider(val)
      ? fixRangeSliderValue(val, minVal, maxVal)
      : fixSingleSliderValue(val, minVal, maxVal);

    return toSliderCssVars({
      trackWidth: getPercentage(
        isRangeSlider(fixedValue)
          ? Math.abs(fixedValue[0] - fixedValue[1])
          : fixedValue - minVal,
        minVal,
        maxVal,
      ),
      trackPosition: getPercentage(
        isRangeSlider(fixedValue)
          ? Math.abs(Math.min(...fixedValue) - minVal)
          : 0,
        minVal,
        maxVal,
      ),
      handlerPosition: getPercentage(
        isRangeSlider(fixedValue) ? 0 : fixedValue - minVal,
        minVal,
        maxVal,
      ),
      handlerStartPosition: getPercentage(
        isRangeSlider(fixedValue)
          ? Math.abs(Math.min(...fixedValue) - minVal)
          : fixedValue,
        minVal,
        maxVal,
      ),
      handlerEndPosition: getPercentage(
        isRangeSlider(fixedValue)
          ? Math.abs(Math.max(...fixedValue) - minVal)
          : fixedValue,
        minVal,
        maxVal,
      ),
    }) as Record<string, string>;
  });

  private readonly activeHandleIndex = computed((): number | undefined => {
    const anchor = this.anchorValue();

    if (typeof anchor !== 'number') {
      return undefined;
    }

    const val = this.resolvedValue();

    return isRangeSlider(val) ? Math.abs(1 - val.indexOf(anchor)) : undefined;
  });

  protected readonly handlerClasses = computed((): string =>
    clsx(classes.handler, {
      [classes.handlerActive]: this.dragging(),
    }),
  );

  protected readonly handlerStartClasses = computed((): string =>
    clsx(classes.handler, {
      [classes.handlerActive]: this.activeHandleIndex() === 0,
    }),
  );

  protected readonly handlerEndClasses = computed((): string =>
    clsx(classes.handler, {
      [classes.handlerActive]: this.activeHandleIndex() === 1,
    }),
  );

  protected readonly controlsClass = classes.controls;
  protected readonly railClass = classes.rail;
  protected readonly trackClass = classes.track;
  protected readonly iconClass = classes.icon;
  protected readonly tickClass = classes.tick;
  protected readonly inputClass = classes.input;

  /** Tooltip offset matching React's handler tooltip positioning. */
  protected readonly handlerTooltipOffset = 12;
  protected readonly handlerPositionClass = classes.handlerPosition;
  protected readonly handlerStartPositionClass = `${classes.handlerPosition} ${classes.handlerStartPosition}`;
  protected readonly handlerEndPositionClass = `${classes.handlerPosition} ${classes.handlerEndPosition}`;

  /** 起始輸入框的文字狀態（range + withInput 模式）。 */
  protected readonly startInputValue = computed((): string => {
    const val = this.resolvedValue();

    return isRangeSlider(val) ? `${val[0]}` : '';
  });

  /** 結束輸入框的文字狀態（single 或 range + withInput 模式）。 */
  protected readonly endInputValue = computed((): string => {
    const val = this.resolvedValue();

    return isRangeSlider(val) ? `${val[1]}` : `${val}`;
  });

  /** 計算刻度的資料陣列，每筆含 percent（0–100）與 label（顯示文字）。 */
  protected readonly ticks = computed(
    (): readonly { readonly percent: number; readonly label: string }[] => {
      const withTick = this.withTick();
      const minVal = this.min();
      const maxVal = this.max();
      const range = maxVal - minVal;

      if (!withTick) return [];

      const result: { percent: number; label: string }[] = [];

      // Always show min and max
      result.push({ percent: 0, label: `${minVal}` });

      if (Array.isArray(withTick)) {
        (withTick as readonly number[]).forEach((v) => {
          if (v > minVal && v < maxVal) {
            result.push({
              percent: ((v - minVal) / range) * 100,
              label: `${v}`,
            });
          }
        });
      } else {
        const count = withTick as number;

        Array.from({ length: count }, (_, i) => i + 1).forEach((i) => {
          const value = (i / (count + 1)) * range + minVal;
          result.push({
            percent: (i / (count + 1)) * 100,
            label: `${Math.round(value * 100) / 100}`,
          });
        });
      }

      result.push({ percent: 100, label: `${maxVal}` });

      return result;
    },
  );

  // ControlValueAccessor
  private onChange: (value: SliderValue) => void = () => {};
  private onTouched: () => void = () => {};

  writeValue(value: SliderValue): void {
    this.internalValue.set(value ?? 0);
  }

  registerOnChange(fn: (value: SliderValue) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  // --- Event handlers ---

  protected onRailMouseDown(event: MouseEvent): void {
    if (this.disabled()) {
      return;
    }

    this.handleClickRail(event.clientX);
  }

  protected onRailTouchStart(event: TouchEvent): void {
    if (this.disabled()) {
      return;
    }

    this.handleClickRail(event.changedTouches[0].clientX);
  }

  protected onHandlerMouseDown(event: MouseEvent, handlerIndex: number): void {
    if (this.disabled()) {
      return;
    }

    event.preventDefault();
    event.stopPropagation();
    this.startDrag(handlerIndex, 'mouse');
  }

  protected onHandlerTouchStart(event: TouchEvent, handlerIndex: number): void {
    if (this.disabled()) {
      return;
    }

    event.stopPropagation();
    this.startDrag(handlerIndex, 'touch');
  }

  protected onInputValueChange(rawValue: string): void {
    const parsed = Number(rawValue);

    if (Number.isNaN(parsed)) return;

    this.updateValue(this.preventOverflow(parsed));
  }

  protected onStartInputValueChange(rawValue: string): void {
    const parsed = Number(rawValue);

    if (Number.isNaN(parsed)) return;

    const val = this.resolvedValue();

    if (isRangeSlider(val)) {
      const next = this.preventOverflow(parsed);

      this.updateValue(sortSliderValue([next, val[1]]));
    }
  }

  protected onEndInputValueChange(rawValue: string): void {
    const parsed = Number(rawValue);

    if (Number.isNaN(parsed)) return;

    const val = this.resolvedValue();

    if (isRangeSlider(val)) {
      const next = this.preventOverflow(parsed);

      this.updateValue(sortSliderValue([val[0], next]));
    } else {
      this.updateValue(this.preventOverflow(parsed));
    }
  }

  protected onPrefixClick(): void {
    if (this.disabled()) {
      return;
    }

    this.prefixIconClick.emit();

    const customHandler = this.onPrefixIconClick();

    if (customHandler) {
      customHandler();

      return;
    }

    const val = this.resolvedValue();

    if (isRangeSlider(val)) {
      const next = this.preventOverflow(val[0] - this.step());

      this.updateValue(sortSliderValue([next, val[1]]));
    } else {
      this.updateValue(this.preventOverflow(val - this.step()));
    }
  }

  protected onSuffixClick(): void {
    if (this.disabled()) {
      return;
    }

    this.suffixIconClick.emit();

    const customHandler = this.onSuffixIconClick();

    if (customHandler) {
      customHandler();

      return;
    }

    const val = this.resolvedValue();

    if (isRangeSlider(val)) {
      const next = this.preventOverflow(val[1] + this.step());

      this.updateValue(sortSliderValue([val[0], next]));
    } else {
      this.updateValue(this.preventOverflow(val + this.step()));
    }
  }

  protected onIconKeyDown(
    event: KeyboardEvent,
    type: 'prefix' | 'suffix',
  ): void {
    const isActivate = event.key === 'Enter' || event.key === ' ';
    if (!isActivate) return;
    if (event.key === ' ') event.preventDefault();
    if (type === 'prefix') {
      this.onPrefixClick();
    } else {
      this.onSuffixClick();
    }
  }

  // --- Internal helpers ---

  private handleClickRail(clientX: number): void {
    const rail = this.railRef()?.nativeElement;

    if (!rail) {
      return;
    }

    const roundedNewValue = this.getRoundedValue(clientX, rail);
    const val = this.resolvedValue();

    if (isRangeSlider(val)) {
      const closestIdx = findClosetValueIndex(val, roundedNewValue);

      this.anchorValue.set(val[Math.abs(1 - closestIdx)]);

      const newRange: RangeSliderValue = [...val];

      newRange[closestIdx] = roundedNewValue;
      this.updateValue(sortSliderValue(newRange));
    } else {
      this.updateValue(roundedNewValue);
    }

    this.dragging.set(true);
  }

  private startDrag(handlerIndex: number, mode: 'mouse' | 'touch'): void {
    const val = this.resolvedValue();

    this.dragging.set(true);
    this.anchorValue.set(
      isRangeSlider(val) ? val[Math.abs(1 - handlerIndex)] : (val as number),
    );

    const onMove = (e: MouseEvent | TouchEvent): void => {
      this.ngZone.run(() => {
        const rail = this.railRef()?.nativeElement;

        if (!rail) {
          return;
        }

        const clientX =
          'touches' in e ? e.changedTouches[0].clientX : e.clientX;
        const roundedNewValue = this.getRoundedValue(clientX, rail);
        const currentVal = this.resolvedValue();

        if (isRangeSlider(currentVal)) {
          const newRange: RangeSliderValue = [...currentVal];

          newRange[handlerIndex] = roundedNewValue;
          this.updateValue(sortSliderValue(newRange));
        } else {
          this.updateValue(roundedNewValue);
        }
      });
    };

    const onEnd = (e: Event): void => {
      e.preventDefault();
      this.dragging.set(false);
      this.anchorValue.set(undefined);
      this.onTouched();

      if (mode === 'mouse') {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onEnd);
        document.removeEventListener('mouseleave', onEnd);
      } else {
        document.removeEventListener('touchmove', onMove);
        document.removeEventListener('touchend', onEnd);
        document.removeEventListener('touchcancel', onEnd);
      }
    };

    if (mode === 'mouse') {
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onEnd);
      document.addEventListener('mouseleave', onEnd);
    } else {
      document.addEventListener('touchmove', onMove);
      document.addEventListener('touchend', onEnd);
      document.addEventListener('touchcancel', onEnd);
    }
  }

  private getRoundedValue(clientX: number, rail: HTMLDivElement): number {
    const rect = getSliderRect(rail);
    const rawValue = getValueFromClientX(clientX, rect, this.min(), this.max());

    return roundToStep(rawValue, this.step(), this.min(), this.max());
  }

  private preventOverflow(target: number): number {
    return Math.max(
      this.min(),
      Math.min(
        this.max(),
        roundToStep(target, this.step(), this.min(), this.max()),
      ),
    );
  }

  private updateValue(val: SliderValue): void {
    this.internalValue.set(val);
    this.onChange(val);
    this.valueChange.emit(val);
  }
}
