// packages/vue/_internal/input-trigger-popper.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { inputTriggerPopperClasses as classes } from '@mezzanine-ui/core/_internal/input-trigger-popper';
import { flip, offset, size } from '@floating-ui/dom';
import MznPopper from '../popper/popper.vue';
import type { PopperOptions } from '../popper/popper.types';
import MznFade from '../transition/fade.vue';
import type { InputTriggerPopperProps } from './input-trigger-popper.types';

/**
 * 由輸入框觸發的浮層：淡入淡出的 Popper。
 *
 * 預設對齊在錨點左下方並保留 4px 間距，空間不足時自動翻面；
 * `sameWidth` 會讓浮層的最小寬度跟著錨點。浮層內的點擊與觸控不會往外冒泡，
 * 否則 portal 出去的內容會被外部點擊關閉。
 *
 * @example
 * ```vue
 * <template>
 *   <MznInputTriggerPopper :anchor="anchor" :open="open">
 *     <MznTimePanel />
 *   </MznInputTriggerPopper>
 * </template>
 * ```
 *
 * @see MznPopper 底層的定位元件
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<InputTriggerPopperProps>(), {
  anchor: undefined,
  arrow: undefined,
  container: undefined,
  disablePortal: undefined,
  fadeProps: undefined,
  open: false,
  options: undefined,
  sameWidth: undefined,
});

defineSlots<{
  /** The popper's content. */
  default?: () => unknown;
}>();

const popper = ref<InstanceType<typeof MznPopper> | null>(null);

/**
 * React forwards a ref to the popper element; the same element is exposed
 * here, read through the floating controller because a template ref cannot
 * see through the Teleport.
 */
defineExpose({
  element: computed(
    (): HTMLElement | null =>
      (popper.value?.controllerRef.elements.floating.value as HTMLElement) ??
      null,
  ),
});

// Middleware to make the popper have the same min-width as the reference element
const sameWidthMiddleware = size({
  apply({ rects, elements }) {
    Object.assign(elements.floating.style, {
      minWidth: `${rects.reference.width}px`,
    });
  },
});

const resolvedOptions = computed((): PopperOptions => {
  const { middleware = [], ...restPopperOptions } = props.options || {};

  return {
    placement: 'bottom-start',
    ...restPopperOptions,
    middleware: [
      offset({ mainAxis: 4 }),
      flip({ fallbackAxisSideDirection: 'end', padding: 8 }),
      ...(props.sameWidth ? [sameWidthMiddleware] : []),
      ...middleware,
    ],
  };
});

/** Prevent event bubble (Because popper may use portal, then click away function would be buggy) */
function stopPropagation(event: Event): void {
  event.stopPropagation();
}

const hostClass = classes.host;
</script>

<template>
  <MznFade v-bind="fadeProps" :in="open">
    <MznPopper
      ref="popper"
      :anchor="anchor"
      :arrow="arrow"
      :class="hostClass"
      :container="container"
      :disable-portal="disablePortal"
      open
      :options="resolvedOptions"
      @click="stopPropagation"
      @touchend="stopPropagation"
      @touchmove="stopPropagation"
      @touchstart="stopPropagation"
    >
      <slot />
    </MznPopper>
  </MznFade>
</template>

// packages/ng/_internal/input-trigger-popper/input-trigger-popper.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
} from '@angular/core';
import { inputTriggerPopperClasses as classes } from '@mezzanine-ui/core/_internal/input-trigger-popper';
import { MznPopper, PopperPlacement } from '@mezzanine-ui/ng/popper';
import { size, type Middleware } from '@floating-ui/dom';

/**
 * 下拉觸發器共用的 Popper 容器（內部元件，不公開匯出）。
 *
 * 組合 `MznPopper`，固定使用 `bottom-start` 定位、4px 間距，
 * 並可選擇讓浮動層寬度與 anchor 對齊。
 *
 * Select / AutoComplete 等元件共用此元件。
 *
 * @example
 * ```html
 * <mzn-input-trigger-popper [anchor]="triggerEl" [open]="isOpen" [sameWidth]="true">
 *   <div>dropdown options</div>
 * </mzn-input-trigger-popper>
 * ```
 */
@Component({
  selector: 'mzn-input-trigger-popper',
  standalone: true,
  imports: [MznPopper],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
    '(click)': '$event.stopPropagation()',
    '(touchstart)': '$event.stopPropagation()',
    '(touchmove)': '$event.stopPropagation()',
    '(touchend)': '$event.stopPropagation()',
  },
  template: `
    <div
      mznPopper
      [anchor]="anchor()"
      [open]="open()"
      [placement]="placement"
      [offsetOptions]="offsetOpts"
      [middleware]="resolvedMiddleware()"
      style="z-index: var(--mzn-z-index-popover)"
    >
      <ng-content />
    </div>
  `,
})
export class MznInputTriggerPopper {
  /**
   * 參考（錨定）元素。
   */
  readonly anchor = input.required<HTMLElement | ElementRef<HTMLElement>>();

  /**
   * 是否顯示。
   * @default false
   */
  readonly open = input(false);

  /**
   * 是否讓浮動層最小寬度與 anchor 對齊。
   * @default false
   */
  readonly sameWidth = input(false);

  protected readonly hostClass = classes.host;
  protected readonly placement: PopperPlacement = 'bottom-start';
  protected readonly offsetOpts = { mainAxis: 4 };

  protected readonly resolvedMiddleware = computed(
    (): ReadonlyArray<Middleware> => {
      if (!this.sameWidth()) {
        return [];
      }

      return [
        size({
          apply({ rects, elements }) {
            Object.assign(elements.floating.style, {
              minWidth: `${rects.reference.width}px`,
            });
          },
        }),
      ];
    },
  );
}
