// packages/ng/filter-area/filter.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
} from '@angular/core';
import {
  filterAreaClasses as classes,
  filterAreaPrefix,
  FilterAlign,
  FilterSpan,
} from '@mezzanine-ui/core/filter-area';
import clsx from 'clsx';
import { MZN_FILTER_AREA_CONTEXT } from './filter-area-context';

/**
 * 單一篩選條件元件，用於在 MznFilterLine 中定義欄位的佔位寬度。
 *
 * 使用 6 欄 Grid，`span` 決定欄位佔用幾欄（1-6）；
 * `grow` 設為 `true` 時欄位自動填滿整行。
 * 從 MZN_FILTER_AREA_CONTEXT 繼承 `size`，統一套用至內部的輸入元件。
 *
 * @example
 * ```html
 * import { MznFilter } from '@mezzanine-ui/ng/filter-area';
 *
 * <mzn-filter [span]="2">
 *   <mzn-text-field label="Name">
 *     <input mznInput placeholder="Enter name" />
 *   </mzn-text-field>
 * </mzn-filter>
 * ```
 *
 * @see {@link MznFilterLine} 包含 MznFilter 的行容器
 * @see {@link MznFilterArea} 管理整個篩選器的容器
 */
@Component({
  selector: 'mzn-filter',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[style]': 'hostStyles()',
  },
  template: '<ng-content />',
})
export class MznFilter {
  private readonly context = inject(MZN_FILTER_AREA_CONTEXT, {
    optional: true,
  });

  /**
   * 欄位的垂直對齊方式。
   * @default 'stretch'
   */
  readonly align = input<FilterAlign>('stretch');

  /**
   * 是否自動填滿整行（等同 span=6）。
   * @default false
   */
  readonly grow = input(false);

  /**
   * 欄位的最小寬度。
   */
  readonly minWidth = input<string>();

  /**
   * 欄位在 Grid 中佔用的欄數（1-6）。
   * 當 `grow` 為 `true` 時此屬性無效。
   * @default 2
   */
  readonly span = input<FilterSpan>(2);

  protected readonly hostClasses = computed((): string =>
    clsx(classes.filter, {
      [classes.filterGrow]: this.grow(),
      [classes.filterAlign(this.align())]: this.align(),
    }),
  );

  protected readonly hostStyles = computed(
    (): Record<string, string | number> => {
      const styles: Record<string, string | number> = {};
      const minW = this.minWidth();
      const grow = this.grow();
      const span = this.span();

      if (minW) {
        styles['min-width'] = minW;
      }

      if (!grow) {
        styles[`--${filterAreaPrefix}-filter-span`] = span;
      }

      return styles;
    },
  );

  /** 從 FilterArea context 取得的 size。 */
  readonly contextSize = computed(() => this.context?.size);
}

// packages/react/src/FilterArea/Filter.tsx
'use client';

import { Children, cloneElement, forwardRef, isValidElement, ReactElement, ReactNode, useContext, useMemo } from 'react';

import {
  filterAreaClasses as classes,
  FilterAlign,
  filterAreaPrefix,
  FilterSpan,
} from '@mezzanine-ui/core/filter-area';

import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

import { FormFieldProps } from '../Form';
import FilterAreaContext, { FilterAreaContextValue } from './FilterAreaContext';
import type { FilterAreaSize } from '@mezzanine-ui/core/filter-area';

export interface FilterProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'> {
  /**
   * Layout control - Vertical alignment of the field.
   * @default 'stretch'
   */
  align?: FilterAlign;
  /**
   * The content of the filter field.
   */
  children: ReactElement<FormFieldProps> | ReactElement<FormFieldProps>[];
  /**
   * Layout control - Whether the field should automatically expand to fill the entire row (equivalent to span={12}).
   * @default false
   */
  grow?: boolean;
  /**
   * Layout control - Minimum width of the field.
   */
  minWidth?: string | number;
  /**
   * Layout control - Number of columns the field occupies in the Grid (1-12, Grid has 12 columns total).
   * This property is ignored when grow is true.
   * @default 2
   */
  span?: FilterSpan;
}

/**
 * 單一篩選條件元件，用於在 FilterLine 中定義欄位的佔位寬度。
 *
 * 使用 12 欄 Grid，`span` 決定欄位佔用幾欄（1–6）；
 * `grow` 設為 `true` 時欄位自動填滿整行。
 * 從 FilterAreaContext 繼承 `size`，統一套用至內部的輸入元件。
 *
 * @example
 * ```tsx
 * import { Filter } from '@mezzanine-ui/react';
 * import { FormField } from '@mezzanine-ui/react';
 * import Input from '@mezzanine-ui/react/Input';
 *
 * <Filter span={2}>
 *   <FormField label="名稱" name="name" layout="horizontal">
 *     <Input placeholder="請輸入" />
 *   </FormField>
 * </Filter>
 * ```
 *
 * @see {@link FilterLine} 包含 Filter 的行容器
 * @see {@link FilterArea} 管理整個篩選器的容器
 */
const Filter = forwardRef<HTMLDivElement, FilterProps>(
  function Filter(props, ref) {
    const {
      align = 'stretch',
      children,
      className,
      grow = false,
      minWidth,
      span = 2,
      ...rest
    } = props;

    const { size } = (useContext(FilterAreaContext) ?? {}) as FilterAreaContextValue;

    const filterClassName = useMemo(
      () =>
        cx(
          classes.filter,
          {
            [classes.filterGrow]: grow,
            [classes.filterAlign(align)]: align,
          },
          className,
        ),
      [align, className, grow],
    );

    const style = useMemo(
      () => ({
        ...(minWidth && { minWidth: typeof minWidth === 'number' ? `${minWidth}px` : minWidth }),
        ...(!grow && {
          [`--${filterAreaPrefix}-filter-span`]: span,
        }),
        ...rest.style,
      }),
      [grow, minWidth, rest.style, span],
    );

    const sizedChildren = useMemo(() => {
      if (!size) return children;
      return Children.map(children, (formField) => {
        const sizedInputs = Children.map(
          formField.props.children as ReactNode,
          (inputChild) => {
            if (!isValidElement(inputChild)) return inputChild;
            const { size: ownSize } = inputChild.props as { size?: FilterAreaSize };
            if (ownSize !== undefined) return inputChild;
            return cloneElement(inputChild as ReactElement<{ size: FilterAreaSize }>, { size });
          },
        );
        return cloneElement(formField, {}, sizedInputs);
      });
    }, [children, size]);

    return (
      <div
        {...rest}
        ref={ref}
        className={filterClassName}
        style={style}
      >
        {sizedChildren}
      </div>
    );
  },
);

export default Filter;
