// packages/react/src/Dropdown/DropdownItem.tsx
'use client';

import keycode from 'keycode';
import { ReactNode, useCallback, useEffect, useMemo, useRef, useState } from 'react';

import {
  DropdownCheckPosition,
  dropdownClasses,
  DropdownItemSharedProps,
  DropdownOption,
  DropdownOptionsByType,
  DropdownStatus as DropdownStatusType,
  DropdownType,
} from '@mezzanine-ui/core/dropdown/dropdown';
import { type IconDefinition } from '@mezzanine-ui/icons';

import { CaretDownIcon, CaretRightIcon } from '@mezzanine-ui/icons';

import type { OverlayScrollbars, PartialOptions } from 'overlayscrollbars';
import type { OverlayScrollbarsComponentProps } from 'overlayscrollbars-react';

import { useElementHeight } from '../hooks/useElementHeight';
import Scrollbar from '../Scrollbar';
import Typography from '../Typography';
import DropdownAction, { type DropdownActionProps } from './DropdownAction';
import DropdownItemCard from './DropdownItemCard';
import DropdownStatus from './DropdownStatus';
import shortcutTextHandler from './shortcutTextHandler';

// Helper function to recursively get all descendant IDs from a tree option (excluding the option itself)
function getAllDescendantIds(option: DropdownOption): string[] {
  const ids: string[] = [];

  if (option.children && option.children.length > 0) {
    option.children.forEach((child) => {
      ids.push(String(child.id));
      ids.push(...getAllDescendantIds(child));
    });
  }

  return ids;
}

export interface DropdownItemProps<T extends DropdownType | undefined = DropdownType> extends Omit<DropdownItemSharedProps, 'type'> {
  /**
   * The action configuration for the dropdown.
   */
  actionConfig?: DropdownActionProps;
  /**
   * The active option index for hover/focus state.
   */
  activeIndex: number | null;
  /**
   * The text to follow.
   */
  followText?: string;
  /**
   * Custom content rendered before options (e.g. inline trigger).
   */
  headerContent?: ReactNode;
  /**
   * The listbox id for aria usage.
   */
  listboxId: string;
  /**
   * The aria-label for the listbox.
   * If not provided, a default label will be used when there are no options.
   */
  listboxLabel?: string;
  /**
   * The max height of the dropdown list.
   */
  maxHeight?: number | string;
  /**
   * Whether to set the same width as its anchor element.
   * @default false
   */
  sameWidth?: boolean;
  /**
   * Callback when hovering option index changes.
  */
  onHover?: (index: number) => void;
  /**
   * Options to render.
   * The structure is constrained based on the `type` prop:
   * - 'default': flat array (no children allowed)
   * - 'grouped': array with one level of children (children cannot have children)
   * - 'tree': array with nested children up to 3 levels (strictly enforced at compile time)
   */
  options: DropdownOptionsByType<T>;
  /**
   * The type of the dropdown.
   * This prop determines the structure of the `options` array:
   * - 'default': flat array (no children allowed)
   * - 'grouped': array with one level of children (children cannot have children)
   * - 'tree': array with nested children up to 3 levels
   */
  type?: DropdownType;
  /**
   * The status of the dropdown (loading or empty).
   */
  status?: DropdownStatusType;
  /**
   * The text of the dropdown loading status.
   */
  loadingText?: string;
  /**
   * The text of the dropdown empty status.
   */
  emptyText?: string;
  /**
   * The icon of the dropdown empty status.
   */
  emptyIcon?: IconDefinition;
  /**
   * Callback fired when the dropdown list reaches the bottom.
   * Only fires when `maxHeight` is set and the list is scrollable.
   */
  onReachBottom?: () => void;
  /**
   * Callback fired when the dropdown list leaves the bottom.
   * Only fires when `maxHeight` is set and the list is scrollable.
   */
  onLeaveBottom?: () => void;
  /**
   * Callback fired when the dropdown list is scrolled.
   * Receives the scroll event and computed scroll information.
   */
  onScroll?: (
    computed: { scrollTop: number; maxScrollTop: number },
    target: HTMLDivElement,
  ) => void;
  /**
   * Whether to defer the initialization of OverlayScrollbars.
   * This can improve initial render performance.
   * @default true
   */
  scrollbarDefer?: boolean | object;
  /**
   * Whether to disable the custom scrollbar component.
   * When false (default), Scrollbar component will be used when maxHeight is set.
   * When true, falls back to native div scrolling (backward compatible).
   * @default false
   */
  scrollbarDisabled?: boolean;
  /**
   * The maximum width of the scrollable container.
   * Can be a CSS value string (e.g., '500px', '100%') or a number (treated as pixels).
   */
  scrollbarMaxWidth?: number | string;
  /**
   * Additional options to pass to OverlayScrollbars.
   * @see https://kingsora.github.io/OverlayScrollbars/#!documentation/options
   */
  scrollbarOptions?: PartialOptions;
}

/**
 * Limits DropdownOption array to a maximum depth, truncating extra children levels and showing error message if exceeded.
 * @param input - The original DropdownOption array
 * @param maxDepth - Maximum depth (default: 3)
 * @param warn - Whether to show warning (default: true)
 * @returns DropdownOption array with at most the specified depth
 */
function truncateArrayDepth(
  input: DropdownOption[],
  maxDepth: number = 3,
  warn: boolean = true
): DropdownOption[] {
  // Internal recursive function: truncates children to specified depth
  const truncate = (options: DropdownOption[], currentDepth: number = 1): DropdownOption[] => {
    if (currentDepth >= maxDepth) {
      // Stop going deeper once maximum depth is reached, remove children
      return options.map(({ children: _children, ...option }) => option);
    }
    return options.map(option => {
      if (!option.children) return option;
      return {
        ...option,
        children: truncate(option.children, currentDepth + 1),
      };
    });
  };

  // Calculate maximum depth by checking all elements (not just the first one)
  const getDepth = (options: DropdownOption[] | undefined, depth: number = 1): number => {
    if (!options || options.length === 0) return depth - 1;

    // Find the maximum depth among all options
    return Math.max(
      ...options.map((option) => {
        if (!option.children || option.children.length === 0) {
          return depth - 1;
        }
        return getDepth(option.children, depth + 1);
      })
    );
  };

  const depth = getDepth(input);
  if (depth <= maxDepth) return input;

  // Exceeds maximum depth → warn
  if (warn) {
    console.error(
      `[truncateArrayDepth] Input DropdownOption array exceeds ${maxDepth} levels. Extra levels were truncated.`
    );
  }

  // Truncate to specified depth
  return truncate(input);
}

export default function DropdownItem<T extends DropdownType | undefined = DropdownType>(props: DropdownItemProps<T>) {
  const {
    activeIndex,
    disabled = false,
    listboxId,
    listboxLabel,
    mode = 'single',
    options,
    value,
    type,
    maxHeight,
    actionConfig,
    onHover,
    onSelect,
    followText,
    headerContent,
    status,
    loadingText,
    emptyText,
    emptyIcon,
    onReachBottom,
    onLeaveBottom,
    onScroll,
    scrollbarDefer = true,
    scrollbarDisabled = false,
    scrollbarMaxWidth,
    scrollbarOptions,
  } = props;

  const optionsContent = truncateArrayDepth(options, 3);
  const listRef = useRef<HTMLUListElement | null>(null);
  const listWrapperRef = useRef<HTMLDivElement | null>(null);
  const viewportRef = useRef<HTMLDivElement | null>(null);
  const wasAtBottomRef = useRef(false);
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(new Set());
  const hasActions = Boolean(actionConfig?.showActions);
  const hasHeader = Boolean(headerContent);
  const shouldUseScrollbar = maxHeight && !scrollbarDisabled;

  // Use custom hook to measure element heights
  const [actionRef, actionHeight] = useElementHeight<HTMLDivElement>(hasActions && !!maxHeight);
  const [headerRef, headerHeight] = useElementHeight<HTMLLIElement>(hasHeader && !!maxHeight);

  const toggleExpand = useCallback((optionId: string) => {
    setExpandedNodes((prev) => {
      const next = new Set(prev);
      if (next.has(optionId)) {
        next.delete(optionId);
      } else {
        next.add(optionId);
      }
      return next;
    });
  }, []);

  const visibleShortcutOptions = useMemo(() => {
    const result: DropdownOption[] = [];

    const collectDefault = (optionList?: DropdownOption[]) => {
      optionList?.forEach((option) => {
        result.push(option);
      });
    };

    const collectGrouped = (optionList?: DropdownOption[]) => {
      optionList?.forEach((groupOption) => {
        groupOption.children?.forEach((option) => {
          result.push(option);
        });
      });
    };

    const collectTree = (optionList?: DropdownOption[]) => {
      optionList?.forEach((option) => {
        result.push(option);
        if (option.children && expandedNodes.has(option.id)) {
          collectTree(option.children);
        }
      });
    };

    if (type === 'grouped') {
      collectGrouped(optionsContent);
    } else if (type === 'tree') {
      collectTree(optionsContent);
    } else {
      collectDefault(optionsContent);
    }

    return result;
  }, [expandedNodes, optionsContent, type]);

  const matchShortcut = useCallback((event: KeyboardEvent, shortcut: number | string) => {
    const eventCode = event.which ?? event.keyCode;

    if (typeof shortcut === 'number') {
      return eventCode === shortcut;
    }

    const tokens = shortcut
      .split('+')
      .map((token) => token.trim().toLowerCase())
      .filter(Boolean);

    let requireMeta = false;
    let requireCtrl = false;
    let requireAlt = false;
    let requireShift = false;
    let mainToken: string | null = null;

    tokens.forEach((token) => {
      switch (token) {
        case 'cmd':
        case 'meta':
        case 'command':
          requireMeta = true;
          break;
        case 'ctrl':
        case 'control':
          requireCtrl = true;
          break;
        case 'alt':
        case 'option':
          requireAlt = true;
          break;
        case 'shift':
          requireShift = true;
          break;
        default:
          mainToken = token;
          break;
      }
    });

    if (!mainToken) return false;
    if (
      requireMeta !== event.metaKey
      || requireCtrl !== event.ctrlKey
      || requireAlt !== event.altKey
      || requireShift !== event.shiftKey
    ) {
      return false;
    }

    const mainCode = keycode(mainToken);
    if (typeof mainCode === 'number' && eventCode === mainCode) {
      return true;
    }

    const eventKey = event.key?.toLowerCase();
    if (eventKey && eventKey === mainToken) {
      return true;
    }

    const eventKeyName = keycode(eventCode);
    return typeof eventKeyName === 'string' && eventKeyName.toLowerCase() === mainToken;
  }, []);

  const renderGroupedOptions = (
    optionList: DropdownOption[] | undefined,
    startIndex: number,
  ): { elements: ReactNode[]; nextIndex: number } => {
    let currentIndex = startIndex;

    const elements = (optionList ?? []).flatMap((groupOption) => {
      const hasChildren = Boolean(groupOption.children && groupOption.children.length > 0);
      const groupElements: ReactNode[] = [];

      if (hasChildren) {
        groupElements.push(
          <Typography
            key={groupOption.id}
            variant="body"
            className={dropdownClasses.groupLabel}
          >
            {groupOption.name}
          </Typography>
        )
        groupOption.children?.forEach((option) => {
          currentIndex += 1;
          const optionIndex = currentIndex;
          const isActive = optionIndex === activeIndex;
          const isSelected = Array.isArray(value)
            ? value.includes(option.id)
            : value === option.id;
          const shortcutText = option.shortcutText
            ? option.shortcutText
            : shortcutTextHandler(option.shortcutKeys ?? []);

          groupElements.push(
            <DropdownItemCard
              followText={followText}
              key={option.id}
              active={isActive}
              checked={isSelected}
              disabled={disabled}
              id={`${listboxId}-option-${optionIndex}`}
              label={option.name}
              mode={mode}
              name={option.name}
              onClick={() => {
                if (disabled) return;
                onSelect?.(option);
              }}
              checkSite="none"
              validate={option.validate ?? 'default'}
              onMouseEnter={() => onHover?.(optionIndex)}
              showUnderline={option.showUnderline ?? false}
              appendContent={shortcutText}
            />
          );
        });
      }

      return groupElements;
    });

    return { elements, nextIndex: currentIndex };
  };

  const calculateNodeSelectionState = useCallback(
    (option: DropdownOption, selectedIds: string[]): { checked: boolean; indeterminate: boolean } => {
      if (!option.children || option.children.length === 0) {
        const isSelected = selectedIds.includes(String(option.id));
        return { checked: isSelected, indeterminate: false };
      }

      // Get all descendant IDs (excluding the parent node itself)
      const allDescendantIds = getAllDescendantIds(option);
      const selectedDescendants = allDescendantIds.filter((id) => selectedIds.includes(id));
      const totalDescendants = allDescendantIds.length;

      if (totalDescendants === 0) {
        // No descendants, check if parent itself is selected
        const isSelected = selectedIds.includes(String(option.id));
        return { checked: isSelected, indeterminate: false };
      }

      if (selectedDescendants.length === 0) {
        return { checked: false, indeterminate: false };
      }
      if (selectedDescendants.length === totalDescendants) {
        // All descendants are selected
        return { checked: true, indeterminate: false };
      }

      // Some but not all descendants are selected
      return { checked: false, indeterminate: true };
    },
    [],
  );

  const renderTreeOptions = (
    optionList: DropdownOption[] | undefined,
    depth: number,
    startIndex: number,
  ): { elements: ReactNode[]; nextIndex: number } => {
    let currentIndex = startIndex;
    const selectedIds = Array.isArray(value) ? value.map((id) => String(id)) : value ? [String(value)] : [];

    const elements = (optionList ?? []).flatMap((option) => {
      currentIndex += 1;
      const optionIndex = currentIndex;
      const level = Math.min(depth, 2) as 0 | 1 | 2;
      const isActive = optionIndex === activeIndex;
      const hasChildren = Boolean(option.children && option.children.length > 0);
      const isExpanded = hasChildren && expandedNodes.has(option.id);
      let prependIcon: IconDefinition | undefined = undefined;

      if (hasChildren && level !== 2) {
        prependIcon = isExpanded ? CaretDownIcon : CaretRightIcon;
      }
      const checkSite: DropdownCheckPosition = option.showCheckbox ? 'prefix' : 'none';
      const shortcutText = option.shortcutText
        ? option.shortcutText
        : shortcutTextHandler(option.shortcutKeys ?? []);
      const selectionState = hasChildren && mode === 'multiple'
        ? calculateNodeSelectionState(option, selectedIds)
        : {
          checked: selectedIds.includes(String(option.id)),
          indeterminate: false,
        };

      const card = (
        <DropdownItemCard
          key={option.id}
          active={isActive}
          checked={selectionState.checked}
          indeterminate={selectionState.indeterminate}
          disabled={disabled}
          id={`${listboxId}-option-${optionIndex}`}
          label={option.name}
          level={level}
          mode={mode}
          name={option.name}
          onClick={() => {
            if (disabled) return;
            if (hasChildren && type === 'tree' && mode === 'multiple' && option.showCheckbox) {
              toggleExpand(option.id);
            } else if (hasChildren && type === 'tree') {
              toggleExpand(option.id);
            } else {
              onSelect?.(option);
            }
          }}
          onCheckedChange={() => {
            if (!disabled) {
              onSelect?.(option);
            }
          }}
          followText={followText}
          checkSite={checkSite}
          onMouseEnter={() => onHover?.(optionIndex)}
          prependIcon={prependIcon}
          showUnderline={option.showUnderline ?? false}
          validate={option.validate ?? 'default'}
          appendContent={shortcutText}
        />
      );

      if (hasChildren && isExpanded && type === 'tree') {
        const childResult = renderTreeOptions(option.children, depth + 1, currentIndex);
        currentIndex = childResult.nextIndex;
        return [card, ...childResult.elements];
      }

      return [card];
    });

    return { elements, nextIndex: currentIndex };
  };

  const renderDefaultOptions = (
    optionList: DropdownOption[] | undefined,
    startIndex: number,
  ): { elements: ReactNode[]; nextIndex: number } => {
    let currentIndex = startIndex;

    const elements = (optionList ?? []).flatMap((option) => {
      currentIndex += 1;

      const optionIndex = currentIndex;
      const isSelected = Array.isArray(value)
        ? value.includes(option.id)
        : value === option.id;
      const isActive = optionIndex === activeIndex;
      const shortcutText = option.shortcutText
        ? option.shortcutText
        : shortcutTextHandler(option.shortcutKeys ?? []);

      const checkSite: DropdownCheckPosition = option?.checkSite ?? 'none';

      return (
        <DropdownItemCard
          followText={followText}
          key={option.id}
          active={isActive}
          checked={isSelected}
          disabled={disabled}
          id={`${listboxId}-option-${optionIndex}`}
          label={option.name}
          mode={mode}
          name={option.name}
          onClick={() => {
            if (disabled) return;
            onSelect?.(option);
          }}
          onMouseEnter={() => onHover?.(optionIndex)}
          prependIcon={option.icon}
          validate={option.validate ?? 'default'}
          showUnderline={option.showUnderline ?? false}
          checkSite={checkSite}
          appendContent={shortcutText}
        />
      )
    })

    return { elements, nextIndex: currentIndex };
  };

  const renderOptions = (
    optionList: DropdownOption[] | undefined,
    depth: number,
    startIndex: number,
  ): { elements: ReactNode[]; nextIndex: number } => {
    if (type === 'grouped') {
      return renderGroupedOptions(optionList, startIndex);
    }

    if (type === 'tree') {
      return renderTreeOptions(optionList, depth, startIndex);
    }

    return renderDefaultOptions(optionList, startIndex);
  };

  const { elements: renderedOptions } = renderOptions(optionsContent, 0, -1);

  // Show status when options are empty and status is provided
  const shouldShowStatus = optionsContent.length === 0 && status;

  const listStyle = useMemo((): React.CSSProperties | undefined => {
    if (!maxHeight) {
      return undefined;
    }

    return {
      maxHeight: typeof maxHeight === 'number' ? `${maxHeight}px` : maxHeight,
    };
  }, [maxHeight]);

  const listWrapperStyle = useMemo((): React.CSSProperties | undefined => {
    if (!maxHeight) {
      return undefined;
    }

    const maxHeightValue = typeof maxHeight === 'number' ? maxHeight : parseFloat(maxHeight);
    const availableHeight = Math.max(0, maxHeightValue - actionHeight - headerHeight);

    return {
      maxHeight: `${availableHeight}px`,
    };
  }, [maxHeight, actionHeight, headerHeight]);

  const getIsAtBottom = useCallback((viewport: HTMLDivElement) => {
    const { scrollTop, scrollHeight, clientHeight } = viewport;
    return scrollTop + clientHeight >= scrollHeight - 1;
  }, []);

  useEffect(() => {
    const listElement = listRef.current;
    if (!listElement || disabled) {
      return;
    }

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.repeat) return;

      const targetOption = visibleShortcutOptions.find((option) => {
        if (!Array.isArray(option.shortcutKeys) || option.shortcutKeys.length === 0) {
          return false;
        }
        return option.shortcutKeys.some((shortcut) => matchShortcut(event, shortcut));
      });

      if (!targetOption) return;

      event.preventDefault();
      event.stopPropagation();

      if (type === 'tree' && targetOption.children && targetOption.children.length > 0) {
        toggleExpand(targetOption.id);
        return;
      }

      onSelect?.(targetOption);
    };

    listElement.addEventListener('keydown', handleKeyDown);

    return () => {
      listElement.removeEventListener('keydown', handleKeyDown);
    };
  }, [disabled, matchShortcut, onSelect, type, toggleExpand, visibleShortcutOptions]);

  const handleViewportReady = useCallback(
    (viewport: HTMLDivElement) => {
      viewportRef.current = viewport;
      listWrapperRef.current = viewport;
      wasAtBottomRef.current = getIsAtBottom(viewport);
    },
    [getIsAtBottom],
  );

  useEffect(() => {
    if (shouldUseScrollbar) {
      return;
    }

    const listWrapperElement = listWrapperRef.current;
    if (!listWrapperElement || !maxHeight || (!onReachBottom && !onLeaveBottom && !onScroll)) {
      return;
    }

    // Initialize wasAtBottom state by checking current position
    const checkInitialState = () => {
      const { scrollTop, scrollHeight, clientHeight } = listWrapperElement;
      return scrollTop + clientHeight >= scrollHeight - 1;
    };

    let wasAtBottom = checkInitialState();

    const handleScroll = () => {
      const { scrollTop, scrollHeight, clientHeight } = listWrapperElement;
      const maxScrollTop = scrollHeight - clientHeight;

      // Call onScroll callback if provided
      if (onScroll) {
        onScroll(
          {
            scrollTop,
            maxScrollTop,
          },
          listWrapperElement,
        );
      }

      // Check if scrolled to bottom (with 1px threshold for rounding errors)
      const isAtBottom = scrollTop + clientHeight >= scrollHeight - 1;

      // Trigger onReachBottom when entering bottom state
      if (isAtBottom && !wasAtBottom) {
        onReachBottom?.();
      }

      // Trigger onLeaveBottom when leaving bottom state
      if (!isAtBottom && wasAtBottom) {
        onLeaveBottom?.();
      }

      wasAtBottom = isAtBottom;
    };

    listWrapperElement.addEventListener('scroll', handleScroll);

    return () => {
      listWrapperElement.removeEventListener('scroll', handleScroll);
    };
  }, [maxHeight, onReachBottom, onLeaveBottom, onScroll, shouldUseScrollbar]);

  const scrollbarEvents = useMemo<OverlayScrollbarsComponentProps['events'] | undefined>(() => {
    if (!shouldUseScrollbar || (!onReachBottom && !onLeaveBottom && !onScroll)) {
      return undefined;
    }

    return {
      scroll: (_instance: OverlayScrollbars, _event: Event) => {
        const viewport = viewportRef.current;
        if (!viewport) return;

        const { scrollTop, scrollHeight, clientHeight } = viewport;
        const maxScrollTop = scrollHeight - clientHeight;

        if (onScroll) {
          onScroll(
            {
              scrollTop,
              maxScrollTop,
            },
            viewport,
          );
        }

        const isAtBottom = getIsAtBottom(viewport);

        if (isAtBottom && !wasAtBottomRef.current) {
          onReachBottom?.();
        }

        if (!isAtBottom && wasAtBottomRef.current) {
          onLeaveBottom?.();
        }

        wasAtBottomRef.current = isAtBottom;
      },
    };
  }, [getIsAtBottom, shouldUseScrollbar, onReachBottom, onLeaveBottom, onScroll]);

  return (
    <ul
      aria-label={listboxLabel || (optionsContent.length === 0 ? 'Dropdown options' : undefined)}
      className={dropdownClasses.list}
      id={listboxId}
      ref={listRef}
      role="listbox"
      style={listStyle}
      tabIndex={-1}
    >
      {hasHeader && (
        <li
          className={dropdownClasses.listHeader}
          role="presentation"
          ref={headerRef}
        >
          <div className={dropdownClasses.listHeaderInner}>
            {headerContent}
          </div>
        </li>
      )}
      {
        maxHeight
          ? (
            shouldUseScrollbar ? (
              <Scrollbar
                className={dropdownClasses.listWrapper}
                defer={scrollbarDefer}
                disabled={false}
                events={scrollbarEvents}
                maxHeight={listWrapperStyle?.maxHeight}
                maxWidth={scrollbarMaxWidth}
                onViewportReady={handleViewportReady}
                options={scrollbarOptions}
              >
                {shouldShowStatus ? (
                  <DropdownStatus
                    status={status}
                    loadingText={loadingText}
                    emptyText={emptyText}
                    emptyIcon={emptyIcon}
                  />
                ) : (
                  renderedOptions
                )}
              </Scrollbar>
            ) : (
              <div
                ref={listWrapperRef}
                className={dropdownClasses.listWrapper}
                style={listWrapperStyle}
              >
                {shouldShowStatus ? (
                  <DropdownStatus
                    status={status}
                    loadingText={loadingText}
                    emptyText={emptyText}
                    emptyIcon={emptyIcon}
                  />
                ) : (
                  renderedOptions
                )}
              </div>
            )
          )
          : shouldShowStatus ? (
            <DropdownStatus
              status={status}
              loadingText={loadingText}
              emptyText={emptyText}
              emptyIcon={emptyIcon}
            />
          ) : (
            renderedOptions
          )
      }
      {hasActions && (
        <div ref={actionRef}>
          <DropdownAction {...actionConfig} />
        </div>
      )}
    </ul>
  );
}

// packages/vue/dropdown/dropdown-item.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import type { CSSProperties, FunctionalComponent } from 'vue';
import {
  dropdownClasses,
  type DropdownCheckPosition,
  type DropdownOption,
} from '@mezzanine-ui/core/dropdown/dropdown';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import { CaretDownIcon, CaretRightIcon } from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import keycode from 'keycode';
import { useElementHeight } from '../_internal/use-element-height';
import MznScrollbar from '../scrollbar/scrollbar.vue';
import MznTypography from '../typography/typography.vue';
import MznDropdownAction from './dropdown-action.vue';
import MznDropdownItemCard from './dropdown-item-card.vue';
import MznDropdownStatus from './dropdown-status.vue';
import shortcutTextHandler from './shortcut-text-handler';
import type { DropdownItemCardProps } from './dropdown-item-card.types';
import type { DropdownItemProps, DropdownItemRow } from './dropdown-item.types';

// Helper function to get only leaf descendant IDs from a tree option (nodes without children)
function getLeafDescendantIds(option: DropdownOption): string[] {
  if (!option.children || option.children.length === 0) {
    return [String(option.id)];
  }

  return option.children.flatMap(getLeafDescendantIds);
}

/**
 * Limits DropdownOption array to a maximum depth, truncating extra children
 * levels and showing an error message if exceeded.
 */
function truncateArrayDepth(
  input: DropdownOption[],
  maxDepth = 3,
  warn = true,
): DropdownOption[] {
  const truncate = (
    options: DropdownOption[],
    currentDepth = 1,
  ): DropdownOption[] => {
    if (currentDepth >= maxDepth) {
      // Stop going deeper once maximum depth is reached, remove children
      return options.map(({ children: _children, ...option }) => option);
    }

    return options.map((option) => {
      if (!option.children) return option;

      return {
        ...option,
        children: truncate(option.children, currentDepth + 1),
      };
    });
  };

  const getDepth = (
    options: DropdownOption[] | undefined,
    depth = 1,
  ): number => {
    if (!options || options.length === 0) return depth - 1;

    return Math.max(
      ...options.map((option) => {
        if (!option.children || option.children.length === 0) {
          return depth - 1;
        }

        return getDepth(option.children, depth + 1);
      }),
    );
  };

  if (getDepth(input) <= maxDepth) return input;

  // Exceeds maximum depth → warn
  if (warn) {
    console.error(
      `[truncateArrayDepth] Input DropdownOption array exceeds ${maxDepth} levels. Extra levels were truncated.`,
    );
  }

  return truncate(input);
}

/**
 * 下拉選單的清單本體。
 *
 * `type` 決定結構：`default` 是平的、`grouped` 多一層群組標題、`tree` 最多三層可展開。
 * 超過三層會被截斷並在 console 報錯。選項可帶快捷鍵，清單取得焦點時按下就會選取。
 * 設了 `maxHeight` 會啟用捲動（預設走 MznScrollbar），並在到底／離底時送出事件。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDropdownItem } from '@mezzanine-ui/vue/dropdown';
 * <\/script>
 *
 * <template>
 *   <MznDropdownItem
 *     :active-index="activeIndex"
 *     listbox-id="listbox"
 *     :options="options"
 *     @select="onSelect"
 *   />
 * </template>
 * ```
 *
 * @see MznDropdown 帶觸發元素與浮層的完整元件
 * @see MznDropdownItemCard 單一選項列
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DropdownItemProps>(), {
  actionConfig: undefined,
  disabled: false,
  emptyIcon: undefined,
  emptyText: undefined,
  expandedNodes: undefined,
  followText: undefined,
  headerContent: undefined,
  keyboardActiveIndex: undefined,
  listboxLabel: undefined,
  loadingPosition: 'full',
  loadingText: undefined,
  maxHeight: undefined,
  minWidth: undefined,
  mode: 'single',
  sameWidth: false,
  scrollbarDefer: true,
  scrollbarDisabled: false,
  scrollbarMaxWidth: undefined,
  scrollbarOptions: undefined,
  status: undefined,
  toggleCheckedOnClick: undefined,
  type: undefined,
  value: undefined,
});

const emit = defineEmits<{
  hover: [index: number];
  leaveBottom: [];
  reachBottom: [];
  scroll: [
    computed: { maxScrollTop: number; scrollTop: number },
    target: HTMLDivElement,
  ];
  select: [option: DropdownOption];
  toggleExpand: [id: string];
}>();

/** React takes the header as a node prop, so this renders one. */
const HeaderContent: FunctionalComponent = () => props.headerContent;

const list = ref<HTMLUListElement | null>(null);
const listWrapper = ref<HTMLDivElement | null>(null);
const viewport = ref<HTMLDivElement | null>(null);
const header = ref<HTMLLIElement | null>(null);
const action = ref<HTMLDivElement | null>(null);
const internalExpandedNodes = ref<Set<string>>(new Set());
let wasAtBottom = false;

const optionsContent = computed((): DropdownOption[] =>
  truncateArrayDepth(props.options as DropdownOption[], 3),
);

const expandedNodes = computed(
  (): Set<string> => props.expandedNodes ?? internalExpandedNodes.value,
);

const hasActions = computed((): boolean =>
  Boolean(props.actionConfig?.showActions),
);
const hasHeader = computed((): boolean => Boolean(props.headerContent));
const shouldUseScrollbar = computed((): boolean =>
  Boolean(props.maxHeight && !props.scrollbarDisabled),
);

// Measure the areas that eat into the scrollable height
const { height: actionHeight } = useElementHeight(action, () =>
  Boolean(hasActions.value && props.maxHeight),
);
const { height: headerHeight } = useElementHeight(header, () =>
  Boolean(hasHeader.value && props.maxHeight),
);

function toggleExpand(optionId: string): void {
  if (props.expandedNodes) {
    emit('toggleExpand', optionId);

    return;
  }

  const next = new Set(internalExpandedNodes.value);

  if (next.has(optionId)) {
    next.delete(optionId);
  } else {
    next.add(optionId);
  }

  internalExpandedNodes.value = next;
}

const activeIndexForCard = computed((): number | null =>
  props.keyboardActiveIndex !== undefined
    ? props.keyboardActiveIndex
    : props.activeIndex,
);

function calculateNodeSelectionState(
  option: DropdownOption,
  selectedIds: string[],
): { checked: boolean; indeterminate: boolean } {
  if (!option.children || option.children.length === 0) {
    return {
      checked: selectedIds.includes(String(option.id)),
      indeterminate: false,
    };
  }

  // Only check leaf descendants since parent nodes are never added to selectedIds
  const leafIds = getLeafDescendantIds(option);
  const selectedLeafCount = leafIds.filter((id) =>
    selectedIds.includes(id),
  ).length;

  if (selectedLeafCount === 0) return { checked: false, indeterminate: false };

  if (selectedLeafCount === leafIds.length) {
    return { checked: true, indeterminate: false };
  }

  return { checked: false, indeterminate: true };
}

const shortcutTextOf = (option: DropdownOption): string =>
  option.shortcutText
    ? option.shortcutText
    : shortcutTextHandler(option.shortcutKeys ?? []);

const isSelected = (option: DropdownOption): boolean =>
  Array.isArray(props.value)
    ? props.value.includes(option.id)
    : props.value === option.id;

/**
 * The list, flattened in render order with React's running index: a group
 * label does not consume one, every card does, and a tree's children are
 * numbered immediately after their parent.
 */
const rows = computed((): DropdownItemRow[] => {
  const result: DropdownItemRow[] = [];
  let currentIndex = -1;

  const pushCard = (
    option: DropdownOption,
    cardProps: DropdownItemCardProps & { class?: string },
    handlers: { onCheckedChange?: () => void; onClick: () => void },
    optionIndex: number,
  ): void => {
    result.push({
      kind: 'card',
      option,
      optionIndex,
      props: cardProps,
      ...handlers,
    });
  };

  const renderGrouped = (optionList: DropdownOption[]): void => {
    optionList.forEach((groupOption) => {
      if (!groupOption.children || groupOption.children.length === 0) return;

      result.push({
        id: groupOption.id,
        kind: 'group',
        name: groupOption.name,
      });

      groupOption.children.forEach((option) => {
        currentIndex += 1;

        const optionIndex = currentIndex;

        pushCard(
          option,
          {
            active: optionIndex === activeIndexForCard.value,
            appendContent: shortcutTextOf(option),
            checked: isSelected(option),
            checkSite: option?.checkSite ?? 'suffix',
            disabled: props.disabled,
            followText: props.followText,
            id: `${props.listboxId}-option-${optionIndex}`,
            label: option.name,
            mode: props.mode,
            name: option.name,
            showUnderline: option.showUnderline ?? false,
            toggleCheckedOnClick: props.toggleCheckedOnClick,
            validate: option.validate ?? 'default',
          },
          {
            onClick: () => {
              if (props.disabled) return;

              emit('select', option);
            },
          },
          optionIndex,
        );
      });
    });
  };

  const renderTree = (optionList: DropdownOption[], depth: number): void => {
    const selectedIds = Array.isArray(props.value)
      ? props.value.map((id) => String(id))
      : props.value
        ? [String(props.value)]
        : [];

    optionList.forEach((option) => {
      currentIndex += 1;

      const optionIndex = currentIndex;
      const level = Math.min(depth, 2) as 0 | 1 | 2;
      const hasChildren = Boolean(
        option.children && option.children.length > 0,
      );
      const isExpanded = hasChildren && expandedNodes.value.has(option.id);
      let prependIcon: IconDefinition | undefined = undefined;

      if (hasChildren && level !== 2) {
        prependIcon = isExpanded ? CaretDownIcon : CaretRightIcon;
      }

      const checkSite: DropdownCheckPosition = option.showCheckbox
        ? 'prefix'
        : (option.checkSite ?? (props.mode === 'single' ? 'suffix' : 'none'));
      const selectionState =
        hasChildren && props.mode === 'multiple'
          ? calculateNodeSelectionState(option, selectedIds)
          : {
              checked: selectedIds.includes(String(option.id)),
              indeterminate: false,
            };
      const resolvedToggleCheckedOnClick =
        props.toggleCheckedOnClick ??
        !(
          hasChildren &&
          props.type === 'tree' &&
          props.mode === 'multiple' &&
          option.showCheckbox
        );

      pushCard(
        option,
        {
          active: optionIndex === activeIndexForCard.value,
          appendContent: shortcutTextOf(option),
          checked: selectionState.checked,
          checkSite,
          class:
            !hasChildren && level === 1
              ? dropdownClasses.cardLeafLevel1
              : undefined,
          disabled: props.disabled,
          followText: props.followText,
          id: `${props.listboxId}-option-${optionIndex}`,
          indeterminate: selectionState.indeterminate,
          label: option.name,
          level,
          mode: props.mode,
          name: option.name,
          prependIcon,
          showUnderline: option.showUnderline ?? false,
          toggleCheckedOnClick: resolvedToggleCheckedOnClick,
          validate: option.validate ?? 'default',
        },
        {
          onCheckedChange: () => {
            if (!props.disabled) {
              emit('select', option);
            }
          },
          onClick: () => {
            if (props.disabled) return;

            if (hasChildren && props.type === 'tree') {
              toggleExpand(option.id);

              return;
            }

            // In `tree` + `multiple` mode the card already triggers selection
            // through `checkedChange` when the row is clicked, so calling
            // `select` here would fire it twice for leaf nodes. The same holds
            // in `multiple` mode whenever `toggleCheckedOnClick` is enabled.
            if (
              !(props.type === 'tree' && props.mode === 'multiple') &&
              !(props.mode === 'multiple' && resolvedToggleCheckedOnClick)
            ) {
              emit('select', option);
            }
          },
        },
        optionIndex,
      );

      if (hasChildren && isExpanded && props.type === 'tree') {
        renderTree(option.children!, depth + 1);
      }
    });
  };

  const renderDefault = (optionList: DropdownOption[]): void => {
    optionList.forEach((option) => {
      currentIndex += 1;

      const optionIndex = currentIndex;

      pushCard(
        option,
        {
          active: optionIndex === activeIndexForCard.value,
          appendContent: shortcutTextOf(option),
          checked: isSelected(option),
          checkSite: option?.checkSite ?? 'suffix',
          disabled: props.disabled,
          followText: props.followText,
          id: `${props.listboxId}-option-${optionIndex}`,
          label: option.name,
          mode: props.mode,
          name: option.name,
          prependIcon: option.icon,
          showUnderline: option.showUnderline ?? false,
          toggleCheckedOnClick: props.toggleCheckedOnClick,
          validate: option.validate ?? 'default',
        },
        {
          onClick: () => {
            if (props.disabled) return;

            emit('select', option);
          },
        },
        optionIndex,
      );
    });
  };

  if (props.type === 'grouped') {
    renderGrouped(optionsContent.value);
  } else if (props.type === 'tree') {
    renderTree(optionsContent.value, 0);
  } else {
    renderDefault(optionsContent.value);
  }

  return result;
});

// Show full status when options are empty and status is provided.
// Empty status always shows as full; loading respects loadingPosition.
const shouldShowFullStatus = computed((): boolean =>
  Boolean(
    optionsContent.value.length === 0 &&
      props.status &&
      (props.status === 'empty' || props.loadingPosition !== 'bottom'),
  ),
);

const shouldShowBottomLoading = computed((): boolean =>
  Boolean(props.status === 'loading' && props.loadingPosition === 'bottom'),
);

const listStyle = computed((): CSSProperties | undefined => {
  const styles: CSSProperties & Record<string, unknown> = {};

  if (props.maxHeight) {
    styles.maxHeight =
      typeof props.maxHeight === 'number'
        ? `${props.maxHeight}px`
        : props.maxHeight;
  }

  if (props.minWidth !== undefined) {
    styles['--mzn-dropdown-list-min-width'] =
      typeof props.minWidth === 'number'
        ? `${props.minWidth}px`
        : props.minWidth;
  }

  return Object.keys(styles).length > 0 ? styles : undefined;
});

const listWrapperMaxHeight = computed((): string | undefined => {
  if (!props.maxHeight) return undefined;

  const maxHeightValue =
    typeof props.maxHeight === 'number'
      ? props.maxHeight
      : parseFloat(props.maxHeight);

  return `${Math.max(0, maxHeightValue - actionHeight.value - headerHeight.value)}px`;
});

const listWrapperStyle = computed((): CSSProperties | undefined =>
  props.maxHeight ? { maxHeight: listWrapperMaxHeight.value } : undefined,
);

const getIsAtBottom = (element: HTMLElement): boolean => {
  const { scrollTop, scrollHeight, clientHeight } = element;

  return scrollTop + clientHeight >= scrollHeight - 1;
};

const visibleShortcutOptions = computed((): DropdownOption[] => {
  const result: DropdownOption[] = [];

  const collectTree = (optionList?: DropdownOption[]): void => {
    optionList?.forEach((option) => {
      result.push(option);

      if (option.children && expandedNodes.value.has(option.id)) {
        collectTree(option.children);
      }
    });
  };

  if (props.type === 'grouped') {
    optionsContent.value.forEach((groupOption) => {
      groupOption.children?.forEach((option) => result.push(option));
    });
  } else if (props.type === 'tree') {
    collectTree(optionsContent.value);
  } else {
    optionsContent.value.forEach((option) => result.push(option));
  }

  return result;
});

function matchShortcut(
  event: KeyboardEvent,
  shortcut: number | string,
): boolean {
  const eventCode = event.which ?? event.keyCode;

  if (typeof shortcut === 'number') {
    return eventCode === shortcut;
  }

  const tokens = shortcut
    .split('+')
    .map((token) => token.trim().toLowerCase())
    .filter(Boolean);

  let requireMeta = false;
  let requireCtrl = false;
  let requireAlt = false;
  let requireShift = false;
  let mainToken: string | null = null;

  tokens.forEach((token) => {
    switch (token) {
      case 'cmd':
      case 'meta':
      case 'command':
        requireMeta = true;
        break;
      case 'ctrl':
      case 'control':
        requireCtrl = true;
        break;
      case 'alt':
      case 'option':
        requireAlt = true;
        break;
      case 'shift':
        requireShift = true;
        break;
      default:
        mainToken = token;
        break;
    }
  });

  if (!mainToken) return false;

  if (
    requireMeta !== event.metaKey ||
    requireCtrl !== event.ctrlKey ||
    requireAlt !== event.altKey ||
    requireShift !== event.shiftKey
  ) {
    return false;
  }

  const mainCode = keycode(mainToken);

  if (typeof mainCode === 'number' && eventCode === mainCode) {
    return true;
  }

  const eventKey = event.key?.toLowerCase();

  if (eventKey && eventKey === mainToken) {
    return true;
  }

  const eventKeyName = keycode(eventCode);

  return (
    typeof eventKeyName === 'string' && eventKeyName.toLowerCase() === mainToken
  );
}

function handleShortcutKeyDown(event: KeyboardEvent): void {
  if (event.repeat || isImeComposing(event)) return;

  const targetOption = visibleShortcutOptions.value.find((option) => {
    if (
      !Array.isArray(option.shortcutKeys) ||
      option.shortcutKeys.length === 0
    ) {
      return false;
    }

    return option.shortcutKeys.some((shortcut) =>
      matchShortcut(event, shortcut),
    );
  });

  if (!targetOption) return;

  event.preventDefault();
  event.stopPropagation();

  if (
    props.type === 'tree' &&
    targetOption.children &&
    targetOption.children.length > 0
  ) {
    toggleExpand(targetOption.id);

    return;
  }

  emit('select', targetOption);
}

let boundList: HTMLUListElement | null = null;

const unbindShortcuts = (): void => {
  boundList?.removeEventListener('keydown', handleShortcutKeyDown);
  boundList = null;
};

watch(
  [list, () => props.disabled],
  ([element, disabled]) => {
    unbindShortcuts();

    if (!element || disabled) return;

    boundList = element;
    element.addEventListener('keydown', handleShortcutKeyDown);
  },
  { immediate: true },
);

onBeforeUnmount(unbindShortcuts);

function reportScroll(element: HTMLElement): void {
  const { scrollTop, scrollHeight, clientHeight } = element;

  emit(
    'scroll',
    { maxScrollTop: scrollHeight - clientHeight, scrollTop },
    element as HTMLDivElement,
  );

  const isAtBottom = getIsAtBottom(element);

  if (isAtBottom && !wasAtBottom) emit('reachBottom');
  if (!isAtBottom && wasAtBottom) emit('leaveBottom');

  wasAtBottom = isAtBottom;
}

function handleViewportReady(element: HTMLDivElement): void {
  viewport.value = element;
  listWrapper.value = element;
  wasAtBottom = getIsAtBottom(element);
}

const scrollbarEvents = computed(() => ({
  scroll: () => {
    if (viewport.value) reportScroll(viewport.value);
  },
}));

function handleWrapperScroll(event: Event): void {
  reportScroll(event.target as HTMLElement);
}

/**
 * Auto-scroll to the bottom when the bottom loading row appears and the user
 * was already at the bottom.
 */
watch(shouldShowBottomLoading, (loading, previous) => {
  if (!loading || previous) return;

  const element = shouldUseScrollbar.value
    ? viewport.value
    : props.maxHeight
      ? listWrapper.value
      : null;

  if (!element || !wasAtBottom) return;

  // Wait for the loading row to be in the DOM before measuring again.
  requestAnimationFrame(() => {
    element.scrollTop = element.scrollHeight;
  });
});

/**
 * Keep focus on the trigger while pressing an option: without this, mousedown
 * blurs the input before the click lands, and a consumer that resets its
 * search text on blur re-renders the list underneath the cursor. The header
 * is excluded because it may hold a real input.
 */
function handleListMouseDown(event: MouseEvent): void {
  if (header.value?.contains(event.target as Node)) return;

  event.preventDefault();
}

const ariaLabel = computed(
  (): string | undefined =>
    props.listboxLabel ||
    (optionsContent.value.length === 0 ? 'Dropdown options' : undefined),
);

const groupLabelClass = dropdownClasses.groupLabel;
const listClass = dropdownClasses.list;
const listHeaderClass = dropdownClasses.listHeader;
const listHeaderInnerClass = dropdownClasses.listHeaderInner;
const listWrapperClass = dropdownClasses.listWrapper;
const loadingMoreClass = dropdownClasses.loadingMore;
const actionWrapperStyle = { position: 'relative', zIndex: 0 } as const;
</script>

<template>
  <ul
    ref="list"
    :aria-label="ariaLabel"
    :class="listClass"
    :id="listboxId"
    role="listbox"
    :style="listStyle"
    :tabindex="-1"
    @mousedown="handleListMouseDown"
  >
    <li
      v-if="hasHeader"
      ref="header"
      :class="listHeaderClass"
      role="presentation"
    >
      <div :class="listHeaderInnerClass"><HeaderContent /></div>
    </li>
    <template v-if="maxHeight">
      <MznScrollbar
        v-if="shouldUseScrollbar"
        :class="listWrapperClass"
        :defer="scrollbarDefer"
        :disabled="false"
        :events="scrollbarEvents"
        :max-height="listWrapperMaxHeight"
        :max-width="scrollbarMaxWidth"
        :options="scrollbarOptions"
        @viewport-ready="handleViewportReady"
      >
        <MznDropdownStatus
          v-if="shouldShowFullStatus"
          :empty-icon="emptyIcon"
          :empty-text="emptyText"
          :loading-text="loadingText"
          :status="status!"
        />
        <template v-else>
          <template
            v-for="row in rows"
            :key="row.kind === 'group' ? row.id : row.option.id"
          >
            <MznTypography
              v-if="row.kind === 'group'"
              :class="groupLabelClass"
              variant="body"
            >
              {{ row.name }}
            </MznTypography>
            <MznDropdownItemCard
              v-else
              v-bind="row.props"
              @checked-change="row.onCheckedChange?.()"
              @click="row.onClick()"
              @mouse-enter="emit('hover', row.optionIndex)"
            />
          </template>
          <li
            v-if="shouldShowBottomLoading"
            aria-live="polite"
            :class="loadingMoreClass"
            role="status"
          >
            <MznDropdownStatus :loading-text="loadingText" status="loading" />
          </li>
        </template>
      </MznScrollbar>
      <div
        v-else
        ref="listWrapper"
        :class="listWrapperClass"
        :style="listWrapperStyle"
        @scroll="handleWrapperScroll"
      >
        <MznDropdownStatus
          v-if="shouldShowFullStatus"
          :empty-icon="emptyIcon"
          :empty-text="emptyText"
          :loading-text="loadingText"
          :status="status!"
        />
        <template v-else>
          <template
            v-for="row in rows"
            :key="row.kind === 'group' ? row.id : row.option.id"
          >
            <MznTypography
              v-if="row.kind === 'group'"
              :class="groupLabelClass"
              variant="body"
            >
              {{ row.name }}
            </MznTypography>
            <MznDropdownItemCard
              v-else
              v-bind="row.props"
              @checked-change="row.onCheckedChange?.()"
              @click="row.onClick()"
              @mouse-enter="emit('hover', row.optionIndex)"
            />
          </template>
          <li
            v-if="shouldShowBottomLoading"
            aria-live="polite"
            :class="loadingMoreClass"
            role="status"
          >
            <MznDropdownStatus :loading-text="loadingText" status="loading" />
          </li>
        </template>
      </div>
    </template>
    <MznDropdownStatus
      v-else-if="shouldShowFullStatus"
      :empty-icon="emptyIcon"
      :empty-text="emptyText"
      :loading-text="loadingText"
      :status="status!"
    />
    <template v-else>
      <template
        v-for="row in rows"
        :key="row.kind === 'group' ? row.id : row.option.id"
      >
        <MznTypography
          v-if="row.kind === 'group'"
          :class="groupLabelClass"
          variant="body"
        >
          {{ row.name }}
        </MznTypography>
        <MznDropdownItemCard
          v-else
          v-bind="row.props"
          @checked-change="row.onCheckedChange?.()"
          @click="row.onClick()"
          @mouse-enter="emit('hover', row.optionIndex)"
        />
      </template>
      <li
        v-if="shouldShowBottomLoading"
        aria-live="polite"
        :class="loadingMoreClass"
        role="status"
      >
        <MznDropdownStatus :loading-text="loadingText" status="loading" />
      </li>
    </template>
    <div v-if="hasActions" ref="action" :style="actionWrapperStyle">
      <MznDropdownAction v-bind="actionConfig" />
    </div>
  </ul>
</template>
