// packages/react/src/Button/ButtonGroup.tsx
import {
  Children,
  cloneElement,
  DetailedHTMLProps,
  forwardRef,
  HTMLAttributes,
  ReactElement,
} from 'react';
import {
  ButtonColor,
  buttonGroupClasses as classes,
  ButtonGroupOrientation,
  ButtonGroupSpacing,
  ButtonSize,
  ButtonVariant,
  toButtonGroupCssVars,
} from '@mezzanine-ui/core/button';
import { cx } from '../utils/cx';
import { ButtonProps } from './Button';
import { IconButtonProps } from './IconButton';

export type ButtonGroupChild = ReactElement<ButtonProps | IconButtonProps>;

export interface ButtonGroupProps extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement> {
  /**
   * If `true`, all buttons will not have spacing between each others.
   * @default false
   */
  attached?: boolean;
  /**
   * Only accept button elements or icon button elements.
   */
  children: ButtonGroupChild | ButtonGroupChild[];
  /**
   * If the `color` of a button inside group not provided, the `color` of group will override it.
   * @default 'primary'
   */
  color?: ButtonColor;
  /**
   * If the `disabled` of a button inside group not provided, the `disabled` of group will override it.
   * @default false
   */
  disabled?: boolean;
  /**
   * If the `error` of a button inside group not provided, the `error` of group will override it.
   * @default false
   */
  error?: boolean;
  /**
   * If `true`, set width: 100%.
   * @default false
   */
  fullWidth?: boolean;
  /**
   * The orientation of button group.
   * @default horizontal
   */
  orientation?: ButtonGroupOrientation;
  /**
   * If the `size` of a button inside group not provided, the `size` of group will override it.
   * @default 'medium'
   */
  size?: ButtonSize;
  /**
   * The spacing level of button gap between each buttons.
   * Will be added on if `attached`=false.
   * @default small:3,others:4
   */
  spacing?: ButtonGroupSpacing;
  /**
   * If the `variant` of a button inside group not provided, the `variant` of group will override it.
   * @default 'text'
   */
  variant?: ButtonVariant;
}

/**
 * The react component for `mezzanine` button group.
 */
const ButtonGroup = forwardRef<HTMLDivElement, ButtonGroupProps>(function ButtonGroup(props, ref) {
  const {
    attached = false,
    children,
    className,
    color = 'primary',
    disabled = false,
    error = false,
    fullWidth = false,
    orientation = 'horizontal',
    role = 'group',
    size = 'medium',
    spacing,
    style: styleProp,
    variant = 'text',
    ...rest
  } = props;
  const cssVars = toButtonGroupCssVars({ size, spacing });
  const style = {
    ...styleProp,
    ...cssVars,
  };

  return (
    <div
      ref={ref}
      {...rest}
      aria-orientation={orientation}
      className={cx(
        classes.host,
        classes.orientation(orientation),
        {
          [classes.fullWidth]: fullWidth,
          [classes.attached]: attached,
        },
        className,
      )}
      role={role}
      style={style}
    >
      {Children.map(children, (unknownChild) => {
        const child = unknownChild as ButtonGroupChild;

        return cloneElement(child, {
          color: child.props.color || color,
          disabled: child.props.disabled ?? disabled,
          error: child.props.error ?? error,
          size: child.props.size || size,
          variant: child.props.variant || variant,
        });
      })}
    </div>
  );
});

export default ButtonGroup;

// packages/ng/button/button-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  forwardRef,
  HostBinding,
  Input,
  OnChanges,
  OnInit,
  Renderer2,
  ViewEncapsulation,
} from '@angular/core';
import {
  ButtonColor,
  buttonGroupClasses as classes,
  ButtonGroupOrientation,
  ButtonGroupSpacing,
  ButtonSize,
  ButtonVariant,
  toButtonGroupCssVars,
} from '@mezzanine-ui/core/button';
import {
  BooleanInput,
  createCssVarsChangeEffect,
  HostBindingClass,
  HostBindingEnumClass,
  InputBoolean,
  InputNumber,
  TypedSimpleChanges,
} from '@mezzanine-ui/ng/cdk';
import { MznButtonGroupControlInputs, MznButtonGroupControlInputsToken } from './button-group.tokens';

@Component({
  selector: 'mzn-button-group',
  exportAs: 'mznButtonGroup',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    {
      provide: MznButtonGroupControlInputsToken,
      useExisting: forwardRef(() => MznButtonGroupComponent),
    },
  ],
  template: `
    <ng-content></ng-content>
  `,
})
export class MznButtonGroupComponent implements MznButtonGroupControlInputs, OnChanges, OnInit {
  static ngAcceptInputType_attached: BooleanInput;

  static ngAcceptInputType_danger: BooleanInput;

  static ngAcceptInputType_disabled: BooleanInput;

  static ngAcceptInputType_fullWidth: BooleanInput;

  constructor(
    private readonly elementRef: ElementRef<HTMLElement>,
    private readonly renderer: Renderer2,
  ) { }

  @HostBindingClass(classes.host)
  readonly bindHostClass = true;

  /**
   * If `true`, all buttons will not have spacing between each others.
   * @default false
   */
  @HostBindingClass(classes.attached)
  @Input()
  @InputBoolean()
  attached = false;

  /**
   * If the `color` of a button inside group not provided, the `color` of group will override it.
   * @default 'primary'
   */
  @Input()
  color: ButtonColor = 'primary';

  /**
   * If the `error` of a button inside group not provided, the `error` of group will override it.
   * @default false
   */
  @Input()
  @InputBoolean()
  danger = false;

  /**
   * If the `disabled` of a button inside group not provided, the `disabled` of group will override it.
   * @default false
   */
  @Input()
  @InputBoolean()
  disabled = false;

  /**
   * If `true`, set width: 100%.
   * @default false
   */
  @HostBindingClass(classes.fullWidth)
  @Input()
  @InputBoolean()
  fullWidth = false;

  /**
   * The orientation of button group.
   * @default horizontal
   */
  @HostBindingEnumClass(classes.orientation, [
    'horizontal',
    'vertical',
  ])
  @HostBinding('attr.aria-orientation')
  @Input()
  orientation: ButtonGroupOrientation = 'horizontal';

  /**
   * Binding the `attr.role`.
   * @default 'group'
   */
  @HostBinding('attr.role')
  @Input()
  role = 'group';

  /**
   * If the `size` of a button inside group not provided, the `size` of group will override it.
   */
  @Input()
  size: ButtonSize = 'medium';

  /**
   * The spacing level of button gap between each buttons.
   * Will be added on if `attached`=false.
   * @default small:3,others:4
   */
  @Input()
  @InputNumber(NaN)
  spacing: ButtonGroupSpacing;

  /**
   * If the `variant` of a button inside group not provided, the `variant` of group will override it.
   * @default 'text'
   */
  @Input()
  variant: ButtonVariant = 'text';

  private readonly changeHostCssVars = createCssVarsChangeEffect(
    this.elementRef,
    this.renderer,
    () => toButtonGroupCssVars({
      spacing: Number.isNaN(this.spacing) ? undefined : this.spacing,
      size: this.size,
    }),
  );

  ngOnChanges(changes: TypedSimpleChanges<MznButtonGroupComponent>) {
    const {
      size,
      spacing,
    } = changes;

    if (size || spacing) {
      this.changeHostCssVars();
    }
  }

  ngOnInit() {
    this.changeHostCssVars();
  }
}
