// packages/vue/form/form-hint-text.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import {
  formFieldClasses as classes,
  formHintIcons,
} from '@mezzanine-ui/core/form';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { FormHintTextProps } from './form-hint-text.types';

/**
 * 表單欄位的提示文字。
 *
 * 依 `severity` 決定顏色與預設圖示；`hintTextIcon` 可蓋掉預設圖示，
 * `showHintTextIcon` 設為 false 則兩者都不顯示。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznFormHintText } from '@mezzanine-ui/vue/form';
 * <\/script>
 *
 * <template>
 *   <MznFormHintText hint-text="電子郵件格式不正確" severity="error" />
 * </template>
 * ```
 *
 * @see MznFormField 使用這個提示文字的欄位容器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<FormHintTextProps>(), {
  hintText: undefined,
  hintTextIcon: undefined,
  severity: 'info',
  showHintTextIcon: true,
});

const attrs = useAttrs();

const defaultIcon = computed(() =>
  props.severity ? formHintIcons[props.severity] : null,
);

const icon = computed(() => props.hintTextIcon ?? defaultIcon.value);

const hostClasses = computed((): string =>
  clsx(
    classes.hintText,
    props.severity ? classes.hintTextSeverity(props.severity) : undefined,
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const iconClass = classes.hintTextIcon;
</script>

<template>
  <span v-bind="forwardedAttrs" :class="hostClasses">
    <MznIcon
      v-if="showHintTextIcon && icon"
      :class="iconClass"
      :color="severity"
      :icon="icon"
    />{{ hintText }}</span
  >
</template>

// packages/ng/form/form-hint-text.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import {
  formFieldClasses as classes,
  formHintIcons,
} from '@mezzanine-ui/core/form';
import { IconDefinition } from '@mezzanine-ui/icons';
import { SeverityWithInfo } from '@mezzanine-ui/system/severity';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';

/**
 * 表單提示文字元件，顯示於輸入欄位下方。
 *
 * @example
 * ```html
 * <mzn-form-hint-text hintText="請輸入有效的電子郵件" severity="error" />
 * ```
 */
@Component({
  selector: 'mzn-form-hint-text',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon],
  template: `
    <span [class]="hostClasses()">
      @if (showHintTextIcon()) {
        @if (resolvedIcon(); as icon) {
          <i mznIcon [class]="classes.hintTextIcon" [icon]="icon"></i>
        }
      }
      {{ hintText() }}
    </span>
  `,
})
export class MznFormHintText {
  protected readonly classes = classes;

  /** 提示文字。 */
  readonly hintText = input<string>();

  /** 自訂提示文字圖示。 */
  readonly hintTextIcon = input<IconDefinition>();

  /**
   * 嚴重程度，決定預設圖示。
   * @default 'info'
   */
  readonly severity = input<SeverityWithInfo>('info');

  /**
   * 是否顯示提示文字圖示。
   * @default true
   */
  readonly showHintTextIcon = input(true);

  protected readonly resolvedIcon = computed((): IconDefinition | null => {
    const custom = this.hintTextIcon();

    if (custom) return custom;

    const sev = this.severity();

    return sev ? (formHintIcons[sev] ?? null) : null;
  });

  protected readonly hostClasses = computed((): string => {
    const sev = this.severity();

    return clsx(
      classes.hintText,
      sev ? classes.hintTextSeverity(sev) : undefined,
    );
  });
}
