// packages/vue/pagination/pagination-jumper.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { paginationJumperClasses as classes } from '@mezzanine-ui/core/pagination';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import MznButton from '../button/button.vue';
import MznInput from '../input/input.vue';
import type { InputProps } from '../input/input.types';
import MznTypography from '../typography/typography.vue';
import type { PaginationJumperProps } from './pagination-jumper.types';

/**
 * 分頁列右側的跳頁欄：一段提示文字、一個數字輸入框與一顆確認按鈕。
 *
 * 輸入超出總頁數或不是數字時，輸入框會轉成錯誤狀態並清空；按 Enter 與按下按鈕
 * 等價（輸入法組字中不會誤觸）。
 *
 * @example
 * ```vue
 * <MznPaginationJumper
 *   button-text="確認"
 *   hint-text="前往"
 *   :total="100"
 *   @change="go"
 * />
 * ```
 *
 * @see MznPagination showJumper 時渲染這一段
 */
const props = withDefaults(defineProps<PaginationJumperProps>(), {
  buttonText: undefined,
  disabled: undefined,
  hintText: undefined,
  inputPlaceholder: undefined,
  pageSize: 5,
  total: 0,
});

const emit = defineEmits<{
  change: [page: number];
}>();

const value = ref('');
const error = ref(false);

const totalPages = computed((): number =>
  props.total ? Math.ceil(props.total / props.pageSize) : 1,
);

function valueValidator(): boolean {
  const stringToNumber = +value.value;
  const validNumber = !!stringToNumber;

  if (validNumber) {
    return !(stringToNumber > totalPages.value || stringToNumber < 1);
  }

  return false;
}

function handleClick(): void {
  const valid = valueValidator();

  if (valid) {
    error.value = false;
    emit('change', +value.value);
    value.value = '';
  } else {
    error.value = true;
    value.value = '';
  }
}

function handleKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' && !isImeComposing(event)) {
    handleClick();
  }
}

function onInputChange(event: Event): void {
  value.value = (event.target as HTMLInputElement).value;
}

const inputProps = computed((): InputProps['inputProps'] => ({
  onKeydown: handleKeydown,
}));

const hostClass = classes.host;
const inputClass = classes.input;
</script>

<template>
  <div :class="hostClass">
    <MznTypography component="div" ellipsis variant="label-primary">
      {{ hintText }}
    </MznTypography>
    <MznInput
      :class="inputClass"
      :disabled="disabled"
      :error="error"
      :input-props="inputProps"
      :placeholder="inputPlaceholder"
      size="sub"
      :value="value"
      variant="number"
      @change="onInputChange"
    />
    <MznButton :disabled="disabled" size="sub" @click="handleClick">
      {{ buttonText }}
    </MznButton>
  </div>
</template>

// packages/ng/pagination/pagination-jumper.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import { paginationJumperClasses as classes } from '@mezzanine-ui/core/pagination/paginationJumper';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import { MznButton } from '@mezzanine-ui/ng/button';
import { MznInput } from '@mezzanine-ui/ng/input';
import { MznTypography } from '@mezzanine-ui/ng/typography';

/**
 * 頁碼跳轉元件，提供文字輸入框讓使用者直接跳至指定頁碼。
 *
 * 等效 React 的 `PaginationJumper` 子元件。
 *
 * @example
 * ```html
 * import { MznPaginationJumper } from '@mezzanine-ui/ng/pagination';
 *
 * <div mznPaginationJumper
 *   buttonText="確認"
 *   hintText="前往"
 *   inputPlaceholder="1"
 *   [pageSize]="10"
 *   [total]="100"
 *   (pageChanged)="onPageChange($event)"
 * ></div>
 * ```
 */
@Component({
  selector: '[mznPaginationJumper]',
  standalone: true,
  imports: [MznButton, MznInput, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
    '[attr.buttonText]': 'null',
    '[attr.disabled]': 'null',
    '[attr.hintText]': 'null',
    '[attr.inputPlaceholder]': 'null',
    '[attr.pageSize]': 'null',
    '[attr.total]': 'null',
  },
  template: `
    @if (hintText()) {
      <div mznTypography variant="label-primary" [ellipsis]="true">{{
        hintText()
      }}</div>
    }
    <div
      mznInput
      variant="number"
      size="sub"
      [class]="inputClass"
      [disabled]="disabled()"
      [placeholder]="inputPlaceholder() ?? ''"
      [value]="value()"
      (valueChange)="value.set($event)"
      (keydown)="onInputKeydown($event)"
    ></div>
    <button
      mznButton
      type="button"
      size="sub"
      [disabled]="disabled()"
      (click)="onSubmit()"
      >{{ buttonText() }}</button
    >
  `,
})
export class MznPaginationJumper {
  /** 跳轉按鈕文字。 */
  readonly buttonText = input<string | undefined>(undefined);

  /**
   * 是否禁用。
   * @default false
   */
  readonly disabled = input(false);

  /** 跳轉輸入框前的提示文字。 */
  readonly hintText = input<string | undefined>(undefined);

  /** 跳轉輸入框的 placeholder。 */
  readonly inputPlaceholder = input<string | undefined>(undefined);

  /**
   * 每頁筆數，用於計算總頁數。
   * @default 10
   */
  readonly pageSize = input(10);

  /**
   * 總筆數。
   * @default 0
   */
  readonly total = input(0);

  /** 頁碼變更事件。 */
  readonly pageChanged = output<number>();

  protected readonly hostClass = classes.host;
  protected readonly inputClass = classes.input;
  protected readonly value = signal('');

  private readonly totalPages = computed((): number => {
    const t = this.total();

    return t ? Math.ceil(t / this.pageSize()) : 1;
  });

  protected onInputKeydown(event: KeyboardEvent): void {
    if (event.key !== 'Enter' || isImeComposing(event)) return;

    this.onSubmit();
  }

  protected onSubmit(): void {
    const raw = Number(this.value());
    const tp = this.totalPages();

    if (raw >= 1 && raw <= tp && Number.isInteger(raw)) {
      this.pageChanged.emit(raw);
    }

    this.value.set('');
  }
}
