// packages/vue/calendar/calendar-days.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import {
  calendarClasses as classes,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import type { TypographyColor } from '@mezzanine-ui/core/typography';
import clsx from 'clsx';
import MznTypography from '../typography/typography.vue';
import MznCalendarCell from './calendar-cell.vue';
import { useCalendarContext } from './calendar-context';
import MznCalendarDayOfWeek from './calendar-day-of-week.vue';
import type { CalendarDaysProps } from './calendar-days.types';

/**
 * 月曆面板，顯示 `referenceDate` 所在月份。
 *
 * 上下月份補滿的日期會標為 inactive；`renderAnnotations` 可為每一天加上一行註記，
 * 沒有回傳值的日期顯示 `--`。可用來組裝自訂日曆。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarDays } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarDays reference-date="2026-01-01" @click="onChange" />
 * </template>
 * ```
 *
 * @see MznCalendar 依 `mode` 切換各面板
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarDaysProps>(), {
  displayWeekDayLocale: undefined,
  isDateDisabled: undefined,
  isDateInRange: undefined,
  isMonthDisabled: undefined,
  isYearDisabled: undefined,
  renderAnnotations: undefined,
  value: undefined,
});

const emit = defineEmits<{
  click: [date: DateType];
  dateHover: [date: DateType];
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const displayWeekDayLocale = computed(
  (): string => props.displayWeekDayLocale ?? calendar.value.locale,
);

const weekends = computed((): boolean[] =>
  calendar.value.getWeekends(displayWeekDayLocale.value),
);

const daysGrid = computed((): number[][] =>
  calendar.value.getCalendarGrid(
    props.referenceDate,
    displayWeekDayLocale.value,
  ),
);

const weeks = computed(() =>
  daysGrid.value.map((week, index) =>
    week.map((dateNum, dayIndex) => {
      const {
        getDate,
        getMonth,
        getNow,
        isDateIncluded,
        isSameDate,
        setDate,
        setMonth,
        setHour,
        setMinute,
        setSecond,
        setMillisecond,
      } = calendar.value;
      const isPrevMonth = index === 0 && dateNum > 7;
      const isNextMonth = index > 3 && dateNum <= 14;
      const thisMonth = getMonth(props.referenceDate);

      const month = isPrevMonth
        ? thisMonth - 1
        : isNextMonth
          ? thisMonth + 1
          : thisMonth;
      const date = setMillisecond(
        setSecond(
          setMinute(
            setHour(setDate(setMonth(props.referenceDate, month), dateNum), 0),
            0,
          ),
          0,
        ),
        0,
      );
      const disabled =
        props.isYearDisabled?.(date) ||
        props.isMonthDisabled?.(date) ||
        props.isDateDisabled?.(date) ||
        false;
      const inactive = !disabled && (isPrevMonth || isNextMonth);
      const inRange =
        !inactive && props.isDateInRange && props.isDateInRange(date);
      const inRangeStart =
        !inactive && props.value && props.value.length > 0
          ? isSameDate(date, props.value[0])
          : false;
      const inRangeEnd =
        !inactive && props.value && props.value.length > 0
          ? isSameDate(date, props.value[props.value.length - 1])
          : false;
      const active =
        !disabled &&
        !inactive &&
        props.value &&
        isDateIncluded(date, props.value);

      // Accessible date label for screen readers
      const dateObj = new Date(date);
      const dayName = dateObj.toLocaleDateString(displayWeekDayLocale.value, {
        weekday: 'long',
      });
      const monthName = dateObj.toLocaleDateString(displayWeekDayLocale.value, {
        month: 'long',
      });
      const year = dateObj.getFullYear();
      const day = dateObj.getDate();
      const isToday = isSameDate(date, getNow());

      const ariaLabel = [
        `${dayName}, ${monthName} ${day}, ${year}`,
        isToday && 'Today',
        active && 'Selected',
        disabled && 'Not available',
        inactive && 'Outside current month',
      ]
        .filter(Boolean)
        .join(', ');

      const annotation = props.renderAnnotations?.(date);

      return {
        active,
        annotationColor: (active
          ? 'text-fixed-light'
          : (annotation?.color ?? 'text-neutral')) as TypographyColor,
        annotationValue: annotation?.value ?? '--',
        ariaLabel,
        buttonClasses: clsx(classes.button, {
          [classes.buttonInRange]: inRange,
          [classes.buttonActive]: active,
          [classes.buttonDisabled]: disabled,
        }),
        cellDisabled: isPrevMonth || isNextMonth,
        cellKey: `${getMonth(date)}/${getDate(date)}`,
        date,
        dateNum,
        disabled,
        inRangeEnd,
        inRangeStart,
        isToday,
        isWeekend: weekends.value[dayIndex],
      };
    }),
  ),
);

const withAnnotation = computed((): boolean =>
  Boolean(props.renderAnnotations),
);

const hostClasses = computed((): string =>
  clsx(classes.board, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const daysGridClass = classes.daysGrid;
const rowClass = classes.row;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <div :class="daysGridClass">
      <MznCalendarDayOfWeek :display-week-day-locale="displayWeekDayLocale" />
      <div
        v-for="(week, index) in weeks"
        :key="`CALENDAR_DAYS/WEEK_OF/${index}`"
        :class="rowClass"
      >
        <MznCalendarCell
          v-for="cell in week"
          :key="cell.cellKey"
          :active="cell.active"
          :disabled="cell.cellDisabled"
          :is-range-end="cell.inRangeEnd"
          :is-range-start="cell.inRangeStart"
          :is-weekend="cell.isWeekend"
          mode="day"
          :today="cell.isToday"
          :with-annotation="withAnnotation"
        >
          <button
            :aria-current="cell.isToday ? 'date' : undefined"
            :aria-disabled="cell.disabled"
            :aria-label="cell.ariaLabel"
            :aria-pressed="cell.active"
            :class="cell.buttonClasses"
            :disabled="cell.disabled"
            type="button"
            @click="emit('click', cell.date)"
            @mouseenter="emit('dateHover', cell.date)"
            >{{ cell.dateNum
            }}<MznTypography
              v-if="renderAnnotations"
              :color="cell.annotationColor"
              variant="annotation"
              >{{ cell.annotationValue }}</MznTypography
            >
          </button>
        </MznCalendarCell>
      </div>
    </div>
  </div>
</template>

// packages/ng/calendar/calendar-days.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import {
  calendarClasses as classes,
  DateType,
} from '@mezzanine-ui/core/calendar';
import { TypographyColor } from '@mezzanine-ui/core/typography';
import clsx from 'clsx';
import { MZN_CALENDAR_CONFIG } from './calendar-config';
import { MznCalendarCell } from './calendar-cell.component';
import { MznCalendarDayOfWeek } from './calendar-day-of-week.component';
import { MznTypography } from '@mezzanine-ui/ng/typography';

/** Annotation render result for a date cell. */
export interface CalendarDayAnnotation {
  readonly value: string;
  readonly color?: TypographyColor;
}

/**
 * 日曆日期面板元件，顯示一個月的日期格子。
 *
 * @example
 * ```html
 * <mzn-calendar-days
 *   [referenceDate]="refDate"
 *   [value]="selectedDates"
 *   (dateClick)="onSelect($event)"
 * />
 * ```
 */
@Component({
  selector: 'mzn-calendar-days',
  standalone: true,
  imports: [MznCalendarCell, MznCalendarDayOfWeek, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'boardClass',
  },
  template: `
    <div [class]="daysGridClass">
      <mzn-calendar-day-of-week
        [displayWeekDayLocale]="displayWeekDayLocale()"
      />
      @for (week of grid(); track weekIdx; let weekIdx = $index) {
        <div [class]="rowClass">
          @for (day of week; track dayIdx; let dayIdx = $index) {
            <mzn-calendar-cell
              [active]="day.active"
              [disabled]="day.isPrevMonth || day.isNextMonth"
              [isRangeStart]="day.isRangeStart"
              [isRangeEnd]="day.isRangeEnd"
              [isWeekend]="day.isWeekend"
              [today]="day.isToday"
              [withAnnotation]="day.hasAnnotation"
              mode="day"
            >
              <button
                type="button"
                [disabled]="day.disabled"
                [attr.aria-disabled]="day.disabled"
                [attr.aria-pressed]="day.active"
                [attr.aria-current]="day.isToday ? 'date' : null"
                [class]="day.buttonClass"
                (click)="onDayClick(day.date)"
                (mouseenter)="dateHover.emit(day.date)"
                >{{ day.dateNum }}
                @if (day.annotation) {
                  <span
                    mznTypography
                    variant="annotation"
                    [color]="
                      day.active
                        ? 'text-fixed-light'
                        : (day.annotation.color ?? 'text-neutral')
                    "
                    >{{ day.annotation.value ?? '--' }}</span
                  >
                }
              </button>
            </mzn-calendar-cell>
          }
        </div>
      }
    </div>
  `,
})
export class MznCalendarDays {
  private readonly config = inject(MZN_CALENDAR_CONFIG);

  /** 參考日期，用來決定顯示哪個月份。 */
  readonly referenceDate = input.required<DateType>();

  /** 已選取的日期陣列。 */
  readonly value = input<ReadonlyArray<DateType> | undefined>(undefined);

  /** 自訂日期禁用判斷。 */
  readonly isDateDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 自訂日期區間判斷。 */
  readonly isDateInRange = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 自訂年份禁用判斷。 */
  readonly isYearDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 自訂月份禁用判斷。 */
  readonly isMonthDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 顯示星期名稱的語系。 */
  readonly displayWeekDayLocale = input<string | undefined>(undefined);

  /** 日期註解渲染函式。 */
  readonly renderAnnotations = input<
    ((date: DateType) => CalendarDayAnnotation) | undefined
  >(undefined);

  /** 日期點擊事件。 */
  readonly dateClick = output<DateType>();

  /** 日期 hover 事件。 */
  readonly dateHover = output<DateType>();

  protected readonly boardClass = classes.board;
  protected readonly daysGridClass = classes.daysGrid;
  protected readonly rowClass = classes.row;

  protected readonly grid = computed(() => {
    const c = this.config;
    const ref = this.referenceDate();
    const locale = this.displayWeekDayLocale() ?? c.locale;
    const weekends = c.getWeekends(locale);
    const rawGrid = c.getCalendarGrid(ref, locale);
    const val = this.value();
    const disabledFn = this.isDateDisabled();
    const rangeFn = this.isDateInRange();
    const yearDisabledFn = this.isYearDisabled();
    const monthDisabledFn = this.isMonthDisabled();
    const annotationFn = this.renderAnnotations();
    const thisMonth = c.getMonth(ref);
    const now = c.getNow();

    return rawGrid.map((week, weekIdx) =>
      week.map((dateNum, dayIdx) => {
        const isPrevMonth = weekIdx === 0 && dateNum > 7;
        const isNextMonth = weekIdx > 3 && dateNum <= 14;
        const month = isPrevMonth
          ? thisMonth - 1
          : isNextMonth
            ? thisMonth + 1
            : thisMonth;

        const date = c.setMillisecond(
          c.setSecond(
            c.setMinute(
              c.setHour(c.setDate(c.setMonth(ref, month), dateNum), 0),
              0,
            ),
            0,
          ),
          0,
        );

        const disabled =
          yearDisabledFn?.(date) ||
          monthDisabledFn?.(date) ||
          disabledFn?.(date) ||
          false;
        const inactive = !disabled && (isPrevMonth || isNextMonth);
        const inRange = !inactive && rangeFn ? rangeFn(date) : false;
        const active =
          !disabled && !inactive && val
            ? c.isDateIncluded(date, [...val])
            : false;
        const isRangeStart =
          !inactive && val && val.length > 0
            ? c.isSameDate(date, val[0])
            : false;
        const isRangeEnd =
          !inactive && val && val.length > 0
            ? c.isSameDate(date, val[val.length - 1])
            : false;
        const isToday = c.isSameDate(date, now);
        const annotation = annotationFn ? annotationFn(date) : undefined;

        return {
          dateNum,
          date,
          active,
          disabled,
          inactive,
          isPrevMonth,
          isNextMonth,
          isRangeStart,
          isRangeEnd,
          isWeekend: weekends[dayIdx],
          isToday,
          hasAnnotation: !!annotationFn,
          annotation,
          buttonClass: clsx(classes.button, {
            [classes.buttonInRange]: inRange,
            [classes.buttonActive]: active,
            [classes.buttonDisabled]: disabled,
          }),
        };
      }),
    );
  });

  protected onDayClick(date: DateType): void {
    this.dateClick.emit(date);
  }
}
