// packages/vue/calendar/calendar-quick-select.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { CalendarQuickSelectProps } from './calendar-quick-select.types';

/**
 * 日曆左側的快速選取清單。
 *
 * 每個選項是一顆按鈕，`activeId` 相符的那顆會加上勾選圖示與選取樣式。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarQuickSelect } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarQuickSelect
 *     active-id="today"
 *     :options="[{ id: 'today', name: 'Today', onClick: selectToday }]"
 *   />
 * </template>
 * ```
 *
 * @see MznCalendar 透過 `quickSelect` prop 使用這個清單
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarQuickSelectProps>(), {
  activeId: undefined,
});

const attrs = useAttrs();

const hostClasses = computed((): string =>
  clsx(classes.quickSelect, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const buttonClasses = (id: string): string =>
  clsx(
    classes.quickSelectButton,
    id === props.activeId && classes.quickSelectButtonActive,
  );
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <button
      v-for="{ id, name, disabled, onClick } in options"
      :key="id"
      :aria-disabled="disabled"
      :class="buttonClasses(id)"
      :disabled="disabled"
      type="button"
      @click="onClick"
    >
      <span>{{ name }}</span>
      <MznIcon v-if="id === activeId" :icon="CheckedIcon" :size="16" />
    </button>
  </div>
</template>

// packages/ng/calendar/calendar-quick-select.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';

export interface CalendarQuickSelectOption {
  /** 選項唯一識別碼。 */
  readonly id: string;
  /** 顯示文字（對應 React 的 `name`）。 */
  readonly name: string;
  /** 是否禁用。 */
  readonly disabled?: boolean;
  /** 點擊事件。 */
  readonly onClick: () => void;
}

/**
 * 日曆快速選取面板元件，顯示一組快速選取按鈕。
 *
 * @example
 * ```html
 * <mzn-calendar-quick-select
 *   [activeId]="activeQuickId"
 *   [options]="quickOptions"
 * />
 * ```
 */
@Component({
  selector: 'mzn-calendar-quick-select',
  standalone: true,
  imports: [MznIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
  },
  template: `
    @for (option of options(); track option.id) {
      <button
        type="button"
        [disabled]="option.disabled ?? false"
        [attr.aria-disabled]="option.disabled ?? false"
        [class]="getButtonClass(option.id)"
        (click)="option.onClick()"
      >
        <span>{{ option.name }}</span>
        @if (option.id === activeId()) {
          <i mznIcon [icon]="checkedIcon" [size]="16"></i>
        }
      </button>
    }
  `,
})
export class MznCalendarQuickSelect {
  /** 目前作用中選項的 id。 */
  readonly activeId = input<string | undefined>(undefined);

  /** 快速選取選項陣列。 */
  readonly options = input<ReadonlyArray<CalendarQuickSelectOption>>([]);

  protected readonly checkedIcon = CheckedIcon;
  protected readonly hostClass = classes.quickSelect;

  protected getButtonClass(id: string): string {
    return clsx(
      classes.quickSelectButton,
      id === this.activeId() && classes.quickSelectButtonActive,
    );
  }
}
