// packages/vue/date-time-range-picker/date-time-range-picker.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { DateType } from '@mezzanine-ui/core/calendar';
import { dateTimeRangePickerClasses as classes } from '@mezzanine-ui/core/date-time-range-picker';
import {
  LongTailArrowDownIcon,
  LongTailArrowRightIcon,
} from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznDateTimePicker from '../date-time-picker/date-time-picker.vue';
import type { DateTimePickerFocusedInput } from '../date-time-picker/date-time-picker.types';
import MznIcon from '../icon/icon.vue';
import type {
  DateTimeRangePickerProps,
  DateTimeRangePickerValue,
} from './date-time-range-picker.types';

/**
 * 日期時間區間選擇器：兩個 MznDateTimePicker 中間夾一個箭頭。
 *
 * `direction` 決定橫排或直排，箭頭跟著換向；其餘設定兩邊共用，
 * 任一端變動都會送出完整的 `[from, to]`。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDateTimeRangePicker } from '@mezzanine-ui/vue/date-time-range-picker';
 * <\/script>
 *
 * <template>
 *   <MznDateTimeRangePicker :value="value" @change="onChange" />
 *   <MznDateTimeRangePicker direction="column" :value="value" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznDateTimePicker 單一日期時間選擇器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DateTimeRangePickerProps>(), {
  calendarProps: undefined,
  clearable: undefined,
  direction: 'row',
  disableOnDoubleNext: undefined,
  disableOnDoublePrev: undefined,
  disableOnNext: undefined,
  disableOnPrev: undefined,
  disabled: undefined,
  disabledMonthSwitch: undefined,
  disabledYearSwitch: undefined,
  displayMonthLocale: undefined,
  error: undefined,
  errorMessagesLeft: undefined,
  errorMessagesRight: undefined,
  fadeProps: undefined,
  formatDate: undefined,
  formatTime: undefined,
  fullWidth: undefined,
  hideHour: undefined,
  hideMinute: undefined,
  hideSecond: undefined,
  hourStep: undefined,
  hoverValueLeft: undefined,
  inputLeftProps: undefined,
  inputRightProps: undefined,
  isDateDisabled: undefined,
  isHalfYearDisabled: undefined,
  isMonthDisabled: undefined,
  isQuarterDisabled: undefined,
  isWeekDisabled: undefined,
  isYearDisabled: undefined,
  minuteStep: undefined,
  mode: undefined,
  placeholderLeft: undefined,
  placeholderRight: undefined,
  popperProps: undefined,
  popperPropsTime: undefined,
  readOnly: undefined,
  referenceDate: undefined,
  required: undefined,
  secondStep: undefined,
  validateLeft: undefined,
  validateRight: undefined,
  value: undefined,
});

const emit = defineEmits<{
  cancel: [];
  change: [value: DateTimeRangePickerValue];
  clear: [event: MouseEvent];
  confirm: [];
  hover: [date: DateType];
  leave: [];
  panelToggle: [open: boolean, focusedInput: DateTimePickerFocusedInput];
}>();

const attrs = useAttrs();

const fromValue = computed((): DateType | undefined => props.value?.[0]);
const toValue = computed((): DateType | undefined => props.value?.[1]);

// Handler for "from" DateTimePicker change
function handleFromChange(newFrom?: DateType): void {
  emit('change', [newFrom, toValue.value]);
}

// Handler for "to" DateTimePicker change
function handleToChange(newTo?: DateType): void {
  emit('change', [fromValue.value, newTo]);
}

/** Everything both pickers share, exactly as React spreads it. */
const sharedProps = computed(() => ({
  calendarProps: props.calendarProps,
  clearable: props.clearable,
  disabled: props.disabled,
  disabledMonthSwitch: props.disabledMonthSwitch,
  disabledYearSwitch: props.disabledYearSwitch,
  disableOnDoubleNext: props.disableOnDoubleNext,
  disableOnDoublePrev: props.disableOnDoublePrev,
  disableOnNext: props.disableOnNext,
  disableOnPrev: props.disableOnPrev,
  displayMonthLocale: props.displayMonthLocale,
  error: props.error,
  fadeProps: props.fadeProps,
  formatDate: props.formatDate,
  formatTime: props.formatTime,
  fullWidth: props.fullWidth,
  hideHour: props.hideHour,
  hideMinute: props.hideMinute,
  hideSecond: props.hideSecond,
  hourStep: props.hourStep,
  isDateDisabled: props.isDateDisabled,
  isHalfYearDisabled: props.isHalfYearDisabled,
  isMonthDisabled: props.isMonthDisabled,
  isQuarterDisabled: props.isQuarterDisabled,
  isWeekDisabled: props.isWeekDisabled,
  isYearDisabled: props.isYearDisabled,
  minuteStep: props.minuteStep,
  mode: props.mode,
  onCancel: () => emit('cancel'),
  onClear: (event: MouseEvent) => emit('clear', event),
  onConfirm: () => emit('confirm'),
  onHover: (date: DateType) => emit('hover', date),
  onLeave: () => emit('leave'),
  onPanelToggle: (open: boolean, focusedInput: DateTimePickerFocusedInput) =>
    emit('panelToggle', open, focusedInput),
  placeholderLeft: props.placeholderLeft,
  placeholderRight: props.placeholderRight,
  popperProps: props.popperProps,
  popperPropsTime: props.popperPropsTime,
  readOnly: props.readOnly,
  referenceDate: props.referenceDate,
  required: props.required,
  secondStep: props.secondStep,
  size: props.size,
}));

const arrowIcon = computed(() =>
  props.direction === 'column' ? LongTailArrowDownIcon : LongTailArrowRightIcon,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    props.direction === 'column' ? classes.column : classes.row,
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const arrowClass = classes.arrow;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <MznDateTimePicker
      v-bind="sharedProps"
      :value="fromValue"
      @change="handleFromChange"
    />
    <MznIcon :class="arrowClass" :icon="arrowIcon" />
    <MznDateTimePicker
      v-bind="sharedProps"
      :value="toValue"
      @change="handleToChange"
    />
  </div>
</template>

// packages/ng/date-time-range-picker/date-time-range-picker.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  input,
  output,
  signal,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DateType } from '@mezzanine-ui/core/calendar';
import { dateTimeRangePickerClasses as classes } from '@mezzanine-ui/core/date-time-range-picker';
import { RangePickerValue } from '@mezzanine-ui/core/picker';
import { TextFieldSize } from '@mezzanine-ui/core/text-field';
import {
  LongTailArrowDownIcon,
  LongTailArrowRightIcon,
} from '@mezzanine-ui/icons';
import { MznDateTimePicker } from '@mezzanine-ui/ng/date-time-picker';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { provideValueAccessor } from '@mezzanine-ui/ng/utils';
import clsx from 'clsx';

/**
 * 日期時間範圍選擇器元件，組合兩個 `MznDateTimePicker` 以選取起止時間。
 *
 * 鏡像 React `DateTimeRangePicker` 的組合模式：
 * 兩個獨立的 DateTimePicker + 方向箭頭 icon。
 *
 * @example
 * ```html
 * import { MznDateTimeRangePicker } from '@mezzanine-ui/ng/date-time-range-picker';
 *
 * <div mznDateTimeRangePicker
 *   [(ngModel)]="dateTimeRange"
 *   placeholderLeft="Select date"
 *   placeholderRight="Select time"
 * ></div>
 * ```
 *
 * @see {@link MznDateTimePicker} 日期時間選擇器元件
 */
@Component({
  selector: '[mznDateTimeRangePicker]',
  host: {
    '[class]': 'hostClasses()',
    '[attr.clearable]': 'null',
    '[attr.direction]': 'null',
    '[attr.disabled]': 'null',
    '[attr.error]': 'null',
    '[attr.formatDate]': 'null',
    '[attr.formatTime]': 'null',
    '[attr.fullWidth]': 'null',
    '[attr.hideHour]': 'null',
    '[attr.hideMinute]': 'null',
    '[attr.hideSecond]': 'null',
    '[attr.hourStep]': 'null',
    '[attr.isDateDisabled]': 'null',
    '[attr.minuteStep]': 'null',
    '[attr.placeholderLeft]': 'null',
    '[attr.placeholderRight]': 'null',
    '[attr.readOnly]': 'null',
    '[attr.required]': 'null',
    '[attr.secondStep]': 'null',
    '[attr.size]': 'null',
    '[attr.value]': 'null',
  },
  standalone: true,
  imports: [MznDateTimePicker, MznIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(MznDateTimeRangePicker)],
  template: `
    <div
      mznDateTimePicker
      [clearable]="clearable()"
      [disabled]="disabled()"
      [error]="error()"
      [formatDate]="formatDate()"
      [formatTime]="formatTime()"
      [fullWidth]="fullWidth()"
      [hideHour]="hideHour()"
      [hideMinute]="hideMinute()"
      [hideSecond]="hideSecond()"
      [hourStep]="hourStep()"
      [isDateDisabled]="isDateDisabled()"
      [minuteStep]="minuteStep()"
      [placeholderLeft]="placeholderLeft()"
      [placeholderRight]="placeholderRight()"
      [readOnly]="readOnly()"
      [required]="required()"
      [secondStep]="secondStep()"
      [size]="size()"
      [value]="fromValue()"
      (change)="onFromChange($event)"
    ></div>
    <i mznIcon [icon]="arrowIcon()" [class]="arrowClass"></i>
    <div
      mznDateTimePicker
      [clearable]="clearable()"
      [disabled]="disabled()"
      [error]="error()"
      [formatDate]="formatDate()"
      [formatTime]="formatTime()"
      [fullWidth]="fullWidth()"
      [hideHour]="hideHour()"
      [hideMinute]="hideMinute()"
      [hideSecond]="hideSecond()"
      [hourStep]="hourStep()"
      [isDateDisabled]="isDateDisabled()"
      [minuteStep]="minuteStep()"
      [placeholderLeft]="placeholderLeft()"
      [placeholderRight]="placeholderRight()"
      [readOnly]="readOnly()"
      [required]="required()"
      [secondStep]="secondStep()"
      [size]="size()"
      [value]="toValue()"
      (change)="onToChange($event)"
    ></div>
  `,
})
export class MznDateTimeRangePicker implements ControlValueAccessor {
  // ─── Inputs (alphabetical, mirroring React DateTimeRangePickerProps) ───

  readonly clearable = input(true);

  /**
   * 兩個日期時間選擇器的排列方向。
   * @default 'row'
   */
  readonly direction = input<'row' | 'column'>('row');

  readonly disabled = input(false);
  readonly error = input(false);

  /** 日期顯示格式。 */
  readonly formatDate = input<string | undefined>(undefined);

  /** 時間顯示格式。 */
  readonly formatTime = input<string | undefined>(undefined);

  readonly fullWidth = input(false);

  /** 是否隱藏小時。 */
  readonly hideHour = input(false);

  /** 是否隱藏分鐘。 */
  readonly hideMinute = input(false);

  readonly hideSecond = input(false);

  /** 小時步長。 */
  readonly hourStep = input(1);

  readonly isDateDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 分鐘步長。 */
  readonly minuteStep = input(1);

  /** 日期輸入的佔位文字。 */
  readonly placeholderLeft = input<string | undefined>(undefined);

  /** 時間輸入的佔位文字。 */
  readonly placeholderRight = input<string | undefined>(undefined);

  readonly readOnly = input(false);

  /**
   * 是否為必填欄位。
   * @default false
   */
  readonly required = input(false);

  /** 秒鐘步長。 */
  readonly secondStep = input(1);

  /**
   * 觸發器尺寸。
   * @default 'main'
   */
  readonly size = input<TextFieldSize>('main');

  readonly value = input<RangePickerValue | undefined>(undefined);

  // ─── Outputs ──────────────────────────────────────────────────────────

  readonly rangeChanged = output<RangePickerValue>();

  // ─── Internal state ───────────────────────────────────────────────────

  protected readonly arrowClass = classes.arrow;

  protected readonly arrowIcon = computed(() =>
    this.direction() === 'column'
      ? LongTailArrowDownIcon
      : LongTailArrowRightIcon,
  );

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.host,
      this.direction() === 'column' ? classes.column : classes.row,
    ),
  );

  private readonly internalValue = signal<RangePickerValue>([
    undefined,
    undefined,
  ] as unknown as RangePickerValue);

  protected readonly fromValue = computed(
    (): DateType | undefined => this.internalValue()?.[0],
  );

  protected readonly toValue = computed(
    (): DateType | undefined => this.internalValue()?.[1],
  );

  private onChange: ((value: RangePickerValue) => void) | null = null;
  private onTouched: (() => void) | null = null;

  constructor() {
    effect(() => {
      const v = this.value();
      if (v) this.internalValue.set(v);
    });
  }

  // ─── ControlValueAccessor ─────────────────────────────────────────────

  writeValue(value: RangePickerValue | undefined): void {
    this.internalValue.set(
      value ?? ([undefined, undefined] as unknown as RangePickerValue),
    );
  }

  registerOnChange(fn: (value: RangePickerValue) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  // ─── Handlers ─────────────────────────────────────────────────────────

  protected onFromChange(newFrom: DateType | undefined): void {
    const range: RangePickerValue = [
      newFrom,
      this.toValue(),
    ] as RangePickerValue;

    this.internalValue.set(range);
    this.onChange?.(range);
    this.rangeChanged.emit(range);
    this.onTouched?.();
  }

  protected onToChange(newTo: DateType | undefined): void {
    const range: RangePickerValue = [
      this.fromValue(),
      newTo,
    ] as RangePickerValue;

    this.internalValue.set(range);
    this.onChange?.(range);
    this.rangeChanged.emit(range);
    this.onTouched?.();
  }
}
