// packages/react/src/Card/FourThumbnailCardSkeleton.tsx
'use client';

import { forwardRef } from 'react';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Skeleton from '../Skeleton';

export interface FourThumbnailCardSkeletonProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'> {
  /**
   * Width of the card skeleton container.
   * @default 360
   */
  thumbnailWidth?: number | string;
  /**
   * Aspect ratio of each thumbnail skeleton.
   * For four-thumbnail layout, force to '4/3' to maintain the grid layout.
   * @default '4/3'
   */
  thumbnailAspectRatio?: string;
}

/**
 * Skeleton placeholder for FourThumbnailCard component.
 * Renders a skeleton that mimics the FourThumbnailCard layout.
 */
const FourThumbnailCardSkeleton = forwardRef<
  HTMLDivElement,
  FourThumbnailCardSkeletonProps
>(function FourThumbnailCardSkeleton(props, ref) {
  const {
    className,
    // thumbnailAspectRatio = '4/3',
    thumbnailWidth = 200,
    ...rest
  } = props;

  return (
    <div {...rest} ref={ref} className={cx(classes.thumbnail, className)}>
      <div className={classes.fourThumbnail}>
        {Array.from({ length: 4 }, (_, index) => (
          <Skeleton
            key={index}
            className={classes.fourThumbnailThumbnail}
            width={thumbnailWidth}
            style={{ aspectRatio: '4/3' }}
          />
        ))}
      </div>
      <div className={classes.thumbnailInfo}>
        <div className={classes.thumbnailInfoMain}>
          <div
            className={classes.thumbnailInfoContent}
            style={{ width: '100%' }}
          >
            <Skeleton height={20} width="100%" />
            <Skeleton height={16} width="100%" />
          </div>
        </div>
      </div>
    </div>
  );
});

FourThumbnailCardSkeleton.displayName = 'FourThumbnailCardSkeleton';

export default FourThumbnailCardSkeleton;

// packages/ng/four-thumbnail-card/four-thumbnail-card-skeleton.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import { MznSkeleton } from '@mezzanine-ui/ng/skeleton';

/**
 * Skeleton placeholder for FourThumbnailCard component.
 * Renders a skeleton that mimics the FourThumbnailCard layout with a 2x2 thumbnail grid.
 *
 * @example
 * ```html
 * import { MznFourThumbnailCardSkeleton } from '@mezzanine-ui/ng/four-thumbnail-card';
 *
 * <mzn-four-thumbnail-card-skeleton />
 * <mzn-four-thumbnail-card-skeleton [thumbnailWidth]="160" />
 * ```
 *
 * @see MznFourThumbnailCard
 */
@Component({
  selector: 'mzn-four-thumbnail-card-skeleton',
  standalone: true,
  imports: [MznSkeleton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
  },
  template: `
    <div [class]="thumbnailGridClass">
      @for (item of thumbnailSlots; track $index) {
        <div
          mznSkeleton
          [class]="thumbnailItemClass"
          [width]="thumbnailWidth()"
          [style.aspect-ratio]="'4/3'"
        ></div>
      }
    </div>
    <div [class]="infoClass">
      <div [class]="infoMainClass">
        <div [class]="infoContentClass" style="width: 100%;">
          <div mznSkeleton [height]="20" width="100%"></div>
          <div mznSkeleton [height]="16" width="100%"></div>
        </div>
      </div>
    </div>
  `,
})
export class MznFourThumbnailCardSkeleton {
  protected readonly hostClass = classes.thumbnail;
  protected readonly thumbnailGridClass = classes.fourThumbnail;
  protected readonly thumbnailItemClass = classes.fourThumbnailThumbnail;
  protected readonly infoClass = classes.thumbnailInfo;
  protected readonly infoMainClass = classes.thumbnailInfoMain;
  protected readonly infoContentClass = classes.thumbnailInfoContent;

  protected readonly thumbnailSlots: readonly null[] = Array.from({
    length: 4,
  });

  /**
   * Width of each thumbnail skeleton in the 2x2 grid.
   * Accepts a number (pixels) or a CSS string value.
   * @default 200
   */
  readonly thumbnailWidth = input<number | string>(200);
}
