// packages/react/src/Anchor/AnchorItem.tsx
'use client';

import { useEffect, useState } from 'react';
import { anchorClasses as classes } from '@mezzanine-ui/core/anchor';
import { cx } from '../utils/cx';
import Typography from '../Typography';

export interface AnchorItemData {
  autoScrollTo?: boolean;
  children?: AnchorItemData[];
  disabled?: boolean;
  href: string;
  id: string;
  name: string;
  onClick?: VoidFunction;
  title?: string;
}

export interface AnchorItemProps {
  autoScrollTo?: boolean;
  className?: string;
  disabled?: boolean;
  href: string;
  id: string;
  level?: number;
  name: string;
  onClick?: VoidFunction;
  parentAutoScrollTo?: boolean;
  parentDisabled?: boolean;
  subAnchors?: AnchorItemData[];
  title?: string;
}

const MAX_CHILDREN_PER_LEVEL = 3;

/**
 * Custom hook to track window.location.hash changes
 */
function useHash() {
  const [hash, setHash] = useState(() =>
    typeof window !== 'undefined' ? window.location.hash : '',
  );

  useEffect(() => {
    const handleHashChange = () => {
      setHash(window.location.hash);
    };

    window.addEventListener('hashchange', handleHashChange);

    return () => {
      window.removeEventListener('hashchange', handleHashChange);
    };
  }, []);

  return hash;
}

/**
 * Individual anchor link with hash tracking and smooth scrolling.
 * Tracks active state from URL hash and inherits disabled state from parent.
 */
function AnchorItem({
  autoScrollTo,
  className,
  disabled,
  href,
  id: _id,
  level = 1,
  name,
  onClick,
  parentAutoScrollTo = false,
  parentDisabled = false,
  subAnchors,
  title,
}: AnchorItemProps) {
  const renderableChildren =
    subAnchors && subAnchors.length > 0 && level < MAX_CHILDREN_PER_LEVEL
      ? subAnchors.slice(0, MAX_CHILDREN_PER_LEVEL)
      : undefined;

  const currentHash = useHash();
  const hashIndex = href.indexOf('#');
  const itemHash = hashIndex !== -1 ? href.slice(hashIndex) : '';
  const isActive = itemHash && currentHash === itemHash;
  const isAutoScrollTo = parentAutoScrollTo || autoScrollTo;
  const isDisabled = parentDisabled || disabled;

  const handleClick = (event: React.MouseEvent<HTMLAnchorElement>) => {
    if (isDisabled) {
      event.preventDefault();
      return;
    }

    // If href contains a hash, update it manually to ensure hashchange event fires
    if (itemHash && typeof window !== 'undefined') {
      // Update the hash in the URL
      if (window.location.hash !== itemHash) {
        window.history.pushState(null, '', itemHash);
        window.dispatchEvent(new HashChangeEvent('hashchange'));
      }

      // Scroll to the target element if it exists and autoScrollTo is enabled
      if (isAutoScrollTo) {
        const targetElement = document.querySelector(itemHash);
        if (targetElement) {
          targetElement.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      }
    }

    onClick?.();
  };

  return (
    <>
      <a
        aria-disabled={isDisabled}
        className={cx(
          classes.anchorItem,
          isActive && classes.anchorItemActive,
          isDisabled && classes.anchorItemDisabled,
          className,
        )}
        href={href}
        onClick={handleClick}
        tabIndex={isDisabled ? -1 : undefined}
        title={title}
      >
        <Typography color="inherit" variant="label-primary">
          {name}
        </Typography>
      </a>
      {renderableChildren && (
        <div className={classes.nested}>
          {renderableChildren.map((child: AnchorItemData) => (
            <AnchorItem
              autoScrollTo={child.autoScrollTo}
              className={cx(
                level === 1 && classes.nestedLevel1,
                level === 2 && classes.nestedLevel2,
              )}
              disabled={child.disabled}
              href={child.href}
              id={child.id}
              key={child.id}
              level={level + 1}
              name={child.name}
              onClick={child.onClick}
              parentAutoScrollTo={isAutoScrollTo}
              parentDisabled={isDisabled}
              subAnchors={child.children}
              title={child.title}
            />
          ))}
        </div>
      )}
    </>
  );
}

export default AnchorItem;

// packages/vue/anchor/anchor-item.vue
<script setup lang="ts">
import { computed } from 'vue';
import { anchorClasses as classes } from '@mezzanine-ui/core/anchor';
import clsx from 'clsx';
import MznTypography from '../typography/typography.vue';
import { useHash } from './use-hash';
import type { AnchorItemProps } from './anchor-item.types';

/**
 * Individual anchor link with hash tracking and smooth scrolling.
 * Tracks active state from the URL hash and inherits disabled state from its
 * parent. Internal to the anchor package.
 */
const props = withDefaults(defineProps<AnchorItemProps>(), {
  level: 1,
  parentAutoScrollTo: false,
  parentDisabled: false,
});

/**
 * Two roots — the link and its nested group — so nothing is forwarded
 * implicitly; `$attrs` is bound to the link, which is where React puts
 * `className`.
 */
defineOptions({ inheritAttrs: false });

const MAX_CHILDREN_PER_LEVEL = 3;

const currentHash = useHash();

const itemHash = computed((): string => {
  const index = props.href.indexOf('#');

  return index !== -1 ? props.href.slice(index) : '';
});

const isActive = computed(
  () => !!itemHash.value && currentHash.value === itemHash.value,
);

const isAutoScrollTo = computed(
  (): boolean | undefined => props.parentAutoScrollTo || props.autoScrollTo,
);

const isDisabled = computed(
  (): boolean | undefined => props.parentDisabled || props.disabled,
);

const renderableChildren = computed((): AnchorItemProps['subAnchors'] =>
  props.subAnchors &&
  props.subAnchors.length > 0 &&
  props.level < MAX_CHILDREN_PER_LEVEL
    ? props.subAnchors.slice(0, MAX_CHILDREN_PER_LEVEL)
    : undefined,
);

const itemClasses = computed((): string =>
  clsx(
    classes.anchorItem,
    isActive.value && classes.anchorItemActive,
    isDisabled.value && classes.anchorItemDisabled,
  ),
);

const nestedChildClasses = computed((): string =>
  clsx(
    props.level === 1 && classes.nestedLevel1,
    props.level === 2 && classes.nestedLevel2,
  ),
);

function handleClick(event: MouseEvent): void {
  if (isDisabled.value) {
    event.preventDefault();

    return;
  }

  // A hash in the href is navigated manually so the hashchange event always
  // fires, which is what drives the active state.
  if (itemHash.value && typeof window !== 'undefined') {
    event.preventDefault();

    if (window.location.hash !== itemHash.value) {
      window.history.pushState(null, '', itemHash.value);
      window.dispatchEvent(new HashChangeEvent('hashchange'));
    }

    if (isAutoScrollTo.value) {
      const target = document.querySelector(itemHash.value);

      if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }

  props.onClick?.();
}

const nestedClass = classes.nested;
</script>

<template>
  <a
    v-bind="$attrs"
    :aria-disabled="isDisabled"
    :class="itemClasses"
    :href="href"
    :tabindex="isDisabled ? -1 : undefined"
    :title="title"
    @click="handleClick"
  >
    <MznTypography color="inherit" variant="label-primary">
      {{ name }}
    </MznTypography>
  </a>

  <div v-if="renderableChildren" :class="nestedClass">
    <AnchorItem
      v-for="child in renderableChildren"
      :key="child.id"
      :auto-scroll-to="child.autoScrollTo"
      :class="nestedChildClasses"
      :disabled="child.disabled"
      :href="child.href"
      :id="child.id"
      :level="level + 1"
      :name="child.name"
      :on-click="child.onClick"
      :parent-auto-scroll-to="isAutoScrollTo"
      :parent-disabled="isDisabled"
      :sub-anchors="child.children"
      :title="child.title"
    />
  </div>
</template>
