// packages/ng/checkbox/checkbox.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import {
  checkboxClasses as classes,
  CheckboxMode,
  CheckboxSeverity,
  CheckboxSize,
} from '@mezzanine-ui/core/checkbox';
import { TypographyColor } from '@mezzanine-ui/core/typography';
import { inputCheckClasses } from '@mezzanine-ui/core/_internal/input-check';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznTextField } from '@mezzanine-ui/ng/text-field';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import {
  MZN_CHECKBOX_GROUP,
  CheckboxGroupContextValue,
} from './checkbox-group-context';
import { provideValueAccessor } from '@mezzanine-ui/ng/utils';

/**
 * 核取方塊元件。
 *
 * 支援 `default`（標準）與 `chip`（標籤）兩種顯示模式，
 * 可獨立使用或搭配 `MznCheckboxGroup` 使用。
 * 實作 `ControlValueAccessor` 以支援 Angular Forms。
 *
 * @example
 * ```html
 * import { MznCheckbox } from '@mezzanine-ui/ng/checkbox';
 *
 * <div mznCheckbox [(ngModel)]="checked">同意條款</div>
 * <div mznCheckbox mode="chip" size="minor">標籤選項</div>
 * ```
 */
@Component({
  selector: '[mznCheckbox]',
  standalone: true,
  imports: [MznIcon, MznTextField, MznTypography],
  providers: [provideValueAccessor(MznCheckbox)],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.checked]': 'null',
    '[attr.disabled]': 'null',
    '[attr.error]': 'null',
    '[attr.hint]': 'null',
    '[attr.indeterminate]': 'null',
    '[attr.label]': 'null',
    '[attr.description]': 'null',
    '[attr.mode]': 'null',
    '[attr.name]': 'null',
    '[attr.severity]': 'null',
    '[attr.size]': 'null',
    '[attr.value]': 'null',
    '[attr.withEditInput]': 'null',
    '[attr.editableInputPlaceholder]': 'null',
    '[attr.editableInputValue]': 'null',
  },
  template: `
    <label [class]="labelContainerClass">
      <div [class]="inputContainerClass">
        <div [class]="inputContentClass">
          <input
            type="checkbox"
            [class]="inputClass"
            [checked]="resolvedChecked()"
            [disabled]="resolvedDisabled()"
            [indeterminate]="indeterminate()"
            [name]="resolvedName()"
            [value]="value()"
            (change)="onInputChange($event)"
            (focus)="onTouched()"
          />
          @if (resolvedMode() === 'chip') {
            @if (resolvedChecked()) {
              <i
                mznIcon
                [icon]="checkIcon"
                [class]="chipIconClass"
                color="brand"
                [size]="16"
              ></i>
            }
          } @else {
            @if (indeterminate()) {
              <span [class]="indeterminateLineClass"></span>
            } @else if (resolvedChecked()) {
              <i
                mznIcon
                [icon]="checkIcon"
                [class]="iconClass"
                color="fixed-light"
                [size]="9"
              ></i>
            }
          }
        </div>
      </div>
      <span [class]="textContainerClass">
        <span
          mznTypography
          variant="label-primary"
          [color]="labelColor()"
          [class]="labelClass"
        >
          @if (label()) {
            {{ label() }}
          }
          <ng-content />
        </span>
        @if (
          description() &&
          resolvedMode() !== 'chip' &&
          !shouldShowEditableInput()
        ) {
          <span
            mznTypography
            variant="caption"
            color="text-neutral"
            [class]="descriptionClass"
            >{{ description() }}</span
          >
        }
        @if (hint()) {
          <span
            mznTypography
            variant="caption"
            color="text-neutral"
            [class]="hintClass"
            >{{ hint() }}</span
          >
        }
      </span>
    </label>
    @if (
      shouldShowEditableInput() && resolvedMode() !== 'chip' && !indeterminate()
    ) {
      <label [class]="editableInputContainerClass">
        <div
          mznTextField
          #editableInputEl
          size="main"
          (mousedown)="onEditableInputMouseDown($event)"
        >
          <input
            type="text"
            [disabled]="resolvedDisabled()"
            [placeholder]="editableInputPlaceholder()"
            [name]="editableInputName()"
            [value]="editableInputValue()"
            (input)="onEditableInput($event)"
          />
        </div>
      </label>
    }
  `,
})
export class MznCheckbox implements ControlValueAccessor {
  private readonly group = inject<CheckboxGroupContextValue>(
    MZN_CHECKBOX_GROUP,
    { optional: true },
  );

  private readonly hostElRef = inject(ElementRef<HTMLElement>);

  /** 是否勾選（獨立使用時）。 */
  readonly checked = input<boolean>();

  /** 是否禁用。 */
  readonly disabled = input(false);

  /** 是否為錯誤狀態。 */
  readonly error = input(false);

  /** 提示文字。 */
  readonly hint = input<string>();

  /** 是否為不定狀態。 */
  readonly indeterminate = input(false);

  /** 標籤文字（顯示於 checkbox 旁）。等同於直接投影文字內容，但方便程式化設定。 */
  readonly label = input<string | undefined>(undefined);

  /** 標籤下方的說明文字（chip 模式下不顯示）。 */
  readonly description = input<string | undefined>(undefined);

  /** 顯示模式。 */
  readonly mode = input<CheckboxMode>('default');

  /** input name。 */
  readonly name = input<string>();

  /** 嚴重性。 */
  readonly severity = input<CheckboxSeverity>();

  /** 尺寸。 */
  readonly size = input<CheckboxSize>('main');

  /** Checkbox 值（用於群組）。 */
  readonly value = input<string>('');

  /**
   * 是否在勾選時顯示附加輸入框。
   * @default false
   */
  readonly withEditInput = input(false);

  /**
   * 附加輸入框的 placeholder。
   * @default 'Please enter...'
   */
  readonly editableInputPlaceholder = input('Please enter...');

  /**
   * 附加輸入框的目前值（受控模式）。
   * @default ''
   */
  readonly editableInputValue = input('');

  /** 附加輸入框值變更事件。 */
  readonly editableInputChange = output<string>();

  /**
   * 附加輸入框的 name。預設由 checkbox name 或 id 衍生。
   */
  readonly editableInputName = computed(
    (): string => `${this.resolvedName() || 'checkbox'}_input`,
  );

  private readonly editableInputElRef =
    viewChild<ElementRef<HTMLElement>>('editableInputEl');

  private readonly internalChecked = signal(false);

  readonly resolvedChecked = computed((): boolean => {
    if (this.group) {
      return this.group.value().includes(this.value());
    }

    return this.checked() ?? this.internalChecked();
  });

  readonly resolvedDisabled = computed(
    (): boolean => this.group?.disabled() || this.disabled(),
  );

  readonly resolvedMode = computed((): CheckboxMode => this.mode());

  readonly resolvedName = computed(
    (): string => this.group?.name() ?? this.name() ?? '',
  );

  readonly resolvedSize = computed(
    (): CheckboxSize => this.group?.size() ?? this.size(),
  );

  protected readonly hostClasses = computed((): string => {
    const mode = this.resolvedMode();

    if (mode === 'chip') {
      return clsx(
        classes.host,
        classes.mode('chip'),
        classes.size(this.resolvedSize()),
        {
          [classes.checked]: this.resolvedChecked(),
          [classes.disabled]: this.resolvedDisabled(),
        },
        this.severity() ? classes.severity(this.severity()!) : undefined,
      );
    }

    // Default mode: match React's root class composition so that
    // `.mzn-checkbox__input { appearance: none; border: 1px solid; ... }`
    // from _checkbox-styles.scss applies to the native input. Previously
    // this emitted `.mzn-input-check` which activated the shared
    // `.mzn-input-check input { opacity: 0 }` rule and hid the visible
    // box entirely. React emits `mzn-checkbox mzn-checkbox--<severity>
    // mzn-checkbox--<size>` with optional state modifiers.
    return clsx(
      classes.host,
      classes.size(this.resolvedSize()),
      classes.severity(this.severity() ?? 'info'),
      {
        [classes.checked]: this.resolvedChecked(),
        [classes.indeterminate]: this.indeterminate(),
        [classes.disabled]: this.resolvedDisabled(),
      },
    );
  });

  protected readonly labelColor = computed(
    (): TypographyColor =>
      this.resolvedDisabled() ? 'text-neutral-light' : 'text-neutral-solid',
  );

  protected readonly labelContainerClass = classes.labelContainer;
  protected readonly inputContainerClass = classes.inputContainer;
  protected readonly inputContentClass = classes.inputContent;
  protected readonly textContainerClass = classes.textContainer;
  protected readonly labelClass = classes.label;
  protected readonly descriptionClass = classes.description;
  protected readonly hintClass = inputCheckClasses.hint;
  protected readonly inputClass = classes.input;
  protected readonly iconClass = classes.icon;
  protected readonly chipIconClass = clsx(classes.icon, classes.chipIcon);
  protected readonly indeterminateLineClass = classes.indeterminateLine;
  protected readonly editableInputContainerClass =
    classes.editableInputContainer;
  protected readonly checkIcon = CheckedIcon;

  protected readonly shouldShowEditableInput = computed((): boolean =>
    this.withEditInput(),
  );

  private prevChecked = false;

  constructor() {
    effect(() => {
      const checked = this.resolvedChecked();
      const show = this.shouldShowEditableInput();

      if (checked && !this.prevChecked && show) {
        queueMicrotask(() => {
          const el = this.editableInputElRef()?.nativeElement;
          const input = el?.querySelector('input');

          input?.focus();
        });
      }

      this.prevChecked = checked;
    });
  }

  protected onEditableInputMouseDown(event: MouseEvent): void {
    if (!this.resolvedChecked() && !this.resolvedDisabled()) {
      event.preventDefault();

      const hostEl = this.hostElRef.nativeElement;
      const checkboxInput = hostEl.querySelector(
        'input[type="checkbox"]',
      ) as HTMLInputElement | null;

      checkboxInput?.click();
    }
  }

  protected onEditableInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;

    this.editableInputChange.emit(value);
  }

  // CVA
  private onChange: (value: boolean) => void = () => {};
  protected onTouched: () => void = () => {};

  writeValue(value: boolean): void {
    this.internalChecked.set(!!value);
  }

  registerOnChange(fn: (value: boolean) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  protected onInputChange(event: Event): void {
    const target = event.target as HTMLInputElement;
    const newChecked = target.checked;

    if (this.group) {
      this.group.toggle(this.value());
    } else {
      this.internalChecked.set(newChecked);
      this.onChange(newChecked);
    }
  }
}

// packages/vue/checkbox/checkbox.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref, useAttrs, useId, watch } from 'vue';
import { checkboxClasses as classes } from '@mezzanine-ui/core/checkbox';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useCheckboxControlValue } from '../_internal/use-checkbox-control-value';
import MznIcon from '../icon/icon.vue';
import MznInput from '../input/input.vue';
import MznTypography from '../typography/typography.vue';
import type { TypographyColor } from '@mezzanine-ui/core/typography';
import { checkboxGroupKey } from './checkbox-group-context';
import type { CheckboxEditableInput, CheckboxProps } from './checkbox.types';

/**
 * 核取方塊，支援預設（default）與晶片（chip）兩種模式。
 *
 * 受控與非受控皆可；放在 MznCheckboxGroup 內時必須提供 `value`。
 * `indeterminate` 顯示中間狀態，`withEditInput` 會在勾選後於右側顯示一個輸入框，
 * 勾選當下自動聚焦到它。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCheckbox } from '@mezzanine-ui/vue/checkbox';
 * <\/script>
 *
 * <template>
 *   <MznCheckbox label="同意條款" name="agree" @change="onChange" />
 *   <MznCheckbox label="其他" with-edit-input value="other" />
 * </template>
 * ```
 *
 * @see MznCheckboxGroup 一組共用 name 的核取方塊
 * @see useCheckboxControlValue 勾選狀態的 composable
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CheckboxProps>(), {
  checked: undefined,
  defaultChecked: undefined,
  description: undefined,
  disabled: undefined,
  editableInput: undefined,
  id: undefined,
  indeterminate: false,
  inputProps: undefined,
  label: undefined,
  mode: 'default',
  name: undefined,
  severity: 'info',
  size: 'main',
  value: undefined,
  withEditInput: false,
});

const emit = defineEmits<{
  change: [event: Event];
}>();

const attrs = useAttrs();
const checkboxGroup = inject(checkboxGroupKey, undefined);

const disabled = computed(
  (): boolean | undefined => props.disabled ?? checkboxGroup?.value.disabled,
);

const generatedId = useId();
const finalInputId = computed((): string => props.id ?? generatedId);

const nameFromInputProps = computed(
  (): string | undefined => props.inputProps?.name,
);

const name = computed(
  (): string | undefined => props.name ?? checkboxGroup?.value.name,
);

const resolvedName = computed((): string => {
  if (name.value) return name.value;
  if (nameFromInputProps.value) return nameFromInputProps.value;

  return finalInputId.value;
});

if (checkboxGroup && props.value == null) {
  throw new Error(
    'Checkbox: `value` is required when the checkbox is used inside a CheckboxGroup.',
  );
}

const { checked, onChange } = useCheckboxControlValue({
  checkboxGroup: () => checkboxGroup?.value,
  checked: () => props.checked,
  defaultChecked: () => props.defaultChecked,
  onChange: (event) => emit('change', event),
  value: () => props.value,
});

// Warn when checkbox is standalone and missing a name (helpful for form libs)
onMounted(() => {
  if (
    !checkboxGroup &&
    !name.value &&
    !nameFromInputProps.value &&
    props.label
  ) {
    console.warn(
      'Checkbox: The `name` prop is recommended when integrating with react-hook-form. ' +
        `Checkbox with label "${props.label}" is missing the \`name\` prop.`,
    );
  }
});

const isChecked = computed(
  (): boolean => checked.value && !props.indeterminate,
);
const isIndeterminate = computed((): boolean => props.indeterminate);

const labelColor = computed(
  (): TypographyColor =>
    props.mode === 'chip' && disabled.value
      ? 'text-neutral-light'
      : 'text-neutral-solid',
);

const inputElement = ref<HTMLInputElement | null>(null);

/**
 * React hands the input out through an `inputRef` prop; Vue's equivalent is
 * the parent placing a `ref` on this component, so the element is exposed.
 */
defineExpose({ input: inputElement });
const editableInputElement = ref<InstanceType<typeof MznInput> | null>(null);

watch(
  [inputElement, isIndeterminate],
  ([element, indeterminate]) => {
    if (element) element.indeterminate = indeterminate;
  },
  { immediate: true },
);

// Generate default editable input config when withEditInput is true but editableInput is not provided
const defaultEditableInput = computed((): CheckboxEditableInput | undefined => {
  if (!props.withEditInput) return undefined;
  if (props.editableInput) return props.editableInput;

  // Default values when editableInput is not provided
  return {
    id: `${finalInputId.value}_input`,
    name: resolvedName.value
      ? `${resolvedName.value}_input`
      : `${finalInputId.value}_input`,
    placeholder: 'Please enter...',
  };
});

const shouldShowEditableInput = computed((): boolean =>
  Boolean(props.withEditInput && defaultEditableInput.value),
);

watch(isChecked, (nowChecked, wasChecked) => {
  if (nowChecked && !wasChecked && shouldShowEditableInput.value) {
    editableInputElement.value?.input?.focus();
  }
});

function handleChipHostClick(event: MouseEvent): void {
  if (disabled.value) return;

  if (event.target === event.currentTarget) {
    inputElement.value?.click();
  }
}

function handleChipHostKeyDown(event: KeyboardEvent): void {
  if (disabled.value) return;

  if (
    event.target === event.currentTarget &&
    (event.key === 'Enter' || event.key === ' ')
  ) {
    event.preventDefault();
    inputElement.value?.click();
  }
}

function handleEditableInputMouseDown(event: MouseEvent): void {
  if (event.defaultPrevented) return;

  if (!isChecked.value && !disabled.value && inputElement.value) {
    // Block the native focus-on-mousedown so the watcher above owns focus timing
    event.preventDefault();
    inputElement.value.click();
  }
}

const editableInputProps = computed(() => {
  const source = defaultEditableInput.value;

  if (!source) return undefined;

  const { inputProps: sourceInputProps, ...rest } = source;

  return {
    ...rest,
    ...(disabled.value && source.disabled !== true ? { disabled: true } : {}),
    inputProps: {
      ...sourceInputProps,
      onMousedown: handleEditableInputMouseDown,
    },
    variant: 'base' as const,
  };
});

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    attrs.class as string,
    {
      [classes.checked]: isChecked.value,
      [classes.indeterminate]: isIndeterminate.value,
      [classes.disabled]: disabled.value,
      [classes.mode(props.mode)]: props.mode !== 'default',
      ...(props.severity ? { [classes.severity(props.severity)]: true } : {}),
    },
    classes.size(props.size),
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const chipHostListeners = computed(() =>
  props.mode === 'chip'
    ? { click: handleChipHostClick, keydown: handleChipHostKeyDown }
    : {},
);

const descriptionClass = classes.description;
const editableInputContainerClass = classes.editableInputContainer;
const iconClass = classes.icon;
const chipIconClasses = `${classes.icon} ${classes.chipIcon}`;
const indeterminateLineClass = classes.indeterminateLine;
const inputClass = classes.input;
const inputContainerClass = classes.inputContainer;
const inputContentClass = classes.inputContent;
const labelClass = classes.label;
const labelContainerClass = classes.labelContainer;
const textContainerClass = classes.textContainer;
</script>

<template>
  <div :class="hostClasses" v-on="chipHostListeners">
    <label v-bind="forwardedAttrs" :class="labelContainerClass">
      <div :class="inputContainerClass">
        <div :class="inputContentClass">
          <input
            ref="inputElement"
            v-bind="inputProps"
            :aria-checked="isIndeterminate ? 'mixed' : checked"
            :aria-disabled="disabled"
            :checked="isChecked"
            :class="inputClass"
            :disabled="disabled"
            :id="finalInputId"
            :name="resolvedName"
            type="checkbox"
            :value="value"
            @change="onChange"
          />
          <MznIcon
            v-if="mode === 'chip' && isChecked"
            aria-hidden="true"
            :class="chipIconClasses"
            color="brand"
            :icon="CheckedIcon"
            :size="16"
          />
          <MznIcon
            v-if="mode !== 'chip' && isChecked"
            aria-hidden="true"
            :class="iconClass"
            color="fixed-light"
            :icon="CheckedIcon"
            :size="9"
          />
          <span
            v-if="mode !== 'chip' && isIndeterminate"
            aria-hidden="true"
            :class="indeterminateLineClass"
          />
        </div>
      </div>
      <span v-if="label || description" :class="textContainerClass">
        <MznTypography
          v-if="label"
          :class="labelClass"
          :color="labelColor"
          variant="label-primary"
        >
          {{ label }}
        </MznTypography>
        <MznTypography
          v-if="description && mode !== 'chip' && !shouldShowEditableInput"
          :class="descriptionClass"
          color="text-neutral"
          variant="caption"
        >
          {{ description }}
        </MznTypography>
      </span>
    </label>
    <label
      v-if="
        shouldShowEditableInput &&
        editableInputProps &&
        mode !== 'chip' &&
        !indeterminate
      "
      :class="editableInputContainerClass"
      :for="finalInputId"
    >
      <MznInput ref="editableInputElement" v-bind="editableInputProps" />
    </label>
  </div>
</template>
