// packages/vue/calendar/calendar-years.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import {
  calendarClasses as classes,
  calendarYearsBase,
  getCalendarYearRange,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import clsx from 'clsx';
import MznCalendarCell from './calendar-cell.vue';
import { useCalendarContext } from './calendar-context';
import type { CalendarYearsProps } from './calendar-years.types';

/**
 * 年份面板，一次顯示 12 個年份。
 *
 * 年份範圍由 `referenceDate` 所在的區間決定；點擊會送出該年第一天的日期物件。
 * 可用來組裝自訂日曆。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarYears } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarYears reference-date="2026-01-01" @click="onChange" />
 * </template>
 * ```
 *
 * @see MznCalendar 依 `mode` 切換各面板
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarYearsProps>(), {
  isYearDisabled: undefined,
  isYearInRange: undefined,
  value: undefined,
});

const emit = defineEmits<{
  click: [target: DateType];
  yearHover: [target: DateType];
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const start = computed(
  (): number =>
    getCalendarYearRange(calendar.value.getYear(props.referenceDate))[0],
);

const years = computed(() =>
  calendarYearsBase.map((base) => {
    const {
      getNow,
      getYear,
      isYearIncluded,
      setYear,
      getCurrentYearFirstDate,
    } = calendar.value;
    const thisYear = base + start.value;
    const yearDateType = setYear(getCurrentYearFirstDate(getNow()), thisYear);
    const disabled = props.isYearDisabled && props.isYearDisabled(yearDateType);
    const active =
      !disabled && props.value && isYearIncluded(yearDateType, props.value);
    const inRange = props.isYearInRange && props.isYearInRange(yearDateType);
    const isRangeStart =
      props.value && props.value.length > 0
        ? isYearIncluded(yearDateType, [props.value[0]])
        : false;
    const isRangeEnd =
      props.value && props.value.length > 0
        ? isYearIncluded(yearDateType, [props.value[props.value.length - 1]])
        : false;

    const ariaLabel = [
      `Year ${thisYear}`,
      active && 'Selected',
      disabled && 'Not available',
    ]
      .filter(Boolean)
      .join(', ');

    return {
      active,
      ariaLabel,
      buttonClasses: clsx(classes.button, {
        [classes.buttonActive]: active,
        [classes.buttonInRange]: inRange,
        [classes.buttonDisabled]: disabled,
      }),
      disabled,
      isRangeEnd,
      isRangeStart,
      thisYear,
      today: getYear(getNow()) === thisYear,
      yearDateType,
    };
  }),
);

const hostClasses = computed((): string =>
  clsx(classes.board, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const gridClass = classes.twelveGrid;
</script>

<template>
  <div :class="hostClasses" v-bind="forwardedAttrs">
    <div :class="gridClass">
      <MznCalendarCell
        v-for="year in years"
        :key="year.thisYear"
        :active="year.active"
        :is-range-end="year.isRangeEnd"
        :is-range-start="year.isRangeStart"
        mode="year"
        :today="year.today"
      >
        <button
          :aria-disabled="year.disabled"
          :aria-label="year.ariaLabel"
          :aria-pressed="year.active"
          :class="year.buttonClasses"
          :disabled="year.disabled"
          type="button"
          @click="emit('click', year.yearDateType)"
          @mouseenter="emit('yearHover', year.yearDateType)"
        >
          {{ year.thisYear }}
        </button>
      </MznCalendarCell>
    </div>
  </div>
</template>

// packages/react/src/Calendar/CalendarYears.tsx
'use client';

import {
  calendarClasses as classes,
  DateType,
  getCalendarYearRange,
  calendarYearsBase,
} from '@mezzanine-ui/core/calendar';
import { useMemo } from 'react';
import CalendarCell from './CalendarCell';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { useCalendarContext } from './CalendarContext';

export interface CalendarYearsProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'div'>,
    'onClick' | 'children'
  > {
  /**
   * Provide if you have a custom disabling logic.
   * The method takes the date object as its parameter.
   */
  isYearDisabled?: (date: DateType) => boolean;
  /**
   * Provide if you have a custom logic for checking if the year is in range.
   * The method takes the date object as its parameter.
   */
  isYearInRange?: (date: DateType) => boolean;
  /**
   * Click handler for the button of each year.
   * The method takes the date object as its parameter.
   */
  onClick?: (target: DateType) => void;
  /**
   * Mouse enter handler for the button of each year.
   * The method takes the date object as its parameter.
   */
  onYearHover?: (target: DateType) => void;
  /**
   * The refernce date for getting the years range and computing the date object.
   */
  referenceDate: DateType;
  /**
   * The year will be marked as active if it matches the same year of any value in the array.
   */
  value?: DateType[];
}

/**
 * The react component for `mezzanine` calendar years. <br />
 * This component displays a 12 year grid.
 * You may use it to compose your own calendar.
 */
function CalendarYears(props: CalendarYearsProps) {
  const { getNow, getYear, isYearIncluded, setYear, getCurrentYearFirstDate } =
    useCalendarContext();
  const {
    className,
    isYearDisabled,
    isYearInRange,
    onClick: onClickProp,
    onYearHover,
    referenceDate,
    value,
    ...rest
  } = props;

  const [start] = useMemo(
    () => getCalendarYearRange(getYear(referenceDate)),
    [getYear, referenceDate],
  );

  return (
    <div className={cx(classes.board, className)} {...rest}>
      <div className={classes.twelveGrid}>
        {calendarYearsBase.map((base) => {
          const thisYear = base + start;
          const yearDateType = setYear(
            getCurrentYearFirstDate(getNow()),
            thisYear,
          );
          const disabled = isYearDisabled && isYearDisabled(yearDateType);
          const active =
            !disabled && value && isYearIncluded(yearDateType, value);
          const inRange = isYearInRange && isYearInRange(yearDateType);
          const isRangeStart =
            value && value.length > 0
              ? isYearIncluded(yearDateType, [value[0]])
              : false;
          const isRangeEnd =
            value && value.length > 0
              ? isYearIncluded(yearDateType, [value[value.length - 1]])
              : false;

          const onClick = onClickProp
            ? () => {
                onClickProp(yearDateType);
              }
            : undefined;
          const onMouseEnter = onYearHover
            ? () => {
                onYearHover(yearDateType);
              }
            : undefined;

          // Accessible year label for screen readers
          const ariaLabel = [
            `Year ${thisYear}`,
            active && 'Selected',
            disabled && 'Not available',
          ]
            .filter(Boolean)
            .join(', ');

          return (
            <CalendarCell
              key={base + start}
              mode="year"
              today={getYear(getNow()) === thisYear}
              active={active}
              isRangeStart={isRangeStart}
              isRangeEnd={isRangeEnd}
            >
              <button
                type="button"
                aria-disabled={disabled}
                disabled={disabled}
                aria-label={ariaLabel}
                aria-pressed={active}
                className={cx(classes.button, {
                  [classes.buttonActive]: active,
                  [classes.buttonInRange]: inRange,
                  [classes.buttonDisabled]: disabled,
                })}
                onClick={onClick}
                onMouseEnter={onMouseEnter}
              >
                {thisYear}
              </button>
            </CalendarCell>
          );
        })}
      </div>
    </div>
  );
}

export default CalendarYears;
