// packages/vue/calendar/calendar-quick-select.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { CalendarQuickSelectProps } from './calendar-quick-select.types';

/**
 * 日曆左側的快速選取清單。
 *
 * 每個選項是一顆按鈕，`activeId` 相符的那顆會加上勾選圖示與選取樣式。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCalendarQuickSelect } from '@mezzanine-ui/vue/calendar';
 * <\/script>
 *
 * <template>
 *   <MznCalendarQuickSelect
 *     active-id="today"
 *     :options="[{ id: 'today', name: 'Today', onClick: selectToday }]"
 *   />
 * </template>
 * ```
 *
 * @see MznCalendar 透過 `quickSelect` prop 使用這個清單
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CalendarQuickSelectProps>(), {
  activeId: undefined,
});

const attrs = useAttrs();

const hostClasses = computed((): string =>
  clsx(classes.quickSelect, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const buttonClasses = (id: string): string =>
  clsx(
    classes.quickSelectButton,
    id === props.activeId && classes.quickSelectButtonActive,
  );
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <button
      v-for="{ id, name, disabled, onClick } in options"
      :key="id"
      :aria-disabled="disabled"
      :class="buttonClasses(id)"
      :disabled="disabled"
      type="button"
      @click="onClick"
    >
      <span>{{ name }}</span>
      <MznIcon v-if="id === activeId" :icon="CheckedIcon" :size="16" />
    </button>
  </div>
</template>

// packages/react/src/Calendar/CalendarQuickSelect.tsx
import { calendarClasses as classes } from '@mezzanine-ui/core/calendar';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Icon from '../Icon';
import { CheckedIcon } from '@mezzanine-ui/icons';

export interface CalendarQuickSelectProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'onClick'> {
  /**
   * The id of active quick select button.
   */
  activeId?: string;
  /**
   * The options for quick select buttons.
   */
  options: {
    id: string;
    name: string;
    disabled?: boolean;
    onClick: VoidFunction;
  }[];
}

/**
 * The react component for `mezzanine` calendar quick select.
 */
function CalendarQuickSelect(props: CalendarQuickSelectProps) {
  const { className, activeId, options, ...restElementProps } = props;

  return (
    <div {...restElementProps} className={cx(classes.quickSelect, className)}>
      {options.map(({ id, name, disabled, onClick }) => (
        <button
          key={id}
          type="button"
          disabled={disabled}
          aria-disabled={disabled}
          className={cx(
            classes.quickSelectButton,
            id === activeId && classes.quickSelectButtonActive,
          )}
          onClick={onClick}
        >
          <span>{name}</span>
          {id === activeId && <Icon icon={CheckedIcon} size={16} />}
        </button>
      ))}
    </div>
  );
}

export default CalendarQuickSelect;
