// packages/vue/clear-actions/clear-actions.vue
<script setup lang="ts">
import { computed } from 'vue';
import { CloseIcon, DangerousFilledIcon } from '@mezzanine-ui/icons';
import {
  clearActionsClasses as classes,
  type ClearActionsType,
  type ClearActionsVariant,
} from '@mezzanine-ui/core/clear-actions';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { ClearActionsProps } from './clear-actions.types';

/**
 * 清除／關閉動作按鈕。
 *
 * `type` 決定使用情境：`standard` 為獨立按鈕、`embedded` 內嵌於其他控制項、
 * `clearable` 用於清除輸入內容（改用警示圖示）。`variant` 依 `type` 提供對應的視覺變體，
 * 未指定時 standard 取 `base`、embedded 取 `contrast`、clearable 固定為 `default`。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznClearActions } from '@mezzanine-ui/vue/clear-actions';
 * <\/script>
 *
 * <template>
 *   <MznClearActions @click="onClear" />
 *   <MznClearActions type="embedded" variant="emphasis" @click="onClear" />
 *   <MznClearActions type="clearable" @click="onClear" />
 * </template>
 * ```
 */
/**
 * No `withDefaults` here: combined with a discriminated union it makes Vue fall
 * back to `Record<string, any>` for the generated component type, which then
 * breaks `Meta<typeof …>` in the stories. React applies the same default in a
 * destructure rather than in the prop declaration, so resolving it here is the
 * closer mirror anyway.
 */
const props = defineProps<ClearActionsProps>();

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();

const type = computed((): ClearActionsType => props.type ?? 'standard');

const resolvedVariant = computed((): ClearActionsVariant => {
  if (type.value === 'clearable') return 'default';

  const variant = 'variant' in props ? props.variant : undefined;

  return variant ?? (type.value === 'standard' ? 'base' : 'contrast');
});

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.type(type.value),
    classes.variant(resolvedVariant.value),
  ),
);

const icon = computed(() =>
  type.value === 'clearable' ? DangerousFilledIcon : CloseIcon,
);

const iconClass = classes.icon;
</script>

<template>
  <button
    aria-label="Close"
    :class="hostClasses"
    type="button"
    @click="emit('click', $event)"
  >
    <MznIcon :class="iconClass" :icon="icon" />
  </button>
</template>

// packages/ng/clear-actions/clear-actions.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import {
  clearActionsClasses as classes,
  ClearActionsEmbeddedVariant,
  ClearActionsStandardVariant,
  ClearActionsType,
  ClearActionsVariant,
} from '@mezzanine-ui/core/clear-actions';
import { CloseIcon, DangerousFilledIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';

/**
 * 清除操作按鈕元件，提供關閉或清除功能。
 *
 * 根據 `type` 決定圖示與視覺樣式：
 * - `standard`：使用 CloseIcon，支援 `base` / `inverse` 變體
 * - `embedded`：使用 CloseIcon，支援 `contrast` / `emphasis` 變體
 * - `clearable`：使用 DangerousFilledIcon
 *
 * @example
 * ```html
 * import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';
 *
 * <button mznClearActions (clicked)="onClose()" ></button>
 * <button mznClearActions type="embedded" variant="contrast" (clicked)="onClose()" ></button>
 * <button mznClearActions type="clearable" (clicked)="onClear()" ></button>
 * ```
 */
@Component({
  selector: 'button[mznClearActions]',
  host: {
    '[attr.type]': "'button'",
    '[attr.aria-label]': "'Close'",
    '[attr.variant]': 'null',
    '[class]': 'hostClasses()',
    '(click)': 'clicked.emit($event)',
  },
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon],
  template: `
    @if (type() === 'clearable') {
      <i mznIcon [class]="iconClass" [icon]="dangerousIcon"></i>
    } @else {
      <i mznIcon [class]="iconClass" [icon]="closeIcon"></i>
    }
  `,
})
export class MznClearActions {
  protected readonly closeIcon = CloseIcon;
  protected readonly dangerousIcon = DangerousFilledIcon;
  protected readonly iconClass = classes.icon;

  /**
   * 點擊事件。
   */
  readonly clicked = output<MouseEvent>();

  /**
   * 清除操作類型。
   * @default 'standard'
   */
  readonly type = input<ClearActionsType>('standard');

  /**
   * 視覺變體，依 type 而定。
   * - standard: 'base' | 'inverse'
   * - embedded: 'contrast' | 'emphasis'
   */
  readonly variant = input<
    ClearActionsEmbeddedVariant | ClearActionsStandardVariant
  >();

  protected readonly resolvedVariant = computed((): ClearActionsVariant => {
    const t = this.type();

    if (t === 'clearable') return 'default';

    const v = this.variant();

    return v ?? (t === 'standard' ? 'base' : 'contrast');
  });

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.host,
      classes.type(this.type()),
      classes.variant(this.resolvedVariant()),
    ),
  );
}
