// packages/vue/checkbox/checkbox.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref, useAttrs, useId, watch } from 'vue';
import { checkboxClasses as classes } from '@mezzanine-ui/core/checkbox';
import { CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useCheckboxControlValue } from '../_internal/use-checkbox-control-value';
import MznIcon from '../icon/icon.vue';
import MznInput from '../input/input.vue';
import MznTypography from '../typography/typography.vue';
import type { TypographyColor } from '@mezzanine-ui/core/typography';
import { checkboxGroupKey } from './checkbox-group-context';
import type { CheckboxEditableInput, CheckboxProps } from './checkbox.types';

/**
 * 核取方塊，支援預設（default）與晶片（chip）兩種模式。
 *
 * 受控與非受控皆可；放在 MznCheckboxGroup 內時必須提供 `value`。
 * `indeterminate` 顯示中間狀態，`withEditInput` 會在勾選後於右側顯示一個輸入框，
 * 勾選當下自動聚焦到它。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCheckbox } from '@mezzanine-ui/vue/checkbox';
 * <\/script>
 *
 * <template>
 *   <MznCheckbox label="同意條款" name="agree" @change="onChange" />
 *   <MznCheckbox label="其他" with-edit-input value="other" />
 * </template>
 * ```
 *
 * @see MznCheckboxGroup 一組共用 name 的核取方塊
 * @see useCheckboxControlValue 勾選狀態的 composable
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<CheckboxProps>(), {
  checked: undefined,
  defaultChecked: undefined,
  description: undefined,
  disabled: undefined,
  editableInput: undefined,
  id: undefined,
  indeterminate: false,
  inputProps: undefined,
  label: undefined,
  mode: 'default',
  name: undefined,
  severity: 'info',
  size: 'main',
  value: undefined,
  withEditInput: false,
});

const emit = defineEmits<{
  change: [event: Event];
}>();

const attrs = useAttrs();
const checkboxGroup = inject(checkboxGroupKey, undefined);

const disabled = computed(
  (): boolean | undefined => props.disabled ?? checkboxGroup?.value.disabled,
);

const generatedId = useId();
const finalInputId = computed((): string => props.id ?? generatedId);

const nameFromInputProps = computed(
  (): string | undefined => props.inputProps?.name,
);

const name = computed(
  (): string | undefined => props.name ?? checkboxGroup?.value.name,
);

const resolvedName = computed((): string => {
  if (name.value) return name.value;
  if (nameFromInputProps.value) return nameFromInputProps.value;

  return finalInputId.value;
});

if (checkboxGroup && props.value == null) {
  throw new Error(
    'Checkbox: `value` is required when the checkbox is used inside a CheckboxGroup.',
  );
}

const { checked, onChange } = useCheckboxControlValue({
  checkboxGroup: () => checkboxGroup?.value,
  checked: () => props.checked,
  defaultChecked: () => props.defaultChecked,
  onChange: (event) => emit('change', event),
  value: () => props.value,
});

// Warn when checkbox is standalone and missing a name (helpful for form libs)
onMounted(() => {
  if (
    !checkboxGroup &&
    !name.value &&
    !nameFromInputProps.value &&
    props.label
  ) {
    console.warn(
      'Checkbox: The `name` prop is recommended when integrating with react-hook-form. ' +
        `Checkbox with label "${props.label}" is missing the \`name\` prop.`,
    );
  }
});

const isChecked = computed(
  (): boolean => checked.value && !props.indeterminate,
);
const isIndeterminate = computed((): boolean => props.indeterminate);

const labelColor = computed(
  (): TypographyColor =>
    props.mode === 'chip' && disabled.value
      ? 'text-neutral-light'
      : 'text-neutral-solid',
);

const inputElement = ref<HTMLInputElement | null>(null);

/**
 * React hands the input out through an `inputRef` prop; Vue's equivalent is
 * the parent placing a `ref` on this component, so the element is exposed.
 */
defineExpose({ input: inputElement });
const editableInputElement = ref<InstanceType<typeof MznInput> | null>(null);

watch(
  [inputElement, isIndeterminate],
  ([element, indeterminate]) => {
    if (element) element.indeterminate = indeterminate;
  },
  { immediate: true },
);

// Generate default editable input config when withEditInput is true but editableInput is not provided
const defaultEditableInput = computed((): CheckboxEditableInput | undefined => {
  if (!props.withEditInput) return undefined;
  if (props.editableInput) return props.editableInput;

  // Default values when editableInput is not provided
  return {
    id: `${finalInputId.value}_input`,
    name: resolvedName.value
      ? `${resolvedName.value}_input`
      : `${finalInputId.value}_input`,
    placeholder: 'Please enter...',
  };
});

const shouldShowEditableInput = computed((): boolean =>
  Boolean(props.withEditInput && defaultEditableInput.value),
);

watch(isChecked, (nowChecked, wasChecked) => {
  if (nowChecked && !wasChecked && shouldShowEditableInput.value) {
    editableInputElement.value?.input?.focus();
  }
});

function handleChipHostClick(event: MouseEvent): void {
  if (disabled.value) return;

  if (event.target === event.currentTarget) {
    inputElement.value?.click();
  }
}

function handleChipHostKeyDown(event: KeyboardEvent): void {
  if (disabled.value) return;

  if (
    event.target === event.currentTarget &&
    (event.key === 'Enter' || event.key === ' ')
  ) {
    event.preventDefault();
    inputElement.value?.click();
  }
}

function handleEditableInputMouseDown(event: MouseEvent): void {
  if (event.defaultPrevented) return;

  if (!isChecked.value && !disabled.value && inputElement.value) {
    // Block the native focus-on-mousedown so the watcher above owns focus timing
    event.preventDefault();
    inputElement.value.click();
  }
}

const editableInputProps = computed(() => {
  const source = defaultEditableInput.value;

  if (!source) return undefined;

  const { inputProps: sourceInputProps, ...rest } = source;

  return {
    ...rest,
    ...(disabled.value && source.disabled !== true ? { disabled: true } : {}),
    inputProps: {
      ...sourceInputProps,
      onMousedown: handleEditableInputMouseDown,
    },
    variant: 'base' as const,
  };
});

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    attrs.class as string,
    {
      [classes.checked]: isChecked.value,
      [classes.indeterminate]: isIndeterminate.value,
      [classes.disabled]: disabled.value,
      [classes.mode(props.mode)]: props.mode !== 'default',
      ...(props.severity ? { [classes.severity(props.severity)]: true } : {}),
    },
    classes.size(props.size),
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const chipHostListeners = computed(() =>
  props.mode === 'chip'
    ? { click: handleChipHostClick, keydown: handleChipHostKeyDown }
    : {},
);

const descriptionClass = classes.description;
const editableInputContainerClass = classes.editableInputContainer;
const iconClass = classes.icon;
const chipIconClasses = `${classes.icon} ${classes.chipIcon}`;
const indeterminateLineClass = classes.indeterminateLine;
const inputClass = classes.input;
const inputContainerClass = classes.inputContainer;
const inputContentClass = classes.inputContent;
const labelClass = classes.label;
const labelContainerClass = classes.labelContainer;
const textContainerClass = classes.textContainer;
</script>

<template>
  <div :class="hostClasses" v-on="chipHostListeners">
    <label v-bind="forwardedAttrs" :class="labelContainerClass">
      <div :class="inputContainerClass">
        <div :class="inputContentClass">
          <input
            ref="inputElement"
            v-bind="inputProps"
            :aria-checked="isIndeterminate ? 'mixed' : checked"
            :aria-disabled="disabled"
            :checked="isChecked"
            :class="inputClass"
            :disabled="disabled"
            :id="finalInputId"
            :name="resolvedName"
            type="checkbox"
            :value="value"
            @change="onChange"
          />
          <MznIcon
            v-if="mode === 'chip' && isChecked"
            aria-hidden="true"
            :class="chipIconClasses"
            color="brand"
            :icon="CheckedIcon"
            :size="16"
          />
          <MznIcon
            v-if="mode !== 'chip' && isChecked"
            aria-hidden="true"
            :class="iconClass"
            color="fixed-light"
            :icon="CheckedIcon"
            :size="9"
          />
          <span
            v-if="mode !== 'chip' && isIndeterminate"
            aria-hidden="true"
            :class="indeterminateLineClass"
          />
        </div>
      </div>
      <span v-if="label || description" :class="textContainerClass">
        <MznTypography
          v-if="label"
          :class="labelClass"
          :color="labelColor"
          variant="label-primary"
        >
          {{ label }}
        </MznTypography>
        <MznTypography
          v-if="description && mode !== 'chip' && !shouldShowEditableInput"
          :class="descriptionClass"
          color="text-neutral"
          variant="caption"
        >
          {{ description }}
        </MznTypography>
      </span>
    </label>
    <label
      v-if="
        shouldShowEditableInput &&
        editableInputProps &&
        mode !== 'chip' &&
        !indeterminate
      "
      :class="editableInputContainerClass"
      :for="finalInputId"
    >
      <MznInput ref="editableInputElement" v-bind="editableInputProps" />
    </label>
  </div>
</template>

// packages/react/src/Checkbox/Checkbox.tsx
'use client';

import {
  ChangeEventHandler,
  MouseEvent,
  Ref,
  forwardRef,
  useContext,
  useEffect,
  useId,
  useMemo,
  useRef,
} from 'react';

import {
  CheckboxSize,
  checkboxClasses as classes,
} from '@mezzanine-ui/core/checkbox';

import { CheckedIcon } from '@mezzanine-ui/icons';

import { useCheckboxControlValue } from '../Form/useCheckboxControlValue';
import Icon from '../Icon';
import Input, { BaseInputProps } from '../Input';
import Typography, { TypographyColor } from '../Typography';
import { composeRefs } from '../utils/composeRefs';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { CheckboxGroupContext } from './CheckboxGroupContext';
import { CheckboxPropsBase } from './typings';

type CheckboxInputElementProps = Omit<
  NativeElementPropsWithoutKeyAndRef<'input'>,
  | 'checked'
  | 'defaultChecked'
  | 'disabled'
  | 'onChange'
  | 'placeholder'
  | 'type'
  | 'value'
  | `aria-${'disabled' | 'checked'}`
> & {
  /**
   * The id attribute can be provided via inputProps, but it's recommended to use the `id` prop directly.
   * If both are provided, the `id` prop takes precedence.
   */
  id?: string;
  /**
   * The name attribute can be provided via inputProps, but it's recommended to use the `name` prop directly.
   * If both are provided, the `name` prop takes precedence.
   */
  name?: string;
};

export interface CheckboxProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'label'>, 'onChange'>,
  CheckboxPropsBase {
  /**
   * Whether to show an editable input when checkbox is checked.
   * When `true`, an Input component will be displayed after the checkbox when checked.
   * If `editableInput` is not provided, default values will be used (name, id, placeholder).
   *
   * @example Simple usage
   * ```tsx
   * <Checkbox
   *   label="其他"
   *   withEditInput
   *   value={otherValue}
   *   onChange={(e) => setOtherValue(e.target.value)}
   * />
   * ```
   *
   * @example With custom editableInput
   * ```tsx
   * <Checkbox
   *   label="其他"
   *   withEditInput
   *   editableInput={{
   *     placeholder: "請輸入其他選項",
   *     name: "otherOption",
   *     value: otherValue,
   *     onChange: (e) => setOtherValue(e.target.value),
   *   }}
   * />
   * ```
   *
   * @example With react-hook-form
   * ```tsx
   * const { register, watch } = useForm();
   * const isOtherChecked = watch('options.other');
   *
   * <Checkbox
   *   label="其他"
   *   {...register('options.other')}
   *   withEditInput
   *   editableInput={{
   *     ...register('otherOption', { required: isOtherChecked }),
   *     placeholder: "請輸入其他選項",
   *   }}
   * />
   * ```
   */
  withEditInput?: boolean;
  /**
   * Configuration for editable input that appears when checkbox is checked.
   * When `withEditInput` is `true` and this prop is not provided, default values will be used.
   *
   * Default values when not provided:
   * - `name`: `{checkboxName}_input` or `{checkboxId}_input`
   * - `id`: `{checkboxId}_input`
   * - `placeholder`: "Please enter..."
   */
  editableInput?: Omit<BaseInputProps, 'variant'>;
  /**
   * The id of input element.
   */
  id?: string;
  /**
   * Since at Mezzanine we use a host element to wrap our input, most derived props will be passed to the host element.
   * If you need direct control to the input element, use this prop to provide to it.
   */
  inputProps?: CheckboxInputElementProps;
  /**
   * The react ref passed to input element.
   *
   * @important When using with react-hook-form's `register`, pass the ref through this prop:
   * ```tsx
   * const { register } = useForm();
   * <Checkbox inputRef={register('fieldName').ref} name="fieldName" />
   * ```
   *
   * For CheckboxGroup, use `Controller` instead of `register` for better array value handling.
   */
  inputRef?: Ref<HTMLInputElement>;
  /**
   * The name attribute of the input element.
   *
   * @important When using with react-hook-form or inside a CheckboxGroup, this prop is recommended.
   * For CheckboxGroup, all checkboxes should share the same `name` attribute.
   *
   * When using with react-hook-form's `register`, ensure this matches the field name:
   * ```tsx
   * const { register } = useForm();
   * <Checkbox {...register('fieldName')} inputRef={register('fieldName').ref} />
   * ```
   */
  name?: string;
  /**
   * Invoked by input change event.
   */
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * The value of checkbox. Used when checkbox is inside a CheckboxGroup.
   *
   * @important This prop is required when checkbox is inside a CheckboxGroup.
   * It is also recommended when integrating with react-hook-form.
   */
  value?: string;
  /**
   * The size of checkbox.
   * When mode is 'chip', size can be 'main' | 'sub' | 'minor'.
   * When mode is 'default', size can be 'main' | 'sub'.
   * @default 'main'
   */
  size?: CheckboxSize<NonNullable<CheckboxPropsBase['mode']>>;
}

/**
 * 核取方塊元件，支援預設（default）與晶片（chip）兩種模式。
 *
 * 提供受控與非受控兩種使用方式，可透過 `checked`／`defaultChecked` 切換狀態。
 * 在 `CheckboxGroup` 內使用時，必須提供 `value` 屬性；支援 `indeterminate` 中間狀態
 * 及 `withEditInput` 勾選後顯示附加輸入框的功能。
 *
 * @example
 * ```tsx
 * import Checkbox from '@mezzanine-ui/react/Checkbox';
 *
 * // 基本用法（非受控）
 * <Checkbox label="同意條款" defaultChecked />
 *
 * // 受控用法
 * const [checked, setChecked] = useState(false);
 * <Checkbox
 *   checked={checked}
 *   label="訂閱電子報"
 *   onChange={(e) => setChecked(e.target.checked)}
 * />
 *
 * // Chip 模式
 * <Checkbox label="熱門" mode="chip" size="sub" />
 *
 * // 含附加輸入框
 * <Checkbox label="其他" withEditInput editableInput={{ placeholder: '請輸入其他選項' }} />
 * ```
 *
 * @see {@link CheckboxGroup} 管理多個核取方塊的群組元件
 * @see {@link useCheckboxControlValue} 核取方塊受控值的自訂 Hook
 */
const Checkbox = forwardRef<HTMLLabelElement, CheckboxProps>(
  function Checkbox(props, ref) {
    const checkboxGroup = useContext(CheckboxGroupContext);
    const { disabled: disabledFromGroup, name: nameFromGroup } =
      checkboxGroup || {};
    const {
      checked: checkedProp,
      className,
      defaultChecked,
      description,
      disabled = disabledFromGroup,
      editableInput,
      id,
      indeterminate = false,
      inputProps,
      inputRef: inputRefProp,
      label,
      mode = 'default',
      name = nameFromGroup,
      onChange: onChangeProp,
      severity = 'info',
      size = 'main',
      value,
      withEditInput = false,
      ...rest
    } = props;

    const { name: nameFromInputProps, ...restInputProps } = inputProps || {};

    // Generate unique id if not provided
    const generatedId = useId();
    const finalInputId = id ?? generatedId;

    if (checkboxGroup && value == null) {
      throw new Error(
        'Checkbox: `value` is required when the checkbox is used inside a CheckboxGroup.',
      );
    }

    const [checked, onChange] = useCheckboxControlValue({
      checked: checkedProp,
      defaultChecked,
      onChange: onChangeProp,
      checkboxGroup,
      value,
    });

    // Warn when checkbox is standalone and missing a name (helpful for form libs)
    useEffect(() => {
      if (!checkboxGroup && !name && !nameFromInputProps && label) {
        console.warn(
          'Checkbox: The `name` prop is recommended when integrating with react-hook-form. ' +
          `Checkbox with label "${label}" is missing the \`name\` prop.`,
        );
      }
    }, [checkboxGroup, name, nameFromInputProps, label]);

    const isChecked = checked && !indeterminate;
    const isIndeterminate = indeterminate;

    const resolvedName = useMemo(() => {
      if (name) return name;
      if (nameFromInputProps) return nameFromInputProps;

      return finalInputId;
    }, [finalInputId, name, nameFromInputProps]);

    const labelColor: TypographyColor = useMemo(() => {
      if (mode === 'chip' && disabled) {
        return 'text-neutral-light';
      }
      return 'text-neutral-solid';
    }, [mode, disabled]);

    const inputElementRef = useRef<HTMLInputElement | null>(null);

    const composedInputRef = useMemo(
      () => composeRefs([inputRefProp, inputElementRef]),
      [inputRefProp],
    );

    useEffect(() => {
      if (inputElementRef.current) {
        inputElementRef.current.indeterminate = isIndeterminate;
      }
    }, [isIndeterminate]);

    const editableInputRef = useRef<HTMLInputElement | null>(null);

    // Generate default editable input config when withEditInput is true but editableInput is not provided
    const defaultEditableInput = useMemo(() => {
      if (!withEditInput) return undefined;

      if (editableInput) {
        return editableInput;
      }

      // Default values when editableInput is not provided
      const defaultName = resolvedName
        ? `${resolvedName}_input`
        : `${finalInputId}_input`;
      const defaultId = `${finalInputId}_input`;

      return {
        id: defaultId,
        name: defaultName,
        placeholder: 'Please enter...',
      } as Omit<BaseInputProps, 'variant'>;
    }, [withEditInput, editableInput, resolvedName, finalInputId]);

    const shouldShowEditableInput = withEditInput && defaultEditableInput;
    const prevIsCheckedRef = useRef(isChecked);

    useEffect(() => {
      if (isChecked && !prevIsCheckedRef.current && shouldShowEditableInput && editableInputRef.current) {
        editableInputRef.current.focus();
      }
      prevIsCheckedRef.current = isChecked;
    }, [isChecked, shouldShowEditableInput]);

    const handleEditableInputContainerMouseDown = (event: MouseEvent<HTMLDivElement>) => {
      if (!isChecked && !disabled && inputElementRef.current) {
        event.preventDefault(); // 阻止原生 focus-on-mousedown，讓 useEffect 統一控制 focus 時機
        inputElementRef.current.click();
      }
    };

    return (
      <div
        className={cx(
          classes.host,
          className,
          {
            [classes.checked]: isChecked,
            [classes.indeterminate]: isIndeterminate,
            [classes.disabled]: disabled,
            [classes.mode(mode)]: mode !== 'default',
            ...(severity && { [classes.severity(severity)]: true }),
          },
          classes.size(size),
        )}
      >
        <label ref={ref} {...rest} className={classes.labelContainer}>
          <div className={classes.inputContainer}>
            <div className={classes.inputContent}>
              <input
                {...restInputProps}
                aria-checked={isIndeterminate ? 'mixed' : checked}
                aria-disabled={disabled}
                checked={isChecked}
                className={classes.input}
                disabled={disabled}
                id={finalInputId}
                name={resolvedName}
                onChange={onChange}
                ref={composedInputRef}
                type="checkbox"
                value={value}
              />
              {mode === 'chip' && isChecked && (
                <Icon
                  aria-hidden="true"
                  className={cx(classes.icon, classes.chipIcon)}
                  color="brand"
                  icon={CheckedIcon}
                  size={16}
                />
              )}
              {mode !== 'chip' && isChecked && (
                <Icon
                  aria-hidden="true"
                  className={classes.icon}
                  color="fixed-light"
                  icon={CheckedIcon}
                  size={9}
                />
              )}
              {mode !== 'chip' && isIndeterminate && (
                <span
                  aria-hidden="true"
                  className={classes.indeterminateLine}
                />
              )}
            </div>
          </div>
          {(label || description) && (
            <span className={classes.textContainer}>
              {label && (
                <Typography
                  className={classes.label}
                  color={labelColor}
                  variant="label-primary"
                >
                  {label}
                </Typography>
              )}
              {description && mode !== 'chip' && !shouldShowEditableInput && (
                <Typography
                  className={classes.description}
                  color="text-neutral"
                  variant="caption"
                >
                  {description}
                </Typography>
              )}
            </span>
          )}
        </label>
        {shouldShowEditableInput &&
          defaultEditableInput &&
          mode !== 'chip' &&
          !indeterminate && (
            <div
              className={classes.editableInputContainer}
              onMouseDown={handleEditableInputContainerMouseDown}
            >
              <Input
                {...defaultEditableInput}
                {...(disabled &&
                  defaultEditableInput.disabled !== true
                  ? { disabled: true }
                  : {})}
                inputRef={composeRefs([
                  defaultEditableInput.inputRef,
                  editableInputRef,
                ])}
                variant="base"
              />
            </div>
          )}
      </div>
    );
  },
);

export default Checkbox;
