// packages/ng/form/form-group.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import { formGroupClasses as classes } from '@mezzanine-ui/core/form';

/**
 * 表單群組元件，將多個表單欄位歸組並加上標題。
 *
 * @example
 * ```html
 * import { MznFormGroup } from '@mezzanine-ui/ng/form';
 *
 * <div mznFormGroup title="基本資料">
 *   <div mznFormField name="name" label="姓名">...</div>
 *   <div mznFormField name="email" label="信箱">...</div>
 * </div>
 * ```
 */
@Component({
  selector: '[mznFormGroup]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
    '[attr.fieldsContainerClassName]': 'null',
    '[attr.title]': 'null',
  },
  template: `
    <div [class]="titleClass">{{ title() }}</div>
    <div [class]="fieldsContainerClass()">
      <ng-content />
    </div>
  `,
})
export class MznFormGroup {
  protected readonly hostClass = classes.host;
  protected readonly titleClass = classes.title;
  protected readonly fieldsContainerClass = computed(() => {
    const extra = this.fieldsContainerClassName();
    return extra
      ? `${classes.fieldsContainer} ${extra}`
      : classes.fieldsContainer;
  });

  /** fields container div 的額外 CSS class。 */
  readonly fieldsContainerClassName = input<string>();

  /** 群組標題。 */
  readonly title = input.required<string>();
}

// packages/vue/form/form-group.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { formGroupClasses as classes } from '@mezzanine-ui/core/form';
import clsx from 'clsx';
import type { FormGroupProps } from './form-group.types';

/**
 * 表單欄位群組：一個標題加上一組欄位。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznFormGroup } from '@mezzanine-ui/vue/form';
 * <\/script>
 *
 * <template>
 *   <MznFormGroup title="基本資料">
 *     <MznFormField label="姓名"><MznInput /></MznFormField>
 *   </MznFormGroup>
 * </template>
 * ```
 *
 * @see MznFormField 群組裡的欄位容器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<FormGroupProps>(), {
  fieldsContainerClassName: undefined,
});

defineSlots<{
  /** The group's fields. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const hostClasses = computed((): string =>
  clsx(classes.host, attrs.class as string),
);

const fieldsContainerClasses = computed((): string =>
  clsx(classes.fieldsContainer, props.fieldsContainerClassName),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const titleClass = classes.title;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <div :class="titleClass">{{ title }}</div>
    <div :class="fieldsContainerClasses"><slot /></div>
  </div>
</template>
