// packages/react/src/Form/FormField.tsx
import { forwardRef } from 'react';
import {
  ControlFieldSlotColumns,
  ControlFieldSlotLayout,
  formFieldClasses as classes,
  FormFieldCounterColor,
  FormFieldDensity,
  FormFieldLabelSpacing,
  FormFieldLayout,
} from '@mezzanine-ui/core/form';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { FormControl, FormControlContext } from './FormControlContext';
import { FormLabel } from './index';
import { IconDefinition } from '@mezzanine-ui/icons';
import { SeverityWithInfo } from '@mezzanine-ui/system/severity';
import FormHintText from './FormHintText';

export interface FormFieldProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * The counter text to display in the form field.
   * Typically used to show character count or remaining characters.
   */
  counter?: string;
  /**
   * The color of the counter text.
   * @default FormFieldCounterColor.INFO
   */
  counterColor?: FormFieldCounterColor;
  /**
   * The number of equal-width columns in the control field slot.
   * When set to 2, 3, or 4, children are arranged in a CSS Grid row.
   */
  controlFieldSlotColumns?: ControlFieldSlotColumns;
  /**
   * The layout variant for the control field slot.
   * Controls the visual styling and appearance of the input control area.
   * @default ControlFieldSlotLayout.MAIN
   */
  controlFieldSlotLayout?: ControlFieldSlotLayout;
  /**
   * To control the field passed from children whether should be disabled.
   * The form message won't appear if disabled.
   */
  disabled?: boolean;
  /**
   * To control the field passed from children whether should be fullWidth.
   */
  fullWidth?: boolean;
  /**
   * The hint text to display below the input field.
   * Provides additional information or guidance to the user.
   */
  hintText?: string;
  /**
   * The icon to display alongside the hint text.
   */
  hintTextIcon?: IconDefinition;
  /**
   * Whether to display the hint text icon.
   * When false, neither the custom icon nor the default severity icon will be shown.
   * @default true
   */
  showHintTextIcon?: boolean;
  /**
   * The label text for the form field.
   */
  label?: string;
  /**
   * The icon to display next to the label.
   * When provided, displays an icon that shows a tooltip on hover.
   */
  labelInformationIcon?: IconDefinition;
  /**
   * The tooltip text to display when hovering over the label information icon.
   * Only shown when labelInformationIcon is provided.
   */
  labelInformationText?: string;
  /**
   * Optional marker text to display after the label.
   * Typically used to show "(optional)" or similar text.
   */
  labelOptionalMarker?: string;
  /**
   * The spacing variant for the label area.
   * Controls the padding and min-height of the label.
   * Only applicable when layout is 'horizontal' or 'stretch'.
   * Ignored when layout is 'vertical'.
   * @default FormFieldLabelSpacing.MAIN
   */
  labelSpacing?: FormFieldLabelSpacing;
  /**
   * The layout variant of the form field.
   * Controls the arrangement direction of label and input.
   * When set to 'vertical', density and labelSpacing are ignored.
   * @default FormFieldLayout.HORIZONTAL
   */
  layout?: FormFieldLayout;
  /**
   * The density variant of the form field.
   * Controls the width of label and max-width of data entry.
   * Only applicable when layout is 'horizontal' or 'stretch'.
   * Ignored when layout is 'vertical'.
   */
  density?: FormFieldDensity;
  /**
   * The name attribute for the form field.
   * Used to identify the field in form submissions and as htmlFor in the label.
   */
  name: string;
  /**
   * To control the field passed from children whether should be required.
   */
  required?: boolean;
  /**
   * The severity level of the form field.
   * Used to indicate the importance or urgency of the field.
   * @default 'info'
   */
  severity?: SeverityWithInfo;
}

/**
 * The React component for `mezzanine` form field.
 */
const FormField = forwardRef<HTMLDivElement, FormFieldProps>(
  function FormField(props, ref) {
    const {
      children,
      className,
      counter,
      counterColor,
      controlFieldSlotColumns,
      controlFieldSlotLayout = ControlFieldSlotLayout.MAIN,
      density,
      disabled = false,
      fullWidth = false,
      hintText,
      hintTextIcon,
      showHintTextIcon,
      label,
      labelInformationIcon,
      labelInformationText,
      labelOptionalMarker,
      labelSpacing = FormFieldLabelSpacing.MAIN,
      layout = FormFieldLayout.HORIZONTAL,
      name,
      required = false,
      severity = 'info',
      ...rest
    } = props;
    const formControl: FormControl = {
      disabled,
      fullWidth,
      required,
      severity,
    };

    const shouldApplyDensity = density && layout !== FormFieldLayout.VERTICAL;
    const densityClass = shouldApplyDensity
      ? classes.density(density)
      : undefined;

    const shouldApplyLabelSpacing = layout !== FormFieldLayout.VERTICAL;
    const labelSpacingClass = shouldApplyLabelSpacing
      ? classes.labelSpacing(labelSpacing)
      : undefined;

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(
          classes.host,
          classes.layout(layout),
          densityClass,
          {
            [classes.disabled]: disabled,
            [classes.fullWidth]: fullWidth,
          },
          className,
        )}
      >
        <FormControlContext.Provider value={formControl}>
          {label && (
            <FormLabel
              className={cx(classes.labelArea, labelSpacingClass)}
              htmlFor={name}
              informationIcon={labelInformationIcon}
              informationText={labelInformationText}
              labelText={label}
              optionalMarker={labelOptionalMarker}
            />
          )}
          <div className={cx(classes.dataEntry)}>
            <div
              className={cx(
                `${classes.controlFieldSlot}--${controlFieldSlotLayout}`,
                controlFieldSlotColumns && controlFieldSlotColumns > 1
                  ? classes.controlFieldSlotColumns(controlFieldSlotColumns)
                  : undefined,
              )}
            >
              {children}
            </div>
            {hintText || hintTextIcon || counter ? (
              <div
                className={cx(classes.hintTextAndCounterArea, {
                  [classes.hintTextAndCounterArea + '--align-right']:
                    !(hintText || hintTextIcon) && counter,
                })}
              >
                {(hintText || hintTextIcon) && (
                  <FormHintText
                    hintText={hintText}
                    hintTextIcon={hintTextIcon}
                    severity={severity}
                    showHintTextIcon={showHintTextIcon}
                  />
                )}
                {counter && (
                  <span
                    className={cx(
                      classes.counter,
                      classes.counterColor(
                        counterColor || FormFieldCounterColor.INFO,
                      ),
                    )}
                  >
                    {counter}
                  </span>
                )}
              </div>
            ) : null}
          </div>
        </FormControlContext.Provider>
      </div>
    );
  },
);

export default FormField;

// packages/vue/form/form-field.vue
<script setup lang="ts">
import { computed, provide, useAttrs } from 'vue';
import {
  ControlFieldSlotLayout,
  FormFieldCounterColor,
  FormFieldLabelSpacing,
  FormFieldLayout,
  formFieldClasses as classes,
} from '@mezzanine-ui/core/form';
import clsx from 'clsx';
import { formControlKey, type FormControl } from '../_internal/form-control';
import MznFormHintText from './form-hint-text.vue';
import MznFormLabel from './form-label.vue';
import type { FormFieldProps } from './form-field.types';

/**
 * 表單欄位容器，整合標籤、提示文字與錯誤狀態。
 *
 * 透過 form control 把 `disabled`、`fullWidth`、`required`、`severity` 往下傳給子元件。
 * 支援水平、垂直與延伸三種排版；`density` 與 `labelSpacing` 在垂直排版下不套用。
 * 有 `hintText`、`hintTextIcon` 或 `counter` 其中之一時才會渲染下方那一列。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznFormField } from '@mezzanine-ui/vue/form';
 * <\/script>
 *
 * <template>
 *   <MznFormField label="使用者名稱" name="username">
 *     <MznTextField />
 *   </MznFormField>
 *
 *   <MznFormField
 *     hint-text="電子郵件格式不正確"
 *     label="電子郵件"
 *     layout="vertical"
 *     severity="error"
 *   >
 *     <MznTextField />
 *   </MznFormField>
 * </template>
 * ```
 *
 * @see MznFormLabel 標籤
 * @see MznFormHintText 提示文字
 * @see MznFormGroup 欄位群組
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<FormFieldProps>(), {
  controlFieldSlotColumns: undefined,
  controlFieldSlotLayout: ControlFieldSlotLayout.MAIN,
  counter: undefined,
  counterColor: undefined,
  density: undefined,
  disabled: false,
  fullWidth: false,
  hintText: undefined,
  hintTextIcon: undefined,
  label: undefined,
  labelInformationIcon: undefined,
  labelInformationText: undefined,
  labelOptionalMarker: undefined,
  labelSpacing: FormFieldLabelSpacing.MAIN,
  layout: FormFieldLayout.HORIZONTAL,
  name: undefined,
  required: false,
  severity: 'info',
  showHintTextIcon: undefined,
});

defineSlots<{
  /** The controls this field wraps. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

provide(
  formControlKey,
  computed(
    (): FormControl => ({
      disabled: props.disabled,
      fullWidth: props.fullWidth,
      required: props.required,
      severity: props.severity,
    }),
  ),
);

const densityClass = computed((): string | undefined => {
  const shouldApplyDensity =
    props.density && props.layout !== FormFieldLayout.VERTICAL;

  return shouldApplyDensity ? classes.density(props.density!) : undefined;
});

const labelSpacingClass = computed((): string | undefined =>
  props.layout !== FormFieldLayout.VERTICAL
    ? classes.labelSpacing(props.labelSpacing)
    : undefined,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.layout(props.layout),
    densityClass.value,
    {
      [classes.disabled]: props.disabled,
      [classes.fullWidth]: props.fullWidth,
    },
    attrs.class as string,
  ),
);

const labelClasses = computed((): string =>
  clsx(classes.labelArea, labelSpacingClass.value),
);

const controlFieldSlotClasses = computed((): string =>
  clsx(
    `${classes.controlFieldSlot}--${props.controlFieldSlotLayout}`,
    props.controlFieldSlotColumns
      ? classes.controlFieldSlotColumns(props.controlFieldSlotColumns)
      : undefined,
  ),
);

const showHintTextAndCounterArea = computed((): boolean =>
  Boolean(props.hintText || props.hintTextIcon || props.counter),
);

const showHintText = computed((): boolean =>
  Boolean(props.hintText || props.hintTextIcon),
);

const hintTextAndCounterAreaClasses = computed((): string =>
  clsx(classes.hintTextAndCounterArea, {
    [`${classes.hintTextAndCounterArea}--align-right`]:
      !showHintText.value && props.counter,
  }),
);

const counterClasses = computed((): string =>
  clsx(
    classes.counter,
    classes.counterColor(props.counterColor || FormFieldCounterColor.INFO),
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const dataEntryClass = classes.dataEntry;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <MznFormLabel
      v-if="label"
      :class="labelClasses"
      :for="name"
      :information-icon="labelInformationIcon"
      :information-text="labelInformationText"
      :label-text="label"
      :optional-marker="labelOptionalMarker"
    />
    <div :class="dataEntryClass">
      <div :class="controlFieldSlotClasses"><slot /></div>
      <div
        v-if="showHintTextAndCounterArea"
        :class="hintTextAndCounterAreaClasses"
      >
        <MznFormHintText
          v-if="showHintText"
          :hint-text="hintText"
          :hint-text-icon="hintTextIcon"
          :severity="severity"
          :show-hint-text-icon="showHintTextIcon"
        />
        <span v-if="counter" :class="counterClasses">{{ counter }}</span>
      </div>
    </div>
  </div>
</template>
