// packages/vue/date-picker/date-picker.vue
<script setup lang="ts">
import { computed, ref, useAttrs, watch } from 'vue';
import type { ComponentPublicInstance } from 'vue';
import {
  getDefaultModeFormat,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import { pickerClasses } from '@mezzanine-ui/core/picker';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { resolveElement } from '../_internal/resolve-element';
import { useCalendarContext } from '../calendar/calendar-context';
import MznIcon from '../icon/icon.vue';
import MznPickerTrigger from '../picker/picker-trigger.vue';
import { usePickerDocumentEventClose } from '../picker/use-picker-document-event-close';
import { usePickerValue } from '../picker/use-picker-value';
import MznDatePickerCalendar from './date-picker-calendar.vue';
import type { DatePickerProps } from './date-picker.types';

/**
 * 日期選擇器，點擊輸入框或日曆圖示開啟日曆浮層。
 *
 * 支援 `day`、`week`、`month`、`quarter`、`half-year`、`year` 六種模式，
 * 可用 `isDateDisabled` 等 predicate 限制可選範圍；輸入框本身是遮罩輸入，
 * 不符合限制的輸入會在失焦時清掉。受控（`value`）與非受控（`defaultValue`）皆可。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDatePicker } from '@mezzanine-ui/vue/date-picker';
 * <\/script>
 *
 * <template>
 *   <MznDatePicker :value="value" @change="onChange" />
 *   <MznDatePicker mode="month" :is-month-disabled="isPast" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznCalendar 日曆本體
 * @see MznTimePicker 時間選擇器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DatePickerProps>(), {
  calendarProps: undefined,
  clearable: true,
  defaultValue: undefined,
  disableOnDoubleNext: undefined,
  disableOnDoublePrev: undefined,
  disableOnNext: undefined,
  disableOnPrev: undefined,
  disabled: false,
  disabledMonthSwitch: false,
  disabledYearSwitch: false,
  displayMonthLocale: undefined,
  error: false,
  errorMessages: undefined,
  fadeProps: undefined,
  format: undefined,
  fullWidth: false,
  hoverValue: undefined,
  inputProps: undefined,
  isDateDisabled: undefined,
  isHalfYearDisabled: undefined,
  isMonthDisabled: undefined,
  isQuarterDisabled: undefined,
  isWeekDisabled: undefined,
  isYearDisabled: undefined,
  mode: 'day',
  placeholder: undefined,
  popperProps: undefined,
  readOnly: undefined,
  referenceDate: undefined,
  required: false,
  validate: undefined,
  value: undefined,
});

const emit = defineEmits<{
  calendarToggle: [open: boolean];
  change: [target?: DateType];
  hover: [date: DateType];
  leave: [];
}>();

defineSlots<{
  /** The trigger's prefix. */
  prefix?: () => unknown;
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const format = computed(
  (): string => props.format || getDefaultModeFormat(props.mode),
);

/**
 * Validate date value against disabled constraints based on mode.
 * Returns true if valid, false if the date is disabled.
 */
function validateDate(isoDate: string): boolean {
  switch (props.mode) {
    case 'day':
      return !props.isDateDisabled?.(isoDate);
    case 'week':
      return !props.isWeekDisabled?.(isoDate);
    case 'month':
      return !props.isMonthDisabled?.(isoDate);
    case 'quarter':
      return !props.isQuarterDisabled?.(isoDate);
    case 'year':
      return !props.isYearDisabled?.(isoDate);
    case 'half-year':
      return !props.isHalfYearDisabled?.(isoDate);
    default:
      return true;
  }
}

/** Calender display control */
const open = ref(false);

function onCalendarToggle(currentOpen: boolean): void {
  if (props.readOnly) return;

  emit('calendarToggle', currentOpen);
  open.value = currentOpen;
}

function onFocus(): void {
  if (props.readOnly) return;

  onCalendarToggle(true);
}

/** Value and change handlers */
const trigger = ref<InstanceType<typeof MznPickerTrigger> | null>(null);
const pickerCalendar = ref<InstanceType<typeof MznDatePickerCalendar> | null>(
  null,
);
const inputRef = computed(
  (): HTMLInputElement | null => trigger.value?.input ?? null,
);
const anchorRef = computed((): HTMLElement | null =>
  resolveElement(trigger.value as ComponentPublicInstance | null),
);
const calendarRef = computed(
  (): HTMLElement | null => pickerCalendar.value?.element ?? null,
);

const {
  inputValue,
  onBlur,
  onChange,
  onInputChange,
  onKeydown,
  value: internalValue,
} = usePickerValue({
  defaultValue: props.defaultValue,
  format,
  inputRef,
  value: () => props.value,
});

/** Bind close control to handlers */
function onCalendarChange(val: DateType): void {
  onChange(val);
  emit('change', val);
  onCalendarToggle(false);
}

function onKeyDownWithCloseControl(event: KeyboardEvent): void {
  onKeydown(event);

  if (event.key === 'Enter' && !isImeComposing(event)) {
    emit('change', internalValue.value);
    onCalendarToggle(false);
  }
}

/** Hover preview value for calendar */
const hoverDate = ref<DateType | undefined>(undefined);

/** using internal reference date */
const referenceDate = ref<DateType>(
  props.referenceDate || props.defaultValue || calendar.value.getNow(),
);

watch(internalValue, (value) => {
  if (value) {
    referenceDate.value = value;
  }
});

/** Resolve input props */
const inputSize = computed(
  (): number | string => props.inputProps?.size ?? format.value.length + 2,
);

const resolvedInputProps = computed(() => ({
  ...props.inputProps,
  size: inputSize.value,
  onBlur,
  onFocus,
  onKeydown: onKeyDownWithCloseControl,
}));

/** Clear handler */
function onClear(): void {
  onChange(undefined);
  emit('change', undefined);
}

/** Blur, click away and key down close */
function onClose(): void {
  onChange(props.value);
  onCalendarToggle(false);
}

function onChangeClose(): void {
  emit('change', internalValue.value);
  onCalendarToggle(false);
}

usePickerDocumentEventClose({
  anchorRef,
  lastElementRefInFlow: inputRef,
  onChangeClose,
  onClose,
  open,
  popperRef: calendarRef,
});

/** Icon */
function onIconClick(event: MouseEvent): void {
  event.stopPropagation();

  if (open.value) {
    onChange(props.value);
  }

  onCalendarToggle(!open.value);
}

function handleTriggerChange(value: string): void {
  onInputChange({ target: { value } } as unknown as Event);
  onCalendarChange(value);
  onCalendarToggle(true);
}

const hoverDisplayValue = computed((): string | undefined =>
  open.value && !inputValue.value && hoverDate.value
    ? (calendar.value.formatToString(
        calendar.value.locale,
        hoverDate.value,
        format.value,
      ) ?? undefined)
    : undefined,
);

const anchorGetter = (): HTMLElement | null => anchorRef.value;
const hostDateClass = pickerClasses.hostDate;
</script>

<template>
  <MznPickerTrigger
    ref="trigger"
    v-bind="attrs"
    :class="hostDateClass"
    :clearable="clearable"
    :disabled="disabled"
    :error="error"
    :error-messages="errorMessages"
    :force-show-clearable="!!internalValue"
    :format="format"
    :full-width="fullWidth"
    :hide-suffix-when-clearable="clearable"
    :hover-value="hoverDisplayValue"
    :input-props="resolvedInputProps"
    :placeholder="placeholder"
    :read-only="readOnly"
    :required="required"
    :size="size"
    :validate="validateDate"
    :value="inputValue"
    :warning="warning"
    @change="handleTriggerChange"
    @clear="onClear"
  >
    <template v-if="$slots.prefix" #prefix><slot name="prefix" /></template>
    <template #suffix>
      <MznIcon
        aria-label="Open calendar"
        :icon="CalendarIcon"
        v-on="readOnly ? {} : { click: onIconClick }"
      />
    </template>
  </MznPickerTrigger>
  <MznDatePickerCalendar
    ref="pickerCalendar"
    :anchor="anchorGetter"
    :calendar-props="calendarProps"
    :disable-on-double-next="disableOnDoubleNext"
    :disable-on-double-prev="disableOnDoublePrev"
    :disable-on-next="disableOnNext"
    :disable-on-prev="disableOnPrev"
    :disabled-month-switch="disabledMonthSwitch"
    :disabled-year-switch="disabledYearSwitch"
    :display-month-locale="displayMonthLocale"
    :fade-props="fadeProps"
    :is-date-disabled="isDateDisabled"
    :is-half-year-disabled="isHalfYearDisabled"
    :is-month-disabled="isMonthDisabled"
    :is-quarter-disabled="isQuarterDisabled"
    :is-week-disabled="isWeekDisabled"
    :is-year-disabled="isYearDisabled"
    :mode="mode"
    :open="open"
    :popper-props="popperProps"
    :reference-date="referenceDate"
    :value="internalValue"
    @change="onCalendarChange"
    @hover="
      (date) => {
        hoverDate = date;
        emit('hover', date);
      }
    "
    @leave="
      () => {
        hoverDate = undefined;
        emit('leave');
      }
    "
  />
</template>

// packages/react/src/DatePicker/DatePicker.tsx
'use client';

import {
  useState,
  useRef,
  useCallback,
  useMemo,
  useEffect,
  MouseEventHandler,
  KeyboardEventHandler,
  FocusEventHandler,
  forwardRef,
} from 'react';
import { DateType, getDefaultModeFormat } from '@mezzanine-ui/core/calendar';
import { pickerClasses } from '@mezzanine-ui/core/picker';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { useCalendarContext } from '../Calendar';
import { cx } from '../utils/cx';
import DatePickerCalendar, {
  DatePickerCalendarProps,
} from './DatePickerCalendar';
import {
  PickerTrigger,
  PickerTriggerProps,
  usePickerDocumentEventClose,
  usePickerValue,
} from '../Picker';
import Icon from '../Icon';
import { useComposeRefs } from '../hooks/useComposeRefs';

export interface DatePickerProps
  extends Omit<
      DatePickerCalendarProps,
      | 'anchor'
      | 'calendarRef'
      | 'disableOnDoubleNext'
      | 'disableOnDoublePrev'
      | 'onChange'
      | 'open'
      | 'referenceDate'
      | 'updateReferenceDate'
    >,
    Omit<
      PickerTriggerProps,
      | 'defaultValue'
      | 'format'
      | 'inputRef'
      | 'onChange'
      | 'onClear'
      | 'onClick'
      | 'onIconClick'
      | 'onKeyDown'
      | 'value'
    > {
  /**
   * Default value for date picker.
   */
  defaultValue?: DateType;
  /**
   * Disabled "double next" button on calendar controls
   * @default false
   */
  disableOnDoubleNext?: boolean;
  /**
   * Disabled "double prev" button on calendar controls
   * @default false
   */
  disableOnDoublePrev?: boolean;
  /**
   * The format for displaying date.
   * The length of the format must match the length of the actual generated value. For example, "gggg-wo" may cause a length mismatch when the week of year is a single digit. It is recommended to use the system's default format instead.
   */
  format?: string;
  /**
   * A function that fires when calendar toggle. Receive open status in boolean format as props.
   */
  onCalendarToggle?: (open: boolean) => void;
  /**
   * Change handler. Takes your declared `DateType` as argument.
   */
  onChange?: (target?: DateType) => void;
  /**
   * The reference date for getting calendars. Default to current time.
   */
  referenceDate?: DateType;
}

/**
 * 日期選擇器元件，透過點擊輸入框或日曆圖示開啟日曆彈出層進行日期選取。
 *
 * 必須搭配 `CalendarContext`（`CalendarConfigProvider`）使用，以提供語系與格式化函式。
 * 支援 `day`、`week`、`month`、`quarter`、`half-year`、`year` 等多種選取模式，
 * 可透過 `isDateDisabled` 等相關 props 限制可選日期範圍，並支援受控（`value`）
 * 與非受控（`defaultValue`）兩種使用方式。
 *
 * @example
 * ```tsx
 * import DatePicker from '@mezzanine-ui/react/DatePicker';
 * import CalendarConfigProvider from '@mezzanine-ui/react/CalendarConfigProvider';
 *
 * // 基本用法（需包覆在 CalendarConfigProvider 內）
 * <CalendarConfigProvider methods={...}>
 *   <DatePicker onChange={(date) => console.log(date)} />
 * </CalendarConfigProvider>
 *
 * // 受控用法
 * const [date, setDate] = useState<DateType>();
 * <CalendarConfigProvider methods={...}>
 *   <DatePicker value={date} onChange={setDate} />
 * </CalendarConfigProvider>
 *
 * // 月份選取模式，禁用過去月份
 * <CalendarConfigProvider methods={...}>
 *   <DatePicker
 *     mode="month"
 *     isMonthDisabled={(iso) => iso < '2024-01'}
 *     onChange={setDate}
 *   />
 * </CalendarConfigProvider>
 * ```
 *
 * @see {@link DateRangePicker} 日期範圍選擇器元件
 * @see {@link DateTimePicker} 日期時間選擇器元件
 * @see {@link Calendar} 日曆元件
 */
const DatePicker = forwardRef<HTMLDivElement, DatePickerProps>(
  function DatePicker(props, ref) {
    const { formatToString, getNow, locale } = useCalendarContext();
    const {
      calendarProps,
      className,
      clearable = true,
      defaultValue,
      disabledMonthSwitch = false,
      disableOnNext,
      disableOnPrev,
      disableOnDoubleNext,
      disableOnDoublePrev,
      disabledYearSwitch = false,
      disabled = false,
      displayMonthLocale,
      error = false,
      errorMessages,
      fadeProps,
      format: formatProp,
      fullWidth = false,
      inputProps,
      isDateDisabled,
      isMonthDisabled,
      isWeekDisabled,
      isYearDisabled,
      isQuarterDisabled,
      isHalfYearDisabled,
      mode = 'day',
      onCalendarToggle: onCalendarToggleProp,
      onChange: onChangeProp,
      placeholder,
      popperProps,
      prefix,
      readOnly,
      referenceDate: referenceDateProp,
      required = false,
      size,
      value: valueProp,
      ...restTriggerProps
    } = props;
    const format = formatProp || getDefaultModeFormat(mode);
    const {
      onBlur: onBlurProp,
      onKeyDown: onKeyDownProp,
      onFocus: onFocusProp,
      size: inputSize = format.length + 2,
      ...restInputProp
    } = inputProps || {};

    /**
     * Validate date value against disabled constraints based on mode.
     * Returns true if valid, false if the date is disabled.
     */
    const validateDate = useCallback(
      (isoDate: string): boolean => {
        switch (mode) {
          case 'day':
            return !isDateDisabled?.(isoDate);
          case 'week':
            return !isWeekDisabled?.(isoDate);
          case 'month':
            return !isMonthDisabled?.(isoDate);
          case 'quarter':
            return !isQuarterDisabled?.(isoDate);
          case 'year':
            return !isYearDisabled?.(isoDate);
          case 'half-year':
            return !isHalfYearDisabled?.(isoDate);
          default:
            return true;
        }
      },
      [
        isDateDisabled,
        isHalfYearDisabled,
        isMonthDisabled,
        isQuarterDisabled,
        isWeekDisabled,
        isYearDisabled,
        mode,
      ],
    );

    /** Calender display control */
    const [open, setOpen] = useState(false);
    const preventOpen = readOnly;
    const onCalendarToggle = useCallback(
      (currentOpen: boolean) => {
        if (!preventOpen) {
          if (onCalendarToggleProp) {
            onCalendarToggleProp(currentOpen);
          }

          setOpen(currentOpen);
        }
      },
      [onCalendarToggleProp, preventOpen],
    );

    const onFocus = useMemo<
      FocusEventHandler<HTMLInputElement> | undefined
    >(() => {
      if (readOnly) {
        return undefined;
      }

      return (event) => {
        if (onFocusProp) {
          onFocusProp(event);
        }

        onCalendarToggle(true);
      };
    }, [onCalendarToggle, onFocusProp, readOnly]);

    /** Value and change handlers */
    const inputRef = useRef<HTMLInputElement>(null);
    const {
      inputValue,
      onBlur,
      onChange,
      onInputChange,
      onKeyDown,
      value: internalValue,
    } = usePickerValue({
      defaultValue,
      format,
      inputRef,
      value: valueProp,
    });

    /** Bind close control to handlers */
    const onCalendarChange = (val: DateType) => {
      onChange(val);
      onChangeProp?.(val);
      onCalendarToggle(false);
    };

    const onKeyDownWithCloseControl = useCallback<
      KeyboardEventHandler<HTMLInputElement>
    >(
      (event) => {
        onKeyDown(event);

        if (onKeyDownProp) {
          onKeyDownProp(event);
        }

        if (event.key === 'Enter' && !isImeComposing(event)) {
          onChangeProp?.(internalValue);
          onCalendarToggle(false);
        }
      },
      [internalValue, onCalendarToggle, onChangeProp, onKeyDown, onKeyDownProp],
    );

    /** Hover preview value for calendar */
    const [hoverDate, setHoverDate] = useState<DateType | undefined>(undefined);

    /** using internal reference date */
    const [referenceDate, setReferenceDate] = useState(
      referenceDateProp || defaultValue || getNow(),
    );

    useEffect(() => {
      if (internalValue) {
        setReferenceDate(internalValue);
      }
    }, [internalValue]);

    /** Resolve input props */
    const onResolvedBlur = useCallback<FocusEventHandler<HTMLInputElement>>(
      (event) => {
        if (onBlurProp) {
          onBlurProp(event);
        }

        onBlur(event);
      },
      [onBlur, onBlurProp],
    );

    const resolvedInputProps = {
      ...restInputProp,
      size: inputSize,
      onFocus,
      onKeyDown: onKeyDownWithCloseControl,
      onBlur: onResolvedBlur,
    };

    /** Popper positioning */
    const anchorRef = useRef<HTMLDivElement>(null);
    const triggerComposedRef = useComposeRefs([ref, anchorRef]);
    const calendarRef = useRef<HTMLDivElement>(null);

    /** Clear handler */
    const onClear = useCallback<MouseEventHandler<HTMLInputElement>>(() => {
      onChange(undefined);
      onChangeProp?.(undefined);
    }, [onChange, onChangeProp]);

    /** Blur, click away and key down close */
    const onClose = () => {
      onChange(valueProp);

      onCalendarToggle(false);
    };

    const onChangeClose = () => {
      onChangeProp?.(internalValue);

      onCalendarToggle(false);
    };

    usePickerDocumentEventClose({
      open,
      anchorRef,
      popperRef: calendarRef,
      lastElementRefInFlow: inputRef,
      onClose,
      onChangeClose,
    });

    /** Icon */
    const onIconClick: MouseEventHandler<HTMLElement> = (e) => {
      e.stopPropagation();

      if (open) {
        onChange(valueProp);
      }

      onCalendarToggle(!open);
    };

    const suffixActionIcon = (
      <Icon
        aria-label="Open calendar"
        icon={CalendarIcon}
        onClick={readOnly ? undefined : onIconClick}
      />
    );

    const hoverDisplayValue =
      open && !inputValue && hoverDate
        ? (formatToString(locale, hoverDate, format) ?? undefined)
        : undefined;

    return (
      <>
        <PickerTrigger
          {...restTriggerProps}
          ref={triggerComposedRef}
          className={cx(pickerClasses.hostDate, className)}
          clearable={clearable}
          disabled={disabled}
          error={error}
          forceShowClearable={!!internalValue}
          hideSuffixWhenClearable={clearable}
          errorMessages={errorMessages}
          format={format}
          fullWidth={fullWidth}
          hoverValue={hoverDisplayValue}
          inputProps={resolvedInputProps}
          inputRef={inputRef}
          onChange={(e) => {
            onInputChange(e);
            onCalendarChange(e.target.value);
            onCalendarToggle(true);
          }}
          onClear={onClear}
          onFocus={() => onCalendarToggle(true)}
          placeholder={placeholder}
          prefix={prefix}
          readOnly={readOnly}
          required={required}
          size={size}
          suffix={suffixActionIcon}
          validate={validateDate}
          value={inputValue}
        />
        <DatePickerCalendar
          ref={calendarRef}
          anchor={anchorRef}
          calendarProps={calendarProps}
          disabledMonthSwitch={disabledMonthSwitch}
          disableOnNext={disableOnNext}
          disableOnPrev={disableOnPrev}
          disableOnDoubleNext={disableOnDoubleNext}
          disableOnDoublePrev={disableOnDoublePrev}
          disabledYearSwitch={disabledYearSwitch}
          displayMonthLocale={displayMonthLocale}
          fadeProps={fadeProps}
          isDateDisabled={isDateDisabled}
          isMonthDisabled={isMonthDisabled}
          isWeekDisabled={isWeekDisabled}
          isQuarterDisabled={isQuarterDisabled}
          isYearDisabled={isYearDisabled}
          isHalfYearDisabled={isHalfYearDisabled}
          mode={mode}
          onChange={onCalendarChange}
          onHover={setHoverDate}
          onLeave={() => setHoverDate(undefined)}
          open={open}
          popperProps={popperProps}
          referenceDate={referenceDate}
          value={internalValue}
        />
      </>
    );
  },
);

export default DatePicker;
