// packages/react/src/Pagination/Pagination.tsx
import {
  forwardRef,
  DetailedHTMLProps,
  HTMLAttributes,
  ReactNode,
} from 'react';
import { paginationClasses as classes } from '@mezzanine-ui/core/pagination';
import PaginationItem, { PaginationItemProps } from './PaginationItem';
import PaginationJumper from './PaginationJumper';
import PaginationPageSize, {
  PaginationPageSizeProps,
} from './PaginationPageSize';
import { usePagination } from './usePagination';
import { cx } from '../utils/cx';
import Typography from '../Typography';

export interface PaginationProps
  extends Omit<
    DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement>,
    'onChange'
  > {
  /**
   * Number of always visible pages at the beginning and end.
   * @default 1
   */
  boundaryCount?: number;
  /**
   * The text displayed in the jumper `button` content.
   */
  buttonText?: string;
  /**
   * The current page number.
   * @default 1
   */
  current?: number;
  /**
   * If `true`, the fields are disabled.
   */
  disabled?: true;
  /**
   * The hint text displayed in front of jumper `input`.
   */
  hintText?: string;
  /**
   * The placeholder displayed in the jumper input before the user enters a value.
   */
  inputPlaceholder?: string;
  /**
   * Render the item.
   * @param {PaginationItemProps} item The props to spread on a PaginationItem.
   * @returns {ReactNode}
   * @default (item) => <PaginationItem {...item} />
   */
  itemRender?: (item: PaginationItemProps) => ReactNode;
  /**
   * Callback fired when the page is changed.
   * @param {number} page The active page number.
   */
  onChange?: (page: number) => void;
  /**
   * Callback fired when the page size is changed.
   * @param {number} pageSize The new page size.
   */
  onChangePageSize?: PaginationPageSizeProps['onChange'];
  /**
   * Number of items per page.
   * @default 10
   */
  pageSize?: PaginationPageSizeProps['value'];
  /**
   * Label displayed before page size selector.
   */
  pageSizeLabel?: PaginationPageSizeProps['label'];
  /**
   * Page size options to render.
   */
  pageSizeOptions?: PaginationPageSizeProps['options'];
  /**
   * Render custom result summary.
   * @param {number} from Start index of current page.
   * @param {number} to End index of current page.
   * @param {number} total Total number of items.
   * @returns {string}
   * @example (from, to, total) => `目前顯示 ${from}-${to} 筆，共 ${total} 筆資料`
   */
  renderResultSummary?: (from: number, to: number, total: number) => string;
  /**
   * Render custom page size option name.
   */
  renderPageSizeOptionName?: PaginationPageSizeProps['renderOptionName'];
  /**
   * If `true`, show jumper.
   * @default false
   */
  showJumper?: boolean;
  /**
   * If `true`, show page size options.
   * @default false
   */
  showPageSizeOptions?: boolean;
  /**
   * Number of always visible pages before and after the current page.
   * @default 1
   */
  siblingCount?: number;
  /**
   * Total number of items.
   * @default 0
   */
  total?: number;
}

/**
 * The react component for `mezzanine` pagination.
 */
const Pagination = forwardRef<HTMLElement, PaginationProps>((props, ref) => {
  const {
    boundaryCount = 1,
    buttonText,
    className,
    current = 1,
    disabled,
    hintText,
    inputPlaceholder,
    itemRender = (item) => <PaginationItem {...item} />,
    onChange,
    onChangePageSize,
    pageSize = 10,
    pageSizeLabel,
    pageSizeOptions,
    renderPageSizeOptionName,
    renderResultSummary,
    showJumper = false,
    showPageSizeOptions = false,
    siblingCount = 1,
    total = 0,
    ...rest
  } = props;

  const { items } = usePagination({
    boundaryCount,
    current,
    disabled,
    onChange,
    pageSize,
    siblingCount,
    total,
  });

  return (
    <nav
      {...rest}
      ref={ref}
      aria-label="pagination navigation"
      className={cx(classes.host, className)}
    >
      {renderResultSummary && (
        <Typography variant="label-primary">
          {renderResultSummary(
            pageSize * (current - 1) + 1,
            Math.min(pageSize * current, total),
            total,
          )}
        </Typography>
      )}

      <ul className={classes.container}>
        {showPageSizeOptions && (
          <li className={classes.pageSize}>
            <PaginationPageSize
              disabled={disabled}
              label={pageSizeLabel}
              onChange={onChangePageSize}
              options={pageSizeOptions}
              renderOptionName={renderPageSizeOptionName}
              value={pageSize}
            />
          </li>
        )}
        <li>
          <ul className={classes.itemList}>
            {items.map((item, index) => (
              <li className={classes.item} key={index}>
                {itemRender(item)}
              </li>
            ))}
          </ul>
        </li>
        {showJumper && (
          <li className={classes.jumper}>
            <PaginationJumper
              buttonText={buttonText}
              disabled={disabled}
              hintText={hintText}
              inputPlaceholder={inputPlaceholder}
              onChange={onChange}
              pageSize={pageSize}
              total={total}
            />
          </li>
        )}
      </ul>
    </nav>
  );
});

export default Pagination;

// packages/vue/pagination/pagination.vue
<script setup lang="ts">
import { computed, h } from 'vue';
import type { VNodeChild } from 'vue';
import { paginationClasses as classes } from '@mezzanine-ui/core/pagination';
import MznTypography from '../typography/typography.vue';
import MznPaginationItem from './pagination-item.vue';
import MznPaginationJumper from './pagination-jumper.vue';
import MznPaginationPageSize from './pagination-page-size.vue';
import { usePagination } from './use-pagination';
import type { PaginationItem } from './use-pagination';
import type { PaginationProps } from './pagination.types';

/**
 * 分頁導覽列：頁碼、跳頁輸入框與每頁筆數選擇器。
 *
 * 給 `total` 與 `pageSize` 就會算出總頁數並排出頁碼；`boundaryCount` 決定首尾
 * 一定看得到幾頁，`siblingCount` 決定目前頁兩側各留幾頁，中間放省略號。
 * `showJumper` 與 `showPageSizeOptions` 分別開啟跳頁欄與每頁筆數選擇器。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznPagination } from '@mezzanine-ui/vue/pagination';
 * <\/script>
 *
 * <template>
 *   <MznPagination :current="page" :total="100" @change="page = $event" />
 *
 *   <MznPagination
 *     button-text="確認"
 *     hint-text="前往"
 *     show-jumper
 *     :total="500"
 *     @change="page = $event"
 *   />
 * </template>
 * ```
 *
 * @see usePagination 只要分頁邏輯時的 composable
 * @see MznPaginationItem 每一個頁碼項目
 */
const props = withDefaults(defineProps<PaginationProps>(), {
  boundaryCount: 1,
  buttonText: undefined,
  current: 1,
  disabled: undefined,
  hintText: undefined,
  inputPlaceholder: undefined,
  itemRender: (item: PaginationItem) => h(MznPaginationItem, item),
  pageSize: 10,
  pageSizeLabel: undefined,
  pageSizeOptions: undefined,
  renderPageSizeOptionName: undefined,
  renderResultSummary: undefined,
  showJumper: false,
  showPageSizeOptions: false,
  siblingCount: 1,
  total: 0,
});

const emit = defineEmits<{
  change: [page: number];
  changePageSize: [pageSize: number];
}>();

const { items } = usePagination({
  boundaryCount: () => props.boundaryCount,
  current: () => props.current,
  disabled: () => props.disabled,
  onChange: (page) => emit('change', page),
  pageSize: () => props.pageSize,
  siblingCount: () => props.siblingCount,
  total: () => props.total,
});

const resultSummary = computed((): string | undefined =>
  props.renderResultSummary?.(
    props.pageSize * (props.current - 1) + 1,
    Math.min(props.pageSize * props.current, props.total),
    props.total,
  ),
);

const renderedItems = computed((): VNodeChild[] =>
  items.value.map((item) => props.itemRender(item)),
);

const containerClass = classes.container;
const itemClass = classes.item;
const itemListClass = classes.itemList;
const jumperClass = classes.jumper;
const pageSizeClass = classes.pageSize;
const resultSummaryClass = classes.resultSummary;
const hostClass = classes.host;
</script>

<template>
  <nav aria-label="pagination navigation" :class="hostClass">
    <MznTypography
      v-if="renderResultSummary"
      :class="resultSummaryClass"
      variant="label-primary"
    >
      {{ resultSummary }}
    </MznTypography>
    <li v-if="showPageSizeOptions" :class="pageSizeClass">
      <MznPaginationPageSize
        :disabled="disabled"
        :label="pageSizeLabel"
        :options="pageSizeOptions"
        :render-option-name="renderPageSizeOptionName"
        :value="pageSize"
        @change="emit('changePageSize', $event)"
      />
    </li>

    <ul :class="containerClass">
      <li>
        <ul :class="itemListClass">
          <li
            v-for="(item, index) in renderedItems"
            :key="index"
            :class="itemClass"
          >
            <component :is="() => item" />
          </li>
        </ul>
      </li>
      <li v-if="showJumper" :class="jumperClass">
        <MznPaginationJumper
          :button-text="buttonText"
          :disabled="disabled"
          :hint-text="hintText"
          :input-placeholder="inputPlaceholder"
          :page-size="pageSize"
          :total="total"
          @change="emit('change', $event)"
        />
      </li>
    </ul>
  </nav>
</template>
