// packages/ng/pagination/pagination-page-size.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { paginationPageSizeClasses as classes } from '@mezzanine-ui/core/pagination/paginationPageSize';
import { DropdownOption } from '@mezzanine-ui/core/dropdown';
import { MznSelect } from '@mezzanine-ui/ng/select';
import { MznTypography } from '@mezzanine-ui/ng/typography';

/**
 * 每頁筆數選擇器，透過下拉選單讓使用者切換每頁顯示筆數。
 *
 * 等效 React 的 `PaginationPageSize` 子元件。
 *
 * @example
 * ```html
 * import { MznPaginationPageSize } from '@mezzanine-ui/ng/pagination';
 *
 * <div mznPaginationPageSize
 *   label="每頁顯示："
 *   [options]="[10, 20, 50, 100]"
 *   [value]="pageSize"
 *   (pageSizeChanged)="onPageSizeChange($event)"
 * ></div>
 * ```
 */
@Component({
  selector: '[mznPaginationPageSize]',
  standalone: true,
  imports: [FormsModule, MznSelect, MznTypography],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
    '[attr.disabled]': 'null',
    '[attr.label]': 'null',
    '[attr.options]': 'null',
    '[attr.renderOptionName]': 'null',
    '[attr.value]': 'null',
  },
  template: `
    @if (label()) {
      <div mznTypography variant="label-primary" [ellipsis]="true">{{
        label()
      }}</div>
    }
    <div
      mznSelect
      size="sub"
      [class]="selectClass"
      [disabled]="disabled()"
      [options]="selectOptions()"
      [ngModel]="currentValueId()"
      (change)="onSelectionChange($event)"
    ></div>
  `,
})
export class MznPaginationPageSize {
  /**
   * 是否禁用。
   * @default false
   */
  readonly disabled = input(false);

  /** 選擇器前方的標籤文字。 */
  readonly label = input<string | undefined>(undefined);

  /**
   * 可選的每頁筆數選項。
   * @default [10, 20, 50, 100]
   */
  readonly options = input<ReadonlyArray<number> | undefined>(undefined);

  /**
   * 自訂每頁筆數選項名稱的渲染函式。
   * 等效 React 版 `renderOptionName` prop。
   * @example (pageSize) => `${pageSize} 筆`
   */
  readonly renderOptionName = input<((pageSize: number) => string) | undefined>(
    undefined,
  );

  /**
   * 目前的每頁筆數。
   * @default 10
   */
  readonly value = input(10);

  /** 每頁筆數變更事件。 */
  readonly pageSizeChanged = output<number>();

  protected readonly hostClass = classes.host;
  protected readonly selectClass = classes.select;

  protected readonly selectOptions = computed(
    (): ReadonlyArray<DropdownOption> => {
      const opts = this.options() ?? [10, 20, 50, 100];
      const renderFn = this.renderOptionName();

      return opts.map((n) => ({
        id: String(n),
        name: renderFn ? renderFn(n) : String(n),
      }));
    },
  );

  protected readonly currentValueId = computed((): string =>
    String(this.value()),
  );

  protected onSelectionChange(option: DropdownOption): void {
    const size = Number(option.id);

    if (!Number.isNaN(size)) {
      this.pageSizeChanged.emit(size);
    }
  }
}

// packages/vue/pagination/pagination-page-size.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { paginationPageSizeClasses as classes } from '@mezzanine-ui/core/pagination';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown';
import MznDropdown from '../dropdown/dropdown.vue';
import MznSelectTrigger from '../select/select-trigger.vue';
import MznTypography from '../typography/typography.vue';
import type { PaginationPageSizeProps } from './pagination-page-size.types';

/**
 * 分頁列左側的每頁筆數選擇器：一段標籤與一個下拉選單。
 *
 * @example
 * ```vue
 * <MznPaginationPageSize
 *   label="每頁顯示："
 *   :options="[10, 20, 50]"
 *   :value="pageSize"
 *   @change="pageSize = $event"
 * />
 * ```
 *
 * @see MznPagination showPageSizeOptions 時渲染這一段
 */
const props = withDefaults(defineProps<PaginationPageSizeProps>(), {
  disabled: false,
  label: undefined,
  options: () => [10, 20, 50, 100],
  renderOptionName: (pageSize: number) => `${pageSize}`,
  value: undefined,
});

const emit = defineEmits<{
  change: [pageSize: number];
}>();

const open = ref(false);

const currentValue = computed((): DropdownOption | undefined =>
  props.value
    ? {
        id: `${props.value}`,
        name: props.renderOptionName(props.value),
      }
    : undefined,
);

const selectOptions = computed((): DropdownOption[] =>
  props.options.map((option) => ({
    id: `${option}`,
    name: props.renderOptionName(option),
  })),
);

function dropdownOnSelect(option: DropdownOption): void {
  emit('change', Number(option.id));
  open.value = false;
}

const hostClass = classes.host;
const selectClass = classes.select;
</script>

<template>
  <div :class="hostClass">
    <MznTypography
      v-if="label"
      component="div"
      ellipsis
      variant="label-primary"
    >
      {{ label }}
    </MznTypography>
    <MznDropdown
      :disabled="disabled"
      flip
      :min-width="0"
      :open="open"
      :options="selectOptions"
      same-width
      :value="currentValue?.id"
      @select="dropdownOnSelect"
      @visibility-change="open = $event"
    >
      <template #default="triggerProps">
        <MznSelectTrigger
          v-bind="triggerProps"
          :class="selectClass"
          :disabled="disabled"
          size="sub"
          :value="currentValue"
        />
      </template>
    </MznDropdown>
  </div>
</template>
