// packages/react/src/Pagination/PaginationJumper.tsx
import {
  forwardRef,
  DetailedHTMLProps,
  HTMLAttributes,
  useState,
  KeyboardEvent,
} from 'react';
import { paginationJumperClasses as classes } from '@mezzanine-ui/core/pagination';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import Typography from '../Typography';
import Button from '../Button';
import Input from '../Input';
import { cx } from '../utils/cx';

export interface PaginationJumperProps
  extends Omit<
    DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>,
    'onChange'
  > {
  /**
   * The text displayed in the `button` content.
   */
  buttonText?: string;
  /**
   * If `true`, the pagination jumper fields are disabled.
   */
  disabled?: true;
  /**
   * The hint text displayed in front of input.
   */
  hintText?: string;
  /**
   * The placeholder displayed in the input before the user enters a value.
   */
  inputPlaceholder?: string;
  /**
   * Callback fired when the page is changed.
   * @param {number} page The active page number.
   */
  onChange?: (page: number) => void;
  /**
   * Number of items per page.
   * @default 5
   */
  pageSize?: number;
  /**
   * Total number of items.
   * @default 0
   */
  total?: number;
}

const PaginationJumper = forwardRef<HTMLDivElement, PaginationJumperProps>(
  (props, ref) => {
    const {
      buttonText,
      className,
      disabled,
      hintText,
      inputPlaceholder,
      onChange: handleChange,
      pageSize = 5,
      total = 0,
      ...rest
    } = props;

    const [value, setValue] = useState('');
    const [error, setError] = useState(false);

    const totalPages = total ? Math.ceil(total / pageSize) : 1;

    const valueValidator = () => {
      const stringToNumber = +value;
      const validNumber = !!stringToNumber;

      if (validNumber) {
        return !(stringToNumber > totalPages || stringToNumber < 1);
      }

      return false;
    };

    const handleClick = () => {
      const valid = valueValidator();

      if (valid) {
        setError(false);

        if (handleChange) {
          handleChange(+value);
          setValue('');
        }
      } else {
        setError(true);
        setValue('');
      }
    };

    const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
      if (e.key === 'Enter' && !isImeComposing(e)) {
        handleClick();
      }
    };

    return (
      <div {...rest} ref={ref} className={cx(classes.host, className)}>
        <Typography component="div" ellipsis variant="label-primary">
          {hintText}
        </Typography>
        <Input
          size="sub"
          disabled={disabled}
          error={error}
          variant="number"
          className={classes.input}
          onChange={(e) => {
            setValue(e.target.value);
          }}
          placeholder={inputPlaceholder}
          inputProps={{
            onKeyDown: handleKeyDown,
          }}
          value={value}
        />
        <Button size="sub" disabled={disabled} onClick={handleClick}>
          {buttonText}
        </Button>
      </div>
    );
  },
);

export default PaginationJumper;

// packages/vue/pagination/pagination-jumper.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { paginationJumperClasses as classes } from '@mezzanine-ui/core/pagination';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import MznButton from '../button/button.vue';
import MznInput from '../input/input.vue';
import type { InputProps } from '../input/input.types';
import MznTypography from '../typography/typography.vue';
import type { PaginationJumperProps } from './pagination-jumper.types';

/**
 * 分頁列右側的跳頁欄：一段提示文字、一個數字輸入框與一顆確認按鈕。
 *
 * 輸入超出總頁數或不是數字時，輸入框會轉成錯誤狀態並清空；按 Enter 與按下按鈕
 * 等價（輸入法組字中不會誤觸）。
 *
 * @example
 * ```vue
 * <MznPaginationJumper
 *   button-text="確認"
 *   hint-text="前往"
 *   :total="100"
 *   @change="go"
 * />
 * ```
 *
 * @see MznPagination showJumper 時渲染這一段
 */
const props = withDefaults(defineProps<PaginationJumperProps>(), {
  buttonText: undefined,
  disabled: undefined,
  hintText: undefined,
  inputPlaceholder: undefined,
  pageSize: 5,
  total: 0,
});

const emit = defineEmits<{
  change: [page: number];
}>();

const value = ref('');
const error = ref(false);

const totalPages = computed((): number =>
  props.total ? Math.ceil(props.total / props.pageSize) : 1,
);

function valueValidator(): boolean {
  const stringToNumber = +value.value;
  const validNumber = !!stringToNumber;

  if (validNumber) {
    return !(stringToNumber > totalPages.value || stringToNumber < 1);
  }

  return false;
}

function handleClick(): void {
  const valid = valueValidator();

  if (valid) {
    error.value = false;
    emit('change', +value.value);
    value.value = '';
  } else {
    error.value = true;
    value.value = '';
  }
}

function handleKeydown(event: KeyboardEvent): void {
  if (event.key === 'Enter' && !isImeComposing(event)) {
    handleClick();
  }
}

function onInputChange(event: Event): void {
  value.value = (event.target as HTMLInputElement).value;
}

const inputProps = computed((): InputProps['inputProps'] => ({
  onKeydown: handleKeydown,
}));

const hostClass = classes.host;
const inputClass = classes.input;
</script>

<template>
  <div :class="hostClass">
    <MznTypography component="div" ellipsis variant="label-primary">
      {{ hintText }}
    </MznTypography>
    <MznInput
      :class="inputClass"
      :disabled="disabled"
      :error="error"
      :input-props="inputProps"
      :placeholder="inputPlaceholder"
      size="sub"
      :value="value"
      variant="number"
      @change="onInputChange"
    />
    <MznButton :disabled="disabled" size="sub" @click="handleClick">
      {{ buttonText }}
    </MznButton>
  </div>
</template>
