// packages/react/src/Pagination/PaginationItem.tsx
import { DetailedHTMLProps, forwardRef, HTMLAttributes, Ref } from 'react';
import {
  PaginationItemType,
  paginationItemClasses as classes,
} from '@mezzanine-ui/core/pagination';

import {
  ChevronLeftIcon,
  ChevronRightIcon,
  DotHorizontalIcon,
  IconDefinition,
} from '@mezzanine-ui/icons';

import Icon from '../Icon';

import { cx } from '../utils/cx';
import Typography from '../Typography';

export type PaginationItemElement = HTMLButtonElement | HTMLDivElement;

export interface PaginationItemProps
  extends Omit<
    DetailedHTMLProps<
      HTMLAttributes<PaginationItemElement>,
      PaginationItemElement
    >,
    'ref'
  > {
  /**
   * If `true`, the pagination item is active.
   * @default false
   */
  active?: boolean;
  /**
   * If `true`, the pagination item is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * The page number.
   * @default 1
   */
  page?: number;
  /**
   * The type of pagination item.
   * @default 'page'
   */
  type?: PaginationItemType;
}

const PaginationItem = forwardRef<PaginationItemElement, PaginationItemProps>(
  (props, ref) => {
    const {
      active = false,
      className,
      disabled = false,
      page = 1,
      type = 'page',
      ...rest
    } = props;

    const icons: { [index: string]: IconDefinition } = {
      next: ChevronRightIcon,
      previous: ChevronLeftIcon,
    };

    const ButtonIcon = icons[type];

    return type === 'ellipsis' ? (
      <div
        {...rest}
        ref={ref as Ref<HTMLDivElement>}
        className={cx(
          classes.host,
          classes.ellipsis,
          {
            [classes.disabled]: disabled,
          },
          className,
        )}
      >
        <Icon icon={DotHorizontalIcon} />
      </div>
    ) : (
      <button
        {...rest}
        ref={ref as Ref<HTMLButtonElement>}
        key={page}
        disabled={disabled}
        className={cx(
          classes.host,
          classes.button,
          {
            [classes.active]: active,
            [classes.disabled]: disabled,
          },
          className,
        )}
        type="button"
      >
        {ButtonIcon && <Icon icon={ButtonIcon} />}
        {type === 'page' && (
          <Typography variant="label-primary">{page}</Typography>
        )}
      </button>
    );
  },
);

export default PaginationItem;

// packages/vue/pagination/pagination-item.vue
<script setup lang="ts">
import { computed } from 'vue';
import { paginationItemClasses as classes } from '@mezzanine-ui/core/pagination';
import {
  ChevronLeftIcon,
  ChevronRightIcon,
  DotHorizontalIcon,
} from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznTypography from '../typography/typography.vue';
import type { PaginationItemProps } from './pagination-item.types';

/**
 * 分頁列上的單一項目：頁碼、上一頁、下一頁或省略號。
 *
 * `type` 決定長相 —— `page` 顯示頁碼、`previous` / `next` 顯示箭頭、`ellipsis`
 * 顯示三個點且不是按鈕。
 *
 * @example
 * ```vue
 * <MznPaginationItem :page="3" type="page" />
 * <MznPaginationItem type="ellipsis" />
 * ```
 *
 * @see MznPagination 排出這些項目的容器
 */
const props = withDefaults(defineProps<PaginationItemProps>(), {
  active: false,
  disabled: false,
  page: 1,
  type: 'page',
});

const icons: Record<string, IconDefinition> = {
  next: ChevronRightIcon,
  previous: ChevronLeftIcon,
};

const buttonIcon = computed(
  (): IconDefinition | undefined => icons[props.type],
);

const ellipsisClasses = computed((): string =>
  clsx(classes.host, classes.ellipsis, {
    [classes.disabled]: props.disabled,
  }),
);

const buttonClasses = computed((): string =>
  clsx(classes.host, classes.button, {
    [classes.active]: props.active,
    [classes.disabled]: props.disabled,
  }),
);
</script>

<template>
  <div v-if="type === 'ellipsis'" :class="ellipsisClasses">
    <MznIcon :icon="DotHorizontalIcon" />
  </div>
  <button v-else :class="buttonClasses" :disabled="disabled" type="button">
    <MznIcon v-if="buttonIcon" :icon="buttonIcon" />
    <MznTypography v-if="type === 'page'" variant="label-primary">
      {{ page }}
    </MznTypography>
  </button>
</template>
