// packages/react/src/MultipleDatePicker/MultipleDatePicker.tsx
'use client';

import {
  calendarClasses,
  DateType,
  getDefaultModeFormat,
} from '@mezzanine-ui/core/calendar';
import {
  multipleDatePickerClasses as classes,
  MultipleDatePickerValue,
} from '@mezzanine-ui/core/multiple-date-picker';
import { CalendarIcon } from '@mezzanine-ui/icons';
import {
  forwardRef,
  MouseEventHandler,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import Calendar, {
  CalendarProps,
  useCalendarContext,
  useCalendarControls,
} from '../Calendar';
import CalendarFooterActions, { CalendarFooterActionsProps } from '../Calendar/CalendarFooterActions';
import Icon from '../Icon';
import { usePickerDocumentEventClose } from '../Picker';
import InputTriggerPopper, {
  InputTriggerPopperProps,
} from '../_internal/InputTriggerPopper';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { cx } from '../utils/cx';
import MultipleDatePickerTrigger, {
  DateValue,
  MultipleDatePickerTriggerProps,
} from './MultipleDatePickerTrigger';
import { useMultipleDatePickerValue } from './useMultipleDatePickerValue';

export interface MultipleDatePickerProps
  extends Pick<
    MultipleDatePickerTriggerProps,
    | 'className'
    | 'clearable'
    | 'disabled'
    | 'error'
    | 'fullWidth'
    | 'overflowStrategy'
    | 'prefix'
    | 'readOnly'
    | 'size'
  >,
  Pick<
    CalendarProps,
    | 'disabledMonthSwitch'
    | 'disableOnNext'
    | 'disableOnPrev'
    | 'disableOnDoubleNext'
    | 'disableOnDoublePrev'
    | 'disabledYearSwitch'
    | 'displayMonthLocale'
    | 'isDateDisabled'
  > {
  /**
   * Custom action button props. Allows overriding confirm/cancel button text and behavior.
   */
  actions?: Partial<CalendarFooterActionsProps['actions']>;
  /**
   * Other calendar props you may provide to `Calendar`.
   */
  calendarProps?: Omit<
    CalendarProps,
    | 'disableOnNext'
    | 'disableOnPrev'
    | 'disableOnDoubleNext'
    | 'disableOnDoublePrev'
    | 'displayMonthLocale'
    | 'isDateDisabled'
    | 'locale'
    | 'mode'
    | 'onChange'
    | 'onMonthControlClick'
    | 'onNext'
    | 'onDoubleNext'
    | 'onPrev'
    | 'onDoublePrev'
    | 'onYearControlClick'
    | 'referenceDate'
    | 'updateReferenceDate'
    | 'value'
  >;
  /**
   * The format for displaying date in tags.
   * @default 'YYYY-MM-DD'
   */
  format?: string;
  /**
   * Maximum number of dates that can be selected.
   */
  maxSelections?: number;
  /**
   * A function that fires when calendar toggle.
   */
  onCalendarToggle?: (open: boolean) => void;
  /**
   * Change handler. Called when user confirms the selection.
   */
  onChange?: (value: MultipleDatePickerValue) => void;
  /**
   * Placeholder text when no dates are selected.
   */
  placeholder?: string;
  /**
   * Other props you may provide to `Popper` component.
   */
  popperProps?: Omit<
    InputTriggerPopperProps,
    'anchor' | 'children' | 'fadeProps' | 'open'
  >;
  /**
   * The reference date for getting calendars. Default to current time.
   */
  referenceDate?: DateType;
  /**
   * Whether the input is required.
   * @default false
   */
  required?: boolean;
  /**
   * Controlled value - array of selected dates.
   * @default []
   */
  value?: MultipleDatePickerValue;
}

/**
 * The react component for `mezzanine` multiple date picker.
 * Allows selecting multiple dates from a calendar with manual confirmation.
 * Notice that any component related to date-picker should be used along with `CalendarContext`.
 */
const MultipleDatePicker = forwardRef<HTMLDivElement, MultipleDatePickerProps>(
  function MultipleDatePicker(props, ref) {
    const { getNow, locale } = useCalendarContext();
    const {
      actions: actionsProp,
      calendarProps,
      className,
      clearable = true,
      disabledMonthSwitch = false,
      disableOnDoubleNext,
      disableOnDoublePrev,
      disableOnNext,
      disableOnPrev,
      disabledYearSwitch = false,
      disabled = false,
      displayMonthLocale = locale,
      error = false,
      format: formatProp,
      fullWidth = false,
      isDateDisabled: isDateDisabledProp,
      maxSelections,
      onCalendarToggle: onCalendarToggleProp,
      onChange: onChangeProp,
      overflowStrategy = 'counter',
      placeholder,
      popperProps,
      prefix,
      required,
      readOnly = false,
      referenceDate: referenceDateProp,
      size = 'main',
      value = [],
    } = props;

    const format = formatProp || getDefaultModeFormat('day');
    const { className: calendarClassName, ...restCalendarProps } =
      calendarProps || {};

    // Calendar open state
    const [open, setOpen] = useState(false);
    const preventOpen = readOnly || disabled;

    const onCalendarToggle = useCallback(
      (currentOpen: boolean) => {
        if (!preventOpen) {
          setOpen(currentOpen);
          onCalendarToggleProp?.(currentOpen);
        }
      },
      [onCalendarToggleProp, preventOpen],
    );

    // Value management hook
    const {
      clearAll,
      formatDate,
      getConfirmValue,
      internalValue,
      isDateSelected,
      isMaxReached,
      removeDate,
      revertToValue,
      toggleDate,
    } = useMultipleDatePickerValue({
      format,
      maxSelections,
      value,
    });

    // Manage referenceDate internally for stable value
    const [internalReferenceDate, setInternalReferenceDate] = useState(
      () => referenceDateProp || getNow(),
    );

    // Sync referenceDate when prop changes
    useEffect(() => {
      if (referenceDateProp) {
        setInternalReferenceDate(referenceDateProp);
      }
    }, [referenceDateProp]);

    // Calendar controls - pass stable referenceDate
    const {
      currentMode,
      onMonthControlClick,
      onNext,
      onPrev,
      onDoublePrev,
      onDoubleNext,
      onYearControlClick,
      popModeStack,
      referenceDate,
      updateReferenceDate,
    } = useCalendarControls(internalReferenceDate, 'day');

    // Handle mode switching (month/year selection) with value transformation
    const createModeChangeHandler = useMemo(() => {
      return (
        transformValue?: (target: DateType, reference: DateType) => DateType,
      ) => {
        return (target: DateType) => {
          const result = transformValue
            ? transformValue(target, referenceDate)
            : target;

          updateReferenceDate(result);
          popModeStack();
        };
      };
    }, [referenceDate, updateReferenceDate, popModeStack]);

    // Convert internalValue to DateValue[] for trigger display
    const triggerValues: DateValue[] = useMemo(
      () =>
        internalValue.map((date) => ({
          date,
          id: formatDate(date),
          name: formatDate(date),
        })),
      [internalValue, formatDate],
    );

    // Handle calendar date click - toggle selection (only in day mode)
    const onCalendarDateChange = useCallback(
      (date: DateType) => {
        if (currentMode === 'day') {
          toggleDate(date);
        } else {
          // Handle month/year mode switching
          createModeChangeHandler()(date);
        }
      },
      [currentMode, toggleDate, createModeChangeHandler],
    );

    // Handle tag close - remove date
    const onTagClose = useCallback(
      (date: DateType) => {
        removeDate(date);
      },
      [removeDate],
    );

    // Handle confirm action
    const onConfirm = useCallback(() => {
      const confirmedValue = getConfirmValue();

      onChangeProp?.(confirmedValue);
      onCalendarToggle(false);
    }, [getConfirmValue, onChangeProp, onCalendarToggle]);

    // Handle cancel action
    const onCancel = useCallback(() => {
      revertToValue();
      onCalendarToggle(false);
    }, [revertToValue, onCalendarToggle]);

    // Handle clear
    const onClear = useCallback<MouseEventHandler<Element>>(
      (e) => {
        e.stopPropagation();

        clearAll();
        onChangeProp?.([]);
      },
      [clearAll, onChangeProp],
    );

    // Auto-generate actions
    const actions: CalendarFooterActionsProps['actions'] = useMemo(() => {
      const hasValue = internalValue.length > 0;

      return {
        primaryButtonProps: {
          children: 'Confirm',
          disabled: !hasValue,
          onClick: onConfirm,
          ...actionsProp?.primaryButtonProps,
        },
        secondaryButtonProps: {
          children: 'Cancel',
          onClick: onCancel,
          ...actionsProp?.secondaryButtonProps,
        },
      };
    }, [actionsProp, internalValue.length, onConfirm, onCancel]);

    // Enhanced isDateDisabled - disable unselected dates when max is reached
    const isDateDisabled = useCallback(
      (date: DateType): boolean => {
        // Check user-provided disabled function first
        if (isDateDisabledProp?.(date)) {
          return true;
        }

        // If max is reached and date is not already selected, disable it
        if (isMaxReached && !isDateSelected(date)) {
          return true;
        }

        return false;
      },
      [isDateDisabledProp, isDateSelected, isMaxReached],
    );

    // Refs for popper positioning
    const anchorRef = useRef<HTMLDivElement>(null);
    const calendarRef = useRef<HTMLDivElement>(null);
    const triggerComposedRef = useComposeRefs([ref, anchorRef]);

    // Close handlers for click-away and escape
    const onClose = useCallback(() => {
      revertToValue();
      onCalendarToggle(false);
    }, [revertToValue, onCalendarToggle]);

    const onChangeClose = useCallback(() => {
      // In manual mode, always revert on click-away (don't auto-submit)
      revertToValue();
      onCalendarToggle(false);
    }, [revertToValue, onCalendarToggle]);

    // Use a dummy ref for lastElementRefInFlow since we don't have a focusable input
    const dummyRef = useRef<HTMLElement>(null);

    usePickerDocumentEventClose({
      anchorRef,
      lastElementRefInFlow: dummyRef,
      onChangeClose,
      onClose,
      open,
      popperRef: calendarRef,
    });

    // Icon click handler
    const onIconClick: MouseEventHandler<HTMLElement> = useCallback(
      (e) => {
        e.stopPropagation();

        if (open) {
          revertToValue();
        }

        onCalendarToggle(!open);
      },
      [open, revertToValue, onCalendarToggle],
    );

    const suffixActionIcon = (
      <Icon
        aria-label="Open calendar"
        icon={CalendarIcon}
        onClick={readOnly || disabled ? undefined : onIconClick}
      />
    );

    // Trigger click handler
    const onTriggerClick: MouseEventHandler<HTMLDivElement> =
      useCallback(() => {
        if (!preventOpen && !open) {
          onCalendarToggle(true);
        }
      }, [preventOpen, open, onCalendarToggle]);

    return (
      <>
        <MultipleDatePickerTrigger
          active={open}
          className={cx(classes.host, className, {
            [classes.hostFullWidth]: fullWidth,
          })}
          clearable={clearable}
          disabled={disabled}
          error={error}
          fullWidth={fullWidth}
          onClick={onTriggerClick}
          onClear={onClear}
          onTagClose={onTagClose}
          overflowStrategy={overflowStrategy}
          placeholder={placeholder}
          prefix={prefix}
          readOnly={readOnly}
          ref={triggerComposedRef}
          required={required}
          size={size}
          suffix={suffixActionIcon}
          value={triggerValues}
        />
        <InputTriggerPopper
          {...popperProps}
          anchor={anchorRef}
          open={open}
          ref={calendarRef}
        >
          <div className={calendarClasses.host}>
            <div className={calendarClasses.mainWithFooter}>
              <Calendar
                {...restCalendarProps}
                className={cx(calendarClasses.noShadowHost, calendarClassName)}
                disabledFooterControl
                disabledMonthSwitch={disabledMonthSwitch}
                disableOnDoubleNext={disableOnDoubleNext}
                disableOnDoublePrev={disableOnDoublePrev}
                disableOnNext={disableOnNext}
                disableOnPrev={disableOnPrev}
                disabledYearSwitch={disabledYearSwitch}
                displayMonthLocale={displayMonthLocale}
                isDateDisabled={isDateDisabled}
                mode={currentMode}
                onChange={onCalendarDateChange}
                onMonthControlClick={onMonthControlClick}
                onNext={onNext}
                onDoubleNext={onDoubleNext}
                onPrev={onPrev}
                onDoublePrev={onDoublePrev}
                onYearControlClick={onYearControlClick}
                referenceDate={referenceDate}
                value={internalValue}
              />
              <CalendarFooterActions actions={actions} />
            </div>
          </div>
        </InputTriggerPopper>
      </>
    );
  },
);

export default MultipleDatePicker;

// packages/vue/multiple-date-picker/multiple-date-picker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { ComponentPublicInstance } from 'vue';
import {
  calendarClasses,
  getDefaultModeFormat,
} from '@mezzanine-ui/core/calendar';
import type { DateType } from '@mezzanine-ui/core/calendar';
import { multipleDatePickerClasses as classes } from '@mezzanine-ui/core/multiple-date-picker';
import type { MultipleDatePickerValue } from '@mezzanine-ui/core/multiple-date-picker';
import { CalendarIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { resolveElement } from '../_internal/resolve-element';
import MznInputTriggerPopper from '../_internal/input-trigger-popper.vue';
import MznCalendarFooterActions from '../calendar/calendar-footer-actions.vue';
import type { CalendarFooterActionsProps } from '../calendar/calendar-footer-actions.types';
import MznCalendar from '../calendar/calendar.vue';
import { useCalendarContext } from '../calendar/calendar-context';
import { useCalendarControls } from '../calendar/use-calendar-controls';
import MznIcon from '../icon/icon.vue';
import { usePickerDocumentEventClose } from '../picker/use-picker-document-event-close';
import MznMultipleDatePickerTrigger from './multiple-date-picker-trigger.vue';
import type { DateValue } from './multiple-date-picker-trigger.types';
import { useMultipleDatePickerValue } from './use-multiple-date-picker-value';
import type { MultipleDatePickerProps } from './multiple-date-picker.types';

/**
 * 多日期選擇器：從日曆挑選多個日期，以標籤呈現，按下確認才送出。
 *
 * 選取先寫進內部狀態，按確認才發出 `change`；取消、點擊外部或按 Escape 都會
 * 還原。`maxSelections` 達到上限後，未選取的日期會被停用。
 * 與其他日曆相關元件一樣，必須包在 MznCalendarConfigProvider 裡。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznMultipleDatePicker } from '@mezzanine-ui/vue/multiple-date-picker';
 * <\/script>
 *
 * <template>
 *   <MznMultipleDatePicker :value="dates" @change="dates = $event" />
 *   <MznMultipleDatePicker :max-selections="3" :value="dates" @change="dates = $event" />
 * </template>
 * ```
 *
 * @see MznDatePicker 單一日期的版本
 * @see useMultipleDatePickerValue 只要待確認選取邏輯時的 composable
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<MultipleDatePickerProps>(), {
  actions: undefined,
  calendarProps: undefined,
  clearable: true,
  disableOnDoubleNext: undefined,
  disableOnDoublePrev: undefined,
  disableOnNext: undefined,
  disableOnPrev: undefined,
  disabled: false,
  disabledMonthSwitch: false,
  disabledYearSwitch: false,
  displayMonthLocale: undefined,
  error: false,
  format: undefined,
  fullWidth: false,
  isDateDisabled: undefined,
  maxSelections: undefined,
  overflowStrategy: 'counter',
  placeholder: undefined,
  popperProps: undefined,
  readOnly: false,
  referenceDate: undefined,
  required: undefined,
  size: 'main',
  value: () => [],
});

const emit = defineEmits<{
  calendarToggle: [open: boolean];
  change: [value: MultipleDatePickerValue];
}>();

defineSlots<{
  /** The trigger's prefix. */
  prefix?: () => unknown;
}>();

const calendar = useCalendarContext();

const format = computed(
  (): string => props.format || getDefaultModeFormat('day'),
);

const displayMonthLocale = computed(
  (): string | undefined => props.displayMonthLocale ?? calendar.value.locale,
);

/** Calendar open state */
const open = ref(false);
const preventOpen = computed((): boolean => props.readOnly || props.disabled);

function onCalendarToggle(currentOpen: boolean): void {
  if (preventOpen.value) return;

  open.value = currentOpen;
  emit('calendarToggle', currentOpen);
}

/** Value management */
const {
  clearAll,
  formatDate,
  getConfirmValue,
  internalValue,
  isDateSelected,
  isMaxReached,
  removeDate,
  revertToValue,
  toggleDate,
} = useMultipleDatePickerValue({
  format: () => format.value,
  maxSelections: () => props.maxSelections,
  value: () => props.value,
});

/** Manage referenceDate internally for a stable value */
const internalReferenceDate = ref<DateType>(
  props.referenceDate || calendar.value.getNow(),
);

watch(
  () => props.referenceDate,
  (value) => {
    if (value) internalReferenceDate.value = value;
  },
);

const {
  currentMode,
  onMonthControlClick,
  onNext,
  onPrev,
  onDoublePrev,
  onDoubleNext,
  onYearControlClick,
  popModeStack,
  referenceDate,
  updateReferenceDate,
} = useCalendarControls(internalReferenceDate, 'day');

/** Convert the internal value to the shape the trigger displays */
const triggerValues = computed((): DateValue[] =>
  internalValue.value.map((date) => ({
    date,
    id: formatDate(date),
    name: formatDate(date),
  })),
);

/** Handle calendar date click — toggle selection (only in day mode) */
function onCalendarDateChange(date: DateType): void {
  if (currentMode.value === 'day') {
    toggleDate(date);

    return;
  }

  // Handle month/year mode switching
  updateReferenceDate(date);
  popModeStack();
}

function onConfirm(): void {
  emit('change', getConfirmValue());
  onCalendarToggle(false);
}

function onCancel(): void {
  revertToValue();
  onCalendarToggle(false);
}

function onClear(event: MouseEvent): void {
  event.stopPropagation();

  clearAll();
  emit('change', []);
}

/** Auto-generate actions */
const actions = computed((): CalendarFooterActionsProps['actions'] => {
  const hasValue = internalValue.value.length > 0;

  return {
    primaryButtonProps: {
      children: 'Confirm',
      disabled: !hasValue,
      onClick: onConfirm,
      ...props.actions?.primaryButtonProps,
    },
    secondaryButtonProps: {
      children: 'Cancel',
      onClick: onCancel,
      ...props.actions?.secondaryButtonProps,
    },
  };
});

/** Disable unselected dates once the maximum is reached */
function isDateDisabled(date: DateType): boolean {
  if (props.isDateDisabled?.(date)) return true;

  return isMaxReached.value && !isDateSelected(date);
}

/** Refs for popper positioning */
const trigger = ref<ComponentPublicInstance | null>(null);
const popper = ref<ComponentPublicInstance | null>(null);
const anchorRef = computed((): HTMLElement | null =>
  resolveElement(trigger.value),
);
const calendarRef = computed((): HTMLElement | null =>
  resolveElement(popper.value),
);

function onClose(): void {
  revertToValue();
  onCalendarToggle(false);
}

/** In manual mode, always revert on click-away (don't auto-submit) */
const dummyRef = ref<HTMLElement | null>(null);

usePickerDocumentEventClose({
  anchorRef,
  lastElementRefInFlow: dummyRef,
  onChangeClose: onClose,
  onClose,
  open,
  popperRef: calendarRef,
});

function onIconClick(event: MouseEvent): void {
  event.stopPropagation();

  if (open.value) revertToValue();

  onCalendarToggle(!open.value);
}

function onTriggerClick(): void {
  if (!preventOpen.value && !open.value) onCalendarToggle(true);
}

/**
 * Bound as an object rather than with `@click`, because React leaves the
 * handler off entirely while disabled or read-only — and an icon with a click
 * listener draws a pointer cursor.
 */
const suffixIconBindings = computed(() => ({
  'aria-label': 'Open calendar',
  icon: CalendarIcon,
  onClick: props.readOnly || props.disabled ? undefined : onIconClick,
}));

const restCalendarProps = computed(() => {
  const { class: _class, ...rest } = (props.calendarProps ?? {}) as Record<
    string,
    unknown
  >;

  return rest;
});

const calendarClassName = computed((): string =>
  clsx(
    calendarClasses.noShadowHost,
    (props.calendarProps as { class?: string } | undefined)?.class,
  ),
);

const hostClasses = computed((): string =>
  clsx(classes.host, {
    [classes.hostFullWidth]: props.fullWidth,
  }),
);

const calendarHostClass = calendarClasses.host;
const mainWithFooterClass = calendarClasses.mainWithFooter;
</script>

<template>
  <MznMultipleDatePickerTrigger
    ref="trigger"
    :active="open"
    :class="hostClasses"
    :clearable="clearable"
    :disabled="disabled"
    :error="error"
    :full-width="fullWidth"
    :overflow-strategy="overflowStrategy"
    :placeholder="placeholder"
    :read-only="readOnly"
    :required="required"
    :size="size"
    :value="triggerValues"
    @click="onTriggerClick"
    @clear="onClear"
    @tag-close="removeDate"
  >
    <!--
      Only forwarded when the consumer actually gave one: an always-present
      slot makes the text field believe it has a prefix, which changes its gap
      and renders an empty prefix element.
    -->
    <template v-if="$slots.prefix" #prefix><slot name="prefix" /></template>
    <template #suffix>
      <MznIcon v-bind="suffixIconBindings" />
    </template>
  </MznMultipleDatePickerTrigger>
  <MznInputTriggerPopper
    ref="popper"
    v-bind="popperProps"
    :anchor="anchorRef"
    :open="open"
  >
    <div :class="calendarHostClass">
      <div :class="mainWithFooterClass">
        <MznCalendar
          v-bind="restCalendarProps"
          :class="calendarClassName"
          disabled-footer-control
          :disabled-month-switch="disabledMonthSwitch"
          :disable-on-double-next="disableOnDoubleNext"
          :disable-on-double-prev="disableOnDoublePrev"
          :disable-on-next="disableOnNext"
          :disable-on-prev="disableOnPrev"
          :disabled-year-switch="disabledYearSwitch"
          :display-month-locale="displayMonthLocale"
          :is-date-disabled="isDateDisabled"
          :mode="currentMode"
          :reference-date="referenceDate"
          :value="internalValue"
          @change="onCalendarDateChange"
          @double-next="onDoubleNext"
          @double-prev="onDoublePrev"
          @month-control-click="onMonthControlClick"
          @next="onNext"
          @prev="onPrev"
          @year-control-click="onYearControlClick"
        />
        <MznCalendarFooterActions :actions="actions" />
      </div>
    </div>
  </MznInputTriggerPopper>
</template>
