// packages/ng/result-state/result-state.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import {
  resultStateClasses as classes,
  ResultStateSize,
  ResultStateType,
} from '@mezzanine-ui/core/result-state';
import {
  CheckedFilledIcon,
  DangerousFilledIcon,
  ErrorFilledIcon,
  IconDefinition,
  InfoFilledIcon,
  QuestionFilledIcon,
  WarningFilledIcon,
} from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznButtonGroup } from '@mezzanine-ui/ng/button';
import { MznIcon } from '@mezzanine-ui/ng/icon';

const iconMap: Record<ResultStateType, IconDefinition> = {
  information: InfoFilledIcon,
  success: CheckedFilledIcon,
  help: QuestionFilledIcon,
  warning: WarningFilledIcon,
  error: ErrorFilledIcon,
  failure: DangerousFilledIcon,
};

/**
 * 結果狀態元件，用於操作結果或狀態頁面的顯示。
 *
 * 根據 `type` 自動選擇對應圖示（information、success、help、warning、error、failure），
 * 搭配 `title` 及 `description` 傳遞訊息。使用 content projection 投射操作按鈕。
 *
 * @example
 * ```html
 * import { MznResultState } from '@mezzanine-ui/ng/result-state';
 *
 * <div mznResultState type="success" title="操作成功" description="您的資料已儲存" ></div>
 *
 * <div mznResultState type="error" title="操作失敗" size="sub">
 *   <button actions>重試</button>
 * </div>
 * ```
 */
@Component({
  selector: '[mznResultState]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznButtonGroup, MznIcon],
  host: {
    '[class]': 'hostClasses()',
    '[attr.description]': 'null',
    '[attr.size]': 'null',
    '[attr.title]': 'null',
    '[attr.type]': 'null',
  },
  template: `
    <div [class]="classes.container">
      <i mznIcon [class]="classes.icon" [icon]="iconDef()"></i>
      <h3 [class]="classes.title">{{ title() }}</h3>
      @if (description()) {
        <p [class]="classes.description">{{ description() }}</p>
      }
      <div mznButtonGroup [class]="classes.actions">
        <ng-content select="[actions]" />
      </div>
    </div>
  `,
})
export class MznResultState {
  protected readonly classes = classes;

  /** 描述文字，顯示在標題下方。 */
  readonly description = input<string>();

  /**
   * 元件尺寸。
   * @default 'main'
   */
  readonly size = input<ResultStateSize>('main');

  /** 結果狀態的標題文字。 */
  readonly title = input.required<string>();

  /**
   * 結果狀態類型，決定預設圖示與色彩。
   * @default 'information'
   */
  readonly type = input<ResultStateType>('information');

  protected readonly iconDef = computed(
    (): IconDefinition => iconMap[this.type()],
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.type(this.type()), classes.size(this.size())),
  );
}

// packages/react/src/ResultState/ResultState.tsx
import type {
  ResultStateSize,
  ResultStateType,
} from '@mezzanine-ui/core/result-state';
import { resultStateClasses as classes } from '@mezzanine-ui/core/result-state';
import { forwardRef, useMemo } from 'react';
import {
  CheckedFilledIcon,
  DangerousFilledIcon,
  ErrorFilledIcon,
  InfoFilledIcon,
  QuestionFilledIcon,
  WarningFilledIcon,
} from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import Button from '../Button';
import type { ButtonProps } from '../Button';
import Icon from '../Icon';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

export interface ResultStateProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * Action buttons configuration for primary and secondary actions.
   * Renders buttons in the order: secondary (left), primary (right).
   */
  actions?: {
    primaryButtonProps?: ButtonProps;
    secondaryButtonProps?: ButtonProps;
  };
  /**
   * Optional description text displayed below the title.
   * Provides additional context or details about the result state.
   */
  description?: string;
  /**
   * The size variant of the result state.
   * Controls typography, spacing, and overall dimensions.
   * @default 'main'
   */
  size?: ResultStateSize;
  /**
   * The title text for the result state.
   * This is the main heading that describes the state.
   */
  title: string;
  /**
   * The type of result state, which determines the icon and color theme.
   * @default 'information'
   */
  type?: ResultStateType;
}

const iconMap: Record<ResultStateType, IconDefinition> = {
  information: InfoFilledIcon,
  success: CheckedFilledIcon,
  help: QuestionFilledIcon,
  warning: WarningFilledIcon,
  error: ErrorFilledIcon,
  failure: DangerousFilledIcon,
};

const ResultState = forwardRef<HTMLDivElement, ResultStateProps>(
  function ResultState(props, ref) {
    const {
      actions,
      className,
      description,
      size = 'main',
      title,
      type = 'information',
      ...rest
    } = props;

    const icon = useMemo(() => iconMap[type], [type]);

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(
          classes.host,
          classes.type(type),
          classes.size(size),
          className,
        )}
      >
        <div className={classes.container}>
          <Icon className={classes.icon} icon={icon} />
          <h3 className={classes.title}>{title}</h3>
          {description && <p className={classes.description}>{description}</p>}
          {actions && (
            <div className={classes.actions}>
              {actions.secondaryButtonProps && (
                <Button
                  size="main"
                  variant="base-secondary"
                  {...actions.secondaryButtonProps}
                />
              )}
              {actions.primaryButtonProps && (
                <Button
                  size="main"
                  variant="base-primary"
                  {...actions.primaryButtonProps}
                />
              )}
            </div>
          )}
        </div>
      </div>
    );
  },
);

export default ResultState;
