// packages/react/src/NotificationCenter/NotificationCenterDrawer.tsx
'use client';

import {
  useMemo,
  type ComponentProps,
  type Key,
  type ReactElement,
} from 'react';

import { DrawerSize } from '@mezzanine-ui/core/drawer';
import { notificationClasses as classes } from '@mezzanine-ui/core/notification-center';


import Drawer, { type DrawerProps } from '../Drawer';
import Empty from '../Empty';
import NotificationCenter, {
  type NotificationData,
} from './NotificationCenter';

type NotificationDataForDrawer = NotificationData & {
  key: Key;
  type: 'drawer';
};

type NotificationCenterDrawerPropsBase = Pick<
  DrawerProps,
  | 'onClose'
  | 'open'
> & {
  /**
   * Label for the "all" filter option in the filter bar.
   */
  filterBarAllRadioLabel?: DrawerProps['filterAreaAllRadioLabel'];
  /**
   * Label for the custom action button in the filter bar.
   */
  filterBarCustomButtonLabel?: DrawerProps['filterAreaCustomButtonLabel'];
  /**
   * Default selected filter value in the filter bar.
   */
  filterBarDefaultValue?: DrawerProps['filterAreaDefaultValue'];
  /**
   * Callback fired when the custom action button is clicked.
   */
  filterBarOnCustomButtonClick?: DrawerProps['filterAreaOnCustomButtonClick'];
  /**
   * Callback fired when the filter option changes.
   */
  filterBarOnRadioChange?: DrawerProps['filterAreaOnRadioChange'];
  /**
   * Label for the "read" filter option in the filter bar.
   */
  filterBarReadRadioLabel?: DrawerProps['filterAreaReadRadioLabel'];
  /**
   * Whether to show the filter bar.
   */
  filterBarShow?: DrawerProps['filterAreaShow'];
  /**
   * Whether to show the "unread only" shortcut button.
   */
  filterBarShowUnreadButton?: DrawerProps['filterAreaShowUnreadButton'];
  /**
   * Label for the "unread" filter option in the filter bar.
   */
  filterBarUnreadRadioLabel?: DrawerProps['filterAreaUnreadRadioLabel'];
  /**
   * Controlled selected filter value in the filter bar.
   */
  filterBarValue?: DrawerProps['filterAreaValue'];
  /**
   * Options for the filter bar dropdown.
   * When non-empty, the right-side filter area button is replaced by a Dropdown
   * triggered by a `DotHorizontalIcon` icon button.
   */
  filterBarOptions?: DrawerProps['filterAreaOptions'];
  /**
   * Callback fired when a filter bar dropdown option is selected.
   * Only used when `filterBarOptions` is non-empty.
   */
  filterBarOnSelect?: DrawerProps['filterAreaOnSelect'];
  /**
   * The size of the drawer.
   * @default 'narrow'
   */
  drawerSize?: DrawerSize;
  /**
   * The label of the "earlier" time group.
   * @default '更早'
   */
  earlierLabel?: string;
  /**
   * The title of the empty notification.
   */
  emptyNotificationTitle?: string;
  /**
   * The description of the empty notification.
   */
  emptyNotificationDescription?: string;
  /**
   * The label for the "past 7 days" time group.
   * @default '過去七天'
   */
  past7DaysLabel?: string;
  /**
   * The title of the drawer.
   */
  title?: string;
  /**
   * The label for the "today" time group.
   * @default '今天'
   */
  todayLabel?: string;
  /**
   * The label for the "yesterday" time group.
   * @default '昨天'
   */
  yesterdayLabel?: string;
};

export type NotificationCenterDrawerProps =
  | (NotificationCenterDrawerPropsBase & {
    /**
     * The children of the drawer.
     * Use this when you want to manually render NotificationCenter components.
     * Can be a single NotificationCenter element or an array of them.
     */
    children:
    | ReactElement<ComponentProps<typeof NotificationCenter>>
    | ReactElement<ComponentProps<typeof NotificationCenter>>[];
    notificationList?: never;
  })
  | (NotificationCenterDrawerPropsBase & {
    /**
     * The list of notifications to render.
     * Use this when you want to pass notification data and let the component render them.
     * Each notification must have `key` and `type: 'drawer'`.
     */
    notificationList: NotificationDataForDrawer[];
    children?: never;
  });

const isValidTime = (timestamp: string | number | undefined): boolean => {
  if (!timestamp) return false;

  const date = new Date(timestamp);

  return !Number.isNaN(date.getTime());
};

const getValidTime = (timestamp: string | number | undefined): number => {
  if (!isValidTime(timestamp)) return 0;

  const date = new Date(timestamp as string | number);

  return date.getTime();
};

type TimeGroup = 'today' | 'yesterday' | 'past7Days' | 'earlier';

const DEFAULT_TIME_GROUP_LABELS: Record<TimeGroup, string> = {
  today: '今天',
  yesterday: '昨天',
  past7Days: '過去七天',
  earlier: '更早',
};

const TIME_GROUP_ORDER: TimeGroup[] = [
  'today',
  'yesterday',
  'past7Days',
  'earlier',
];

const getTimeGroup = (
  timestamp: string | number | undefined,
  now: Date,
): TimeGroup => {
  if (!isValidTime(timestamp)) return 'earlier';

  const notificationDate = new Date(timestamp as string | number);
  const nowStartOfDay = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
  );
  const notificationStartOfDay = new Date(
    notificationDate.getFullYear(),
    notificationDate.getMonth(),
    notificationDate.getDate(),
  );

  // Today: same calendar day
  if (notificationStartOfDay.getTime() === nowStartOfDay.getTime()) {
    return 'today';
  }

  // Yesterday: previous calendar day
  const yesterdayStartOfDay = new Date(nowStartOfDay);
  yesterdayStartOfDay.setDate(yesterdayStartOfDay.getDate() - 1);
  if (notificationStartOfDay.getTime() === yesterdayStartOfDay.getTime()) {
    return 'yesterday';
  }

  // Past 7 days: within 7 days but not today or yesterday
  const diffInDays =
    (now.getTime() - notificationDate.getTime()) / (1000 * 60 * 60 * 24);
  if (diffInDays <= 7) {
    return 'past7Days';
  }

  // Earlier: more than 7 days ago
  return 'earlier';
};

const NotificationCenterDrawer = (props: NotificationCenterDrawerProps) => {
  const {
    children,
    filterBarAllRadioLabel,
    filterBarCustomButtonLabel,
    filterBarDefaultValue,
    filterBarOnCustomButtonClick,
    filterBarOnRadioChange,
    filterBarOnSelect,
    filterBarReadRadioLabel,
    filterBarShow,
    filterBarShowUnreadButton,
    filterBarUnreadRadioLabel,
    filterBarValue,
    filterBarOptions,
    drawerSize = 'narrow',
    earlierLabel,
    emptyNotificationTitle = '目前沒有新的通知',
    emptyNotificationDescription = '當有新的系統通知時，將會顯示在這裡。',
    notificationList,
    onClose,
    open,
    past7DaysLabel,
    title,
    todayLabel,
    yesterdayLabel,
    ...restDrawerProps
  } = props;

  const isEmpty = useMemo(() => {
    if (notificationList) {
      return notificationList.length === 0;
    }

    if (Array.isArray(children)) {
      return children.length === 0;
    }

    return !children;
  }, [notificationList, children]);

  const renderNotifications = useMemo(() => {
    const renderEmptyNotifications = () => {
      return (
        <div className={classes.emptyNotifications}>
          <Empty
            type="notification"
            size="main"
            title={emptyNotificationTitle}
            description={emptyNotificationDescription}
          />
        </div>
      );
    };

    if (isEmpty) {
      return renderEmptyNotifications();
    }

    // Check if notificationList is provided
    if (notificationList) {
      // Sort once by timestamp (newest first), then group while maintaining order
      const sorted = [...notificationList].sort((a, b) => {
        const aTime = getValidTime(a.timeStamp);
        const bTime = getValidTime(b.timeStamp);
        return bTime - aTime;
      });

      // Group sorted notifications
      const now = new Date();
      const grouped = sorted.reduce(
        (acc, notification) => {
          const group = getTimeGroup(notification.timeStamp, now);
          (acc[group] ??= []).push(notification);
          return acc;
        },
        {} as Record<TimeGroup, typeof notificationList>,
      );

      // Get time group labels from props or use defaults
      const timeGroupLabels: Record<TimeGroup, string> = {
        earlier: earlierLabel ?? DEFAULT_TIME_GROUP_LABELS.earlier,
        past7Days: past7DaysLabel ?? DEFAULT_TIME_GROUP_LABELS.past7Days,
        today: todayLabel ?? DEFAULT_TIME_GROUP_LABELS.today,
        yesterday: yesterdayLabel ?? DEFAULT_TIME_GROUP_LABELS.yesterday,
      };

      // Render notifications with prependTips for first item in each group
      return TIME_GROUP_ORDER.flatMap((group) => {
        const notifications = grouped[group];
        if (!notifications?.length) {
          return [];
        }

        return notifications.map((notification, index) => {
          const { key, ...restNotification } = notification;

          return (
            <NotificationCenter
              key={key}
              {...restNotification}
              prependTips={index === 0 ? timeGroupLabels[group] : undefined}
              reference={key}
              type="drawer"
            />
          );
        });
      });
    }

    // Return children (can be single element or array)
    return Array.isArray(children) ? children : children;
  }, [
    isEmpty,
    notificationList,
    children,
    emptyNotificationTitle,
    emptyNotificationDescription,
    earlierLabel,
    past7DaysLabel,
    todayLabel,
    yesterdayLabel,
  ]);

  return (
    <Drawer
      className={classes.drawer}
      filterAreaAllRadioLabel={filterBarAllRadioLabel}
      filterAreaCustomButtonLabel={filterBarCustomButtonLabel}
      filterAreaDefaultValue={filterBarDefaultValue}
      filterAreaIsEmpty={isEmpty}
      filterAreaOnCustomButtonClick={filterBarOnCustomButtonClick}
      filterAreaOnRadioChange={filterBarOnRadioChange}
      filterAreaOnSelect={filterBarOnSelect}
      filterAreaReadRadioLabel={filterBarReadRadioLabel}
      filterAreaShow={filterBarShow}
      filterAreaShowUnreadButton={filterBarShowUnreadButton}
      filterAreaUnreadRadioLabel={filterBarUnreadRadioLabel}
      filterAreaValue={filterBarValue}
      filterAreaOptions={filterBarOptions}
      headerTitle={title}
      isHeaderDisplay={Boolean(title)}
      onClose={onClose}
      open={open}
      size={drawerSize}
      {...restDrawerProps}
    >
      <div className={classes.notificationsContainer}>
        {renderNotifications}
      </div>
    </Drawer>
  );
};

export default NotificationCenterDrawer;

// packages/ng/notification-center/notification-center-drawer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { notificationClasses as classes } from '@mezzanine-ui/core/notification-center';
import { DrawerSize } from '@mezzanine-ui/core/drawer';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown';
import { MznDrawer } from '@mezzanine-ui/ng/drawer';
import { MznEmpty } from '@mezzanine-ui/ng/empty';
import { MznNotificationCenter } from './notification-center.component';
import type { NotificationItem } from './notification';

type TimeGroup = 'today' | 'yesterday' | 'past7Days' | 'earlier';

interface GroupedItem extends NotificationItem {
  readonly _prependTips?: string;
}

const TIME_GROUP_ORDER: ReadonlyArray<TimeGroup> = [
  'today',
  'yesterday',
  'past7Days',
  'earlier',
];

const isValidTime = (ts: string | number | Date | undefined): boolean => {
  if (ts === undefined || ts === null) return false;
  const d = ts instanceof Date ? ts : new Date(ts);
  return !Number.isNaN(d.getTime());
};

const getValidTime = (ts: string | number | Date | undefined): number => {
  if (ts === undefined || ts === null) return 0;
  const d = ts instanceof Date ? ts : new Date(ts);
  return Number.isNaN(d.getTime()) ? 0 : d.getTime();
};

function getTimeGroup(
  ts: string | number | Date | undefined,
  now: Date,
): TimeGroup {
  if (!isValidTime(ts)) return 'earlier';
  const d = ts instanceof Date ? ts : new Date(ts as string | number);
  const nowStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const tsStart = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  if (tsStart.getTime() === nowStart.getTime()) return 'today';
  const yesterdayStart = new Date(nowStart);
  yesterdayStart.setDate(yesterdayStart.getDate() - 1);
  if (tsStart.getTime() === yesterdayStart.getTime()) return 'yesterday';
  const diffInDays = (now.getTime() - d.getTime()) / (1000 * 60 * 60 * 24);
  if (diffInDays <= 7) return 'past7Days';
  return 'earlier';
}

/**
 * 通知中心抽屜面板，對齊 React `<NotificationCenterDrawer>`。
 *
 * 有兩種資料輸入方式：
 * 1. `[notificationList]` 傳入通知資料陣列，元件自動依 `timeStamp` 做
 *    「今天／昨天／過去七天／更早」分組，並為每組第一項附上 prependTips。
 * 2. 直接投射一或多個 `<div mznNotificationCenter type="drawer">` 子節點。
 *
 * 空狀態時自動顯示 `<div mznEmpty type="notification">`。
 *
 * @example
 * ```html
 * <!-- notificationList 模式 -->
 * <div mznNotificationCenterDrawer
 *   [open]="open()"
 *   title="通知中心"
 *   [notificationList]="items"
 *   (closed)="open.set(false)"
 * ></div>
 *
 * <!-- children 模式 -->
 * <div mznNotificationCenterDrawer [open]="open()" title="通知中心">
 *   <div mznNotificationCenter type="drawer" severity="info" title="..." />
 *   <div mznNotificationCenter type="drawer" severity="warning" title="..." />
 * </div>
 * ```
 */
@Component({
  selector: '[mznNotificationCenterDrawer]',
  standalone: true,
  imports: [MznDrawer, MznEmpty, MznNotificationCenter],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[attr.open]': 'null',
    '[attr.drawerSize]': 'null',
    '[attr.earlierLabel]': 'null',
    '[attr.emptyNotificationDescription]': 'null',
    '[attr.emptyNotificationTitle]': 'null',
    '[attr.notificationList]': 'null',
    '[attr.past7DaysLabel]': 'null',
    '[attr.title]': 'null',
    '[attr.todayLabel]': 'null',
    '[attr.yesterdayLabel]': 'null',
  },
  template: `
    <div
      mznDrawer
      [class]="drawerClass"
      [open]="open()"
      [size]="drawerSize()"
      [headerTitle]="title() ?? ''"
      [isHeaderDisplay]="!!title()"
      [filterAreaShow]="filterBarShow()"
      [filterAreaDefaultValue]="filterBarDefaultValue() ?? ''"
      [filterAreaValue]="filterBarValue() ?? ''"
      [filterAreaAllRadioLabel]="filterBarAllRadioLabel() ?? ''"
      [filterAreaReadRadioLabel]="filterBarReadRadioLabel() ?? ''"
      [filterAreaUnreadRadioLabel]="filterBarUnreadRadioLabel() ?? ''"
      [filterAreaShowUnreadButton]="filterBarShowUnreadButton()"
      [filterAreaCustomButtonLabel]="filterBarCustomButtonLabel() ?? ''"
      [filterAreaOptions]="filterBarOptions() ?? []"
      [filterAreaIsEmpty]="isEmpty()"
      (closed)="closed.emit()"
      (filterAreaRadioChange)="filterBarOnRadioChange.emit($event)"
      (filterAreaCustomButtonClick)="filterBarOnCustomButtonClick.emit()"
      (filterAreaSelect)="filterBarOnSelect.emit($event)"
    >
      @if (isEmpty()) {
        <div [class]="emptyClass">
          <div
            mznEmpty
            type="notification"
            size="main"
            [title]="emptyNotificationTitle()"
            [description]="emptyNotificationDescription()"
          ></div>
        </div>
      } @else {
        <div [class]="notificationsContainerClass">
          @if (notificationList() && notificationList()!.length > 0) {
            @for (item of groupedItems(); track item.key) {
              <div
                mznNotificationCenter
                type="drawer"
                [severity]="item.severity ?? 'info'"
                [title]="item.title ?? ''"
                [description]="item.description ?? ''"
                [timeStamp]="resolvedTimeStamp(item)"
                [timeStampLocale]="item.timeStampLocale ?? 'zh-TW'"
                [prependTips]="item._prependTips ?? null"
                [appendTips]="item.appendTips ?? null"
                [showBadge]="item.showBadge ?? false"
                [options]="item.options ?? []"
                [reference]="item.key ?? item.id ?? ''"
              ></div>
            }
          } @else {
            <ng-content />
          }
        </div>
      }
    </div>
  `,
})
export class MznNotificationCenterDrawer {
  /** 抽屜開關狀態。 */
  readonly open = input(false);

  /** 抽屜寬度。@default 'narrow' */
  readonly drawerSize = input<DrawerSize>('narrow');

  /** 抽屜標題。 */
  readonly title = input<string>();

  /** `notificationList` 模式下的通知資料。 */
  readonly notificationList = input<ReadonlyArray<NotificationItem>>();

  /** 「今天」分組標籤。@default '今天' */
  readonly todayLabel = input<string>('今天');

  /** 「昨天」分組標籤。@default '昨天' */
  readonly yesterdayLabel = input<string>('昨天');

  /** 「過去七天」分組標籤。@default '過去七天' */
  readonly past7DaysLabel = input<string>('過去七天');

  /** 「更早」分組標籤。@default '更早' */
  readonly earlierLabel = input<string>('更早');

  /** 空狀態標題。@default '目前沒有新的通知' */
  readonly emptyNotificationTitle = input<string>('目前沒有新的通知');

  /** 空狀態描述。@default '當有新的系統通知時，將會顯示在這裡。' */
  readonly emptyNotificationDescription =
    input<string>('當有新的系統通知時，將會顯示在這裡。');

  // ─── Filter bar (maps to MznDrawer filterArea* API) ─────────────────
  readonly filterBarShow = input<boolean>(false);
  readonly filterBarDefaultValue = input<string>();
  readonly filterBarValue = input<string>();
  readonly filterBarAllRadioLabel = input<string>();
  readonly filterBarReadRadioLabel = input<string>();
  readonly filterBarUnreadRadioLabel = input<string>();
  readonly filterBarShowUnreadButton = input<boolean>(false);
  readonly filterBarCustomButtonLabel = input<string>();
  readonly filterBarOptions = input<ReadonlyArray<DropdownOption>>();

  /** 抽屜關閉事件（點擊 backdrop 或 X）。 */
  readonly closed = output<void>();

  /** filter bar radio 變更。 */
  readonly filterBarOnRadioChange = output<string>();

  /** filter bar 自訂按鈕點擊。 */
  readonly filterBarOnCustomButtonClick = output<void>();

  /** filter bar Dropdown 選項選取。 */
  readonly filterBarOnSelect = output<DropdownOption>();

  protected readonly drawerClass = classes.drawer;
  protected readonly emptyClass = classes.emptyNotifications;
  protected readonly notificationsContainerClass =
    classes.notificationsContainer;

  protected readonly isEmpty = computed((): boolean => {
    const list = this.notificationList();
    if (list) return list.length === 0;
    // children projection — we can't easily count projected nodes from a
    // signal-based computed; treat falsy children as non-empty by default.
    return false;
  });

  protected readonly groupedItems = computed((): ReadonlyArray<GroupedItem> => {
    const list = this.notificationList();
    if (!list || list.length === 0) return [];
    const sorted = [...list].sort(
      (a, b) =>
        getValidTime(resolveTimeStamp(b)) - getValidTime(resolveTimeStamp(a)),
    );
    const now = new Date();
    const buckets: Record<TimeGroup, NotificationItem[]> = {
      today: [],
      yesterday: [],
      past7Days: [],
      earlier: [],
    };
    for (const item of sorted) {
      buckets[getTimeGroup(resolveTimeStamp(item), now)].push(item);
    }
    const labels: Record<TimeGroup, string> = {
      today: this.todayLabel(),
      yesterday: this.yesterdayLabel(),
      past7Days: this.past7DaysLabel(),
      earlier: this.earlierLabel(),
    };
    const out: GroupedItem[] = [];
    for (const group of TIME_GROUP_ORDER) {
      const items = buckets[group];
      if (!items.length) continue;
      items.forEach((item, idx) => {
        out.push({
          ...item,
          _prependTips: idx === 0 ? labels[group] : undefined,
        });
      });
    }
    return out;
  });

  protected resolvedTimeStamp(item: NotificationItem): string | number | Date {
    return resolveTimeStamp(item) ?? new Date();
  }
}

function resolveTimeStamp(
  item: NotificationItem,
): string | number | Date | undefined {
  return item.timeStamp ?? item.timestamp;
}
