// packages/react/src/Layout/LayoutLeftPanel.tsx
'use client';

import { useCallback, useContext, useEffect, useRef, useState } from 'react';
import { layoutClasses as classes } from '@mezzanine-ui/core/layout';
import { cx } from '../utils/cx';
import { useDocumentEvents } from '../hooks/useDocumentEvents';
import Scrollbar, { ScrollbarProps } from '../Scrollbar';
import { LayoutContext } from './LayoutContext';

const MIN_PANEL_WIDTH = 240;
const CONTENT_WRAPPER_MIN_WIDTH = 480;
const ARROW_KEY_STEP = 10;

export interface LayoutLeftPanelProps {
  /** The content rendered inside the left panel. */
  children?: React.ReactNode;
  /** Additional class name applied to the panel element. */
  className?: string;
  /** Initial width (in px) of the panel. Clamped to a minimum of 240px. */
  defaultWidth?: number;
  /** Callback fired when the panel width changes during resize. */
  onWidthChange?: (width: number) => void;
  /** Controls whether the panel and its divider are visible. */
  open?: boolean;
  /** Props passed to the internal `Scrollbar` component. */
  scrollbarProps?: Omit<ScrollbarProps, 'children'>;
}

export function LayoutLeftPanel({
  children,
  className,
  defaultWidth = 320,
  onWidthChange,
  open = false,
  scrollbarProps = {},
}: LayoutLeftPanelProps) {
  const context = useContext(LayoutContext);

  const [isDragging, setIsDragging] = useState(false);
  const [width, setWidth] = useState(() =>
    Math.max(MIN_PANEL_WIDTH, defaultWidth),
  );
  const dragStartRef = useRef<{
    width: number;
    x: number;
    maxWidth: number;
  } | null>(null);
  const rafIdRef = useRef<number | null>(null);

  useEffect(() => {
    return () => {
      if (rafIdRef.current !== null) {
        window.cancelAnimationFrame(rafIdRef.current);
        rafIdRef.current = null;
      }
    };
  }, []);

  const handleDividerMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();

      const mainWidth =
        context?.mainRef.current?.offsetWidth || window.innerWidth;
      const maxWidth =
        width + Math.max(0, mainWidth - CONTENT_WRAPPER_MIN_WIDTH);

      setIsDragging(true);
      dragStartRef.current = { maxWidth, width, x: e.clientX };
    },
    [context, width],
  );

  const handleDividerKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return;

      e.preventDefault();

      const mainWidth =
        context?.mainRef.current?.offsetWidth || window.innerWidth;
      const maxWidth =
        width + Math.max(0, mainWidth - CONTENT_WRAPPER_MIN_WIDTH);
      const step = e.key === 'ArrowRight' ? ARROW_KEY_STEP : -ARROW_KEY_STEP;
      const newWidth = Math.min(
        maxWidth,
        Math.max(MIN_PANEL_WIDTH, width + step),
      );

      setWidth(newWidth);
      onWidthChange?.(newWidth);
    },
    [context, onWidthChange, width],
  );

  useDocumentEvents(() => {
    if (!isDragging) return undefined;

    return {
      mousemove: (e: MouseEvent) => {
        if (!dragStartRef.current) return;

        if (rafIdRef.current !== null) {
          window.cancelAnimationFrame(rafIdRef.current);
        }

        rafIdRef.current = window.requestAnimationFrame(() => {
          rafIdRef.current = null;

          if (!dragStartRef.current) return;

          const delta = e.clientX - dragStartRef.current.x;
          const newWidth = dragStartRef.current.width + delta;
          const clamped = Math.min(
            dragStartRef.current.maxWidth,
            Math.max(MIN_PANEL_WIDTH, newWidth),
          );

          setWidth(clamped);
          onWidthChange?.(clamped);
        });
      },
      mouseup: () => {
        if (rafIdRef.current !== null) {
          window.cancelAnimationFrame(rafIdRef.current);
          rafIdRef.current = null;
        }

        setIsDragging(false);
        dragStartRef.current = null;
      },
    };
  }, [isDragging, onWidthChange]);

  if (!open) return null;

  return (
    <aside
      aria-label="Left panel"
      className={cx(classes.sidePanel, classes.sidePanelLeft, className)}
      style={{ inlineSize: width }}
    >
      <div className={classes.sidePanelContent}>
        <Scrollbar {...scrollbarProps}>{children}</Scrollbar>
      </div>
      {/* eslint-disable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex -- WAI-ARIA 1.2: focusable separator with aria-valuenow is an interactive widget */}
      <div
        aria-label="Resize left panel"
        aria-orientation="vertical"
        aria-valuemin={MIN_PANEL_WIDTH}
        aria-valuenow={width}
        className={cx(classes.divider, {
          [classes.dividerDragging]: isDragging,
        })}
        onKeyDown={handleDividerKeyDown}
        onMouseDown={handleDividerMouseDown}
        role="separator"
        tabIndex={0}
      />
      {/* eslint-enable jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/no-noninteractive-tabindex */}
    </aside>
  );
}

LayoutLeftPanel.displayName = 'Layout.LeftPanel';

// packages/vue/layout/layout-left-panel.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { CSSProperties } from 'vue';
import { layoutClasses as classes } from '@mezzanine-ui/core/layout';
import clsx from 'clsx';
import { toCssLength } from '../_internal/css-length';
import MznScrollbar from '../scrollbar/scrollbar.vue';
import { MIN_PANEL_WIDTH, useSidePanelResize } from './use-side-panel-resize';
import type { LayoutLeftPanelProps } from './layout-left-panel.types';

/**
 * 版面左側的面板，可以拖曳分隔線改變寬度。
 *
 * `open` 為 false 時整個不渲染。寬度下限 240px，上限則留給主要區域至少 480px；
 * 分隔線可以聚焦，用左右方向鍵一次調 10px。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznLayoutLeftPanel } from '@mezzanine-ui/vue/layout';
 * <\/script>
 *
 * <template>
 *   <MznLayoutLeftPanel :default-width="240" open>...</MznLayoutLeftPanel>
 * </template>
 * ```
 *
 * @see MznLayoutRightPanel 右側的同款面板
 */
const props = withDefaults(defineProps<LayoutLeftPanelProps>(), {
  defaultWidth: 320,
  open: false,
  scrollbarProps: () => ({}),
});

const emit = defineEmits<{
  /** Fired with the new width while the panel is being resized. */
  widthChange: [width: number];
}>();

defineSlots<{
  /** The panel's own content. */
  default?: () => unknown;
}>();

const { isDragging, onDividerKeydown, onDividerMousedown, width } =
  useSidePanelResize({
    defaultWidth: () => props.defaultWidth,
    onWidthChange: (next) => emit('widthChange', next),
    side: 'left',
  });

const hostClasses = computed((): string =>
  clsx(classes.sidePanel, classes.sidePanelLeft),
);

/** React appends `px` to a numeric style value; Vue leaves it invalid. */
const hostStyle = computed(
  (): CSSProperties => ({ inlineSize: toCssLength(width.value) }),
);

const dividerClasses = computed((): string =>
  clsx(classes.divider, { [classes.dividerDragging]: isDragging.value }),
);

const MIN_WIDTH = MIN_PANEL_WIDTH;
</script>

<template>
  <aside
    v-if="open"
    aria-label="Left panel"
    :class="hostClasses"
    :style="hostStyle"
  >
    <div :class="classes.sidePanelContent">
      <MznScrollbar v-bind="scrollbarProps"><slot /></MznScrollbar>
    </div>
    <!--
      WAI-ARIA 1.2: a focusable separator carrying aria-valuenow is an
      interactive widget, so the tabindex and the handlers belong on it.
    -->
    <div
      aria-label="Resize left panel"
      aria-orientation="vertical"
      :aria-valuemin="MIN_WIDTH"
      :aria-valuenow="width"
      :class="dividerClasses"
      role="separator"
      :tabindex="0"
      @keydown="onDividerKeydown"
      @mousedown="onDividerMousedown"
    />
  </aside>
</template>
