// packages/vue/alert-banner/alert-banner.vue
<script setup lang="ts">
import { computed, onMounted, ref, useAttrs, watch } from 'vue';
import {
  alertBannerIcons,
  alertBannerClasses as classes,
} from '@mezzanine-ui/core/alert-banner';
import type { IconDefinition } from '@mezzanine-ui/icons';
import { MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznPortal from '../portal/portal.vue';
import type { AlertBannerProps } from './alert-banner.types';

/**
 * 頁面層級的橫幅式警示訊息。
 *
 * 預設透過 MznPortal 渲染至 alert layer，支援 `info`、`warning`、`error` 三種
 * 嚴重程度，最多兩個操作按鈕與一個關閉按鈕。開啟與關閉時以高度動畫展開／收合。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznAlertBanner } from '@mezzanine-ui/vue/alert-banner';
 * <\/script>
 *
 * <template>
 *   <MznAlertBanner message="系統將於今晚進行維護" severity="info" />
 * </template>
 * ```
 *
 * @see alertBanner 以命令式呼叫的版本
 * @see MznInlineMessage 行內訊息元件
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<AlertBannerProps>(), {
  actions: undefined,
  closable: true,
  disablePortal: false,
  icon: undefined,
});

const emit = defineEmits<{
  close: [];
}>();

const attrs = useAttrs();

const visible = ref(true);
const node = ref<HTMLElement | null>(null);
const wrapper = ref<HTMLElement | null>(null);

/** Ported from React's `reflow`. */
function reflow(element: HTMLElement): void {
  void element.scrollTop;
}

function handleClose(): void {
  const element = wrapper.value;

  if (element) {
    element.style.height = `${element.scrollHeight}px`;
    element.style.overflow = 'hidden';
    reflow(element);

    element.style.transition = `height 250ms ${MOTION_EASING.exit}`;
    element.style.height = '0px';
  }

  setTimeout(() => {
    visible.value = false;
    emit('close');
  }, 250); // moderate duration
}

watch(
  (): AlertBannerProps['actions'] => props.actions,
  (actions) => {
    if (actions && actions.length > 2) {
      console.warn('AlertBanner: actions maximum is 2');
    }
  },
  { immediate: true },
);

/**
 * Expand from nothing to the content's height, then hand the height back to
 * the layout — an explicit `auto` would not animate, and leaving the measured
 * pixel height would freeze the banner at one size.
 */
function playEnter(): void {
  const element = wrapper.value;
  const inner = node.value;

  if (!visible.value || !element || !inner) return;

  element.style.height = '0px';
  element.style.overflow = 'hidden';
  reflow(element);

  requestAnimationFrame(() => {
    element.style.transition = `height 250ms ${MOTION_EASING.entrance}`;
    element.style.height = `${inner.scrollHeight}px`;

    setTimeout(() => {
      element.style.height = 'auto';
      element.style.overflow = 'visible';
      element.style.transition = '';
    }, 250);
  });
}

onMounted(playEnter);
watch(visible, playEnter, { flush: 'post' });

const resolvedIcon = computed(
  (): IconDefinition => props.icon ?? alertBannerIcons[props.severity],
);

/**
 * Maximum support 2 actions. `content` and `onClick` are pulled out the way
 * React destructures them, so neither reaches the button as an attribute, and
 * the rest is bound after `size`/`variant` so a caller can still override them.
 */
const validActions = computed(() =>
  (props.actions?.slice(0, 2) ?? []).map((action) => {
    const { content, onClick, ...buttonProps } = action;

    return { buttonProps, content, onClick };
  }),
);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.severity(props.severity), attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const {
    class: _class,
    instanceKey: _instanceKey,
    maxCount: _maxCount,
    ...rest
  } = attrs;

  return rest;
});

const wrapperClass = classes.wrapper;
const bodyClass = classes.body;
const iconClass = classes.icon;
const messageClass = classes.message;
const controlsClass = classes.controls;
const actionsClass = classes.actions;
const closeClass = classes.close;
</script>

<template>
  <MznPortal v-if="visible" :disable-portal="disablePortal" layer="alert">
    <div ref="wrapper" :class="wrapperClass">
      <div
        v-bind="forwardedAttrs"
        ref="node"
        aria-live="polite"
        :class="hostClasses"
        role="status"
      >
        <div :class="bodyClass">
          <MznIcon :class="iconClass" :icon="resolvedIcon" />
          <span :class="messageClass">{{ message }}</span>
        </div>

        <div :class="controlsClass">
          <div v-if="validActions.length" :class="actionsClass">
            <MznButton
              v-for="(action, index) in validActions"
              :key="index"
              size="minor"
              variant="inverse"
              v-bind="action.buttonProps"
              @click="action.onClick"
            >
              {{ action.content }}
            </MznButton>
          </div>
          <MznClearActions
            v-if="closable"
            :class="closeClass"
            type="standard"
            variant="inverse"
            @click="handleClose"
          />
        </div>
      </div>
    </div>
  </MznPortal>
</template>

// packages/ng/alert-banner/alert-banner.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  OnInit,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { IconDefinition } from '@mezzanine-ui/icons';
import {
  alertBannerClasses as classes,
  alertBannerIcons,
  AlertBannerSeverity,
} from '@mezzanine-ui/core/alert-banner';

export { AlertBannerSeverity };
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznButton } from '@mezzanine-ui/ng/button';
import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';
import { MOTION_DURATION } from '@mezzanine-ui/system/motion/duration';
import { MOTION_EASING } from '@mezzanine-ui/system/motion/easing';

/** AlertBanner 操作按鈕定義。 */
export interface AlertBannerAction {
  readonly content?: string;
  readonly onClick: (event: MouseEvent) => void;
}

/**
 * 橫幅通知元件，用於全域性重要訊息。
 *
 * 支援 info / warning / error 三種嚴重程度，
 * 可附帶操作按鈕（最多 2 個）與關閉按鈕。
 * 含入場/離場高度動畫。
 *
 * @example
 * ```html
 * import { MznAlertBanner } from '@mezzanine-ui/ng/alert-banner';
 *
 * <div mznAlertBanner
 *   severity="warning"
 *   message="系統將於 30 分鐘後維護"
 *   [closable]="true"
 *   (closed)="onClose()"
 * ></div>
 * ```
 */
@Component({
  selector: '[mznAlertBanner]',
  host: {
    '[attr.severity]': 'null',
    '[attr.message]': 'null',
    '[attr.actions]': 'null',
    '[attr.createdAt]': 'null',
    '[attr.closable]': 'null',
    '[attr.icon]': 'null',
    '[attr.reference]': 'null',
  },
  standalone: true,
  imports: [MznIcon, MznButton, MznClearActions],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (visible()) {
      <div #wrapper [class]="wrapperClass">
        <div [class]="hostClasses()" role="status" aria-live="polite">
          <div [class]="bodyClass">
            <i mznIcon [icon]="resolvedIcon()" [class]="iconClass"></i>
            <span [class]="messageClass">{{ message() }}</span>
          </div>
          <div [class]="controlsClass">
            @if (displayActions().length > 0) {
              <div [class]="actionsClass">
                @for (action of displayActions(); track $index) {
                  <button
                    mznButton
                    variant="inverse"
                    size="minor"
                    (click)="action.onClick($event)"
                    >{{ action.content }}</button
                  >
                }
              </div>
            }
            @if (showCloseButton()) {
              <button
                mznClearActions
                type="standard"
                variant="inverse"
                [class]="closeClass"
                (clicked)="handleClose()"
              ></button>
            }
          </div>
        </div>
      </div>
    }
  `,
})
export class MznAlertBanner implements OnInit {
  private readonly wrapperRef = viewChild<ElementRef<HTMLElement>>('wrapper');

  /**
   * 嚴重程度。
   */
  readonly severity = input.required<AlertBannerSeverity>();

  /**
   * 訊息文字。
   */
  readonly message = input.required<string>();

  /**
   * 操作按鈕（最多 2 個）。
   */
  readonly actions = input<ReadonlyArray<AlertBannerAction>>([]);

  /**
   * 建立時間戳（毫秒）。由 `MznAlertBannerService` 自動填入，用於排序多個橫幅通知。
   * @internal
   */
  readonly createdAt = input<number>();

  /**
   * 是否顯示關閉按鈕。
   * @default true
   */
  readonly closable = input(true);

  /**
   * 自訂圖示（預設依 severity 自動選擇）。
   */
  readonly icon = input<IconDefinition>();

  /**
   * AlertBanner 的唯一識別 key，可用於程式化關閉（透過 MznAlertBannerService.remove(reference)）。
   */
  readonly reference = input<string | number | undefined>(undefined);

  /** 關閉事件。 */
  readonly closed = output<void>();

  readonly visible = signal(true);

  protected readonly resolvedIcon = computed(
    (): IconDefinition => this.icon() ?? alertBannerIcons[this.severity()],
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.severity(this.severity())),
  );

  protected readonly displayActions = computed(
    (): ReadonlyArray<AlertBannerAction> => {
      const acts = this.actions();

      if (acts.length > 2) {
        console.warn(
          'MznAlertBanner: actions 最多支援 2 個，超出部分將被截斷。',
        );
      }

      return acts.slice(0, 2);
    },
  );

  protected readonly showCloseButton = computed((): boolean => this.closable());

  protected readonly wrapperClass = classes.wrapper;
  protected readonly bodyClass = classes.body;
  protected readonly iconClass = classes.icon;
  protected readonly messageClass = classes.message;
  protected readonly controlsClass = classes.controls;
  protected readonly actionsClass = classes.actions;
  protected readonly closeClass = classes.close;

  ngOnInit(): void {
    requestAnimationFrame(() => {
      this.animateEnter();
    });
  }

  protected handleClose(): void {
    this.animateExit(() => {
      this.visible.set(false);
      this.closed.emit();
    });
  }

  private animateEnter(): void {
    const wrapper = this.wrapperRef()?.nativeElement;

    if (!wrapper) {
      return;
    }

    const height = wrapper.scrollHeight;

    wrapper.style.height = '0px';
    wrapper.style.overflow = 'hidden';

    // Force reflow
    void wrapper.scrollTop;

    wrapper.style.transition = `height ${MOTION_DURATION.moderate}ms ${MOTION_EASING.entrance}`;
    wrapper.style.height = `${height}px`;

    setTimeout(() => {
      wrapper.style.height = 'auto';
      wrapper.style.overflow = '';
      wrapper.style.transition = '';
    }, MOTION_DURATION.moderate);
  }

  private animateExit(onDone: () => void): void {
    const wrapper = this.wrapperRef()?.nativeElement;

    if (!wrapper) {
      onDone();

      return;
    }

    wrapper.style.height = `${wrapper.scrollHeight}px`;
    wrapper.style.overflow = 'hidden';

    // Force reflow
    void wrapper.scrollTop;

    wrapper.style.transition = `height ${MOTION_DURATION.moderate}ms ${MOTION_EASING.exit}`;
    wrapper.style.height = '0px';

    setTimeout(onDone, MOTION_DURATION.moderate);
  }
}
