// packages/react/src/Section/Section.tsx
import {
  cloneElement,
  forwardRef,
  isValidElement,
  PropsWithChildren,
  ReactElement,
} from 'react';
import ContentHeader, { ContentHeaderProps } from '../ContentHeader';
import { FilterArea, FilterAreaProps } from '../FilterArea';
import Tab, { TabProps } from '../Tab';
import { cx } from '../utils/cx';
import { sectionClasses as classes } from '@mezzanine-ui/core/section';

export interface SectionProps {
  /**
   * Additional style for the section container.
   */
  className?: string;
  /**
   * Accept `<ContentHeader />` component from `mezzanine`.
   * Other components will trigger a warning.
   */
  contentHeader?: ReactElement<ContentHeaderProps>;
  /**
   * Accept `<FilterArea />` component from `mezzanine`.
   * Other components will trigger a warning.
   */
  filterArea?: ReactElement<FilterAreaProps>;
  /**
   * Accept `<Tab />` component from `mezzanine`.
   * Other components will trigger a warning.
   */
  tab?: ReactElement<TabProps>;
}

function getDisplayName(element: ReactElement): string {
  const type = element.type;

  if (typeof type === 'string') {
    return type;
  }

  return (
    (type as { displayName?: string }).displayName ||
    (type as { name?: string }).name ||
    'Unknown'
  );
}

function isContentHeaderElement(
  element: ReactElement<ContentHeaderProps> | undefined,
): element is ReactElement<ContentHeaderProps> {
  return isValidElement(element) && element.type === ContentHeader;
}

function isFilterAreaElement(
  element: ReactElement<FilterAreaProps> | undefined,
): element is ReactElement<FilterAreaProps> {
  return isValidElement(element) && element.type === FilterArea;
}

function isTabElement(
  element: ReactElement<TabProps> | undefined,
): element is ReactElement<TabProps> {
  return isValidElement(element) && element.type === Tab;
}

/**
 * The react component for `mezzanine` section.
 */
const Section = forwardRef<HTMLDivElement, PropsWithChildren<SectionProps>>(
  function Section(props, ref) {
    const { children, className, contentHeader, filterArea, tab } = props;

    let renderedContentHeader: ReactElement<ContentHeaderProps> | null = null;
    let renderedFilterArea: ReactElement<FilterAreaProps> | null = null;
    let renderedTab: ReactElement<TabProps> | null = null;

    if (contentHeader) {
      if (isContentHeaderElement(contentHeader)) {
        renderedContentHeader = cloneElement(contentHeader, { size: 'sub' });
      } else if (isValidElement(contentHeader)) {
        console.warn(
          `[Section] Invalid contentHeader type: <${getDisplayName(contentHeader)}>. Only <ContentHeader /> component from @mezzanine-ui/react is allowed.`,
        );
      }
    }

    if (filterArea) {
      if (isFilterAreaElement(filterArea)) {
        renderedFilterArea = cloneElement(filterArea, { size: 'sub' });
      } else if (isValidElement(filterArea)) {
        console.warn(
          `[Section] Invalid filterArea type: <${getDisplayName(filterArea)}>. Only <FilterArea /> component from @mezzanine-ui/react is allowed.`,
        );
      }
    }

    if (tab) {
      if (isTabElement(tab)) {
        renderedTab = tab;
      } else if (isValidElement(tab)) {
        console.warn(
          `[Section] Invalid tab type: <${getDisplayName(tab)}>. Only <Tab /> component from @mezzanine-ui/react is allowed.`,
        );
      }
    }

    return (
      <div ref={ref} className={cx(classes.host, className)}>
        {renderedContentHeader}
        {renderedFilterArea}
        {renderedTab}
        <div className={classes.hostContent}>{children}</div>
      </div>
    );
  },
);

export default Section;

// packages/vue/section/section.vue
<script setup lang="ts">
import { cloneVNode, computed } from 'vue';
import type { FunctionalComponent, VNode } from 'vue';
import { sectionClasses as classes } from '@mezzanine-ui/core/section';
import MznContentHeader from '../content-header/content-header.vue';
import MznFilterArea from '../filter-area/filter-area.vue';
import MznTab from '../tab/tab.vue';
import type { SectionProps } from './section.types';

/**
 * 頁面裡的一個區塊：標題列、篩選器、頁籤，加上內容。
 *
 * 三個位置各自只收對應的元件，給錯會印出警告並不渲染。標題列與篩選器一律被改成
 * `sub` 尺寸。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { h } from 'vue';
 * import { MznSection } from '@mezzanine-ui/vue/section';
 * import { MznContentHeader } from '@mezzanine-ui/vue/content-header';
 * <\/script>
 *
 * <template>
 *   <MznSection :content-header="h(MznContentHeader, { title: 'Section Title' })">
 *     內容
 *   </MznSection>
 * </template>
 * ```
 *
 * @see MznSectionGroup 把多個區塊排在一起
 */
const props = withDefaults(defineProps<SectionProps>(), {
  contentHeader: undefined,
  filterArea: undefined,
  tab: undefined,
});

defineSlots<{
  /** The section's own content. */
  default?: () => unknown;
}>();

/** React reads `displayName` or the function's name off the element's type. */
function displayNameOf(node: VNode): string {
  const { type } = node;

  if (typeof type === 'string') return type;

  const component = type as { __name?: string; name?: string };

  return component.name || component.__name || 'Unknown';
}

function resolve(
  node: VNode | undefined,
  expected: unknown,
  slotName: string,
  size?: 'sub',
): VNode | null {
  if (!node) return null;

  if (node.type === expected) {
    return size ? cloneVNode(node, { size }) : node;
  }

  console.warn(
    `[Section] Invalid ${slotName} type: <${displayNameOf(node)}>. Only <${slotName === 'contentHeader' ? 'ContentHeader' : slotName === 'filterArea' ? 'FilterArea' : 'Tab'} /> component from @mezzanine-ui/react is allowed.`,
  );

  return null;
}

const renderedContentHeader = computed((): VNode | null =>
  resolve(props.contentHeader, MznContentHeader, 'contentHeader', 'sub'),
);

const renderedFilterArea = computed((): VNode | null =>
  resolve(props.filterArea, MznFilterArea, 'filterArea', 'sub'),
);

const renderedTab = computed((): VNode | null =>
  resolve(props.tab, MznTab, 'tab'),
);

const ContentHeaderSlot: FunctionalComponent = () =>
  renderedContentHeader.value;
const FilterAreaSlot: FunctionalComponent = () => renderedFilterArea.value;
const TabSlot: FunctionalComponent = () => renderedTab.value;
</script>

<template>
  <div :class="classes.host">
    <ContentHeaderSlot />
    <FilterAreaSlot />
    <TabSlot />
    <div :class="classes.hostContent"><slot /></div>
  </div>
</template>
