// packages/vue/time-panel/time-panel.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { DateType } from '@mezzanine-ui/core/calendar';
import {
  getUnits,
  timePanelClasses as classes,
  type TimePanelUnit,
} from '@mezzanine-ui/core/time-panel';
import clsx from 'clsx';
import MznCalendarFooterActions from '../calendar/calendar-footer-actions.vue';
import { useCalendarContext } from '../calendar/calendar-context';
import MznTimePanelColumn from './time-panel-column.vue';
import type { TimePanelProps } from './time-panel.types';

/**
 * 時間面板，以時、分、秒三個捲動欄位選取時間。
 *
 * 每個欄位都可以個別隱藏，步進值也可分別設定；沒有 `value` 時以今天的
 * 零點為基準套用選取的單位。底部固定是取消與確認兩顆按鈕。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznTimePanel } from '@mezzanine-ui/vue/time-panel';
 * <\/script>
 *
 * <template>
 *   <MznTimePanel
 *     :minute-step="5"
 *     :value="value"
 *     @cancel="onCancel"
 *     @change="onChange"
 *     @confirm="onConfirm"
 *   />
 * </template>
 * ```
 *
 * @see MznCalendar 日期面板
 * @see MznCalendarConfigProvider 提供日期函式庫與語系
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TimePanelProps>(), {
  hideHour: false,
  hideMinute: false,
  hideSecond: false,
  hourStep: 1,
  minuteStep: 1,
  secondStep: 1,
  value: undefined,
});

const emit = defineEmits<{
  cancel: [];
  change: [target: DateType];
  confirm: [];
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const hourUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideHour ? undefined : getUnits(0, 23, props.hourStep),
);

const minuteUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideMinute ? undefined : getUnits(0, 59, props.minuteStep),
);

const secondUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideSecond ? undefined : getUnits(0, 59, props.secondStep),
);

const activeHour = computed((): number | undefined =>
  props.value ? calendar.value.getHour(props.value) : undefined,
);

const activeMinute = computed((): number | undefined =>
  props.value ? calendar.value.getMinute(props.value) : undefined,
);

const activeSecond = computed((): number | undefined =>
  props.value ? calendar.value.getSecond(props.value) : undefined,
);

function handleChange(
  granularity: 'hour' | 'minute' | 'second',
  target: TimePanelUnit,
): void {
  const { getNow, setHour, setMinute, setSecond, startOf } = calendar.value;
  const setter = { hour: setHour, minute: setMinute, second: setSecond }[
    granularity
  ];
  const currentValue = props.value || startOf(getNow(), 'day');

  emit('change', setter(currentValue, target.value));
}

const actions = computed(() => ({
  secondaryButtonProps: {
    children: 'Cancel',
    onClick: () => emit('cancel'),
  },
  primaryButtonProps: {
    children: 'Ok',
    onClick: () => emit('confirm'),
  },
}));

const hostClasses = computed((): string =>
  clsx(classes.host, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const columnsClass = classes.columns;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <div :class="columnsClass">
      <MznTimePanelColumn
        v-if="!hideHour && hourUnits"
        :active-unit="activeHour"
        :units="hourUnits"
        @change="handleChange('hour', $event)"
      />
      <MznTimePanelColumn
        v-if="!hideMinute && minuteUnits"
        :active-unit="activeMinute"
        :units="minuteUnits"
        @change="handleChange('minute', $event)"
      />
      <MznTimePanelColumn
        v-if="!hideSecond && secondUnits"
        :active-unit="activeSecond"
        :units="secondUnits"
        @change="handleChange('second', $event)"
      />
    </div>
    <MznCalendarFooterActions :actions="actions" />
  </div>
</template>

// packages/ng/time-panel/time-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  input,
  output,
} from '@angular/core';
import { DateType } from '@mezzanine-ui/core/calendar';
import {
  getUnits,
  timePanelClasses as classes,
  TimePanelUnit,
} from '@mezzanine-ui/core/time-panel';
import { MZN_CALENDAR_CONFIG } from '@mezzanine-ui/ng/calendar';
import { MznCalendarFooterActions } from '@mezzanine-ui/ng/_internal';
import { MznTimePanelColumn } from './time-panel-column.component';

/**
 * 時間面板元件，顯示時/分/秒的可滾動欄位，附帶 Cancel/Ok 按鈕。
 *
 * 採用兩階段提交模式：欄位變更更新 pending value，
 * 點擊「Ok」才正式提交，「Cancel」則放棄修改。
 *
 * @example
 * ```html
 * import { MznTimePanel } from '@mezzanine-ui/ng/time-panel';
 *
 * <mzn-time-panel
 *   [value]="pendingTime"
 *   (timeChanged)="onTimeChange($event)"
 *   (confirmed)="onConfirm()"
 *   (cancelled)="onCancel()"
 * />
 * ```
 */
@Component({
  selector: 'mzn-time-panel',
  standalone: true,
  imports: [MznTimePanelColumn, MznCalendarFooterActions],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClass',
  },
  template: `
    <div [class]="columnsClass">
      @if (!hideHour()) {
        <mzn-time-panel-column
          [units]="hourUnits()"
          [activeUnit]="activeHour()"
          [cellHeight]="cellHeight()"
          (unitChanged)="onColumnChange('hour', $event)"
        />
      }
      @if (!hideMinute()) {
        <mzn-time-panel-column
          [units]="minuteUnits()"
          [activeUnit]="activeMinute()"
          [cellHeight]="cellHeight()"
          (unitChanged)="onColumnChange('minute', $event)"
        />
      }
      @if (!hideSecond()) {
        <mzn-time-panel-column
          [units]="secondUnits()"
          [activeUnit]="activeSecond()"
          [cellHeight]="cellHeight()"
          (unitChanged)="onColumnChange('second', $event)"
        />
      }
    </div>
    <mzn-calendar-footer-actions
      cancelText="Cancel"
      confirmText="Ok"
      (cancelled)="cancelled.emit()"
      (confirmed)="confirmed.emit()"
    />
  `,
})
export class MznTimePanel {
  private readonly config = inject(MZN_CALENDAR_CONFIG);

  /** 是否隱藏小時欄。 */
  readonly hideHour = input(false);
  /** 是否隱藏分鐘欄。 */
  readonly hideMinute = input(false);
  /** 是否隱藏秒鐘欄。 */
  readonly hideSecond = input(false);
  /** 小時步長。 @default 1 */
  readonly hourStep = input(1);
  /** 分鐘步長。 @default 1 */
  readonly minuteStep = input(1);
  /** 秒鐘步長。 @default 1 */
  readonly secondStep = input(1);
  /**
   * 每個儲存格的高度（px），控制捲動定位。
   * @default 32
   */
  readonly cellHeight = input(32);
  /** 當前顯示值。 */
  readonly value = input<DateType | undefined>(undefined);

  /** 時間變更事件（pending，尚未提交）。 */
  readonly timeChanged = output<DateType>();
  /** 確認事件。 */
  readonly confirmed = output<void>();
  /** 取消事件。 */
  readonly cancelled = output<void>();

  protected readonly hostClass = classes.host;
  protected readonly columnsClass = classes.columns;

  protected readonly hourUnits = computed(() =>
    this.hideHour() ? [] : getUnits(0, 23, this.hourStep()),
  );
  protected readonly minuteUnits = computed(() =>
    this.hideMinute() ? [] : getUnits(0, 59, this.minuteStep()),
  );
  protected readonly secondUnits = computed(() =>
    this.hideSecond() ? [] : getUnits(0, 59, this.secondStep()),
  );

  protected readonly activeHour = computed(() => {
    const v = this.value();
    return v ? this.config.getHour(v) : undefined;
  });
  protected readonly activeMinute = computed(() => {
    const v = this.value();
    return v ? this.config.getMinute(v) : undefined;
  });
  protected readonly activeSecond = computed(() => {
    const v = this.value();
    return v ? this.config.getSecond(v) : undefined;
  });

  protected onColumnChange(
    granularity: 'hour' | 'minute' | 'second',
    unit: TimePanelUnit,
  ): void {
    const c = this.config;
    const current = this.value() ?? c.startOf(c.getNow(), 'day');

    const setters = {
      hour: c.setHour,
      minute: c.setMinute,
      second: c.setSecond,
    } as const;

    const result = setters[granularity](current, unit.value);
    this.timeChanged.emit(result);
  }
}
