// packages/vue/time-panel/time-panel-column.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import {
  timePanelClasses as classes,
  type TimePanelUnit,
} from '@mezzanine-ui/core/time-panel';
import clsx from 'clsx';
import { toCssLength } from '../_internal/css-length';
import { getNumericCSSVariablePixelValue } from '../_internal/css-variable';
import MznScrollbar from '../scrollbar/scrollbar.vue';
import type { TimePanelColumnProps } from './time-panel-column.types';

/**
 * 時間面板的單一欄位（時、分或秒）。
 *
 * 上下各補三個佔位格，讓選中的單位可以捲到欄位中央；`cellHeight` 未指定時取
 * `--mzn-spacing-size-element-loose` 的計算值。第一次定位不帶動畫，之後才平滑捲動。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznTimePanelColumn } from '@mezzanine-ui/vue/time-panel';
 * <\/script>
 *
 * <template>
 *   <MznTimePanelColumn :active-unit="8" :units="units" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznTimePanel 由三個欄位組成的時間面板
 */
const props = withDefaults(defineProps<TimePanelColumnProps>(), {
  activeUnit: undefined,
  cellHeight: undefined,
});

const emit = defineEmits<{
  change: [unit: TimePanelUnit];
}>();

const cellHeight = computed(
  (): number =>
    props.cellHeight ??
    getNumericCSSVariablePixelValue('--mzn-spacing-size-element-loose'),
);

const viewport = ref<HTMLDivElement | null>(null);
const preferSmoothScroll = ref(true);

function scrollToTarget(element: HTMLDivElement): void {
  const activeIndex = props.units.findIndex(
    ({ value }) => value === props.activeUnit,
  );

  element.scrollTo({
    behavior: preferSmoothScroll.value ? 'auto' : 'smooth',
    top: activeIndex * cellHeight.value,
  });

  preferSmoothScroll.value = false;
}

function handleViewportReady(element: HTMLDivElement): void {
  viewport.value = element;

  scrollToTarget(element);
}

onMounted(() => {
  if (viewport.value) scrollToTarget(viewport.value);
});

watch([() => props.activeUnit, cellHeight, () => props.units], () => {
  if (viewport.value) scrollToTarget(viewport.value);
});

// Number of padding cells needed for centering (3 cells above and below the center position)
const paddingCellCount = 3;
const placeholders = Array.from({ length: paddingCellCount }, (_, i) => i);

const placeholderStyle = computed(() => ({
  height: toCssLength(cellHeight.value),
}));

const maxHeight = computed((): number => cellHeight.value * 7);

const buttonClasses = (unit: TimePanelUnit): string =>
  clsx(classes.button, classes.columnButton, {
    [classes.buttonActive]: unit.value === props.activeUnit,
  });

const columnClass = classes.column;
const placeholderClass = classes.columnPlaceholder;
</script>

<template>
  <div :class="columnClass">
    <MznScrollbar :max-height="maxHeight" @viewport-ready="handleViewportReady">
      <div
        v-for="index in placeholders"
        :key="`placeholder-top-${index}`"
        aria-hidden="true"
        :class="placeholderClass"
        :style="placeholderStyle"
      />
      <button
        v-for="unit in units"
        :key="unit.value"
        :class="buttonClasses(unit)"
        type="button"
        @click="emit('change', unit)"
      >
        {{ unit.label }}
      </button>
      <div
        v-for="index in placeholders"
        :key="`placeholder-bottom-${index}`"
        aria-hidden="true"
        :class="placeholderClass"
        :style="placeholderStyle"
      />
    </MznScrollbar>
  </div>
</template>

// packages/ng/time-panel/time-panel-column.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  effect,
  ElementRef,
  input,
  output,
  viewChild,
} from '@angular/core';
import {
  TimePanelUnit,
  timePanelClasses as classes,
} from '@mezzanine-ui/core/time-panel';
import { scrollbarClasses } from '@mezzanine-ui/core/scrollbar';
import clsx from 'clsx';

/**
 * 時間面板的單一欄位元件（時/分/秒），可滾動選取。
 *
 * @example
 * ```html
 * <mzn-time-panel-column
 *   [units]="hourUnits"
 *   [activeUnit]="currentHour"
 *   (unitChanged)="onHourChange($event)"
 * />
 * ```
 */
@Component({
  selector: 'mzn-time-panel-column',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'columnClass',
  },
  template: `
    <div
      #scrollContainer
      [class]="scrollClass"
      [style.max-height.px]="cellHeight() * 7"
      style="overflow-y: auto"
    >
      @for (ph of paddings; track $index) {
        <div
          [class]="placeholderClass"
          [style.height.px]="cellHeight()"
          aria-hidden="true"
        ></div>
      }
      @for (unit of units(); track unit.value) {
        <button
          type="button"
          [class]="getButtonClass(unit)"
          (click)="onSelect(unit)"
          >{{ unit.label }}</button
        >
      }
      @for (ph of paddings; track $index) {
        <div
          [class]="placeholderClass"
          [style.height.px]="cellHeight()"
          aria-hidden="true"
        ></div>
      }
    </div>
  `,
})
export class MznTimePanelColumn implements AfterViewInit {
  /** 可選單位列表。 */
  readonly units = input.required<ReadonlyArray<TimePanelUnit>>();

  /** 目前選取值。 */
  readonly activeUnit = input<number | undefined>(undefined);

  /**
   * 每個儲存格的高度（px），用於控制捲動位置。
   * @default 32
   */
  readonly cellHeight = input(32);

  /** 單位變更事件。 */
  readonly unitChanged = output<TimePanelUnit>();
  protected readonly paddings = [0, 1, 2]; // 3 placeholder cells

  protected readonly columnClass = classes.column;
  protected readonly scrollClass = scrollbarClasses.host;
  protected readonly placeholderClass = classes.columnPlaceholder;

  private readonly scrollContainer =
    viewChild<ElementRef<HTMLDivElement>>('scrollContainer');

  ngAfterViewInit(): void {
    this.scrollToActive('auto');
  }

  constructor() {
    effect(() => {
      this.activeUnit(); // track
      this.scrollToActive('smooth');
    });
  }

  protected getButtonClass(unit: TimePanelUnit): string {
    return clsx(classes.button, classes.columnButton, {
      [classes.buttonActive]: unit.value === this.activeUnit(),
    });
  }

  protected onSelect(unit: TimePanelUnit): void {
    this.unitChanged.emit(unit);
  }

  private scrollToActive(behavior: ScrollBehavior): void {
    const container = this.scrollContainer()?.nativeElement;
    if (!container) return;

    const active = this.activeUnit();
    if (active === undefined) return;

    const units = this.units();
    const idx = units.findIndex((u) => u.value === active);
    if (idx < 0) return;

    const height = this.cellHeight();

    if (typeof container.scrollTo === 'function') {
      container.scrollTo({
        behavior,
        top: idx * height,
      });
    } else {
      container.scrollTop = idx * height;
    }
  }
}
