// packages/vue/transition/scale.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { useTransitionImplementation } from './use-transition-implementation';
import type { TransitionRunnerConfig } from './transition-styles';
import type { ScaleProps } from './scale.types';

/**
 * 縮放轉場：進場時從 95% 放大並淡入，離場時反向。
 *
 * 進場結束後 `transform` 會設回 `none` 而不是 `scale(1)`，與 React 一致 ——
 * 留著 transform 會讓子元素建立新的 containing block，影響固定定位的內容。
 *
 * @example
 * ```vue
 * <MznScale :in="visible" transform-origin="top left">
 *   <div>內容</div>
 * </MznScale>
 * ```
 *
 * @see MznFade 純淡入淡出
 */
const props = withDefaults(defineProps<ScaleProps>(), {
  appear: true,
  delay: 0,
  duration: () => ({
    enter: MOTION_DURATION.moderate,
    exit: MOTION_DURATION.moderate,
  }),
  easing: () => ({
    enter: MOTION_EASING.entrance,
    exit: MOTION_EASING.exit,
  }),
  in: false,
  keepMount: false,
  lazyMount: true,
  transformOrigin: 'center',
});

const emit = defineEmits<{
  enter: [node: HTMLElement, isAppearing: boolean];
  entered: [node: HTMLElement, isAppearing: boolean];
  entering: [node: HTMLElement, isAppearing: boolean];
  exit: [node: HTMLElement];
  exited: [node: HTMLElement];
  exiting: [node: HTMLElement];
}>();

defineSlots<{
  default?: () => unknown;
}>();

const config = computed(
  (): TransitionRunnerConfig => ({
    base: { transformOrigin: props.transformOrigin },
    delay: props.delay,
    duration:
      props.duration === 'auto'
        ? { enter: MOTION_DURATION.moderate, exit: MOTION_DURATION.moderate }
        : props.duration,
    easing: props.easing,
    entered: { opacity: 1, transform: 'none' },
    entering: { opacity: 1, transform: 'scale(1)' },
    exited: { opacity: 0, transform: 'scale(0.95)' },
    properties: ['opacity', 'transform'],
  }),
);

const slots = useSlots();

const { TransitionChild, onAppear, onEnter, onLeave, shown } =
  useTransitionImplementation({
    child: () => slots.default?.(),
    config: () => config.value,
    in: () => props.in,
    keepMount: () => props.keepMount,
    lazyMount: () => props.lazyMount,
    on: {
      enter: (node, isAppearing) => emit('enter', node, isAppearing),
      entered: (node, isAppearing) => emit('entered', node, isAppearing),
      entering: (node, isAppearing) => emit('entering', node, isAppearing),
      exit: (node) => emit('exit', node),
      exited: (node) => emit('exited', node),
      exiting: (node) => emit('exiting', node),
    },
  });
</script>

<template>
  <Transition
    :appear="appear"
    :css="false"
    @appear="onAppear"
    @enter="onEnter"
    @leave="onLeave"
  >
    <TransitionChild v-if="shown" />
  </Transition>
</template>

// packages/react/src/Transition/Scale.tsx
import { cloneElement, CSSProperties, forwardRef, useRef } from 'react';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { useComposeRefs } from '../hooks/useComposeRefs';
import Transition, {
  TransitionImplementationProps,
  TransitionProps,
  TransitionState,
} from './Transition';
import { getAutoSizeDuration } from './getAutoSizeDuration';
import { reflow } from './reflow';
import { useAutoTransitionDuration } from './useAutoTransitionDuration';
import { useSetNodeTransition } from './useSetNodeTransition';

function getScale(value: number) {
  return `scale(${value})`;
}

function getStyle(state: TransitionState): CSSProperties {
  if (state === 'entering') {
    return {
      opacity: 1,
      transform: getScale(1),
    };
  }

  if (state === 'entered') {
    return {
      opacity: 1,
      transform: 'none',
    };
  }

  return {
    opacity: 0,
    transform: getScale(0.95),
  };
}

const defaultDuration = {
  enter: MOTION_DURATION.moderate,
  exit: MOTION_DURATION.moderate,
};

const defaultEasing = {
  enter: MOTION_EASING.entrance,
  exit: MOTION_EASING.exit,
};

export interface ScaleProps extends TransitionImplementationProps {
  /**
   * The transform origin for child element.
   * @default 'center'
   */
  transformOrigin?: string;
}

/**
 * The react component for `mezzanine` transition scale.
 */
const Scale = forwardRef<HTMLElement, ScaleProps>(function Scale(
  props: ScaleProps,
  ref,
) {
  const {
    appear,
    children,
    delay = 0,
    duration: durationProp = defaultDuration,
    easing = defaultEasing,
    in: inProp,
    onEnter,
    onEntered,
    onExit,
    onExited,
    transformOrigin = 'center',
    ...rest
  } = props;
  const duration = durationProp === 'auto' ? defaultDuration : durationProp;
  const { autoTransitionDurationRef, addEndListener } =
    useAutoTransitionDuration(duration);
  const nodeRef = useRef<HTMLElement>(null);
  const [setNodeTransition, resetNodeTransition] = useSetNodeTransition(
    {
      delay,
      duration,
      easing,
      properties: [
        'opacity',
        [
          'transform',
          (transitionProps) => {
            const { delay: delayProp, duration: durationProp } =
              transitionProps;

            return {
              ...transitionProps,
              delay: delayProp,
              duration: durationProp,
            };
          },
        ],
      ],
      resolveAutoDuration: () => {
        const autoSizeDuration = getAutoSizeDuration(
          nodeRef.current?.clientHeight ?? 0,
        );

        autoTransitionDurationRef.current = autoSizeDuration;

        return autoSizeDuration;
      },
    },
    children?.props.style,
  );
  const composedNodeRef = useComposeRefs([ref, nodeRef]);
  const transitionProps: TransitionProps = {
    ...rest,
    addEndListener,
    appear,
    duration,
    in: inProp,
    nodeRef,

    onEnter(node, isAppearing) {
      setNodeTransition(node, 'enter');
      reflow(node);

      if (onEnter) {
        onEnter(node, isAppearing);
      }
    },
    onEntered(node, isAppearing) {
      resetNodeTransition(node);

      if (onEntered) {
        onEntered(node, isAppearing);
      }
    },
    onExit(node) {
      setNodeTransition(node, 'exit');

      if (onExit) {
        onExit(node);
      }
    },
    onExited(node) {
      resetNodeTransition(node);

      if (onExited) {
        onExited(node);
      }
    },
  };

  return (
    <Transition {...transitionProps}>
      {children &&
        ((state) =>
          cloneElement(children, {
            ...children.props,
            ref: composedNodeRef,
            style: {
              visibility: state === 'exited' && !inProp ? 'hidden' : undefined,
              ...getStyle(state),
              transformOrigin,
              ...children.props.style,
            },
          }))}
    </Transition>
  );
});

export default Scale;
