// packages/react/src/Card/FourThumbnailCardSkeleton.tsx
'use client';

import { forwardRef } from 'react';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Skeleton from '../Skeleton';

export interface FourThumbnailCardSkeletonProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'> {
  /**
   * Width of the card skeleton container.
   * @default 200
   */
  thumbnailWidth?: number | string;
}

/**
 * Skeleton placeholder for FourThumbnailCard component.
 * Renders a skeleton that mimics the FourThumbnailCard layout.
 */
const FourThumbnailCardSkeleton = forwardRef<
  HTMLDivElement,
  FourThumbnailCardSkeletonProps
>(function FourThumbnailCardSkeleton(props, ref) {
  const { className, thumbnailWidth = 200, ...rest } = props;

  return (
    <div {...rest} ref={ref} className={cx(classes.thumbnail, className)}>
      <div className={classes.fourThumbnail}>
        {Array.from({ length: 4 }, (_, index) => (
          <Skeleton
            key={index}
            className={classes.fourThumbnailThumbnail}
            width={thumbnailWidth}
            // For four-thumbnail layout, force to '4/3' to maintain the grid layout.
            style={{ aspectRatio: '4/3' }}
          />
        ))}
      </div>
      <div className={classes.thumbnailInfo}>
        <div className={classes.thumbnailInfoMain}>
          <div
            className={classes.thumbnailInfoContent}
            style={{ width: '100%' }}
          >
            <Skeleton height={20} width="100%" />
            <Skeleton height={16} width="100%" />
          </div>
        </div>
      </div>
    </div>
  );
});

FourThumbnailCardSkeleton.displayName = 'FourThumbnailCardSkeleton';

export default FourThumbnailCardSkeleton;

// packages/vue/card/four-thumbnail-card-skeleton.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue';
import { cardClasses as classes } from '@mezzanine-ui/core/card';
import MznSkeleton from '../skeleton/skeleton.vue';
import type { FourThumbnailCardSkeletonProps } from './four-thumbnail-card-skeleton.types';

/**
 * MznFourThumbnailCard 的載入佔位版本。
 *
 * @see MznCardGroup loading 時渲染這一個
 */
withDefaults(defineProps<FourThumbnailCardSkeletonProps>(), {
  thumbnailWidth: 200,
});

// For four-thumbnail layout, force to '4/3' to maintain the grid layout.
const THUMBNAIL_STYLE: CSSProperties = { aspectRatio: '4/3' };
const CONTENT_STYLE: CSSProperties = { width: '100%' };

const SLOTS = [0, 1, 2, 3];

const gridClass = classes.fourThumbnail;
const hostClass = classes.thumbnail;
const infoClass = classes.thumbnailInfo;
const infoContentClass = classes.thumbnailInfoContent;
const infoMainClass = classes.thumbnailInfoMain;
const thumbnailClass = classes.fourThumbnailThumbnail;
</script>

<template>
  <div :class="hostClass">
    <div :class="gridClass">
      <MznSkeleton
        v-for="index in SLOTS"
        :key="index"
        :class="thumbnailClass"
        :style="THUMBNAIL_STYLE"
        :width="thumbnailWidth"
      />
    </div>
    <div :class="infoClass">
      <div :class="infoMainClass">
        <div :class="infoContentClass" :style="CONTENT_STYLE">
          <MznSkeleton :height="20" width="100%" />
          <MznSkeleton :height="16" width="100%" />
        </div>
      </div>
    </div>
  </div>
</template>
