// packages/vue/date-picker/date-picker.vue
<script setup lang="ts">
import { computed, ref, useAttrs, watch } from 'vue';
import type { ComponentPublicInstance } from 'vue';
import {
  getDefaultModeFormat,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import { pickerClasses } from '@mezzanine-ui/core/picker';
import { isImeComposing } from '@mezzanine-ui/core/utils';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { resolveElement } from '../_internal/resolve-element';
import { useCalendarContext } from '../calendar/calendar-context';
import MznIcon from '../icon/icon.vue';
import MznPickerTrigger from '../picker/picker-trigger.vue';
import { usePickerDocumentEventClose } from '../picker/use-picker-document-event-close';
import { usePickerValue } from '../picker/use-picker-value';
import MznDatePickerCalendar from './date-picker-calendar.vue';
import type { DatePickerProps } from './date-picker.types';

/**
 * 日期選擇器，點擊輸入框或日曆圖示開啟日曆浮層。
 *
 * 支援 `day`、`week`、`month`、`quarter`、`half-year`、`year` 六種模式，
 * 可用 `isDateDisabled` 等 predicate 限制可選範圍；輸入框本身是遮罩輸入，
 * 不符合限制的輸入會在失焦時清掉。受控（`value`）與非受控（`defaultValue`）皆可。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDatePicker } from '@mezzanine-ui/vue/date-picker';
 * <\/script>
 *
 * <template>
 *   <MznDatePicker :value="value" @change="onChange" />
 *   <MznDatePicker mode="month" :is-month-disabled="isPast" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznCalendar 日曆本體
 * @see MznTimePicker 時間選擇器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DatePickerProps>(), {
  calendarProps: undefined,
  clearable: true,
  defaultValue: undefined,
  disableOnDoubleNext: undefined,
  disableOnDoublePrev: undefined,
  disableOnNext: undefined,
  disableOnPrev: undefined,
  disabled: false,
  disabledMonthSwitch: false,
  disabledYearSwitch: false,
  displayMonthLocale: undefined,
  error: false,
  errorMessages: undefined,
  fadeProps: undefined,
  format: undefined,
  fullWidth: false,
  hoverValue: undefined,
  inputProps: undefined,
  isDateDisabled: undefined,
  isHalfYearDisabled: undefined,
  isMonthDisabled: undefined,
  isQuarterDisabled: undefined,
  isWeekDisabled: undefined,
  isYearDisabled: undefined,
  mode: 'day',
  placeholder: undefined,
  popperProps: undefined,
  readOnly: undefined,
  referenceDate: undefined,
  required: false,
  validate: undefined,
  value: undefined,
});

const emit = defineEmits<{
  calendarToggle: [open: boolean];
  change: [target?: DateType];
  hover: [date: DateType];
  leave: [];
}>();

defineSlots<{
  /** The trigger's prefix. */
  prefix?: () => unknown;
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const format = computed(
  (): string => props.format || getDefaultModeFormat(props.mode),
);

/**
 * Validate date value against disabled constraints based on mode.
 * Returns true if valid, false if the date is disabled.
 */
function validateDate(isoDate: string): boolean {
  switch (props.mode) {
    case 'day':
      return !props.isDateDisabled?.(isoDate);
    case 'week':
      return !props.isWeekDisabled?.(isoDate);
    case 'month':
      return !props.isMonthDisabled?.(isoDate);
    case 'quarter':
      return !props.isQuarterDisabled?.(isoDate);
    case 'year':
      return !props.isYearDisabled?.(isoDate);
    case 'half-year':
      return !props.isHalfYearDisabled?.(isoDate);
    default:
      return true;
  }
}

/** Calender display control */
const open = ref(false);

function onCalendarToggle(currentOpen: boolean): void {
  if (props.readOnly) return;

  emit('calendarToggle', currentOpen);
  open.value = currentOpen;
}

function onFocus(): void {
  if (props.readOnly) return;

  onCalendarToggle(true);
}

/** Value and change handlers */
const trigger = ref<InstanceType<typeof MznPickerTrigger> | null>(null);
const pickerCalendar = ref<InstanceType<typeof MznDatePickerCalendar> | null>(
  null,
);
const inputRef = computed(
  (): HTMLInputElement | null => trigger.value?.input ?? null,
);
const anchorRef = computed((): HTMLElement | null =>
  resolveElement(trigger.value as ComponentPublicInstance | null),
);
const calendarRef = computed(
  (): HTMLElement | null => pickerCalendar.value?.element ?? null,
);

const {
  inputValue,
  onBlur,
  onChange,
  onInputChange,
  onKeydown,
  value: internalValue,
} = usePickerValue({
  defaultValue: props.defaultValue,
  format,
  inputRef,
  value: () => props.value,
});

/** Bind close control to handlers */
function onCalendarChange(val: DateType): void {
  onChange(val);
  emit('change', val);
  onCalendarToggle(false);
}

function onKeyDownWithCloseControl(event: KeyboardEvent): void {
  onKeydown(event);

  if (event.key === 'Enter' && !isImeComposing(event)) {
    emit('change', internalValue.value);
    onCalendarToggle(false);
  }
}

/** Hover preview value for calendar */
const hoverDate = ref<DateType | undefined>(undefined);

/** using internal reference date */
const referenceDate = ref<DateType>(
  props.referenceDate || props.defaultValue || calendar.value.getNow(),
);

watch(internalValue, (value) => {
  if (value) {
    referenceDate.value = value;
  }
});

/** Resolve input props */
const inputSize = computed(
  (): number | string => props.inputProps?.size ?? format.value.length + 2,
);

const resolvedInputProps = computed(() => ({
  ...props.inputProps,
  size: inputSize.value,
  onBlur,
  onFocus,
  onKeydown: onKeyDownWithCloseControl,
}));

/** Clear handler */
function onClear(): void {
  onChange(undefined);
  emit('change', undefined);
}

/** Blur, click away and key down close */
function onClose(): void {
  onChange(props.value);
  onCalendarToggle(false);
}

function onChangeClose(): void {
  emit('change', internalValue.value);
  onCalendarToggle(false);
}

usePickerDocumentEventClose({
  anchorRef,
  lastElementRefInFlow: inputRef,
  onChangeClose,
  onClose,
  open,
  popperRef: calendarRef,
});

/** Icon */
function onIconClick(event: MouseEvent): void {
  event.stopPropagation();

  if (open.value) {
    onChange(props.value);
  }

  onCalendarToggle(!open.value);
}

function handleTriggerChange(value: string): void {
  onInputChange({ target: { value } } as unknown as Event);
  onCalendarChange(value);
  onCalendarToggle(true);
}

const hoverDisplayValue = computed((): string | undefined =>
  open.value && !inputValue.value && hoverDate.value
    ? (calendar.value.formatToString(
        calendar.value.locale,
        hoverDate.value,
        format.value,
      ) ?? undefined)
    : undefined,
);

const anchorGetter = (): HTMLElement | null => anchorRef.value;
const hostDateClass = pickerClasses.hostDate;
</script>

<template>
  <MznPickerTrigger
    ref="trigger"
    v-bind="attrs"
    :class="hostDateClass"
    :clearable="clearable"
    :disabled="disabled"
    :error="error"
    :error-messages="errorMessages"
    :force-show-clearable="!!internalValue"
    :format="format"
    :full-width="fullWidth"
    :hide-suffix-when-clearable="clearable"
    :hover-value="hoverDisplayValue"
    :input-props="resolvedInputProps"
    :placeholder="placeholder"
    :read-only="readOnly"
    :required="required"
    :size="size"
    :validate="validateDate"
    :value="inputValue"
    :warning="warning"
    @change="handleTriggerChange"
    @clear="onClear"
  >
    <template v-if="$slots.prefix" #prefix><slot name="prefix" /></template>
    <template #suffix>
      <MznIcon
        aria-label="Open calendar"
        :icon="CalendarIcon"
        v-on="readOnly ? {} : { click: onIconClick }"
      />
    </template>
  </MznPickerTrigger>
  <MznDatePickerCalendar
    ref="pickerCalendar"
    :anchor="anchorGetter"
    :calendar-props="calendarProps"
    :disable-on-double-next="disableOnDoubleNext"
    :disable-on-double-prev="disableOnDoublePrev"
    :disable-on-next="disableOnNext"
    :disable-on-prev="disableOnPrev"
    :disabled-month-switch="disabledMonthSwitch"
    :disabled-year-switch="disabledYearSwitch"
    :display-month-locale="displayMonthLocale"
    :fade-props="fadeProps"
    :is-date-disabled="isDateDisabled"
    :is-half-year-disabled="isHalfYearDisabled"
    :is-month-disabled="isMonthDisabled"
    :is-quarter-disabled="isQuarterDisabled"
    :is-week-disabled="isWeekDisabled"
    :is-year-disabled="isYearDisabled"
    :mode="mode"
    :open="open"
    :popper-props="popperProps"
    :reference-date="referenceDate"
    :value="internalValue"
    @change="onCalendarChange"
    @hover="
      (date) => {
        hoverDate = date;
        emit('hover', date);
      }
    "
    @leave="
      () => {
        hoverDate = undefined;
        emit('leave');
      }
    "
  />
</template>

// packages/ng/date-picker/date-picker.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  input,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import {
  CalendarMode,
  DateType,
  getDefaultModeFormat,
} from '@mezzanine-ui/core/calendar';
import { pickerClasses } from '@mezzanine-ui/core/picker';
import { TextFieldSize } from '@mezzanine-ui/core/text-field';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { MZN_CALENDAR_CONFIG } from '@mezzanine-ui/ng/calendar';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznPickerTrigger } from '@mezzanine-ui/ng/picker';
import { provideValueAccessor } from '@mezzanine-ui/ng/utils';
import { MznDatePickerCalendar } from './date-picker-calendar.component';

/**
 * 日期選擇器元件，點擊輸入框開啟日曆彈出層。
 *
 * 支援 day/week/month/year/quarter/half-year 等模式。
 * 實作 ControlValueAccessor，可搭配 Angular Forms 使用。
 *
 * @example
 * ```html
 * import { MznDatePicker } from '@mezzanine-ui/ng/date-picker';
 *
 * <mzn-date-picker
 *   [(ngModel)]="selectedDate"
 *   mode="day"
 *   placeholder="Select date"
 * />
 * ```
 *
 * @see {@link MznCalendar} 日曆元件
 * @see {@link MznDateRangePicker} 日期範圍選擇器
 */
@Component({
  selector: 'mzn-date-picker',
  standalone: true,
  imports: [MznDatePickerCalendar, MznIcon, MznPickerTrigger],
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [provideValueAccessor(MznDatePicker)],
  template: `
    <mzn-picker-trigger
      #triggerEl
      [format]="resolvedFormat()"
      [value]="displayValue()"
      [placeholder]="placeholder()"
      [disabled]="disabled()"
      [readOnly]="readOnly()"
      [clearable]="clearable()"
      [error]="error()"
      [fullWidth]="fullWidth()"
      [hostClassModifier]="dateHostClass"
      [size]="size()"
      [validate]="validateFn()"
      (inputFocused)="openCalendar()"
      (cleared)="onClear()"
      (inputKeydown)="onKeydown($event)"
      (valueChanged)="onTriggerValueChange($event)"
    >
      <i
        mznIcon
        suffix
        [icon]="calendarIcon"
        (click)="toggleCalendar($event)"
      ></i>
    </mzn-picker-trigger>
    <mzn-date-picker-calendar
      [anchor]="triggerElement()"
      [open]="isOpen()"
      [mode]="mode()"
      [referenceDate]="internalReferenceDate()"
      [value]="internalValue()"
      [disabledMonthSwitch]="disabledMonthSwitch()"
      [disabledYearSwitch]="disabledYearSwitch()"
      [disableOnNext]="disableOnNext()"
      [disableOnPrev]="disableOnPrev()"
      [disableOnDoubleNext]="disableOnDoubleNext()"
      [disableOnDoublePrev]="disableOnDoublePrev()"
      [displayMonthLocale]="displayMonthLocale()"
      [displayWeekDayLocale]="displayWeekDayLocale()"
      [isDateDisabled]="isDateDisabled()"
      [isHalfYearDisabled]="isHalfYearDisabled()"
      [isMonthDisabled]="isMonthDisabled()"
      [isQuarterDisabled]="isQuarterDisabled()"
      [isWeekDisabled]="isWeekDisabled()"
      [isYearDisabled]="isYearDisabled()"
      (dateChanged)="onCalendarChange($event)"
    />
  `,
})
export class MznDatePicker implements ControlValueAccessor {
  private readonly config = inject(MZN_CALENDAR_CONFIG);

  /** 是否可清除。 @default true */
  readonly clearable = input(true);

  /** 是否禁用。 @default false */
  readonly disabled = input(false);

  /** 禁用日曆控制列的「向後跳兩個月/年」按鈕。 @default false */
  readonly disableOnDoubleNext = input(false);

  /** 禁用日曆控制列的「向前跳兩個月/年」按鈕。 @default false */
  readonly disableOnDoublePrev = input(false);

  /** 禁用日曆控制列的「向後一個月/年」按鈕。 @default false */
  readonly disableOnNext = input(false);

  /** 禁用日曆控制列的「向前一個月/年」按鈕。 @default false */
  readonly disableOnPrev = input(false);

  /** 是否禁用月份切換按鈕。 @default false */
  readonly disabledMonthSwitch = input(false);

  /** 是否禁用年份切換按鈕。 @default false */
  readonly disabledYearSwitch = input(false);

  /** 顯示月份標題的語系。 */
  readonly displayMonthLocale = input<string | undefined>(undefined);

  /** 顯示星期列標題的語系。 */
  readonly displayWeekDayLocale = input<string | undefined>(undefined);

  /** 是否有錯誤。 @default false */
  readonly error = input(false);

  /** 顯示格式。 */
  readonly format = input<string | undefined>(undefined);

  /** 是否全寬。 @default false */
  readonly fullWidth = input(false);

  readonly isDateDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );
  readonly isHalfYearDisabled = input<
    ((date: DateType) => boolean) | undefined
  >(undefined);
  readonly isMonthDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );
  readonly isQuarterDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );
  readonly isWeekDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );
  readonly isYearDisabled = input<((date: DateType) => boolean) | undefined>(
    undefined,
  );

  /** 日曆模式。 @default 'day' */
  readonly mode = input<CalendarMode>('day');

  /** 尺寸。 @default 'main' */
  readonly size = input<TextFieldSize>('main');

  /** 佔位文字。 */
  readonly placeholder = input('');

  /** 是否唯讀。 @default false */
  readonly readOnly = input(false);

  /** 參考日期。 */
  readonly referenceDate = input<DateType | undefined>(undefined);

  /** 外部值（受控模式）。 */
  readonly value = input<DateType | undefined>(undefined);

  /** 日期變更事件。 */
  readonly dateChanged = output<DateType | undefined>();
  /** 日曆開關事件。 */
  readonly calendarToggled = output<boolean>();

  protected readonly calendarIcon = CalendarIcon;
  protected readonly dateHostClass = pickerClasses.hostDate;

  private readonly triggerRef = viewChild<MznPickerTrigger, ElementRef>(
    'triggerEl',
    { read: ElementRef },
  );

  protected readonly triggerElement = computed(() => this.triggerRef());

  readonly isOpen = signal(false);
  readonly internalValue = signal<DateType | undefined>(undefined);
  readonly internalReferenceDate = signal<DateType>('');

  protected readonly resolvedFormat = computed(
    () => this.format() ?? getDefaultModeFormat(this.mode()),
  );

  protected readonly formatLength = computed(
    () => this.resolvedFormat().length + 2,
  );

  protected readonly displayValue = computed(() => {
    const val = this.internalValue();
    if (!val) return '';
    return this.config.formatToString(
      this.config.locale,
      val,
      this.resolvedFormat(),
    );
  });

  /**
   * Validate predicate passed to MznPickerTrigger.
   * Combines isDateDisabled / isMonthDisabled / isYearDisabled / isWeekDisabled
   * / isQuarterDisabled / isHalfYearDisabled to reject typed input that
   * resolves to a disabled date.
   */
  protected readonly validateFn = computed(
    (): ((isoDate: string) => boolean) | undefined => {
      const checks = [
        this.isDateDisabled(),
        this.isMonthDisabled(),
        this.isYearDisabled(),
        this.isWeekDisabled(),
        this.isQuarterDisabled(),
        this.isHalfYearDisabled(),
      ].filter((fn): fn is (date: DateType) => boolean => !!fn);

      if (checks.length === 0) return undefined;

      return (isoDate: string): boolean => {
        const c = this.config;
        const parsed = c.parseFormattedValue(
          isoDate,
          this.resolvedFormat(),
          c.locale,
        );
        if (!parsed) return false;
        return !checks.some((fn) => fn(parsed));
      };
    },
  );

  private onChange: ((value: DateType | undefined) => void) | null = null;
  private onTouched: (() => void) | null = null;

  constructor() {
    // Sync external value to internal
    effect(() => {
      const v = this.value();
      if (v !== undefined) {
        this.internalValue.set(v);
      }
    });

    // Sync internal value to reference date
    effect(() => {
      const v = this.internalValue();
      if (v) {
        this.internalReferenceDate.set(v);
      }
    });

    // Init reference date
    effect(() => {
      const ref = this.referenceDate();
      if (ref) {
        this.internalReferenceDate.set(ref);
      } else if (!this.internalReferenceDate()) {
        this.internalReferenceDate.set(this.config.getNow());
      }
    });
  }

  writeValue(value: DateType | undefined): void {
    this.internalValue.set(value ?? undefined);
    if (value) {
      this.internalReferenceDate.set(value);
    }
  }

  registerOnChange(fn: (value: DateType | undefined) => void): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouched = fn;
  }

  protected openCalendar(): void {
    if (this.readOnly() || this.disabled()) return;
    this.isOpen.set(true);
    this.calendarToggled.emit(true);
  }

  protected toggleCalendar(event: Event): void {
    event.stopPropagation();
    if (this.readOnly() || this.disabled()) return;

    const next = !this.isOpen();
    this.isOpen.set(next);
    this.calendarToggled.emit(next);
  }

  /**
   * Handle typed-input changes from MznPickerTrigger.
   * Parses the formatted string and commits if it resolves to a valid,
   * non-disabled date. Mirrors React DatePicker.onInputChange path.
   */
  protected onTriggerValueChange({
    isoValue,
  }: {
    isoValue: string;
    rawDigits: string;
  }): void {
    if (!isoValue) return;
    const c = this.config;
    const parsed = c.parseFormattedValue(
      isoValue,
      this.resolvedFormat(),
      c.locale,
    );
    if (!parsed) return;
    const validate = this.validateFn();
    if (validate && !validate(isoValue)) return;
    this.internalValue.set(parsed);
    this.internalReferenceDate.set(parsed);
    this.onChange?.(parsed);
    this.dateChanged.emit(parsed);
    this.onTouched?.();
  }

  protected onCalendarChange(date: DateType): void {
    this.internalValue.set(date);
    this.onChange?.(date);
    this.dateChanged.emit(date);
    this.isOpen.set(false);
    this.calendarToggled.emit(false);
    this.onTouched?.();
  }

  protected onClear(): void {
    this.internalValue.set(undefined);
    this.onChange?.(undefined);
    this.dateChanged.emit(undefined);
    this.onTouched?.();
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.isOpen.set(false);
      this.calendarToggled.emit(false);
    }
    if (event.key === 'Enter') {
      this.isOpen.set(false);
      this.calendarToggled.emit(false);
    }
  }
}
