// packages/ng/cascader/cascader-panel.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { cascaderClasses as classes } from '@mezzanine-ui/core/cascader';
import { ChevronRightIcon, CheckedIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';

import { MznIcon } from '@mezzanine-ui/ng/icon';
import { CascaderOption } from './cascader-option';

/**
 * 串接式選單的單欄面板，用於顯示單一層級的選項清單。
 *
 * 每個選項可包含子選項（顯示右箭頭圖示）或為葉節點（選取後顯示勾選圖示）。
 * 此元件通常由 `MznCascader` 內部使用，不建議單獨使用。
 *
 * @example
 * ```html
 * import { MznCascaderPanel } from '@mezzanine-ui/ng/cascader';
 *
 * <mzn-cascader-panel
 *   [options]="options"
 *   [activeOptionId]="'option-1'"
 *   (optionSelect)="onSelect($event)"
 * />
 * ```
 *
 * @see MznCascader
 */
@Component({
  selector: 'mzn-cascader-panel',
  standalone: true,
  imports: [MznIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
  },
  template: `
    @for (option of options(); track option.id) {
      <div [class]="getItemClasses(option)" (click)="onItemClick(option)">
        <span [class]="labelClass">{{ option.name }}</span>
        <span [class]="appendClass">
          @if (option.children?.length) {
            <i mznIcon [icon]="chevronRightIcon"></i>
          } @else if (isSelected(option)) {
            <i mznIcon [icon]="checkedIcon"></i>
          }
        </span>
      </div>
    }
  `,
})
export class MznCascaderPanel {
  /** 目前展開（active）的選項 ID。 */
  readonly activeOptionId = input<string>();

  /** 目前聚焦的選項 ID。 */
  readonly focusedOptionId = input<string>();

  /** 此面板顯示的選項清單。 */
  readonly options = input<CascaderOption[]>([]);

  /** 已選取的葉節點選項 ID。 */
  readonly selectedOptionId = input<string>();

  /** 當使用者點選選項時發出。 */
  readonly optionSelect = output<CascaderOption>();

  protected readonly chevronRightIcon = ChevronRightIcon;
  protected readonly checkedIcon = CheckedIcon;

  protected readonly labelClass = classes.itemLabel;
  protected readonly appendClass = classes.itemAppend;

  protected readonly hostClasses = computed((): string => clsx(classes.panel));

  protected getItemClasses(option: CascaderOption): string {
    return clsx(classes.item, {
      [classes.itemActive]: this.activeOptionId() === option.id,
      [classes.itemDisabled]: option.disabled,
      [classes.itemFocused]: this.focusedOptionId() === option.id,
      [classes.itemSelected]: this.isSelected(option),
    });
  }

  protected isSelected(option: CascaderOption): boolean {
    return this.selectedOptionId() === option.id;
  }

  protected onItemClick(option: CascaderOption): void {
    if (option.disabled) {
      return;
    }

    this.optionSelect.emit(option);
  }
}

// packages/vue/cascader/cascader-panel.vue
<script setup lang="ts">
import { computed, watch } from 'vue';
import type { CSSProperties } from 'vue';
import { cascaderClasses as classes } from '@mezzanine-ui/core/cascader';
import { CheckedIcon, ChevronRightIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { toCssLength } from '../_internal/css-length';
import MznIcon from '../icon/icon.vue';
import MznScrollbar from '../scrollbar/scrollbar.vue';
import type { CascaderOption } from './cascader.types';
import type { CascaderPanelProps } from './cascader-panel.types';

/**
 * 階層選單的其中一欄。
 *
 * 每一欄是一個 listbox，選項有子項時右側顯示箭頭、是葉節點且被選取時顯示勾勾。
 * 鍵盤移動到的選項會自己捲進可視範圍。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznCascaderPanel } from '@mezzanine-ui/vue/cascader';
 * <\/script>
 *
 * <template>
 *   <MznCascaderPanel :options="options" @select="onSelect" />
 * </template>
 * ```
 *
 * @see MznCascader 把多欄排在一起的階層選擇器
 */
const props = defineProps<CascaderPanelProps>();

const emit = defineEmits<{
  /** Fired when an option is clicked; `isLeaf` says whether it ends the path. */
  select: [option: CascaderOption, isLeaf: boolean];
}>();

const toItemId = (optionId: string): string =>
  `mzn-cascader-option-${optionId}`;

watch(
  () => props.focusedId,
  (focusedId) => {
    if (!focusedId) return;

    document
      .getElementById(toItemId(focusedId))
      ?.scrollIntoView({ block: 'nearest' });
  },
  { flush: 'post' },
);

/** React appends `px` to a numeric style value; Vue leaves it invalid. */
const panelStyle = computed((): CSSProperties | undefined =>
  props.maxHeight ? { maxHeight: toCssLength(props.maxHeight) } : undefined,
);

const scrollbarStyle: CSSProperties = { flex: 1, minHeight: 0 };

interface PanelItem {
  classes: string;
  isLeaf: boolean;
  isSelected: boolean;
  itemId: string;
  option: CascaderOption;
  expanded: boolean | undefined;
}

const items = computed((): PanelItem[] =>
  props.options.map((option) => {
    const isLeaf = !option.children || option.children.length === 0;
    const isActive = option.id === props.activeId;
    const isSelected = option.id === props.selectedId;

    return {
      classes: clsx(
        classes.item,
        isActive && classes.itemActive,
        option.disabled && classes.itemDisabled,
        option.id === props.focusedId && classes.itemFocused,
        isSelected && classes.itemSelected,
      ),
      expanded: !isLeaf ? isActive : undefined,
      isLeaf,
      isSelected,
      itemId: toItemId(option.id),
      option,
    };
  }),
);

const activeDescendant = computed((): string | undefined =>
  props.focusedId ? toItemId(props.focusedId) : undefined,
);

function onSelect(option: CascaderOption, isLeaf: boolean): void {
  if (!option.disabled) emit('select', option, isLeaf);
}

function onKeydown(
  event: KeyboardEvent,
  option: CascaderOption,
  isLeaf: boolean,
): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    onSelect(option, isLeaf);
  }
}
</script>

<template>
  <div :class="classes.panel" :style="panelStyle">
    <MznScrollbar :style="scrollbarStyle">
      <ul
        :aria-activedescendant="activeDescendant"
        aria-label="Options"
        role="listbox"
        :tabindex="-1"
      >
        <li
          v-for="item in items"
          :id="item.itemId"
          :key="item.option.id"
          :aria-disabled="item.option.disabled || undefined"
          :aria-expanded="item.expanded"
          :aria-selected="item.isSelected"
          :class="item.classes"
          role="option"
          @click="onSelect(item.option, item.isLeaf)"
          @keydown="onKeydown($event, item.option, item.isLeaf)"
        >
          <span :class="classes.itemLabel">{{ item.option.name }}</span>
          <span :class="classes.itemAppend">
            <template v-if="item.isLeaf">
              <MznIcon v-if="item.isSelected" :icon="CheckedIcon" />
            </template>
            <MznIcon v-else :icon="ChevronRightIcon" />
          </span>
        </li>
      </ul>
    </MznScrollbar>
  </div>
</template>
