// packages/vue/scrollbar/scrollbar.vue
<script setup lang="ts">
import 'overlayscrollbars/overlayscrollbars.css';

import {
  computed,
  onMounted,
  useAttrs,
  type ComponentPublicInstance,
} from 'vue';
import {
  ClickScrollPlugin,
  OverlayScrollbars,
  type EventListeners,
  type PartialOptions,
} from 'overlayscrollbars';
import { OverlayScrollbarsComponent } from 'overlayscrollbars-vue';
import { scrollbarClasses as classes } from '@mezzanine-ui/core/scrollbar';
import { toCssLength } from '../_internal/css-length';
import clsx from 'clsx';
import type { ScrollbarProps } from './scrollbar.types';

/**
 * 自訂捲軸容器，在所有瀏覽器上提供一致的捲軸外觀。
 *
 * 以 OverlayScrollbars 實作，透過 `maxHeight` / `maxWidth` 限制容器尺寸並觸發捲動。
 * `disabled` 為 true 時退回原生捲軸的純 div，適合巢狀情境。
 * 初始化完成後會發出 `viewportReady`，可用來銜接虛擬捲動或拖放等外部整合。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznScrollbar } from '@mezzanine-ui/vue/scrollbar';
 * <\/script>
 *
 * <template>
 *   <MznScrollbar :max-height="300">
 *     <LongContent />
 *   </MznScrollbar>
 * </template>
 * ```
 */
const props = withDefaults(defineProps<ScrollbarProps>(), {
  defer: true,
  disabled: false,
});

const emit = defineEmits<{
  viewportReady: [viewport: HTMLDivElement, instance?: OverlayScrollbars];
}>();

defineSlots<{
  default?: () => unknown;
}>();

/**
 * React merges the consumer style *under* maxHeight/maxWidth and puts both
 * `...rest` and `className` on the scroll container. Vue's default fallthrough
 * would let the consumer style win instead, so inheritance is disabled and the
 * attributes are bound before the computed style, which restores React's
 * precedence.
 */
defineOptions({ inheritAttrs: false });

const attrs = useAttrs();

/** Register ClickScrollPlugin once (required for the clickScroll option). */
onMounted(() => {
  OverlayScrollbars.plugin(ClickScrollPlugin);
});

/**
 * In the disabled branch React forwards the plain div through a callback ref.
 * Vue's function ref is the direct equivalent: it is invoked during patch, so
 * the event fires synchronously on attach just as React's does. A `watch` on a
 * template ref would only deliver it on the next tick.
 */
function setDisabledElement(
  element: Element | ComponentPublicInstance | null,
): void {
  if (element instanceof HTMLDivElement) emit('viewportReady', element);
}

const mergedOptions = computed(
  (): PartialOptions => ({
    ...props.options,
    overflow: {
      x: 'scroll',
      y: 'scroll',
      ...props.options?.overflow,
    },
    scrollbars: {
      autoHide: 'scroll',
      autoHideDelay: 600,
      clickScroll: true,
      ...props.options?.scrollbars,
    },
  }),
);

const containerStyle = computed(() => ({
  maxHeight: toCssLength(props.maxHeight),
  maxWidth: toCssLength(props.maxWidth),
}));

const hostClasses = computed((): string => clsx(classes.host));

/**
 * React skips the events object entirely when neither `onViewportReady` nor
 * `events` is supplied. `$attrs` tells us whether a `viewportReady` listener is
 * bound, which is the same signal React reads from its props.
 */
const mergedEvents = computed((): EventListeners | undefined => {
  const { events } = props;

  if (!attrs.onViewportReady && !events) return undefined;

  const listeners = events && typeof events !== 'boolean' ? events : undefined;

  return {
    ...listeners,
    initialized: (instance: OverlayScrollbars) => {
      const { viewport } = instance.elements();

      emit('viewportReady', viewport as HTMLDivElement, instance);

      const initialized = listeners?.initialized;

      if (!initialized) return;

      if (Array.isArray(initialized)) {
        initialized.forEach((handler) => handler(instance));
      } else {
        initialized(instance);
      }
    },
  };
});
</script>

<template>
  <div
    v-if="disabled"
    :ref="setDisabledElement"
    v-bind="$attrs"
    :style="containerStyle"
  >
    <slot />
  </div>

  <OverlayScrollbarsComponent
    v-else
    v-bind="$attrs"
    :class="hostClasses"
    :defer="defer"
    element="div"
    :events="mergedEvents"
    :options="mergedOptions"
    :style="containerStyle"
  >
    <slot />
  </OverlayScrollbarsComponent>
</template>

// packages/react/src/Scrollbar/Scrollbar.tsx
import 'overlayscrollbars/overlayscrollbars.css';

import { forwardRef, useCallback, useEffect, useMemo } from 'react';
import {
  ClickScrollPlugin,
  OverlayScrollbars,
  type PartialOptions,
} from 'overlayscrollbars';
import type { OverlayScrollbarsComponentProps } from 'overlayscrollbars-react';
import {
  OverlayScrollbarsComponent,
  OverlayScrollbarsComponentRef,
} from 'overlayscrollbars-react';
import { scrollbarClasses as classes } from '@mezzanine-ui/core/scrollbar';
import { cx } from '../utils/cx';
import type { ScrollbarProps } from './typings';

/**
 * The react component for `mezzanine` scrollbar.
 * A customizable scrollbar container that provides consistent styling across all browsers
 */
const Scrollbar = forwardRef<
  OverlayScrollbarsComponentRef<'div'>,
  ScrollbarProps
>(function Scrollbar(props, ref) {
  const {
    children,
    className,
    defer = true,
    disabled = false,
    events,
    maxHeight,
    maxWidth,
    onViewportReady,
    options,
    style,
    ...rest
  } = props;

  // Register ClickScrollPlugin once (required for clickScroll option to work)
  useEffect(() => {
    OverlayScrollbars.plugin(ClickScrollPlugin);
  }, []);

  const mergedOptions = useMemo<PartialOptions>(
    () => ({
      ...options,
      overflow: {
        x: 'scroll',
        y: 'scroll',
      },
      scrollbars: {
        autoHide: 'scroll',
        autoHideDelay: 600,
        clickScroll: true,
        ...options?.scrollbars,
      },
    }),
    [options],
  );

  const containerStyle = useMemo(
    () => ({
      ...style,
      maxHeight,
      maxWidth,
    }),
    [maxHeight, maxWidth, style],
  );

  // Merge events with onViewportReady callback
  const mergedEvents = useMemo<
    OverlayScrollbarsComponentProps['events']
  >(() => {
    if (!onViewportReady && !events) return undefined;

    return {
      ...events,
      initialized: (instance: OverlayScrollbars) => {
        const { viewport } = instance.elements();

        onViewportReady?.(viewport as HTMLDivElement, instance);

        if (events && typeof events !== 'boolean' && events.initialized) {
          const initializedHandler = events.initialized;

          if (Array.isArray(initializedHandler)) {
            initializedHandler.forEach((handler) => handler(instance));
          } else {
            initializedHandler(instance);
          }
        }
      },
    };
  }, [events, onViewportReady]);

  // Callback ref for disabled mode - triggers onViewportReady with the div element
  const disabledRef = useCallback(
    (element: HTMLDivElement | null) => {
      // Forward to user ref if provided
      if (typeof ref === 'function') {
        (ref as (instance: HTMLDivElement | null) => void)(element);
      } else if (ref) {
        (ref as React.RefObject<HTMLDivElement | null>).current = element;
      }

      // Call onViewportReady with the div element (no OverlayScrollbars instance)
      if (element && onViewportReady) {
        onViewportReady(element, null as unknown as OverlayScrollbars);
      }
    },
    [onViewportReady, ref],
  );

  // When disabled, render a plain div instead of OverlayScrollbarsComponent
  if (disabled) {
    return (
      <div
        {...rest}
        ref={disabledRef}
        className={className}
        style={containerStyle}
      >
        {children}
      </div>
    );
  }

  return (
    <OverlayScrollbarsComponent
      {...rest}
      ref={ref}
      className={cx(classes.host, className)}
      defer={defer}
      element="div"
      events={mergedEvents}
      options={mergedOptions}
      style={containerStyle}
    >
      {children}
    </OverlayScrollbarsComponent>
  );
});

export default Scrollbar;
