// packages/react/src/Modal/Modal.tsx
import {
  modalClasses as classes,
  ModalSize,
  ModalStatusType,
} from '@mezzanine-ui/core/modal';
import { forwardRef, useCallback, useRef, useState, useMemo } from 'react';
import { cx } from '../utils/cx';
import { ModalControl, ModalControlContext } from './ModalControl';
import useModalContainer, { ModalContainerProps } from './useModalContainer';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import ModalHeader, { ModalHeaderProps } from './ModalHeader';
import ModalFooter, { ModalFooterProps } from './ModalFooter';
import ClearActions from '../ClearActions';

export type ModalHeaderLayoutProps = Pick<
  ModalHeaderProps,
  'statusTypeIconLayout' | 'titleAlign' | 'supportingTextAlign'
>;

interface CommonModalProps
  extends Omit<ModalContainerProps, 'children'>,
    Pick<NativeElementPropsWithoutKeyAndRef<'div'>, 'children'>,
    Partial<
      Omit<
        ModalFooterProps,
        | 'cancelText'
        | 'children'
        | 'className'
        | 'confirmText'
        | 'showCancelButton'
      >
    > {
  /**
   * The custom class name applied to the modal container.
   */
  backdropClassName?: string;
  /**
   * Whether to force full screen on any breakpoint.
   * @default false
   */
  fullScreen?: boolean;
  /**
   * Whether the modal is loading.
   * Controls the loading prop of confirm button in modal actions.
   */
  loading?: boolean;
  /**
   * Controls whether or not to display status icon before title.
   * Notice that giving a status will only display the regular title.
   * @default 'info'
   */
  modalStatusType?: ModalStatusType;
  /**
   * Controls whether or not to show dismiss button at top-end.
   * @default true
   */
  showDismissButton?: boolean;
  /**
   * Whether to show status type icon.
   * @default false
   */
  showStatusTypeIcon?: boolean;
  /**
   * Supporting text displayed below the title.
   */
  supportingText?: string;
}

interface ExtendedSplitModalProps extends CommonModalProps {
  /**
   * Content for the left side in extendedSplit layout.
   * Required when modalType is 'extendedSplit'.
   */
  extendedSplitLeftSideContent: React.ReactNode;
  /**
   * Content for the right side in extendedSplit layout.
   * Required when modalType is 'extendedSplit'.
   */
  extendedSplitRightSideContent: React.ReactNode;
  /**
   * Controls which side the sidebar panel (narrow column with footer) appears on.
   * - `'left'`: sidebar on the left, wide content on the right
   * - `'right'`: wide content on the left, sidebar on the right
   * @default 'right'
   */
  extendedSplitSidebarPosition?: 'left' | 'right';
  /**
   * Controls the type/layout of the modal.
   * - 'extendedSplit': Modal with split layout (footer inside left content)
   */
  modalType: 'extendedSplit';
  /**
   * Controls the size of the modal.
   * For extendedSplit type, only 'wide' is allowed.
   * @default 'wide'
   */
  size?: 'wide';
}

interface OtherModalProps extends CommonModalProps {
  /**
   * Content for the left side in extendedSplit layout.
   * Cannot be provided when modalType is not 'extendedSplit'.
   */
  extendedSplitLeftSideContent?: never;
  /**
   * Content for the right side in extendedSplit layout.
   * Cannot be provided when modalType is not 'extendedSplit'.
   */
  extendedSplitRightSideContent?: never;
  /**
   * 此模式下不適用。
   */
  extendedSplitSidebarPosition?: never;
  /**
   * Controls the type/layout of the modal.
   * - 'standard': Default modal with body container
   * - 'extended': Modal with left and right content areas
   * - 'mediaPreview': Modal for media preview
   * - 'verification': Modal for verification flows
   * @default 'standard'
   */
  modalType: 'extended' | 'standard' | 'mediaPreview' | 'verification';
  /**
   * Controls the size of the modal.
   * @default 'regular'
   */
  size?: ModalSize;
}

type BaseModalProps = ExtendedSplitModalProps | OtherModalProps;

type ModalHeaderPropsWithHeader = {
  /**
   * Whether to show modal header.
   */
  showModalHeader: true;
  /**
   * The title of the modal header (required when showModalHeader is true).
   */
  title: string;
};

type ModalHeaderPropsWithoutHeader = {
  /**
   * Whether to show modal header.
   * @default false
   */
  showModalHeader?: false;
  /**
   * The title of the modal header.
   * Cannot be provided when showModalHeader is false.
   */
  title?: never;
};

export type ModalFooterCancelProps = Pick<
  ModalFooterProps,
  'cancelText' | 'showCancelButton'
>;

type ModalFooterPropsWithFooter = {
  /**
   * Whether to show modal footer.
   */
  showModalFooter: true;
  /**
   * The confirm button text of the modal footer (required when showModalFooter is true).
   */
  confirmText: string;
} & ModalFooterCancelProps;

type ModalFooterPropsWithoutFooter = {
  /**
   * Whether to show modal footer.
   * @default false
   */
  showModalFooter?: false;
  /**
   * The confirm button text of the modal footer.
   * Cannot be provided when showModalFooter is false.
   */
  confirmText?: never;
  /**
   * 此模式下不適用。
   */
  cancelText?: never;
  /**
   * 此模式下不適用。
   */
  showCancelButton?: never;
};

export type ModalProps = BaseModalProps &
  ModalHeaderLayoutProps &
  (
    | (ModalHeaderPropsWithHeader & ModalFooterPropsWithFooter)
    | (ModalHeaderPropsWithHeader & ModalFooterPropsWithoutFooter)
    | (ModalHeaderPropsWithoutHeader & ModalFooterPropsWithFooter)
    | (ModalHeaderPropsWithoutHeader & ModalFooterPropsWithoutFooter)
  );

/**
 * 對話框元件，以 Backdrop 遮罩呈現需要使用者互動或確認的浮動視窗。
 *
 * 透過 `showModalHeader` 與 `showModalFooter` 分別啟用標題列與操作列，
 * `modalStatusType` 可在標題旁顯示狀態圖示（`info`、`success`、`warning`、`error`）。
 * `modalType` 支援 `standard`、`extended`、`mediaPreview`、`verification` 及 `extendedSplit` 佈局，
 * 其中 `extendedSplit` 需同時傳入 `extendedSplitLeftSideContent` 與 `extendedSplitRightSideContent`。
 * `size` 可選 `regular`、`large`、`wide` 等尺寸，`fullScreen` 則強制全螢幕顯示。
 *
 * @example
 * ```tsx
 * import Modal from '@mezzanine-ui/react/Modal';
 *
 * // 基本對話框（含標題與操作列）
 * <Modal
 *   open={isOpen}
 *   onClose={() => setIsOpen(false)}
 *   showModalHeader
 *   title="確認刪除"
 *   showModalFooter
 *   confirmText="確認"
 *   cancelText="取消"
 *   onConfirm={handleConfirm}
 *   onCancel={() => setIsOpen(false)}
 * >
 *   <p>此操作無法復原，確定要刪除嗎？</p>
 * </Modal>
 *
 * // 帶狀態圖示的對話框
 * <Modal
 *   open={isOpen}
 *   onClose={() => setIsOpen(false)}
 *   showModalHeader
 *   title="操作成功"
 *   showStatusTypeIcon
 *   modalStatusType="success"
 *   showModalFooter
 *   confirmText="關閉"
 *   onConfirm={() => setIsOpen(false)}
 * />
 * ```
 *
 * @see {@link Drawer} 從側邊滑入的抽屜式對話框元件
 * @see {@link useModalContainer} 用於自訂 Modal 掛載容器的 Hook
 */
const Modal = forwardRef<HTMLDivElement, ModalProps>(
  function Modal(props, ref) {
    const {
      actionsButtonLayout,
      annotation,
      auxiliaryContentButtonProps,
      auxiliaryContentButtonText,
      auxiliaryContentChecked,
      auxiliaryContentLabel,
      auxiliaryContentOnChange,
      auxiliaryContentOnClick,
      auxiliaryContentType,
      backdropClassName,
      cancelButtonProps,
      cancelText,
      children,
      className,
      confirmButtonProps,
      confirmText,
      container,
      disableCloseOnBackdropClick = false,
      disableCloseOnEscapeKeyDown = false,
      disablePortal = false,
      extendedSplitLeftSideContent,
      extendedSplitRightSideContent,
      extendedSplitSidebarPosition = 'right',
      fullScreen = false,
      loading = false,
      modalStatusType = 'info',
      modalType = 'standard',
      onBackdropClick,
      onCancel,
      onClose,
      onConfirm,
      open,
      passwordButtonProps,
      passwordButtonText,
      passwordChecked,
      passwordCheckedLabel,
      passwordCheckedOnChange,
      passwordOnClick,
      showCancelButton,
      showDismissButton = true,
      showModalFooter = false,
      showModalHeader,
      showStatusTypeIcon,
      size = 'regular',
      statusTypeIconLayout,
      supportingText,
      supportingTextAlign,
      title,
      titleAlign,
      ...rest
    } = props;

    const bodyContentRef = useRef<HTMLDivElement>(null);
    const [hasTopSeparator, setHasTopSeparator] = useState(false);
    const [hasBottomSeparator, setHasBottomSeparator] = useState(false);
    const scrollCleanupRef = useRef<(() => void) | null>(null);

    const handleBodyContainerRef = useCallback(
      (node: HTMLDivElement | null) => {
        if (scrollCleanupRef.current) {
          scrollCleanupRef.current();
          scrollCleanupRef.current = null;
        }

        if (!node) {
          setHasTopSeparator(false);
          setHasBottomSeparator(false);

          return;
        }

        const checkScroll = () => {
          const { scrollTop, scrollHeight, clientHeight } = node;

          setHasTopSeparator(scrollTop > 0);
          setHasBottomSeparator(scrollTop + clientHeight < scrollHeight);
        };

        const rafId = requestAnimationFrame(checkScroll);

        node.addEventListener('scroll', checkScroll);

        const observer = new ResizeObserver(checkScroll);

        observer.observe(node);

        const content = bodyContentRef.current;

        if (content) {
          observer.observe(content);
        }

        scrollCleanupRef.current = () => {
          cancelAnimationFrame(rafId);
          node.removeEventListener('scroll', checkScroll);
          observer.disconnect();
        };
      },
      [],
    );

    const modalControl: ModalControl = useMemo(
      () => ({
        loading,
        modalStatusType: modalStatusType,
      }),
      [loading, modalStatusType],
    );

    const { Container: ModalContainer } = useModalContainer();

    const renderModalFooter = () => (
      <ModalFooter
        {...({
          actionsButtonLayout,
          annotation,
          auxiliaryContentButtonProps,
          auxiliaryContentButtonText,
          auxiliaryContentChecked,
          auxiliaryContentLabel,
          auxiliaryContentOnChange,
          auxiliaryContentOnClick,
          auxiliaryContentType,
          cancelButtonProps,
          cancelText,
          confirmButtonProps,
          confirmText: confirmText as string,
          loading,
          onCancel,
          onConfirm,
          passwordButtonProps,
          passwordButtonText,
          passwordChecked,
          passwordCheckedLabel,
          passwordCheckedOnChange,
          passwordOnClick,
          showCancelButton,
        } as ModalFooterProps)}
      />
    );

    return (
      <ModalControlContext.Provider value={modalControl}>
        <ModalContainer
          className={backdropClassName}
          container={container}
          disableCloseOnBackdropClick={disableCloseOnBackdropClick}
          disableCloseOnEscapeKeyDown={disableCloseOnEscapeKeyDown}
          disablePortal={disablePortal}
          onBackdropClick={onBackdropClick}
          onClose={onClose}
          open={open}
          ref={ref}
        >
          <div
            aria-modal={open ? true : undefined}
            {...rest}
            className={cx(
              classes.host,
              classes.modalStatusType(modalStatusType),
              classes.size(size),
              {
                [classes.fullScreen]: fullScreen,
                [classes.withCloseIcon]: showDismissButton,
              },
              className,
            )}
            role="dialog"
          >
            {showModalHeader && (
              <ModalHeader
                {...({
                  showStatusTypeIcon,
                  statusTypeIconLayout,
                  supportingText,
                  supportingTextAlign,
                  title: title as string,
                  titleAlign,
                } as ModalHeaderProps)}
              />
            )}
            {modalType === 'extendedSplit' && (
              <div
                className={cx(classes.modalBodyContainerExtendedSplit, {
                  [classes.modalBodyContainerExtendedSplitSidebarLeft]:
                    extendedSplitSidebarPosition === 'left',
                })}
              >
                <div className={classes.modalBodyContainerExtendedSplitRight}>
                  {extendedSplitRightSideContent}
                </div>
                <div className={classes.modalBodyContainerExtendedSplitLeft}>
                  <div
                    className={
                      classes.modalBodyContainerExtendedSplitLeftSideContent
                    }
                  >
                    {extendedSplitLeftSideContent}
                  </div>
                  {showModalFooter && renderModalFooter()}
                </div>
              </div>
            )}
            {(modalType === 'standard' ||
              modalType === 'verification' ||
              modalType === 'extended' ||
              modalType === 'mediaPreview') && (
              <>
                {children && (
                  <div
                    ref={handleBodyContainerRef}
                    className={cx(classes.modalBodyContainer, {
                      [classes.modalBodyContainerWithTopSeparator]:
                        modalType === 'extended' || hasTopSeparator,
                      [classes.modalBodyContainerWithBottomSeparator]:
                        modalType === 'extended' || hasBottomSeparator,
                    })}
                  >
                    <div ref={bodyContentRef}>{children}</div>
                  </div>
                )}
                {showModalFooter && renderModalFooter()}
              </>
            )}
            {showDismissButton && (
              <ClearActions
                onClick={onClose}
                className={classes.closeIcon}
                variant="base"
              />
            )}
          </div>
        </ModalContainer>
      </ModalControlContext.Provider>
    );
  },
);

export default Modal;

// packages/vue/modal/modal.vue
<script setup lang="ts">
import { computed, ref, useAttrs } from 'vue';
import type { ComponentPublicInstance, VNodeArrayChildren } from 'vue';
import { modalClasses as classes } from '@mezzanine-ui/core/modal';
import clsx from 'clsx';
import { flattenChildren } from '../_internal/flatten-children';
import MznClearActions from '../clear-actions/clear-actions.vue';
import { provideModalControl } from './modal-control';
import MznModalFooter from './modal-footer.vue';
import MznModalHeader from './modal-header.vue';
import { useModalContainer } from './use-modal-container';
import type { ModalProps } from './modal.types';

/**
 * 對話框元件，以遮罩呈現需要使用者互動或確認的浮動視窗。
 *
 * `showModalHeader` 與 `showModalFooter` 分別啟用標題列與操作列；
 * `modalStatusType` 決定標題旁狀態圖示的樣子（info、success、warning、error、
 * email、delete）。`modalType` 支援 standard、extended、mediaPreview、
 * verification 與 extendedSplit 五種佈局，其中 extendedSplit 需同時給左右內容。
 * 內容超出高度時會自動在上下加上分隔線。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { ref } from 'vue';
 * import { MznModal } from '@mezzanine-ui/vue/modal';
 *
 * const open = ref(false);
 * <\/script>
 *
 * <template>
 *   <MznModal
 *     cancel-text="取消"
 *     confirm-text="確認"
 *     :open="open"
 *     show-modal-footer
 *     show-modal-header
 *     title="確認刪除"
 *     @cancel="open = false"
 *     @close="open = false"
 *     @confirm="remove"
 *   >
 *     <p>此操作無法復原，確定要刪除嗎？</p>
 *   </MznModal>
 * </template>
 * ```
 *
 * @see MznModalHeader 標題列
 * @see MznModalFooter 操作列
 * @see useModalContainer 自訂浮層時可重用的外殼
 */
/**
 * React spreads its rest props onto the dialog element inside the container,
 * and `backdropClassName` onto the container itself. Vue's fallthrough would
 * hand everything to the container instead, so both are placed explicitly.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<ModalProps>(), {
  actionsButtonLayout: undefined,
  annotation: undefined,
  auxiliaryContentButtonProps: undefined,
  auxiliaryContentButtonText: undefined,
  auxiliaryContentChecked: undefined,
  auxiliaryContentLabel: undefined,
  auxiliaryContentOnChange: undefined,
  auxiliaryContentOnClick: undefined,
  auxiliaryContentType: undefined,
  backdropClassName: undefined,
  cancelButtonProps: undefined,
  cancelText: undefined,
  confirmButtonProps: undefined,
  confirmText: undefined,
  container: undefined,
  disableCloseOnBackdropClick: false,
  disableCloseOnEscapeKeyDown: false,
  disablePortal: false,
  extendedSplitLeftSideContent: undefined,
  extendedSplitRightSideContent: undefined,
  extendedSplitSidebarPosition: 'right',
  fullScreen: false,
  loading: false,
  modalStatusType: 'info',
  modalType: 'standard',
  open: undefined,
  passwordButtonProps: undefined,
  passwordButtonText: undefined,
  passwordChecked: undefined,
  passwordCheckedLabel: undefined,
  passwordCheckedOnChange: undefined,
  passwordOnClick: undefined,
  showCancelButton: undefined,
  showDismissButton: true,
  showModalFooter: false,
  showModalHeader: undefined,
  showStatusTypeIcon: undefined,
  size: 'regular',
  statusTypeIconLayout: undefined,
  supportingText: undefined,
  supportingTextAlign: undefined,
  title: undefined,
  titleAlign: undefined,
});

const emit = defineEmits<{
  backdropClick: [event: MouseEvent];
  cancel: [event: MouseEvent];
  close: [];
  confirm: [event: MouseEvent];
}>();

const slots = defineSlots<{
  /** The modal body. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const { Container: MznModalContainer } = useModalContainer();

provideModalControl(() => ({
  loading: props.loading,
  modalStatusType: props.modalStatusType,
}));

const bodyContent = ref<HTMLDivElement | null>(null);
const hasTopSeparator = ref(false);
const hasBottomSeparator = ref(false);

let scrollCleanup: (() => void) | null = null;

/**
 * Written as a function ref rather than a watcher because it has to run the
 * moment the container element appears and to tear down the moment it goes —
 * which is exactly when React's callback ref fires.
 */
function setBodyContainer(
  element: Element | ComponentPublicInstance | null,
): void {
  if (scrollCleanup) {
    scrollCleanup();
    scrollCleanup = null;
  }

  const node = element as HTMLDivElement | null;

  if (!node) {
    hasTopSeparator.value = false;
    hasBottomSeparator.value = false;

    return;
  }

  const checkScroll = (): void => {
    const { scrollTop, scrollHeight, clientHeight } = node;

    hasTopSeparator.value = scrollTop > 0;
    hasBottomSeparator.value = scrollTop + clientHeight < scrollHeight;
  };

  const rafId = requestAnimationFrame(checkScroll);

  node.addEventListener('scroll', checkScroll);

  const observer = new ResizeObserver(checkScroll);

  observer.observe(node);

  const content = bodyContent.value;

  if (content) {
    observer.observe(content);
  }

  scrollCleanup = (): void => {
    cancelAnimationFrame(rafId);
    node.removeEventListener('scroll', checkScroll);
    observer.disconnect();
  };
}

/**
 * What the slot actually renders, not whether one was passed: React skips the
 * whole body container when `children` is falsy, and a slot whose only content
 * is a false `v-if` still leaves a comment placeholder behind.
 */
const hasChildren = computed((): boolean =>
  Boolean(
    flattenChildren(slots.default?.() as VNodeArrayChildren | undefined).length,
  ),
);

const isBodyContainerType = computed(
  (): boolean =>
    props.modalType === 'standard' ||
    props.modalType === 'verification' ||
    props.modalType === 'extended' ||
    props.modalType === 'mediaPreview',
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.modalStatusType(props.modalStatusType),
    classes.size(props.size),
    {
      [classes.fullScreen]: props.fullScreen,
      [classes.withCloseIcon]: props.showDismissButton,
    },
    attrs.class as string,
  ),
);

const bodyContainerClasses = computed((): string =>
  clsx(classes.modalBodyContainer, {
    [classes.modalBodyContainerWithTopSeparator]:
      props.modalType === 'extended' || hasTopSeparator.value,
    [classes.modalBodyContainerWithBottomSeparator]:
      props.modalType === 'extended' || hasBottomSeparator.value,
  }),
);

const extendedSplitClasses = computed((): string =>
  clsx(classes.modalBodyContainerExtendedSplit, {
    [classes.modalBodyContainerExtendedSplitSidebarLeft]:
      props.extendedSplitSidebarPosition === 'left',
  }),
);

const footerBindings = computed(() => ({
  actionsButtonLayout: props.actionsButtonLayout,
  annotation: props.annotation,
  auxiliaryContentButtonProps: props.auxiliaryContentButtonProps,
  auxiliaryContentButtonText: props.auxiliaryContentButtonText,
  auxiliaryContentChecked: props.auxiliaryContentChecked,
  auxiliaryContentLabel: props.auxiliaryContentLabel,
  auxiliaryContentOnChange: props.auxiliaryContentOnChange,
  auxiliaryContentOnClick: props.auxiliaryContentOnClick,
  auxiliaryContentType: props.auxiliaryContentType,
  cancelButtonProps: props.cancelButtonProps,
  cancelText: props.cancelText,
  confirmButtonProps: props.confirmButtonProps,
  confirmText: props.confirmText,
  loading: props.loading,
  passwordButtonProps: props.passwordButtonProps,
  passwordButtonText: props.passwordButtonText,
  passwordChecked: props.passwordChecked,
  passwordCheckedLabel: props.passwordCheckedLabel,
  passwordCheckedOnChange: props.passwordCheckedOnChange,
  passwordOnClick: props.passwordOnClick,
  showCancelButton: props.showCancelButton,
}));

const closeIconClass = classes.closeIcon;
const extendedSplitLeftClass = classes.modalBodyContainerExtendedSplitLeft;
const extendedSplitLeftSideContentClass =
  classes.modalBodyContainerExtendedSplitLeftSideContent;
const extendedSplitRightClass = classes.modalBodyContainerExtendedSplitRight;
</script>

<template>
  <MznModalContainer
    :class="backdropClassName"
    :container="container"
    :disable-close-on-backdrop-click="disableCloseOnBackdropClick"
    :disable-close-on-escape-key-down="disableCloseOnEscapeKeyDown"
    :disable-portal="disablePortal"
    :open="open"
    @backdrop-click="emit('backdropClick', $event)"
    @close="emit('close')"
  >
    <div
      :aria-modal="open ? true : undefined"
      v-bind="forwardedAttrs"
      :class="hostClasses"
      role="dialog"
    >
      <MznModalHeader
        v-if="showModalHeader"
        :show-status-type-icon="showStatusTypeIcon"
        :status-type-icon-layout="statusTypeIconLayout"
        :supporting-text="supportingText"
        :supporting-text-align="supportingTextAlign"
        :title="title as string"
        :title-align="titleAlign"
      />
      <div v-if="modalType === 'extendedSplit'" :class="extendedSplitClasses">
        <div :class="extendedSplitRightClass">
          <component :is="() => extendedSplitRightSideContent" />
        </div>
        <div :class="extendedSplitLeftClass">
          <div :class="extendedSplitLeftSideContentClass">
            <component :is="() => extendedSplitLeftSideContent" />
          </div>
          <MznModalFooter
            v-if="showModalFooter"
            v-bind="footerBindings"
            @cancel="emit('cancel', $event)"
            @confirm="emit('confirm', $event)"
          />
        </div>
      </div>
      <template v-if="isBodyContainerType">
        <div
          v-if="hasChildren"
          :ref="setBodyContainer"
          :class="bodyContainerClasses"
        >
          <div ref="bodyContent"><slot /></div>
        </div>
        <MznModalFooter
          v-if="showModalFooter"
          v-bind="footerBindings"
          @cancel="emit('cancel', $event)"
          @confirm="emit('confirm', $event)"
        />
      </template>
      <MznClearActions
        v-if="showDismissButton"
        :class="closeIconClass"
        variant="base"
        @click="emit('close')"
      />
    </div>
  </MznModalContainer>
</template>
