// packages/react/src/Modal/ModalHeader.tsx
'use client';

import { forwardRef, useContext } from 'react';
import {
  modalClasses as classes,
  ModalStatusType,
  modalStatusTypeIcons,
} from '@mezzanine-ui/core/modal';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Icon from '../Icon';
import { ModalControlContext } from './ModalControl';
import Typography from '../Typography';

export interface ModalHeaderProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * Whether to show status type icon.
   * @default false
   */
  showStatusTypeIcon?: boolean;
  /**
   * Layout of the status type icon relative to title.
   * - 'vertical': Icon above title
   * - 'horizontal': Icon to the left of title
   * @default 'vertical'
   */
  statusTypeIconLayout?: 'vertical' | 'horizontal';
  /**
   * Supporting text displayed below the title.
   */
  supportingText?: string;
  /**
   * Alignment of the supporting text.
   * @default 'left'
   */
  supportingTextAlign?: 'left' | 'center';
  /**
   * The title text of the modal header.
   */
  title: string;
  /**
   * Alignment of the title.
   * @default 'left'
   */
  titleAlign?: 'left' | 'center';
}

/**
 * The React component for `mezzanine` modal header.
 */
const ModalHeader = forwardRef<HTMLDivElement, ModalHeaderProps>(
  function ModalHeader(props, ref) {
    const {
      className,
      showStatusTypeIcon = false,
      statusTypeIconLayout = 'vertical',
      supportingText,
      supportingTextAlign = 'left',
      title,
      titleAlign = 'left',
      ...rest
    } = props;
    const { modalStatusType } = useContext(ModalControlContext);

    const iconColor = (type: ModalStatusType) => {
      switch (type) {
        case 'success':
          return 'success-strong';
        case 'warning':
          return 'warning';
        case 'error':
          return 'error-solid';
        case 'info':
          return 'info-strong';
        case 'email':
          return 'info-strong';
        case 'delete':
          return 'error-solid';
        default:
          return 'neutral';
      }
    };

    return (
      <div
        {...rest}
        ref={ref}
        className={cx(
          classes.modalHeader,
          {
            [classes.modalHeader + '--horizontal']:
              statusTypeIconLayout === 'horizontal',
            [classes.modalHeader + '--vertical']:
              statusTypeIconLayout === 'vertical',
            [classes.modalHeader + '--title-align-left']: titleAlign === 'left',
            [classes.modalHeader + '--title-align-center']:
              titleAlign === 'center',
            [classes.modalHeader + '--show-modal-status-type-icon']:
              showStatusTypeIcon,
          },
          className,
        )}
      >
        {showStatusTypeIcon && (
          <div className={cx(classes.modalHeaderStatusTypeIcon)}>
            <Icon
              icon={modalStatusTypeIcons[modalStatusType]}
              color={iconColor(modalStatusType)}
              size={20}
            />
          </div>
        )}
        <div className={cx(classes.modalHeaderTitleAndSupportingTextContainer)}>
          <Typography
            variant="h2"
            color="text-neutral-solid"
            className={cx(classes.modalHeaderTitle)}
            title={typeof title === 'string' ? title : undefined}
          >
            {title}
          </Typography>
          <Typography
            variant="body"
            color="text-neutral-strong"
            className={cx(classes.modalHeaderSupportingText, {
              [classes.modalHeaderSupportingText + '--align-left']:
                supportingTextAlign === 'left',
              [classes.modalHeaderSupportingText + '--align-center']:
                supportingTextAlign === 'center',
            })}
          >
            {supportingText}
          </Typography>
        </div>
      </div>
    );
  },
);

export default ModalHeader;

// packages/vue/modal/modal-header.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  modalClasses as classes,
  modalStatusTypeIcons,
} from '@mezzanine-ui/core/modal';
import type { ModalStatusType } from '@mezzanine-ui/core/modal';
import type { IconColor } from '@mezzanine-ui/core/icon';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznTypography from '../typography/typography.vue';
import { useModalControl } from './modal-control';
import type { ModalHeaderProps } from './modal-header.types';

/**
 * Modal 的標題列，顯示標題、輔助說明與狀態圖示。
 *
 * 狀態圖示取自 Modal 提供的 `modalStatusType`，圖示與顏色一一對應；
 * `statusTypeIconLayout` 決定圖示在標題左邊還是上方，`titleAlign` 與
 * `supportingTextAlign` 決定文字對齊。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznModalHeader } from '@mezzanine-ui/vue/modal';
 * <\/script>
 *
 * <template>
 *   <MznModalHeader show-status-type-icon title="確認刪除" />
 *   <MznModalHeader
 *     supporting-text="這個動作無法復原"
 *     title="確認刪除"
 *     title-align="center"
 *   />
 * </template>
 * ```
 *
 * @see MznModal 以 showModalHeader 渲染這個標題列
 */
const props = withDefaults(defineProps<ModalHeaderProps>(), {
  showStatusTypeIcon: false,
  statusTypeIconLayout: 'vertical',
  supportingText: undefined,
  supportingTextAlign: 'left',
  titleAlign: 'left',
});

const modalControl = useModalControl();

const iconColor = (type: ModalStatusType): IconColor => {
  switch (type) {
    case 'success':
      return 'success-strong';
    case 'warning':
      return 'warning';
    case 'error':
      return 'error-solid';
    case 'info':
      return 'info-strong';
    case 'email':
      return 'info-strong';
    case 'delete':
      return 'error-solid';
    default:
      return 'neutral';
  }
};

const statusTypeIcon = computed(
  (): IconDefinition =>
    modalStatusTypeIcons[modalControl.value.modalStatusType],
);

const statusTypeIconColor = computed(
  (): IconColor => iconColor(modalControl.value.modalStatusType),
);

const hostClasses = computed((): string =>
  clsx(classes.modalHeader, {
    [`${classes.modalHeader}--horizontal`]:
      props.statusTypeIconLayout === 'horizontal',
    [`${classes.modalHeader}--vertical`]:
      props.statusTypeIconLayout === 'vertical',
    [`${classes.modalHeader}--title-align-left`]: props.titleAlign === 'left',
    [`${classes.modalHeader}--title-align-center`]:
      props.titleAlign === 'center',
    [`${classes.modalHeader}--show-modal-status-type-icon`]:
      props.showStatusTypeIcon,
  }),
);

const supportingTextClasses = computed((): string =>
  clsx(classes.modalHeaderSupportingText, {
    [`${classes.modalHeaderSupportingText}--align-left`]:
      props.supportingTextAlign === 'left',
    [`${classes.modalHeaderSupportingText}--align-center`]:
      props.supportingTextAlign === 'center',
  }),
);

const statusTypeIconClass = classes.modalHeaderStatusTypeIcon;
const titleAndSupportingTextContainerClass =
  classes.modalHeaderTitleAndSupportingTextContainer;
const titleClass = classes.modalHeaderTitle;
</script>

<template>
  <div :class="hostClasses">
    <div v-if="showStatusTypeIcon" :class="statusTypeIconClass">
      <MznIcon :color="statusTypeIconColor" :icon="statusTypeIcon" :size="20" />
    </div>
    <div :class="titleAndSupportingTextContainerClass">
      <MznTypography
        :class="titleClass"
        color="text-neutral-solid"
        :title="title"
        variant="h2"
      >
        {{ title }}
      </MznTypography>
      <MznTypography
        :class="supportingTextClasses"
        color="text-neutral-strong"
        variant="body"
      >
        {{ supportingText }}
      </MznTypography>
    </div>
  </div>
</template>
