// packages/ng/notification-center/notification-center.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  ElementRef,
  inject,
  input,
  OnInit,
  output,
  signal,
  viewChild,
} from '@angular/core';
import {
  notificationClasses as classes,
  notificationIcons,
  NotificationSeverity,
  NotificationType,
} from '@mezzanine-ui/core/notification-center';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { CloseIcon, DotHorizontalIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznBadge } from '@mezzanine-ui/ng/badge';
import { MznButton, MznButtonGroup } from '@mezzanine-ui/ng/button';
import { MznDropdown } from '@mezzanine-ui/ng/dropdown';
import { MznPopper } from '@mezzanine-ui/ng/popper';
import { MznTypography } from '@mezzanine-ui/ng/typography';
import { buildTransitionString, reflow } from '@mezzanine-ui/ng/transition';

/**
 * 單項通知元件，對齊 React `<NotificationCenter />` 的 per-item render。
 *
 * 支援 `type='notification'`（浮動提示，附滑入／淡出動畫）與 `type='drawer'`
 * （抽屜列表項，附時間戳記 hover popper 與 Dropdown 操作）。元件只負責
 * 單一通知的渲染；批次顯示請搭配 `MznNotificationCenterDrawer` 或自行
 * 迭代 `*ngFor`。
 *
 * @example
 * ```html
 * import { MznNotificationCenter } from '@mezzanine-ui/ng/notification-center';
 *
 * <div mznNotificationCenter
 *   type="notification"
 *   severity="success"
 *   title="Deployment succeeded"
 *   description="Build #42 is live."
 *   confirmButtonText="View"
 *   (confirmed)="viewBuild()"
 *   (closed)="dismiss($event)"
 * ></div>
 * ```
 */
@Component({
  selector: '[mznNotificationCenter]',
  standalone: true,
  imports: [
    MznIcon,
    MznBadge,
    MznButton,
    MznButtonGroup,
    MznDropdown,
    MznPopper,
    MznTypography,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[style.opacity]': 'opacityStyle()',
    '[style.transform]': 'transformStyle()',
    '[style.visibility]': 'visibilityStyle()',
    '(mouseenter)': 'onMouseEnter()',
    '(mouseleave)': 'onMouseLeave()',
    '[attr.appendTips]': 'null',
    '[attr.cancelButtonText]': 'null',
    '[attr.confirmButtonText]': 'null',
    '[attr.description]': 'null',
    '[attr.duration]': 'null',
    '[attr.from]': 'null',
    '[attr.options]': 'null',
    '[attr.prependTips]': 'null',
    '[attr.reference]': 'null',
    '[attr.severity]': 'null',
    '[attr.showBadge]': 'null',
    '[attr.timeStamp]': 'null',
    '[attr.timeStampLocale]': 'null',
    '[attr.title]': 'null',
    '[attr.type]': 'null',
  },
  template: `
    @if (resolvedIcon(); as icon) {
      <div [class]="iconContainerClass">
        <i mznIcon [class]="severityIconClass" [icon]="icon" [size]="32"></i>
      </div>
    }

    <div [class]="bodyClass">
      <div [class]="bodyContentClass">
        <h4 [class]="titleClass">{{ title() }}</h4>
        <p mznTypography [class]="contentClass" style="margin: 0;">{{
          description()
        }}</p>
      </div>

      @if (showActions()) {
        <div mznButtonGroup [class]="actionClass">
          @if (showCancelButton() && cancelButtonText()) {
            <button
              mznButton
              variant="base-secondary"
              size="minor"
              (click)="onCancelClick()"
            >
              {{ cancelButtonText() }}
            </button>
          }
          @if (showConfirmButton() && confirmButtonText()) {
            <button mznButton size="minor" (click)="onConfirmClick()">
              {{ confirmButtonText() }}
            </button>
          }
        </div>
      }

      @if (type() === 'drawer') {
        <span
          #timeStampRef
          mznTypography
          variant="label-secondary"
          [class]="timeStampClass"
          >{{ formattedTimeStamp() }}</span
        >
        @if (isToday() && timeStampAnchor()) {
          <div
            mznPopper
            [anchor]="timeStampAnchor()"
            [open]="true"
            placement="bottom"
            [offsetOptions]="timeStampOffsetOptions"
            [arrowOptions]="timeStampArrowOptions"
            [class]="timeStampPopperClass"
            [style.z-index]="'var(--mzn-z-index-popover)'"
          >
            <span mznTypography [class]="timeStampTextClass">{{
              rawTimeStamp()
            }}</span>
          </div>
        }
      }
    </div>

    @if (type() === 'drawer') {
      <button
        #dotTrigger
        mznButton
        variant="base-ghost"
        [class]="dotIconButtonClass"
        (click)="onDotButtonClick()"
      >
        @if (showBadge()) {
          <div mznBadge variant="dot-error"></div>
        }
        <i
          mznIcon
          [class]="closeIconClass"
          [clickable]="true"
          [icon]="dotHorizontalIcon"
          [size]="16"
          (click)="onBadgeClick($event)"
        ></i>
      </button>
      @if (options().length > 0) {
        <div
          mznDropdown
          [anchor]="dotTrigger"
          [open]="openDropdown()"
          [options]="options()"
          placement="bottom-end"
          zIndex="var(--mzn-z-index-popover)"
          (selected)="onBadgeSelect($event)"
          (closed)="openDropdown.set(false)"
        ></div>
      }
    } @else {
      <i
        mznIcon
        [class]="closeIconClass"
        [clickable]="true"
        [icon]="closeIcon"
        [size]="16"
        (click)="onCloseClick()"
      ></i>
    }
  `,
})
export class MznNotificationCenter implements OnInit {
  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly destroyRef = inject(DestroyRef);

  /** 附加在項目底部的備註（僅 drawer 模式）。 */
  readonly appendTips = input<string>();

  /** 取消按鈕文字（僅 notification 模式）。@default 'Cancel' */
  readonly cancelButtonText = input<string>('Cancel');

  /** 確認按鈕文字（僅 notification 模式）。@default 'Confirm' */
  readonly confirmButtonText = input<string>('Confirm');

  /**
   * 是否顯示確認按鈕。對應 React `onConfirm` 存在時才顯示的語意 —
   * Angular 的 `output()` 無法從內部 introspect 是否有 subscriber，
   * 所以改以 explicit input 控制。
   * @default false
   */
  readonly showConfirmButton = input(false);

  /**
   * 是否顯示取消按鈕。對應 React `(onCancel || onClose)` 語意的顯式開關。
   * @default false
   */
  readonly showCancelButton = input(false);

  /** 描述內容。 */
  readonly description = input<string>('');

  /**
   * 自動關閉時間（毫秒）。設為 `false` 或省略時不自動關閉。
   * @default false
   */
  readonly duration = input<number | false>(false);

  /**
   * 進場方向（僅 notification 模式）。
   * @default 'top'
   */
  readonly from = input<'right' | 'top'>('top');

  /** drawer mode 右上角 Dropdown 選項。 */
  readonly options = input<ReadonlyArray<DropdownOption>>([]);

  /** 附加在項目頂部的時間分組標籤（僅 drawer 模式）。 */
  readonly prependTips = input<string>();

  /** 通知唯一識別（供 `closed` 事件回傳）。 */
  readonly reference = input<string | number>();

  /** 嚴重程度。@default 'info' */
  readonly severity = input<NotificationSeverity>('info');

  /** drawer mode 點點按鈕上的紅點徽章。@default false */
  readonly showBadge = input(false);

  /** 時間戳記。@default `new Date()` */
  readonly timeStamp = input<string | number | Date>(new Date());

  /** 時間戳記地區。@default 'zh-TW' */
  readonly timeStampLocale = input<string>('zh-TW');

  /** 標題。 */
  readonly title = input<string>('');

  /** 通知類型。@default 'notification' */
  readonly type = input<NotificationType>('notification');

  /** 確認按鈕被點擊。 */
  readonly confirmed = output<void>();

  /** 取消按鈕被點擊（沒傳時點 close 也會退回此事件）。 */
  readonly cancelled = output<void>();

  /** 關閉（X 或 badge 點擊）時發出，payload 為 `reference`。 */
  readonly closed = output<string | number | undefined>();

  /** drawer mode 點點按鈕被點擊。 */
  readonly badgeClicked = output<void>();

  /** drawer mode Dropdown 選項被選中。 */
  readonly badgeSelected = output<DropdownOption>();

  protected readonly closeIcon = CloseIcon;
  protected readonly dotHorizontalIcon = DotHorizontalIcon;
  protected readonly iconContainerClass = classes.iconContainer;
  protected readonly severityIconClass = classes.severityIcon;
  protected readonly bodyClass = classes.body;
  protected readonly timeStampPopperClass = classes.timeStampPopper;
  protected readonly timeStampTextClass = classes.timeStampText;
  protected readonly timeStampOffsetOptions = { mainAxis: 8 };
  protected readonly timeStampArrowOptions = {
    className: classes.timeStampPopperArrow,
    enabled: true,
    padding: 0,
  };

  private readonly timeStampEl =
    viewChild<ElementRef<HTMLElement>>('timeStampRef');
  protected readonly timeStampAnchor = signal<HTMLElement | null>(null);
  protected readonly bodyContentClass = classes.bodyContent;
  protected readonly titleClass = classes.title;
  protected readonly contentClass = classes.content;
  protected readonly actionClass = classes.action;
  protected readonly closeIconClass = classes.closeIcon;
  protected readonly dotIconButtonClass = classes.dotIconButton;
  protected readonly timeStampClass = classes.timeStamp;

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.host,
      classes.severity(this.severity()),
      classes.type(this.type()),
    ),
  );

  protected readonly resolvedIcon = computed(
    () => notificationIcons[this.severity()],
  );

  protected readonly showActions = computed(
    (): boolean =>
      this.type() === 'notification' &&
      ((this.showConfirmButton() && !!this.confirmButtonText()) ||
        (this.showCancelButton() && !!this.cancelButtonText())),
  );

  private parsedTimeStamp = computed((): Date | null => {
    const ts = this.timeStamp();
    const d = ts instanceof Date ? ts : new Date(ts);
    return Number.isNaN(d.getTime()) ? null : d;
  });

  protected readonly isToday = computed((): boolean => {
    const d = this.parsedTimeStamp();
    if (!d) return false;
    const now = new Date();
    return (
      d.getFullYear() === now.getFullYear() &&
      d.getMonth() === now.getMonth() &&
      d.getDate() === now.getDate()
    );
  });

  protected readonly rawTimeStamp = computed((): string => {
    const ts = this.timeStamp();
    if (ts instanceof Date) return ts.toLocaleString(this.timeStampLocale());
    return String(ts);
  });

  protected readonly formattedTimeStamp = computed((): string => {
    const d = this.parsedTimeStamp();
    const tsRaw = this.timeStamp();
    const tsText =
      typeof tsRaw === 'string'
        ? tsRaw
        : String(tsRaw instanceof Date ? '' : tsRaw);

    if (!d) return tsText;

    const now = Date.now();
    const nowDate = new Date(now);
    const nowStartOfDay = new Date(
      nowDate.getFullYear(),
      nowDate.getMonth(),
      nowDate.getDate(),
    );
    const tsStartOfDay = new Date(d.getFullYear(), d.getMonth(), d.getDate());
    const isToday = nowStartOfDay.getTime() === tsStartOfDay.getTime();

    if (isToday) {
      const diffInMs = d.getTime() - now;
      const diffInSeconds = Math.round(diffInMs / 1000);
      const rtf = new Intl.RelativeTimeFormat(this.timeStampLocale(), {
        numeric: 'always',
      });
      const units: Array<{
        unit: Intl.RelativeTimeFormatUnit;
        seconds: number;
      }> = [
        { unit: 'hour', seconds: 3600 },
        { unit: 'minute', seconds: 60 },
      ];
      for (const { unit, seconds } of units) {
        const value = Math.round(diffInSeconds / seconds);
        if (Math.abs(value) >= 1) return rtf.format(value, unit);
      }
      return 'now';
    }

    const hasTimeComponent =
      tsText && (/:\d{2}/.test(tsText) || tsText.includes('T'));
    if (hasTimeComponent) {
      const fmt = new Intl.DateTimeFormat(this.timeStampLocale(), {
        year: 'numeric',
        month: '2-digit',
        day: '2-digit',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false,
      });
      return fmt.format(d).replace(/\//g, '-');
    }
    const fmt = new Intl.DateTimeFormat(this.timeStampLocale(), {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
    });
    return fmt.format(d).replace(/\//g, '-');
  });

  // ─── Slide-fade transition state (type='notification') ──────────────
  private readonly state = signal<
    'entering' | 'entered' | 'exiting' | 'exited'
  >('exited');

  protected readonly opacityStyle = computed(() => {
    if (this.type() !== 'notification') return undefined;
    const s = this.state();
    return s === 'entering' || s === 'entered' ? 1 : 0;
  });

  protected readonly transformStyle = computed(() => {
    if (this.type() !== 'notification') return undefined;
    const s = this.state();
    if (s === 'entering' || s === 'entered' || s === 'exiting') {
      return 'translate3d(0, 0, 0)';
    }
    const from = this.from();
    return from === 'top'
      ? 'translate3d(0, -100%, 0)'
      : 'translate3d(100%, 0, 0)';
  });

  protected readonly visibilityStyle = computed(() => {
    if (this.type() !== 'notification') return undefined;
    const s = this.state();
    return s === 'exited' ? 'hidden' : undefined;
  });

  // ─── Dropdown state placeholder ─────────────────────────────────────
  // TODO: wire to MznDropdown + MznPopper for full React parity (drawer mode
  // dot button opens an options dropdown, and timestamp hover reveals a raw
  // timestamp popper).
  protected readonly openDropdown = signal(false);

  ngOnInit(): void {
    if (this.type() === 'notification') {
      // Trigger enter transition after first render so the browser commits
      // the initial exited paint before we flip to entering (matches React
      // Transition's slide+fade behaviour via useSetNodeTransition).
      queueMicrotask(() => this.triggerEnter());
    } else {
      this.state.set('entered');
    }

    const duration = this.duration();
    if (
      this.type() === 'notification' &&
      typeof duration === 'number' &&
      duration > 0
    ) {
      const timer = setTimeout(() => this.startExit(), duration);
      this.destroyRef.onDestroy(() => clearTimeout(timer));
    }
  }

  protected onMouseEnter(): void {
    if (this.type() !== 'drawer' || !this.isToday()) return;
    // Defer anchor pickup so the Popper reads a laid-out DOM element.
    queueMicrotask(() => {
      const el = this.timeStampEl()?.nativeElement ?? null;
      this.timeStampAnchor.set(el);
    });
  }

  protected onMouseLeave(): void {
    if (this.type() !== 'drawer') return;
    this.timeStampAnchor.set(null);
  }

  protected onConfirmClick(): void {
    this.confirmed.emit();
    this.startExit();
  }

  protected onCancelClick(): void {
    this.cancelled.emit();
    this.startExit();
  }

  protected onCloseClick(): void {
    this.closed.emit(this.reference());
    this.startExit();
  }

  protected onDotButtonClick(): void {
    this.closed.emit(this.reference());
  }

  protected onBadgeClick(event: Event): void {
    event.stopPropagation();
    this.badgeClicked.emit();
    if (this.options().length > 0) {
      this.openDropdown.set(true);
    }
  }

  protected onBadgeSelect(option: DropdownOption): void {
    this.badgeSelected.emit(option);
    this.openDropdown.set(false);
  }

  private triggerEnter(): void {
    const node = this.hostRef.nativeElement;
    node.style.transition = buildTransitionString('enter', ['transform'], {
      delay: 0,
      duration: {
        enter: MOTION_DURATION.slow,
        exit: MOTION_DURATION.moderate,
      },
      easing: {
        enter: MOTION_EASING.standard,
        exit: MOTION_EASING.exit,
      },
    });
    reflow(node);

    // Double rAF — let browser paint the exited state before flipping so the
    // transition actually animates (same guard MznTranslate/MznFade use).
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        this.state.set('entering');
        const handler = (): void => {
          node.removeEventListener('transitionend', handler);
          this.state.set('entered');
          node.style.transition = '';
        };
        node.addEventListener('transitionend', handler);
      });
    });
  }

  private startExit(): void {
    if (this.type() !== 'notification') return;
    const node = this.hostRef.nativeElement;
    node.style.transition = buildTransitionString('exit', ['opacity'], {
      delay: 0,
      duration: {
        enter: MOTION_DURATION.slow,
        exit: MOTION_DURATION.moderate,
      },
      easing: {
        enter: MOTION_EASING.standard,
        exit: MOTION_EASING.exit,
      },
    });
    this.state.set('exiting');
    const handler = (): void => {
      node.removeEventListener('transitionend', handler);
      this.state.set('exited');
      node.style.transition = '';
    };
    node.addEventListener('transitionend', handler);
  }
}

// packages/vue/notification-center/notification-center.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import type { ComponentPublicInstance, CSSProperties } from 'vue';
import { flip, offset } from '@floating-ui/dom';
import type { DropdownOption } from '@mezzanine-ui/core/dropdown/dropdown';
import {
  notificationClasses as classes,
  notificationIcons,
} from '@mezzanine-ui/core/notification-center';
import { CloseIcon, DotHorizontalIcon } from '@mezzanine-ui/icons';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { resolveElement } from '../_internal/resolve-element';
import MznBadge from '../badge/badge.vue';
import MznButtonGroup from '../button/button-group.vue';
import MznButton from '../button/button.vue';
import MznDropdown from '../dropdown/dropdown.vue';
import MznIcon from '../icon/icon.vue';
import MznPopper from '../popper/popper.vue';
import MznTypography from '../typography/typography.vue';
import { getTransitionStyleProps } from '../transition/get-transition-style-props';
import type { NotificationData } from './notification-center.types';

/**
 * 單則通知的呈現：`notification` 是浮動提示，`drawer` 是抽屜清單裡的一列。
 *
 * 由通知中心的工廠建立，也可以直接寫在畫面上。浮動模式從邊緣滑入、關閉時淡出；
 * 抽屜模式改用時間戳與徽章下拉，滑鼠移上今天的時間戳會浮出完整時間。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznNotificationCenter } from '@mezzanine-ui/vue/notification-center';
 * <\/script>
 *
 * <template>
 *   <MznNotificationCenter severity="success" title="儲存成功" type="notification" />
 * </template>
 * ```
 *
 * @see notificationCenter 命令式觸發通知的工廠
 * @see MznNotificationCenterDrawer 抽屜清單模式的容器
 */
const props = withDefaults(defineProps<NotificationData>(), {
  appendTips: undefined,
  cancelButtonProps: () => ({}),
  cancelButtonText: 'Cancel',
  children: undefined,
  confirmButtonProps: () => ({}),
  confirmButtonText: 'Confirm',
  description: undefined,
  duration: undefined,
  easing: undefined,
  from: 'top',
  maxVisibleNotifications: undefined,
  onBadgeClick: undefined,
  onBadgeSelect: undefined,
  onCancel: undefined,
  onClose: undefined,
  onConfirm: undefined,
  onEnter: undefined,
  onEntered: undefined,
  onExit: undefined,
  onExited: undefined,
  onViewAll: undefined,
  options: undefined,
  prependTips: undefined,
  reference: undefined,
  severity: 'info',
  showBadge: undefined,
  timeStamp: () => new Date().toLocaleTimeString(),
  timeStampLocale: 'zh-TW',
  title: undefined,
  type: 'notification',
  viewAllButtonText: undefined,
});

/**
 * The tips around a drawer notification are roots of their own, as React's
 * fragment is, and React's own component takes no native props — so there is
 * nothing to forward.
 */
defineOptions({ inheritAttrs: false });

const SLIDE_FADE_DURATION = {
  enter: MOTION_DURATION.slow,
  exit: MOTION_DURATION.moderate,
};

const SLIDE_FADE_EASING = {
  enter: MOTION_EASING.standard,
  exit: MOTION_EASING.exit,
};

const targetIcon = computed(() => notificationIcons[props.severity]);

const open = ref(true);
const openDropdown = ref(false);
const timeStampAnchor = ref<HTMLElement | null>(null);
const timeStampElement = ref<HTMLElement | null>(null);

function setTimeStamp(element: Element | ComponentPublicInstance | null): void {
  timeStampElement.value = resolveElement(element);
}

const easing = computed(() => props.easing ?? SLIDE_FADE_EASING);

const isToday = computed((): boolean => {
  try {
    const timestampDate = new Date(props.timeStamp);

    if (Number.isNaN(timestampDate.getTime())) return false;

    const now = new Date();
    const nowStartOfDay = new Date(
      now.getFullYear(),
      now.getMonth(),
      now.getDate(),
    );
    const timestampStartOfDay = new Date(
      timestampDate.getFullYear(),
      timestampDate.getMonth(),
      timestampDate.getDate(),
    );

    return timestampStartOfDay.getTime() === nowStartOfDay.getTime();
  } catch {
    return false;
  }
});

const formattedTimeStamp = computed((): string => {
  const { timeStamp, timeStampLocale } = props;

  try {
    const timestampDate = new Date(timeStamp);
    const timeStampText =
      typeof timeStamp === 'string' ? timeStamp : String(timeStamp);

    if (Number.isNaN(timestampDate.getTime())) return timeStampText;

    const now = Date.now();
    const nowDate = new Date(now);
    const nowStartOfDay = new Date(
      nowDate.getFullYear(),
      nowDate.getMonth(),
      nowDate.getDate(),
    );
    const timestampStartOfDay = new Date(
      timestampDate.getFullYear(),
      timestampDate.getMonth(),
      timestampDate.getDate(),
    );

    // Only show relative time if the timestamp is today
    if (nowStartOfDay.getTime() === timestampStartOfDay.getTime()) {
      const diffInSeconds = Math.round((timestampDate.getTime() - now) / 1000);
      const rtf = new Intl.RelativeTimeFormat(timeStampLocale, {
        numeric: 'always',
      });

      const units: Array<{
        seconds: number;
        unit: Intl.RelativeTimeFormatUnit;
      }> = [
        { seconds: 3600, unit: 'hour' },
        { seconds: 60, unit: 'minute' },
      ];

      for (const { seconds, unit } of units) {
        const value = Math.round(diffInSeconds / seconds);

        if (Math.abs(value) >= 1) return rtf.format(value, unit);
      }

      return 'now';
    }

    const hasTimeComponent =
      /:\d{2}/.test(timeStampText) || timeStampText.includes('T');

    const dateFormatter = new Intl.DateTimeFormat(
      timeStampLocale,
      hasTimeComponent
        ? {
            day: '2-digit',
            hour: '2-digit',
            hour12: false,
            minute: '2-digit',
            month: '2-digit',
            year: 'numeric',
          }
        : { day: '2-digit', month: '2-digit', year: 'numeric' },
    );

    return dateFormatter.format(timestampDate).replace(/\//g, '-');
  } catch {
    return typeof timeStamp === 'string' ? timeStamp : String(timeStamp);
  }
});

let timer: number | null = null;

function clearTimer(): void {
  if (timer !== null) {
    window.clearTimeout(timer);
    timer = null;
  }
}

watch(
  [open, (): NotificationData['duration'] => props.duration],
  ([isOpen, duration]) => {
    clearTimer();

    if (isOpen && duration) {
      timer = window.setTimeout(() => {
        open.value = false;
      }, duration);
    }
  },
  { immediate: true },
);

onBeforeUnmount(clearTimer);

function onBadgeClick(): void {
  props.onBadgeClick?.();

  if (props.options && props.options.length > 0) openDropdown.value = true;
}

function onClose(): void {
  open.value = false;

  if (props.onClose && props.reference !== undefined) {
    props.onClose(props.reference);
  }
}

const onConfirm = computed(() =>
  props.onConfirm
    ? (): void => {
        open.value = false;
        props.onConfirm?.();
      }
    : undefined,
);

const onCancel = computed(() =>
  props.onCancel
    ? (): void => {
        open.value = false;
        props.onCancel?.();
      }
    : undefined,
);

function onSelect(option: DropdownOption): void {
  props.onBadgeSelect?.(option);
}

function handleMouseEnter(): void {
  if (props.type === 'drawer' && isToday.value) {
    setTimeout(() => {
      if (timeStampElement.value)
        timeStampAnchor.value = timeStampElement.value;
    }, 0);
  }
}

function handleMouseLeave(): void {
  if (props.type === 'drawer' && isToday.value) timeStampAnchor.value = null;
}

const showConfirmButton = computed((): boolean =>
  Boolean(props.confirmButtonText && props.onConfirm),
);

const showCancelButton = computed((): boolean =>
  Boolean(props.cancelButtonText && (props.onCancel || props.onClose)),
);

const hideButtons = computed(
  (): boolean =>
    !(
      props.type === 'notification' &&
      (showConfirmButton.value || showCancelButton.value)
    ),
);

/**
 * The slide and the fade are two separate transitions: entering moves the
 * notification in, leaving only fades it out where it stands.
 */
function transitionFor(property: string, mode: 'enter' | 'exit'): string {
  const { delay, duration, timingFunction } = getTransitionStyleProps(mode, {
    delay: 0,
    duration: SLIDE_FADE_DURATION,
    easing: easing.value,
  });

  return `${property} ${duration}ms ${timingFunction} ${delay}ms`;
}

const exitedTransform = computed((): string =>
  props.from === 'top' ? 'translate3d(0, -100%, 0)' : 'translate3d(100%, 0, 0)',
);

function applyStyle(
  element: HTMLElement,
  style: Record<string, number | string>,
): void {
  Object.entries(style).forEach(([property, value]) => {
    element.style.setProperty(
      property.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`),
      value == null ? '' : String(value),
    );
  });
}

/** Committed before the transition is armed, the way the shared runner does. */
function reflow(element: HTMLElement): void {
  void element.scrollTop;
}

function onBeforeEnter(element: Element): void {
  applyStyle(element as HTMLElement, {
    opacity: 0,
    transform: exitedTransform.value,
    visibility: '',
  });
}

function onEnter(element: Element, done: () => void): void {
  const node = element as HTMLElement;

  node.style.transition = transitionFor('transform', 'enter');
  reflow(node);
  props.onEnter?.(node, true);
  applyStyle(node, { opacity: 1, transform: 'translate3d(0, 0, 0)' });

  window.setTimeout(() => {
    node.style.transition = '';
    props.onEntered?.(node, true);
    done();
  }, SLIDE_FADE_DURATION.enter);
}

function onLeave(element: Element, done: () => void): void {
  const node = element as HTMLElement;

  node.style.transition = transitionFor('opacity', 'exit');
  props.onExit?.(node);
  applyStyle(node, { opacity: 0, transform: 'translate3d(0, 0, 0)' });

  window.setTimeout(() => {
    node.style.transition = '';
    applyStyle(node, {
      opacity: 0,
      transform: exitedTransform.value,
      visibility: 'hidden',
    });
    props.onExited?.(node);
    done();
  }, SLIDE_FADE_DURATION.exit);
}

const hostClasses = computed((): string[] => [
  classes.host,
  classes.severity(props.severity),
  classes.type(props.type),
]);

const TIME_STAMP_POPPER_ARROW = {
  className: classes.timeStampPopperArrow,
  enabled: true,
  padding: 0,
};

const TIME_STAMP_POPPER_STYLE: CSSProperties = {
  zIndex: 'var(--mzn-z-index-popover)',
};

const timeStampPopperOptions = {
  middleware: [offset({ mainAxis: 8 }), flip()],
  placement: 'bottom' as const,
};
</script>

<template>
  <MznTypography
    v-if="type === 'drawer' && prependTips"
    :class="classes.prependTips"
  >
    {{ prependTips }}
  </MznTypography>

  <Transition
    :appear="type === 'notification'"
    :css="false"
    @appear="(element, done) => onEnter(element, done)"
    @appear-cancelled="() => {}"
    @before-appear="onBeforeEnter"
    @before-enter="onBeforeEnter"
    @enter="(element, done) => onEnter(element, done)"
    @leave="(element, done) => onLeave(element, done)"
  >
    <div
      v-if="type !== 'notification' || open"
      :class="hostClasses"
      @mouseenter="handleMouseEnter"
      @mouseleave="handleMouseLeave"
    >
      <div v-if="targetIcon" :class="classes.iconContainer">
        <MznIcon :class="classes.severityIcon" :icon="targetIcon" :size="32" />
      </div>
      <div :class="classes.body">
        <div :class="classes.bodyContent">
          <h4 :class="classes.title">{{ title }}</h4>
          <MznTypography :class="classes.content">
            {{ description }}
          </MznTypography>
        </div>
        <MznButtonGroup v-if="!hideButtons" :class="classes.action">
          <MznButton
            v-if="showCancelButton"
            size="minor"
            variant="base-secondary"
            v-bind="cancelButtonProps"
            @click="onCancel ? onCancel() : onClose()"
          >
            {{ cancelButtonText }}
          </MznButton>
          <MznButton
            v-if="showConfirmButton"
            size="minor"
            v-bind="confirmButtonProps"
            @click="onConfirm?.()"
          >
            {{ confirmButtonText }}
          </MznButton>
        </MznButtonGroup>
        <template v-if="type === 'drawer'">
          <MznPopper
            v-if="isToday"
            :anchor="timeStampAnchor"
            :arrow="TIME_STAMP_POPPER_ARROW"
            :open="Boolean(timeStampAnchor)"
            :options="timeStampPopperOptions"
            :style="TIME_STAMP_POPPER_STYLE"
          >
            <div :class="classes.timeStampPopper">
              <MznTypography :class="classes.timeStampText">
                {{ timeStamp }}
              </MznTypography>
            </div>
          </MznPopper>
          <MznTypography
            :ref="setTimeStamp"
            :class="classes.timeStamp"
            variant="label-secondary"
          >
            {{ formattedTimeStamp }}
          </MznTypography>
        </template>
      </div>
      <MznDropdown
        v-if="type === 'drawer'"
        :open="openDropdown"
        :options="options ?? []"
        placement="bottom-end"
        z-index="var(--mzn-z-index-popover)"
        @close="openDropdown = false"
        @select="onSelect"
        @visibility-change="openDropdown = $event"
      >
        <template #default="trigger">
          <MznButton
            v-bind="trigger"
            :class="classes.dotIconButton"
            variant="base-ghost"
            @click="onClose"
          >
            <MznBadge v-if="showBadge" variant="dot-error" />
            <MznIcon
              :class="classes.closeIcon"
              :icon="DotHorizontalIcon"
              :size="16"
              @click="onBadgeClick"
            />
          </MznButton>
        </template>
      </MznDropdown>
      <MznIcon
        v-else
        :class="classes.closeIcon"
        :icon="CloseIcon"
        :size="16"
        @click="onClose"
      />
    </div>
  </Transition>

  <MznTypography
    v-if="type === 'drawer' && appendTips"
    :class="classes.appendTips"
  >
    {{ appendTips }}
  </MznTypography>
</template>
