// packages/react/src/NotificationCenter/NotificationCenterDrawer.tsx
'use client';

import {
  useMemo,
  type ComponentProps,
  type Key,
  type ReactElement,
} from 'react';

import { DrawerSize } from '@mezzanine-ui/core/drawer';
import { notificationClasses as classes } from '@mezzanine-ui/core/notification-center';


import Drawer, { type DrawerProps } from '../Drawer';
import Empty from '../Empty';
import NotificationCenter, {
  type NotificationData,
} from './NotificationCenter';

type NotificationDataForDrawer = NotificationData & {
  key: Key;
  type: 'drawer';
};

type NotificationCenterDrawerPropsBase = Pick<
  DrawerProps,
  | 'onClose'
  | 'open'
> & {
  /**
   * Label for the "all" filter option in the filter bar.
   */
  filterBarAllRadioLabel?: DrawerProps['filterAreaAllRadioLabel'];
  /**
   * Label for the custom action button in the filter bar.
   */
  filterBarCustomButtonLabel?: DrawerProps['filterAreaCustomButtonLabel'];
  /**
   * Default selected filter value in the filter bar.
   */
  filterBarDefaultValue?: DrawerProps['filterAreaDefaultValue'];
  /**
   * Callback fired when the custom action button is clicked.
   */
  filterBarOnCustomButtonClick?: DrawerProps['filterAreaOnCustomButtonClick'];
  /**
   * Callback fired when the filter option changes.
   */
  filterBarOnRadioChange?: DrawerProps['filterAreaOnRadioChange'];
  /**
   * Label for the "read" filter option in the filter bar.
   */
  filterBarReadRadioLabel?: DrawerProps['filterAreaReadRadioLabel'];
  /**
   * Whether to show the filter bar.
   */
  filterBarShow?: DrawerProps['filterAreaShow'];
  /**
   * Whether to show the "unread only" shortcut button.
   */
  filterBarShowUnreadButton?: DrawerProps['filterAreaShowUnreadButton'];
  /**
   * Label for the "unread" filter option in the filter bar.
   */
  filterBarUnreadRadioLabel?: DrawerProps['filterAreaUnreadRadioLabel'];
  /**
   * Controlled selected filter value in the filter bar.
   */
  filterBarValue?: DrawerProps['filterAreaValue'];
  /**
   * Options for the filter bar dropdown.
   * When non-empty, the right-side filter area button is replaced by a Dropdown
   * triggered by a `DotHorizontalIcon` icon button.
   */
  filterBarOptions?: DrawerProps['filterAreaOptions'];
  /**
   * Callback fired when a filter bar dropdown option is selected.
   * Only used when `filterBarOptions` is non-empty.
   */
  filterBarOnSelect?: DrawerProps['filterAreaOnSelect'];
  /**
   * The size of the drawer.
   * @default 'narrow'
   */
  drawerSize?: DrawerSize;
  /**
   * The label of the "earlier" time group.
   * @default '更早'
   */
  earlierLabel?: string;
  /**
   * The title of the empty notification.
   */
  emptyNotificationTitle?: string;
  /**
   * The description of the empty notification.
   */
  emptyNotificationDescription?: string;
  /**
   * The label for the "past 7 days" time group.
   * @default '過去七天'
   */
  past7DaysLabel?: string;
  /**
   * The title of the drawer.
   */
  title?: string;
  /**
   * The label for the "today" time group.
   * @default '今天'
   */
  todayLabel?: string;
  /**
   * The label for the "yesterday" time group.
   * @default '昨天'
   */
  yesterdayLabel?: string;
};

export type NotificationCenterDrawerProps =
  | (NotificationCenterDrawerPropsBase & {
    /**
     * The children of the drawer.
     * Use this when you want to manually render NotificationCenter components.
     * Can be a single NotificationCenter element or an array of them.
     */
    children:
    | ReactElement<ComponentProps<typeof NotificationCenter>>
    | ReactElement<ComponentProps<typeof NotificationCenter>>[];
    notificationList?: never;
  })
  | (NotificationCenterDrawerPropsBase & {
    /**
     * The list of notifications to render.
     * Use this when you want to pass notification data and let the component render them.
     * Each notification must have `key` and `type: 'drawer'`.
     */
    notificationList: NotificationDataForDrawer[];
    children?: never;
  });

const isValidTime = (timestamp: string | number | undefined): boolean => {
  if (!timestamp) return false;

  const date = new Date(timestamp);

  return !Number.isNaN(date.getTime());
};

const getValidTime = (timestamp: string | number | undefined): number => {
  if (!isValidTime(timestamp)) return 0;

  const date = new Date(timestamp as string | number);

  return date.getTime();
};

type TimeGroup = 'today' | 'yesterday' | 'past7Days' | 'earlier';

const DEFAULT_TIME_GROUP_LABELS: Record<TimeGroup, string> = {
  today: '今天',
  yesterday: '昨天',
  past7Days: '過去七天',
  earlier: '更早',
};

const TIME_GROUP_ORDER: TimeGroup[] = [
  'today',
  'yesterday',
  'past7Days',
  'earlier',
];

const getTimeGroup = (
  timestamp: string | number | undefined,
  now: Date,
): TimeGroup => {
  if (!isValidTime(timestamp)) return 'earlier';

  const notificationDate = new Date(timestamp as string | number);
  const nowStartOfDay = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
  );
  const notificationStartOfDay = new Date(
    notificationDate.getFullYear(),
    notificationDate.getMonth(),
    notificationDate.getDate(),
  );

  // Today: same calendar day
  if (notificationStartOfDay.getTime() === nowStartOfDay.getTime()) {
    return 'today';
  }

  // Yesterday: previous calendar day
  const yesterdayStartOfDay = new Date(nowStartOfDay);
  yesterdayStartOfDay.setDate(yesterdayStartOfDay.getDate() - 1);
  if (notificationStartOfDay.getTime() === yesterdayStartOfDay.getTime()) {
    return 'yesterday';
  }

  // Past 7 days: within 7 days but not today or yesterday
  const diffInDays =
    (now.getTime() - notificationDate.getTime()) / (1000 * 60 * 60 * 24);
  if (diffInDays <= 7) {
    return 'past7Days';
  }

  // Earlier: more than 7 days ago
  return 'earlier';
};

const NotificationCenterDrawer = (props: NotificationCenterDrawerProps) => {
  const {
    children,
    filterBarAllRadioLabel,
    filterBarCustomButtonLabel,
    filterBarDefaultValue,
    filterBarOnCustomButtonClick,
    filterBarOnRadioChange,
    filterBarOnSelect,
    filterBarReadRadioLabel,
    filterBarShow,
    filterBarShowUnreadButton,
    filterBarUnreadRadioLabel,
    filterBarValue,
    filterBarOptions,
    drawerSize = 'narrow',
    earlierLabel,
    emptyNotificationTitle = '目前沒有新的通知',
    emptyNotificationDescription = '當有新的系統通知時，將會顯示在這裡。',
    notificationList,
    onClose,
    open,
    past7DaysLabel,
    title,
    todayLabel,
    yesterdayLabel,
    ...restDrawerProps
  } = props;

  const isEmpty = useMemo(() => {
    if (notificationList) {
      return notificationList.length === 0;
    }

    if (Array.isArray(children)) {
      return children.length === 0;
    }

    return !children;
  }, [notificationList, children]);

  const renderNotifications = useMemo(() => {
    const renderEmptyNotifications = () => {
      return (
        <div className={classes.emptyNotifications}>
          <Empty
            type="notification"
            size="main"
            title={emptyNotificationTitle}
            description={emptyNotificationDescription}
          />
        </div>
      );
    };

    if (isEmpty) {
      return renderEmptyNotifications();
    }

    // Check if notificationList is provided
    if (notificationList) {
      // Sort once by timestamp (newest first), then group while maintaining order
      const sorted = [...notificationList].sort((a, b) => {
        const aTime = getValidTime(a.timeStamp);
        const bTime = getValidTime(b.timeStamp);
        return bTime - aTime;
      });

      // Group sorted notifications
      const now = new Date();
      const grouped = sorted.reduce(
        (acc, notification) => {
          const group = getTimeGroup(notification.timeStamp, now);
          (acc[group] ??= []).push(notification);
          return acc;
        },
        {} as Record<TimeGroup, typeof notificationList>,
      );

      // Get time group labels from props or use defaults
      const timeGroupLabels: Record<TimeGroup, string> = {
        earlier: earlierLabel ?? DEFAULT_TIME_GROUP_LABELS.earlier,
        past7Days: past7DaysLabel ?? DEFAULT_TIME_GROUP_LABELS.past7Days,
        today: todayLabel ?? DEFAULT_TIME_GROUP_LABELS.today,
        yesterday: yesterdayLabel ?? DEFAULT_TIME_GROUP_LABELS.yesterday,
      };

      // Render notifications with prependTips for first item in each group
      return TIME_GROUP_ORDER.flatMap((group) => {
        const notifications = grouped[group];
        if (!notifications?.length) {
          return [];
        }

        return notifications.map((notification, index) => {
          const { key, ...restNotification } = notification;

          return (
            <NotificationCenter
              key={key}
              {...restNotification}
              prependTips={index === 0 ? timeGroupLabels[group] : undefined}
              reference={key}
              type="drawer"
            />
          );
        });
      });
    }

    // Return children (can be single element or array)
    return Array.isArray(children) ? children : children;
  }, [
    isEmpty,
    notificationList,
    children,
    emptyNotificationTitle,
    emptyNotificationDescription,
    earlierLabel,
    past7DaysLabel,
    todayLabel,
    yesterdayLabel,
  ]);

  return (
    <Drawer
      className={classes.drawer}
      filterAreaAllRadioLabel={filterBarAllRadioLabel}
      filterAreaCustomButtonLabel={filterBarCustomButtonLabel}
      filterAreaDefaultValue={filterBarDefaultValue}
      filterAreaIsEmpty={isEmpty}
      filterAreaOnCustomButtonClick={filterBarOnCustomButtonClick}
      filterAreaOnRadioChange={filterBarOnRadioChange}
      filterAreaOnSelect={filterBarOnSelect}
      filterAreaReadRadioLabel={filterBarReadRadioLabel}
      filterAreaShow={filterBarShow}
      filterAreaShowUnreadButton={filterBarShowUnreadButton}
      filterAreaUnreadRadioLabel={filterBarUnreadRadioLabel}
      filterAreaValue={filterBarValue}
      filterAreaOptions={filterBarOptions}
      headerTitle={title}
      isHeaderDisplay={Boolean(title)}
      onClose={onClose}
      open={open}
      size={drawerSize}
      {...restDrawerProps}
    >
      <div className={classes.notificationsContainer}>
        {renderNotifications}
      </div>
    </Drawer>
  );
};

export default NotificationCenterDrawer;

// packages/vue/notification-center/notification-center-drawer.vue
<script setup lang="ts">
import { computed, h, useSlots } from 'vue';
import type { FunctionalComponent, VNodeChild } from 'vue';
import { notificationClasses as classes } from '@mezzanine-ui/core/notification-center';
import { flattenChildren } from '../_internal/flatten-children';
import MznDrawer from '../drawer/drawer.vue';
import MznEmpty from '../empty/empty.vue';
import MznNotificationCenter from './notification-center.vue';
import type {
  NotificationCenterDrawerProps,
  NotificationDataForDrawer,
} from './notification-center-drawer.types';

/**
 * 通知中心的抽屜清單。
 *
 * 通知可以用 `notificationList` 交出去、由這個元件排序分組後渲染，也可以自己把
 * MznNotificationCenter 放進預設 slot。用 `notificationList` 時會依時間戳由新到
 * 舊排序，再分成今天／昨天／過去七天／更早四組，每組第一則帶上組名。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznNotificationCenterDrawer } from '@mezzanine-ui/vue/notification-center';
 * <\/script>
 *
 * <template>
 *   <MznNotificationCenterDrawer
 *     :notification-list="list"
 *     :open="open"
 *     title="通知中心"
 *     @close="open = false"
 *   />
 * </template>
 * ```
 *
 * @see MznNotificationCenter 清單裡的單則通知
 */
const props = withDefaults(defineProps<NotificationCenterDrawerProps>(), {
  drawerSize: 'narrow',
  earlierLabel: undefined,
  emptyNotificationDescription: '當有新的系統通知時，將會顯示在這裡。',
  emptyNotificationTitle: '目前沒有新的通知',
  filterBarAllRadioLabel: undefined,
  filterBarCustomButtonLabel: undefined,
  filterBarDefaultValue: undefined,
  filterBarOnCustomButtonClick: undefined,
  filterBarOnRadioChange: undefined,
  filterBarOnSelect: undefined,
  filterBarOptions: undefined,
  filterBarReadRadioLabel: undefined,
  filterBarShow: undefined,
  filterBarShowUnreadButton: undefined,
  filterBarUnreadRadioLabel: undefined,
  filterBarValue: undefined,
  notificationList: undefined,
  open: undefined,
  past7DaysLabel: undefined,
  title: undefined,
  todayLabel: undefined,
  yesterdayLabel: undefined,
});

const emit = defineEmits<{
  /** Fired when the drawer asks to be closed. */
  close: [];
}>();

defineSlots<{
  /**
   * The notifications, when you want to render them yourself rather than hand
   * over a `notificationList`.
   */
  default?: () => unknown;
}>();

const slots = useSlots();

type TimeGroup = 'today' | 'yesterday' | 'past7Days' | 'earlier';

const DEFAULT_TIME_GROUP_LABELS: Record<TimeGroup, string> = {
  earlier: '更早',
  past7Days: '過去七天',
  today: '今天',
  yesterday: '昨天',
};

const TIME_GROUP_ORDER: TimeGroup[] = [
  'today',
  'yesterday',
  'past7Days',
  'earlier',
];

const isValidTime = (timestamp: number | string | undefined): boolean => {
  if (!timestamp) return false;

  return !Number.isNaN(new Date(timestamp).getTime());
};

const getValidTime = (timestamp: number | string | undefined): number =>
  isValidTime(timestamp) ? new Date(timestamp as number | string).getTime() : 0;

function getTimeGroup(
  timestamp: number | string | undefined,
  now: Date,
): TimeGroup {
  if (!isValidTime(timestamp)) return 'earlier';

  const notificationDate = new Date(timestamp as number | string);
  const nowStartOfDay = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
  );
  const notificationStartOfDay = new Date(
    notificationDate.getFullYear(),
    notificationDate.getMonth(),
    notificationDate.getDate(),
  );

  // Today: same calendar day
  if (notificationStartOfDay.getTime() === nowStartOfDay.getTime()) {
    return 'today';
  }

  // Yesterday: previous calendar day
  const yesterdayStartOfDay = new Date(nowStartOfDay);

  yesterdayStartOfDay.setDate(yesterdayStartOfDay.getDate() - 1);

  if (notificationStartOfDay.getTime() === yesterdayStartOfDay.getTime()) {
    return 'yesterday';
  }

  // Past 7 days: within 7 days but not today or yesterday
  const diffInDays =
    (now.getTime() - notificationDate.getTime()) / (1000 * 60 * 60 * 24);

  return diffInDays <= 7 ? 'past7Days' : 'earlier';
}

const isEmpty = computed((): boolean => {
  if (props.notificationList) return props.notificationList.length === 0;

  return flattenChildren(slots.default?.()).length === 0;
});

const timeGroupLabels = computed(
  (): Record<TimeGroup, string> => ({
    earlier: props.earlierLabel ?? DEFAULT_TIME_GROUP_LABELS.earlier,
    past7Days: props.past7DaysLabel ?? DEFAULT_TIME_GROUP_LABELS.past7Days,
    today: props.todayLabel ?? DEFAULT_TIME_GROUP_LABELS.today,
    yesterday: props.yesterdayLabel ?? DEFAULT_TIME_GROUP_LABELS.yesterday,
  }),
);

const notifications = computed((): VNodeChild => {
  if (isEmpty.value) {
    return h('div', { class: classes.emptyNotifications }, [
      h(MznEmpty, {
        description: props.emptyNotificationDescription,
        size: 'main',
        title: props.emptyNotificationTitle,
        type: 'notification',
      }),
    ]);
  }

  if (!props.notificationList) return slots.default?.();

  // Sort once by timestamp (newest first), then group while keeping the order.
  const sorted = [...props.notificationList].sort(
    (a, b) => getValidTime(b.timeStamp) - getValidTime(a.timeStamp),
  );
  const now = new Date();
  const grouped = sorted.reduce(
    (acc, notification) => {
      const group = getTimeGroup(notification.timeStamp, now);

      (acc[group] ??= []).push(notification);

      return acc;
    },
    {} as Record<TimeGroup, NotificationDataForDrawer[]>,
  );

  return TIME_GROUP_ORDER.flatMap((group) => {
    const groupNotifications = grouped[group];

    if (!groupNotifications?.length) return [];

    return groupNotifications.map((notification, index) => {
      const { key, ...rest } = notification;

      return h(MznNotificationCenter, {
        ...rest,
        key,
        prependTips: index === 0 ? timeGroupLabels.value[group] : undefined,
        reference: key,
        type: 'drawer',
      });
    });
  });
});

const Notifications: FunctionalComponent = () => notifications.value;
</script>

<template>
  <MznDrawer
    :class="classes.drawer"
    :filter-area-all-radio-label="filterBarAllRadioLabel"
    :filter-area-custom-button-label="filterBarCustomButtonLabel"
    :filter-area-default-value="filterBarDefaultValue"
    :filter-area-is-empty="isEmpty"
    :filter-area-on-custom-button-click="filterBarOnCustomButtonClick"
    :filter-area-on-radio-change="filterBarOnRadioChange"
    :filter-area-on-select="filterBarOnSelect"
    :filter-area-options="filterBarOptions"
    :filter-area-read-radio-label="filterBarReadRadioLabel"
    :filter-area-show="filterBarShow"
    :filter-area-show-unread-button="filterBarShowUnreadButton"
    :filter-area-unread-radio-label="filterBarUnreadRadioLabel"
    :filter-area-value="filterBarValue"
    :header-title="title"
    :is-header-display="Boolean(title)"
    :open="open"
    :size="drawerSize"
    @close="emit('close')"
  >
    <div :class="classes.notificationsContainer"><Notifications /></div>
  </MznDrawer>
</template>
