// packages/react/src/TimePanel/TimePanel.tsx
'use client';

import { DateType } from '@mezzanine-ui/core/calendar';
import {
  getUnits,
  timePanelClasses as classes,
  TimePanelUnit,
} from '@mezzanine-ui/core/time-panel';
import { forwardRef, useMemo } from 'react';
import { useCalendarContext } from '../Calendar';
import CalendarFooterActions from '../Calendar/CalendarFooterActions';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import TimePanelColumn from './TimePanelColumn';

export interface TimePanelProps
  extends Omit<
    NativeElementPropsWithoutKeyAndRef<'div'>,
    'value' | 'onChange' | 'children'
  > {
  /**
   * Controls whether or not to hide hours column.
   */
  hideHour?: boolean;
  /**
   * Controls whether or not to hide minutes column.
   */
  hideMinute?: boolean;
  /**
   * Controls whether or not to hide seconds column.
   */
  hideSecond?: boolean;
  /**
   * The steps of hour.
   * @default 1
   */
  hourStep?: number;
  /**
   * The steps of minute.
   * @default 1
   */
  minuteStep?: number;
  /**
   * Change handler. Takes `DateType` as its argument.
   */
  onChange?: (target: DateType) => void;
  /**
   * Called when the user clicks the Cancel button.
   */
  onCancel?: VoidFunction;
  /**
   * Called when the user clicks the Ok button.
   */
  onConfirm?: VoidFunction;
  /**
   * The steps of second.
   * @default 1
   */
  secondStep?: number;
  /**
   * Display value of the panel
   */
  value?: DateType;
}

/**
 * The react component for `mezzanine` time panel.
 * Notice that any component related to time-panel should be used along with `CalendarContext`.
 */
const TimePanel = forwardRef<HTMLDivElement, TimePanelProps>(
  function TimePanel(props, ref) {
    const {
      getHour,
      getMinute,
      getSecond,
      setHour,
      setMinute,
      setSecond,
      startOf,
      getNow,
    } = useCalendarContext();
    const {
      className,
      hideHour = false,
      hideMinute = false,
      hideSecond = false,
      hourStep = 1,
      minuteStep = 1,
      onChange,
      onCancel,
      onConfirm,
      secondStep = 1,
      value,
      ...restHostProps
    } = props;
    const setters = {
      hour: setHour,
      minute: setMinute,
      second: setSecond,
    };
    const hourUnits = useMemo(
      () => (hideHour ? undefined : getUnits(0, 23, hourStep)),
      [hideHour, hourStep],
    );
    const minuteUnits = useMemo(
      () => (hideMinute ? undefined : getUnits(0, 59, minuteStep)),
      [hideMinute, minuteStep],
    );
    const secondUnits = useMemo(
      () => (hideSecond ? undefined : getUnits(0, 59, secondStep)),
      [hideSecond, secondStep],
    );
    const activeHour = value ? getHour(value) : undefined;
    const activeMinute = value ? getMinute(value) : undefined;
    const activeSecond = value ? getSecond(value) : undefined;

    function getChangeHandle(granularity: 'hour' | 'minute' | 'second') {
      if (!onChange) return undefined;

      const setter = setters[granularity];

      const currentValue = value || startOf(getNow(), 'day');

      return (target: TimePanelUnit) => {
        const result = setter(currentValue, target.value);

        onChange(result);
      };
    }

    return (
      <div {...restHostProps} ref={ref} className={cx(classes.host, className)}>
        <div className={classes.columns}>
          {!hideHour && hourUnits && (
            <TimePanelColumn
              units={hourUnits}
              activeUnit={activeHour}
              onChange={getChangeHandle('hour')}
            />
          )}
          {!hideMinute && minuteUnits && (
            <TimePanelColumn
              units={minuteUnits}
              activeUnit={activeMinute}
              onChange={getChangeHandle('minute')}
            />
          )}
          {!hideSecond && secondUnits && (
            <TimePanelColumn
              units={secondUnits}
              activeUnit={activeSecond}
              onChange={getChangeHandle('second')}
            />
          )}
        </div>
        <CalendarFooterActions
          actions={{
            secondaryButtonProps: {
              children: 'Cancel',
              onClick: onCancel,
            },
            primaryButtonProps: {
              children: 'Ok',
              onClick: onConfirm,
            },
          }}
        />
      </div>
    );
  },
);

export default TimePanel;

// packages/vue/time-panel/time-panel.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import type { DateType } from '@mezzanine-ui/core/calendar';
import {
  getUnits,
  timePanelClasses as classes,
  type TimePanelUnit,
} from '@mezzanine-ui/core/time-panel';
import clsx from 'clsx';
import MznCalendarFooterActions from '../calendar/calendar-footer-actions.vue';
import { useCalendarContext } from '../calendar/calendar-context';
import MznTimePanelColumn from './time-panel-column.vue';
import type { TimePanelProps } from './time-panel.types';

/**
 * 時間面板，以時、分、秒三個捲動欄位選取時間。
 *
 * 每個欄位都可以個別隱藏，步進值也可分別設定；沒有 `value` 時以今天的
 * 零點為基準套用選取的單位。底部固定是取消與確認兩顆按鈕。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznTimePanel } from '@mezzanine-ui/vue/time-panel';
 * <\/script>
 *
 * <template>
 *   <MznTimePanel
 *     :minute-step="5"
 *     :value="value"
 *     @cancel="onCancel"
 *     @change="onChange"
 *     @confirm="onConfirm"
 *   />
 * </template>
 * ```
 *
 * @see MznCalendar 日期面板
 * @see MznCalendarConfigProvider 提供日期函式庫與語系
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<TimePanelProps>(), {
  hideHour: false,
  hideMinute: false,
  hideSecond: false,
  hourStep: 1,
  minuteStep: 1,
  secondStep: 1,
  value: undefined,
});

const emit = defineEmits<{
  cancel: [];
  change: [target: DateType];
  confirm: [];
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const hourUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideHour ? undefined : getUnits(0, 23, props.hourStep),
);

const minuteUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideMinute ? undefined : getUnits(0, 59, props.minuteStep),
);

const secondUnits = computed((): TimePanelUnit[] | undefined =>
  props.hideSecond ? undefined : getUnits(0, 59, props.secondStep),
);

const activeHour = computed((): number | undefined =>
  props.value ? calendar.value.getHour(props.value) : undefined,
);

const activeMinute = computed((): number | undefined =>
  props.value ? calendar.value.getMinute(props.value) : undefined,
);

const activeSecond = computed((): number | undefined =>
  props.value ? calendar.value.getSecond(props.value) : undefined,
);

function handleChange(
  granularity: 'hour' | 'minute' | 'second',
  target: TimePanelUnit,
): void {
  const { getNow, setHour, setMinute, setSecond, startOf } = calendar.value;
  const setter = { hour: setHour, minute: setMinute, second: setSecond }[
    granularity
  ];
  const currentValue = props.value || startOf(getNow(), 'day');

  emit('change', setter(currentValue, target.value));
}

const actions = computed(() => ({
  secondaryButtonProps: {
    children: 'Cancel',
    onClick: () => emit('cancel'),
  },
  primaryButtonProps: {
    children: 'Ok',
    onClick: () => emit('confirm'),
  },
}));

const hostClasses = computed((): string =>
  clsx(classes.host, attrs.class as string),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const columnsClass = classes.columns;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="hostClasses">
    <div :class="columnsClass">
      <MznTimePanelColumn
        v-if="!hideHour && hourUnits"
        :active-unit="activeHour"
        :units="hourUnits"
        @change="handleChange('hour', $event)"
      />
      <MznTimePanelColumn
        v-if="!hideMinute && minuteUnits"
        :active-unit="activeMinute"
        :units="minuteUnits"
        @change="handleChange('minute', $event)"
      />
      <MznTimePanelColumn
        v-if="!hideSecond && secondUnits"
        :active-unit="activeSecond"
        :units="secondUnits"
        @change="handleChange('second', $event)"
      />
    </div>
    <MznCalendarFooterActions :actions="actions" />
  </div>
</template>
