// packages/vue/upload/upload.vue
<script setup lang="ts">
import { computed, h, ref } from 'vue';
import type { VNodeChild } from 'vue';
import {
  defaultUploadPictureCardErrorMessage,
  uploadClasses as classes,
} from '@mezzanine-ui/core/upload';
import type {
  UploadItemStatus,
  UploadItemType,
} from '@mezzanine-ui/core/upload';
import { DangerousFilledIcon, InfoFilledIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznMediaPreviewModal from '../modal/media-preview-modal.vue';
import MznUploadItem from './upload-item.vue';
import MznUploadPictureCard from './upload-picture-card.vue';
import MznUploader from './uploader.vue';
import { isImageFile } from './upload-utils';
import type { UploaderProps } from './uploader.types';
import type { UploadFile, UploadProps } from './upload.types';

/**
 * 檔案上傳：一個觸發區加上一份檔案清單。
 *
 * `mode` 決定版面：`list` / `basic-list` / `button-list` 用清單呈現，`cards` /
 * `card-wall` 用圖片卡片。檔案狀態完全受控 —— 拿 `files` 進來、用 `change` 出去。
 * `onUpload` 的回傳值會被讀取，後端給的 id 與狀態會寫回清單。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznUpload } from '@mezzanine-ui/vue/upload';
 * <\/script>
 *
 * <template>
 *   <MznUpload :files="files" multiple @change="files = $event" />
 * </template>
 * ```
 *
 * @see MznUploader 只要觸發區時用這個
 */
const props = withDefaults(defineProps<UploadProps>(), {
  accept: undefined,
  ariaLabels: undefined,
  disabled: false,
  dropzoneHints: undefined,
  errorIcon: undefined,
  errorMessage: undefined,
  files: () => [],
  hints: undefined,
  id: undefined,
  inputProps: undefined,
  maxFiles: undefined,
  mode: 'list',
  multiple: false,
  name: undefined,
  onUpload: undefined,
  showFileSize: true,
  size: 'main',
  uploaderIcon: undefined,
  uploaderLabel: undefined,
});

const emit = defineEmits<{
  /** Fired when the file list changes. */
  change: [files: UploadFile[]];
  /** Fired when a file is deleted. */
  delete: [fileId: string, file: File];
  /** Fired when a file is downloaded (done state). */
  download: [fileId: string, file: File];
  /** Fired when the maximum number of files is exceeded. */
  maxFilesExceeded: [
    maxFiles: number,
    selectedCount: number,
    currentCount: number,
  ];
  /** Fired when a file upload is retried (error state). */
  reload: [fileId: string, file: File];
  /** Fired when zoom in is clicked on a picture card (done state). */
  zoomIn: [fileId: string, file: File];
}>();

/**
 * The list as the async upload flow last left it. React keeps the same thing in
 * a ref so that a handler resolving later works from the current list rather
 * than the one it closed over.
 */
let latestFiles: UploadFile[] = props.files;

const files = computed((): UploadFile[] => {
  latestFiles = props.files;

  return props.files;
});

const replaceFileId = ref<string | null>(null);
const replaceInput = ref<HTMLInputElement | null>(null);

const previewFile = ref<UploadFile | null>(null);
const isPreviewOpen = ref(false);
const previewObjectUrl = ref<string | null>(null);

const defaultErrorIconElement = computed(
  (): VNodeChild =>
    props.errorIcon ??
    h(MznIcon, { color: 'error', icon: DangerousFilledIcon, size: 24 }),
);

const isMaxFilesReached = computed((): boolean => {
  if (props.maxFiles === undefined) return false;

  return files.value.length >= props.maxFiles;
});

const effectiveDisabled = computed(
  (): boolean => props.disabled || isMaxFilesReached.value,
);

const findFileById = (fileId: string): UploadFile | undefined =>
  latestFiles.find((file) => file.id === fileId);

function emitChange(nextFiles: UploadFile[]): void {
  latestFiles = nextFiles;
  emit('change', nextFiles);
}

async function handleUpload(selectedFiles: File[]): Promise<void> {
  if (!selectedFiles.length) return;

  // A replacement drops the file it stands in for before anything else.
  if (replaceFileId.value !== null) {
    const fileIdToReplace = replaceFileId.value;

    replaceFileId.value = null;
    latestFiles = latestFiles.filter((file) => file.id !== fileIdToReplace);
  }

  let accepted = selectedFiles;

  if (props.maxFiles !== undefined) {
    const currentCount = latestFiles.length;
    const selectedCount = accepted.length;

    if (currentCount + selectedCount > props.maxFiles) {
      const allowedCount = Math.max(0, props.maxFiles - currentCount);

      if (allowedCount <= 0) {
        emit('maxFilesExceeded', props.maxFiles, selectedCount, currentCount);

        return;
      }

      accepted = accepted.slice(0, allowedCount);
      emit('maxFilesExceeded', props.maxFiles, selectedCount, currentCount);
    }
  }

  // A batch timestamp plus the index is unique within this batch, which is all
  // the id has to be until the backend hands back the real one.
  const batchId = Date.now();
  const tempFiles: UploadFile[] = accepted.map((file, index) => ({
    file,
    id: `temp-${batchId}-${index}`,
    progress: 0,
    status: 'loading' as UploadItemStatus,
  }));

  emitChange([...latestFiles, ...tempFiles]);

  if (!props.onUpload) {
    emitChange(
      latestFiles.map((file) =>
        tempFiles.some((temp) => temp.id === file.id)
          ? { ...file, progress: 100, status: 'done' as UploadItemStatus }
          : file,
      ),
    );

    return;
  }

  const tempIdToIndex = new Map<string, number>();

  tempFiles.forEach((tempFile, index) => {
    tempIdToIndex.set(tempFile.id, index);
  });

  const setProgress = (fileIndex: number, progress: number): void => {
    const targetFile = tempFiles[fileIndex];

    if (!targetFile) return;

    emitChange(
      latestFiles.map((file) =>
        file.id === targetFile.id ? { ...file, progress } : file,
      ),
    );
  };

  try {
    const result = await Promise.resolve(props.onUpload(accepted, setProgress));

    if (Array.isArray(result) && result.length > 0) {
      const [firstItem] = result;
      const isFullUploadFile = 'file' in firstItem && 'status' in firstItem;

      if (isFullUploadFile) {
        const backendFiles = result as UploadFile[];

        emitChange(
          latestFiles.map((file) => {
            const tempIndex = tempIdToIndex.get(file.id);

            if (tempIndex === undefined || tempIndex >= backendFiles.length) {
              return file;
            }

            const backendFile = backendFiles[tempIndex];

            if (backendFile.status === 'error') {
              return {
                ...backendFile,
                errorIcon:
                  backendFile.errorIcon ?? defaultErrorIconElement.value,
                errorMessage:
                  backendFile.errorMessage ??
                  props.errorMessage ??
                  defaultUploadPictureCardErrorMessage,
              };
            }

            return backendFile;
          }),
        );

        return;
      }

      const backendIds = result as Array<{ id: string }>;

      emitChange(
        latestFiles.map((file) => {
          const tempIndex = tempIdToIndex.get(file.id);

          if (tempIndex === undefined || tempIndex >= backendIds.length) {
            return file;
          }

          return {
            ...file,
            id: backendIds[tempIndex].id,
            progress: 100,
            status: 'done' as UploadItemStatus,
          };
        }),
      );

      return;
    }

    emitChange(
      latestFiles.map((file) =>
        tempFiles.some((temp) => temp.id === file.id)
          ? { ...file, progress: 100, status: 'done' as UploadItemStatus }
          : file,
      ),
    );
  } catch (error) {
    console.error('Upload failed:', error);

    emitChange(
      latestFiles.map((file) => {
        if (!tempFiles.some((temp) => temp.id === file.id)) return file;

        return {
          ...file,
          errorIcon: file.errorIcon ?? defaultErrorIconElement.value,
          errorMessage:
            file.errorMessage ??
            props.errorMessage ??
            defaultUploadPictureCardErrorMessage,
          status: 'error' as UploadItemStatus,
        };
      }),
    );
  }
}

function handleDelete(fileId: string): void {
  const file = findFileById(fileId);

  if (!file) return;

  emitChange(latestFiles.filter((item) => item.id !== fileId));

  if (file.file) emit('delete', fileId, file.file);
}

function handleReload(fileId: string): void {
  const file = findFileById(fileId);

  if (!file) return;

  emitChange(
    latestFiles.map((item) =>
      item.id === fileId
        ? { ...item, progress: 0, status: 'loading' as UploadItemStatus }
        : item,
    ),
  );

  if (file.file) emit('reload', fileId, file.file);
}

function handleDownload(fileId: string): void {
  const file = findFileById(fileId);

  if (file?.file) emit('download', fileId, file.file);
}

let previewObjectUrlToRevoke: string | null = null;

function handleZoomIn(fileId: string): void {
  const file = findFileById(fileId);

  if (!file) return;

  previewFile.value = file;
  isPreviewOpen.value = true;

  if (previewObjectUrlToRevoke) {
    URL.revokeObjectURL(previewObjectUrlToRevoke);
    previewObjectUrlToRevoke = null;
  }

  if (!file.url && file.file && isImageFile(file.file, file.url)) {
    previewObjectUrlToRevoke = URL.createObjectURL(file.file);
    previewObjectUrl.value = previewObjectUrlToRevoke;
  } else {
    previewObjectUrl.value = null;
  }

  if (file.file) emit('zoomIn', fileId, file.file);
}

const previewIsImage = computed((): boolean =>
  previewFile.value
    ? isImageFile(previewFile.value.file, previewFile.value.url)
    : false,
);

const previewImageSrc = computed(
  (): string => previewFile.value?.url ?? previewObjectUrl.value ?? '',
);

const imageFiles = computed((): UploadFile[] =>
  files.value.filter((file) => isImageFile(file.file, file.url)),
);

const nonImageFiles = computed((): UploadFile[] =>
  files.value.filter((file) => !isImageFile(file.file, file.url)),
);

const UPLOADER_CONFIG: Record<string, UploaderProps> = {
  'basic-list': { mode: 'basic', type: 'base' },
  'button-list': { type: 'button' },
  'card-wall': { mode: 'basic', type: 'base' },
  cards: { mode: 'basic', type: 'base' },
  list: { mode: 'dropzone', type: 'base' },
};

const uploaderConfig = computed(
  (): UploaderProps => UPLOADER_CONFIG[props.mode],
);

const topUploaderConfig = computed((): UploaderProps | null =>
  props.mode === 'card-wall' ? { mode: 'dropzone', type: 'base' } : null,
);

const shouldUsePictureCard = computed((): boolean =>
  /cards|card-wall/.test(props.mode),
);

const isSingleFileCardMode = computed(
  (): boolean => shouldUsePictureCard.value && props.maxFiles === 1,
);

/** The inline card uploader is redundant once a top one exists. */
const showInlineCardUploader = computed(
  (): boolean => topUploaderConfig.value === null,
);

const uploaderBindings = computed(() => ({
  accept: props.accept,
  disabled: effectiveDisabled.value,
  icon: props.uploaderIcon,
  inputProps: props.inputProps,
  label: props.uploaderLabel,
  multiple: props.multiple,
  name: props.name,
}));

const itemTypeOf = (file: UploadFile): UploadItemType =>
  isImageFile(file.file, file.url) ? 'thumbnail' : 'icon';

const renderableFiles = (list: UploadFile[]): UploadFile[] =>
  list.filter((file) => file.file || file.url);

const hintsClassName = computed((): string =>
  props.mode === 'list' || props.mode === 'card-wall' || props.mode === 'cards'
    ? classes.fillWidthHints
    : classes.hints,
);

const hasHints = computed((): boolean => Boolean(props.hints?.length));

const hostClasses = computed((): string =>
  clsx(classes.host, props.mode === 'cards' && classes.hostCards),
);

const uploadListClasses = computed((): string =>
  clsx(
    classes.uploadList,
    shouldUsePictureCard.value && classes.uploadListCards,
  ),
);

function onReplaceInputChange(event: Event): void {
  const target = event.target as HTMLInputElement;
  const selectedFiles = Array.from(target.files ?? []);

  target.value = '';

  if (selectedFiles.length) void handleUpload(selectedFiles);
}

function onReplace(fileId: string, event: MouseEvent): void {
  event.stopPropagation();
  replaceFileId.value = fileId;
  replaceInput.value?.click();
}

const REPLACE_INPUT_STYLE = { display: 'none' };
</script>

<template>
  <div :class="hostClasses">
    <MznUploader
      v-if="topUploaderConfig"
      v-bind="{ ...uploaderBindings, ...topUploaderConfig }"
      :hints="dropzoneHints"
      :id="id ? `${id}-top` : undefined"
      @upload="handleUpload"
    />
    <ul v-if="mode === 'card-wall' && hasHints" :class="hintsClassName">
      <li
        v-for="hint in hints"
        :key="hint.label"
        :class="classes.hint(hint.type || 'info')"
      >
        <MznIcon
          :color="hint.type === 'info' ? 'info' : 'error'"
          :icon="hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon"
          :size="14"
        />
        {{ hint.label }}
      </li>
    </ul>
    <div v-if="!shouldUsePictureCard" :class="classes.uploadButtonList">
      <MznUploader
        v-bind="{ ...uploaderBindings, ...uploaderConfig }"
        :hints="uploaderConfig.mode === 'dropzone' ? dropzoneHints : undefined"
        :id="id"
        @upload="handleUpload"
      />
      <ul v-if="hasHints" :class="hintsClassName">
        <li
          v-for="hint in hints"
          :key="hint.label"
          :class="classes.hint(hint.type || 'info')"
        >
          <MznIcon
            :color="hint.type === 'info' ? 'info' : 'error'"
            :icon="hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon"
            :size="14"
          />
          {{ hint.label }}
        </li>
      </ul>
    </div>
    <div :class="uploadListClasses">
      <template v-if="shouldUsePictureCard">
        <MznUploadPictureCard
          v-for="uploadFile in imageFiles"
          :key="uploadFile.id"
          :aria-labels="ariaLabels"
          :disabled="disabled"
          :error-message="uploadFile.errorMessage"
          :file="uploadFile.file"
          :id="uploadFile.id"
          :size="size"
          :status="uploadFile.status"
          :url="uploadFile.url"
          @delete="handleDelete(uploadFile.id)"
          @reload="handleReload(uploadFile.id)"
          v-on="
            isSingleFileCardMode
              ? {
                  replace: (event: MouseEvent) =>
                    onReplace(uploadFile.id, event),
                }
              : {
                  download: () => handleDownload(uploadFile.id),
                  zoomIn: () => handleZoomIn(uploadFile.id),
                }
          "
        />
        <MznUploadPictureCard
          v-for="uploadFile in nonImageFiles"
          :key="uploadFile.id"
          :aria-labels="ariaLabels"
          :disabled="disabled"
          :error-message="uploadFile.errorMessage"
          :file="uploadFile.file"
          :id="uploadFile.id"
          :size="size"
          :status="uploadFile.status"
          :url="uploadFile.url"
          @delete="handleDelete(uploadFile.id)"
          @reload="handleReload(uploadFile.id)"
          v-on="
            isSingleFileCardMode
              ? {}
              : { download: () => handleDownload(uploadFile.id) }
          "
        />
        <MznUploader
          v-if="
            showInlineCardUploader &&
            (!isSingleFileCardMode || imageFiles.length === 0)
          "
          v-bind="{ ...uploaderBindings, ...uploaderConfig }"
          :hints="
            uploaderConfig.mode === 'dropzone' ? dropzoneHints : undefined
          "
          :id="id"
          @upload="handleUpload"
        />
        <input
          v-if="isSingleFileCardMode"
          ref="replaceInput"
          :accept="accept"
          :style="REPLACE_INPUT_STYLE"
          type="file"
          @change="onReplaceInputChange"
        />
      </template>
      <template v-if="!shouldUsePictureCard">
        <MznUploadItem
          v-for="uploadFile in renderableFiles(nonImageFiles)"
          :key="uploadFile.id"
          :disabled="disabled"
          :file="uploadFile.file"
          :id="uploadFile.id"
          :show-file-size="showFileSize"
          :size="size"
          :status="uploadFile.status"
          :type="itemTypeOf(uploadFile)"
          :url="uploadFile.url"
          @delete="handleDelete(uploadFile.id)"
          @download="handleDownload(uploadFile.id)"
          @reload="handleReload(uploadFile.id)"
        />
        <MznUploadItem
          v-for="uploadFile in renderableFiles(imageFiles)"
          :key="uploadFile.id"
          :disabled="disabled"
          :file="uploadFile.file"
          :id="uploadFile.id"
          :show-file-size="showFileSize"
          :size="size"
          :status="uploadFile.status"
          :type="itemTypeOf(uploadFile)"
          :url="uploadFile.url"
          @delete="handleDelete(uploadFile.id)"
          @download="handleDownload(uploadFile.id)"
          @reload="handleReload(uploadFile.id)"
        />
      </template>
    </div>
    <ul v-if="mode === 'cards' && hasHints" :class="hintsClassName">
      <li
        v-for="hint in hints"
        :key="hint.label"
        :class="classes.hint(hint.type || 'info')"
      >
        <MznIcon
          :color="hint.type === 'info' ? 'info' : 'error'"
          :icon="hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon"
          :size="14"
        />
        {{ hint.label }}
      </li>
    </ul>
    <MznMediaPreviewModal
      v-if="previewFile && previewIsImage && previewImageSrc"
      :media-items="[previewImageSrc]"
      :open="isPreviewOpen"
      @close="isPreviewOpen = false"
    />
  </div>
</template>

// packages/react/src/Upload/Upload.tsx
'use client';

import {
  type UploadItemStatus,
  type UploadItemType,
  type UploadMode,
  type UploadSize,
} from '@mezzanine-ui/core/upload';
import {
  forwardRef,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  type ReactNode,
} from 'react';

import {
  uploadClasses as classes,
  defaultUploadPictureCardErrorMessage,
} from '@mezzanine-ui/core/upload';

import { DangerousFilledIcon, InfoFilledIcon } from '@mezzanine-ui/icons';

import Icon from '../Icon';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { isImageFile } from './upload-utils';
import type { UploaderProps } from './Uploader';
import Uploader from './Uploader';
import UploadItem from './UploadItem';
import UploadPictureCard from './UploadPictureCard';

export interface UploadFile {
  /**
   * The file object.
   * Required when uploading new files.
   * Optional when `url` is provided for already uploaded files.
   */
  file?: File;
  /**
   * The URL of the uploaded file.
   * When provided, this will be used to display files that have already been uploaded to the server.
   * Useful for loading file lists from the backend.
   */
  url?: string;
  /**
   * The unique id of the file.
   */
  id: string;
  /**
   * The upload status of the file.
   * @default 'loading'
   */
  status: UploadItemStatus;
  /**
   * The upload progress percentage (0-100).
   * @default 0
   */
  progress?: number;
  /**
   * Error message to display when status is 'error'.
   * If not provided, the default error message from Upload component will be used.
   */
  errorMessage?: string;
  /**
   * Error icon to display when status is 'error'.
   * If not provided, the default error icon from Upload component will be used.
   */
  errorIcon?: ReactNode;
}

export interface UploadProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'div'>, 'onChange'> {
  /**
   * The accept attributes of native input element.
   * @example 'image/*', '.pdf,.doc,.docx'
   */
  accept?: string;
  /**
   * Whether the upload is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Controlled file list for the upload component.
   * Provide this along with `onChange` to fully control the file state.
   */
  files?: UploadFile[];
  /**
   * Array of hints to display with the upload component.
   */
  hints?: UploaderProps['hints'];
  /**
   * Icon configuration for different actions and states.
   */
  uploaderIcon?: UploaderProps['icon'];
  /**
   * The id of input element.
   */
  id?: string;
  /**
   * Since at Mezzanine we use a host element to wrap our input, most derived props will be passed to the host element.
   * If you need direct control to the input element, use this prop to provide to it.
   */
  inputProps?: UploaderProps['inputProps'];
  /**
   * The react ref passed to input element.
   */
  inputRef?: UploaderProps['inputRef'];
  /**
   * Maximum number of files allowed to upload.
   * If exceeded, the excess files will be ignored.
   */
  maxFiles?: number;
  /**
   * The display mode for the upload component.
   * - 'list': Display files as a list using UploadItem
   * - 'button-list': Display uploader as a button with files in list format
   * - 'cards': Display image files as picture cards using UploadPictureCard
   * - 'card-wall': Display uploader at top with image files as picture cards below
   * @default 'list'
   */
  mode?: UploadMode;
  /**
   * Whether can select multiple files to upload.
   * @default false
   */
  multiple?: boolean;
  /**
   * The name attribute of the input element.
   */
  name?: string;
  /**
   * The size of the upload component.
   * @default 'main'
   */
  size?: UploadSize;
  /**
   * Whether to show file size in list mode.
   * @default true
   */
  showFileSize?: boolean;
  /**
   * Label configuration for different states.
   */
  uploaderLabel?: UploaderProps['label'];
  /**
   * Default error message to display when upload fails.
   * This will be used when a file's status becomes 'error' and no errorMessage is provided.
   */
  errorMessage?: string;
  /**
   * Default error icon to display when upload fails.
   * This will be used when a file's status becomes 'error' and no errorIcon is provided.
   */
  errorIcon?: ReactNode;
  /**
   * Fired when files list changes.
   */
  onChange?: (files: UploadFile[]) => void;
  /**
   * Fired when a file is deleted.
   */
  onDelete?: (fileId: string, file: File) => void;
  /**
   * Fired when a file is downloaded (done state).
   */
  onDownload?: (fileId: string, file: File) => void;
  /**
   * Fired when the maximum number of files is exceeded.
   * @param maxFiles - The maximum number of files allowed
   * @param selectedCount - The number of files selected
   * @param currentCount - The current number of files in the list
   */
  onMaxFilesExceeded?: (
    maxFiles: number,
    selectedCount: number,
    currentCount: number,
  ) => void;
  /**
   * Fired when a file upload is retried (error state).
   */
  onReload?: (fileId: string, file: File) => void;
  /**
   * Fired when files are selected for upload.
   * @param files - The files to upload
   * @param setProgress - Callback to update upload progress for a specific file (file index, progress 0-100)
   * @returns Can return:
   *   - UploadFile[]: Full file objects with backend-provided IDs and status
   *   - { id: string }[]: Array of objects with backend-provided IDs (status will be set to 'done')
   *   - void/Promise<void>: For backward compatibility (status will be set to 'done')
   */
  onUpload?: (
    files: File[],
    setProgress?: (fileIndex: number, progress: number) => void,
  ) =>
    | Promise<UploadFile[]>
    | UploadFile[]
    | Promise<Array<{ id: string }>>
    | Array<{ id: string }>
    | Promise<void>
    | void;
  /**
   * Fired when zoom in is clicked on a picture card (done state).
   */
  onZoomIn?: (fileId: string, file: File) => void;
}

const Upload = forwardRef<HTMLDivElement, UploadProps>(
  function Upload(props, ref) {
    const {
      accept,
      className,
      disabled = false,
      mode = 'list',
      size = 'main',
      showFileSize = true,
      files: controlledFiles = [],
      onUpload,
      onDelete,
      onReload,
      onDownload,
      onZoomIn,
      onChange,
      id,
      name,
      multiple = false,
      maxFiles,
      hints,
      uploaderLabel,
      uploaderIcon,
      inputRef,
      inputProps,
      onMaxFilesExceeded,
      errorMessage,
      errorIcon,
      ...rest
    } = props;

    const files = controlledFiles;
    const filesRef = useRef<UploadFile[]>(files);
    const replaceFileIdRef = useRef<string | null>(null);
    const replaceInputRef = useRef<HTMLInputElement>(null);

    useEffect(() => {
      filesRef.current = files;
    }, [files]);

    // Default error icon when status is error and no errorIcon is provided
    const defaultErrorIconElement = useMemo(
      () =>
        errorIcon ?? (
          <Icon icon={DangerousFilledIcon} color="error" size={24} />
        ),
      [errorIcon],
    );

    // Auto-disable when maxFiles is reached
    const isMaxFilesReached = useMemo(() => {
      if (maxFiles === undefined) return false;
      return files.length >= maxFiles;
    }, [files.length, maxFiles]);

    const effectiveDisabled = disabled || isMaxFilesReached;

    // Helper function to find file by ID
    const findFileById = useCallback(
      (fileId: string): UploadFile | undefined => {
        return filesRef.current.find((f) => f.id === fileId);
      },
      [],
    );

    const emitChange = useCallback(
      (nextFiles: UploadFile[]) => {
        filesRef.current = nextFiles;
        onChange?.(nextFiles);
      },
      [onChange],
    );

    const handleUpload = useCallback(
      async (selectedFiles: File[]) => {
        if (!selectedFiles.length) return;

        // If a replace operation is in progress, remove the old file first
        if (replaceFileIdRef.current !== null) {
          const fileIdToReplace = replaceFileIdRef.current;
          replaceFileIdRef.current = null;
          filesRef.current = filesRef.current.filter(
            (f) => f.id !== fileIdToReplace,
          );
        }

        // Check maxFiles limit
        if (maxFiles !== undefined) {
          const currentCount = filesRef.current.length;
          const selectedCount = selectedFiles.length;
          const totalCount = currentCount + selectedCount;

          if (totalCount > maxFiles) {
            const allowedCount = Math.max(0, maxFiles - currentCount);

            if (allowedCount <= 0) {
              // No more files can be added
              onMaxFilesExceeded?.(maxFiles, selectedCount, currentCount);
              return;
            }

            // Only take the allowed number of files
            selectedFiles = selectedFiles.slice(0, allowedCount);
            onMaxFilesExceeded?.(maxFiles, selectedCount, currentCount);
          }
        }

        // Create temporary files with unique temporary IDs
        // The actual IDs will be provided by the backend via onUpload return value
        // Use a batch identifier + index to create unique IDs for this batch of files
        const batchId = Date.now();
        const tempFiles: UploadFile[] = selectedFiles.map((file, index) => ({
          file,
          // Simple ID: batch timestamp + index ensures uniqueness within this upload batch
          // This is sufficient because:
          // 1. Each upload batch has a unique timestamp
          // 2. Index ensures uniqueness within the batch
          // 3. Backend will replace this with real ID after upload completes
          id: `temp-${batchId}-${index}`,
          status: 'loading' as UploadItemStatus,
          progress: 0,
        }));

        const updatedFiles = [...filesRef.current, ...tempFiles];
        emitChange(updatedFiles);

        if (onUpload) {
          // Map to track temporary ID to file index
          const tempIdToIndex = new Map<string, number>();
          tempFiles.forEach((tempFile, index) => {
            tempIdToIndex.set(tempFile.id, index);
          });

          const setProgress = (fileIndex: number, progress: number) => {
            const targetFile = tempFiles[fileIndex];
            if (!targetFile) return;

            const nextFiles = filesRef.current.map((file) =>
              file.id === targetFile.id ? { ...file, progress } : file,
            );

            emitChange(nextFiles);
          };

          try {
            const result = await Promise.resolve(
              onUpload(selectedFiles, (fileIndex, progress) =>
                setProgress(fileIndex, progress),
              ),
            );

            // Check if result is an array (new API) or void (old API for backward compatibility)
            if (Array.isArray(result) && result.length > 0) {
              // Check if it's UploadFile[] (full objects) or { id: string }[] (just IDs)
              const firstItem = result[0];
              const isFullUploadFile =
                'file' in firstItem && 'status' in firstItem;

              if (isFullUploadFile) {
                // Full UploadFile[] API: backend returns complete file objects
                const backendFiles = result as UploadFile[];

                // Update files with backend-provided IDs and status
                // Match by index: backendFiles[i] corresponds to selectedFiles[i]
                const nextFiles = filesRef.current.map((file) => {
                  const tempIndex = tempIdToIndex.get(file.id);

                  // If this is a temp file and we have a corresponding backend file
                  if (
                    tempIndex !== undefined &&
                    tempIndex < backendFiles.length
                  ) {
                    const backendFile = backendFiles[tempIndex];
                    // Replace temporary file with backend file (includes real ID and status)
                    // Apply default error message and icon if status is error and not provided
                    if (backendFile.status === 'error') {
                      return {
                        ...backendFile,
                        errorMessage:
                          backendFile.errorMessage ??
                          errorMessage ??
                          defaultUploadPictureCardErrorMessage,
                        errorIcon:
                          backendFile.errorIcon ?? defaultErrorIconElement,
                      };
                    }
                    return backendFile;
                  }

                  return file;
                });

                emitChange(nextFiles);
              } else {
                // Simple { id: string }[] API: backend returns just IDs
                const backendIds = result as Array<{ id: string }>;

                // Update files with backend-provided IDs, set status to 'done'
                const nextFiles = filesRef.current.map((file) => {
                  const tempIndex = tempIdToIndex.get(file.id);

                  // If this is a temp file and we have a corresponding backend ID
                  if (
                    tempIndex !== undefined &&
                    tempIndex < backendIds.length
                  ) {
                    const backendId = backendIds[tempIndex];
                    // Replace temporary ID with backend ID, set status to 'done'
                    return {
                      ...file,
                      id: backendId.id,
                      status: 'done' as UploadItemStatus,
                      progress: 100,
                    };
                  }

                  return file;
                });

                emitChange(nextFiles);
              }
            } else {
              // Old API: backward compatibility - no return value, assume success
              const nextFiles = filesRef.current.map((file) =>
                tempFiles.some((tf) => tf.id === file.id)
                  ? {
                    ...file,
                    status: 'done' as UploadItemStatus,
                    progress: 100,
                  }
                  : file,
              );

              emitChange(nextFiles);
            }
          } catch (error) {
            console.error('Upload failed:', error);
            // Update all temp files to error status with default error message and icon
            const nextFiles = filesRef.current.map((file) => {
              if (tempFiles.some((tf) => tf.id === file.id)) {
                return {
                  ...file,
                  status: 'error' as UploadItemStatus,
                  errorMessage:
                    file.errorMessage ??
                    errorMessage ??
                    defaultUploadPictureCardErrorMessage,
                  errorIcon: file.errorIcon ?? defaultErrorIconElement,
                };
              }
              return file;
            });

            emitChange(nextFiles);
          }
        } else {
          // No onUpload handler - mark as done immediately
          const nextFiles = filesRef.current.map((file) =>
            tempFiles.some((tf) => tf.id === file.id)
              ? { ...file, status: 'done' as UploadItemStatus, progress: 100 }
              : file,
          );

          emitChange(nextFiles);
        }
      },
      [
        emitChange,
        maxFiles,
        onMaxFilesExceeded,
        onUpload,
        errorMessage,
        defaultErrorIconElement,
      ],
    );

    const handleDelete = useCallback(
      (fileId: string) => {
        const file = findFileById(fileId);

        if (!file) return;

        const updated = filesRef.current.filter((f) => f.id !== fileId);

        emitChange(updated);
        if (file.file) {
          onDelete?.(fileId, file.file);
        }
      },
      [emitChange, findFileById, onDelete],
    );

    const handleReload = useCallback(
      (fileId: string) => {
        const file = findFileById(fileId);

        if (!file) return;

        const updated = filesRef.current.map((f) =>
          f.id === fileId
            ? { ...f, status: 'loading' as UploadItemStatus, progress: 0 }
            : f,
        );

        emitChange(updated);
        if (file.file) {
          onReload?.(fileId, file.file);
        }
      },
      [emitChange, findFileById, onReload],
    );

    const handleDownload = useCallback(
      (fileId: string) => {
        const file = findFileById(fileId);
        if (file && file.file) {
          onDownload?.(fileId, file.file);
        }
      },
      [findFileById, onDownload],
    );

    const handleZoomIn = useCallback(
      (fileId: string) => {
        const file = findFileById(fileId);
        if (file && file.file) {
          onZoomIn?.(fileId, file.file);
        }
      },
      [findFileById, onZoomIn],
    );

    const { imageFiles, nonImageFiles } = useMemo(() => {
      const images: UploadFile[] = [];
      const nonImages: UploadFile[] = [];

      files.forEach((file) => {
        // Determine if file is an image using shared utility
        const isImage = isImageFile(file.file, file.url);

        if (isImage) {
          images.push(file);
        } else {
          nonImages.push(file);
        }
      });

      return { imageFiles: images, nonImageFiles: nonImages };
    }, [files]);

    const uploaderConfig = useMemo(() => {
      const config: Record<UploadMode, UploaderProps> = {
        list: {
          mode: 'dropzone',
          type: 'base',
        },
        'button-list': {
          type: 'button',
        },
        cards: {
          mode: 'basic',
          type: 'base',
        },
        'card-wall': {
          mode: 'basic',
          type: 'base',
        },
      };

      return config[mode];
    }, [mode]);

    const topUploaderConfig = useMemo(() => {
      if (mode === 'card-wall') {
        return {
          mode: 'dropzone' as const,
          type: 'base' as const,
        };
      }
      return null;
    }, [mode]);

    const shouldUsePictureCard = useMemo(() => {
      return /cards|card-wall/.test(mode);
    }, [mode]);

    const isSingleFileCardMode = shouldUsePictureCard && maxFiles === 1;

    const renderUploadItem = useCallback(
      (uploadFile: UploadFile) => {
        // Skip rendering if neither file nor url is provided
        if (!uploadFile.file && !uploadFile.url) {
          return null;
        }

        // Determine if it's an image using shared utility
        const isImage = isImageFile(uploadFile.file, uploadFile.url);

        // For images, use 'thumbnail' to show image preview; for non-images, use 'icon' to show file icon
        const itemType: UploadItemType | undefined = isImage
          ? 'thumbnail'
          : 'icon';

        return (
          <UploadItem
            key={uploadFile.id}
            file={uploadFile.file}
            url={uploadFile.url}
            id={uploadFile.id}
            status={uploadFile.status}
            size={size}
            type={itemType}
            showFileSize={showFileSize}
            disabled={disabled}
            onDelete={() => handleDelete(uploadFile.id)}
            onDownload={() => handleDownload(uploadFile.id)}
            onReload={() => handleReload(uploadFile.id)}
          />
        );
      },
      [
        size,
        showFileSize,
        disabled,
        handleDelete,
        handleDownload,
        handleReload,
      ],
    );

    const uploaderElement = (
      <Uploader
        accept={accept}
        disabled={effectiveDisabled}
        id={id}
        name={name}
        multiple={multiple}
        label={uploaderLabel}
        icon={uploaderIcon}
        inputRef={inputRef}
        inputProps={inputProps}
        hints={hints}
        onUpload={handleUpload}
        {...uploaderConfig}
      />
    );

    const topUploaderElement = topUploaderConfig ? (
      <Uploader
        accept={accept}
        disabled={effectiveDisabled}
        id={id ? `${id}-top` : undefined}
        name={name}
        multiple={multiple}
        label={uploaderLabel}
        icon={uploaderIcon}
        inputRef={inputRef}
        inputProps={inputProps}
        hints={hints}
        onUpload={handleUpload}
        {...topUploaderConfig}
      />
    ) : null;

    // When a top uploader exists (card-wall mode), the inline card uploader is not needed.
    const inlineCardUploaderElement = topUploaderElement ? null : uploaderElement;

    const hintsElement = useMemo(() => {
      if (
        !hints ||
        hints.length === 0 ||
        mode === 'list' ||
        mode === 'card-wall'
      )
        return null;

      const hintsClassName =
        mode === 'cards' ? classes.fillWidthHints : classes.hints;

      return (
        <ul className={hintsClassName}>
          {hints.map((hint) => (
            <li key={hint.label} className={classes.hint(hint.type || 'info')}>
              <Icon
                icon={
                  hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon
                }
                color={hint.type === 'info' ? 'info' : 'error'}
                size={14}
              />
              {hint.label}
            </li>
          ))}
        </ul>
      );
    }, [hints, mode]);

    return (
      <div
        ref={ref}
        className={cx(
          classes.host,
          className,
          mode === 'cards' && classes.hostCards,
        )}
        {...rest}
      >
        {topUploaderElement}
        {!shouldUsePictureCard && (
          <div className={classes.uploadButtonList}>
            {uploaderElement}
            {mode === 'button-list' && hintsElement}
          </div>
        )}
        <div
          className={cx(
            classes.uploadList,
            shouldUsePictureCard && classes.uploadListCards,
          )}
        >
          {shouldUsePictureCard && (
            <>
              {imageFiles.map((uploadFile) => (
                <UploadPictureCard
                  key={uploadFile.id}
                  file={uploadFile.file}
                  url={uploadFile.url}
                  id={uploadFile.id}
                  status={uploadFile.status}
                  size={size}
                  disabled={disabled}
                  errorMessage={uploadFile.errorMessage}
                  onDelete={() => handleDelete(uploadFile.id)}
                  onReload={() => handleReload(uploadFile.id)}
                  {...(!isSingleFileCardMode && {
                    onDownload: () => handleDownload(uploadFile.id),
                    onZoomIn: () => handleZoomIn(uploadFile.id),
                  })}
                  {...(isSingleFileCardMode && {
                    onReplace: (e) => {
                      e.stopPropagation();
                      replaceFileIdRef.current = uploadFile.id;
                      replaceInputRef.current?.click();
                    },
                  })}
                />
              ))}
              {!isSingleFileCardMode && inlineCardUploaderElement}
              {isSingleFileCardMode &&
                imageFiles.length === 0 &&
                inlineCardUploaderElement}
              {isSingleFileCardMode && (
                <input
                  ref={replaceInputRef}
                  accept={accept}
                  style={{ display: 'none' }}
                  type="file"
                  onChange={(e) => {
                    const selectedFiles = Array.from(e.target.files ?? []);
                    e.target.value = '';
                    if (selectedFiles.length) handleUpload(selectedFiles);
                  }}
                />
              )}
            </>
          )}
          {nonImageFiles.length > 0 && nonImageFiles.map(renderUploadItem)}
          {!shouldUsePictureCard &&
            imageFiles.length > 0 &&
            imageFiles.map(renderUploadItem)}
        </div>
        {mode === 'cards' && hintsElement}
      </div>
    );
  },
);

export default Upload;
