// packages/vue/upload/upload-picture-card.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import type { CSSProperties } from 'vue';
import { uploadPictureCardClasses as classes } from '@mezzanine-ui/core/upload';
import {
  DownloadIcon,
  FileIcon,
  ImageIcon,
  ResetIcon,
  TrashIcon,
  ZoomInIcon,
} from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { useHasListener } from '../_internal/use-has-listener';
import MznButton from '../button/button.vue';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTypography from '../typography/typography.vue';
import { isImageFile } from './upload-utils';
import type {
  UploadPictureCardAriaLabels,
  UploadPictureCardProps,
} from './upload-picture-card.types';

/**
 * 圖片上傳的卡片式預覽。
 *
 * 圖片以 blob 或網址顯示，非圖片顯示檔名。`status` 決定右上角的操作：上傳中是
 * 取消加轉圈、完成是放大／下載／刪除、錯誤是重試加刪除。`readable` 讓卡片變成
 * 純展示；有人監聽 `replace` 且已完成時，整張卡片變成重新選檔的觸發區。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznUploadPictureCard } from '@mezzanine-ui/vue/upload';
 * <\/script>
 *
 * <template>
 *   <MznUploadPictureCard :file="file" status="done" @delete="onDelete" />
 * </template>
 * ```
 *
 * @see MznUpload 管理整組卡片的元件
 */
const props = withDefaults(defineProps<UploadPictureCardProps>(), {
  ariaLabels: undefined,
  disabled: false,
  errorIcon: undefined,
  errorMessage: undefined,
  file: undefined,
  id: undefined,
  imageFit: 'cover',
  readable: false,
  size: 'main',
  status: 'loading',
  url: undefined,
});

const emit = defineEmits<{
  /** Fired when the delete action is used. */
  delete: [event: MouseEvent];
  /** Fired when the download action is used. */
  download: [event: MouseEvent];
  /** Fired when the reload action is used. */
  reload: [event: MouseEvent];
  /** Fired when the card is clicked while it stands for a replacement. */
  replace: [event: MouseEvent];
  /** Fired when the zoom-in action is used. */
  zoomIn: [event: MouseEvent];
}>();

const hasListener = useHasListener();

const DEFAULT_ARIA_LABELS: Required<UploadPictureCardAriaLabels> = {
  cancelUpload: 'Cancel upload',
  clickToReplace: 'Click to Replace',
  delete: 'Delete file',
  download: 'Download file',
  reload: 'Retry upload',
  uploading: 'Uploading',
  zoomIn: 'Zoom in image',
};

const labels = computed(
  (): Required<UploadPictureCardAriaLabels> => ({
    ...DEFAULT_ARIA_LABELS,
    ...props.ariaLabels,
  }),
);

const isImage = computed((): boolean => isImageFile(props.file, props.url));

const fileName = computed((): string => {
  if (props.file?.name && !props.url) return props.file.name;

  if (props.url) {
    try {
      const url = new URL(props.url);

      return url.pathname.split('/').pop() || '';
    } catch {
      const urlWithoutQuery = props.url.split('?')[0].split('#')[0];

      return urlWithoutQuery.split('/').pop() || '';
    }
  }

  return '';
});

const imageUrl = ref('');

let objectUrl: string | null = null;

function revokeObjectUrl(): void {
  if (objectUrl) {
    URL.revokeObjectURL(objectUrl);
    objectUrl = null;
  }
}

watch(
  [
    (): File | undefined => props.file,
    (): string | undefined => props.url,
    isImage,
  ],
  ([file, url, image]) => {
    revokeObjectUrl();

    if (url && image) {
      imageUrl.value = url;

      return;
    }

    if (file && image) {
      try {
        objectUrl = URL.createObjectURL(file);
        imageUrl.value = objectUrl;
      } catch (error) {
        console.error('Failed to create object URL for image:', error);
        imageUrl.value = '';
      }

      return;
    }

    imageUrl.value = '';
  },
  { immediate: true },
);

onBeforeUnmount(revokeObjectUrl);

watch(
  [(): File | undefined => props.file, (): string | undefined => props.url],
  ([file, url]) => {
    if (!file && !url) {
      console.warn(
        'UploadPictureCard: Both `file` and `url` props are missing. At least one should be provided to display the upload picture card.',
      );
    }
  },
  { immediate: true },
);

const errorIconContent = computed((): IconDefinition => {
  if (props.errorIcon) return props.errorIcon;

  return isImage.value ? ImageIcon : FileIcon;
});

const errorMessageContent = computed((): string => {
  if (props.errorMessage) return props.errorMessage;

  return fileName.value ? fileName.value : 'Upload error';
});

const unsupported = computed(
  (): boolean => !isImage.value && props.size === 'minor',
);

watch(
  unsupported,
  (value) => {
    if (value) {
      console.warn(
        'UploadPictureCard: minor size is not supported for non-image files',
      );
    }
  },
  { immediate: true },
);

const canZoomIn = computed((): boolean => hasListener('zoomIn'));
const canDownload = computed((): boolean => hasListener('download'));
const canReplace = computed((): boolean => hasListener('replace'));

const isReplaceTrigger = computed(
  (): boolean => !props.readable && canReplace.value && props.status === 'done',
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    classes.size(props.size),
    props.disabled && classes.disabled,
    props.readable && classes.readable,
    isReplaceTrigger.value && classes.replaceMode,
  ),
);

const imageStyle = computed(
  (): CSSProperties => ({
    objectFit: props.imageFit,
    objectPosition: 'center',
  }),
);

function onHostClick(event: MouseEvent): void {
  if (isReplaceTrigger.value) emit('replace', event);
}

function onHostKeydown(event: KeyboardEvent): void {
  if (!isReplaceTrigger.value) return;

  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    (event.currentTarget as HTMLElement).click();
  }
}

function onDelete(event: MouseEvent): void {
  event.stopPropagation();
  emit('delete', event);
}

function onDownload(event: MouseEvent): void {
  event.stopPropagation();
  emit('download', event);
}

function onZoomIn(event: MouseEvent): void {
  event.stopPropagation();
  emit('zoomIn', event);
}
</script>

<template>
  <div
    v-if="!unsupported"
    :aria-disabled="disabled"
    :class="hostClasses"
    role="group"
    :tabindex="disabled || readable ? -1 : 0"
    @click="onHostClick"
    @keydown="onHostKeydown"
  >
    <div :class="classes.container">
      <img
        v-if="isImage && imageUrl && status !== 'error'"
        :alt="fileName"
        :src="imageUrl"
        :style="imageStyle"
      />
      <div
        v-if="status === 'done' && size !== 'minor' && !isImage"
        :class="classes.content"
      >
        <MznIcon color="brand" :icon="FileIcon" :size="16" />
        <MznTypography :class="classes.name" ellipsis>
          {{ fileName }}
        </MznTypography>
      </div>
      <div
        v-if="status === 'error' && size !== 'minor'"
        aria-live="polite"
        :class="classes.errorMessage"
        role="alert"
      >
        <MznIcon color="error" :icon="errorIconContent" :size="16" />
        <MznTypography :class="classes.errorMessageText">
          {{ errorMessageContent }}
        </MznTypography>
      </div>
      <div :class="[classes.actions, classes.actionsStatus(status)]">
        <template v-if="status === 'loading' && size !== 'minor' && !readable">
          <MznClearActions
            :aria-label="labels.cancelUpload"
            :class="classes.clearActionsIcon"
            type="embedded"
            variant="contrast"
            @click="emit('delete', $event)"
          />
          <div :aria-label="labels.uploading" :class="classes.loadingIcon">
            <MznSpin loading size="sub" />
          </div>
        </template>
        <template v-if="status === 'done' && size !== 'minor' && !readable">
          <div :class="classes.tools">
            <div :class="classes.toolsContent">
              <MznButton
                v-if="canZoomIn"
                :aria-label="labels.zoomIn"
                :icon="ZoomInIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onZoomIn"
              />
              <MznButton
                v-if="canDownload"
                :aria-label="labels.download"
                :icon="DownloadIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onDownload"
              />
              <MznButton
                :aria-label="labels.delete"
                :icon="TrashIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="onDelete"
              />
            </div>
          </div>
          <span v-if="canReplace" :class="classes.replaceLabel">
            {{ labels.clickToReplace }}
          </span>
        </template>
        <template v-if="status === 'error' && size !== 'minor' && !readable">
          <div :class="classes.tools">
            <div :class="classes.toolsContent">
              <MznButton
                :aria-label="labels.reload"
                :icon="ResetIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="emit('reload', $event)"
              />
              <MznButton
                :aria-label="labels.delete"
                :icon="TrashIcon"
                icon-type="icon-only"
                size="minor"
                variant="base-secondary"
                @click="emit('delete', $event)"
              />
            </div>
          </div>
        </template>
        <MznIcon
          v-if="size === 'minor' && !readable"
          color="fixed-light"
          :icon="ZoomInIcon"
          :size="24"
        />
      </div>
    </div>
  </div>
</template>

// packages/react/src/Upload/UploadPictureCard.tsx
'use client';

import {
  forwardRef,
  MouseEventHandler,
  useEffect,
  useMemo,
  useState,
} from 'react';

import {
  uploadPictureCardClasses as classes,
  UploadItemStatus,
  UploadPictureCardImageFit,
  UploadPictureCardSize,
} from '@mezzanine-ui/core/upload';
import type { IconDefinition } from '@mezzanine-ui/icons';

import {
  DownloadIcon,
  FileIcon,
  ImageIcon,
  ResetIcon,
  TrashIcon,
  ZoomInIcon,
} from '@mezzanine-ui/icons';

import Button from '../Button';
import ClearActions from '../ClearActions';
import Icon from '../Icon';
import Spin from '../Spin';
import Typography from '../Typography';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { isImageFile } from './upload-utils';

export interface UploadPictureCardAriaLabels {
  /**
   * Aria label for cancel upload button.
   * @default 'Cancel upload'
   */
  cancelUpload?: string;
  /**
   * Aria label for the click-to-replace overlay label.
   * @default 'Click to Replace'
   */
  clickToReplace?: string;
  /**
   * Aria label for delete button.
   * @default 'Delete file'
   */
  delete?: string;
  /**
   * Aria label for download button.
   * @default 'Download file'
   */
  download?: string;
  /**
   * Aria label for reload/retry button.
   * @default 'Retry upload'
   */
  reload?: string;
  /**
   * Aria label for uploading status.
   * @default 'Uploading'
   */
  uploading?: string;
  /**
   * Aria label for zoom in button.
   * @default 'Zoom in image'
   */
  zoomIn?: string;
}

export interface UploadPictureCardProps
  extends NativeElementPropsWithoutKeyAndRef<'div'> {
  /**
   * Aria labels for accessibility. Allows customization for internationalization.
   */
  ariaLabels?: UploadPictureCardAriaLabels;
  /**
   * The file to display.
   * Required when displaying local files (before upload).
   * Optional when `url` is provided for already uploaded files.
   */
  file?: File;
  /**
   * The URL of the uploaded file.
   * When provided, this will be used instead of creating a blob URL from `file`.
   * Useful for displaying files that have already been uploaded to the server.
   *
   * @note If only `url` is provided (without `file`), the file type will be inferred
   * from the URL extension. For accurate type detection, provide `file` when available.
   */
  url?: string;
  /**
   * The id of the file id to identify the file.
   */
  id?: string;
  /**
   * The status of the upload picture card.
   * @default 'loading'
   */
  status?: UploadItemStatus;
  /**
   * The size of the upload picture card.
   * @default 'main'
   */
  size?: UploadPictureCardSize;
  /**
   * The image fit of the upload picture card.
   * @default 'cover'
   */
  imageFit?: UploadPictureCardImageFit;
  /**
   * Whether the upload picture card is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Error message to display when status is 'error'.
   */
  errorMessage?: string;
  /**
   * Error icon to display when status is 'error'.
   */
  errorIcon?: IconDefinition;
  /**
   * Whether the upload picture card is readable.
   * @default false
   */
  readable?: boolean;
  /**
   * When delete icon is clicked, this callback will be fired.
   */
  onDelete?: MouseEventHandler;
  /**
   * When download icon is clicked, this callback will be fired.
   */
  onDownload?: MouseEventHandler;
  /**
   * When reload icon is clicked, this callback will be fired.
   */
  onReload?: MouseEventHandler;
  /**
   * When provided, the card becomes a replacement trigger in done status.
   * On hover, shows a "Click to Replace" overlay label. Fired when the card body is clicked.
   */
  onReplace?: MouseEventHandler;
  /**
   * When zoom in icon is clicked, this callback will be fired.
   */
  onZoomIn?: MouseEventHandler;
}

/**
 * The react component for `mezzanine` upload picture card.
 */
const UploadPictureCard = forwardRef<HTMLDivElement, UploadPictureCardProps>(
  function UploadPictureCard(props, ref) {
    const {
      ariaLabels,
      className,
      file,
      url,
      status = 'loading',
      imageFit = 'cover',
      size = 'main',
      disabled = false,
      errorMessage,
      errorIcon,
      readable = false,
      onDelete,
      onDownload,
      onReload,
      onReplace,
      onZoomIn,
      ...rest
    } = props;

    const defaultAriaLabels: Required<UploadPictureCardAriaLabels> = {
      cancelUpload: 'Cancel upload',
      clickToReplace: 'Click to Replace',
      delete: 'Delete file',
      download: 'Download file',
      reload: 'Retry upload',
      uploading: 'Uploading',
      zoomIn: 'Zoom in image',
    };

    const labels = { ...defaultAriaLabels, ...ariaLabels };

    const isImage = useMemo(() => {
      return isImageFile(file, url);
    }, [file, url]);

    const fileName = useMemo(() => {
      if (props.file?.name && !props.url) return props.file.name;
      if (props.url) {
        try {
          const url = new URL(props.url);
          const pathname = url.pathname;
          const filename = pathname.split('/').pop() || '';
          return filename;
        } catch {
          const urlWithoutQuery = props.url.split('?')[0].split('#')[0];
          return urlWithoutQuery.split('/').pop() || '';
        }
      }
      return '';
    }, [props.file?.name, props.url]);

    const [imageUrl, setImageUrl] = useState<string>('');

    const errorIconContent = useMemo(() => {
      if (errorIcon) {
        return errorIcon;
      }

      return isImage ? ImageIcon : FileIcon;
    }, [isImage, errorIcon]);

    const errorMessageContent = useMemo(() => {
      if (errorMessage) {
        return errorMessage;
      }

      return fileName ? fileName : 'Upload error';
    }, [fileName, errorMessage]);

    // Warn if both file and url are missing
    useEffect(() => {
      if (!file && !url) {
        console.warn(
          'UploadPictureCard: Both `file` and `url` props are missing. At least one should be provided to display the upload picture card.',
        );
      }
    }, [file, url]);

    useEffect(() => {
      if (url && isImage) {
        setImageUrl(url);
        return undefined;
      }

      if (file && isImage) {
        try {
          const blobUrl = URL.createObjectURL(file);
          setImageUrl(blobUrl);

          return () => {
            URL.revokeObjectURL(blobUrl);
          };
        } catch (error) {
          console.error('Failed to create object URL for image:', error);
          setImageUrl('');
        }
      } else {
        setImageUrl('');
      }

      return undefined;
    }, [file, url, isImage]);

    if (!isImage && size === 'minor') {
      console.warn(
        'UploadPictureCard: minor size is not supported for non-image files',
      );

      return null;
    }

    return (
      <div
        aria-disabled={disabled}
        className={cx(
          classes.host,
          classes.size(size),
          disabled && classes.disabled,
          readable && classes.readable,
          !readable && onReplace && status === 'done' && classes.replaceMode,
          className,
        )}
        onClick={
          !readable && onReplace && status === 'done' ? onReplace : undefined
        }
        onKeyDown={
          !readable && onReplace && status === 'done'
            ? (e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                e.currentTarget.click();
              }
            }
            : undefined
        }
        ref={ref}
        role="group"
        tabIndex={disabled || readable ? -1 : 0}
        {...rest}
      >
        <div className={classes.container}>
          {isImage && imageUrl && status !== 'error' && (
            <img
              alt={fileName}
              src={imageUrl}
              style={{
                objectFit: imageFit,
                objectPosition: 'center',
              }}
            />
          )}
          {status === 'done' && size !== 'minor' && !isImage && (
            <div className={classes.content}>
              <Icon icon={FileIcon} color="brand" size={16} />
              <Typography className={classes.name} ellipsis>
                {fileName}
              </Typography>
            </div>
          )}
          {status === 'error' && size !== 'minor' && (
            <div
              className={classes.errorMessage}
              role="alert"
              aria-live="polite"
            >
              <Icon icon={errorIconContent} color="error" size={16} />
              <Typography className={classes.errorMessageText}>
                {errorMessageContent}
              </Typography>
            </div>
          )}
          <div className={cx(classes.actions, classes.actionsStatus(status))}>
            {status === 'loading' && size !== 'minor' && !readable && (
              <>
                <ClearActions
                  type="embedded"
                  variant="contrast"
                  onClick={onDelete}
                  className={classes.clearActionsIcon}
                  aria-label={labels.cancelUpload}
                />
                <div
                  className={classes.loadingIcon}
                  aria-label={labels.uploading}
                >
                  <Spin loading size="sub" />
                </div>
              </>
            )}
            {status === 'done' && size !== 'minor' && !readable && (
              <>
                <div className={classes.tools}>
                  <div className={classes.toolsContent}>
                    {onZoomIn && (
                      <Button
                        variant="base-secondary"
                        size="minor"
                        icon={ZoomInIcon}
                        iconType="icon-only"
                        onClick={onZoomIn}
                        aria-label={labels.zoomIn}
                      />
                    )}
                    {onDownload && (
                      <Button
                        variant="base-secondary"
                        size="minor"
                        iconType="icon-only"
                        icon={DownloadIcon}
                        onClick={onDownload}
                        aria-label={labels.download}
                      />
                    )}
                    <Button
                      variant="base-secondary"
                      size="minor"
                      iconType="icon-only"
                      icon={TrashIcon}
                      onClick={onDelete}
                      aria-label={labels.delete}
                    />
                  </div>
                </div>
                {onReplace && (
                  <span className={classes.replaceLabel}>
                    {labels.clickToReplace}
                  </span>
                )}
              </>
            )}
            {status === 'error' && size !== 'minor' && !readable && (
              <>
                <div className={classes.tools}>
                  <div className={classes.toolsContent}>
                    <Button
                      variant="base-secondary"
                      size="minor"
                      iconType="icon-only"
                      icon={ResetIcon}
                      onClick={onReload}
                      aria-label={labels.reload}
                    />
                    <Button
                      variant="base-secondary"
                      size="minor"
                      iconType="icon-only"
                      icon={TrashIcon}
                      onClick={onDelete}
                      aria-label={labels.delete}
                    />
                  </div>
                </div>
              </>
            )}
            {size === 'minor' && !readable && (
              <Icon icon={ZoomInIcon} color="fixed-light" size={24} />
            )}
          </div>
        </div>
      </div>
    );
  },
);

export default UploadPictureCard;
