// packages/vue/upload/uploader.vue
<script setup lang="ts">
import { computed, ref, useId } from 'vue';
import type { FunctionalComponent } from 'vue';
import { uploaderClasses as classes } from '@mezzanine-ui/core/upload';
import {
  DangerousFilledIcon,
  InfoFilledIcon,
  UploadIcon,
} from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import MznIcon from '../icon/icon.vue';
import MznTypography from '../typography/typography.vue';
import type { UploaderProps } from './uploader.types';

/**
 * 上傳觸發區：一個包住 file input 的 label。
 *
 * `type="base"` 是可拖放的區塊，`type="button"` 是一顆按鈕；`mode="dropzone"`
 * 時區塊會填滿寬度並顯示提示文字。拖曳進來的檔案透過 `upload` 送出。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznUploader } from '@mezzanine-ui/vue/upload';
 * <\/script>
 *
 * <template>
 *   <MznUploader mode="dropzone" type="base" @upload="onUpload" />
 * </template>
 * ```
 *
 * @see MznUpload 把觸發區與清單組合起來的元件
 */
const props = withDefaults(defineProps<UploaderProps>(), {
  accept: undefined,
  disabled: false,
  externalHints: undefined,
  hints: undefined,
  icon: undefined,
  id: undefined,
  inputProps: undefined,
  label: undefined,
  mode: 'basic',
  multiple: false,
  name: undefined,
  type: undefined,
});

const emit = defineEmits<{
  /** Fired by the input's own change event. */
  change: [event: Event];
  /** Fired after the user selected files. */
  upload: [files: File[]];
}>();

/** React spreads the rest onto the label, and the hints are a second root. */
defineOptions({ inheritAttrs: false });

/** The input element, exposed so a consumer can drive the file dialog. */
const input = ref<HTMLInputElement | null>(null);

defineExpose({ input });

const generatedId = useId();

const restInputProps = computed(() => {
  const { id: _id, name: _name, ...rest } = props.inputProps ?? {};

  return rest;
});

const inputId = computed(
  (): string =>
    props.id ?? (props.inputProps?.id as string | undefined) ?? generatedId,
);

const resolvedName = computed(
  (): string =>
    props.name ??
    (props.inputProps?.name as string | undefined) ??
    inputId.value,
);

const isDropzone = computed((): boolean => props.mode === 'dropzone');
const isDragging = ref(false);

function handleChange(event: Event): void {
  emit('change', event);

  const target = event.target as HTMLInputElement;
  const { files: fileList } = target;

  if (fileList) {
    const files: File[] = [];

    for (let i = 0; i < fileList.length; i += 1) {
      files.push(fileList[i]);
    }

    emit('upload', files);
  }

  // Reset input value to allow selecting the same file again
  (event.currentTarget as HTMLInputElement).value = '';
}

const dragDisabled = computed(
  (): boolean => props.disabled || props.type === 'button',
);

function handleDragOver(event: DragEvent): void {
  if (dragDisabled.value) return;

  event.preventDefault();
  event.stopPropagation();
}

function handleDragEnter(event: DragEvent): void {
  if (dragDisabled.value) return;

  event.preventDefault();
  event.stopPropagation();
  isDragging.value = true;
}

function handleDragLeave(event: DragEvent): void {
  if (dragDisabled.value) return;

  // Only clear dragging state if leaving the label itself (not a child)
  const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
  const { clientX: x, clientY: y } = event;

  if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
    isDragging.value = false;
  }
}

function handleDrop(event: DragEvent): void {
  if (dragDisabled.value) return;

  event.preventDefault();
  event.stopPropagation();
  isDragging.value = false;

  const { dataTransfer } = event;

  if (dataTransfer?.files && dataTransfer.files.length > 0) {
    const files: File[] = [];

    for (let i = 0; i < dataTransfer.files.length; i += 1) {
      files.push(dataTransfer.files[i]);
    }

    emit('upload', files);
  }

  // The input's files cannot be set from a drop, so no change event follows;
  // a consumer that needs it has to listen for `upload`.
}

function handleClickToUpload(event: MouseEvent): void {
  event.preventDefault();
  event.stopPropagation();

  if (!props.disabled && input.value) input.value.click();
}

const uploadIcon = computed(() => props.icon?.upload ?? UploadIcon);

const uploadLabel = computed((): string => {
  if (props.label?.uploadLabel) return props.label.uploadLabel;

  return isDropzone.value ? 'Drag the file here or' : 'Upload';
});

const clickToUploadLabel = computed(
  (): string => props.label?.clickToUpload ?? 'Click to upload',
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    props.type && classes.type(props.type),
    props.type !== 'button' && isDropzone.value && classes.fillWidth,
    isDragging.value && classes.dragging,
    props.type !== 'button' && props.disabled && classes.disabled,
  ),
);

/**
 * React writes `{uploadLabel}{' '}` — two text nodes — before the highlighted
 * part, so the label is handed over as its parts.
 */
const LabelParts: FunctionalComponent<{ parts: string[] }> = (partProps) =>
  partProps.parts;
</script>

<template>
  <label
    v-bind="$attrs"
    :class="hostClasses"
    @dragenter="handleDragEnter"
    @dragleave="handleDragLeave"
    @dragover="handleDragOver"
    @drop="handleDrop"
  >
    <div v-if="type === 'base' && isDropzone" :class="classes.uploadContent">
      <MznIcon :class="classes.uploadIcon" :icon="uploadIcon" />
      <MznTypography :class="classes.uploadLabel">
        <LabelParts v-if="uploadLabel" :parts="[uploadLabel, ' ']" />
        <span :class="classes.clickToUpload">{{ clickToUploadLabel }}</span>
      </MznTypography>
      <MznTypography
        v-for="(hint, index) in hints"
        :key="index"
        :class="classes.fillWidthHints"
      >
        {{ hint.label }}
      </MznTypography>
    </div>
    <div v-if="type === 'base' && !isDropzone" :class="classes.uploadContent">
      <MznIcon :class="classes.uploadIcon" :icon="uploadIcon" />
      <MznTypography :class="classes.uploadLabel">
        {{ uploadLabel }}
      </MznTypography>
    </div>
    <MznButton
      v-if="type === 'button'"
      :disabled="disabled"
      :icon="UploadIcon"
      icon-type="leading"
      @click="handleClickToUpload"
    >
      <MznTypography
        align="center"
        :class="classes.uploadButtonText"
        color="text-fixed-light"
        variant="button-highlight"
      >
        {{ uploadLabel }}
      </MznTypography>
    </MznButton>
    <input
      ref="input"
      v-bind="restInputProps"
      :accept="accept"
      :aria-disabled="disabled"
      :class="classes.input"
      :disabled="disabled"
      :id="inputId"
      :multiple="multiple"
      :name="resolvedName"
      type="file"
      @change="handleChange"
    />
  </label>
  <ul
    v-if="externalHints && externalHints.length > 0"
    :class="classes.externalHints"
  >
    <li
      v-for="hint in externalHints"
      :key="hint.label"
      :class="classes.externalHint(hint.type || 'info')"
    >
      <MznIcon
        :color="hint.type === 'info' ? 'info' : 'error'"
        :icon="hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon"
        :size="14"
      />
      {{ hint.label }}
    </li>
  </ul>
</template>

// packages/react/src/Upload/Uploader.tsx
'use client';

import {
  ChangeEventHandler,
  DragEventHandler,
  forwardRef,
  MouseEvent,
  ReactNode,
  Ref,
  useId,
  useMemo,
  useRef,
  useState
} from 'react';

import {
  uploaderClasses as classes,
  type UploaderHintType,
  type UploaderMode,
  type UploadPictureControl,
  type UploadType
} from '@mezzanine-ui/core/upload';
import { DangerousFilledIcon, InfoFilledIcon, type IconDefinition, UploadIcon as UploadIconIcon } from '@mezzanine-ui/icons';

import Button from '../Button';
import Icon from '../Icon';
import Typography from '../Typography';
import { composeRefs } from '../utils/composeRefs';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';

type UploaderInputElementProps = Omit<
  NativeElementPropsWithoutKeyAndRef<'input'>,
  | 'accept'
  | 'disabled'
  | 'multiple'
  | 'onChange'
  | 'type'
  | `aria-${'disabled'}`
> & {
  /**
   * The id attribute can be provided via inputProps, but it's recommended to use the `id` prop directly.
   * If both are provided, the `id` prop takes precedence.
   */
  id?: string;
  /**
   * The name attribute can be provided via inputProps, but it's recommended to use the `name` prop directly.
   * If both are provided, the `name` prop takes precedence.
   */
  name?: string;
};

export interface UploaderHint {
  /**
   * The label text of the hint.
   */
  label: string;
  /**
   * The icon element of the hint.
   */
  type?: UploaderHintType;
}

export interface UploaderLabel {
  /**
   * Label text for upload state.
   */
  uploadLabel?: string;
  /**
   * Label text for uploading state.
   */
  uploadingLabel?: string;
  /**
   * Label text for success state.
   */
  success?: string;
  /**
   * Label text for error state.
   */
  error?: string;
  /**
   * Label text for "Click to upload" in `mode="dropzone"`.
   * @default 'Click to upload'
   */
  clickToUpload?: string;
}

export interface UploaderIcon {
  /**
   * Icon for upload action.
   */
  upload?: IconDefinition;
  /**
   * Icon for error state.
   */
  error?: ReactNode;
  /**
   * Icon for success state.
   */
  success?: ReactNode;
  /**
   * Icon for zoom action.
   */
  zoom?: ReactNode;
  /**
   * Icon for document.
   */
  document?: ReactNode;
  /**
   * Icon for download action.
   */
  download?: ReactNode;
  /**
   * Icon for reload action.
   */
  reload?: ReactNode;
  /**
   * Icon for delete action.
   */
  delete?: ReactNode;
}

export interface UploaderProps
  extends Omit<NativeElementPropsWithoutKeyAndRef<'label'>, 'onChange'> {
  /**
   * The accept attributes of native input element.
   * @example 'image/*', '.pdf,.doc,.docx'
   */
  accept?: string;
  /**
   * Provide `controllerRef` if you need detail data of file.
   */
  controllerRef?: Ref<UploadPictureControl | null>;
  /**
   * Whether the input is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Array of hints to display outside the uploader (below the label element).
   */
  externalHints?: UploaderHint[];
  /**
   * Array of hints to display with the upload component.
   */
  hints?: UploaderHint[];
  /**
   * Icon configuration for different actions and states.
   */
  icon?: UploaderIcon;
  /**
   * The id of input element.
   */
  id?: string;
  /**
   * Since at Mezzanine we use a host element to wrap our input, most derived props will be passed to the host element.
   * If you need direct control to the input element, use this prop to provide to it.
   */
  inputProps?: UploaderInputElementProps;
  /**
   * The react ref passed to input element.
   */
  inputRef?: React.Ref<HTMLInputElement>;
  /**
   * Label configuration for different states.
   */
  label?: UploaderLabel;
  /**
   * The name attribute of the input element.
   */
  name?: string;
  /**
   * The mode for upload component.
   * @default 'basic'
   * @example 'basic' | 'dropzone'
   */
  mode?: UploaderMode;
  /**
   * Whether can select multiple files to upload.
   * @default false
   */
  multiple?: boolean;
  /**
   * Invoked by input change event.
   */
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * Fired after user selected files.
   */
  onUpload?: (files: File[]) => void;
  /**
   * The type for upload component.
   * @default 'base'
   * @example 'base' | 'button'
   */
  type?: UploadType;
}

/**
 * The react component for `mezzanine` uploader.
 */
const Uploader = forwardRef<HTMLLabelElement, UploaderProps>(function Uploader(
  props,
  ref,
) {
  const {
    accept,
    className,
    controllerRef: _controllerRef,
    disabled = false,
    externalHints,
    id,
    hints,
    icon: iconConfig,
    inputProps,
    inputRef: inputRefProp,
    label: labelConfig,
    mode = 'basic',
    multiple = false,
    name,
    onChange: onChangeProp,
    onUpload,
    type,
    ...rest
  } = props;

  const {
    name: nameFromInputProps,
    id: idFromInputProps,
    ...restInputProps
  } = inputProps || {};

  // Generate unique id if not provided
  const generatedId = useId();
  const finalInputId = id ?? idFromInputProps ?? generatedId;

  const inputElementRef = useRef<HTMLInputElement | null>(null);
  const [isDragging, setIsDragging] = useState(false);

  const composedInputRef = useMemo(
    () => composeRefs([inputRefProp, inputElementRef]),
    [inputRefProp],
  );

  const resolvedName = name ?? nameFromInputProps ?? finalInputId;
  const isDropzone = mode === 'dropzone';

  const handleChange: ChangeEventHandler<HTMLInputElement> = (event) => {
    if (onChangeProp) {
      onChangeProp(event);
    }

    if (onUpload) {
      const { files: fileList } = event.target;

      if (fileList) {
        const files: File[] = [];

        for (let i = 0; i < fileList.length; i += 1) {
          files.push(fileList[i]);
        }

        onUpload(files);
      }
    }

    // Reset input value to allow selecting the same file again
    event.currentTarget.value = '';
  };

  const handleDragOver: DragEventHandler<HTMLLabelElement> = (event) => {
    if (disabled || type === 'button') {
      return;
    }

    event.preventDefault();
    event.stopPropagation();
  };

  const handleDragEnter: DragEventHandler<HTMLLabelElement> = (event) => {
    if (disabled || type === 'button') {
      return;
    }

    event.preventDefault();
    event.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave: DragEventHandler<HTMLLabelElement> = (event) => {
    if (disabled || type === 'button') {
      return;
    }

    // Only clear dragging state if leaving the label itself (not a child)
    const rect = event.currentTarget.getBoundingClientRect();
    const x = event.clientX;
    const y = event.clientY;

    if (
      x < rect.left ||
      x > rect.right ||
      y < rect.top ||
      y > rect.bottom
    ) {
      setIsDragging(false);
    }
  };

  const handleDrop: DragEventHandler<HTMLLabelElement> = (event) => {
    if (disabled || type === 'button') {
      return;
    }

    event.preventDefault();
    event.stopPropagation();

    setIsDragging(false);

    const { dataTransfer } = event;

    if (dataTransfer?.files && dataTransfer.files.length > 0) {
      const files: File[] = [];

      for (let i = 0; i < dataTransfer.files.length; i += 1) {
        files.push(dataTransfer.files[i]);
      }

      if (onUpload) {
        onUpload(files);
      }

      // Note: We cannot directly set input.files from drag & drop
      // The onChange event will not be triggered for drag & drop
      // If onChange is needed, it should be handled via onUpload callback
    }
  };

  const uploadIcon = useMemo(() => {
    const icon = iconConfig?.upload ?? UploadIconIcon;

    return <Icon className={classes.uploadIcon} icon={icon} />;
  }, [iconConfig]);

  const uploadLabel = labelConfig?.uploadLabel
    ? labelConfig?.uploadLabel
    : isDropzone
      ? 'Drag the file here or'
      : 'Upload';
  const clickToUploadLabel = labelConfig?.clickToUpload ?? 'Click to upload';

  const handleClickToUpload = (event: MouseEvent<HTMLElement>) => {
    event.preventDefault();
    event.stopPropagation();

    if (!disabled && inputElementRef.current) {
      inputElementRef.current.click();
    }
  };

  return (
    <>
      <label
        className={cx(
          classes.host,
          type && classes.type(type),
          type !== 'button' && isDropzone && classes.fillWidth,
          isDragging && classes.dragging,
          type !== 'button' && disabled && classes.disabled,
          className,
        )}
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        ref={ref}
        {...rest}
      >
        <>
          {
            type === 'base'
            && isDropzone
            && <div className={classes.uploadContent}>
              {uploadIcon}
              <Typography className={classes.uploadLabel}>
                {uploadLabel && <>{uploadLabel}{' '}</>}
                <span className={classes.clickToUpload}>
                  {clickToUploadLabel}
                </span>
              </Typography>
              {
                hints?.map((hint, index) => (
                  <Typography key={index} className={classes.fillWidthHints}>
                    {hint.label}
                  </Typography>
                ))
              }
            </div>
          }
          {
            type === 'base'
            && !isDropzone
            && <div className={classes.uploadContent}>
              {uploadIcon}
              <Typography className={classes.uploadLabel}>
                {uploadLabel}
              </Typography>
            </div>
          }
          {
            type === 'button'
            && (
              <Button disabled={disabled} onClick={handleClickToUpload}>
                {uploadIcon}
                <Typography>
                  {uploadLabel}
                </Typography>
              </Button>
            )
          }
          <input
            {...restInputProps}
            accept={accept}
            aria-disabled={disabled}
            className={classes.input}
            disabled={disabled}
            id={finalInputId}
            multiple={multiple}
            name={resolvedName}
            onChange={handleChange}
            ref={composedInputRef}
            type="file"
          />
        </>
      </label>
      {externalHints && externalHints.length > 0 && (
        <ul className={classes.externalHints}>
          {externalHints.map((hint) => (
            <li key={hint.label} className={classes.externalHint(hint.type || 'info')}>
              <Icon
                icon={hint.type === 'info' ? InfoFilledIcon : DangerousFilledIcon}
                color={hint.type === 'info' ? 'info' : 'error'}
                size={14}
              />
              {hint.label}
            </li>
          ))}
        </ul>
      )}
    </>
  );
});

export default Uploader;
