// packages/react/src/Alert/Alert.tsx
import {
  DetailedHTMLProps,
  HTMLAttributes,
  forwardRef,
  MouseEventHandler,
} from 'react';
import {
  alertClasses as classes,
  alertIcons,
  AlertSeverity,
} from '@mezzanine-ui/core/alert';
import {
  TimesIcon,
} from '@mezzanine-ui/icons';
import Icon from '../Icon';
import Typography from '../Typography';
import { cx } from '../utils/cx';

export interface AlertProps
  extends DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement> {
  /**
   * Close handler.
   */
  onClose?: MouseEventHandler;
  /**
   * The severity of alert.
   * @default success
   */
  severity?: AlertSeverity;
}

/**
 * The react component for `mezzanine` alert.
 * This component should always be full width of its parent.
 */
const Alert = forwardRef<HTMLDivElement, AlertProps>(function Alert(props, ref) {
  const {
    className,
    children,
    onClose,
    severity = 'success',
    ...rest
  } = props;

  const targetIcon = alertIcons[severity];

  return (
    <div
      ref={ref}
      className={cx(
        classes.host,
        classes.severity(severity),
        className,
      )}
      {...rest}
    >
      <Icon
        icon={targetIcon}
        color={severity}
        className={classes.icon}
      />
      <Typography
        component="p"
        variant="body1"
        className={classes.message}
      >
        {children}
      </Typography>
      <Icon
        icon={TimesIcon}
        onClick={onClose}
        className={classes.closeIcon}
        role="button"
      />
    </div>
  );
});

export default Alert;

// packages/ng/alert/alert.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import { TimesIcon } from '@mezzanine-ui/icons';
import {
  alertClasses as classes,
  alertIcons,
  AlertSeverity,
} from '@mezzanine-ui/core/alert';
import { HostBindingClass, HostBindingEnumClass } from '@mezzanine-ui/ng/cdk';

/**
 * The ng component for `mezzanine` alert.
 */
@Component({
  selector: 'mzn-alert',
  exportAs: 'mznAlert',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <i
      [mzn-icon]="severityIcon"
      [class]="classes.icon"
      [color]="severity"
    ></i>
    <p mzn-typography="body1" [class]="classes.message">
      <ng-content></ng-content>
    </p>
    <i
      [mzn-icon]="closeIcon"
      [class]="classes.closeIcon"
      (click)="onClose($event)"
      role="button"
    ></i>
  `,
})
export class MznAlertComponent {
  @HostBindingClass(classes.host)
  readonly bindHostClass = true;

  readonly classes = classes;

  closeIcon = TimesIcon;

  get severityIcon() {
    return alertIcons[this.severity];
  }

  /**
   * The severity of alert.
   * @default 'success'
   */
  @HostBindingEnumClass(classes.severity, [
    'success',
    'warning',
    'error',
  ])
  @Input()
  severity: AlertSeverity = 'success';

  /**
   * Fired on close icon clicked.
   */
  // eslint-disable-next-line @angular-eslint/no-output-native
  @Output()
  readonly close = new EventEmitter<MouseEvent>();

  onClose(event: MouseEvent) {
    this.close.emit(event);
  }
}
