// packages/vue/inline-message/inline-message.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import {
  inlineMessageClasses as classes,
  inlineMessageIcons,
} from '@mezzanine-ui/core/inline-message';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznIcon from '../icon/icon.vue';
import MznFade from '../transition/fade.vue';
import type { InlineMessageProps } from './inline-message.types';

/**
 * 行內提示訊息。
 *
 * 直接放進版面中呈現情境回饋，需要在關閉時反應請監聽 `close`。
 *
 * 根元素預設帶 `role="status"` 與 `aria-live="polite"`，其餘屬性會原樣轉發；
 * 兩個預設值都可覆寫 — 失敗訊息需要插播時請傳 `aria-live="assertive"`。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInlineMessage } from '@mezzanine-ui/vue/inline-message';
 * <\/script>
 *
 * <template>
 *   <MznInlineMessage content="已儲存草稿" severity="info" />
 *
 *   <MznInlineMessage
 *     aria-live="assertive"
 *     content="送出失敗"
 *     id="submit-error"
 *     severity="error"
 *   />
 * </template>
 * ```
 */
const props = defineProps<InlineMessageProps>();

const emit = defineEmits<{
  close: [];
}>();

/**
 * React spreads the rest props onto the inner div, after `role` and
 * `aria-live` so the consumer can override them. The root here is the fade
 * wrapper, so attributes are forwarded explicitly and in that same order.
 */
defineOptions({ inheritAttrs: false });

const visible = ref(true);

const fadeDuration = {
  enter: MOTION_DURATION.fast,
  exit: MOTION_DURATION.fast,
};
const fadeEasing = {
  enter: MOTION_EASING.standard,
  exit: MOTION_EASING.standard,
};

const icon = computed(() => props.icon ?? inlineMessageIcons[props.severity]);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.severity(props.severity)),
);

function handleClose(): void {
  visible.value = false;
  emit('close');
}

const iconClass = classes.icon;
const contentContainerClass = classes.contentContainer;
const contentClass = classes.content;
</script>

<template>
  <MznFade :duration="fadeDuration" :easing="fadeEasing" :in="visible">
    <div aria-live="polite" role="status" v-bind="$attrs" :class="hostClasses">
      <div :class="contentContainerClass">
        <MznIcon :class="iconClass" :icon="icon" />
        <span :class="contentClass">{{ content }}</span>
      </div>
      <MznClearActions
        v-if="severity === 'info'"
        type="standard"
        variant="base"
        @click="handleClose"
      />
    </div>
  </MznFade>
</template>

// packages/ng/inline-message/inline-message.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
  signal,
} from '@angular/core';
import {
  inlineMessageClasses as classes,
  inlineMessageIcons,
  InlineMessageSeverity,
} from '@mezzanine-ui/core/inline-message';
import { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznClearActions } from '@mezzanine-ui/ng/clear-actions';

/**
 * 行內訊息元件。
 *
 * 用於表單欄位旁的即時回饋，支援 info / warning / error 三種語意。
 * info 模式可附帶關閉按鈕。
 *
 * @example
 * ```html
 * import { MznInlineMessage } from '@mezzanine-ui/ng/inline-message';
 *
 * <mzn-inline-message
 *   severity="error"
 *   content="此欄位為必填"
 * />
 * ```
 */
@Component({
  selector: 'mzn-inline-message',
  standalone: true,
  imports: [MznIcon, MznClearActions],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    role: 'status',
    'aria-live': 'polite',
  },
  template: `
    @if (visible()) {
      <div [class]="contentContainerClass">
        <i mznIcon [icon]="resolvedIcon()" [class]="iconClass"></i>
        <span [class]="contentClass">{{ content() }}</span>
      </div>
      @if (severity() === 'info') {
        <mzn-clear-actions
          type="standard"
          variant="base"
          (clicked)="handleClose()"
        />
      }
    }
  `,
})
export class MznInlineMessage {
  /** 嚴重程度（必填）。 */
  readonly severity = input.required<InlineMessageSeverity>();

  /** 訊息文字（必填）。 */
  readonly content = input.required<string>();

  /** 自訂圖示（預設依 severity 自動選擇）。 */
  readonly icon = input<IconDefinition>();

  /** 關閉事件。 */
  readonly closed = output<void>();

  readonly visible = signal(true);

  protected readonly resolvedIcon = computed(
    (): IconDefinition => this.icon() ?? inlineMessageIcons[this.severity()],
  );

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.severity(this.severity())),
  );

  protected readonly contentContainerClass = classes.contentContainer;
  protected readonly iconClass = classes.icon;
  protected readonly contentClass = classes.content;

  protected handleClose(): void {
    this.visible.set(false);
    this.closed.emit();
  }
}
