// packages/vue/date-range-picker/date-range-picker.vue
<script setup lang="ts">
import { computed, ref, useAttrs, watch } from 'vue';
import type { ComponentPublicInstance } from 'vue';
import {
  getDefaultModeFormat,
  type DateType,
} from '@mezzanine-ui/core/calendar';
import { pickerClasses } from '@mezzanine-ui/core/picker';
import type { RangePickerValue } from '@mezzanine-ui/core/picker';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { h } from 'vue';
import { resolveElement } from '../_internal/resolve-element';
import { useCalendarContext } from '../calendar/calendar-context';
import type { CalendarFooterActionsProps } from '../calendar/calendar-footer-actions.types';
import MznIcon from '../icon/icon.vue';
import MznRangePickerTrigger from '../picker/range-picker-trigger.vue';
import { usePickerDocumentEventClose } from '../picker/use-picker-document-event-close';
import MznDateRangePickerCalendar from './date-range-picker-calendar.vue';
import type { DateRangePickerProps } from './date-range-picker.types';
import { useDateRangePickerValue } from './use-date-range-picker-value';

/**
 * 日期區間選擇器：兩個輸入框加上並排的雙日曆浮層。
 *
 * `confirmMode` 決定何時送出 `change`：`immediate` 選滿兩端就送出並關閉浮層，
 * `manual` 則自動補上「Confirm／Cancel」兩顆按鈕，按下確認才送出。
 * 自行傳入 `actions` 時同樣不會自動關閉。輸入顛倒的兩端會自動對調。
 * 必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDateRangePicker } from '@mezzanine-ui/vue/date-range-picker';
 * <\/script>
 *
 * <template>
 *   <MznDateRangePicker :value="value" @change="onChange" />
 *   <MznDateRangePicker confirm-mode="manual" :value="value" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznRangeCalendar 雙日曆本體
 * @see MznDatePicker 單一日期選擇器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DateRangePickerProps>(), {
  actions: undefined,
  calendarProps: undefined,
  clearable: true,
  confirmMode: 'immediate',
  defaultValue: undefined,
  disableOnDoubleNext: undefined,
  disableOnDoublePrev: undefined,
  disableOnNext: undefined,
  disableOnPrev: undefined,
  disabled: false,
  disabledMonthSwitch: false,
  disabledYearSwitch: false,
  displayMonthLocale: undefined,
  displayWeekDayLocale: undefined,
  error: false,
  errorMessagesFrom: undefined,
  errorMessagesTo: undefined,
  fadeProps: undefined,
  format: undefined,
  fullWidth: false,
  inputFromPlaceholder: undefined,
  inputFromProps: undefined,
  inputToPlaceholder: undefined,
  inputToProps: undefined,
  isDateDisabled: undefined,
  isHalfYearDisabled: undefined,
  isMonthDisabled: undefined,
  isQuarterDisabled: undefined,
  isWeekDisabled: undefined,
  isYearDisabled: undefined,
  mode: 'day',
  popperProps: undefined,
  quickSelect: undefined,
  readOnly: undefined,
  referenceDate: undefined,
  renderAnnotations: undefined,
  required: false,
  validateFrom: undefined,
  validateTo: undefined,
  value: undefined,
});

const emit = defineEmits<{
  calendarToggle: [open: boolean];
  change: [target?: RangePickerValue];
}>();

defineSlots<{
  /** The trigger's prefix. */
  prefix?: () => unknown;
}>();

const calendar = useCalendarContext();
const attrs = useAttrs();

const format = computed(
  (): string => props.format || getDefaultModeFormat(props.mode),
);

function isBetweenRange(
  valueToCheck: DateType,
  t1: DateType,
  t2: DateType,
  granularity: string,
): boolean {
  const { isBetween } = calendar.value;

  return (
    isBetween(valueToCheck, t1, t2, granularity) ||
    isBetween(valueToCheck, t2, t1, granularity)
  );
}

/** Using internal reference date */
const referenceDate = ref<DateType>(
  props.referenceDate || props.defaultValue?.[0] || calendar.value.getNow(),
);

/** Calendar panel toggle */
const open = ref(false);

function onCalendarToggle(currentOpen: boolean): void {
  if (props.readOnly) return;

  open.value = currentOpen;
  emit('calendarToggle', currentOpen);
}

/** Values and onChange */
const trigger = ref<InstanceType<typeof MznRangePickerTrigger> | null>(null);
const pickerCalendar = ref<InstanceType<
  typeof MznDateRangePickerCalendar
> | null>(null);
const inputFromRef = computed(
  (): HTMLInputElement | null => trigger.value?.inputFrom ?? null,
);
const inputToRef = computed(
  (): HTMLInputElement | null => trigger.value?.inputTo ?? null,
);
const anchorRef = computed((): HTMLElement | null =>
  resolveElement(trigger.value as ComponentPublicInstance | null),
);
const calendarRef = computed(
  (): HTMLElement | null => pickerCalendar.value?.element ?? null,
);

// In manual mode, don't hand onChange to the composable - the confirm button does it
const shouldTriggerOnChangeImmediately = computed(
  (): boolean => props.confirmMode === 'immediate' && !props.actions,
);

const {
  calendarValue,
  committedCalendarValue,
  hoverValue,
  hoverFromValue,
  hoverToValue,
  inputFromValue,
  inputToValue,
  onCalendarChange,
  onCalendarHover,
  onChange,
  onClear,
  onFromBlur,
  onFromFocus,
  onHoverClear,
  onInputFromChange,
  onInputToChange,
  onToBlur,
  onToFocus,
  value: internalValue,
} = useDateRangePickerValue({
  format,
  inputFromRef,
  inputToRef,
  mode: () => props.mode,
  onChange: (value) => {
    if (!shouldTriggerOnChangeImmediately.value) return;

    emit('change', value);
  },
  value: () => props.value,
});

// Update reference date when internal value changes
watch(internalValue, ([from, to]) => {
  if (from) {
    referenceDate.value = from;
  } else if (to) {
    referenceDate.value = to;
  }
});

/** Bind calendar open control to handlers */
function onCalendarChangeWithCloseControl(
  val: [DateType, DateType | undefined],
): void {
  onCalendarChange(val);

  // Close panel when range is complete (only if auto-close is enabled)
  // Auto-close is disabled when actions are provided or in manual mode
  if (val[0] && val[1] && shouldTriggerOnChangeImmediately.value) {
    onCalendarToggle(false);
  }
}

/** Handle confirm action (for manual mode) */
function onConfirm(): void {
  const [from, to] = internalValue.value;

  if (from && to) {
    emit('change', [from, to]);
    // Sync internal state and reset isSelecting
    onChange([from, to]);
  }

  onCalendarToggle(false);
}

/** Handle cancel action (for manual mode) */
function onCancel(): void {
  onChange(props.value);
  onCalendarToggle(false);
}

/** Auto-generated actions for manual mode */
const actions = computed(
  (): CalendarFooterActionsProps['actions'] | undefined => {
    // In manual mode, auto-generate actions
    if (props.confirmMode === 'manual') {
      const [from, to] = internalValue.value;
      const isRangeComplete = Boolean(from && to);

      return {
        primaryButtonProps: {
          children: 'Confirm',
          disabled: !isRangeComplete,
          onClick: onConfirm,
          ...props.actions?.primaryButtonProps,
        },
        secondaryButtonProps: {
          children: 'Cancel',
          onClick: onCancel,
          ...props.actions?.secondaryButtonProps,
        },
      };
    }

    if (props.actions) {
      return props.actions;
    }

    return undefined;
  },
);

/**
 * Calendar cell in range checker.
 *
 * Pure geometry — whether the range covers a disabled unit is decided by
 * `MznRangeCalendar`, which is the only place that knows which cells are
 * actually on screen. Keeping that scan out of here is what makes this
 * component's render cost independent of how wide the range is.
 */
function getIsInRangeHandler(
  granularity: string,
): ((date: DateType) => boolean) | undefined {
  const [rangeAnchorStart, rangeAnchorEnd] = calendarValue.value || [];

  if (!rangeAnchorStart || !rangeAnchorEnd) {
    return undefined;
  }

  return (date: DateType) =>
    isBetweenRange(date, rangeAnchorStart, rangeAnchorEnd, granularity);
}

/** Input focus handlers */
function onFromFocusHandler(): void {
  onFromFocus();
  onCalendarToggle(true);
}

function onToFocusHandler(): void {
  onToFocus();
  onCalendarToggle(true);
}

/** Blur, click away and key down close */
function onClose(): void {
  onChange(props.value);
  onCalendarToggle(false);
}

function onChangeClose(): void {
  // In manual mode, always restore to value (don't auto-submit on click-away)
  if (props.confirmMode === 'manual') {
    onChange(props.value);
    onCalendarToggle(false);

    return;
  }

  const [from, to] = internalValue.value;

  if (from && to) {
    emit('change', [from, to]);
  } else {
    onChange(props.value);
  }

  onCalendarToggle(false);
}

usePickerDocumentEventClose({
  anchorRef,
  lastElementRefInFlow: inputToRef,
  onChangeClose,
  onClose,
  open,
  popperRef: calendarRef,
});

/** Icon click handler */
function onIconClick(event: MouseEvent): void {
  event.stopPropagation();

  if (open.value) {
    onChange(props.value);
  }

  onCalendarToggle(!open.value);
}

const suffixActionIcon = computed(() =>
  h(MznIcon, { icon: CalendarIcon, onClick: onIconClick }),
);

const rangeWidthClass = computed((): string | undefined => {
  if (props.mode === 'year') return pickerClasses.hostRangeYear;

  return props.mode !== 'day' ? pickerClasses.hostRangeSlim : undefined;
});

const anchorGetter = (): HTMLElement | null => anchorRef.value;
</script>

<template>
  <MznRangePickerTrigger
    ref="trigger"
    v-bind="attrs"
    :class="rangeWidthClass"
    :clearable="clearable"
    :disabled="disabled"
    :error="error"
    :error-messages-from="errorMessagesFrom"
    :error-messages-to="errorMessagesTo"
    :force-show-clearable="!!(internalValue[0] || internalValue[1])"
    :format="format"
    :full-width="fullWidth"
    :hide-suffix-when-clearable="clearable"
    :hover-from-value="open ? hoverFromValue : undefined"
    :hover-to-value="open ? hoverToValue : undefined"
    :input-from-placeholder="inputFromPlaceholder"
    :input-from-props="inputFromProps"
    :input-from-value="inputFromValue"
    :input-to-placeholder="inputToPlaceholder"
    :input-to-props="inputToProps"
    :input-to-value="inputToValue"
    :read-only="readOnly"
    :required="required"
    :size="size"
    :suffix-action-icon="suffixActionIcon"
    :validate-from="validateFrom"
    :validate-to="validateTo"
    @clear="onClear"
    @from-blur="onFromBlur"
    @from-focus="onFromFocusHandler"
    @input-from-change="onInputFromChange"
    @input-to-change="onInputToChange"
    @to-blur="onToBlur"
    @to-focus="onToFocusHandler"
  >
    <template v-if="$slots.prefix" #prefix><slot name="prefix" /></template>
  </MznRangePickerTrigger>
  <MznDateRangePickerCalendar
    ref="pickerCalendar"
    :actions="actions"
    :anchor="anchorGetter"
    :calendar-props="calendarProps"
    :disable-on-double-next="disableOnDoubleNext"
    :disable-on-double-prev="disableOnDoublePrev"
    :disable-on-next="disableOnNext"
    :disable-on-prev="disableOnPrev"
    :disabled-month-switch="disabledMonthSwitch"
    :disabled-year-switch="disabledYearSwitch"
    :display-month-locale="displayMonthLocale"
    :display-week-day-locale="displayWeekDayLocale"
    :fade-props="fadeProps"
    :is-date-disabled="isDateDisabled"
    :is-date-in-range="getIsInRangeHandler('date')"
    :is-half-year-disabled="isHalfYearDisabled"
    :is-half-year-in-range="getIsInRangeHandler('half-year')"
    :is-month-disabled="isMonthDisabled"
    :is-month-in-range="getIsInRangeHandler('month')"
    :is-quarter-disabled="isQuarterDisabled"
    :is-quarter-in-range="getIsInRangeHandler('quarter')"
    :is-week-disabled="isWeekDisabled"
    :is-week-in-range="getIsInRangeHandler('week')"
    :is-year-disabled="isYearDisabled"
    :is-year-in-range="getIsInRangeHandler('year')"
    :mode="mode"
    :open="open"
    :popper-props="popperProps"
    :preview-value="hoverValue"
    :quick-select="quickSelect"
    :reference-date="referenceDate"
    :render-annotations="renderAnnotations"
    :value="committedCalendarValue"
    @change="onCalendarChangeWithCloseControl"
    @date-hover="onCalendarHover"
    @half-year-hover="onCalendarHover"
    @leave="onHoverClear"
    @month-hover="onCalendarHover"
    @quarter-hover="onCalendarHover"
    @week-hover="onCalendarHover"
    @year-hover="onCalendarHover"
  />
</template>

// packages/react/src/DateRangePicker/DateRangePicker.tsx
'use client';

import {
  forwardRef,
  FocusEvent,
  MouseEventHandler,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import { DateType, getDefaultModeFormat } from '@mezzanine-ui/core/calendar';
import { pickerClasses, RangePickerValue } from '@mezzanine-ui/core/picker';
import { CalendarIcon } from '@mezzanine-ui/icons';
import { useCalendarContext } from '../Calendar';
import { CalendarFooterActionsProps } from '../Calendar/CalendarFooterActions';
import DateRangePickerCalendar, {
  DateRangePickerCalendarProps,
} from './DateRangePickerCalendar';
import { useDateRangePickerValue } from './useDateRangePickerValue';
import {
  RangePickerTrigger,
  RangePickerTriggerProps,
  usePickerDocumentEventClose,
} from '../Picker';
import Icon from '../Icon';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { cx } from '../utils/cx';

export interface DateRangePickerProps
  extends Pick<
      DateRangePickerCalendarProps,
      | 'calendarProps'
      | 'disabledMonthSwitch'
      | 'disableOnNext'
      | 'disableOnPrev'
      | 'disableOnDoubleNext'
      | 'disableOnDoublePrev'
      | 'disabledYearSwitch'
      | 'displayMonthLocale'
      | 'displayWeekDayLocale'
      | 'fadeProps'
      | 'firstCalendarRef'
      | 'isDateDisabled'
      | 'isWeekDisabled'
      | 'isMonthDisabled'
      | 'isYearDisabled'
      | 'isQuarterDisabled'
      | 'isHalfYearDisabled'
      | 'mode'
      | 'popperProps'
      | 'quickSelect'
      | 'renderAnnotations'
      | 'secondCalendarRef'
    >,
    Pick<
      RangePickerTriggerProps,
      | 'className'
      | 'clearable'
      | 'disabled'
      | 'error'
      | 'errorMessagesFrom'
      | 'errorMessagesTo'
      | 'fullWidth'
      | 'inputFromPlaceholder'
      | 'inputFromProps'
      | 'inputToPlaceholder'
      | 'inputToProps'
      | 'prefix'
      | 'readOnly'
      | 'required'
      | 'size'
      | 'validateFrom'
      | 'validateTo'
    > {
  /**
   * Footer action buttons props.
   * When provided, the calendar will NOT auto-close after range selection.
   * This allows users to interact with the action buttons before confirming.
   */
  actions?: CalendarFooterActionsProps['actions'];
  /**
   * The confirm mode for date range selection.
   * - `'immediate'` (default): onChange is triggered immediately after selecting both dates,
   *   and calendar auto-closes (unless actions prop is provided).
   * - `'manual'`: onChange is triggered only when user clicks the confirm button.
   *   Default actions (Confirm/Cancel) will be auto-generated if not provided.
   * @default 'immediate'
   */
  confirmMode?: 'immediate' | 'manual';
  /**
   * Default value for date range picker.
   */
  defaultValue?: [DateType, DateType];
  /**
   * The format for displaying date.
   */
  format?: string;
  /**
   * A function that fires when calendar toggle. Receive open status in boolean format as props.
   */
  onCalendarToggle?: (open: boolean) => void;
  /**
   * Change handler. Takes an array of your declared `DateType` which represents from and to in order.
   */
  onChange?: (target?: RangePickerValue) => void;
  /**
   * The reference date for getting calendars. Default to current time.
   */
  referenceDate?: DateRangePickerCalendarProps['referenceDate'];
  /**
   * Value of the range picker.
   * It is an array of your declared `DateType` which represents from and to in order.
   */
  value?: RangePickerValue;
}

/**
 * The react component for `mezzanine` date range picker.
 * Notice that any component related to date-range-picker should be used along with `CalendarContext`.
 */
const DateRangePicker = forwardRef<HTMLDivElement, DateRangePickerProps>(
  function DateRangePicker(props, ref) {
    const { getNow, isBetween } = useCalendarContext();
    const {
      actions: actionsProp,
      calendarProps,
      className,
      clearable = true,
      confirmMode = 'immediate',
      defaultValue,
      disabledMonthSwitch = false,
      disableOnDoubleNext,
      disableOnDoublePrev,
      disableOnNext,
      disableOnPrev,
      disabled = false,
      disabledYearSwitch = false,
      displayMonthLocale,
      displayWeekDayLocale,
      error = false,
      errorMessagesFrom,
      errorMessagesTo,
      fadeProps,
      firstCalendarRef,
      format: formatProp,
      fullWidth = false,
      inputFromPlaceholder,
      inputFromProps,
      inputToPlaceholder,
      inputToProps,
      isDateDisabled,
      isHalfYearDisabled,
      isMonthDisabled,
      isQuarterDisabled,
      isWeekDisabled,
      isYearDisabled,
      mode = 'day',
      onCalendarToggle: onCalendarToggleProp,
      onChange: onChangeProp,
      popperProps,
      prefix,
      quickSelect,
      readOnly,
      referenceDate: referenceDateProp,
      renderAnnotations,
      required = false,
      secondCalendarRef,
      size,
      validateFrom,
      validateTo,
      value: valueProp,
    } = props;

    const format = formatProp || getDefaultModeFormat(mode);

    const isBetweenRange = useCallback(
      (
        valueToCheck: DateType,
        t1: DateType,
        t2: DateType,
        granularity: string,
      ) =>
        isBetween(valueToCheck, t1, t2, granularity) ||
        isBetween(valueToCheck, t2, t1, granularity),
      [isBetween],
    );

    /** Using internal reference date */
    const [referenceDate, updateReferenceDate] = useState(
      referenceDateProp || defaultValue?.[0] || getNow(),
    );

    /** Calendar panel toggle */
    const [open, setOpen] = useState(false);
    const preventOpen = readOnly;
    const onCalendarToggle = useCallback(
      (currentOpen: boolean) => {
        if (!preventOpen) {
          setOpen(currentOpen);
          onCalendarToggleProp?.(currentOpen);
        }
      },
      [onCalendarToggleProp, preventOpen],
    );

    /** Values and onChange */
    const inputToRef = useRef<HTMLInputElement>(null);
    const inputFromRef = useRef<HTMLInputElement>(null);

    // In manual mode, don't pass onChange to hook - we'll handle it via confirm button
    const shouldTriggerOnChangeImmediately =
      confirmMode === 'immediate' && !actionsProp;

    const {
      calendarValue,
      committedCalendarValue,
      hoverValue,
      hoverFromValue,
      hoverToValue,
      inputFromValue,
      inputToValue,
      onCalendarChange,
      onCalendarHover,
      onChange,
      onClear,
      onFromBlur,
      onFromFocus,
      onHoverClear,
      onInputFromChange,
      onInputToChange,
      onToBlur,
      onToFocus,
      value: internalValue,
    } = useDateRangePickerValue({
      format,
      inputFromRef,
      inputToRef,
      mode,
      onChange: shouldTriggerOnChangeImmediately ? onChangeProp : undefined,
      value: valueProp,
    });

    // Update reference date when internal value changes
    useEffect(() => {
      const [from, to] = internalValue;

      if (from) {
        updateReferenceDate(from);
      } else if (to) {
        updateReferenceDate(to);
      }
    }, [internalValue]);

    /** Bind calendar open control to handlers */
    const onCalendarChangeWithCloseControl = useCallback(
      (val: [DateType, DateType | undefined]) => {
        onCalendarChange(val);

        // Close panel when range is complete (only if auto-close is enabled)
        // Auto-close is disabled when actions are provided or in manual mode
        if (val[0] && val[1] && shouldTriggerOnChangeImmediately) {
          onCalendarToggle(false);
        }
      },
      [onCalendarChange, onCalendarToggle, shouldTriggerOnChangeImmediately],
    );

    /** Handle confirm action (for manual mode) */
    const onConfirm = useCallback(() => {
      const [from, to] = internalValue;

      if (from && to) {
        onChangeProp?.([from, to]);
        // Sync internal state and reset isSelecting
        onChange([from, to]);
      }

      onCalendarToggle(false);
    }, [internalValue, onChange, onChangeProp, onCalendarToggle]);

    /** Handle cancel action (for manual mode) */
    const onCancel = useCallback(() => {
      onChange(valueProp);
      onCalendarToggle(false);
    }, [onChange, onCalendarToggle, valueProp]);

    /** Auto-generated actions for manual mode */
    const actions: CalendarFooterActionsProps['actions'] | undefined =
      useMemo(() => {
        // In manual mode, auto-generate actions
        if (confirmMode === 'manual') {
          const [from, to] = internalValue;
          const isRangeComplete = Boolean(from && to);

          return {
            primaryButtonProps: {
              children: 'Confirm',
              disabled: !isRangeComplete,
              onClick: onConfirm,
              ...actionsProp?.primaryButtonProps,
            },
            secondaryButtonProps: {
              children: 'Cancel',
              onClick: onCancel,
              ...actionsProp?.secondaryButtonProps,
            },
          };
        }

        if (actionsProp) {
          return actionsProp;
        }

        return undefined;
      }, [actionsProp, confirmMode, internalValue, onConfirm, onCancel]);

    /**
     * Calendar cell in range checker.
     *
     * Pure geometry — whether the range covers a disabled unit is decided by
     * `RangeCalendar`, which is the only place that knows which cells are
     * actually on screen. Keeping that scan out of here is what makes this
     * component's render cost independent of how wide the range is.
     */
    const [rangeAnchorStart, rangeAnchorEnd] = calendarValue || [];
    const getIsInRangeHandler = useCallback(
      (granularity: string) => {
        if (!rangeAnchorStart || !rangeAnchorEnd) {
          return undefined;
        }

        return (date: DateType) =>
          isBetweenRange(date, rangeAnchorStart, rangeAnchorEnd, granularity);
      },
      [isBetweenRange, rangeAnchorEnd, rangeAnchorStart],
    );

    /** Popper settings */
    const anchorRef = useRef<HTMLDivElement>(null);
    const calendarRef = useRef<HTMLDivElement>(null);
    const triggerComposedRef = useComposeRefs([anchorRef, ref]);

    /** Input focus handlers */
    const onFromFocusHandler = useCallback(
      (_event: FocusEvent<HTMLInputElement>) => {
        onFromFocus();
        onCalendarToggle(true);
      },
      [onCalendarToggle, onFromFocus],
    );

    const onToFocusHandler = useCallback(
      (_event: FocusEvent<HTMLInputElement>) => {
        onToFocus();
        onCalendarToggle(true);
      },
      [onCalendarToggle, onToFocus],
    );

    /** Blur, click away and key down close */
    const onClose = useCallback(() => {
      onChange(valueProp);
      onCalendarToggle(false);
    }, [onChange, onCalendarToggle, valueProp]);

    const onChangeClose = useCallback(() => {
      // In manual mode, always restore to valueProp (don't auto-submit on click-away)
      if (confirmMode === 'manual') {
        onChange(valueProp);
        onCalendarToggle(false);
        return;
      }

      const [from, to] = internalValue;

      if (from && to) {
        onChangeProp?.([from, to]);
      } else {
        onChange(valueProp);
      }

      onCalendarToggle(false);
    }, [
      confirmMode,
      internalValue,
      onChange,
      onCalendarToggle,
      onChangeProp,
      valueProp,
    ]);

    usePickerDocumentEventClose({
      anchorRef,
      lastElementRefInFlow: inputToRef,
      onChangeClose,
      onClose,
      open,
      popperRef: calendarRef,
    });

    /** Icon click handler */
    const onIconClick: MouseEventHandler<HTMLElement> = useCallback(
      (e) => {
        e.stopPropagation();

        if (open) {
          onChange(valueProp);
        }

        onCalendarToggle(!open);
      },
      [onChange, onCalendarToggle, open, valueProp],
    );

    const suffixActionIcon = <Icon icon={CalendarIcon} onClick={onIconClick} />;

    const rangeWidthClass =
      mode === 'year'
        ? pickerClasses.hostRangeYear
        : mode !== 'day'
          ? pickerClasses.hostRangeSlim
          : undefined;

    return (
      <>
        <RangePickerTrigger
          className={cx(rangeWidthClass, className)}
          clearable={clearable}
          disabled={disabled}
          forceShowClearable={!!(internalValue[0] || internalValue[1])}
          hideSuffixWhenClearable={clearable}
          error={error}
          errorMessagesFrom={errorMessagesFrom}
          errorMessagesTo={errorMessagesTo}
          format={format}
          fullWidth={fullWidth}
          hoverFromValue={open ? hoverFromValue : undefined}
          hoverToValue={open ? hoverToValue : undefined}
          inputFromPlaceholder={inputFromPlaceholder}
          inputFromProps={inputFromProps}
          inputFromRef={inputFromRef}
          inputFromValue={inputFromValue}
          inputToPlaceholder={inputToPlaceholder}
          inputToProps={inputToProps}
          inputToRef={inputToRef}
          inputToValue={inputToValue}
          onClear={onClear}
          onFromBlur={onFromBlur}
          onFromFocus={onFromFocusHandler}
          onInputFromChange={onInputFromChange}
          onInputToChange={onInputToChange}
          onToBlur={onToBlur}
          onToFocus={onToFocusHandler}
          prefix={prefix}
          readOnly={readOnly}
          ref={triggerComposedRef}
          required={required}
          size={size}
          suffixActionIcon={suffixActionIcon}
          validateFrom={validateFrom}
          validateTo={validateTo}
        />
        <DateRangePickerCalendar
          actions={actions}
          anchor={anchorRef}
          calendarProps={calendarProps}
          disabledMonthSwitch={disabledMonthSwitch}
          disabledYearSwitch={disabledYearSwitch}
          disableOnDoubleNext={disableOnDoubleNext}
          disableOnDoublePrev={disableOnDoublePrev}
          disableOnNext={disableOnNext}
          disableOnPrev={disableOnPrev}
          displayMonthLocale={displayMonthLocale}
          displayWeekDayLocale={displayWeekDayLocale}
          fadeProps={fadeProps}
          firstCalendarRef={firstCalendarRef}
          isDateDisabled={isDateDisabled}
          isDateInRange={getIsInRangeHandler('date')}
          isHalfYearDisabled={isHalfYearDisabled}
          isHalfYearInRange={getIsInRangeHandler('half-year')}
          isMonthDisabled={isMonthDisabled}
          isMonthInRange={getIsInRangeHandler('month')}
          isQuarterDisabled={isQuarterDisabled}
          isQuarterInRange={getIsInRangeHandler('quarter')}
          isWeekDisabled={isWeekDisabled}
          isWeekInRange={getIsInRangeHandler('week')}
          isYearDisabled={isYearDisabled}
          isYearInRange={getIsInRangeHandler('year')}
          mode={mode}
          onChange={onCalendarChangeWithCloseControl}
          onDateHover={onCalendarHover}
          onHalfYearHover={onCalendarHover}
          onLeave={onHoverClear}
          onMonthHover={onCalendarHover}
          onQuarterHover={onCalendarHover}
          onWeekHover={onCalendarHover}
          onYearHover={onCalendarHover}
          open={open}
          popperProps={popperProps}
          previewValue={hoverValue}
          quickSelect={quickSelect}
          ref={calendarRef}
          referenceDate={referenceDate}
          renderAnnotations={renderAnnotations}
          secondCalendarRef={secondCalendarRef}
          value={committedCalendarValue}
        />
      </>
    );
  },
);

export default DateRangePicker;
