// packages/react/src/Transition/Slide.tsx
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { cloneElement, CSSProperties, forwardRef, useRef } from 'react';
import { useComposeRefs } from '../hooks/useComposeRefs';
import Transition, {
  TransitionState,
  TransitionImplementationProps,
  TransitionProps,
} from './Transition';
import { reflow } from './reflow';
import { useSetNodeTransition } from './useSetNodeTransition';

function getStyle(
  state: TransitionState,
  inProp: boolean,
  from: SlideFrom,
): CSSProperties {
  if (state === 'entering' || state === 'entered') {
    return {
      transform: 'translate3d(0, 0, 0)',
    };
  }

  const style: CSSProperties = {
    transform: {
      top: 'translate3d(0, -100%, 0)',
      right: 'translate3d(100%, 0, 0)',
    }[from],
  };

  if (state === 'exited' && !inProp) {
    style.visibility = 'hidden';
  }

  return style;
}

const defaultDuration = {
  enter: MOTION_DURATION.slow,
  exit: MOTION_DURATION.slow,
};

const defaultEasing = {
  enter: MOTION_EASING.standard,
  exit: MOTION_EASING.standard,
};

export type SlideFrom = 'right' | 'top';

export interface SlideProps extends TransitionImplementationProps {
  /**
   * The position of child element will enter from.
   * @default 'right'
   */
  from?: SlideFrom;
}

/**
 * The react component for `mezzanine` transition slide in/out.
 */
const Slide = forwardRef<HTMLElement, SlideProps>(function Slide(
  props: SlideProps,
  ref,
) {
  const {
    children,
    delay = 0,
    duration: durationProp = defaultDuration,
    easing = defaultEasing,
    from = 'right',
    in: inProp = false,
    onEnter,
    onEntered,
    onExit,
    onExited,
    ...rest
  } = props;
  const duration = durationProp === 'auto' ? defaultDuration : durationProp;
  const nodeRef = useRef<HTMLElement>(null);
  const composedNodeRef = useComposeRefs([ref, nodeRef]);
  const [setNodeTransition, resetNodeTransition] = useSetNodeTransition(
    {
      delay,
      duration,
      easing,
      properties: ['transform'],
    },
    children?.props.style,
  );
  const transitionProps: TransitionProps = {
    ...rest,
    duration,
    in: inProp,
    nodeRef,
    onEnter(node, isAppearing) {
      setNodeTransition(node, 'enter');
      reflow(node);

      if (onEnter) {
        onEnter(node, isAppearing);
      }
    },
    onEntered(node, isAppearing) {
      resetNodeTransition(node);

      if (onEntered) {
        onEntered(node, isAppearing);
      }
    },
    onExit(node) {
      setNodeTransition(node, 'exit');

      if (onExit) {
        onExit(node);
      }
    },
    onExited(node) {
      resetNodeTransition(node);

      if (onExited) {
        onExited(node);
      }
    },
  };

  return (
    <Transition {...transitionProps}>
      {children &&
        ((state) =>
          cloneElement(children, {
            ...children.props,
            ref: composedNodeRef,
            style: {
              ...getStyle(state, inProp, from),
              ...children.props.style,
            },
          }))}
    </Transition>
  );
});

export default Slide;

// packages/vue/transition/slide.vue
<script setup lang="ts">
import { computed, useSlots } from 'vue';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import { useTransitionImplementation } from './use-transition-implementation';
import type { TransitionRunnerConfig } from './transition-styles';
import type { SlideFrom, SlideProps } from './slide.types';

/**
 * 滑入轉場：整塊內容從畫面邊緣滑入，用於抽屜這類覆蓋層。
 *
 * 位移量是元素自身的 100%，且不帶淡入 —— 與 MznTranslate 的 4px 微幅位移是
 * 不同用途。
 *
 * @example
 * ```vue
 * <MznSlide from="right" :in="open">
 *   <div>抽屜內容</div>
 * </MznSlide>
 * ```
 *
 * @see MznTranslate 小幅位移的轉場
 */
const props = withDefaults(defineProps<SlideProps>(), {
  appear: true,
  delay: 0,
  duration: () => ({
    enter: MOTION_DURATION.slow,
    exit: MOTION_DURATION.slow,
  }),
  easing: () => ({
    enter: MOTION_EASING.standard,
    exit: MOTION_EASING.standard,
  }),
  from: 'right',
  in: false,
  keepMount: false,
  lazyMount: true,
});

const emit = defineEmits<{
  enter: [node: HTMLElement, isAppearing: boolean];
  entered: [node: HTMLElement, isAppearing: boolean];
  entering: [node: HTMLElement, isAppearing: boolean];
  exit: [node: HTMLElement];
  exited: [node: HTMLElement];
  exiting: [node: HTMLElement];
}>();

defineSlots<{
  default?: () => unknown;
}>();

const OFFSETS: Record<SlideFrom, string> = {
  top: 'translate3d(0, -100%, 0)',
  right: 'translate3d(100%, 0, 0)',
};

const config = computed(
  (): TransitionRunnerConfig => ({
    delay: props.delay,
    duration:
      props.duration === 'auto'
        ? { enter: MOTION_DURATION.slow, exit: MOTION_DURATION.slow }
        : props.duration,
    easing: props.easing,
    entered: { transform: 'translate3d(0, 0, 0)' },
    entering: { transform: 'translate3d(0, 0, 0)' },
    exited: { transform: OFFSETS[props.from] },
    properties: ['transform'],
  }),
);

const slots = useSlots();

const { TransitionChild, onAppear, onEnter, onLeave, shown } =
  useTransitionImplementation({
    child: () => slots.default?.(),
    config: () => config.value,
    in: () => props.in,
    keepMount: () => props.keepMount,
    on: {
      enter: (node, isAppearing) => emit('enter', node, isAppearing),
      entered: (node, isAppearing) => emit('entered', node, isAppearing),
      entering: (node, isAppearing) => emit('entering', node, isAppearing),
      exit: (node) => emit('exit', node),
      exited: (node) => emit('exited', node),
      exiting: (node) => emit('exiting', node),
    },
  });
</script>

<template>
  <Transition
    :appear="appear"
    :css="false"
    @appear="onAppear"
    @enter="onEnter"
    @leave="onLeave"
  >
    <TransitionChild v-if="shown" />
  </Transition>
</template>
