// packages/ng/_internal/input-check/input-check.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import {
  inputCheckClasses as classes,
  InputCheckSize,
} from '@mezzanine-ui/core/_internal/input-check';
import clsx from 'clsx';

/**
 * Checkbox / Radio 共用的勾選控制項佈局元件（內部元件，不公開匯出）。
 *
 * 負責渲染 label、control slot、hint 文字，以及各種狀態 CSS class。
 *
 * @example
 * ```html
 * <div mznInputCheck [size]="'main'" [disabled]="false">
 *   <ng-container control><input type="checkbox" /></ng-container>
 *   Label text
 * </div>
 * ```
 */
@Component({
  selector: '[mznInputCheck]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '[class]': 'hostClasses()',
    '[attr.size]': 'null',
    '[attr.disabled]': 'null',
    '[attr.error]': 'null',
    '[attr.focused]': 'null',
    '[attr.hint]': 'null',
    '[attr.hasLabel]': 'null',
    '[attr.segmentedStyle]': 'null',
  },
  template: `
    <span [class]="controlClasses()">
      <ng-content select="[control]" />
    </span>
    @if (hasLabel()) {
      <span [class]="labelClass">
        <ng-content />
        @if (hint()) {
          <span [class]="hintClass">{{ hint() }}</span>
        }
      </span>
    }
  `,
})
export class MznInputCheck {
  /**
   * 尺寸。
   * @default 'main'
   */
  readonly size = input<InputCheckSize>('main');

  /**
   * 是否禁用。
   * @default false
   */
  readonly disabled = input(false);

  /**
   * 是否為錯誤狀態。
   * @default false
   */
  readonly error = input(false);

  /**
   * 是否顯示焦點樣式。
   * @default false
   */
  readonly focused = input(false);

  /**
   * 提示文字。
   */
  readonly hint = input<string>();

  /**
   * 是否有 label 內容。
   * @default true
   */
  readonly hasLabel = input(true);

  /**
   * 是否為 segmented 樣式。
   * @default false
   */
  readonly segmentedStyle = input(false);

  protected readonly hostClasses = computed((): string =>
    clsx(classes.host, classes.size(this.size()), {
      [classes.disabled]: this.disabled(),
      [classes.error]: this.error(),
      [classes.segmented]: this.segmentedStyle(),
      [classes.withLabel]: this.hasLabel(),
    }),
  );

  protected readonly controlClasses = computed((): string =>
    clsx(classes.control, {
      [classes.controlFocused]: this.focused(),
      [classes.controlSegmented]: this.segmentedStyle(),
    }),
  );

  protected readonly labelClass = classes.label;
  protected readonly hintClass = classes.hint;
}

// packages/vue/_internal/input-check.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { VNode, VNodeArrayChildren } from 'vue';
import { inputCheckClasses as classes } from '@mezzanine-ui/core/_internal/input-check';
import clsx from 'clsx';
import { flattenChildren } from './flatten-children';
import type { InputCheckProps } from './input-check.types';

/**
 * 勾選類輸入元件的外框：一個 `label` 包住控制項與說明文字。
 *
 * 控制項由 `control` 傳入（React 是 ReactNode，這裡是 VNode），標籤文字走預設 slot；
 * 有標籤時才會渲染文字區塊，`hint` 只在有標籤時出現。
 *
 * @example
 * ```vue
 * <template>
 *   <MznInputCheck :control="h('input', { type: 'radio' })">選項</MznInputCheck>
 * </template>
 * ```
 *
 * @see MznRadio 使用這個外框的元件
 */
const props = withDefaults(defineProps<InputCheckProps>(), {
  control: undefined,
  disabled: undefined,
  error: undefined,
  focused: undefined,
  hint: undefined,
  segmentedStyle: false,
  size: 'main',
});

const slots = defineSlots<{
  /** The label of input check. */
  default?: () => VNode[];
}>();

/**
 * What the slot actually renders, not whether one was passed: Radio hands
 * `<slot v-if="type === 'radio'" />` down, and a `v-if` that is false still
 * leaves a comment placeholder behind. React sees `false` there and skips the
 * label — including its `--with-label` class.
 */
const hasLabel = computed((): boolean =>
  Boolean(
    flattenChildren(slots.default?.() as VNodeArrayChildren | undefined).length,
  ),
);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.size(props.size), {
    [classes.disabled]: props.disabled,
    [classes.error]: props.error,
    [classes.segmented]: props.segmentedStyle,
    [classes.withLabel]: hasLabel.value,
  }),
);

const controlClasses = computed((): string =>
  clsx(classes.control, {
    [classes.controlFocused]: props.focused,
    [classes.controlSegmented]: props.segmentedStyle,
  }),
);

const labelClass = classes.label;
const hintClass = classes.hint;
</script>

<template>
  <label :class="hostClasses">
    <span :class="controlClasses"><component :is="() => control" /></span>
    <span v-if="hasLabel" :class="labelClass">
      <slot />
      <span v-if="hint" :class="hintClass">{{ hint }}</span>
    </span>
  </label>
</template>
