// packages/vue/dropdown/dropdown-status.vue
<script setup lang="ts">
import { computed } from 'vue';
import { dropdownClasses as classes } from '@mezzanine-ui/core/dropdown/dropdown';
import { FolderOpenIcon } from '@mezzanine-ui/icons';
import MznIcon from '../icon/icon.vue';
import MznSpin from '../spin/spin.vue';
import MznTypography from '../typography/typography.vue';
import type { DropdownStatusProps } from './dropdown-status.types';

/**
 * 下拉選單的載入中／無資料狀態。
 *
 * `loading` 顯示轉圈，其餘顯示資料夾圖示；兩者的文字都可覆寫。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDropdownStatus } from '@mezzanine-ui/vue/dropdown';
 * <\/script>
 *
 * <template>
 *   <MznDropdownStatus status="empty" empty-text="沒有符合的選項" />
 * </template>
 * ```
 *
 * @see MznDropdown 顯示這個狀態的元件
 */
const props = withDefaults(defineProps<DropdownStatusProps>(), {
  emptyIcon: undefined,
  emptyText: undefined,
  loadingText: undefined,
});

const defaultStatusText = computed((): string => {
  if (props.status === 'loading') {
    return props.loadingText ?? 'Loading...';
  }

  if (props.status === 'empty') {
    return props.emptyText ?? 'No matching options.';
  }

  return '';
});

const icon = computed(() => props.emptyIcon ?? FolderOpenIcon);

const statusClass = classes.status;
const statusTextClass = classes.statusText;
</script>

<template>
  <div :class="statusClass">
    <MznSpin v-if="status === 'loading'" loading size="minor" />
    <MznIcon v-else :icon="icon" :size="16" />
    <MznTypography :class="statusTextClass">
      {{ defaultStatusText }}
    </MznTypography>
  </div>
</template>

// packages/react/src/Dropdown/DropdownStatus.tsx
'use client';

import { useMemo } from 'react';

import {
  dropdownClasses as classes,
  DropdownStatus as DropdownStatusType,
} from '@mezzanine-ui/core/dropdown/dropdown';
import { FolderOpenIcon, IconDefinition } from '@mezzanine-ui/icons';

import Icon from '../Icon';
import Spin from '../Spin';
import Typography from '../Typography';

export interface DropdownStatusProps {
  /**
   * The status of the dropdown.
   * @default 'loading'
   */
  status: DropdownStatusType;
  /**
   * The text of the dropdown loading status.
   */
  loadingText?: string;
  /**
   * The text of the dropdown empty status.
   */
  emptyText?: string;
  /**
   * The icon of the dropdown empty status.
   */
  emptyIcon?: IconDefinition;
}

export default function DropdownStatus(props: DropdownStatusProps) {
  const { status, loadingText, emptyText, emptyIcon } = props;

  const defaultStatusText = useMemo(() => {
    if (status === 'loading') {
      return loadingText ?? 'Loading...';
    }

    if (status === 'empty') {
      return emptyText ?? 'No matching options.';
    }

    return '';
  }, [status, loadingText, emptyText]);

  const IconElement = useMemo(() => {
    if (status === 'loading') {
      return <Spin loading size="minor" />;
    }

    return <Icon icon={emptyIcon ?? FolderOpenIcon} size={16} />;
  }, [status, emptyIcon]);

  return (
    <div className={classes.status}>
      {IconElement}
      <Typography className={classes.statusText}>
        {defaultStatusText}
      </Typography>
    </div>
  );
}
