// packages/ng/typography/typography.component.ts
import {
  AfterViewChecked,
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  OnChanges,
  Renderer2,
  ViewEncapsulation,
} from '@angular/core';
import {
  toTypographyCssVars,
  typographyClasses as classes,
  TypographyAlign,
  TypographyColor,
  TypographyDisplay,
  TypographyVariant,
} from '@mezzanine-ui/core/typography';
import {
  BooleanInput,
  createChangeEffect,
  createCssVarsChangeEffect,
  EnumWithFallbackInput,
  InputBoolean,
  InputEnumWithFallback,
  HostBindingClass,
  HostBindingEnumClass,
  TypedSimpleChanges,
} from '@mezzanine-ui/ng/cdk';

interface EllipsisInfo {
  status: boolean;
  content: string | null;
}

/**
 * The ng component for `mezzanine` typography.
 */
@Component({
  selector: '[mzn-typography]',
  exportAs: 'mznTypography',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ng-content></ng-content>
  `,
})
export class MznTypographyComponent implements OnChanges, AfterViewChecked {
  static ngAcceptInputType_ellipsis: BooleanInput;

  static ngAcceptInputType_noWrap: BooleanInput;

  static ngAcceptInputType_variant: EnumWithFallbackInput<TypographyVariant>;

  constructor(
    private readonly elementRef: ElementRef<HTMLElement>,
    private readonly renderer: Renderer2,
  ) {}

  private get hostElement() {
    return this.elementRef.nativeElement;
  }

  /**
   * The css variable for `text-align`.
   */
  @HostBindingClass(classes.align)
  @Input()
  align?: TypographyAlign;

  /**
   * The color name provided by palette.
   */
  @HostBindingClass(classes.color)
  @Input()
  color?: TypographyColor;

  /**
   * The css variable for `display`.
   */
  @HostBindingClass(classes.display)
  @Input()
  display?: TypographyDisplay;

  /**
   * If `true`, the text will not wrap, but instead will truncate with a text overflow ellipsis.
   *
   * Note that text overflow can only happen with `block` or `inline-block` level elements
   * @default false
   */
  @HostBindingClass(classes.ellipsis)
  @Input()
  @InputBoolean()
  ellipsis = false;

  /**
   * If `true`, the text will not wrap.
   * @default false
   */
  @HostBindingClass(classes.noWrap)
  @Input()
  @InputBoolean()
  noWrap = false;

  /**
   * Applies the typography variant.
   * @default 'body1'
   */
  // eslint-disable-next-line @angular-eslint/no-input-rename
  @HostBindingEnumClass(classes.variant, [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'body1',
    'body2',
    'button1',
    'button2',
    'button3',
    'input1',
    'input2',
    'input3',
    'caption',
  ])
  @Input('mzn-typography')
  @InputEnumWithFallback<TypographyVariant>('body1')
  variant: TypographyVariant;

  private readonly changeHostCssVars = createCssVarsChangeEffect(
    this.elementRef,
    this.renderer,
    () => toTypographyCssVars({
      align: this.align,
      color: this.color,
      display: this.display,
    }),
  );

  private readonly changeTitleAttr = createChangeEffect<EllipsisInfo>(
    ({ status, content }) => {
      if (status && content) {
        this.renderer.setAttribute(this.hostElement, 'title', content);
      } else {
        this.renderer.removeAttribute(this.hostElement, 'title');
      }
    },
    (x, y) => (
      x.status === y.status &&
      x.content === y.content
    ),
  );

  ngOnChanges(changes: TypedSimpleChanges<MznTypographyComponent>) {
    const {
      align,
      color,
      display,
    } = changes;

    if (align || color || display) {
      this.changeHostCssVars();
    }
  }

  ngAfterViewChecked() {
    this.changeTitleAttr({
      status: this.ellipsis,
      content: this.hostElement.textContent,
    });
  }
}

// packages/react/src/Typography/Typography.tsx
import { forwardRef, JSXElementConstructor } from 'react';
import {
  toTypographyCssVars,
  TypographyAlign,
  typographyClasses as classes,
  TypographyColor,
  TypographyDisplay,
  TypographyVariant,
} from '@mezzanine-ui/core/typography';
import { cx } from '../utils/cx';
import { ComponentOverridableForwardRefComponentPropsFactory } from '../utils/jsx-types';

export type TypographyComponent =
  | `h${1 | 2 | 3 | 4 | 5 | 6}`
  | 'p'
  | 'span'
  | 'label'
  | 'div'
  | 'caption'
  | 'a'
  | JSXElementConstructor<any>;

function getComponentFromVariant(variant: TypographyVariant): TypographyComponent {
  if (variant.startsWith('h')) {
    return variant as TypographyComponent;
  }

  if (variant.startsWith('body')) {
    return 'p';
  }

  return 'span';
}

interface TypographyPropsBase {
  /**
   * The css variable for `text-align`.
   */
  align?: TypographyAlign;
  /**
   * The color name provided by palette.
   */
  color?: TypographyColor;
  /**
   * The css variable for `display`.
   */
  display?: TypographyDisplay;
  /**
   * If `true`, the text will not wrap, but instead will truncate with a text overflow ellipsis.
   *
   * Note that text overflow can only happen with `block` or `inline-block` level elements
   * @default false
   */
  ellipsis?: boolean;
  /**
   * If `true`, the text will not wrap.
   * @default false
   */
  noWrap?: boolean;
  /**
   * Applies the typography variant.
   * @default 'body1'
   */
  variant?: TypographyVariant;
}

export type TypographyProps<C extends TypographyComponent = 'p'> =
  ComponentOverridableForwardRefComponentPropsFactory<TypographyComponent, C, TypographyPropsBase>;

/**
 * The react component for `mezzanine` typography.
 */
const Typography = forwardRef<HTMLParagraphElement, TypographyProps<'p'>>(function Typography(props, ref) {
  const {
    align,
    children,
    className,
    color,
    component,
    display,
    ellipsis = false,
    noWrap = false,
    variant = 'body1',
    style: styleProp,
    ...rest
  } = props;
  const Component = component || getComponentFromVariant(variant) as any;
  const cssVars = toTypographyCssVars({ align, color, display });
  const style = {
    ...cssVars,
    ...styleProp,
  };
  const title = ellipsis && typeof children === 'string'
    ? children
    : undefined;

  return (
    <Component
      {...rest}
      ref={ref}
      className={cx(
        classes.variant(variant),
        {
          [classes.align]: align,
          [classes.color]: color,
          [classes.display]: display,
          [classes.ellipsis]: ellipsis,
          [classes.noWrap]: noWrap,
        },
        className,
      )}
      style={style}
      title={title}
    >
      {children}
    </Component>
  );
});

export default Typography;
