// packages/react/src/Picker/RangePickerTrigger.tsx
import { CalendarIcon, LongTailArrowRightIcon } from '@mezzanine-ui/icons';
import { pickerClasses as classes } from '@mezzanine-ui/core/picker';
import {
  FocusEventHandler,
  forwardRef,
  MouseEventHandler,
  ReactNode,
  RefObject,
  useCallback,
  useRef,
} from 'react';
import TextField, { TextFieldProps } from '../TextField';
import Icon from '../Icon';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { cx } from '../utils/cx';
import FormattedInput, { FormattedInputProps } from './FormattedInput';
import { useComposeRefs } from '../hooks/useComposeRefs';

export interface RangePickerTriggerProps
  extends Omit<
    TextFieldProps,
    | 'active'
    | 'children'
    | 'defaultChecked'
    | 'disabled'
    | 'placeholder'
    | 'readonly'
    | 'typing'
  > {
  /**
   * Whether the picker is disabled.
   * @default false
   */
  disabled?: boolean;
  /**
   * Error messages configuration for 'from' input
   */
  errorMessagesFrom?: FormattedInputProps['errorMessages'];
  /**
   * Error messages configuration for 'to' input
   */
  errorMessagesTo?: FormattedInputProps['errorMessages'];
  /**
   * The format pattern for the inputs (e.g., "YYYY-MM-DD")
   */
  format: string;
  /**
   * Placeholder for the 'from' input element.
   */
  inputFromPlaceholder?: string;
  /**
   * React Ref for the 'from' input element.
   */
  inputFromRef?: RefObject<HTMLInputElement | null>;
  /**
   * Value of the 'from' input element.
   */
  inputFromValue?: string;
  /**
   * Placeholder for the 'to' input element.
   */
  inputToPlaceholder?: string;
  /**
   * React Ref for the 'to' input element.
   */
  inputToRef?: RefObject<HTMLInputElement | null>;
  /**
   * Value of the 'to' input element.
   */
  inputToValue?: string;
  /**
   * Click Handler for the calendar icon.
   */
  onIconClick?: MouseEventHandler;
  /**
   * Change handler for the 'from' input element.
   */
  onInputFromChange?: (formatted: string, rawDigits: string) => void;
  /**
   * Change handler for the 'to' input element.
   */
  onInputToChange?: (formatted: string, rawDigits: string) => void;
  /**
   * Focus handler for the 'from' input element.
   */
  onFromFocus?: FocusEventHandler<HTMLInputElement>;
  /**
   * Blur handler for the 'from' input element.
   */
  onFromBlur?: FocusEventHandler<HTMLInputElement>;
  /**
   * Focus handler for the 'to' input element.
   */
  onToFocus?: FocusEventHandler<HTMLInputElement>;
  /**
   * Blur handler for the 'to' input element.
   */
  onToBlur?: FocusEventHandler<HTMLInputElement>;
  /**
   * Whether the inputs are readonly.
   * @default false
   */
  readOnly?: boolean;
  /**
   * Whether the inputs are required.
   * @default false
   */
  required?: boolean;
  /**
   * Custom suffix element. If not provided, defaults to CalendarIcon.
   */
  suffix?: ReactNode;
  /**
   * Custom suffix action icon element (e.g., calendar icon with click handler)
   */
  suffixActionIcon?: ReactNode;
  /**
   * Custom validation function for 'from' input
   */
  validateFrom?: (isoDate: string) => boolean;
  /**
   * Custom validation function for 'to' input
   */
  validateTo?: (isoDate: string) => boolean;
  /**
   * A pre-formatted date string to preview in the 'from' input when it is empty and not focused.
   */
  hoverFromValue?: string;
  /**
   * A pre-formatted date string to preview in the 'to' input when it is empty and not focused.
   */
  hoverToValue?: string;
  /**
   * Other input props you may provide to the 'from' input element.
   */
  inputFromProps?: Omit<
    NativeElementPropsWithoutKeyAndRef<'input'>,
    | 'defaultValue'
    | 'disabled'
    | 'onChange'
    | 'placeholder'
    | 'readOnly'
    | 'required'
    | 'value'
    | `aria-${'disabled' | 'multiline' | 'readonly' | 'required'}`
  >;
  /**
   * Other input props you may provide to the 'to' input element.
   */
  inputToProps?: Omit<
    NativeElementPropsWithoutKeyAndRef<'input'>,
    | 'defaultValue'
    | 'disabled'
    | 'onChange'
    | 'placeholder'
    | 'readOnly'
    | 'required'
    | 'value'
    | `aria-${'disabled' | 'multiline' | 'readonly' | 'required'}`
  >;
}

/**
 * The react component for `mezzanine` date range picker trigger.
 * Uses FormattedInput for both from and to inputs to support the new input mode.
 */
const RangePickerTrigger = forwardRef<HTMLDivElement, RangePickerTriggerProps>(
  function RangePickerTrigger(props, ref) {
    const {
      className,
      clearable = true,
      disabled,
      errorMessagesFrom,
      errorMessagesTo,
      format,
      hoverFromValue,
      hoverToValue,
      inputFromPlaceholder,
      inputFromProps,
      inputFromRef: inputFromRefProp,
      inputFromValue,
      inputToPlaceholder,
      inputToProps,
      inputToRef: inputToRefProp,
      inputToValue,
      onFromBlur,
      onFromFocus,
      onIconClick,
      onInputFromChange,
      onInputToChange,
      onToBlur,
      onToFocus,
      readOnly,
      required,
      suffix,
      suffixActionIcon,
      validateFrom,
      validateTo,
      ...restTextFieldProps
    } = props;

    const internalFromRef = useRef<HTMLInputElement>(null);
    const internalToRef = useRef<HTMLInputElement>(null);

    const fromRef = useComposeRefs([
      internalFromRef,
      inputFromRefProp,
    ]) as unknown as RefObject<HTMLInputElement | null>;

    const toRef = useComposeRefs([
      internalToRef,
      inputToRefProp,
    ]) as unknown as RefObject<HTMLInputElement | null>;

    const defaultSuffix = suffixActionIcon ?? (
      <Icon
        icon={CalendarIcon}
        onClick={onIconClick}
        aria-label="Open calendar"
      />
    );

    // TextField requires disabled and readonly to be mutually exclusive
    let defaultTextFieldProps = {};

    if (disabled) {
      defaultTextFieldProps = { disabled: true as const };
    } else if (readOnly) {
      defaultTextFieldProps = { readonly: true as const };
    }

    /**
     * Handle from input change
     */
    const handleFromChange = useCallback(
      (formattedValue: string, rawDigits: string) => {
        onInputFromChange?.(formattedValue, rawDigits);
      },
      [onInputFromChange],
    );

    /**
     * Handle to input change
     */
    const handleToChange = useCallback(
      (formattedValue: string, rawDigits: string) => {
        onInputToChange?.(formattedValue, rawDigits);
      },
      [onInputToChange],
    );

    /**
     * Handle from input focus
     */
    const handleFromFocus: FocusEventHandler<HTMLInputElement> = useCallback(
      (e) => {
        onFromFocus?.(e);
      },
      [onFromFocus],
    );

    /**
     * Handle to input focus
     */
    const handleToFocus: FocusEventHandler<HTMLInputElement> = useCallback(
      (e) => {
        onToFocus?.(e);
      },
      [onToFocus],
    );

    /**
     * Handle from input blur
     */
    const handleFromBlur: FocusEventHandler<HTMLInputElement> = useCallback(
      (e) => {
        onFromBlur?.(e);
      },
      [onFromBlur],
    );

    /**
     * Handle to input blur
     */
    const handleToBlur: FocusEventHandler<HTMLInputElement> = useCallback(
      (e) => {
        onToBlur?.(e);
      },
      [onToBlur],
    );

    return (
      <TextField
        {...restTextFieldProps}
        {...defaultTextFieldProps}
        ref={ref}
        className={cx(classes.host, classes.hostRange, className)}
        clearable={!readOnly && clearable}
        suffix={suffix ?? defaultSuffix}
      >
        <FormattedInput
          {...inputFromProps}
          ref={fromRef}
          aria-disabled={disabled}
          aria-label="Start date"
          aria-multiline={false}
          aria-readonly={readOnly}
          aria-required={required}
          disabled={disabled}
          errorMessages={errorMessagesFrom}
          format={format}
          hoverValue={hoverFromValue}
          onBlur={handleFromBlur}
          onChange={handleFromChange}
          onFocus={handleFromFocus}
          placeholder={inputFromPlaceholder}
          readOnly={readOnly}
          required={required}
          validate={validateFrom}
          value={inputFromValue}
        />
        <Icon
          icon={LongTailArrowRightIcon}
          className={classes.arrowIcon}
          aria-hidden="true"
        />
        <FormattedInput
          {...inputToProps}
          ref={toRef}
          aria-disabled={disabled}
          aria-label="End date"
          aria-multiline={false}
          aria-readonly={readOnly}
          aria-required={required}
          disabled={disabled}
          errorMessages={errorMessagesTo}
          format={format}
          hoverValue={hoverToValue}
          onBlur={handleToBlur}
          onChange={handleToChange}
          onFocus={handleToFocus}
          placeholder={inputToPlaceholder}
          readOnly={readOnly}
          required={required}
          validate={validateTo}
          value={inputToValue}
        />
      </TextField>
    );
  },
);

export default RangePickerTrigger;

// packages/vue/picker/range-picker-trigger.vue
<script setup lang="ts">
import { computed, h, ref } from 'vue';
import type { FunctionalComponent, VNodeChild } from 'vue';
import { pickerClasses as classes } from '@mezzanine-ui/core/picker';
import { CalendarIcon, LongTailArrowRightIcon } from '@mezzanine-ui/icons';
import MznIcon from '../icon/icon.vue';
import MznTextField from '../text-field/text-field.vue';
import MznFormattedInput from './formatted-input.vue';
import type { RangePickerTriggerProps } from './range-picker-trigger.types';

/**
 * 區間 picker 的觸發元件：兩個共用同一格式的遮罩輸入框，中間是箭頭圖示。
 *
 * 沒有提供 `suffix` slot 或 `suffixActionIcon` 時，後綴預設是日曆圖示，
 * 點擊會送出 `iconClick`。必須放在 MznCalendarConfigProvider 底下。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznRangePickerTrigger } from '@mezzanine-ui/vue/picker';
 * <\/script>
 *
 * <template>
 *   <MznRangePickerTrigger
 *     format="YYYY-MM-DD"
 *     :input-from-value="from"
 *     :input-to-value="to"
 *     @input-from-change="onFromChange"
 *     @input-to-change="onToChange"
 *   />
 * </template>
 * ```
 *
 * @see MznPickerTrigger 單一輸入框的版本
 */
const props = withDefaults(defineProps<RangePickerTriggerProps>(), {
  clearable: true,
  disabled: undefined,
  errorMessagesFrom: undefined,
  errorMessagesTo: undefined,
  hoverFromValue: undefined,
  hoverToValue: undefined,
  inputFromPlaceholder: undefined,
  inputFromProps: undefined,
  inputFromValue: undefined,
  inputToPlaceholder: undefined,
  inputToProps: undefined,
  inputToValue: undefined,
  readOnly: undefined,
  required: undefined,
  suffixActionIcon: undefined,
  validateFrom: undefined,
  validateTo: undefined,
});

const emit = defineEmits<{
  clear: [event: MouseEvent];
  fromBlur: [event: FocusEvent];
  fromFocus: [event: FocusEvent];
  iconClick: [event: MouseEvent];
  inputFromChange: [formatted: string, rawDigits: string];
  inputToChange: [formatted: string, rawDigits: string];
  toBlur: [event: FocusEvent];
  toFocus: [event: FocusEvent];
}>();

const slots = defineSlots<{
  /** The trigger's suffix. Defaults to a calendar icon. */
  suffix?: () => unknown;
}>();

const fromInput = ref<InstanceType<typeof MznFormattedInput> | null>(null);
const toInput = ref<InstanceType<typeof MznFormattedInput> | null>(null);

/**
 * React hands the inputs out through `inputFromRef` / `inputToRef` props;
 * Vue's equivalent is the parent placing a `ref` on this component, so the
 * elements are exposed.
 */
defineExpose({
  inputFrom: computed(
    (): HTMLInputElement | null => fromInput.value?.input ?? null,
  ),
  inputTo: computed(
    (): HTMLInputElement | null => toInput.value?.input ?? null,
  ),
});

const defaultSuffix = computed(
  (): VNodeChild =>
    props.suffixActionIcon ??
    h(MznIcon, {
      'aria-label': 'Open calendar',
      icon: CalendarIcon,
      onClick: (event: MouseEvent) => emit('iconClick', event),
    }),
);

const Suffix: FunctionalComponent = () =>
  slots.suffix ? slots.suffix() : defaultSuffix.value;

// TextField requires disabled and readonly to be mutually exclusive
const textFieldState = computed(() => {
  if (props.disabled) return { disabled: true as const };
  if (props.readOnly) return { readonly: true as const };

  return {};
});

const arrowIconClass = classes.arrowIcon;
const hostClasses = `${classes.host} ${classes.hostRange}`;
</script>

<template>
  <MznTextField
    v-bind="textFieldState"
    :class="hostClasses"
    :clearable="!readOnly && clearable"
    :error="error"
    :force-show-clearable="forceShowClearable"
    :full-width="fullWidth"
    :hide-suffix-when-clearable="hideSuffixWhenClearable"
    role="presentation"
    :size="size"
    :warning="warning"
    @clear="emit('clear', $event)"
  >
    <template #suffix><Suffix /></template>
    <MznFormattedInput
      ref="fromInput"
      v-bind="inputFromProps"
      aria-label="Start date"
      :aria-disabled="disabled"
      :aria-multiline="false"
      :aria-readonly="readOnly"
      :aria-required="required"
      :disabled="disabled"
      :error-messages="errorMessagesFrom"
      :format="format"
      :hover-value="hoverFromValue"
      :placeholder="inputFromPlaceholder"
      :read-only="readOnly"
      :required="required"
      :validate="validateFrom"
      :value="inputFromValue"
      @blur="emit('fromBlur', $event)"
      @change="
        (formatted, rawDigits) => emit('inputFromChange', formatted, rawDigits)
      "
      @focus="emit('fromFocus', $event)"
    />
    <MznIcon
      aria-hidden="true"
      :class="arrowIconClass"
      :icon="LongTailArrowRightIcon"
    />
    <MznFormattedInput
      ref="toInput"
      v-bind="inputToProps"
      aria-label="End date"
      :aria-disabled="disabled"
      :aria-multiline="false"
      :aria-readonly="readOnly"
      :aria-required="required"
      :disabled="disabled"
      :error-messages="errorMessagesTo"
      :format="format"
      :hover-value="hoverToValue"
      :placeholder="inputToPlaceholder"
      :read-only="readOnly"
      :required="required"
      :validate="validateTo"
      :value="inputToValue"
      @blur="emit('toBlur', $event)"
      @change="
        (formatted, rawDigits) => emit('inputToChange', formatted, rawDigits)
      "
      @focus="emit('toFocus', $event)"
    />
  </MznTextField>
</template>
