// packages/vue/floating-button/floating-button.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { floatingButtonClasses as classes } from '@mezzanine-ui/core/floating-button';
import clsx from 'clsx';
import MznButton from '../button/button.vue';
import type { FloatingButtonProps } from './floating-button.types';

/**
 * 浮動按鈕，固定在畫面角落，捲動時不隨內容移動。
 *
 * 外觀固定為 `base-primary`、`main` 尺寸，圖示模式的提示固定顯示在左側，
 * 因此不接受 `variant`、`size` 與 `tooltipPosition`。搭配 `autoHideWhenOpen`
 * 與 `open`，可在旁邊的面板或對話框開啟時把自己收起來。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznFloatingButton } from '@mezzanine-ui/vue/floating-button';
 * import { PlusIcon } from '@mezzanine-ui/icons';
 * <\/script>
 *
 * <template>
 *   <MznFloatingButton :icon="PlusIcon" icon-type="leading">新增</MznFloatingButton>
 *   <MznFloatingButton auto-hide-when-open :open="open" @click="open = !open">
 *     開啟
 *   </MznFloatingButton>
 * </template>
 * ```
 *
 * @see MznButton 內部渲染的按鈕
 */
/**
 * React puts the consumer's `className` on the wrapper and spreads everything
 * else onto the Button. Vue's fallthrough would put all of it on the wrapper.
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<FloatingButtonProps>(), {
  autoHideWhenOpen: false,
  component: undefined,
  disabled: undefined,
  disabledTooltip: undefined,
  icon: undefined,
  iconType: undefined,
  loading: undefined,
  open: false,
});

defineSlots<{
  /** The button label, or the tooltip content when `iconType="icon-only"`. */
  default?: () => unknown;
}>();

const attrs = useAttrs();

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const hostClasses = computed((): string =>
  clsx(classes.host, attrs.class as string),
);

const buttonClasses = computed((): string =>
  clsx(classes.button, {
    [classes.buttonHidden]: props.autoHideWhenOpen && props.open,
  }),
);
</script>

<template>
  <div :class="hostClasses">
    <MznButton
      v-bind="forwardedAttrs"
      :class="buttonClasses"
      :component="component"
      :disabled="disabled"
      :disabled-tooltip="disabledTooltip"
      :icon="icon"
      :icon-type="iconType"
      :loading="loading"
      size="main"
      tooltip-position="left"
      variant="base-primary"
    >
      <slot />
    </MznButton>
  </div>
</template>

// packages/ng/floating-button/floating-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from '@angular/core';
import { IconDefinition } from '@mezzanine-ui/icons';
import { ButtonIconType } from '@mezzanine-ui/core/button';
import { floatingButtonClasses as classes } from '@mezzanine-ui/core/floating-button';

import { MznButton } from '@mezzanine-ui/ng/button';
import { MznIcon } from '@mezzanine-ui/ng/icon';

/**
 * 浮動按鈕元件，固定於畫面角落的操作按鈕容器。
 *
 * 內部封裝一顆 `MznButton`（強制 `variant="base-primary"` / `size="main"` /
 * `tooltipPosition="left"`），對應 React `<FloatingButton>` 的結構。
 * 使用 attribute selector 套用於 `<div>`，host element 為 `<div>` 以與 React 完全一致。
 *
 * @example
 * ```html
 * import { MznFloatingButton } from '@mezzanine-ui/ng/floating-button';
 *
 * <div mzn-floating-button [icon]="PlusIcon" iconType="leading">Button</div>
 *
 * <div mzn-floating-button [autoHideWhenOpen]="true" [open]="open()" (click)="toggle()">
 *   Open
 * </div>
 * ```
 */
@Component({
  selector: '[mznFloatingButton]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznButton, MznIcon],
  host: {
    '[class]': 'hostClasses()',
  },
  template: `
    <button
      mznButton
      variant="base-primary"
      size="main"
      tooltipPosition="left"
      [class.mzn-floating-button__button]="true"
      [class.mzn-floating-button__button--hidden]="hidden()"
      [disabled]="disabled()"
      [disabledTooltip]="disabledTooltip()"
      [icon]="icon()"
      [iconType]="iconType()"
      [loading]="loading()"
    >
      @if (icon() && iconType() !== 'trailing') {
        <i mznIcon [icon]="icon()!"></i>
      }
      @if (iconType() !== 'icon-only') {
        <ng-content />
      }
      @if (icon() && iconType() === 'trailing') {
        <i mznIcon [icon]="icon()!"></i>
      }
    </button>
  `,
})
export class MznFloatingButton {
  /**
   * 是否在 `open` 為 true 時自動隱藏按鈕。
   * @default false
   */
  readonly autoHideWhenOpen = input(false);

  /**
   * 是否禁用內部按鈕。
   * @default false
   */
  readonly disabled = input(false);

  /**
   * 是否禁用 icon-only 模式的自動 tooltip。
   * @default false
   */
  readonly disabledTooltip = input(false);

  /** 按鈕圖示定義（來自 `@mezzanine-ui/icons`）。 */
  readonly icon = input<IconDefinition>();

  /**
   * 圖示排列方式。
   */
  readonly iconType = input<ButtonIconType>();

  /**
   * 是否顯示載入狀態。
   * @default false
   */
  readonly loading = input(false);

  /**
   * 是否為展開狀態。搭配 `autoHideWhenOpen` 使用。
   * @default false
   */
  readonly open = input(false);

  protected readonly hostClasses = computed((): string => classes.host);

  protected readonly hidden = computed(
    (): boolean => this.autoHideWhenOpen() && this.open(),
  );
}
