// packages/react/src/Empty/Empty.tsx
import {
  DetailedHTMLProps,
  forwardRef,
  HTMLAttributes,
  ReactNode,
} from 'react';
import {
  emptyClasses as classes,
} from '@mezzanine-ui/core/empty';
import { FolderOpenIcon } from '@mezzanine-ui/icons';
import { cx } from '../utils/cx';
import Icon from '../Icon';
import Typography from '../Typography';

export interface EmptyProps extends Omit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, 'title'> {
  /**
   * if true, the empty component will be 100% height of it's parent
   */
  fullHeight?: boolean;
  /**
   * Override default icon.
   */
  image?: ReactNode;
  /**
   * Optionally given a title. If not required, simply use react children to display description.
   */
  title?: ReactNode;
}

const Empty = forwardRef<HTMLDivElement, EmptyProps>(function Empty(props, ref) {
  const defaultIcon = (
    <Icon
      className={classes.icon}
      icon={FolderOpenIcon}
      color="disabled"
    />
  );

  const {
    children,
    className,
    fullHeight,
    image = defaultIcon,
    title,
    ...rest
  } = props;

  return (
    <div
      ref={ref}
      className={cx(
        classes.host,
        {
          [classes.fullHeight]: fullHeight,
        },
        className,
      )}
      {...rest}
    >
      {image}
      {title && (
        <Typography
          component="div"
          variant="h3"
          className={classes.title}
          color="text-secondary"
        >
          {title}
        </Typography>
      )}
      <Typography
        component="div"
        variant="body1"
        color="text-secondary"
      >
        {children}
      </Typography>
    </div>
  );
});

export default Empty;

// packages/ng/src/empty/empty.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  HostBinding,
  Input,
  TemplateRef,
  ViewEncapsulation,
} from '@angular/core';
import { emptyClasses as classes } from '@mezzanine-ui/core/empty';
import { FolderOpenIcon } from '@mezzanine-ui/icons';
import { BooleanInput, InputBoolean } from '../core';

/**
 * The ng component for `mezzanine` empty.
 */
@Component({
  selector: 'mzn-empty',
  exportAs: 'mznEmpty',
  preserveWhitespaces: false,
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  template: `
    <ng-template #defaultImageTemplate>
      <i [mzn-icon]="icon" [class]="classes.icon" color="disabled"></i>
    </ng-template>

    <ng-template [ngTemplateOutlet]="image || defaultImageTemplate"></ng-template>
    <div *ngIf="title" mzn-typography="h3" [class]="classes.title" color="text-secondary">{{title}}</div>
    <div mzn-typography="body1" color="text-secondary">
      <ng-content></ng-content>
    </div>
  `,
})
export class MznEmptyComponent {
  static ngAcceptInputType_spin: BooleanInput;

  @HostBinding(`class.${classes.host}`)
  readonly bindHostClass = true;

  readonly classes = classes;

  icon = FolderOpenIcon;

  /**
   * If true, set height of host to 100%.
   */
  @HostBinding(`class.${classes.fullHeight}`)
  @Input()
  @InputBoolean()
  fullHeight = false;

  /**
   * A TemplateRef for override default icon.
   */
  @Input()
  image?: TemplateRef<any>;

  /**
   * The empty title.
   */
  @Input()
  title?: string;
}
