// packages/vue/progress/progress.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import type { CSSProperties } from 'vue';
import {
  progressClasses as classes,
  ProgressStatuses,
  ProgressTypes,
} from '@mezzanine-ui/core/progress';
import type { ProgressStatus } from '@mezzanine-ui/core/progress';
import { CheckedFilledIcon, DangerousFilledIcon } from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import MznTypography from '../typography/typography.vue';
import type { ProgressProps } from './progress.types';

/**
 * 進度條元件，支援百分比文字與狀態圖示兩種顯示類型。
 *
 * `percent` 介於 0～100，未達 100 時狀態自動為 `enabled`，達到 100 時自動切換為 `success`。
 * 可強制指定 `status` 為 `error` 以顯示錯誤圖示；使用 `tick` prop 可在進度條上標記特定位置。
 * 支援 `icons` prop 自訂 success 與 error 狀態的圖示。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznProgress } from '@mezzanine-ui/vue/progress';
 * <\/script>
 *
 * <template>
 *   <MznProgress :percent="60" />
 *   <MznProgress :percent="75" type="percent" />
 *   <MznProgress :percent="40" status="error" type="icon" />
 *   <MznProgress :percent="60" :tick="80" />
 * </template>
 * ```
 *
 * @see MznSpin 載入旋轉元件
 */
const props = withDefaults(defineProps<ProgressProps>(), {
  icons: undefined,
  percent: 0,
  percentProps: undefined,
  status: undefined,
  tick: undefined,
  type: 'progress',
});

const status = computed(
  (): ProgressStatus =>
    props.status ??
    (props.percent < 100 ? ProgressStatuses.enabled : ProgressStatuses.success),
);

const percentLimited = computed((): number =>
  Math.max(0, Math.min(100, props.percent)),
);

const icon = computed((): IconDefinition => {
  if (status.value === ProgressStatuses.success) {
    return props.icons?.success ?? CheckedFilledIcon;
  }

  return props.icons?.error ?? DangerousFilledIcon;
});

const isSuccessStatus = computed(
  (): boolean =>
    status.value === ProgressStatuses.success &&
    props.type === ProgressTypes.icon,
);
const isErrorStatus = computed(
  (): boolean =>
    status.value === ProgressStatuses.error &&
    props.type === ProgressTypes.icon,
);
const isActiveTick = computed(
  (): boolean => props.tick !== undefined && props.tick > 0 && props.tick < 100,
);

const tickPosition = computed((): number | undefined => {
  if (!isActiveTick.value || props.tick === undefined) return undefined;

  return Math.max(0, Math.min(100, props.tick));
});

const line = ref<HTMLDivElement | null>(null);
const tickLeft = ref<string | undefined>(undefined);

let resizeObserver: ResizeObserver | null = null;
let updateTickPosition: (() => void) | null = null;

function teardownTick(): void {
  resizeObserver?.disconnect();
  resizeObserver = null;

  if (updateTickPosition) {
    window.removeEventListener('resize', updateTickPosition);
    updateTickPosition = null;
  }
}

/**
 * The tick sits on the container, not on the line, so its offset has to be
 * translated from a percentage of the line into a percentage of the container.
 */
watch(
  [isActiveTick, tickPosition, () => props.type, percentLimited, line],
  () => {
    teardownTick();

    const lineElement = line.value;

    if (
      !isActiveTick.value ||
      tickPosition.value === undefined ||
      !lineElement
    ) {
      tickLeft.value = undefined;

      return;
    }

    const containerElement = lineElement.parentElement;

    if (!containerElement) {
      tickLeft.value = undefined;

      return;
    }

    updateTickPosition = (): void => {
      const lineRect = lineElement.getBoundingClientRect();
      const containerRect = containerElement.getBoundingClientRect();

      // 計算 line 相對於容器的位置和寬度
      const lineLeft = lineRect.left - containerRect.left;
      const lineWidth = lineRect.width;

      // 計算 tick 在 line 中的位置（百分比轉換為像素）
      const tickOffsetInLine = ((tickPosition.value ?? 0) / 100) * lineWidth;

      // 計算 tick 相對於容器的絕對位置
      const tickAbsoluteLeft = lineLeft + tickOffsetInLine;

      // 轉換為百分比（相對於容器）
      const containerWidth = containerRect.width;

      tickLeft.value = `${(tickAbsoluteLeft / containerWidth) * 100}%`;
    };

    // 初始計算
    updateTickPosition();
    window.addEventListener('resize', updateTickPosition);

    if (typeof ResizeObserver !== 'undefined') {
      resizeObserver = new ResizeObserver(() => updateTickPosition?.());
      resizeObserver.observe(lineElement);
      resizeObserver.observe(containerElement);
    }
  },
  { flush: 'post', immediate: true },
);

onBeforeUnmount(teardownTick);

const hostClasses = computed((): string =>
  clsx(classes.host, classes.type(props.type), {
    [classes.success]: status.value === ProgressStatuses.success,
    [classes.error]: status.value === ProgressStatuses.error,
  }),
);

const lineStyle = computed(
  (): CSSProperties => ({ width: `${percentLimited.value}%` }),
);

const tickStyle = computed(
  (): CSSProperties => ({ '--tick-position': tickLeft.value }) as CSSProperties,
);

const lineVariantClass = classes.lineVariant;
const lineBgClass = classes.lineBg;
const infoPercentClass = classes.infoPercent;
const infoIconClass = classes.infoIcon;
const tickClass = classes.tick;
</script>

<template>
  <div :class="hostClasses">
    <div ref="line" :class="lineVariantClass">
      <i :class="lineBgClass" :style="lineStyle" />
    </div>
    <MznTypography
      v-if="type === 'percent'"
      variant="input"
      v-bind="percentProps"
      :class="infoPercentClass"
    >
      {{ `${percentLimited}%` }}
    </MznTypography>
    <MznIcon
      v-if="isSuccessStatus || isErrorStatus"
      :class="infoIconClass"
      :icon="icon"
    />
    <div
      v-if="isActiveTick && tickLeft !== undefined"
      :class="tickClass"
      :style="tickStyle"
    />
  </div>
</template>

// packages/ng/progress/progress.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  computed,
  DestroyRef,
  ElementRef,
  inject,
  input,
  signal,
  viewChild,
} from '@angular/core';
import {
  progressClasses as classes,
  ProgressStatus,
  ProgressStatuses,
  ProgressType,
  ProgressTypes,
} from '@mezzanine-ui/core/progress';
import {
  TypographyAlign,
  TypographyColor,
  TypographyDisplay,
} from '@mezzanine-ui/core/typography';
import { TypographySemanticType } from '@mezzanine-ui/system/typography';
import {
  CheckedFilledIcon,
  DangerousFilledIcon,
  IconDefinition,
} from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznTypography } from '@mezzanine-ui/ng/typography';

export interface ProgressPercentProps {
  align?: TypographyAlign;
  color?: TypographyColor;
  display?: TypographyDisplay;
  ellipsis?: boolean;
  noWrap?: boolean;
  variant?: TypographySemanticType;
}

/**
 * 進度條元件，支援百分比文字與狀態圖示兩種顯示類型。
 *
 * `percent` 介於 0～100，未達 100 時狀態自動為 `enabled`，達到 100 時自動切換為 `success`。
 * 可強制指定 `status` 為 `error` 以顯示錯誤圖示；使用 `tick` 可在進度條上標記特定位置。
 *
 * @example
 * ```html
 * import { MznProgress } from '@mezzanine-ui/ng/progress';
 *
 * <div mznProgress [percent]="60" ></div>
 * <div mznProgress [percent]="75" type="percent" ></div>
 * <div mznProgress [percent]="40" status="error" type="icon" ></div>
 * <div mznProgress [percent]="60" [tick]="80" ></div>
 * ```
 */
@Component({
  selector: '[mznProgress]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon, MznTypography],
  host: {
    '[class]': 'hostClasses()',
    '[attr.icons]': 'null',
    '[attr.percent]': 'null',
    '[attr.percentProps]': 'null',
    '[attr.status]': 'null',
    '[attr.tick]': 'null',
    '[attr.type]': 'null',
  },
  template: `
    <div #lineRef [class]="classes.lineVariant">
      <i [class]="classes.lineBg" [style.width.%]="percentLimited()"></i>
    </div>
    @if (type() === 'percent') {
      <span
        mznTypography
        [variant]="percentProps()?.variant ?? 'input'"
        [align]="percentProps()?.align"
        [color]="percentProps()?.color"
        [display]="percentProps()?.display"
        [ellipsis]="percentProps()?.ellipsis ?? false"
        [noWrap]="percentProps()?.noWrap ?? false"
        [class]="classes.infoPercent"
        >{{ percentLimited() }}%</span
      >
    }
    @if (isSuccessStatus() || isErrorStatus()) {
      <i mznIcon [class]="classes.infoIcon" [icon]="icon()"></i>
    }
    @if (isActiveTick() && tickLeft()) {
      <div [class]="classes.tick" [style.--tick-position]="tickLeft()"></div>
    }
  `,
})
export class MznProgress implements AfterViewInit {
  protected readonly classes = classes;

  private readonly destroyRef = inject(DestroyRef);
  private readonly lineRef = viewChild<ElementRef<HTMLDivElement>>('lineRef');
  private readonly tickLeftSignal = signal<string | undefined>(undefined);

  /**
   * 自訂狀態圖示。
   */
  readonly icons = input<{
    readonly error?: IconDefinition;
    readonly success?: IconDefinition;
  }>();

  /**
   * 進度百分比（0～100）。
   * @default 0
   */
  readonly percent = input(0);

  /**
   * 百分比文字的排版屬性（status 為 enabled 時顯示）。
   */
  readonly percentProps = input<ProgressPercentProps>();

  /**
   * 強制指定進度狀態。未設定時依 percent 自動判斷
   * （percent < 100 ⇒ `enabled`，percent = 100 ⇒ `success`）。
   */
  readonly status = input<ProgressStatus>();

  /**
   * 進度條上的標記位置（0～100）。
   * @default 0
   */
  readonly tick = input(0);

  /**
   * 進度條顯示類型。
   * @default 'progress'
   */
  readonly type = input<ProgressType>('progress');

  protected readonly percentLimited = computed((): number =>
    Math.max(0, Math.min(100, this.percent())),
  );

  protected readonly resolvedStatus = computed((): ProgressStatus => {
    const explicit = this.status();

    if (explicit) return explicit;

    return this.percent() < 100
      ? ProgressStatuses.enabled
      : ProgressStatuses.success;
  });

  protected readonly icon = computed((): IconDefinition => {
    const icons = this.icons();

    if (this.resolvedStatus() === ProgressStatuses.success) {
      return icons?.success ?? CheckedFilledIcon;
    }

    return icons?.error ?? DangerousFilledIcon;
  });

  protected readonly isSuccessStatus = computed(
    (): boolean =>
      this.resolvedStatus() === ProgressStatuses.success &&
      this.type() === ProgressTypes.icon,
  );

  protected readonly isErrorStatus = computed(
    (): boolean =>
      this.resolvedStatus() === ProgressStatuses.error &&
      this.type() === ProgressTypes.icon,
  );

  protected readonly isActiveTick = computed((): boolean => {
    const t = this.tick();

    return t !== undefined && t > 0 && t < 100;
  });

  protected readonly tickPosition = computed((): number | undefined => {
    if (!this.isActiveTick()) return undefined;

    return Math.max(0, Math.min(100, this.tick()));
  });

  protected readonly tickLeft = computed((): string | undefined =>
    this.tickLeftSignal(),
  );

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.host,
      classes.type(this.type()),
      this.resolvedStatus() === ProgressStatuses.success && classes.success,
      this.resolvedStatus() === ProgressStatuses.error && classes.error,
    ),
  );

  ngAfterViewInit(): void {
    this.updateTickPosition();

    const onResize = (): void => {
      this.updateTickPosition();
    };

    window.addEventListener('resize', onResize);

    const lineEl = this.lineRef()?.nativeElement;
    const containerEl = lineEl?.parentElement;
    let resizeObserver: ResizeObserver | undefined;

    if (lineEl && containerEl && typeof ResizeObserver !== 'undefined') {
      resizeObserver = new ResizeObserver(() => this.updateTickPosition());
      resizeObserver.observe(lineEl);
      resizeObserver.observe(containerEl);
    }

    this.destroyRef.onDestroy(() => {
      window.removeEventListener('resize', onResize);
      resizeObserver?.disconnect();
    });
  }

  private updateTickPosition(): void {
    const pos = this.tickPosition();
    const lineEl = this.lineRef()?.nativeElement;
    const containerEl = lineEl?.parentElement;

    if (!this.isActiveTick() || pos === undefined || !lineEl || !containerEl) {
      this.tickLeftSignal.set(undefined);

      return;
    }

    const lineRect = lineEl.getBoundingClientRect();
    const containerRect = containerEl.getBoundingClientRect();
    const lineLeft = lineRect.left - containerRect.left;
    const tickOffsetInLine = (pos / 100) * lineRect.width;
    const tickAbsoluteLeft = lineLeft + tickOffsetInLine;
    const tickPercent = (tickAbsoluteLeft / containerRect.width) * 100;

    this.tickLeftSignal.set(`${tickPercent}%`);
  }
}
