// packages/vue/input/input.vue
<script setup lang="ts">
import { computed, nextTick, ref, useAttrs } from 'vue';
import type { CSSProperties } from 'vue';
import { inputClasses as classes } from '@mezzanine-ui/core/input';
import { textFieldClasses } from '@mezzanine-ui/core/text-field';
import { EyeIcon, EyeInvisibleIcon, SearchIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { formatNumberWithCommas } from '../_internal/format-number-with-commas';
import { parseNumberWithCommas } from '../_internal/parse-number-with-commas';
import { useInputWithClearControlValue } from '../_internal/use-input-with-clear-control-value';
import MznIcon from '../icon/icon.vue';
import MznTextField from '../text-field/text-field.vue';
import MznInputActionButton from './action-button.vue';
import MznPasswordStrengthIndicator from './password-strength-indicator.vue';
import MznInputSelectButton from './select-button.vue';
import MznInputSpinnerButton from './spinner-button.vue';
import type { InputProps } from './input.types';

/**
 * 多功能輸入框，以 `variant` 決定型態。
 *
 * 八種：`base`、`affix`（前後綴）、`search`（預設可清除、前綴放大鏡）、`number`（原生數字）、
 * `measure`（千分位格式化，可加上下微調）、`action`（旁邊一顆動作按鈕）、
 * `select`（旁邊一顆下拉按鈕）、`password`（可切換顯示，並可加強度指示條）。
 * `measure` 顯示時自動加千分位，`change` 送出的仍是原始數值。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInput } from '@mezzanine-ui/vue/input';
 * <\/script>
 *
 * <template>
 *   <MznInput clearable placeholder="請輸入文字" />
 *   <MznInput variant="search" placeholder="搜尋關鍵字" />
 *   <MznInput variant="measure" suffix="px" show-spinner :min="0" :max="100" />
 * </template>
 * ```
 *
 * @see MznTextField 外框容器
 * @see MznFormField 提供標籤與提示訊息的欄位容器
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<InputProps>(), {
  actionButton: undefined,
  active: undefined,
  clearable: undefined,
  defaultValue: undefined,
  disabled: false,
  dropdownMaxHeight: 114,
  dropdownPlacement: 'bottom-start',
  dropdownWidth: 120,
  error: false,
  forceShowClearable: undefined,
  formatter: undefined,
  fullWidth: true,
  hideSuffixWhenClearable: undefined,
  id: undefined,
  inputProps: undefined,
  inputType: undefined,
  max: undefined,
  min: undefined,
  name: undefined,
  options: undefined,
  parser: undefined,
  passwordStrengthIndicator: undefined,
  placeholder: undefined,
  readonly: undefined,
  selectButton: undefined,
  selectedValue: undefined,
  showPasswordStrengthIndicator: undefined,
  showSpinner: undefined,
  size: 'main',
  step: 1,
  typing: undefined,
  value: undefined,
  variant: 'base',
  warning: undefined,
});

const emit = defineEmits<{
  change: [event: Event];
  clear: [event: MouseEvent];
  select: [value: string];
  spinDown: [];
  spinUp: [];
}>();

const slots = defineSlots<{
  /** The field's prefix, for `variant="affix"` and `variant="measure"`. */
  prefix?: () => unknown;
  /** The field's suffix, for `variant="affix"` and `variant="measure"`. */
  suffix?: () => unknown;
}>();

const attrs = useAttrs();

const input = ref<HTMLInputElement | null>(null);
const showPassword = ref(false);

/**
 * React hands the input out through an `inputRef` prop; Vue's equivalent is
 * the parent placing a `ref` on this component, so the element is exposed.
 */
defineExpose({ input });

const {
  onChange,
  onClear: onClearFromHook,
  value,
} = useInputWithClearControlValue({
  defaultValue: () => props.defaultValue,
  elementRef: input,
  onChange: (event) => emit('change', event),
  value: () => props.value,
});

// Handle formatter/parser logic
const formatter = computed((): ((value: string) => string) | undefined => {
  if (props.formatter) return props.formatter;

  if (props.variant === 'measure') {
    return (raw: string) => formatNumberWithCommas(raw);
  }

  return undefined;
});

const parser = computed((): ((value: string) => string) | undefined => {
  if (props.parser) return props.parser;

  if (props.variant === 'measure') {
    return (raw: string) => parseNumberWithCommas(raw)?.toString() ?? '';
  }

  return undefined;
});

function handleChange(event: Event): void {
  restoreControlledValue();

  if (!parser.value) {
    onChange(event);

    return;
  }

  const target = event.target as HTMLInputElement;
  const parsed = parser.value(target.value);
  const originalValue = target.value;

  // Report the parsed value the way React rebuilds the event with it.
  target.value = parsed;
  onChange(event);
  target.value = originalValue;
}

/**
 * React re-renders a controlled input on every change and resets the element's
 * value even when the `value` prop did not move, so text typed into an input
 * whose value is pinned disappears again. Vue skips the patch when the bound
 * value is unchanged, leaving the typed text on screen, so it is put back here.
 */
function restoreControlledValue(): void {
  nextTick(() => {
    if (input.value && input.value.value !== displayValue.value) {
      input.value.value = displayValue.value;
    }
  });
}

// Format the display value
const displayValue = computed((): string =>
  formatter.value ? formatter.value(value.value) : value.value,
);

const isSearch = computed((): boolean => props.variant === 'search');
const isMeasure = computed((): boolean => props.variant === 'measure');
const isPassword = computed((): boolean => props.variant === 'password');

const hasSpinner = computed(
  (): boolean => isMeasure.value && Boolean(props.showSpinner),
);

const clearable = computed((): boolean => {
  if (isSearch.value) {
    // 預設為可清除
    return typeof props.clearable !== 'undefined' ? props.clearable : true;
  }

  if (
    props.variant === 'base' ||
    props.variant === 'affix' ||
    isPassword.value
  ) {
    return Boolean(props.clearable);
  }

  return false;
});

const defaultInputType = computed((): string => {
  if (props.variant === 'number') return 'number';
  if (isPassword.value) return showPassword.value ? 'text' : 'password';

  return 'text';
});

const defaultInputProps = computed((): Record<string, unknown> => {
  if (props.variant === 'number' || isMeasure.value) {
    return { max: props.max, min: props.min, step: props.step };
  }

  return {};
});

// 預設置右對齊
const inputStyle = computed((): CSSProperties | undefined =>
  isMeasure.value ? { textAlign: 'right' } : undefined,
);

function handleSpin(direction: 1 | -1): void {
  const currentValue = parseFloat(value.value || '0');
  const newValue = currentValue + direction * props.step;
  const withinBounds =
    direction === 1
      ? typeof props.max === 'undefined' || newValue <= props.max
      : typeof props.min === 'undefined' || newValue >= props.min;

  if (withinBounds) {
    // React hands the hook a synthetic event carrying only the new value;
    // the rendered value comes from state either way.
    onChange({ target: { value: String(newValue) } } as unknown as Event);
  }

  if (direction === 1) {
    emit('spinUp');
  } else {
    emit('spinDown');
  }
}

const actionButtonProps = computed(() => {
  if (props.variant !== 'action' || !props.actionButton) return undefined;

  const { position: _position, ...rest } = props.actionButton;

  return {
    ...rest,
    disabled:
      typeof rest.disabled === 'boolean'
        ? rest.disabled
        : props.disabled || props.readonly,
    size: props.size,
  };
});

const selectButtonProps = computed(() => {
  if (props.variant !== 'select' || !props.selectButton) return undefined;

  const { position: _position, ...rest } = props.selectButton;

  return {
    ...rest,
    disabled: rest.disabled || props.disabled,
    dropdownMaxHeight: props.dropdownMaxHeight,
    dropdownPlacement: props.dropdownPlacement,
    dropdownWidth: props.dropdownWidth,
    options: props.options,
    size: props.size,
  };
});

const prefixExternalButton = computed((): boolean => {
  if (props.variant === 'action') {
    return props.actionButton?.position === 'prefix';
  }

  if (props.variant === 'select') {
    return (
      props.selectButton?.position === 'both' ||
      props.selectButton?.position === 'prefix'
    );
  }

  return false;
});

const suffixExternalButton = computed((): boolean => {
  if (props.variant === 'action') {
    return props.actionButton?.position === 'suffix';
  }

  if (props.variant === 'select') {
    return (
      props.selectButton?.position === 'both' ||
      props.selectButton?.position === 'suffix'
    );
  }

  return false;
});

const showPasswordStrengthIndicator = computed(
  (): boolean =>
    isPassword.value && Boolean(props.showPasswordStrengthIndicator),
);

function togglePassword(): void {
  showPassword.value = !showPassword.value;
}

function handlePasswordToggleKeyDown(event: KeyboardEvent): void {
  if (event.key === 'Enter' || event.key === ' ') {
    event.preventDefault();
    togglePassword();
  }
}

function handleClear(event: MouseEvent): void {
  emit('clear', event);
  onClearFromHook(event);
}

const interactiveProps = computed(() => {
  if (props.disabled) return { disabled: true as const };
  if (props.readonly) return { readonly: true as const };
  if (props.typing) return { typing: true as const };

  return {};
});

const containerClasses = computed((): string =>
  clsx(classes.container, attrs.class as string),
);

const hostClasses = computed((): string =>
  clsx(classes.host, {
    [classes.number]: props.variant === 'number',
    [classes.passwordInput]: isPassword.value,
    [classes.withPrefixExternalAction]: prefixExternalButton.value,
    [classes.withSuffixExternalAction]: suffixExternalButton.value,
    [classes.searchInput]: isSearch.value,
    [classes.measureWithSpinner]: isMeasure.value && hasSpinner.value,
    [classes.measureWithoutSpinner]: isMeasure.value && !hasSpinner.value,
  }),
);

const fieldClasses = computed((): string =>
  clsx(
    classes.field,
    {
      [classes.number]: props.variant === 'number',
      [textFieldClasses.monoInput]: isMeasure.value,
      [textFieldClasses.tinyGap]: isMeasure.value && hasSpinner.value,
    },
    classes.size(props.size),
  ),
);

const indicatorClasses = computed((): string =>
  clsx(classes.indicatorContainer),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});

const hasPrefixSlot = computed((): boolean =>
  Boolean(slots.prefix && (props.variant === 'affix' || isMeasure.value)),
);

const hasSuffixSlot = computed((): boolean =>
  Boolean(slots.suffix && (props.variant === 'affix' || isMeasure.value)),
);

const spinnersClass = classes.spinners;
</script>

<template>
  <div v-bind="forwardedAttrs" :class="containerClasses">
    <div :class="hostClasses">
      <MznInputActionButton
        v-if="prefixExternalButton && actionButtonProps"
        v-bind="actionButtonProps"
      />
      <MznInputSelectButton
        v-if="prefixExternalButton && selectButtonProps"
        v-bind="selectButtonProps"
        @select="emit('select', $event)"
      />
      <MznTextField
        v-bind="interactiveProps"
        :active="active"
        :class="fieldClasses"
        :clearable="clearable"
        :error="error"
        :force-show-clearable="forceShowClearable"
        :full-width="fullWidth"
        :hide-suffix-when-clearable="hideSuffixWhenClearable"
        role="presentation"
        :size="size"
        :warning="warning"
        @clear="handleClear"
      >
        <template v-if="isSearch || hasPrefixSlot" #prefix>
          <MznIcon v-if="isSearch" :icon="SearchIcon" />
          <slot v-else name="prefix" />
        </template>
        <template
          v-if="hasSuffixSlot || (isMeasure && hasSpinner) || isPassword"
          #suffix
        >
          <slot v-if="hasSuffixSlot" name="suffix" />
          <div v-if="isMeasure && hasSpinner" :class="spinnersClass">
            <MznInputSpinnerButton
              :disabled="disabled"
              :size="size"
              type="up"
              @click="handleSpin(1)"
            />
            <MznInputSpinnerButton
              :disabled="disabled"
              :size="size"
              type="down"
              @click="handleSpin(-1)"
            />
          </div>
          <MznIcon
            v-if="isPassword"
            :aria-label="showPassword ? 'Hide password' : 'Show password'"
            :icon="showPassword ? EyeIcon : EyeInvisibleIcon"
            role="button"
            :tabindex="0"
            @click="togglePassword"
            @keydown="handlePasswordToggleKeyDown"
          />
        </template>
        <input
          ref="input"
          v-bind="{ ...defaultInputProps, ...inputProps }"
          :aria-disabled="disabled"
          :aria-multiline="false"
          :aria-readonly="readonly"
          :disabled="disabled"
          :id="id"
          :name="name"
          :placeholder="placeholder"
          :readonly="readonly"
          :style="[inputStyle, inputProps?.style]"
          :type="inputType ?? defaultInputType"
          :value="displayValue"
          @input="handleChange"
        />
      </MznTextField>
      <MznInputActionButton
        v-if="suffixExternalButton && actionButtonProps"
        v-bind="actionButtonProps"
      />
      <MznInputSelectButton
        v-if="suffixExternalButton && selectButtonProps"
        v-bind="selectButtonProps"
        @select="emit('select', $event)"
      />
    </div>
    <MznPasswordStrengthIndicator
      v-if="showPasswordStrengthIndicator"
      v-bind="passwordStrengthIndicator"
      :class="indicatorClasses"
    />
  </div>
</template>

// packages/ng/input/input.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  ElementRef,
  input,
  OnInit,
  output,
  signal,
  viewChild,
} from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DropdownOption } from '@mezzanine-ui/core/dropdown';
import { inputClasses as classes } from '@mezzanine-ui/core/input';
import { textFieldClasses } from '@mezzanine-ui/core/text-field';
import { type Placement } from '@floating-ui/dom';
import { EyeIcon, EyeInvisibleIcon, SearchIcon } from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';
import { MznTextField } from '@mezzanine-ui/ng/text-field';
import {
  formatNumberWithCommas,
  parseNumberWithCommas,
  provideValueAccessor,
} from '@mezzanine-ui/ng/utils';
import { MznInputSpinnerButton } from './spinner-button.component';
import { MznInputActionButton } from './action-button.component';
import { MznInputSelectButton } from './select-button.component';
import { MznPasswordStrengthIndicator } from './password-strength-indicator.component';

/** Input 的變體類型。 */
export type InputVariant =
  | 'base'
  | 'affix'
  | 'action'
  | 'measure'
  | 'number'
  | 'password'
  | 'search'
  | 'select';

/**
 * 多功能輸入框元件，支援 base、affix、search、password、measure、action 等多種變體。
 *
 * 實作 `ControlValueAccessor`，可搭配 Angular Reactive Forms 或 Template-driven Forms。
 * `search` 變體預設帶搜尋圖示與清除按鈕；`password` 變體提供密碼可見性切換及強度指示器；
 * `measure` 變體支援 Spinner 微調按鈕；`action` 變體支援外部動作按鈕。
 *
 * @example
 * ```html
 * import { MznInput } from '@mezzanine-ui/ng/input';
 *
 * <div mznInput placeholder="請輸入" ></div>
 * <div mznInput variant="search" placeholder="搜尋" ></div>
 * <div mznInput variant="password" placeholder="密碼" ></div>
 * <div mznInput variant="affix" prefixText="$" suffixText=".00" ></div>
 * <div mznInput variant="measure" suffixText="px" [showSpinner]="true" ></div>
 * ```
 */
@Component({
  selector: '[mznInput]',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    MznIcon,
    MznInputActionButton,
    MznInputSelectButton,
    MznInputSpinnerButton,
    MznPasswordStrengthIndicator,
    MznTextField,
  ],
  providers: [provideValueAccessor(MznInput)],
  host: {
    '[class]': 'containerClasses()',
    '[style.display]': '"block"',
    '[attr.externalValue]': 'null',
    '[attr.active]': 'null',
    '[attr.actionButton]': 'null',
    '[attr.clearable]': 'null',
    '[attr.defaultValue]': 'null',
    '[attr.selectButton]': 'null',
    '[attr.selectOptions]': 'null',
    '[attr.dropdownWidth]': 'null',
    '[attr.dropdownMaxHeight]': 'null',
    '[attr.dropdownPlacement]': 'null',
    '[attr.disabled]': 'null',
    '[attr.error]': 'null',
    '[attr.fullWidth]': 'null',
    '[attr.formatter]': 'null',
    '[attr.inputId]': 'null',
    '[attr.inputName]': 'null',
    '[attr.inputType]': 'null',
    '[attr.max]': 'null',
    '[attr.min]': 'null',
    '[attr.parser]': 'null',
    '[attr.placeholder]': 'null',
    '[attr.prefixIcon]': 'null',
    '[attr.prefixText]': 'null',
    '[attr.passwordStrengthIndicator]': 'null',
    '[attr.readonlyState]': 'null',
    '[attr.size]': 'null',
    '[attr.showPasswordStrengthIndicator]': 'null',
    '[attr.showSpinner]': 'null',
    '[attr.step]': 'null',
    '[attr.suffixText]': 'null',
    '[attr.typing]': 'null',
    '[attr.variant]': 'null',
  },
  template: `
    <div [class]="hostClasses()">
      @if (actionButtonPosition() === 'prefix') {
        <div
          mznInputActionButton
          [disabled]="actionButtonDisabled()"
          [icon]="actionButton()?.icon"
          [label]="actionButton()?.label ?? 'Copy'"
          [size]="size()"
          (clicked)="actionButton()?.onClick?.()"
        ></div>
      }
      @if (
        selectButtonPosition() === 'prefix' || selectButtonPosition() === 'both'
      ) {
        <div
          mznInputSelectButton
          [disabled]="selectButton()?.disabled || disabled()"
          [dropdownMaxHeight]="dropdownMaxHeight()"
          [dropdownPlacement]="dropdownPlacement()"
          [dropdownWidth]="dropdownWidth()"
          [options]="selectOptions()"
          [size]="size()"
          [value]="selectButton()?.value"
          (selected)="onSelectOption($event)"
        ></div>
      }
      <div
        mznTextField
        [active]="active()"
        [class]="fieldClasses()"
        [clearable]="isClearable()"
        [disabled]="disabled()"
        [error]="error()"
        [fullWidth]="fullWidth()"
        [hasPrefix]="!!resolvedPrefix()"
        [hasSuffix]="
          !!resolvedSuffix() || (showSpinner() && variant() === 'measure')
        "
        [readonly]="readonlyState()"
        [size]="size()"
        [typing]="typing()"
        (cleared)="onClear()"
      >
        @if (resolvedPrefix(); as pfx) {
          <span prefix [class]="textFieldClasses.prefix">
            @if (pfx === 'search-icon') {
              <i mznIcon [icon]="searchIcon"></i>
            } @else if (pfx === 'prefix-icon') {
              <i mznIcon [icon]="prefixIcon()!"></i>
            } @else {
              {{ pfx }}
            }
          </span>
        }
        <input
          #inputEl
          [attr.id]="inputId()"
          [attr.name]="inputName()"
          [attr.placeholder]="placeholder()"
          [attr.aria-disabled]="disabled()"
          [attr.aria-multiline]="false"
          [attr.aria-readonly]="readonlyState()"
          [attr.min]="min()"
          [attr.max]="max()"
          [attr.step]="step()"
          [disabled]="disabled()"
          [readOnly]="readonlyState()"
          [type]="resolvedInputType()"
          [style.text-align]="inputTextAlign()"
          [value]="displayValue()"
          (input)="onInput($event)"
          (blur)="onBlur()"
        />
        @if (showSpinner() && variant() === 'measure') {
          <span suffix>
            @if (resolvedSuffix(); as sfx) {
              {{ sfx }}
            }
            <div [class]="classes.spinners">
              <div
                mznInputSpinnerButton
                type="up"
                [size]="size()"
                [disabled]="disabled()"
                (clicked)="onSpinUp()"
              ></div>
              <div
                mznInputSpinnerButton
                type="down"
                [size]="size()"
                [disabled]="disabled()"
                (clicked)="onSpinDown()"
              ></div>
            </div>
          </span>
        } @else if (resolvedSuffix(); as sfx) {
          <span suffix [class]="textFieldClasses.suffix">
            @if (sfx === 'password-toggle') {
              <i
                mznIcon
                [clickable]="true"
                [icon]="showPassword() ? eyeIcon : eyeInvisibleIcon"
                (click)="togglePassword()"
                role="button"
                tabindex="0"
                [attr.aria-label]="
                  showPassword() ? 'Hide password' : 'Show password'
                "
                (keydown.enter)="togglePassword()"
                (keydown.space)="togglePassword(); $event.preventDefault()"
              ></i>
            } @else {
              {{ sfx }}
            }
          </span>
        }
      </div>
      @if (actionButtonPosition() === 'suffix') {
        <div
          mznInputActionButton
          [disabled]="actionButtonDisabled()"
          [icon]="actionButton()?.icon"
          [label]="actionButton()?.label ?? 'Copy'"
          [size]="size()"
          (clicked)="actionButton()?.onClick?.()"
        ></div>
      }
      @if (
        selectButtonPosition() === 'suffix' || selectButtonPosition() === 'both'
      ) {
        <div
          mznInputSelectButton
          [disabled]="selectButton()?.disabled || disabled()"
          [dropdownMaxHeight]="dropdownMaxHeight()"
          [dropdownPlacement]="dropdownPlacement()"
          [dropdownWidth]="dropdownWidth()"
          [options]="selectOptions()"
          [size]="size()"
          [value]="selectButton()?.value"
          (selected)="onSelectOption($event)"
        ></div>
      }
    </div>
    @if (showPasswordStrengthIndicator() && variant() === 'password') {
      <div [class]="classes.indicatorContainer">
        <div
          mznPasswordStrengthIndicator
          [strength]="passwordStrengthIndicator()?.strength ?? 'weak'"
          [strengthText]="passwordStrengthIndicator()?.strengthText"
          [strengthTextPrefix]="
            passwordStrengthIndicator()?.strengthTextPrefix ?? '密碼強度：'
          "
          [hintTexts]="passwordStrengthIndicator()?.hintTexts"
        ></div>
      </div>
    }
  `,
})
export class MznInput implements ControlValueAccessor, OnInit {
  protected readonly textFieldClasses = textFieldClasses;
  protected readonly classes = classes;
  protected readonly searchIcon = SearchIcon;
  protected readonly eyeIcon = EyeIcon;
  protected readonly eyeInvisibleIcon = EyeInvisibleIcon;

  private readonly inputEl = viewChild<ElementRef<HTMLInputElement>>('inputEl');

  private onChangeFn: (value: string) => void = () => {};
  private onTouchedFn: () => void = () => {};

  /**
   * 輸入值，可透過模板綁定 `[value]="..."` 或 `value="..."` 設定。
   * 同時支援 ControlValueAccessor（Reactive Forms / ngModel）。
   *
   * Controlled mode：parent 透過 `[value]` 控制顯示值，需監聽 `(valueChange)` 更新。
   * Uncontrolled mode：不綁定 `[value]`，透過 CVA 或直接輸入管理值。
   */
  readonly externalValue = input<string | undefined>(undefined, {
    alias: 'value',
  });

  /** 內部值 signal — 用於 uncontrolled mode 和 CVA。 */
  protected readonly internalValue = signal('');

  protected readonly showPassword = signal(false);

  /**
   * 是否處於 active 狀態。
   * @default false
   */
  readonly active = input(false);

  /**
   * 外部動作按鈕設定（action 變體用）。
   * `position` 決定按鈕在輸入框前（'prefix'）或後（'suffix'）。
   */
  readonly actionButton = input<{
    readonly position?: 'prefix' | 'suffix';
    readonly icon?: IconDefinition;
    readonly label?: string;
    readonly disabled?: boolean;
    readonly onClick?: () => void;
  }>();

  /**
   * 是否可清除。search 變體預設為 true，其餘預設為 false。
   */
  readonly clearable = input<boolean>();

  /**
   * 初始預設值（uncontrolled 模式）。
   * 僅在元件初始化時生效，若同時提供 `[value]` 則 `defaultValue` 無效。
   * 對應 React 的 `defaultValue` prop。
   */
  readonly defaultValue = input<string>();

  /**
   * 選擇按鈕設定（select 變體用）。
   * `position` 決定按鈕在 'prefix'、'suffix' 或 'both'（兩端皆顯示）。
   */
  readonly selectButton = input<{
    readonly position?: 'prefix' | 'suffix' | 'both';
    readonly disabled?: boolean;
    readonly value?: string;
    readonly onClick?: () => void;
  }>();

  /**
   * 下拉選單的選項列表（select 變體用）。
   */
  readonly selectOptions = input<ReadonlyArray<DropdownOption>>();

  /**
   * 下拉選單的固定寬度（select 變體用）。
   * @default 120
   */
  readonly dropdownWidth = input<number | string>(120);

  /**
   * 下拉選單的最大高度（select 變體用）。
   * @default 114
   */
  readonly dropdownMaxHeight = input<number | string>(114);

  /**
   * 下拉選單的定位方向（select 變體用）。
   * @default 'bottom-start'
   */
  readonly dropdownPlacement = input<Placement>('bottom-start');

  /**
   * 是否停用。
   * @default false
   */
  readonly disabled = input(false);

  /**
   * 是否為錯誤狀態。
   * @default false
   */
  readonly error = input(false);

  /**
   * 是否全寬。
   * @default true
   */
  readonly fullWidth = input(true);

  /**
   * 數值格式化函式，將內部值轉換為顯示文字（measure / number 變體用）。
   */
  readonly formatter = input<(value: string) => string>();

  /** input 的 id 屬性。 */
  readonly inputId = input<string>();

  /** input 的 name 屬性。 */
  readonly inputName = input<string>();

  /**
   * input 的原生 type 屬性。
   */
  readonly inputType = input<string>();

  /**
   * 最大值（measure / number 變體用）。
   */
  readonly max = input<number>();

  /**
   * 最小值（measure / number 變體用）。
   */
  readonly min = input<number>();

  /**
   * 數值解析函式，將顯示文字轉換回原始值（measure / number 變體用）。
   */
  readonly parser = input<(value: string) => string>();

  /** 佔位文字。 */
  readonly placeholder = input<string>();

  /**
   * 前綴圖示（affix 變體用），優先於 `prefixText`。
   */
  readonly prefixIcon = input<IconDefinition>();

  /** 前綴文字（affix 變體用）。 */
  readonly prefixText = input<string>();

  /**
   * 密碼強度指示器設定（password 變體 + showPasswordStrengthIndicator 為 true 時使用）。
   */
  readonly passwordStrengthIndicator = input<{
    readonly strength?: 'weak' | 'medium' | 'strong';
    readonly strengthText?: string;
    readonly strengthTextPrefix?: string;
    readonly hintTexts?: readonly {
      severity: 'error' | 'info' | 'success' | 'warning';
      hint: string;
    }[];
  }>();

  /**
   * 是否唯讀。
   * @default false
   */
  readonly readonlyState = input(false, { alias: 'readonly' });

  /**
   * 欄位尺寸。
   * @default 'main'
   */
  readonly size = input<'main' | 'sub'>('main');

  /**
   * 是否顯示密碼強度指示器（password 變體用）。
   * @default false
   */
  readonly showPasswordStrengthIndicator = input(false);

  /**
   * 是否顯示 Spinner 微調按鈕（measure 變體用）。
   * @default false
   */
  readonly showSpinner = input(false);

  /**
   * 步進值（measure / number 變體用）。
   * @default 1
   */
  readonly step = input<number>();

  /** 後綴文字（affix / measure 變體用）。 */
  readonly suffixText = input<string>();

  /**
   * 是否正在輸入（覆蓋 TextField 的自動偵測）。
   */
  readonly typing = input<boolean>();

  /**
   * 輸入框變體。
   * @default 'base'
   */
  readonly variant = input<InputVariant>('base');

  /** 值變更事件。 */
  readonly valueChange = output<string>();

  /** Spinner 往上微調事件（measure 變體用）。 */
  readonly spinUp = output<void>();

  /** Spinner 往下微調事件（measure 變體用）。 */
  readonly spinDown = output<void>();

  /** 下拉選項選取事件（select 變體用）。 */
  readonly selectOptionSelected = output<DropdownOption>();

  protected readonly isClearable = computed((): boolean => {
    const v = this.variant();

    if (v === 'search') return this.clearable() !== false;

    return this.clearable() ?? false;
  });

  protected readonly resolvedInputType = computed((): string => {
    const custom = this.inputType();

    if (custom) return custom;

    if (this.variant() === 'password') {
      return this.showPassword() ? 'text' : 'password';
    }

    if (this.variant() === 'number') {
      return 'number';
    }

    return 'text';
  });

  protected readonly resolvedPrefix = computed((): string | null => {
    if (this.variant() === 'search') return 'search-icon';

    const icon = this.prefixIcon();

    if (icon) return 'prefix-icon';

    const text = this.prefixText();

    return text ?? null;
  });

  protected readonly resolvedSuffix = computed((): string | null => {
    if (this.variant() === 'password') return 'password-toggle';

    const text = this.suffixText();

    return text ?? null;
  });

  /** 解析後的當前值（externalValue 優先、internalValue 為 fallback）。 */
  protected readonly resolvedValue = computed((): string => {
    const external = this.externalValue();

    return external !== undefined ? external : this.internalValue();
  });

  protected readonly displayValue = computed((): string => {
    const fmt = this.formatter();
    const raw = this.resolvedValue();

    if (fmt) return fmt(raw);

    if (this.variant() === 'measure' && raw !== '') {
      const n = Number(raw);

      if (!Number.isNaN(n)) return formatNumberWithCommas(n);
    }

    return raw;
  });

  protected readonly containerClasses = computed((): string =>
    clsx(classes.container),
  );

  protected readonly hostClasses = computed((): string => {
    const sbPos = this.selectButtonPosition();
    const hasPrefixExternal =
      this.actionButtonPosition() === 'prefix' ||
      sbPos === 'prefix' ||
      sbPos === 'both';
    const hasSuffixExternal =
      this.actionButtonPosition() === 'suffix' ||
      sbPos === 'suffix' ||
      sbPos === 'both';

    return clsx(classes.host, {
      [classes.number]: this.variant() === 'number',
      [classes.passwordInput]: this.variant() === 'password',
      [classes.searchInput]: this.variant() === 'search',
      [classes.measureWithSpinner]:
        this.variant() === 'measure' && this.showSpinner(),
      [classes.measureWithoutSpinner]:
        this.variant() === 'measure' && !this.showSpinner(),
      [classes.withPrefixExternalAction]: hasPrefixExternal,
      [classes.withSuffixExternalAction]: hasSuffixExternal,
    });
  });

  protected readonly fieldClasses = computed((): string =>
    clsx(
      classes.field,
      {
        [classes.number]: this.variant() === 'number',
        [textFieldClasses.monoInput]: this.variant() === 'measure',
        [textFieldClasses.tinyGap]:
          this.variant() === 'measure' && this.showSpinner(),
      },
      classes.size(this.size()),
    ),
  );

  protected readonly inputTextAlign = computed((): string | null =>
    this.variant() === 'measure' ? 'right' : null,
  );

  protected readonly actionButtonPosition = computed(
    (): 'prefix' | 'suffix' | null => {
      const ab = this.actionButton();

      if (!ab) return null;

      return ab.position ?? null;
    },
  );

  protected readonly actionButtonDisabled = computed((): boolean => {
    const ab = this.actionButton();

    if (typeof ab?.disabled === 'boolean') return ab.disabled;

    return this.disabled() || this.readonlyState();
  });

  protected readonly selectButtonPosition = computed(
    (): 'prefix' | 'suffix' | 'both' | null => {
      const sb = this.selectButton();

      if (!sb) return null;

      return sb.position ?? null;
    },
  );

  // ControlValueAccessor
  writeValue(value: string | null): void {
    this.internalValue.set(value ?? '');
  }

  registerOnChange(fn: (value: string) => void): void {
    this.onChangeFn = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedFn = fn;
  }

  setDisabledState?(_isDisabled: boolean): void {
    // Disabled state is managed via the `disabled` input
  }

  ngOnInit(): void {
    // Set internalValue from defaultValue if no external value is bound
    const dv = this.defaultValue();

    if (dv !== undefined && this.externalValue() === undefined) {
      this.internalValue.set(dv);
    }
  }

  protected onInput(event: Event): void {
    const target = event.target as HTMLInputElement;
    const rawValue = target.value;
    const parse = this.parser();
    let newValue: string;

    if (parse) {
      newValue = parse(rawValue);
    } else if (this.variant() === 'measure') {
      newValue = String(parseNumberWithCommas(rawValue));
    } else {
      newValue = rawValue;
    }

    this.internalValue.set(newValue);
    this.onChangeFn(newValue);
    this.valueChange.emit(newValue);

    // Force-sync native input to formatted display value.
    // When the parsed value doesn't change (e.g. typing "a" into empty field
    // → parser returns "" which is already the current value), Angular skips
    // the DOM update because the signal didn't change. We must imperatively
    // set the native input value so invalid characters are stripped.
    const formatted = this.displayValue();

    if (target.value !== formatted) {
      target.value = formatted;
    }
  }

  protected onBlur(): void {
    this.onTouchedFn();
  }

  protected onClear(): void {
    this.internalValue.set('');
    this.onChangeFn('');
    this.valueChange.emit('');

    const el = this.inputEl()?.nativeElement;

    if (el) {
      el.value = '';
      el.focus();
    }
  }

  protected togglePassword(): void {
    this.showPassword.update((v) => !v);
  }

  protected updateValue(newVal: string): void {
    this.internalValue.set(newVal);
    this.onChangeFn(newVal);
    this.valueChange.emit(newVal);
  }

  protected onSpinUp(): void {
    const val = parseFloat(this.resolvedValue() || '0');
    const step = this.step() ?? 1;
    const max = this.max();
    const newVal = max != null ? Math.min(val + step, max) : val + step;

    this.updateValue(String(newVal));
    this.spinUp.emit();
  }

  protected onSpinDown(): void {
    const val = parseFloat(this.resolvedValue() || '0');
    const step = this.step() ?? 1;
    const min = this.min();
    const newVal = min != null ? Math.max(val - step, min) : val - step;

    this.updateValue(String(newVal));
    this.spinDown.emit();
  }

  protected onSelectOption(option: DropdownOption): void {
    this.selectOptionSelected.emit(option);
  }
}
