// packages/vue/input/spinner-button.vue
<script setup lang="ts">
import { computed, useAttrs } from 'vue';
import { inputSpinnerButtonClasses as classes } from '@mezzanine-ui/core/input';
import { CaretDownFlatIcon, CaretUpFlatIcon } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import MznIcon from '../icon/icon.vue';
import type { SpinnerButtonProps } from './spinner-button.types';

/**
 * 數值輸入框的上下微調按鈕。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznInputSpinnerButton } from '@mezzanine-ui/vue/input';
 * <\/script>
 *
 * <template>
 *   <MznInputSpinnerButton type="up" @click="increase" />
 * </template>
 * ```
 *
 * @see MznInput `variant="measure"` 且 `showSpinner` 時會渲染這兩顆按鈕
 */
defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<SpinnerButtonProps>(), {
  disabled: undefined,
  size: 'main',
});

const attrs = useAttrs();

const label = computed((): string =>
  props.type === 'up' ? 'Increase value' : 'Decrease value',
);

const icon = computed(() =>
  props.type === 'up' ? CaretUpFlatIcon : CaretDownFlatIcon,
);

const hostClasses = computed((): string =>
  clsx(
    classes.host,
    props.disabled && classes.disabled,
    props.size === 'main' ? classes.main : classes.sub,
    attrs.class as string,
  ),
);

const forwardedAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;

  return rest;
});
</script>

<template>
  <button
    :aria-label="label"
    :class="hostClasses"
    :disabled="disabled"
    :title="label"
    type="button"
    v-bind="forwardedAttrs"
  >
    <MznIcon aria-hidden="true" :icon="icon" />
  </button>
</template>

// packages/ng/input/spinner-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  output,
} from '@angular/core';
import { inputSpinnerButtonClasses as classes } from '@mezzanine-ui/core/input';
import { CaretDownFlatIcon, CaretUpFlatIcon } from '@mezzanine-ui/icons';
import type { IconDefinition } from '@mezzanine-ui/icons';
import clsx from 'clsx';
import { MznIcon } from '@mezzanine-ui/ng/icon';

/**
 * 數字微調按鈕元件，提供上/下箭頭，搭配數字輸入框使用。
 *
 * `type` 決定方向：`'up'` 顯示向上箭頭，`'down'` 顯示向下箭頭。
 *
 * @example
 * ```html
 * import { MznInputSpinnerButton } from '@mezzanine-ui/ng/input';
 *
 * <mzn-input-spinner-button type="up" (clicked)="onIncrement()" />
 * <mzn-input-spinner-button type="down" (clicked)="onDecrement()" />
 * ```
 */
@Component({
  selector: 'mzn-input-spinner-button',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MznIcon],
  host: {
    style: 'display: contents',
  },
  template: `
    <button
      type="button"
      [class]="hostClasses()"
      [disabled]="disabled()"
      [attr.aria-label]="ariaLabel()"
      [title]="ariaLabel()"
      (click)="clicked.emit()"
    >
      <i mznIcon aria-hidden="true" [icon]="resolvedIcon()"></i>
    </button>
  `,
})
export class MznInputSpinnerButton {
  /**
   * 是否停用。
   * @default false
   */
  readonly disabled = input(false);

  /**
   * 按鈕尺寸。
   * @default 'main'
   */
  readonly size = input<'main' | 'sub'>('main');

  /**
   * 按鈕方向類型。
   */
  readonly type = input.required<'up' | 'down'>();

  /** 點擊事件。 */
  readonly clicked = output<void>();

  protected readonly resolvedIcon = computed(
    (): IconDefinition =>
      this.type() === 'up' ? CaretUpFlatIcon : CaretDownFlatIcon,
  );

  protected readonly ariaLabel = computed((): string =>
    this.type() === 'up' ? 'Increase value' : 'Decrease value',
  );

  protected readonly hostClasses = computed((): string =>
    clsx(
      classes.host,
      this.disabled() && classes.disabled,
      this.size() === 'main' ? classes.main : classes.sub,
    ),
  );
}
