// packages/vue/select/select-trigger-tags.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { selectClasses as classes } from '@mezzanine-ui/core/select';
import clsx from 'clsx';
import MznOverflowCounterTag from '../overflow-tooltip/overflow-counter-tag.vue';
import MznTag from '../tag/tag.vue';
import MznTagGroup from '../tag/tag-group.vue';
import type { SelectValue } from './select.types';
import type { SelectTriggerTagsProps } from './select-trigger-tags.types';
import { useSelectTriggerTags } from './use-select-trigger-tags';

/**
 * 多選 Select 觸發器裡的標籤列。
 *
 * `overflowStrategy="counter"` 時只顯示放得下的標籤，其餘收進計數標籤；
 * `"wrap"` 時全部換行顯示。`showTextInputAfterTags` 會在標籤後補一個搜尋輸入框。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznSelectTriggerTags } from '@mezzanine-ui/vue/select';
 * <\/script>
 *
 * <template>
 *   <MznSelectTriggerTags overflow-strategy="counter" :value="selections" @tag-close="remove" />
 * </template>
 * ```
 *
 * @see MznSelectTrigger 放置這個標籤列的觸發器
 */
const props = withDefaults(defineProps<SelectTriggerTagsProps>(), {
  disabled: undefined,
  inputProps: undefined,
  readOnly: undefined,
  required: undefined,
  searchText: undefined,
  showTextInputAfterTags: undefined,
  size: undefined,
  value: () => [],
});

const emit = defineEmits<{
  /** The click handler for the cross icon on tags. */
  tagClose: [target: SelectValue];
}>();

const wrapper = ref<HTMLElement | null>(null);
const tags = ref<HTMLElement | null>(null);

const { FakeTags, overflowSelections, visibleSelections } =
  useSelectTriggerTags({
    containerRef: wrapper,
    enabled: () => props.overflowStrategy === 'counter',
    size: () => props.size,
    tagsRef: tags,
    value: () => props.value,
  });

const displaySelections = computed((): SelectValue[] =>
  props.overflowStrategy === 'counter' ? visibleSelections.value : props.value,
);

const overflowTagNames = computed((): string[] =>
  overflowSelections.value.map((selection) => selection.name),
);

function handleTagClose(event: MouseEvent, selection: SelectValue): void {
  event.stopPropagation();
  emit('tagClose', selection);
}

function handleOverflowDismiss(tagIndex: number): void {
  const target = overflowSelections.value[tagIndex];

  if (!target) return;

  emit('tagClose', target);
}

function stopPropagation(event: MouseEvent): void {
  event.stopPropagation();
}

const wrapperClasses = computed((): string =>
  clsx(classes.triggerTagsInputWrapper, {
    [classes.triggerTagsInputWrapperEllipsis]:
      props.overflowStrategy === 'counter',
  }),
);

const tagsClasses = computed((): string =>
  clsx(classes.triggerTags, {
    [classes.triggerTagsEllipsis]: props.overflowStrategy === 'counter',
  }),
);

const wrapWrapperClasses = clsx(
  classes.triggerTagsInputWrapper,
  classes.triggerTagsInputWrapperWrap,
);
const tagsInputClass = classes.triggerTagsInput;
</script>

<template>
  <div
    v-if="overflowStrategy === 'wrap'"
    ref="wrapper"
    :class="wrapWrapperClasses"
  >
    <span v-for="selection in value" :key="selection.id">
      <MznTag
        v-if="readOnly"
        :label="selection.name"
        read-only
        :size="size"
        type="static"
      />
      <MznTag
        v-else
        :disabled="disabled"
        :label="selection.name"
        :size="size"
        type="dismissable"
        @close="handleTagClose($event, selection)"
      />
    </span>
    <div v-if="showTextInputAfterTags" :class="tagsInputClass">
      <input
        v-bind="inputProps"
        aria-autocomplete="list"
        :aria-disabled="disabled"
        aria-haspopup="listbox"
        :aria-readonly="readOnly"
        :aria-required="required"
        autocomplete="off"
        :disabled="disabled"
        :readonly="readOnly"
        :required="required"
        type="search"
        :value="searchText"
      />
    </div>
  </div>
  <div v-else ref="wrapper" :class="wrapperClasses">
    <div ref="tags" :class="tagsClasses">
      <MznTagGroup>
        <MznTag
          v-for="selection in displaySelections"
          :key="selection.id"
          :disabled="readOnly ? undefined : disabled"
          :label="selection.name"
          :read-only="readOnly ? true : undefined"
          :size="size"
          :type="readOnly ? 'static' : 'dismissable'"
          @close="handleTagClose($event, selection)"
        />
        <MznOverflowCounterTag
          v-if="overflowSelections.length"
          key="overflow-counter"
          :disabled="disabled"
          :read-only="readOnly"
          :tag-size="size"
          :tags="overflowTagNames"
          @click="stopPropagation"
          @tag-dismiss="handleOverflowDismiss"
        />
      </MznTagGroup>

      <FakeTags />
    </div>

    <div v-if="showTextInputAfterTags" :class="tagsInputClass">
      <input
        v-bind="inputProps"
        aria-autocomplete="list"
        :aria-disabled="disabled"
        aria-haspopup="listbox"
        :aria-readonly="readOnly"
        :aria-required="required"
        autocomplete="off"
        :disabled="disabled"
        :readonly="readOnly"
        :required="required"
        type="search"
        :value="searchText"
      />
    </div>
  </div>
</template>

// packages/react/src/Select/SelectTriggerTags.tsx
import { Ref, forwardRef, useMemo, useRef } from 'react';
import { selectClasses as classes } from '@mezzanine-ui/core/select';
import { TagSize } from '@mezzanine-ui/core/tag';
import { cx } from '../utils/cx';
import { useComposeRefs } from '../hooks/useComposeRefs';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import { useSelectTriggerTags } from './useSelectTriggerTags';
import { SelectValue } from './typings';
import Tag from '../Tag';
import { OverflowCounterTag } from '../OverflowTooltip';
import TagGroup from '../Tag/TagGroup';

export interface SelectTriggerTagsProps {
  disabled?: boolean;
  ellipsis: boolean;
  inputProps?: Omit<
    NativeElementPropsWithoutKeyAndRef<'input'>,
    | 'autoComplete'
    | 'children'
    | 'defaultValue'
    | 'disabled'
    | 'readOnly'
    | 'required'
    | 'type'
    | 'value'
    | `aria-${
        | 'autocomplete'
        | 'disabled'
        | 'haspopup'
        | 'multiline'
        | 'readonly'
        | 'required'}`
  >;
  inputRef?: Ref<HTMLInputElement>;
  onTagClose?: (target: SelectValue) => void;
  readOnly?: boolean;
  required?: boolean;
  searchText?: string;
  size?: TagSize;
  showTextInputAfterTags?: boolean;
  value?: SelectValue[];
}

const SelectTriggerTags = forwardRef<HTMLDivElement, SelectTriggerTagsProps>(
  function SelectTriggerTags(props, ref) {
    const {
      disabled,
      ellipsis,
      inputProps,
      inputRef,
      onTagClose,
      readOnly,
      required,
      searchText,
      size,
      showTextInputAfterTags,
      value = [],
    } = props;
    const wrapperRef = useRef<HTMLDivElement>(null);
    const tagsRef = useRef<HTMLDivElement>(null);
    const composedRef = useComposeRefs([ref, wrapperRef]);

    const { overflowSelections, renderFakeTags, visibleSelections } =
      useSelectTriggerTags({
        enabled: ellipsis,
        containerRef: wrapperRef,
        tagsRef,
        value,
        size,
      });

    const displaySelections = useMemo(
      () => (ellipsis ? visibleSelections : value),
      [ellipsis, value, visibleSelections],
    );

    const tagChildren = useMemo(() => {
      const tags = displaySelections.map((selection) => (
        <Tag
          key={selection.id}
          type="dismissable"
          disabled={disabled}
          onClose={(e) => {
            e.stopPropagation();
            onTagClose?.(selection);
          }}
          readOnly={readOnly}
          size={size}
          label={selection.name}
        />
      ));

      if (ellipsis && overflowSelections.length) {
        tags.push(
          <OverflowCounterTag
            key="overflow-counter"
            // TODO: tbc
            // disabled={disabled}
            onClick={(e) => {
              e.stopPropagation();
            }}
            onTagDismiss={(tagIndex) => {
              const target = overflowSelections[tagIndex];

              if (!target) return;

              onTagClose?.(target);
            }}
            tagSize={size}
            tags={overflowSelections.map((selection) => selection.name)}
          />,
        );
      }

      return tags;
    }, [
      disabled,
      displaySelections,
      ellipsis,
      onTagClose,
      overflowSelections,
      readOnly,
      size,
    ]);

    return (
      <div
        ref={composedRef}
        className={cx(classes.triggerTagsInputWrapper, {
          [classes.triggerTagsInputWrapperEllipsis]: ellipsis,
        })}
      >
        <div
          ref={tagsRef}
          className={cx(classes.triggerTags, {
            [classes.triggerTagsEllipsis]: ellipsis,
          })}
        >
          <TagGroup>{tagChildren}</TagGroup>

          {ellipsis ? renderFakeTags() : null}
        </div>

        {showTextInputAfterTags ? (
          <div className={classes.triggerTagsInput}>
            <input
              {...inputProps}
              ref={inputRef}
              aria-autocomplete="list"
              aria-disabled={disabled}
              aria-haspopup="listbox"
              aria-readonly={readOnly}
              aria-required={required}
              autoComplete="off"
              disabled={disabled}
              readOnly={readOnly}
              required={required}
              type="search"
              value={searchText}
            />
          </div>
        ) : null}
      </div>
    );
  },
);

export default SelectTriggerTags;
