// packages/vue/drawer/drawer.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { drawerClasses as classes } from '@mezzanine-ui/core/drawer';
import { DotHorizontalIcon } from '@mezzanine-ui/icons';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';
import clsx from 'clsx';
import { useDocumentEscapeKeyDown } from '../_internal/use-document-escape-key-down';
import { useTopStack } from '../_internal/use-top-stack';
import MznBackdrop from '../backdrop/backdrop.vue';
import MznButton from '../button/button.vue';
import MznClearActions from '../clear-actions/clear-actions.vue';
import MznDropdown from '../dropdown/dropdown.vue';
import MznRadioGroup from '../radio/radio-group.vue';
import MznRadio from '../radio/radio.vue';
import MznSlide from '../transition/slide.vue';
import type { DrawerProps } from './drawer.types';

/**
 * 從螢幕右側滑入的抽屜面板。
 *
 * 以 MznBackdrop 當遮罩、MznSlide 做進出場。可以帶標題列、篩選區（分頁 radio 或
 * 下拉）與底部操作列。多個抽屜同時開著時，Escape 只關最上面那一個。內容區在重新
 * 開啟時會自動重掛，也可以用 `contentKey` 自己控制。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznDrawer } from '@mezzanine-ui/vue/drawer';
 * <\/script>
 *
 * <template>
 *   <MznDrawer :open="open" isHeaderDisplay header-title="詳細資料" @close="open = false">
 *     <p>抽屜內容</p>
 *   </MznDrawer>
 * </template>
 * ```
 *
 * @see MznModal 對話框元件
 * @see MznBackdrop 遮罩層元件
 */
const props = withDefaults(defineProps<DrawerProps>(), {
  bottomGhostActionDisabled: undefined,
  bottomGhostActionIcon: undefined,
  bottomGhostActionIconType: undefined,
  bottomGhostActionLoading: undefined,
  bottomGhostActionSize: undefined,
  bottomGhostActionText: undefined,
  bottomGhostActionVariant: 'base-ghost',
  bottomOnGhostActionClick: undefined,
  bottomOnPrimaryActionClick: undefined,
  bottomOnSecondaryActionClick: undefined,
  bottomPrimaryActionDisabled: undefined,
  bottomPrimaryActionIcon: undefined,
  bottomPrimaryActionIconType: undefined,
  bottomPrimaryActionLoading: undefined,
  bottomPrimaryActionSize: undefined,
  bottomPrimaryActionText: undefined,
  bottomPrimaryActionVariant: 'base-primary',
  bottomSecondaryActionDisabled: undefined,
  bottomSecondaryActionIcon: undefined,
  bottomSecondaryActionIconType: undefined,
  bottomSecondaryActionLoading: undefined,
  bottomSecondaryActionSize: undefined,
  bottomSecondaryActionText: undefined,
  bottomSecondaryActionVariant: 'base-secondary',
  container: undefined,
  contentKey: undefined,
  disableCloseOnBackdropClick: false,
  disableCloseOnEscapeKeyDown: false,
  disablePortal: undefined,
  filterAreaAllRadioLabel: undefined,
  filterAreaCustomButtonLabel: '全部已讀',
  filterAreaDefaultValue: undefined,
  filterAreaIsEmpty: false,
  filterAreaOnCustomButtonClick: undefined,
  filterAreaOnRadioChange: undefined,
  filterAreaOnSelect: undefined,
  filterAreaOptions: () => [],
  filterAreaReadRadioLabel: undefined,
  filterAreaShow: false,
  filterAreaShowUnreadButton: false,
  filterAreaUnreadRadioLabel: undefined,
  filterAreaValue: undefined,
  headerTitle: undefined,
  isBottomDisplay: undefined,
  isHeaderDisplay: undefined,
  open: undefined,
  size: 'medium',
});

const emit = defineEmits<{
  /** Fired when the backdrop itself is clicked. */
  backdropClick: [event: MouseEvent];
  /** Fired when the drawer asks to be closed. */
  close: [];
}>();

defineSlots<{
  /** The drawer's own content. */
  default?: () => unknown;
}>();

const exited = ref(true);
const openCount = ref(0);

/** Counting the openings is what remounts the content when no key was given. */
watch(
  () => props.open,
  (open) => {
    if (open) openCount.value += 1;
  },
  { immediate: true },
);

/** Escape closes only the drawer on top. */
const checkIsOnTheTop = useTopStack(() => Boolean(props.open));

useDocumentEscapeKeyDown(() => {
  if (!props.open || props.disableCloseOnEscapeKeyDown) return undefined;

  return (event: KeyboardEvent) => {
    if (checkIsOnTheTop()) {
      event.stopPropagation();
      emit('close');
    }
  };
});

interface FilterRadio {
  key: string;
  label: string;
  value: string;
}

const filterRadios = computed((): FilterRadio[] => {
  const radios: FilterRadio[] = [];

  if (props.filterAreaAllRadioLabel) {
    radios.push({
      key: 'all',
      label: props.filterAreaAllRadioLabel,
      value: 'all',
    });
  }

  if (props.filterAreaReadRadioLabel) {
    radios.push({
      key: 'read',
      label: props.filterAreaReadRadioLabel,
      value: 'read',
    });
  }

  if (props.filterAreaUnreadRadioLabel && props.filterAreaShowUnreadButton) {
    radios.push({
      key: 'unread',
      label: props.filterAreaUnreadRadioLabel,
      value: 'unread',
    });
  }

  return radios;
});

const hasRadios = computed((): boolean => filterRadios.value.length > 0);

const hasFilterButton = computed(
  (): boolean =>
    props.filterAreaOptions.length > 0 ||
    props.filterAreaOnCustomButtonClick !== undefined,
);

const showFilterArea = computed(
  (): boolean =>
    props.filterAreaShow && (hasRadios.value || hasFilterButton.value),
);

const filterAreaClasses = computed((): string =>
  clsx(classes.filterArea, {
    [classes.filterAreaButtonOnly]: !hasRadios.value && hasFilterButton.value,
  }),
);

/**
 * Bound as objects rather than with `@change` / `@select`, because React hands
 * these straight through — a consumer that gave none leaves the child without
 * a handler at all.
 */
const filterRadioGroupBindings = computed(() => ({
  defaultValue: props.filterAreaDefaultValue ?? 'all',
  onChange: props.filterAreaOnRadioChange,
  size: 'minor' as const,
  type: 'segment' as const,
  value: props.filterAreaValue,
}));

const filterDropdownBindings = computed(() => ({
  onSelect: props.filterAreaOnSelect,
  options: props.filterAreaOptions,
  placement: 'bottom-end' as const,
}));

const hostClasses = computed((): string =>
  clsx(classes.host, classes.right, classes.size(props.size)),
);

const contentKey = computed((): number | string =>
  props.contentKey !== undefined ? props.contentKey : openCount.value,
);

const SLIDE_DURATION = {
  enter: MOTION_DURATION.moderate,
  exit: MOTION_DURATION.moderate,
};
const SLIDE_EASING = {
  enter: MOTION_EASING.entrance,
  exit: MOTION_EASING.exit,
};
</script>

<template>
  <MznBackdrop
    v-if="open || !exited"
    :class="classes.overlay"
    :container="container"
    :disable-close-on-backdrop-click="disableCloseOnBackdropClick"
    :disable-portal="disablePortal"
    :open="open"
    role="presentation"
    @backdrop-click="emit('backdropClick', $event)"
    @close="emit('close')"
  >
    <MznSlide
      :duration="SLIDE_DURATION"
      :easing="SLIDE_EASING"
      :in="open"
      @entered="exited = false"
      @exited="exited = true"
    >
      <div :class="hostClasses">
        <div v-if="isHeaderDisplay" :class="classes.header">
          {{ headerTitle }}
          <MznClearActions @click="emit('close')" />
        </div>

        <div v-if="showFilterArea" :class="filterAreaClasses">
          <MznRadioGroup v-if="hasRadios" v-bind="filterRadioGroupBindings">
            <MznRadio
              v-for="radio in filterRadios"
              :key="radio.key"
              type="segment"
              :value="radio.value"
            >
              {{ radio.label }}
            </MznRadio>
          </MznRadioGroup>
          <template v-if="hasFilterButton">
            <MznDropdown
              v-if="filterAreaOptions.length > 0"
              v-bind="filterDropdownBindings"
            >
              <template #default="trigger">
                <MznButton
                  v-bind="trigger"
                  :icon="DotHorizontalIcon"
                  icon-type="icon-only"
                  size="minor"
                  type="button"
                  variant="base-ghost"
                />
              </template>
            </MznDropdown>
            <MznButton
              v-else
              :disabled="filterAreaIsEmpty"
              size="minor"
              type="button"
              variant="base-ghost"
              @click="filterAreaOnCustomButtonClick?.()"
            >
              {{ filterAreaCustomButtonLabel }}
            </MznButton>
          </template>
        </div>

        <div :key="contentKey" :class="classes.content"><slot /></div>

        <div v-if="isBottomDisplay" :class="classes.bottom">
          <div>
            <MznButton
              v-if="bottomGhostActionText && bottomOnGhostActionClick"
              :disabled="bottomGhostActionDisabled"
              :icon="bottomGhostActionIcon"
              :icon-type="bottomGhostActionIconType"
              :loading="bottomGhostActionLoading"
              :size="bottomGhostActionSize"
              type="button"
              :variant="bottomGhostActionVariant"
              @click="bottomOnGhostActionClick()"
            >
              {{ bottomGhostActionText }}
            </MznButton>
          </div>
          <div :class="classes.bottom__actions">
            <MznButton
              v-if="bottomSecondaryActionText && bottomOnSecondaryActionClick"
              :disabled="bottomSecondaryActionDisabled"
              :icon="bottomSecondaryActionIcon"
              :icon-type="bottomSecondaryActionIconType"
              :loading="bottomSecondaryActionLoading"
              :size="bottomSecondaryActionSize"
              type="button"
              :variant="bottomSecondaryActionVariant"
              @click="bottomOnSecondaryActionClick()"
            >
              {{ bottomSecondaryActionText }}
            </MznButton>
            <MznButton
              v-if="bottomPrimaryActionText && bottomOnPrimaryActionClick"
              :disabled="bottomPrimaryActionDisabled"
              :icon="bottomPrimaryActionIcon"
              :icon-type="bottomPrimaryActionIconType"
              :loading="bottomPrimaryActionLoading"
              :size="bottomPrimaryActionSize"
              type="button"
              :variant="bottomPrimaryActionVariant"
              @click="bottomOnPrimaryActionClick()"
            >
              {{ bottomPrimaryActionText }}
            </MznButton>
          </div>
        </div>
      </div>
    </MznSlide>
  </MznBackdrop>
</template>

// packages/react/src/Drawer/Drawer.tsx
import React, {
  forwardRef,
  useMemo,
  useState,
  type ChangeEventHandler,
} from 'react';
import {
  drawerClasses as classes,
  DrawerSize,
} from '@mezzanine-ui/core/drawer';
import { IconDefinition } from '@mezzanine-ui/icons';
import {
  ButtonIconType,
  ButtonSize,
  ButtonVariant,
} from '@mezzanine-ui/core/button';
import { cx } from '../utils/cx';
import { NativeElementPropsWithoutKeyAndRef } from '../utils/jsx-types';
import Backdrop, { BackdropProps } from '../Backdrop';
import { Slide } from '../Transition';
import { useDocumentEscapeKeyDown } from '../hooks/useDocumentEscapeKeyDown';
import useTopStack from '../hooks/useTopStack';
import ClearActions from '../ClearActions';
import Button from '../Button';
import Radio from '../Radio/Radio';
import RadioGroup from '../Radio/RadioGroup';
import { MOTION_DURATION, MOTION_EASING } from '@mezzanine-ui/system/motion';

export interface DrawerProps
  extends NativeElementPropsWithoutKeyAndRef<'div'>,
    Pick<
      BackdropProps,
      | 'container'
      | 'disableCloseOnBackdropClick'
      | 'disablePortal'
      | 'onBackdropClick'
      | 'onClose'
      | 'open'
    > {
  /**
   * Disabled state for the ghost action button.
   */
  bottomGhostActionDisabled?: boolean;
  /**
   * Icon for the ghost action button.
   */
  bottomGhostActionIcon?: IconDefinition;
  /**
   * Icon type for the ghost action button.
   */
  bottomGhostActionIconType?: ButtonIconType;
  /**
   * Loading state for the ghost action button.
   */
  bottomGhostActionLoading?: boolean;
  /**
   * Size for the ghost action button.
   */
  bottomGhostActionSize?: ButtonSize;
  /**
   * Text for the ghost action button in the bottom action area.
   */
  bottomGhostActionText?: string;
  /**
   * Variant for the ghost action button.
   * @default 'base-ghost'
   */
  bottomGhostActionVariant?: ButtonVariant;
  /**
   * Click handler for the ghost action button in the bottom action area.
   */
  bottomOnGhostActionClick?: VoidFunction;
  /**
   * Click handler for the primary action button in the bottom action area.
   */
  bottomOnPrimaryActionClick?: VoidFunction;
  /**
   * Click handler for the secondary action button in the bottom action area.
   */
  bottomOnSecondaryActionClick?: VoidFunction;
  /**
   * Disabled state for the primary action button.
   */
  bottomPrimaryActionDisabled?: boolean;
  /**
   * Icon for the primary action button.
   */
  bottomPrimaryActionIcon?: IconDefinition;
  /**
   * Icon type for the primary action button.
   */
  bottomPrimaryActionIconType?: ButtonIconType;
  /**
   * Loading state for the primary action button.
   */
  bottomPrimaryActionLoading?: boolean;
  /**
   * Size for the primary action button.
   */
  bottomPrimaryActionSize?: ButtonSize;
  /**
   * Text for the primary action button in the bottom action area.
   */
  bottomPrimaryActionText?: string;
  /**
   * Variant for the primary action button.
   * @default 'base-primary'
   */
  bottomPrimaryActionVariant?: ButtonVariant;
  /**
   * Disabled state for the secondary action button.
   */
  bottomSecondaryActionDisabled?: boolean;
  /**
   * Icon for the secondary action button.
   */
  bottomSecondaryActionIcon?: IconDefinition;
  /**
   * Icon type for the secondary action button.
   */
  bottomSecondaryActionIconType?: ButtonIconType;
  /**
   * Loading state for the secondary action button.
   */
  bottomSecondaryActionLoading?: boolean;
  /**
   * Size for the secondary action button.
   */
  bottomSecondaryActionSize?: ButtonSize;
  /**
   * Text for the secondary action button in the bottom action area.
   */
  bottomSecondaryActionText?: string;
  /**
   * Variant for the secondary action button.
   * @default 'base-secondary'
   */
  bottomSecondaryActionVariant?: ButtonVariant;
  /**
   * The label of the all radio in control bar.
   */
  controlBarAllRadioLabel?: string;
  /**
   * The label of the custom button in control bar.
   */
  controlBarCustomButtonLabel?: string;
  /**
   * The default value of the radio group in control bar.
   */
  controlBarDefaultValue?: string;
  /**
   * Whether the control bar content is empty (for disabling custom button).
   */
  controlBarIsEmpty?: boolean;
  /**
   * The callback function when the custom button is clicked in control bar.
   */
  controlBarOnCustomButtonClick?: VoidFunction;
  /**
   * The callback function when the radio group value changes in control bar.
   */
  controlBarOnRadioChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * The label of the read radio in control bar.
   */
  controlBarReadRadioLabel?: string;
  /**
   * Controls whether to display the control bar.
   * @default false
   */
  controlBarShow?: boolean;
  /**
   * Controls whether to display the unread button in control bar.
   * @default false
   */
  controlBarShowUnreadButton?: boolean;
  /**
   * The label of the unread radio in control bar.
   */
  controlBarUnreadRadioLabel?: string;
  /**
   * The value of the radio group in control bar.
   */
  controlBarValue?: string;
  /**
   * Controls whether to disable closing drawer while escape key down.
   * @default false
   */
  disableCloseOnEscapeKeyDown?: boolean;
  /**
   * Title text displayed in the drawer header.
   */
  headerTitle?: string;
  /**
   * Controls whether to display the bottom action area.
   */
  isBottomDisplay?: boolean;
  /**
   * Controls whether to display the header area.
   */
  isHeaderDisplay?: boolean;
  /**
   * Custom render function for the control bar area.
   * The control bar will be rendered between the header and content areas.
   * If provided, this will override the default control bar rendering and control bar-related props.
   * @returns ReactNode - The custom control bar element
   */
  renderControlBar?: () => React.ReactNode;
  /**
   * Controls the width of the drawer.
   * @default 'medium'
   */
  size?: DrawerSize;
}

const Drawer = forwardRef<HTMLDivElement, DrawerProps>((props, ref) => {
  const {
    bottomGhostActionDisabled,
    bottomGhostActionIcon,
    bottomGhostActionIconType,
    bottomGhostActionLoading,
    bottomGhostActionSize,
    bottomGhostActionText,
    bottomGhostActionVariant = 'base-ghost',
    bottomOnGhostActionClick,
    bottomOnPrimaryActionClick,
    bottomOnSecondaryActionClick,
    bottomPrimaryActionDisabled,
    bottomPrimaryActionIcon,
    bottomPrimaryActionIconType,
    bottomPrimaryActionLoading,
    bottomPrimaryActionSize,
    bottomPrimaryActionText,
    bottomPrimaryActionVariant = 'base-primary',
    bottomSecondaryActionDisabled,
    bottomSecondaryActionIcon,
    bottomSecondaryActionIconType,
    bottomSecondaryActionLoading,
    bottomSecondaryActionSize,
    bottomSecondaryActionText,
    bottomSecondaryActionVariant = 'base-secondary',
    children,
    className,
    container,
    controlBarAllRadioLabel,
    controlBarCustomButtonLabel = '全部已讀',
    controlBarDefaultValue,
    controlBarIsEmpty = false,
    controlBarOnCustomButtonClick,
    controlBarOnRadioChange,
    controlBarReadRadioLabel,
    controlBarShow = false,
    controlBarShowUnreadButton = false,
    controlBarUnreadRadioLabel,
    controlBarValue,
    disableCloseOnBackdropClick = false,
    disableCloseOnEscapeKeyDown = false,
    disablePortal,
    headerTitle,
    isBottomDisplay,
    isHeaderDisplay,
    onBackdropClick,
    onClose,
    open,
    renderControlBar: customRenderControlBar,
    size = 'medium',
    ...rest
  } = props;

  const [exited, setExited] = useState(true);

  /**
   * Escape keydown close: escape will only close the top drawer
   */
  const checkIsOnTheTop = useTopStack(open);

  const renderControlBar = useMemo(() => {
    // If custom renderControlBar is provided, use it
    if (customRenderControlBar) {
      return customRenderControlBar;
    }

    // Default control bar implementation
    if (!controlBarShow) {
      return undefined;
    }

    return () => {
      const radios = [];

      if (controlBarAllRadioLabel) {
        radios.push(
          <Radio key="all" type="segment" value="all">
            {controlBarAllRadioLabel}
          </Radio>,
        );
      }

      if (controlBarReadRadioLabel) {
        radios.push(
          <Radio key="read" type="segment" value="read">
            {controlBarReadRadioLabel}
          </Radio>,
        );
      }

      if (controlBarUnreadRadioLabel && controlBarShowUnreadButton) {
        radios.push(
          <Radio key="unread" type="segment" value="unread">
            {controlBarUnreadRadioLabel}
          </Radio>,
        );
      }

      const hasRadios = radios.length > 0;
      const hasButton = controlBarOnCustomButtonClick !== undefined;

      // Don't render if neither radios nor button are provided
      if (!hasRadios && !hasButton) {
        return null;
      }

      return (
        <div
          className={cx(
            classes.controlBar,
            !hasRadios && hasButton && classes.controlBarButtonOnly,
          )}
        >
          {hasRadios && (
            <RadioGroup
              defaultValue={controlBarDefaultValue ?? 'all'}
              onChange={controlBarOnRadioChange}
              size="minor"
              type="segment"
              value={controlBarValue}
            >
              {radios}
            </RadioGroup>
          )}
          {hasButton && (
            <Button
              disabled={controlBarIsEmpty}
              onClick={controlBarOnCustomButtonClick}
              size="minor"
              type="button"
              variant="base-ghost"
            >
              {controlBarCustomButtonLabel}
            </Button>
          )}
        </div>
      );
    };
  }, [
    controlBarAllRadioLabel,
    controlBarCustomButtonLabel,
    controlBarDefaultValue,
    controlBarIsEmpty,
    controlBarOnCustomButtonClick,
    controlBarOnRadioChange,
    controlBarReadRadioLabel,
    controlBarShow,
    controlBarShowUnreadButton,
    controlBarUnreadRadioLabel,
    controlBarValue,
    customRenderControlBar,
  ]);

  useDocumentEscapeKeyDown(() => {
    if (!open || disableCloseOnEscapeKeyDown || !onClose) {
      return;
    }

    return (event) => {
      if (checkIsOnTheTop()) {
        event.stopPropagation();

        onClose();
      }
    };
  }, [disableCloseOnEscapeKeyDown, checkIsOnTheTop, open, onClose]);

  if (!open && exited) {
    return null;
  }

  return (
    <Backdrop
      className={classes.overlay}
      container={container}
      disableCloseOnBackdropClick={disableCloseOnBackdropClick}
      disablePortal={disablePortal}
      onBackdropClick={onBackdropClick}
      onClose={onClose}
      open={open}
      role="presentation"
    >
      <Slide
        duration={{
          enter: MOTION_DURATION.moderate,
          exit: MOTION_DURATION.moderate,
        }}
        easing={{
          enter: MOTION_EASING.entrance,
          exit: MOTION_EASING.exit,
        }}
        in={open}
        onEntered={() => setExited(false)}
        onExited={() => setExited(true)}
        ref={ref}
      >
        <div
          {...rest}
          className={cx(
            classes.host,
            classes.right,
            classes.size(size),
            className,
          )}
        >
          {isHeaderDisplay && (
            <div className={classes.header}>
              {headerTitle}
              <ClearActions onClick={onClose} />
            </div>
          )}

          {renderControlBar?.()}

          <div className={classes.content}>{children}</div>

          {isBottomDisplay && (
            <div className={classes.bottom}>
              <div>
                {bottomGhostActionText && bottomOnGhostActionClick && (
                  <Button
                    disabled={bottomGhostActionDisabled}
                    icon={bottomGhostActionIcon}
                    iconType={bottomGhostActionIconType}
                    loading={bottomGhostActionLoading}
                    onClick={bottomOnGhostActionClick}
                    size={bottomGhostActionSize}
                    type="button"
                    variant={bottomGhostActionVariant}
                  >
                    {bottomGhostActionText}
                  </Button>
                )}
              </div>
              <div className={classes['bottom__actions']}>
                {bottomSecondaryActionText && bottomOnSecondaryActionClick && (
                  <Button
                    disabled={bottomSecondaryActionDisabled}
                    icon={bottomSecondaryActionIcon}
                    iconType={bottomSecondaryActionIconType}
                    loading={bottomSecondaryActionLoading}
                    onClick={bottomOnSecondaryActionClick}
                    size={bottomSecondaryActionSize}
                    type="button"
                    variant={bottomSecondaryActionVariant}
                  >
                    {bottomSecondaryActionText}
                  </Button>
                )}
                {bottomPrimaryActionText && bottomOnPrimaryActionClick && (
                  <Button
                    disabled={bottomPrimaryActionDisabled}
                    icon={bottomPrimaryActionIcon}
                    iconType={bottomPrimaryActionIconType}
                    loading={bottomPrimaryActionLoading}
                    onClick={bottomOnPrimaryActionClick}
                    size={bottomPrimaryActionSize}
                    type="button"
                    variant={bottomPrimaryActionVariant}
                  >
                    {bottomPrimaryActionText}
                  </Button>
                )}
              </div>
            </div>
          )}
        </div>
      </Slide>
    </Backdrop>
  );
});

export default Drawer;
