// packages/react/src/Radio/RadioGroup.tsx
import { InputCheckSize } from '@mezzanine-ui/core/_internal/input-check';
import { ChangeEventHandler, forwardRef, ReactNode, useMemo } from 'react';
import InputCheckGroup, {
  InputCheckGroupProps,
} from '../_internal/InputCheck/InputCheckGroup';
import { useInputControlValue } from '../Form/useInputControlValue';
import { RadioGroupContext, RadioGroupContextValue } from './RadioGroupContext';
import Radio, { RadioNormalProps, RadioSegmentProps } from './Radio';

export interface RadioGroupNormalOption
  extends Pick<
    RadioNormalProps,
    'disabled' | 'error' | 'icon' | 'hint' | 'withInputConfig'
  > {
  id: string;
  name: string | number;
}

export interface RadioGroupSegmentOption
  extends Pick<
    RadioSegmentProps,
    'disabled' | 'error' | 'icon' | 'hint' | 'withInputConfig'
  > {
  id: string;
  name: string | number;
}

export interface RadioGroupBaseProps
  extends Omit<InputCheckGroupProps, 'onChange' | 'type'> {
  /**
   * The radios in radio group.
   */
  children?: ReactNode;
  /**
   * The default value of radio group.
   */
  defaultValue?: string;
  /**
   * Whether the radio group is disabled.
   * Control the disabled of radios in group if disabled not passed to radio.
   */
  disabled?: boolean;
  /**
   * The name of radio group.
   * Control the name of radios in group if name not passed to radio.
   */
  name?: string;
  /**
   * The onChange of radio group.
   * Will be passed to each radios but composing both instead of overriding.
   */
  onChange?: ChangeEventHandler<HTMLInputElement>;
  /**
   * The size of radio group.
   * Control the size of radios in group if size not passed to radio.
   */
  size?: InputCheckSize;
  /**
   * The value of radio group.
   */
  value?: string;
}

export interface RadioGroupNormalProps extends RadioGroupBaseProps {
  /**
   * The options of radio group.
   * Will be ignored if children passed.
   */
  options?: RadioGroupNormalOption[];
  /**
   * The type of radio group.
   * Control the type of radios in group if type not passed to radio.
   */
  type?: 'radio';
}

export interface RadioGroupSegmentProps extends RadioGroupBaseProps {
  /**
   * The options of radio group.
   * Will be ignored if children passed.
   */
  options?: RadioGroupSegmentOption[];
  /**
   * The type of radio group.
   * Control the type of radios in group if type not passed to radio.
   */
  type: 'segment';
}

export type RadioGroupProps = RadioGroupNormalProps | RadioGroupSegmentProps;

/**
 * The react component for `mezzanine` radio group.
 */
const RadioGroup = forwardRef<HTMLDivElement, RadioGroupProps>(
  function RadioGroup(props, ref) {
    const {
      children: childrenProp,
      defaultValue,
      disabled,
      name,
      options = [],
      onChange: onChangeProp,
      size,
      type,
      value: valueProp,
      ...rest
    } = props;
    const [value, onChange] = useInputControlValue({
      defaultValue,
      onChange: onChangeProp,
      value: valueProp,
    });
    const context: RadioGroupContextValue = useMemo(
      () => ({
        disabled,
        name,
        onChange,
        size,
        type,
        value,
      }),
      [disabled, name, onChange, size, type, value],
    );

    const children =
      childrenProp ||
      options.map((option) => (
        <Radio
          key={option.id}
          disabled={option.disabled}
          error={option.error}
          hint={option.hint}
          value={option.id}
          withInputConfig={option.withInputConfig}
        >
          {option.name}
        </Radio>
      ));

    return (
      <RadioGroupContext.Provider value={context}>
        <InputCheckGroup
          {...rest}
          ref={ref}
          role="radiogroup"
          segmentedStyle={type === 'segment'}
          size={size}
        >
          {children}
        </InputCheckGroup>
      </RadioGroupContext.Provider>
    );
  },
);

export default RadioGroup;

// packages/vue/radio/radio-group.vue
<script setup lang="ts">
import { computed, provide } from 'vue';
import type { InputCheckSize } from '@mezzanine-ui/core/_internal/input-check';
import MznInputCheckGroup from '../_internal/input-check-group.vue';
import { useInputControlValue } from '../_internal/use-input-control-value';
import MznRadio from './radio.vue';
import { radioGroupKey } from './radio-group-context';
import type { RadioGroupContextValue } from './radio-group-context';
import type { RadioGroupProps } from './radio-group.types';

/**
 * 一組共用 name 與選取值的單選按鈕。
 *
 * 以 `options` 或預設 slot 提供內容，slot 優先；群組的 `disabled`、`name`、`size`
 * 與 `type` 會在子項目沒有自己設定時生效。
 *
 * @example
 * ```vue
 * <script setup lang="ts">
 * import { MznRadioGroup } from '@mezzanine-ui/vue/radio';
 * <\/script>
 *
 * <template>
 *   <MznRadioGroup name="gender" :options="options" :value="value" @change="onChange" />
 * </template>
 * ```
 *
 * @see MznRadio 群組內的單選按鈕
 */
const props = withDefaults(defineProps<RadioGroupProps>(), {
  defaultValue: undefined,
  disabled: undefined,
  name: undefined,
  options: () => [],
  orientation: undefined,
  segmentedStyle: undefined,
  size: undefined,
  type: undefined,
  value: undefined,
});

const emit = defineEmits<{
  /**
   * The onChange of radio group.
   * Will be passed to each radios but composing both instead of overriding.
   */
  change: [event: Event];
}>();

const slots = defineSlots<{
  /** The radios in radio group. */
  default?: () => unknown;
}>();

const { onChange, value } = useInputControlValue({
  defaultValue: () => props.defaultValue,
  onChange: (event) => emit('change', event),
  value: () => props.value,
});

provide(
  radioGroupKey,
  computed(
    (): RadioGroupContextValue => ({
      disabled: props.disabled,
      name: props.name,
      onChange,
      size: props.size as InputCheckSize | undefined,
      type: props.type,
      value: value.value,
    }),
  ),
);

const hasChildren = computed((): boolean => Boolean(slots.default));
</script>

<template>
  <MznInputCheckGroup
    :orientation="orientation"
    role="radiogroup"
    :segmented-style="type === 'segment'"
    :size="size"
  >
    <slot v-if="hasChildren" />
    <MznRadio
      v-for="option in options"
      v-else
      :key="option.id"
      :disabled="option.disabled"
      :error="option.error"
      :hint="option.hint"
      :value="option.id"
      :with-input-config="option.withInputConfig"
    >
      {{ option.name }}
    </MznRadio>
  </MznInputCheckGroup>
</template>
